### ISSUE TITLE
Recipes not using Ore Dictionary Iron plates

### ISSUE THREAD

**Issue by trbocode** [TechReborn/TechReborn#1003]
Same issue as yesterday.Many machines need IC2 plates for some reason. This appears to be a very easy fix- Just edit getStack(IC2Duplicates.REFINED_IRON) to plateIron.

**Comment by modmuss50** [comment]
What version are you using?

**Comment by modmuss50** [comment]
Im not 100% sure what you mean?

**Comment by trbocode** [comment]
Newest version, 2.1.9 on 1.10, was used. The problem that was supossedly fixed in 3ee81c2 wasn't actually fixed for Iron plates. I managed to fix it by editing getStack(IC2Duplicates.REFINED_IRON)  to "plateIron" in the recipe source code files, but i'm unaware if that broke anything else.

**Comment by DarkHelmet433** [comment]
FWIW I'm still seeing this on 2.1.11.209 on 1.10.2 in FTB Beyond.  Iron Fences won't craft with oredict plateIron.

**Comment by DarkHelmet433** [comment]
I grabbed the unreleased Jenkins build 216 and I can confirm that it does work as expected.

**Comment by modmuss50** [comment]
I will push an update to curse soon. thanks for testing 👍
