### ISSUE TITLE
Industrial Grinder broken after bd4b03 and d126eda 

### ISSUE THREAD

**Issue by trbocode** [TechReborn/TechReborn#1004]
Stuck on 100%- Tested on multiple versions (Non releases were compiled using gradle and not gradlew if that makes a difference). Both 2.1.8 releases had the bug. bd4b03b itself wasn't tested, but 1ea621b and d126eda were. 
The grinder was built as per old gregtech rules and the overlay indeed disappears.

**Comment by modmuss50** [comment]
Ok, can confirm this.
