### ISSUE TITLE
Recipes removed?

### ISSUE THREAD

**Issue by Staegrin** [TechReborn/TechReborn#1005]
Updated to version TechReborn-1.10.2-2.1.8.193-universal. Seeing small piles of dust piling up in my storage. Turns out almost all the recipes using small piles to make regular dust piles are no longer there.

Ender eye dust, ender pearl dust, red garnet dust, saw dust, yellow garnet dust can still be made from their small pile version.
![2017-03-12_00 48 50](https://cloud.githubusercontent.com/assets/8494635/23827838/c4bcdeac-06bd-11e7-8497-ce0d64264b90.png)
![2017-03-12_00 48 55](https://cloud.githubusercontent.com/assets/8494635/23827839/c4bd337a-06bd-11e7-80f4-736b465df787.png)
![2017-03-12_00 49 05](https://cloud.githubusercontent.com/assets/8494635/23827837/c4bc87c2-06bd-11e7-8e15-ae22b09e13bd.png)

**Comment by modmuss50** [comment]
Huh, im not sure why they broke, I changed them to use the ore dict. I will look into it.
