### ISSUE TITLE
[1.11.2] Oregen config not being respected in some situations

### ISSUE THREAD

**Issue by Rosethorns** [TechReborn/TechReborn#1007]
Description:
It appears that aspects of the oregen config are not accurately represent or not being represented at all.
In the first case the height of copper ore is not being respected in any capacity.
  blockName: tile.techreborn.ore2
      blockNiceName: Copper
      meta: 0
      veinSize: 15
      veinsPerChunk: 30
      minYHeight: 50
      maxYHeight: 60
      shouldSpawn: true

http://imgur.com/a/Rxud9
Oddly 10-40 seemed to actually be respected in another attempt.

In the second case. Vein size was tested. 3 veins per chunk
This was the result http://imgur.com/g2Hqmhw

Reproduce:
1. change copper configs to those listed above
2. create new world
3. try to find copper at around y 55

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
TechReborn: 2.1.9-82

**Comment by modmuss50** [comment]
The issue with small vein size is because we use Minecrafts vein generator and it doesn't support smaller sizes. The other issues I can look into.

**Comment by modmuss50** [comment]
4 is the smallest vein size that the vanilla ore generator can handle, without a bit of extra work I cannot make it go smaller. If you need to be able to have smaller than 4 vein sizes let me know and I can add it. 

But the height issue has been fixed.

**Comment by MrNinja93** [comment]
In regards to vein size not being able to go lower than 4 could there be a "range" value put into the configs to indicate that it can't go lower than 4? (and maybe any others that are range dependant)
