### ISSUE TITLE
[1.11.2] Config crash - gem tools/armor

### ISSUE THREAD

**Issue by Terpo** [TechReborn/TechReborn#1008]
Report: https://gist.github.com/Terpo/25152e352a55d64c47b29eca280b462d
TechReborn-1.11.2-2.1.10.88-universal.jar
RebornCore-1.11.2-2.13.5.42-universal.jar

Setting this setting to false will result in a preInit crash.    
# Should the gem tools and armor be added to the game
    B:"Gem tools and armor"=true

**Comment by modmuss50** [comment]
Huh, I thought I fixed this a while ago. I will take another look
