### ISSUE TITLE
Ore Spawn Glitch

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1009]
are you sure you guys fixed ore spawn on world generation?
![2017-03-15_22 00 42](https://cloud.githubusercontent.com/assets/24831406/23966047/a9fde23e-09c2-11e7-84fa-cd17d1ad8d5b.png)
![2017-03-15_22 00 51](https://cloud.githubusercontent.com/assets/24831406/23966049/aac39d80-09c2-11e7-9e30-596623f383fa.png)

it is very bad, there are too many tin and copper ores
using game 1.11.2 forge 2259 RebornCore-1.11.2-2.13.5.42 TechReborn-1.11.2-2.1.10.88

**Comment by modmuss50** [comment]
oh, can you send me your ores.hjson file?

**Comment by modmuss50** [comment]
its location in the techreborn folder in the config directory

**Comment by ghost** [comment]
sure, here it is
[ores.hjson.txt](https://github.com/TechReborn/TechReborn/files/845720/ores.hjson.txt)
tin ore spawn disabled in it because when i see too many tin ores i just wanted to disable it in techreborn config because there are also tin ores from Forestry mod. **But**, it didn't work. I disabled tin ore spawn in ores.hjson file and i created new world, it is still like this in pictures.

**Comment by modmuss50** [comment]
Ok, thanks I will take a look

**Comment by ghost** [comment]
thank you. i'm waiting for a new release about this. get luck with! hope it ll be fixed

**Comment by FluffyCloud** [comment]
Doesn't look like this on the dev test server... but we are using ATG?

![2017-03-15_15 13 08](https://cloud.githubusercontent.com/assets/9650826/23966544/1e459b2c-0992-11e7-95a0-80a70d59c117.png)

**Comment by modmuss50** [comment]
Yeah, I can test in about an hour on a normal world.

**Comment by ghost** [comment]
ah yes, i am also using ATG. is it problem?
and, if i can disable tin and copper spawn, it is ok. because Forestry copper and tins are spawning fine.
thanks.

**Comment by modmuss50** [comment]
Can you close your game/stop the server, delete the ores.hjson file and try again in a new world?

**Comment by kenijey** [comment]
okay let me do it. give me 5 mins i will edit this comment

**Comment by ghost** [comment]
okay let me do it. give me 5 mins i will edit this comment
looks like same :(
![2017-03-15_22 32 14](https://cloud.githubusercontent.com/assets/24831406/23967281/f6a292fc-09c6-11e7-8728-8a804ef62633.png)

**Comment by modmuss50** [comment]
Humm, ok. I will have to take a look in a bit then. Thanks for trying.

**Comment by ghost** [comment]
okay. i will help my best.

**Comment by ghost** [comment]
and ah, i tried it without ATG because of maybe it effects as i think, but nothing different. ATG doesn't effect. it is new created world without ATG. maybe you wanna know..
![2017-03-15_22 36 02](https://cloud.githubusercontent.com/assets/24831406/23967404/77f0fd08-09c7-11e7-9f1c-acb6d19f5a57.png)

**Comment by modmuss50** [comment]
![java_2017-03-15_20-16-56](https://cloud.githubusercontent.com/assets/4324090/23968864/694c82b4-09bc-11e7-8fb9-983d8a8458f1.png)

Looks ok to me. Latest version of everything.

**Comment by modmuss50** [comment]
use the command `/trdev clear`

**Comment by ghost** [comment]
so? it is my problem? =c

**Comment by modmuss50** [comment]
Im not sure tbh, I will leave it open for a bit to see if someone else has the same issue.

**Comment by ghost** [comment]
it is amazing :D 
hey, is there a way to disable the tin and copper ore in ores.hjson file? because i tried disabling tin ore but it didn't work. is it my problem again? thanks.
![2017-03-15_23 28 39](https://cloud.githubusercontent.com/assets/24831406/23969331/cc329c1c-09ce-11e7-8101-450be4074b71.png)

**Comment by modmuss50** [comment]
set should spawn to false in the config file.

**Comment by ghost** [comment]
oh okay, it is not fault of techreborn. i deleted techreborn, created new world and looked the underground again, i see too many redstone ores. i think another mod causes it. i hope i will find it :)

**Comment by ghost** [comment]
omg... i start inspecting the bug with deleting all the config files, then created a new world and this problem solved. i really wonder what is my fault :( i really need help

**Comment by ghost** [comment]
hey, @modmuss50 , i did a mistake yesterday. and i inspected now this bug more, and i found the problem. when i delete techreborn folder in config, this problem is getting solved. just letting you know.
