### ISSUE TITLE
Locales feature

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1011]
Can you add formatter (pattern) for fluids cells, bukkits and etc? Cuz on differend languages can be different order or words.. 
ex:  tr.fuildcells.pattern={$cell} {$fluid}

![image](https://cloud.githubusercontent.com/assets/20370136/24021673/1e1d07d0-0ab3-11e7-997c-19cc0f19aca9.png)

**Comment by ghost** [comment]
Also some words are long and can't fit in gui

![image](https://cloud.githubusercontent.com/assets/20370136/24021733/6c874dd6-0ab3-11e7-9bdd-49ea5f2c86be.png)

**Comment by ghost** [comment]
ALSO add localization for these strings
![image](https://cloud.githubusercontent.com/assets/20370136/24022091/65a366ba-0ab5-11e7-8b59-e22978fd88fd.png)

**Comment by ghost** [comment]
huh, can you fix names of variables? 
1 - has prefix "techreborn"
2 - doesn't have techreborn prefix, but starts with upper case
3 - none of this
![image](https://cloud.githubusercontent.com/assets/20370136/24022484/c479e658-0ab7-11e7-978b-fea4fc3b7816.png)

**Comment by Prospector** [comment]
Not much I can do about the names not fitting in the GUIs, but eventually that gui will get redone to fit it

**Comment by modmuss50** [comment]
Im not sure there is a lot we can do about the gui text spilling over the side. And the lang file can be cleaned up over time, but its not causing an issue.
