### ISSUE TITLE
peridot doesn't generate

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#1014]
It seems peridot doesn't generate in the ender. I had searshed it for a long time and didn't find any clusters of peridot, while I didn't have difficulties to find tungstene and sodalite. I use the last version for 1.10.2

**Comment by drcrazy** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/1382352/30131849-f5868dc8-9356-11e7-9adf-925fd1d03f25.png)

**Comment by 0Navis0** [comment]
Simply because it has already been solved since a long time.
