### ISSUE TITLE
The Iron Furnace is not quicker than the vanilla furnace

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1015]
Version: **1.11.2**. I am using the latest version of TechReborn.

I just did a small test with the vanilla furnace and TechReborn’s iron furnace, and here are the results:
The vanilla furnace smelts eight items per piece of coal, and the iron furnace smelts ten items per piece of coal. This is all good, but the problem is that it did _not_ smelt the items quicker, which the IC2 iron furnace does.

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/TechReborn/commit/21dd44def6ff6527e80a3ab31e9fee648b94d400

**Comment by ghost** [comment]
@modmuss50 Thanks!
