### ISSUE TITLE
Fuel is put into the wrong slot when using hoppers with the iron furnace

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1016]
Coal and other fuel items go into the output slot or the top slot (the slot for items that should be smelted/cooked), rather than the bottom slot (the fuel slot) when put in a hopper that is connected to the iron furnace, as opposed to the vanilla furnace, which puts fuel in the right slots.

I am using the latest TechReborn version for 1.11.2.

**Comment by codewarrior0** [comment]
Furthermore, a hopper beneath an Iron Furnace will extract the furnace's fuel instead of its outputs.

TechReborn-1.11.2-2.1.10.88-universal.jar
