### ISSUE TITLE
5231e1d wasn't applied to the 1.10 branch

### ISSUE THREAD

**Issue by trbocode** [TechReborn/TechReborn#1017]
Meaning issue #1004 still exists there

**Comment by modmuss50** [comment]
Thanks for spotting that, should be an easy fix

**Comment by ReillyBrogan** [comment]
@trbocode Take a look at my comment in #1020 for a fixed jar that you can use until modmuss50 fixes the 1.10.2 branch.

**Comment by trbocode** [comment]
@ReillyBrogan Thanks, but I already had a jar of my own.

**Comment by modmuss50** [comment]
Done.
