### ISSUE TITLE
MT Integration Support

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#1018]
I'm now at the stage of using the new MT script integration but only getting an error.

Plate Stuff.zs:88 > a method available but none matches the parameters (minetweaker.oredict.IOreDictEntry, minetweaker.item.IIngredient[])
This is usually an error in your script, not in the mod
addShapeless(ZenTypeNative, ZenTypeArrayBasic, Optional ZenTypeNative, Optional ZenTypeNative )

What is the correct format on how to use the new MT integrations given some machines have a 3*3 grid in the interface??
Current script file: https://gist.github.com/the-creamster/bd88eed32d5ff7c3291477889c0f6bc0

**Comment by modmuss50** [comment]
it was the same as vanilla crafting, If not I can take a look

**Comment by ghost** [comment]
I don't believe that minetweaker will ever let you use oredict entries for output.

**Comment by the-creamster** [comment]
Firstly i made a classic MT mistake(note: {}=<>, but due to github there not displaying):
"
mods.techreborn.rollingMachine.addShaped(ore:plateIron*4,
    [[null, null, null],
    [null, null, null],
    [{ore:ingotIron}, {ore:ingotIron}, {ore:ingotIron}]]);
"

when it should be(crafted item reference aside):
"
mods.techreborn.rollingMachine.addShaped({ore:plateIron}*4,
    [[null, null, null],
    [null, null, null],
    [{ore:ingotIron}, {ore:ingotIron}, {ore:ingotIron}]]);
"

But it's still not working even when directly referencing a TR iron plate so it may be something up with your integration and/or MT itself.
"
mods.techreborn.rollingMachine.addShaped({techreborn:plates}*4,
    [[null, null, null],
    [null, null, null],
    [{ore:ingotIron} {ore:ingotIron}, {ore:ingotIron}]]);
"

Secondly, was the MT integration tested before released? If not i'll be able to test them sorta thoroughly as i found a few recipes that don't quite seem right that should be fixed your end. i can list them for you if you want??

Edit:
the 2 plates i can see atm are;
1. A single IC2 lapis plate(ore dict to any dye; compressor)
2. A single Redstone plate(uses the extra utilities 2 Resonating Redstone Crystal; compressor)

**Comment by drcrazy** [comment]
Duplicate for #1251
