### ISSUE TITLE
Superconductors won't superconduct due to how IC2 works

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#102]
Self explainatory, that is due to the fact IC2 hardcoded the minimum value of loss being 0.0001 eu, and anything lower will return this value...

A simple solution is to use UE or Mekanism or a custom net for the superconductor to make it lossless, and push EU when needed to other machines. You might need a custom e-net anyway as you guys wanted to make TechReborn being independent :/

**Comment by modmuss50** [comment]
I was going to write a custom net. I need to think out how its going to work.

**Comment by Carbon-Ghost** [comment]
Kk, and this is more an interaction bug, so yeah, we need to speak more about how it will work, here is my suggestion : 

- If IC2 classic or exp not detected
Then load net to all cables
-else hide TechReborn cables or IC2 ones ( dunno how you will do it ) and load normal IC2 enet to all cables except Superconductors. 

By default superconductors will only use eu and push eu to machines ^ ^

**Comment by modmuss50** [comment]
Are we going to add theis?

**Comment by Carbon-Ghost** [comment]
well you wanted to add your own cables anyway with your own E-net, so if you do so, then it might not be a bad idea also doing a superconductor cable ^^

**Comment by modmuss50** [comment]
Im still not sure on this one, There might be a way around the minimum loss.

**Comment by Carbon-Ghost** [comment]
It might require you modifying some important classes I think, though if you want to add your own cables, the "If IC2 classic or exp not detected Then load net to all cables -else hide TechReborn cables or IC2 ones ( dunno how you will do it ) and load normal IC2 enet to all cables except Superconductors. " suggestion would be better anyway ^^

**Comment by modmuss50** [comment]
That value is soo small it wont even matter right?

**Comment by Carbon-Ghost** [comment]
Well it won't be a superconductor then xD It's the same logic with the glass fibre then :p

**Comment by modmuss50** [comment]
No one will notice. You would need 1000 cables to loose just 1 eu.

**Comment by Carbon-Ghost** [comment]
well again, the best solution would be to do it like mekanism, by using my suggestion ^^'' If you do a standalone config for cables and stuff you will end up using a separate e-net, so logically you will be able to make superconductor truly superconducting, then if IC2 is loaded, just hide your cables ( recipes ) except for superconductor, basically your e-net will still be functional, just all cables not crafteable except superconductor, which will work, and if it detects IC2 net stuff, it will push/pull the EU ( it's possible, that's how mekanism is doing it and how they made their cables superconductors ).
