### ISSUE TITLE
Issues with Industrial Grinder (Sheldonite recipe does not grind)

### ISSUE THREAD

**Issue by MathijsNL** [TechReborn/TechReborn#1020]
Hi there,

I am encountering an issue with the industrial grinder when grinding some ores. Gold ore and Sheldonite ore are not working, didn't test all possible recipes.

As you can see in the picture it goes to 100% and then stops. This is in FTB Beyond, running TechReborn version TechReborn-1.10.2-2.1.10.207

![sheldonite](https://cloud.githubusercontent.com/assets/1612886/24110692/68ec640c-0d94-11e7-908f-b8d9baee7245.png)

Since the machine and the ores are both from this mod I thought this was the right place to post the issue.

**Comment by TheMilso** [comment]
Im having same along with a lot of other ores.
Playing FTB beyond pack on MC 1.10

but found this:
https://github.com/TechReborn/TechReborn/issues/1017

Looks like this was already an issue but they missed the fix in 1.10 branch.

**Comment by ReillyBrogan** [comment]
It doesn't look like the mod author has yet had a chance to update the 1.10 branch so I took the liberty of doing it myself and built a new jar with the fixes:

[Fixed Jar](https://drive.google.com/file/d/0B9Ese0JWE3QAdVZSYS1TQ21sWEE/view?usp=sharing)

To install just delete the existing TechReborn jar from the mods folder and drop this version in. If you play on a server it is probable that only the server needs the fixed jar but I haven't tested it.

Please note that this jar is provided without any support and only provided for those who don't want to wait until modmuss50 updates the mod. Don't create any issues here for any bugs encountered with the modified jar unless you can reproduce with the official one.

**Comment by modmuss50** [comment]
Sorry about not looking at issues in a while I've been busy working on other projects

**Comment by TheMilso** [comment]
Testing now.
FYI so far I had to put version on client as well as getting version mismatch error. (it may have been compiled vrs a different version then FTB beyond uses (207))

Thanks.

**Comment by davqvist** [comment]
I just got a report from a user about this bug as well. It seems Sheldonite works fine with Mercury but doesn't work with Water.

**Comment by Vectrobe** [comment]
I will add this here to clarify; the fluid gauge in the GUI doesn't actually update at all once it's been filled, so to be sure you should wrench the grinder and place it back and then re-fill it with water.

**Comment by drcrazy** [comment]
Not reproducible in 1.12.1

![image](https://user-images.githubusercontent.com/1382352/29733460-dc89275a-89f5-11e7-85db-cd11c3b4bfaa.png)

**Comment by Vectrobe** [comment]
@drcrazy water is where the problem lies, did you test that?

**Comment by drcrazy** [comment]
tested with water also
![image](https://user-images.githubusercontent.com/1382352/29742214-96a23d56-8a83-11e7-8fdd-56691d22cfab.png)

**Comment by drcrazy** [comment]
The only Industrial Grinder specific issue in 1.12.1 as for now is that tank level is not updated properly
