### ISSUE TITLE
Many recipes only use uncraftable IC2 Iridium Reinforced Plates

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#1021]
https://forum.feed-the-beast.com/threads/many-recipes-only-use-uncraftable-ic2-iridium-reinforced-plates.222504/

**Comment by LuigiHutch** [comment]
As TR for 1.10 is only recieving limited support, im guessing there are no plans to fix this for 1.10.2 and ftb beyond?

**Comment by modmuss50** [comment]
I might fix some the beyond recipe issues still.
