### ISSUE TITLE
[1.11.2] TechReborn 2.1.10.88 Crash with Matter Fabricator

### ISSUE THREAD

**Issue by Valchap** [TechReborn/TechReborn#1023]
When I put other than scrap in a Matter Fabricator the game crash and the map is corrupted.

It's a null pointer exception.

**Comment by modmuss50** [comment]
I need the log

**Comment by Valchap** [comment]
The log : [Crash.txt](https://github.com/TechReborn/TechReborn/files/862632/Crash.txt)

**Comment by drcrazy** [comment]
Same here with Minecraft 1.11.2 and TechReborn-1.11.2-2.1.10.96-universal

Log:
[00:46:14] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.util.ReportedException: Ticking block entity
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[cch.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
> Caused by: java.lang.NullPointerException
> 	at techreborn.init.IC2Duplicates.hasIC2Stack(IC2Duplicates.java:106) ~[IC2Duplicates.class:?]
> 	at techreborn.tiles.TileMatterFabricator.getValue(TileMatterFabricator.java:173) ~[TileMatterFabricator.class:?]
> 	at techreborn.tiles.TileMatterFabricator.updateEntity(TileMatterFabricator.java:118) ~[TileMatterFabricator.class:?]
> 	at reborncore.common.tile.TileLegacyMachineBase.func_73660_a(TileLegacyMachineBase.java:68) ~[TileLegacyMachineBase.class:?]
> 	at reborncore.common.powerSystem.TilePowerAcceptor.func_73660_a(TilePowerAcceptor.java:64) ~[TilePowerAcceptor.class:?]
> 	at net.minecraft.world.World.func_72939_s(World.java:1801) ~[ajs.class:?]
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
> 	... 4 more
