### ISSUE TITLE
[1.11.2] TechReborn Axes not properly registered as axe tool

### ISSUE THREAD

**Issue by Rosethorns** [TechReborn/TechReborn#1027]
Description:
This was discovered via a mod interaction on the Raxpack mod pack. But holds true elsewhere.
The TechReborn axes output the wrong result when cutting down logs with BWM installed as BWM recognizes them as not being axes. This does not appear to be specifically a BWM interaction as other modded axes are working correctly.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2260
Techreborn: 2.1.10.88

**Comment by modmuss50** [comment]
Yeah, I see whats up.

**Comment by Prospector** [comment]
Oh yeah, when we first ported to 1.9 forge broke the ItemAxe code so we couldn't use it. Guess we never fixed it.
