### ISSUE TITLE
iron fence block texture missing

### ISSUE THREAD

**Issue by L0laapk3** [TechReborn/TechReborn#1028]
I don't know if this is already fixed or not, so I figured I'd report it just to make sure.

I just updated my server to the lastest stable release of techreborn for 1.10.2 (2.1.10.207), And the iron fence block texture appears to be missing:

http://imgur.com/JVYfa5D

**Comment by drcrazy** [comment]
Not reproducible in 1.12.1

![image](https://user-images.githubusercontent.com/1382352/29733224-d2387ec8-89f4-11e7-8ec0-fb37ce94d556.png)
