### ISSUE TITLE
[1.10.2] Rendering Crash

### ISSUE THREAD

**Issue by DoughnutDev** [TechReborn/TechReborn#1029]
I am using all the latest versions of TechReborn RebornCore and Forge. Whenever I hover over a machine in JEI or a creative tab I get this crash https://hastebin.com/nasameqofa.pas. I also get this crash when I right click on a machine after I place it https://hastebin.com/inaciziyot.pas

**Comment by modmuss50** [comment]
The quick fix for this is to delete the power priority file in the team reborn folder.

**Comment by modmuss50** [comment]
Links are dead. Closing. Reopen if you can make this happen in 1.12. Thanks
