### ISSUE TITLE
Blast Furnace req temp for Iron/pyrite is wrong

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#103]
Currently iron and pyrite both require 15000 degrees to smelt in the blast furnace, whereas steel is only 1000 degrees.

(The ores are red because Galacticraft/Nether versions)

![captrrure](https://cloud.githubusercontent.com/assets/7843312/9159749/f28dffd8-3f71-11e5-8b7b-7f913db952bd.PNG)
![capdture](https://cloud.githubusercontent.com/assets/7843312/9159756/1b174fe0-3f72-11e5-9b61-d8302eef9975.PNG)

**Comment by modmuss50** [comment]
should they both be 1000?

**Comment by TheQuantumGeneral** [comment]
From old Gregtech values yeah, both 1000 kelvin

**Comment by modmuss50** [comment]
ok thanks
