### ISSUE TITLE
Rubber Sapling doesn't have a texture

### ISSUE THREAD

**Issue by Lethann** [TechReborn/TechReborn#1030]
TechReborn 2.1.10.207
Custom Modpack

Rubber saplings show as the pink/black texture missing. This is on both Single Player and our private server.

I'd list all our mods but don't know how to get a list of them without manually typing... but here are a few that might be conflicting:

BiomesOPlenty-1.10.2-5.0.0.2162
Forestry 1.10.2-5.2.17.368
Natura-1.10.2-4.1.0.24

**Comment by Prospector** [comment]
dupe of #943

**Comment by Lethann** [comment]
oops sorry. I searched but the other one didn't show up.
