### ISSUE TITLE
Client Crash when breaking Copper Wire

### ISSUE THREAD

**Issue by kitsushadow** [TechReborn/TechReborn#1031]
https://paste.ee/p/LfktM

I tried to break it with a pick and crashed.

**Comment by Captainaviator** [comment]
another client, same server and same wire - https://pastebin.com/tfsBK7JB

something else to note, is that I have WIT installed (WAILA alternative), and this wire is the only block that doesn't show anything.

**Comment by Prospector** [comment]
dupe of #987
