### ISSUE TITLE
[1.10.2] OreDict Machine Frames

### ISSUE THREAD

**Issue by DoughnutDev** [TechReborn/TechReborn#1032]
Would it be possible to have the machine frames from IC2 and TechReborn be the same or disable one when duplication setting is set to true, because when you craft a basic machine frame it gives you a TR one and not an IC2 one and the IC2 macerator will not craft with the TR machine frame. Here is a gif of what I mean https://gyazo.com/f2e8151b3e268405446c5861eea7d8d2

**Comment by drcrazy** [comment]
Fixed in 1.12.1
