### ISSUE TITLE
Construction Foam

### ISSUE THREAD

**Issue by Scorch-Mechanic** [TechReborn/TechReborn#1034]
Yes, good old fashioned CF just like in the olden golden days of IC2. Personally I don't have a strong preference for the IC2 version over the Experimental version (I liked both, honestly). I particularly enjoyed laying out whole buildings with scaffolding and then turning them permanent with a few quick blurts from the CF sprayer.

**Comment by modmuss50** [comment]
I dont think we are going to add it. We are trying to move away from just copying ic2 1 to 1 and adding our ideas. Something similar may happen.
