### ISSUE TITLE
Cables do not work with Forge Energy or TESLA

### ISSUE THREAD

**Issue by Valchap** [TechReborn/TechReborn#1038]
More explanations here: raoulvdberge/refinedstorage#1141

RELATED ISSUES:
https://github.com/TechReborn/TechReborn/issues/984 - [1.10.2]/[1.11.2] Some kind of incompatibilities with Forge Energy System

**Comment by modmuss50** [comment]
This is waiting on MCMP 2 to come out.

**Comment by modmuss50** [comment]
Closing this as I'm going to rewrite the powernet after we have the upgrades in.
