### ISSUE TITLE
Alloy furnace crash

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#104]
Had an alloy furnace yesterday, didn't work so I left it. 
Updated today because you added alloy furnace logic, set it to make cupronickel, walked away.
Placed a macerator and the server crashed. 

tl;dr placing an ic2 machine while the basic alloy furnace was working crashed server, unsure if it's a coincidence. 

Here's a log
http://pastebin.com/sMnmER07

**Comment by LordMonoxide** [comment]
The alloy furnace crashes when it finishes processing everything that's in it.  (It also doesn't use the items in the right slot.)

**Comment by modmuss50** [comment]
Thanks for braking everything while I'm away :) gonna leave a reminder to fix the input stack size checking here.
