### ISSUE TITLE
[1.10+ Suggestion] Add more materials 

### ISSUE THREAD

**Issue by CrossVas** [TechReborn/TechReborn#1040]
Hey! 
TechReborn is a "mod designed by the ideals of GregTech 2"
And I thought that it would be cool to add Stainless Steel Concept, made by mixing 6 Iron, 1 Nickel, 1 Chrome and 1 Manganese Dust to get 9 Stainless Steel Dust, which can then be smolten at 2000 in the Blast Furnace. It also will be great to add some ingots (and plates) like:
^Stainless Steel Ingot (+ Plate); 
Cupronickel Ingot = 1 Nickel + 1 Copper ingot in Alloy Furnace to get 2;
and Nichrome Ingot = 4 Nickel Dust + 1 Chrome Dust to get 5 dusts [Shapeless Craft] or 4 Nickel Dust + 1 Chrome Dust to get 5 ingots in Alloy Furnace;

If you decide to add this you also need to change the craft of Nichrome Heating Coil to something like [this](http://i.imgur.com/0ZNLndM.png) and Cupronickel Heating Coil like [this](http://i.imgur.com/jK87OcL.png).

It's a good opportunity for those who want to make TechReborn a little bit harder, a little bit similar to GT 3, 4.
Thanks!

!!!Bad English!!!

**Comment by modmuss50** [comment]
I'm not sure what we would use the stainless steel for.

**Comment by Dimmerworld** [comment]
Juicer recipes

**Comment by jusvit** [comment]
@modmuss50 Juicer recipes

**Comment by CrossVas** [comment]
@modmuss50 Stainless Steel Plate can be used for craft a several items/blocks:
- Alternative craft of [Reinforced Machine Casing](http://i.imgur.com/W29nNRW.png)
- Alternative craft of [Diamond Grinding Head](http://i.imgur.com/Kzy8CTK.png)
- Regular craft of [Steel Drill](http://i.imgur.com/e18rTua.png)
- Regular craft of [Steel Chainsaw](http://i.imgur.com/6IOifdt.png)
- Regular craft of [Industrial Centrifuge](http://i.imgur.com/Qjjd7sE.png)
- Regular craft of [Saw Mill](http://i.imgur.com/eqKgYCf.png)
- Regular craft of [Industrial Electrolyzer ](http://i.imgur.com/rM2EnP4.png)

**Comment by modmuss50** [comment]
I dont see a real need.
