### ISSUE TITLE
techreborn.power.TRPowerNet.tick sometimes crashes

### ISSUE THREAD

**Issue by drcrazy** [TechReborn/TechReborn#1041]
Hi there, 

minecraft sometimes crashes with same java.util.ConcurrentModificationException exception. 

Minecraft 1.11.2
forge-1.11.2-13.20.0.2264
RebornCore-1.11.2-2.13.6.52-universal
TechReborn-1.11.2-2.1.11.103-universal

[00:29:49] [Server thread/ERROR] [FML]: Exception caught during firing event techreborn.power.PowerTickEvent@923acb1:
> java.util.ConcurrentModificationException
> 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_121]
> 	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_121]
> 	at techreborn.power.TRPowerNet.tick(TRPowerNet.java:97) ~[TRPowerNet.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_129_TRPowerNet_tick_PowerTickEvent.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
> 	at techreborn.events.TRTickHandler.worldTick(TRTickHandler.java:70) [TRTickHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_TRTickHandler_worldTick_WorldTickEvent.invoke(.dynamic) [?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285) [FMLCommonHandler.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [cch.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

Do you need full crash log?

WBR,
drcrazy

**Comment by modmuss50** [comment]
Uhh, I thought I fixed this. Ok thanks for reporting.
