### ISSUE TITLE
[Suggestion/Question] Guidebook Release 

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [TechReborn/TechReborn#1042]
Sorry for asking on here, but I couldnt find anywhere else.

I love this mod, but the one issue that me (and several others I know) have is that it is complicated, expecially without a guidebook. 

Any word on when the guidebook will be complete (or at least usable)? Playing this with it would make it so much better.

Thanks in advance!

**Comment by drcrazy** [comment]
Hello ErnestoPeroPezzi,
There is a wiki for TechReborn. You can find it here: https://wiki.techreborn.ovh/
If you are interested in particular machine, please, post more detailed request, like https://github.com/TechReborn/TechReborn/issues/979 . 

Overall step-by-step walk-through for TechReborn is in very distant plans. 

On the over hand, feel free to join wiki team to contribute to it's content. 

WBR,
drcrazy

**Comment by modmuss50** [comment]
Yeah, the wiki is the main source of information. This is because we can easily update it separately to the mod. And it can contain more ritch content easily.
