### ISSUE TITLE
With all cells, the same result

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1043]
**Issue Description:**

You can do some things with all the cells that exist in this modification for the same result.

**What happens:**

For example, 60k Helium Coolant Cell, you have to use Helium Cell cells to make the result. However, you should exchange the cells with other cells, the same thing comes out.

**What you expected to happen:**

It Works xD

**Steps to reproduce:**

Orginal Recipe: https://pudding.tk/HNnMDOSq.png
With nothing in Cell: https://pudding.tk/OcHY8qj4.png
With Protein Cell: https://pudding.tk/gLVoWbYP.png

60k Nak Coolant Cell is the same problem

Tested with all Cells

**Affected Versions (Do not use "latest"):**

    Techreborn: TechReborn-1.10.2-2.1.10.207-universal
    Minecraft: 1.10.2
    Forge: 12.18.3.2254

**Comment by jusvit** [comment]
#956
#1112

**Comment by jusvit** [comment]
I've narrowed the problem(I think) to 
`public static ItemStack getCellWithFluid(Fluid fluid, int stackSize) {
		Validate.notNull(fluid);
		ItemStack stack = new ItemStack(ModItems.CELL);
		getFluidHandler(stack).fill(new FluidStack(fluid, CAPACITY), true);
		return stack;
	}`
In DynamicCell.java
Doesn't return a valid item stack for the fluid.

**Comment by drcrazy** [comment]
Fix available on curse starting from TechReborn-1.12.1-2.7.0.205
