### ISSUE TITLE
Cabling using all available power

### ISSUE THREAD

**Issue by RichardAnderson** [TechReborn/TechReborn#1044]
**Running:**
- MC 1.11.2
- Forge 1.11.2-forge1.11.2-13.20.0.2282

**Mods:**
- Astral Sorcery, 1.3.0-beta
- Chisel, MC1.11.2-0.0.9.13
- Embers, 0.206
- Just Enough Items, 4.2.10.248
- RebornCore, 2.13.5.44
- TechReborn, 2.1.11.103
- Xaero's Minimap, 1.12.6

**To confirm:**
I've tried the same with ONLY the following mods, and I get the same result
- RebornCore, 2.13.5.44
- TechReborn, 2.1.11.103

**Replication Steps:**
Build 2 setups for 
"Generator" (P)
"Insulated Copper Cable" (C)
"Grinder" (G)

**First setup:**
PG
![setup1](https://cloud.githubusercontent.com/assets/860443/24906257/ebed7726-1eae-11e7-8866-1690281192f9.PNG)

**Second setup:**
PCG
![setup2](https://cloud.githubusercontent.com/assets/860443/24906263/f426bcb8-1eae-11e7-9159-6df54c08d92b.PNG)

Fill both "Grinders" with 64 Iron Ore
Fill both "Generators" with 64 Coal

**Expected Result:**
The Generator in the first setup, which is directly connected to the grinder, without a cable, will correctly send power to the connected Grinder, at a rate of around 300 per every few ticks (seems to be a trigger on how low the power is on the Grinder?).   I believe this is the expected result of both setups?

**Actual Result:**
The Generator in the second setup, which is connected to the Grinder via an Insulated Copper Cable (but the same is true for Tin Cable and Copper Cable), the power transfers from the generator at maximum rate, seemingly "lost" to the cable, as the grinder can only accept a small amount.

**Another example of the issue:**
Make setup 2 without the cable, but this time, only fill the generator with Coal.
Wait for the generator to be full, then connect the machines (without filling up the Grinder)
4,000 energy is transferred over.
Break the cable, add 1 ore to the Grinder.
748 FE is left (18% charged)
Add 1 more ore to the grinder
Now, 0 FE and only 22% complete.

Adding the cable back in, should drain 4,000 energy from the generator, and then a further 2,536 FE ( (3,252 / 100) * 78) over the next X seconds (the time it takes to grind the ore.

**Actual Result:**
The generator is FULLY drained of its 40,000 FE charge.  Therefore, over X seconds, 33,464 FE has been "lost".

**Comment by Tyler799** [comment]
Having the same issue in build 142 of TR. No modpack. It's just an issue with the grinder, seemingly. Electric furnace is fine. 

Wish there was a workaround. Guess you could use batteries lol. 

EDIT: And why the heck is this labeled "enhancement". This is obviously not an extremely serious bug, not a request for enhancement.
