### ISSUE TITLE
having problem loading the mod

### ISSUE THREAD

**Issue by greenoceanxd** [TechReborn/TechReborn#1045]
When I am loading up the game it crashes after a few seconds. i have all the required things and versions. I am running this on version 1.11.2 and this pops up when it crashes:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TechReborn (techreborn)              

Thanks for dropping by!

**Comment by modmuss50** [comment]
I need the full log please

**Comment by drcrazy** [comment]
Hello greenoceanxd, 

May I ask you to attach crash log from <minecraft folder>/logs, please?
Thank you in advance and sorry for crashing your game.

**Comment by modmuss50** [comment]
Closing as no log was provided.
