### ISSUE TITLE
Importer filling up both slots in electric furnace

### ISSUE THREAD

**Issue by jusvit** [TechReborn/TechReborn#1047]
Unsure if this is a bug or not finished yet.

![2017-04-14_17 10 39](https://cloud.githubusercontent.com/assets/4002351/25036169/8de4bf98-2135-11e7-85cf-f34c09864776.png)
![2017-04-14_17 10 43](https://cloud.githubusercontent.com/assets/4002351/25036170/8de874f8-2135-11e7-8dda-a2f74b73a733.png)

**Comment by drcrazy** [comment]
Electric furnace doesn't have upgrades anymore )
