### ISSUE TITLE
How do you increase heat in a Blast Furnace?

### ISSUE THREAD

**Issue by Tontete** [TechReborn/TechReborn#1056]
How do you get past Heat Level 1440 in a Blast Furnace?

**Comment by modmuss50** [comment]
Use better casings. You can mix + match

**Comment by Tontete** [comment]
I have already tried that, it says "Incomplete Multiblock"

**Comment by Tontete** [comment]
Also, why did you close the issue without confirming that the problem is solved?

**Comment by Tontete** [comment]
Ooops, didn't realize I was on an older version of the modpack. Now updated and it works

**Comment by drcrazy** [comment]
Here is a wiki article with examples for heat.

https://wiki.techreborn.ovh/doku.php?id=blocks:blast_furnace
