### ISSUE TITLE
[1.11.2] Server crash at start

### ISSUE THREAD

**Issue by kwpugh** [TechReborn/TechReborn#1058]
RebornCore-1.11.2-2.14.0.80-universal.jar
TechReborn-1.11.2-2.2.0.136-universal.jar
forge-1.11.2-13.20.0.2282-universal.jar

Crash report:
https://gist.github.com/anonymous/e4001b67f92004feb5fc0938b776ac57

**Comment by modmuss50** [comment]
Fixed update both mods
