### ISSUE TITLE
[1.11.2] Machines are not taking power from adjacent generator

### ISSUE THREAD

**Issue by drcrazy** [TechReborn/TechReborn#1059]
RebornCore-1.11.2-2.14.0.81-universal
TechReborn-1.11.2-2.2.0.137-universal

Machines are not accepting power from adjacent generator while cables are working fine. 

![image](https://cloud.githubusercontent.com/assets/1382352/25057782/7f90126c-217b-11e7-824f-a55c19e59b27.png)

**Comment by jusvit** [comment]
Tested other generators and such, this seems to be a isolated problem with the creative pane and pane only.
