### ISSUE TITLE
Literature & Industrial Grinder Multiblock Center Requirment Render not Rendering/not Functioning.

### ISSUE THREAD

**Issue by Twilight-Sparkle-Princess-of-Friendship** [TechReborn/TechReborn#1063]
I have the latest version and I can't find out what I need to use in the Center Multiblock for the Industrial Grinder because the Blocks Render isn't displaying & I can't find any Literature on it, even the In-Game Manuel doesn't Render correctly. Please advise.

**Comment by jusvit** [comment]
You need to use water.
https://wiki.techreborn.ovh/doku.php?id=blocks:industrial_grinder

**Comment by Twilight-Sparkle-Princess-of-Friendship** [comment]
I still can't get it to work, the Holigram of the center wants an unknown Block.

**Comment by Twilight-Sparkle-Princess-of-Friendship** [comment]
![2017-04-18_19 26 36](https://cloud.githubusercontent.com/assets/27166393/25158342/3bc88362-246d-11e7-836d-f3c770904df4.png)
This is the Industrial Grinder Hologram Display.

**Comment by Prospector** [comment]
The unknown block is water

**Comment by Twilight-Sparkle-Princess-of-Friendship** [comment]
I put water in there and it still won't let me use the Industrial Grinder.

**Comment by modmuss50** [comment]
Make sure you on the latest vesion of the mod.

**Comment by Twilight-Sparkle-Princess-of-Friendship** [comment]
It is the latest from curse.com, I still can't get it to recognize it has
all the components it needs.
