### ISSUE TITLE
[1.11.2] Overclockers not working in all machines

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1064]
I tried the overclocker in the grinder and it worked very fast but when I put overclocker upgrades in an electric furnace, the upgrade doesn't accelerate the process.

**Comment by modmuss50** [comment]
Yeah, the furnace doesn't use the same crafting system. This needs fixing.

**Comment by jusvit** [comment]
The furnace in general needs a redo, it's a glorified furnace and someone when making it tried to reinvent the wheel.

**Comment by Skillotic0703** [comment]
Haha ok thank you!
