### ISSUE TITLE
[1.11.2] MT Integration not updating recipes in JEI

### ISSUE THREAD

**Issue by Beetrootmonkey** [TechReborn/TechReborn#1068]
Hi! I'm using **forge-13.20.0.2282**, with TechReborn **2.2.1.142**.

Although Minecraft displays errors when you screw up a MT script using TR recipes (which indicates that the integration is somewhat there), it doesn't actually _change_ anything ingame. Neither adding nor removing machine recipes works. I'm glad the documentation is online, and thankful for giving us the means to integrate TR into our packs. But _please_ have a look into why scripts don't do anything.

Have a nice day!

**Comment by modmuss50** [comment]
Can you send me an example of a change you are trying to do?

**Comment by WTFNoNamesLeftoO** [comment]
"mods.techreborn.compressor.removeRecipe(<techreborn:plates:35>);"
![image](https://cloud.githubusercontent.com/assets/12583297/25313357/2d561e0c-282d-11e7-966e-55fd987158ab.png)

**Comment by Beetrootmonkey** [comment]
Thanks for the quick reply!
...
Woops. Turns out, all the changed I made actually do work. The problem seems to be with JEI, as it still shows no change at all. Removing/adding machine recipes isn't recognized by JEI, despite getting registered with the specific machine.
That leaves the question open, on what mod's end the mistake lies. Maybe RT has to update the recipe in question in JEI?

**Comment by Beetrootmonkey** [comment]
I'm noticing just now that there are more custom machine-type recipes that are working, but not showing up in JEI. Even furnace recipe, which is really odd. Since it seems that the "fault" is on JEI's end, I welcome you to close this issue once you read this. Sorry to have bothered you.

**Comment by modmuss50** [comment]
I know that MT changed the way recipes are added to JEI a while back, it may have broken again.
