### ISSUE TITLE
[1.11.2] Plate crafting

### ISSUE THREAD

**Issue by Terpo** [TechReborn/TechReborn#1069]
TechReborn plates like the Iron Plate is oreDict with plateIron, but crafting it in a compressor costs 9 ingots or an iron block.
Mod other mods do the conversion 1 iron => 1 plate. IC2 used dense plates for a conversion 9 iron => 1 dense plate.

At the current state it does not make sense to use the TR plates when ImmersiveEngineering or Embers is installed.

I would suggest changing the names to dense plates or at least change the oredict entry for it.

**Comment by modmuss50** [comment]
It should be 1-1, I thought I fixed this though? What version of TechReborn are you using?

**Comment by Terpo** [comment]
TechReborn-1.11.2-2.2.1.142-universal
RebornCore-1.11.2-2.14.2.94-universal

**Comment by modmuss50** [comment]
Humm, ok. I may have forgotten to port the fix to 1.11

**Comment by TheLimePixel** [comment]
I was going to suggest the same. Also for some reason the Redstone Plate uses Resonating Redstone Crystals from Extra Utils, so maybe you shouldn't oredict it.

**Comment by TheLimePixel** [comment]
It also happens in the 1.12 version

**Comment by drcrazy** [comment]
1 ingot  = 1 plate in 1.12.1
