### ISSUE TITLE
Hello - Potential new developer?

### ISSUE THREAD

**Issue by TheDoctorSoda** [TechReborn/TechReborn#107]
Hi, I've recently gotten into modding, but I would love to help. I am also a texture artist, so I would also love to help texture-wise. I feel like this project could also help me advance my modding knowledge, so would you mind if I did some pull requests and stuff? Also what's the best way to contact you guys?

**Comment by modmuss50** [comment]
Pull requests are great, the best way to contact us to begin with is on irc, #TechReborn on Espernet

**Comment by TheDoctorSoda** [comment]
Thanks
