### ISSUE TITLE
[1.11.2] Grinder draws over 10x power needed if connected via cable

### ISSUE THREAD

**Issue by Tyler799** [TechReborn/TechReborn#1070]
MC 1.11.2, TR version 2.2.1.142. 

A grinder should draw about 3,200 FE for every operation. And if directly connected to a batbox or a generator, it draws exactly that.

And batboxes connected to generators via cable suffer no losses.

However, the moment I connect generators to machines via cable or batboxes to machines via cable, the power use spikes to over 35,000 FE for a single ore operation. This happens with both tin, copper, and insulated copper cabling. 

EDIT: Just tested, electric furnace not effected. Changed title to reflect this.

**Comment by modmuss50** [comment]
Thanks, this isn't going to be fun to figure out :/
