### ISSUE TITLE
[Suggestion] Power display

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1072]
In 1.10.2 versions (I don't know for 1.11) the energy amount and type display is a bit weird. Sometimes it displays EU, sometimes it displays FE etc... I think that you should replace these displays with a string variable energyType, and energyType takes the value of the chosen power system in the configs so you would have to change the power system display in only one place. For the amount of power I think that every operation should have an associated integer which would be the amount of power required in RF/Tesla/FE and when EU is selected the amount is 4 * energyRequired.

**Comment by modmuss50** [comment]
Click the power bar to change the value its shown in.
