### ISSUE TITLE
[1.10.2] No Recycler for make Scrap? (Matter Fabricator)

### ISSUE THREAD

**Issue by Hodel1** [TechReborn/TechReborn#1074]
Hi,

i had tested a little bit in Singleplayer, before i would start on Multiplayer.
But i dont have a Recipe to a Recycler or Scrap from TechReborn, only for IC2.

i tested the Matter Fabricator, it will work with IC2 Scrap but not with IC2 Scrapboxes.
TechReborn Scrap cannot be crafted.

I tested it on FTB Beyond 1.5.3 with TechReborn 2.1.11.209

**Comment by modmuss50** [comment]
Ic2 scrap will work.
