### ISSUE TITLE
[1.11.2] Can't connect TR power to Refined Storage controller.

### ISSUE THREAD

**Issue by alvarocastro** [TechReborn/TechReborn#1081]
Just created my own modpack and while testing it noticed TR cables won't connect to an RS controller.
I also tried placing the controller adjacent to a battery, but still no power in my RS network.

I understand that both mods use Forge Energy.

My modpack just has Buildcraft, Tech Reborn and Refined Storage.

**Comment by modmuss50** [comment]
Our cables don't work with FE just yet. Is high on my todo list

**Comment by cryptiklemur** [comment]
This issue should be left open then, no? Or is this finished now

**Comment by modmuss50** [comment]
Should be fixed
