### ISSUE TITLE
[1.10.2] Crafting Issues with IC2. 

### ISSUE THREAD

**Issue by MaxineBean** [TechReborn/TechReborn#1082]
Industrial Craft 2 version: industrialcraft-2-2.6.206-ex110
Tech Reborn version: TechReborn-1.10.2-2.1.12.215-universal
Reborn Core: RebornCore-1.10.2-2.13.5.136-universal
Forge Version: forge-1.10.2-12.18.3.2281

When attempting to create a basic machine casing from IC2 for IC2 machines, a Tech Reborn machine block is made, and it cannot be used for IC2 Machines. This issue also occurs with advanced machine casings as well. I will say, I have tried changing `B:"Remove Duplicates when IC2 is installed"=false` to true and the issue still exists. I was able to "fix" this issue with this Minetweaker script.

```
# Imports

import minetweaker.item.IItemStack;
import minetweaker.data.IData;
import minetweaker.item.IIngredient;

# Removing Recipes

recipes.removeShapeless(<minecraft:iron_ingot>*8,[<ic2:resource:12>]);
recipes.removeShapeless(<techreborn:techreborn.machineFrame:1>,[<ic2:resource:12>]);
recipes.removeShapeless(<ic2:resource:12>,[<techreborn:techreborn.machineFrame:1>]);

# Adding Recipes

recipes.addShapeless(<ic2:resource:12>,[<techreborn:techreborn.machineFrame>]);
recipes.addShapeless(<techreborn:techreborn.machineFrame:1>,[<ic2:resource:13>]);
recipes.addShapeless(<techreborn:techreborn.machineFrame>,[<ic2:resource:12>]);
recipes.addShapeless(<ic2:resource:13>,[<techreborn:techreborn.machineFrame:1>]);
```
I have also noticed that for some reason, I cannot craft advanced circuits from Tech Reborn. As well as, for some reason the recipe for a generator from IC2 is the same as the generator from Tech Reborn. The recipe I am talking about is the one added from Tech Reborn.

**Comment by drcrazy** [comment]
Not reproducible in 1.12.1
