### ISSUE TITLE
Infinite Energy Bug (Mod Compatibility)

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1083]
on minecraft 1.11.2, forge 2298. RebornCore 2.14.2.94, TechReborn 2.2.1.142, Actually Additions r107.
this happens:(solar panel is full but mfsu is filling)
![bug](https://cloud.githubusercontent.com/assets/24831406/26191623/459b093a-3bb7-11e7-8e93-9b7ef4c6eea9.gif)
https://github.com/Ellpeck/ActuallyAdditions/issues/771

**Comment by modmuss50** [comment]
Can you try with this version of Reborncore? https://jenkins.modmuss50.me/job/TeamReborn/job/RebornCore/job/RebornCore-1.11.2/101/ It should also fix your issues with the FluxedRedstone cables

**Comment by ghost** [comment]
of course, let me try.

**Comment by ghost** [comment]
uh oh, it didn't work again with laser relays from ActuallyAdditions :/ 
And very important another thing, i made a test.
i set the time to night, i placed 2 solar panels, connected first solar panel to the first mfsu with redstone fluxed wire, and connected second solar panel to the second mfsu with copper cable. then i set time day, and time night again after 4 seconds. and surprise! redstone fluxed wire-connected mfsu filled 3 times more than the other one. and solar panels was empty.
here some screenshots:
![2017-05-18_17 57 15](https://cloud.githubusercontent.com/assets/24831406/26208732/7fbd316a-3bf3-11e7-975d-f9b0c9004ea6.png)
![2017-05-18_17 58 41](https://cloud.githubusercontent.com/assets/24831406/26208802/b2354e70-3bf3-11e7-9e50-adc19aad969f.png)
![2017-05-18_17 58 42](https://cloud.githubusercontent.com/assets/24831406/26208803/b238fea8-3bf3-11e7-9e73-c5bd6631fef6.png)

**Comment by modmuss50** [comment]
Humm ok, thanks for that I will take a look later at it

**Comment by ghost** [comment]
ok thanks, we will be waiting

**Comment by modmuss50** [comment]
Ok, done some more changes, if you want to test you can use:
https://jenkins.modmuss50.me/job/TeamReborn/job/RebornCore/job/RebornCore-1.11.2/103/
and
https://jenkins.modmuss50.me/job/TeamReborn/job/TechReborn/job/TechReborn-1.11.2/151/

**Comment by ghost** [comment]
let me test

**Comment by ghost** [comment]
well, Techreborn cables working awesome. They connect other mods machines, it's amazing. But actually additions's  laser relay still not working with techreborn's machines. thanks! great job

**Comment by modmuss50** [comment]
Ok, Im getting there. :) I will install Actually additions to try and see whats wrong with them next.

Thanks a lot for helping test 👍

**Comment by ghost** [comment]
ur welcome. btw, i'm using AA r107

**Comment by modmuss50** [comment]
Should be fixed now, going to prep a beta for curse.

**Comment by ghost** [comment]
i hope it will fix my modpack bug too :( (infinite energy) thanks for great work
