### ISSUE TITLE
[1.11.2] Achievement New Ore!

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1086]
I'm using forge 13.20.0.2299 TechReborn 2.3.0.152 and RebornCore 2.16.0.106. When I mine a TechReborn ore (tested with Copper, Tin, Galena, Bauxite, Lead, Silver, Peridot, Ruby, Sapphire so far) I don't get the New Ore! achievement.

**Comment by modmuss50** [comment]
Achievements are getting removed in 1.12, so dont expect this to be fixed.

**Comment by Skillotic0703** [comment]
I understand, that seems to be logic. Thank you for your time anyway.

**Comment by modmuss50** [comment]
Fixed by removing them, I dont see a point in fixing them, as I will have to get rid of them in a few weeks for 1.12 anyway.
