### ISSUE TITLE
[Suggestion] QuantumStorage

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1087]
When the QuantumStorage mod is installed, you should add TechReborn recipes for its items. Maybe you could also add a config option to disable this feature.

**Comment by modmuss50** [comment]
What currently happens is the TR items are hidden and replaced with the QS ones. Only issue is in 1.11 QS has had some major changes.

**Comment by Skillotic0703** [comment]
Is that a problem for you to change QS recipes to match TR ones?

**Comment by modmuss50** [comment]
@gigabit101 Would need to give the go ahead for this.

**Comment by modmuss50** [comment]
and if so, it would be a config disabled by default.

**Comment by gigabit101** [comment]
Go for it

**Comment by modmuss50** [comment]
Closing as QS now has some different items/blocks, if a pack author wants to do it they can use minetweaker.
