### ISSUE TITLE
[Suggestion] Power converters

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1090]
I think that having an all-in-one power system is a bad idea. You should have only one supported power system, that's your own power system. It should be a power system which is equal to eu. And to convert to and from other power systems, you should implement converters. These could be very simple converters (even simpler than those of power converters). There should be converters for each voltage and they multiply by 4 the power input when outputting.
I give you this suggestion because it could be much simpler for you to do that and because in the current situation your system is completely broken.

**Comment by modmuss50** [comment]
This is out plan for TechReborn 3, but that is a long way off. I might have to do this in 1.12 but i dont think it will happen in 1.11 due to fear of breaking worlds unless things get bad

**Comment by Skillotic0703** [comment]
I remember that in gregtech 2 there was the pneumatic generator upgrade that allowed the machines to be able to be powered by MJ power. MJ is not anymore and RF took its place so I think that you should also add this upgrade in 1.12 (maybe you could wait until CoFH mods come out when 1.12 releases). The conversion ratio was 1 EU for 1 MJ so now it means that 10 RF should give 4 FE. But I think that in 1.12 you should return to a power system where 1 unit is equal to 4 RF/FE. So with the upgrade it would give 1 TR unit for 10 RF.

**Comment by Prospector** [comment]
When we do TR3 it won't run on any existing power system, and it won't behave like any of them either. There will be some way to generate it with FE, but direct conversions aren't really a thing that would work.

**Comment by Valchap** [comment]
I just want to hear your opinion.
Would not it be better that all mods use ForgeEnergy ?

**Comment by Prospector** [comment]
Forge Energy should be used where it makes sense to be used, and not where it doesn't.

**Comment by drcrazy** [comment]
FE based on ForgeEnergy. Thus FE is compatible with all RF-based mods. 
There are issues with EU power net. So maybe in some future there will be power converters. But not in nearest one. Too much work as for now.
