### ISSUE TITLE
[1.10.2] Crash with TR Quantum chest

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1093]
TechReborn 1.10.2-2.1.13.219
RebornCore 1.10.2-2.13.6.142
Forge 1.10.2 - 12.18.3.2297
https://pastebin.com/4K9Ve0iC
I just tried to put several stacks at a time in a TR Quantum Chest

**Comment by drcrazy** [comment]
Not reproducible in 1.12.1
For 1.10.2 use Quantum Storage instead of this one.
