### ISSUE TITLE
[1.10.2] Implosion compressor working regardless of the multiblock structure

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1094]
TechReborn 1.10.2-2.1.13.219
RebornCore 1.10.2-2.13.6.142
Forge 1.10.2 - 12.18.3.2297
The implosion compressor is always displaying "Incomplete Multiblock" even though I have the multiblock built below the implosion compressor and it works even when the multiblock is not built.

**Comment by modmuss50** [comment]
I think I fixed this a while back on 1.11 but forgot to port it back to 1.10

**Comment by Skillotic0703** [comment]
This is fixed in 1.12 and will probably never get fixed in 1.10.2 so...
