### ISSUE TITLE
[1.10.2] Cables accepting power regardless of voltage

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1098]
The power system works pretty well now. You can put a grinder in front of an mfsu and it will not charge so it's working as intended but when you put a copper cable between the two machines, power is transferring.
But if I put a gold cable instead of a copper cable the grinder makes smoking particles. SO I think that the problem is that cables accept power regardless of voltage.

**Comment by modmuss50** [comment]
The cables work on FE which does not have voltages or teirs.
