### ISSUE TITLE
[1.10.2] Transformers not working properly

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1099]
The HV transformer is outputting LV power, the MV transformer only accepts LV power so everything is working improperly.
What I expected to happen was: 
- HV transformer accepts EV and outputs HV
- MV transformer accepts HV and outputs MV
- LV transformer accepts MV and outputs LV

**Comment by drcrazy** [comment]
Not reproducible in 1.12. At least as per tooltip )

![image](https://user-images.githubusercontent.com/1382352/30885899-b9736ea6-a31d-11e7-897c-b4712e71c53f.png)
