### ISSUE TITLE
[1.12] Generators are not distributing power evenly between machines

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1100]
All generators should be distributing power evenly to all its sides. So if I put a thermal generator between two battery boxes, when the generator stops running, the two battery boxes should have the same amount of power.

**Comment by Skillotic0703** [comment]
The solution imo would be to check the number of sides that can output power. And each side would output the base amount divided by the number of sides.

**Comment by drcrazy** [comment]
Fixed in RebornCore version RebornCore-1.12.1-3.4.0.107.jar
Minor issue like loss of 1-2 EU due to rounding from double to int will persist
