### ISSUE TITLE
[1.12] Machines will only input from the top and output from the bottom

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1103]
It can be very useful to I/O from the same side or from the back. For example if you put your machines in a wall and don't want to see the refined storage crafters, it can be cool to be able to place them at the back.
Can you make so that we're able to I/O from all sides of the machines?

**Comment by drcrazy** [comment]
Not reproducible in 1.12 

I've checked with xnet and sawmill. Xnet connector was attached to side. Wood from chest successfully went to sawmill. There might be an issue with some machines. Please, name them explicitly. 

![image](https://user-images.githubusercontent.com/1382352/30885312-62cc2c70-a31b-11e7-9574-241f92531361.png)
