### ISSUE TITLE
[1.10.2] [Request] Backport upgrades to 1.10.2

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1104]
For the time being 1.10.2 is the main MC version so I think it's legitimate to ask for these as they are more than useful. It's really annoying to have 1K recylers instead of 10 with overclockers to run a matter fabricator. Currently transformers aren't working very well and I think that it's easier to add an upgrade which improves by one level the voltage of a machine instead of fixing the transformers.

**Comment by Prospector** [comment]
No, sorry

**Comment by modmuss50** [comment]
Yeah, backporting the upgrades would be a lot of work. We might be able to speed the recycler up or something. ¯\_(ツ)_/¯

**Comment by Skillotic0703** [comment]
I understand. Thank you for your work. I think that i'll find another solution. Maybe i'll add a recipe for scrap in other mods machines.
