### ISSUE TITLE
Unable to create Sulfur Cells

### ISSUE THREAD

**Issue by seanjohnbell** [TechReborn/TechReborn#1105]
Unable to create Sulfur Cells with 2.1.12.215 as part of FTB Beyond 1.7.0-1.

JEI doesn't show any available recipes for creating the cells other than breaking down Sulfuric Acid cells... which need the Sulfur Cells in the first place to make!

Gregtech originally had the recipe as combining Sulfur Dust and Cells in the regular crafting grid, but this doesn't appear to be enabled,

**Comment by drcrazy** [comment]
Fixed in 1.12.1. Sulfur cells are not produced by Industrial Centrifuge from glowstone or netherrack dusts.

**Comment by drcrazy** [comment]
Fix available on curse starting from TechReborn-1.12.1-2.7.0.205
