### ISSUE TITLE
[1.11.2/1.12] Magnesium useless without magnalium plates

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1109]
Can you just add back the magnalium plate please ? Because without the magnalium plate, magnesium dust is completely useless! It used to be useful because you could craft the windmill with magnalium plates.

**Comment by modmuss50** [comment]
No new features in 1.10

**Comment by Skillotic0703** [comment]
First I thought that I would be able to create a modpack centered around TechReborn in 1.10.2, but now I think that this isn't going to be possible so I will just help you to improve the 1.11.2 version until the other mods update to 1.11.2. So can you add the magnalium plates in 1.11.2 please (It's just an item and a rolling machine recipe)?
![image](https://cloud.githubusercontent.com/assets/12701912/26742157/dc907d80-47dc-11e7-9827-3fe8252603b2.png)

**Comment by modmuss50** [comment]
I will put it on the list

**Comment by drcrazy** [comment]
@Skillotic0703 , thank you for reporting this

**Comment by drcrazy** [comment]
Fix available on curse starting from TechReborn-1.12.1-2.7.0.205
