### ISSUE TITLE
Compatibility issue with latest version of forestry

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#111]
While using the lastest dev version of forestry I got the following crash
http://pastebin.com/hcVacum0

**Comment by modmuss50** [comment]
It looks like they renamed something internaly

**Comment by LordMonoxide** [comment]
Forestry underwent a fairly large API refactoring a little while ago.  This may be the same thing that broke Biomes o' Plenty's integration. Until it's fixed, Forestry #639 will work.

**Comment by modmuss50** [comment]
I wont fix this, until it breaks on the stable branch of forestry.

**Comment by modmuss50** [comment]
Forestry 4 has been pushed to stable, this has been fixed.
