### ISSUE TITLE
[1.12] ThermalExpansion machines compatibility

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1110]
In gregtech 2, there was compatibility for Thermal Expansion.
There was recipes in the pulverizer :
- Sodalite Ore -> 12 Sodalite Dust + 10% chance for an Aluminium Dust
- Plate -> Dust recycling recipes

Recipes for the induction smelter:
- Classic induction smelter ore to ingot recipes but with Tungsten ore and it gives tungsten dust instead of tungsten ingots
- Sand + 2 Iron Ingots -> 2 Refined Iron Ingots + 25% chance for a Slag

Recipes for the fluid transposer:
- 6000mB of coolant + Empty cell -> 60k coolant cell
- Coal Dust + 125mB of water -> Hydrated Coal Dust

**Comment by modmuss50** [comment]
I will look into this once TE updates to 1.11

**Comment by Skillotic0703** [comment]
Can you reopen this now that TE updated to 1.12?

**Comment by modmuss50** [comment]
Yes I can!

**Comment by Skillotic0703** [comment]
Yeah!!!!

**Comment by modmuss50** [comment]
Ok, im editing the issue as I do them so I don't loose track.
