### ISSUE TITLE
[1.11.2] Quarry recipe

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1111]
Now that buildcraft is out you can add back this recipe for the quarry:
![image](https://cloud.githubusercontent.com/assets/12701912/26693360/2bbeda52-4704-11e7-9514-031b451d5fae.png)

**Comment by modmuss50** [comment]
yeah, thanks for reminding me :)

**Comment by modmuss50** [comment]
Added: https://github.com/TechReborn/TechReborn/commit/a6d0e57d1021eed72cd0bdae45ebd9914beca0e9
