### ISSUE TITLE
[1.11.2] 60K helium coolant cell recipe

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1112]
The recipe for 60k helium coolant cell requires an Helium cell but the recipes works even if you replace the helium cell by any cell.
![image](https://cloud.githubusercontent.com/assets/12701912/26695867/bf528c52-470c-11e7-8179-cf28817155de.png)

**Comment by Skillotic0703** [comment]
It also happens in 1.12!

**Comment by drcrazy** [comment]
Duplicate for #1043
