### ISSUE TITLE
[1.11.2/1.12] Canning machine

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1113]
I think that this machine is pretty important for some recipes (sulfur cells, wolframium cells) even though you created some recipes, they feel a bit wrong. It doesn't seem to me that it would be very difficult to implement because you already have a bunch of machines, so you already set the general logic for your machines up. Please implement this machine (and don't forget crafttweaker support if you don't have time to add the recipes by yourself).

**Comment by modmuss50** [comment]
Not needed.
