### ISSUE TITLE
Eletronic circuit not in JEI HELP PLEASE

### ISSUE THREAD

**Issue by GamingWithJean** [TechReborn/TechReborn#1114]
Thanks for reporting an issue! However, before you report an issue, please read the following:

 * We will not backport to an old version of minecraft. Do not suggest this
 * Make sure you're using the latest version of TechReborn, RebornCore, and Forge before reporting a bug!
 * Don't argue with any TechReborn developers. What they say goes. Feel free to suggest a way to implement something, but if they say no, don't push it.
 * If you want to suggest something please open an issue, and it will get tagged as a suggestion.
 
 Make sure to delete all this text before you report your issue.

**Comment by modmuss50** [comment]
Need more info, mod version? are you using a mod pack? Config changes?

**Comment by GamingWithJean** [comment]
It is in the newest update for the modpack ftb Beyond

**Comment by GamingWithJean** [comment]
I Just started TechReborn but i dont want to use the IC2 Circuits

**Comment by GamingWithJean** [comment]
Can you help me please?

**Comment by modmuss50** [comment]
In beyond you have to use IC2 to progress into TR

**Comment by GamingWithJean** [comment]
Oh.....

**Comment by GamingWithJean** [comment]
i hate ic2

**Comment by GamingWithJean** [comment]
so no recipe for eletronic circuit from TR
