### ISSUE TITLE
Single Battery

### ISSUE THREAD

**Issue by skye006** [TechReborn/TechReborn#1115]
For some reason the recipe for the single battery does not work for me. I seem to have the right recipe but nothing shows up in the output of the crafting grid. 
[http://imgur.com/a/2kq3W](url)

**Comment by skye006** [comment]
as for the version of the pack i have the latest release update

**Comment by Prospector** [comment]
Wrong mod, mate. I think you have us confused with Actually Additions.

**Comment by skye006** [comment]
Switched up the links. Thought this was a diff github. Sorry bout that
