### ISSUE TITLE
[1.11.2] Plate bending machine

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1117]
I know that you added recipes for plates in the compressor but it looks very weird to use the compressor for plates. And I have good arguments to convince you to add the plate bending machine : 
- If you add it, you can add ore dict support for it so it automatically creates recipes for plates from other mods.
- If the plate creation functionnality already exists in other mods, it would be easier to disable the plate bending machine instead of disabling all the recipes for plates in the compressor.

**Comment by modmuss50** [comment]
I could auto add recipes to the compressor if needed, but I dont think it is. MT can be used to remove the recipes. If you really want I can add a config to remove the recipes? But that would have to be a special case.

**Comment by Skillotic0703** [comment]
No thank you, I don't want to bother you, I just realized that this is just a detail, it's not important ;)

**Comment by modmuss50** [comment]
Quick note, if you want to ask quick questions it might be easier to ask on our discord server: https://discord.gg/0tCDWb77cvetwm0e Saves the effort of opening an issue and then waiting for a reply.
