### ISSUE TITLE
[1.11.2] Grinder recipes can not be removed with Crafttweaker

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1118]
TechReborn-1.11.2-2.3.3.174
RebornCore-1.11.2-2.16.1.115
Forge 13.20.0.2310
I write a script to remove recipes from the grinder. Then I reload the scripts with /mt reload. It doesn't tell me that the script is not working but when I try the recipe in the grinder, the recipe still works and it's displayed in JEI.

**Comment by modmuss50** [comment]
I assume it's just the grinder that has issues?

**Comment by Skillotic0703** [comment]
Yeah with removing yes.
