### ISSUE TITLE
[1.11.2] Weird behaviour of Crafttweaker with the industrial centrifuge

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1119]
When I try to make a recipe for the industrial centrifuge, I have to have 4 outputs (I can't just write null instead of setting an output) for the recipe to work. When I put less than 4 outputs it says : "Output stack is null or empty".

**Comment by modmuss50** [comment]
Humm yeah. That would have broken when we moved to 1.11. Should be an easy fix.

**Comment by TheLimePixel** [comment]
Talking about CT support, could you please make the recipes show up in JEI? Idk if the same goes for all machines, but the Rolling Machine recipes never get updated in JEI.

**Comment by modmuss50** [comment]
I thought I fixed this? Are you using the latest 1.11.2 versions of TR, JEI and CT? I might need to take another look.

**Comment by TheLimePixel** [comment]
Yes.
![image](https://user-images.githubusercontent.com/25333164/27129514-f928c964-5102-11e7-84e1-0dd694833e75.png)

![image](https://user-images.githubusercontent.com/25333164/27129719-8ba72cd6-5103-11e7-816e-e703b0e81e34.png)

![image](https://user-images.githubusercontent.com/25333164/27129734-9ae007cc-5103-11e7-9fad-f6bf54d1343a.png)

Also, which machines have CT support? I need the Chemical Reactor, but I tried both techreborn.chemicalReactor and techreborn.reactor and neither one works. Is it something different maybe?

**Comment by modmuss50** [comment]
Here is an auto generated list of all the machines: https://wiki.techreborn.ovh/doku.php?id=development:mt

**Comment by TheLimePixel** [comment]
Thanks! I thought it'd be on the GitHub as all other mods that have CT support have it, so I didn't even bother checking the wiki.

**Comment by modmuss50** [comment]
You can also enable a config in Reborncore that will try to auto generate all documentation for all installed mods at runtime.

**Comment by TheLimePixel** [comment]
Good news! Only the Rolling Machine doesn't show recipes in JEI. I still need it to though. :I

**Comment by drcrazy** [comment]
Rolling machines recipes are visible in JEI
![image](https://user-images.githubusercontent.com/1382352/30062280-4d560efc-9253-11e7-8efe-bff4a261f956.png)
