### ISSUE TITLE
[Suggestion] Provide a config option to disable RF input/output

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#112]
As Aroma1997 has provided a way for IC2 to use the old IC2 e-net, techreborn can be played with IC2 just like before
(http://forum.industrial-craft.net/index.php?page=Thread&threadID=11586)

So I would like to know if it's possible to add a config option to disable RF input/output, to restore the gameplay style we had at 1.4.7

**Comment by modmuss50** [comment]
Yes this was planned to be off by default when ic2 is installed, and always on when not installed. Just forgot to do it.
