### ISSUE TITLE
[1.10.2/1.11.2] Brass ingot display

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1122]
When checking the uses for Brass in JEI there is always a subscript 4.
![image](https://cloud.githubusercontent.com/assets/12701912/26801586/95a405b4-4a3d-11e7-9eb6-4f7756f87144.png)
![image](https://cloud.githubusercontent.com/assets/12701912/26801611/a68fcf52-4a3d-11e7-94a9-c0fb9a1c901e.png)
![image](https://cloud.githubusercontent.com/assets/12701912/26801623/afdf83f4-4a3d-11e7-9771-d616cb1d6f93.png)

**Comment by modmuss50** [comment]
Uhh, ok. We had this issue with redstone a while ago, it wasnt fun to track down.

**Comment by modmuss50** [comment]
Can you check to see if this only happens with just TR and JEI?

**Comment by Skillotic0703** [comment]
Yeah it happens with only TR and JEI! But I also found sth:
![image](https://user-images.githubusercontent.com/12701912/26840839-cdfc5042-4ae7-11e7-9225-234f38204f88.png)
There is the same problem but with a subscript 9 in this recipe.

**Comment by Prospector** [comment]
Just bronze? That's odd.

**Comment by Skillotic0703** [comment]
That's brass actually, I confused but yes, it's just brass.

**Comment by Skillotic0703** [comment]
That's also fixed in 1.12!
