### ISSUE TITLE
[1.7.10] Black Machine GUI

### ISSUE THREAD

**Issue by CrossVas** [TechReborn/TechReborn#1126]
Hey!
I know 1.7.10 is a old MC version and still not be update. On the other side i don't want to play with TR [1.8+]. So, i have a question. How i can fix this issue for 1.7.10?

Minecraft Forge 10.13.4.1614
RebornCore-1.1.0.15-universal
TechReborn-1.7.10-0.7.20.1118-universal

![2017-04-02_19 17 06](https://user-images.githubusercontent.com/25727222/26946703-e0ecaafa-4c98-11e7-9c11-50ede3a4e251.png)
![2017-06-08_22 19 27](https://user-images.githubusercontent.com/25727222/26946706-e0f9a5d4-4c98-11e7-8377-b8ea9583d16b.png)
![2017-06-08_22 19 31](https://user-images.githubusercontent.com/25727222/26946704-e0f1aec4-4c98-11e7-8790-415fb34562aa.png)
![2017-06-08_22 19 34](https://user-images.githubusercontent.com/25727222/26946705-e0f8d23a-4c98-11e7-985f-31439e7d5dbc.png)
![2017-06-08_22 19 38](https://user-images.githubusercontent.com/25727222/26946707-e0fae656-4c98-11e7-8361-9731756deca5.png)

**Comment by modmuss50** [comment]
Few things to try, if you have any graphics mods like optifine, or fastcraft, try removing them. 

Try hiding nei? does that help?

Last thing to do, the machines should still work just fine, you might have to put up with it. I wont be fixing this for 1.7 as it isnt a major issue.

**Comment by CrossVas** [comment]
Unfortunately, none of the tips did not help to solve the problem. 
Thanks anyway!
