### ISSUE TITLE
[1.11.2] Crash near Blast Furnace

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1133]
Here is the problem: I experience a crash which I can reproduce pretty reliably.  Whenever I approach my TechReborn Blast Furnace multi-block structure, my client crashes with the following error:
https://pastebin.com/K7QctDbh

 I wasn't sure whether or not to post this on the RC or TR GitHub, but as the multiblock is from this mod, I went with it. This has been going on for a couple of versions.

**Comment by drcrazy** [comment]
Not reproducible in 1.12
