### ISSUE TITLE
No Rubber Trees in Overworld?

### ISSUE THREAD

**Issue by InterPlay02** [TechReborn/TechReborn#1134]
Hello!

I'm  here today to tell you a strange thing: The rubber trees are NOT beeing generated in overworld.
It seems to be happening only if Tech Reborn is in a pack. I've tested it alone, but everything looks right. But, in my modpack, at least, the rubber trees are not beeing generated in overworld.

But I am pretty sure that I don't changed anything in the mod's config file.
Any idea about what could be happening? Can this be a bug caused by Biomes O'Plenty?

This is the modpack, if you want to take a look:
https://minecraft.curseforge.com/projects/tech-nature

**Comment by modmuss50** [comment]
It could well be BOP, I will look into it.

**Comment by InterPlay02** [comment]
Update:
Hm... I've tested out again.
Even without Biomes O'Plenty in the pack, the rubber trees are not beeing generated...
=P

**Comment by modmuss50** [comment]
Try deleting your config, and looking harder. As they work fine for me and other people.

**Comment by InterPlay02** [comment]
Man... Did you see the link that I've mentioned?
There was other people there, that also has the same thing going on!
One of them have look arround 5000 blocks in all directions... But nothing...
But ok... Sorry for disturbing you.

**Comment by InterPlay02** [comment]
Take a look by yourself:
![config](https://user-images.githubusercontent.com/23037423/27262423-fb73703e-542c-11e7-815f-4055a504ffea.JPG)
