### ISSUE TITLE
Chrome and Titanium

### ISSUE THREAD

**Issue by bonnedav** [TechReborn/TechReborn#1136]
How do you get Chrome and Titanium? I can't find the recipe in JEI.
Tech Reborn: 2.1.13.219
Reborn Core: 2-2.13.6.142
JEI: 3.14.7.419
Forge: 12.18.3.2254
MC: 1.10.2

**Comment by bonnedav** [comment]
Never mind, I found it.

**Comment by valkyrienyanko** [comment]
How did you find it?
