### ISSUE TITLE
[1.12] Quantum chest weird behaviour

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1138]
Forge 14.21.0.2327
Reborn Core 3.0.1.12
Tech Reborn 2.4.0.50
Everything works fine as long as I don't use shift-click in the quantum chest. When I use shift-click to put one stack in the quantum chest, it works but the time is still displayed in my inventory until I quit the quantum chest GUI. When I try to put multiple stacks at a time in the quantum chest, it only transfers two stacks and the items are still being displayed in my inventory. And when I try to withdraw the stacks from the quantum chest using shift-click it works but when I withdraw the last stack the quantum chest still displays 64 items whereas there are 0 items and the items are not displayed in my inventory until I quit the quantum chest
However, there are no dupe bugs.

**Comment by drcrazy** [comment]
Duplicate for #1255
