### ISSUE TITLE
[1.10.2] Game crashes when opening GUI

### ISSUE THREAD

**Issue by Stetoskop** [TechReborn/TechReborn#1140]
Hey, my friend and I use TechReborn on our private server, the problem is that my friend cannot open any TR GUIs without crashing, but I'm able to avoid that and the GUI opens as usual. We've got a good chunk of other mods installed, but we're using the same exact mods so it doesn't seem like that should affect him only.

[crash-2017-06-16_17.59.06-client.txt](https://github.com/TechReborn/TechReborn/files/1081379/crash-2017-06-16_17.59.06-client.txt)

**Comment by modmuss50** [comment]
We talked on discord, its an issue with the energy priority system.

**Comment by modmuss50** [comment]
I think this has been fixed on 1.12. Please re-open if it happens on 1.12
