### ISSUE TITLE
Issue when used with chisels and bits

### ISSUE THREAD

**Issue by kamanabc123** [TechReborn/TechReborn#1141]
Hey I didn't see this posted as an issue so I thought I would let you know that in the 1.10.2 version when used with chisels and bits if you make a stair using chisels and bits like if u take a stone block and use 1/2 sized grid snapped cube mode and break 2 parts to make it into a stair and u try to go up it like a stair you can't. You get stuck. I noticed this awhile back in a modpack I had before. No clue as to why this happens but it does. Hope you fix this.

**Comment by modmuss50** [comment]
Nothing to do with TechReborn?

**Comment by kamanabc123** [comment]
This only happens when TechReborn is installed......... Don't know how it has nothing to do with it. This could be a problem with chisels and bits but I don't think it is. I will try post an issue on that too.
