### ISSUE TITLE
TechReborn and IC2 not compatible?

### ISSUE THREAD

**Issue by E4002X3102** [TechReborn/TechReborn#1142]
[crash-2017-06-18_12.25.56-client.txt](https://github.com/TechReborn/TechReborn/files/1082904/crash-2017-06-18_12.25.56-client.txt)

Minecraft crashed while loading when I attempt to load BOTH TechReborn and IndustrialCraft 2. Both mods works individually. Would like to know if these 2 mods are not supposed to work/be compatible with each other?

By the way, if they are not going to be compatible with each other, I will stick to TechReborn, since it has a working wiki but IC2 doesn't. :)

**Comment by modmuss50** [comment]
Looks like I need to update to support newer ic2

**Comment by modmuss50** [comment]
After looking it it more, it seems to be an issue with IC2.

Having said that using the latest versions of TechReborn and IC2 from curse seems to be working ok.

**Comment by E4002X3102** [comment]
Updated IC2, RebornCore and TechReborn with the latest versions in curse, and it worked. Thank you and sorry for wasting your time.
In case anyone stop by with similar problems in the future, here's the version no. that worked:
IC2: 2.7.59-ex111
RebornCore: 1.11.2-2.16.1.115-universal
TechReborn: 1.11.2-2.3.3.174-universal
