### ISSUE TITLE
"Basic Machine Frame" recipe produces 12 "HV Cables"

### ISSUE THREAD

**Issue by Krowerom** [TechReborn/TechReborn#1143]
Hi, I am trying to run your mod for my server as the 'tech' mod.  At first, I thought there was an incompatibility, but I have reduced the mods to just TechReborn and RebornCore and still get the same issue.

**Running Server with:**
- Forge 14.21.0.2334 (1.12)
- TechReborn 1.12-2.4.1.56
- RebornCore 1.12-3.0.4.44

**Description of issue:**
Attempting to craft a Basic Machine Frame (8 refined iron in 'chest' shape) results in 12 HV cables.
I get the same result using 3 refined iron in a 'slab' shape.

**Comment by modmuss50** [comment]
Is it causing any issues with other mods recipes? or is it just TechReborns?

**Comment by Krowerom** [comment]
Hi :) that was fast!

I reduced my server to only have TechReborn, I will check out another mod and get back to you.

**Comment by Krowerom** [comment]
My server has very few mods (partly because there aren't many 1.12 mods yet!) and I am struggling to find a mod with a recipe that has the 'slab' shape and 'chest' shape using the same materials to produce different items. I can't verify that it affects any other mods.

I have noticed that there is an updated Forge (2335) released today, I will try it on that in case it's a general Forge issue.

**Comment by modmuss50** [comment]
Yeah, thanks for looking into it. Forge still has some issues that will need clearing up, and I know they plan to rewrite the way things are registered soon.

**Comment by Krowerom** [comment]
Can you tell me which version of forge you used when updating to 1.12, modmuss? I've tried the two latest Forge releases (2334 and 2335) and both have this recipe issue.

**Comment by modmuss50** [comment]
The newest is going to be your best bet. I will have a look into this tomorrow as its getting late here now.

**Comment by Krowerom** [comment]
no worries - thanks for your help too :)

**Comment by Krowerom** [comment]
This could be either a 1.12 Forge issue or maybe something wrong in the 1.12 version of TechReborn, I am unable to determine which is the culprit.

I can confirm that using TechReborn-1.11.2-2.3.3.174 with RebornCore-1.11.2-2.16.11.115 on Forge 13.20.0.2315 (1.11.2) and the recipes work fine.

On 1.12 if there is one row full of the refined iron, it produces the HV cables, regardless of the rest of the crafting grid.

**Comment by modmuss50** [comment]
Ok, I tracked the issue down, and made it reproducible on my end. Just need to fix it now

**Comment by modmuss50** [comment]
I think this may be a forge issue, I have opened a bug report on their issue tracker here: https://github.com/MinecraftForge/MinecraftForge/issues/4038

**Comment by modmuss50** [comment]
Ok, ive worked around it, Update to the latest forge (I tested with 14.21.0.2340), and update to RebornCore 3.0.5.46.

Thanks for reporting the issue.
