### ISSUE TITLE
missing recipes?

### ISSUE THREAD

**Issue by Tkdmaster** [TechReborn/TechReborn#1144]
Mod version: TechReborn-1.10.2-2.1.13.219
Forge version: forge-1.10.2-12.18.3.2281

Hello, I'm currently playing the Galactic Engineers mod which has TechReborn in it, and have found that most machines are...uncraftable? One example is the refined iron, its only recipes are nuggets to ingots, and a solid block to ingots, but there's no way to actually make the refined iron itself. Also, soem blocks don't even have a recipe, like the Dragon Egg Energy Siphon. Is there something I'm missing here, or is the mod just...unusable without heavy minetweaker editing?

**Comment by modmuss50** [comment]
Do you have ic2 in that pack?

**Comment by Tkdmaster** [comment]
IC2 is not in the pack, no. I have tried adding that in myself just to see if that'd help, but still nothing.

**Comment by drcrazy** [comment]
Not reproducible in 1.12.1
Refined Iron ingot produced by smelting iron ingot in any kind of furnace. Dragon Egg Energy Siphon is WIP.
