### ISSUE TITLE
Missing Lang on JEI

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1148]
![as](https://user-images.githubusercontent.com/24831406/27480159-882221c4-581f-11e7-8460-f2a70a285442.PNG)
used forge 2347, TechReborn-1.12-2.4.5.92-universal, jei_1.12-4.6.0.65
i forgot to check but i think all machines or blocks or items like this

**Comment by modmuss50** [comment]
Fixed via PR

**Comment by ghost** [comment]
thanks.

**Comment by ghost** [comment]
uhm, just wanted to ask a little thing, modmuss, are you willing to add jetpacks at anytime? it would really be beauty. thanks again.

**Comment by modmuss50** [comment]
Yeah, I have loads of idea, just not enough time.

**Comment by ghost** [comment]
oh thats nice. i hope you have enough free time for your hobbies.
