### ISSUE TITLE
Suggestion - In world Multiblock previews. 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#115]
Have you guys seen Magneticraft?

Video skips to correct time, in German but the point gets across.
https://youtu.be/zUG8Ss7Mtlc?t=1581

Right click on the base machine, it shows an in world ghost block image of what the multiblock should be. Would be extremely helpful to new and old users alike.

**Comment by modmuss50** [comment]
Thats a cool idea, I dont want to steel it from them but we could do something like this.

**Comment by TheQuantumGeneral** [comment]
Botania has a similar system too.

https://imgur.com/a/myxI2

**Comment by gigabit101** [comment]
I did think of something similar but I'm not sure how to render it yet ;-)

**Comment by modmuss50** [comment]
@gigabit101 ive added an example render api (Its from botania) for this to show you how to do it, Im not sure how you want to add pages for it

**Comment by gigabit101** [comment]
@modmuss50 I will take a look when I get some free time

**Comment by gigabit101** [comment]
maybe we just wont a button on the multiblock page in the PDA

**Comment by modmuss50** [comment]
At the moment I added a button to show an example multiblock that when toggled will render at the players cross hair.

**Comment by Carbon-Ghost** [comment]
can we have a config for that ? as it will be able to bypass forcefields & warded blocks :/

**Comment by modmuss50** [comment]
Why? Its just a render for the blocks. It does not place blocks.

**Comment by Carbon-Ghost** [comment]
Oh, but like there won't be the shift-right click places blocks in phantom blocks ? But it's still annoying if someone prank you with phantom blocks everywhere :P

**Comment by modmuss50** [comment]
It is all just a client side render, it does show for other players. You can just place a block in the space that it is in. but if another block is there it wont replace it.

**Comment by Carbon-Ghost** [comment]
Kk then ^^ Also small questions, did I sent you the GUIs ? if yes may you try to include it to GT-R-C ? I am going to test it on a large custom modpack as well as the minetweaker & modtweaker functions with it ^^ and interactions with IC2 classic E-net ^^

**Comment by modmuss50** [comment]
I don't have the guis. And what's GT-R-C?

**Comment by Carbon-Ghost** [comment]
Weird I thought I sent them to you, wait gonna redo it, also it's GT reborn classic

**Comment by modmuss50** [comment]
they might be on the todo.

**Comment by modmuss50** [comment]
Got them sorry https://imgur.com/GGGgfZp,TBaiLjv,g28l7Ak#0

**Comment by Carbon-Ghost** [comment]
^^ no problem, also once a new version of GT-R-C with all that is released, may you notify me, I want to test it asap ^^
