### ISSUE TITLE
[1.10.2] RFTools storage scanner interaction with TechReborn inventories

### ISSUE THREAD

**Issue by GreatestFool** [TechReborn/TechReborn#1151]
I made a thread about this on /r/feedthebeastcrashes and a guy over there [helped me understand what this error message meant](https://pastebin.com/uSm4yDPp). He also told me I should notify you about this because it didn't seem like it was a RFTools problem.

When a TechReborn machine is within the range of the storage scanner, it prints an error in the server terminal every time it is opened remotely with a tablet or through the scanner itself. It does not crash the game or anything and everything seems fine, I only noticed it when I was offline and checked the server and saw it.

I don't know if this is a known problem or not, so I hope I'm not annoying you guys with this.

**Comment by modmuss50** [comment]
Log link dead, and 1.10.2 issue. Re open if still an issue in 1.12.
