### ISSUE TITLE
Adding Custom fuel sources to different generators

### ISSUE THREAD

**Issue by myd01** [TechReborn/TechReborn#1153]
It seems like you can't add custom fuel sources for generators(like gas turbine), or at least I didn't see it in the minetweaker support section in the wiki. I'm currently working on a modpack , I would appreciate it if you can work on that.

**Comment by modmuss50** [comment]
That should be possible

**Comment by myd01** [comment]
Wow, that was quick. Well, I guess I will go back to this page to check if there's any new change every now and then.Thanks for replying though.     :3

**Comment by modmuss50** [comment]
```
mods.techreborn.fluidGen.addThermalFluid(<liquid:water>, 10);
mods.techreborn.fluidGen.addGasFluid(<liquid:water>, 10);
mods.techreborn.fluidGen.addSemiFluid(<liquid:water>, 10);
mods.techreborn.fluidGen.addDieselFluid(<liquid:water>, 10);
```

number being the amount of power (in eu) that is generated per mb
