### ISSUE TITLE
[1.10.2] Windmills drop a machine block despite needing only 1/2 of a machine block to craft

### ISSUE THREAD

**Issue by dmarcuse** [TechReborn/TechReborn#1154]
When breaking windmills without a wrench, a machine block is dropped. However, the windmill recipe gives two windmills per machine block, so you're effectively gaining 4 iron every time if you craft and then break windmills.

**Comment by modmuss50** [comment]
Humm, I think the easiest way to fix this is to just make them drop themselves

**Comment by Skillotic0703** [comment]
![image](https://user-images.githubusercontent.com/12701912/27634985-bac6cdd4-5c05-11e7-9221-00d1b60d695f.png)
Windmills should be crafted like this normally so they should effectively drop a machine block.
The easiest fix is to change the recipe!

**Comment by Skillotic0703** [comment]
One generator and 4 carbon plates!

**Comment by dmarcuse** [comment]
I like the carbon plates recipe, it forces you to get some basic infrastructure set up (compressor and a generator) and balances it a little better too.

**Comment by dmarcuse** [comment]
Thanks!
