### ISSUE TITLE
[1.12] Industrial Grinder bugs

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1155]
Forge 14.21.1.2387
Tech Reborn 2.6.0.119
Reborn Core 3.0.4.45

- There are two slots, one for item input and one for liquid input but only the top one works and it can input items and liquids. The second slot is completely useless.
- Once you fill some quantity of liquid into the industrial grinder and use the industrial grinder, the liquid gets consumed but the display doesn't get updated. So you still think that you have 16 bucket whereas you have 0.

**Comment by drcrazy** [comment]
Slots 1&3 are used to store input ingredients. Fluid required for grinding and item being grinded.
Slot 2 used to store empty buckets\cells used from slot 1. 
![image](https://user-images.githubusercontent.com/1382352/29466578-10e6ae06-8446-11e7-86aa-c1f3107669b2.png)

Fluid tank is not updated, confirmed.
