### ISSUE TITLE
[1.12] Overclocker upgrade weird behaviour

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1156]
There is always a little pause between the end of the processing of an item and the beggining of the processing of the second item. During this pause, the progress bar shows a negative percentage.

**Comment by modmuss50** [comment]
How many overclockers do you have in the machine?

**Comment by Skillotic0703** [comment]
With 3 upgrades it shows -1% and with 4 upgrades it shows -50%. But it think that it works fine with 1 or 2.

**Comment by Skillotic0703** [comment]
The percentage is different in every machine. For example 4 upgrades in industrial centrifuge displays -20%.
It also depends on the recipe and the time it takes.
