### ISSUE TITLE
[1.12] Shift-clicking is weird on TR GUIs

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1157]
When shift-clicking items to put them in a slot, they transfer but they are still displayed in the player's inventory and they are not displayed in the machine's slot. On the contrary, when shift-clicking to take off items from a TR inventory, they are still displayed in the inventory but not in the player's inventory. The displaying updates when going out of the GUI.

**Comment by Skillotic0703** [comment]
It also updates when trying to pickup the ghost items!

**Comment by modmuss50** [comment]
yeah, I noticed this. I will take a look at some point.

**Comment by tterrag1098** [comment]
:+1: to this, I might look at the code myself. It even seems to behave different on client/server as an item will sometimes end up somewhere else once I close the GUI.
