### ISSUE TITLE
[1.12] Chemical reactor crash

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1159]
Crash report: https://pastebin.com/0N4qWC0T
Steps to reproduce:
- Put 4 overclocker upgrades in a chemical reactor
- Put 1 stack of melon and 1 stack of gold
- Enjoy your crash!

**Comment by modmuss50** [comment]
Can confirm

**Comment by modmuss50** [comment]
Ok, it looks like the issue is because with the overclockers the process time was less than a tick, so I have put a limit on the process time, so it cannot go bellow 1 tick
