### ISSUE TITLE
Thermal Generator balance

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#116]
Thermal Generator appears to generates the same eu/t when sitting next to lava as it does when it consumes lava. Seems to be pushing around 1000 eu/second, for such a cheap machine its better than 1000 solar panels. If its going to be a passive generator, 1eu/t or something please.

**Comment by Carbon-Ghost** [comment]
Here is how it's supposed to work by default without counting configs :+1: 
- Is 1.5 more efficient with EU generation when supplied lava, basically it produces 1.5 more time energy from the same bucket of lava as the Geothermal does. 
-Produces 1 eu/tick per lava block next to it.
