### ISSUE TITLE
1.12 RFTools Control/TechReborn Crash

### ISSUE THREAD

**Issue by Razorfin8** [TechReborn/TechReborn#1161]
Pastebin: https://pastebin.com/YaHH9VVA
RFTools report: https://github.com/McJty/RFToolsControl/issues/96
I'm pretty sure this is RFTools related and I already submitted an issue to mcjty but it does involve tech reborn so I'm gonna post here too. 

Modpack ATM3
mod version: whatever ATM3 is using. 

Basically in a creative world, I made a windmill and watermill farm.  The windmill consisted of 4 windmills going into a RFTools Powercell (since they convert and are wireless) and 10 watermills going into a RFTools powercell; both are using glass cables.  I made link cards for the powercells and when I inserted the card into the powercell, i got a crash.  The card did make it into the power cell cause i get a crash whenever I load the world.  Again, pretty sure this is mcjty's side but thought i would post here anyway.

**Comment by modmuss50** [comment]
Yeah, looks a lot like his issue, I will leave this open just in case.

**Comment by Razorfin8** [comment]
Mcjty replied to the report on his github, according to him it looks like it actually is your mod, heres his reply

"It seems that TechReborn is trying to send energy to the powercells clientside which is not legal.
