### ISSUE TITLE
[1.12] RetroGen seems to not working

### ISSUE THREAD

**Issue by ExDomino** [TechReborn/TechReborn#1162]
Forge : 14.21.1.2387
RebornCore : 3.2.1.77
TechReborn : 2.6.1.124

Hello, I have activated RetroGen to generate ores in my old world but it seems to not working. No ores from your mod seems to be generated in old chunks, even with "retroGenOres" at true in "config/teamreborn/techreborn/ores.json". We have started a vanilla world on our server and we plan to install your mod without reseting our map. Thank in advance. Ores are generated in new chunks though.

Also, the procude of other mods retrogen indicates that I have to turn off this feature when all my old chunks are regenerated. But I don't know me what chunk is old or new. I'm not alone on my server. Is this retro generation during the world starting? Or I have to re-visit each old chunks manualy before turning off this feature? Thank in advance again.

**Comment by modmuss50** [comment]
I will test it to see if its working or not.

But the way it works is when a chunk is loaded(not generated) it checks to see if the chunk has allready been populated using our world generator, if it hasnt it should retro gen. So yeah you will need load all the old chunks to find ore in them. I dont think there is a downside to leaving it enabled

**Comment by ExDomino** [comment]
Do I have to set the feature to off after? Or I can let it on? How this feature works in order to check if a chunk need to be retro generated or not?

**Comment by modmuss50** [comment]
it wont "re-retro" gen a chunk, so there shouldn't be any issue in leaving it on.

**Comment by ExDomino** [comment]
The mod will memorize all regenerated chunk? How? By a file, for example, in the world folder?

**Comment by modmuss50** [comment]
By storing a tag in the chunks NBT data

**Comment by ExDomino** [comment]
So, if the retrogen doesn't work, trying to enable it will make that the old chunks will never have the new ores even after the correction of the bug?

**Comment by ExDomino** [comment]
Retrogen really doesn't work. I explain : I tested in creating a world without any mod and then adding your mod (with retrogen at true) and re-explore the same world. After, I created two new worlds with the exact same seed and get to the same location. You mod seems to generate ressources at the same place on world 2 and 3 (the worlds where chunks was generated with your mod) but no ressources was retro-generated on world 1 (where chunks was generated before installing your mod). This proove that your retro-generation doesn't work at all, or that your mod ignore the "retroGenOres" setting on "ores.json" line 4, or the retrogen needs to activate another setting elsewhere in the config.

Also, your retro-generation only work on dimension 0 so overworld, right?
Can you make that work also in the Nether and the End?

Edit : In your code, retrogen seems working server-side only. I will try server-side to see if retrogen is working or not. Tested server-side, still not working.

**Comment by ExDomino** [comment]
Forge : 14.21.1.2387 <not upgraded>
RebornCore : 3.2.3.83 <upgraded from 77 to 83>
TechReborn : 2.6.2.139 <upgraded from 124 to 139>

Retrogen still not working.

**Comment by Jeyge** [comment]
The line in Core.java which would allow retro gen to work is commented out and has been as far as I can tell since July of 2016.  Fixing that will lead to many other problems though with the retro gen code.
//MinecraftForge.EVENT_BUS.register(worldGen.retroGen);
