### ISSUE TITLE
[Suggestion] Adding sound to machines (ex.: Electric Furnace)

### ISSUE THREAD

**Issue by ExDomino** [TechReborn/TechReborn#1163]
Hello, my suggestion is simple : adding sound to machines. Ex.: even the vanilla furnace has sound, but your machines are silent. Can you make like IndustrialCraft and add sounds to your machines please? Thank you very much in advance. ^_^

**Comment by modmuss50** [comment]
Yeah I have wanted to do this for a while. Just need to find some good sounds.

**Comment by modmuss50** [comment]
Done

**Comment by ExDomino** [comment]
Thanks. ^_^

**Comment by ExDomino** [comment]
Updated to 2.6.6.151. Still no sounds.
Maybe it's for the next version?

Edit : I wrote the bad version number, it's the 151, not the 144.

**Comment by ExDomino** [comment]
Updated to 2.6.8.157. Still no sounds.
