### ISSUE TITLE
[1.12] Oil fails to render a texture in the world

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/TechReborn#1164]
Hello there,

TR: 2.6.1.124
Reborn Core: 3.2.1.77

Oil loads a broken texture in the world

https://gyazo.com/47b371f3f8c0dec8923c127e14f2f9a8

**Comment by modmuss50** [comment]
Working when I try it on latest forge + RC + TR

**Comment by modmuss50** [comment]
Colossal Chest, not me
