### ISSUE TITLE
(suggestion) wrench pick

### ISSUE THREAD

**Issue by kohlth** [TechReborn/TechReborn#1165]
this idea is a simple yet interesting idea for a pickax and a wrench to use on rotating blocks and picking up machines while having the ability to break blocks

**Comment by kohlth** [comment]
possibly a upgrade-able pic or possibly even a multi tool laser with a wrench?

**Comment by modmuss50** [comment]
This might be possible, but I dont see a real need for it, as most of the time you wont need a pick around your machines. So the wrench does the job.
