### ISSUE TITLE
Vacuum Freezer

### ISSUE THREAD

**Issue by ddthejj** [TechReborn/TechReborn#1167]
I'm playing FTB infinity beyond (which I believe has the newest version of TechReborn) and the vacuum freezer recipe only takes the reinforced glass from TechReborn and not the reinforced glass from IC2. I'm not sure if this is the right place to post this, and I'll be putting it in the FTB infinity beyond forums too, but I just thought I'd let you know. Thanks!

**Comment by ddthejj** [comment]
Also, the singularity compressor can't compress advanced alloy ingots. Also don't know if this is the right place for this.

**Comment by modmuss50** [comment]
Yep this is the correct place
