### ISSUE TITLE
[1.12 - v2.6.1.124] World gen oil has no texture

### ISSUE THREAD

**Issue by VallenFrostweaver** [TechReborn/TechReborn#1168]
As stated above. See image below. :)
![tr oil bug](https://user-images.githubusercontent.com/13642054/27762071-c7cb529e-5e61-11e7-8515-a7bd0fd92dc4.png)

**Comment by modmuss50** [comment]
Do you have the Colossal Chest mod installed?

**Comment by VallenFrostweaver** [comment]
Yes

**Comment by modmuss50** [comment]
Fixed here: https://github.com/CyclopsMC/CyclopsCore/commit/e0b1620bf7d7728cc32e9a58cb89869531999490
