### ISSUE TITLE
1.12 - Mining ore too fast

### ISSUE THREAD

**Issue by ExDomino** [TechReborn/TechReborn#1169]
Forge : 14.21.1.2387
RebornCore : 3.2.1.77
TechReborn : 2.6.1.124

Ores from your mod are mined too fast. You can think by error that you have the good pickaxe to mine it when you don't. For example, trying to mine a silver ore with hands, it take as long as iron ore with a stone pickaxe. You should increase the time needed to mine them please.

Edit : This bug is from a player of my server, but I just mined a Tin Ore from your mod and I didn't any problem at all. I will continue to test on my side.

**Comment by ExDomino** [comment]
It applys on all ores that needs a Iron Pickaxe to be mined. When you use a Stone Pickaxe on them, the fast mining speed could let you think that you have the good pickaxe.

**Comment by modmuss50** [comment]
Seems fine to me in dev. Reopen if its still an issue.
