### ISSUE TITLE
1.12 - In multiplayer, IRON furnaces don't turn red when smelting

### ISSUE THREAD

**Issue by ExDomino** [TechReborn/TechReborn#1170]
Forge : 14.21.1.2387
RebornCore : 3.2.1.77
TechReborn : 2.6.1.124

In multiplayer, when I use an electric furnace to smelt something, the furnace doesn't turn red or something like that. No indication to indicate that an item is still smelting. It's a bit confusing.

By red, I mean the "black" in the model of the furnace, turning red and some fire appear front of it, like vanilla furnace. You also could re-use vanilla smelting sound if you want, until you get your own sounds.

It's maybe the same with all other machines, except solar panels. (I just tested solar panels and furnaces)

**Comment by drcrazy** [comment]
Not reproducible ))
![image](https://user-images.githubusercontent.com/1382352/27762653-021ecd6e-5e7f-11e7-960f-a6842ae0f470.png)

**Comment by ExDomino** [comment]
On multiplayer ? Connected to a server ?

**Comment by drcrazy** [comment]
yes. Test TR server.

**Comment by drcrazy** [comment]
Forge 14.21.1.2387
TR 2.6.1.131

**Comment by ExDomino** [comment]
Ok, I will re-test that on my server.

**Comment by drcrazy** [comment]
on a client. Dunno what forge version on server and same TR version on server

**Comment by ExDomino** [comment]
My server uses the same Forge and TechReborn version than the client.

**Comment by ExDomino** [comment]
On our server, we have this bug. I dunno why you can't reproduce it, but on our server, machines don't change their visual client-side when they are in use server-side. They look like they are not in use.

It's maybe an option? Something wrong? I dunno, but the bug affects all of my players.
Some of them prefer using vanilla furnace instead, because of this bug.

This bug is only when we are connected to a server. In singleplayer the furnace change its stade without any problem, except the Iron Furnace.

So, in singleplayer, the problem only concerns the Iron Furnace when the Electric Furnace works correctly. In multiplayer, the problem concerns both the Iron Furnace and the Electric Furnace. I just tested.

The versions I noted on my first message are the same for the client and the server.

**Comment by ExDomino** [comment]
Re : Bug maybe fixed in 134, I updated both Reborn Core and Tech Reborn to their latest version and all works perfectly well. I created my server two days ago and didn't notice that new versions of your mod was released in the meantime.

However, the problem about Iron Furnces is still not fixed. Iron Furnaces still don't change their state at all!

**Comment by ExDomino** [comment]
Updated to 2.6.6.151, Iron Furnace still not red in multiplayer when in function.

Also, taking a block from them make a kind of client-server sync error when trying to place it in the world. It's a minor issue, the problem is solving by itself after a short moment. Possibly a Forge issue, but the problem only concerns the Iron Furnace. I have no problem with the Electric Furnace.

**Comment by drcrazy** [comment]
![image](https://user-images.githubusercontent.com/1382352/28010771-a589561e-6568-11e7-8dbb-e4edc3ed951d.png)

Confirmed for Iron Furnace

**Comment by drcrazy** [comment]
Sorry, partially confirmed ).
It is turning red but only bare visible few pale red dots. 
![image](https://user-images.githubusercontent.com/1382352/28010836-e6346d8e-6568-11e7-8b86-0cad519670d4.png)

I suggest to make them more bright to be in line with vanilla furnace visibility of burning and with TR electric furnace.

**Comment by tterrag1098** [comment]
Yeah seconding this, the active texture is barely distinguishable.

**Comment by modmuss50** [comment]
Ok, so it's just the texture. That's an easy change.

**Comment by modmuss50** [comment]
Fixed ^
