### ISSUE TITLE
[1.12] Ore Dictionary registration is all over the place

### ISSUE THREAD

**Issue by ChloeDawn** [TechReborn/TechReborn#1171]
**Mod version:** [2.6.1.124](https://minecraft.curseforge.com/projects/techreborn/files/2443226)

Here's a list of ore dictionary entries my mod reports back when TR is in the instance
[gist/e05acb8b2feefa4916ae3e8d8cc04e4b](https://gist.github.com/anonymous/e05acb8b2feefa4916ae3e8d8cc04e4b)

Normally, most mods wouldn't care, however MoreChisels registers a chisel for every gem and ingot in the ore dictionary, and generates it's registry names by passing ore dictionary names to the following method
```java
public static String format(String input) {
    return input.replaceAll("[A-Z]","_$0");
}
```

This causes a crash as your entries result in my mod registering multiple identical registry names to the instance.

**Comment by Prospector** [comment]
@modmuss50 leave this to me

**Comment by modmuss50** [comment]
Ive got it
