### ISSUE TITLE
1.12 : Machines are disconnected from network when chunks are unloaded

### ISSUE THREAD

**Issue by ExDomino** [TechReborn/TechReborn#1173]
Minecraft : 1.12 < Java 8 >
Forge : 14.21.1.2387
RebornCore : 3.2.3.83
TechReborn : 2.6.2.139
Mode : Multiplayer
Same versions for both client and server.

Machines are disconnected from energy network when chunk unload and reload. Fixing this issue need to remove the cable and then replace it. Else, the machines runs out of power when the Battery Box is full.

And note that when you remove a cable, it loses its insulation.
In multiplayer, disconnect and reconnect can cause the bug as well as fixing it. It's strange.

Edit : A machine seems to disconnect itself from the Energy Network when it finishs a work, or when it finishs to being recharged. As I said, it's really strange.

**Comment by ExDomino** [comment]
When I removed a cable from my network and replaced it, the machines begin to work proprely for a while, but when I removed it, the machines started to continue working just like the cable was still there but a little bit different (jumping from 100% to 99% to 100% all the time when with the cable they stay at 100%). I'm really not sure what is that bug but I think it's either that machines disconnect themself or they continue to being connected even if a cable is removed. It's a severe bug according to me.

**Comment by ExDomino** [comment]
I think the problem comes with the Battery Box that sometime ceasses to output its energy.

**Comment by drcrazy** [comment]
Do you have IC2?

**Comment by drcrazy** [comment]
Not reproduced 
Setup: batbox with battery inside->cable->electric furnace
I've put stack of ore in furnace. And flew away. 
After returning to batbox it is working fine, draining battery and providing energy for furnace.
