### ISSUE TITLE
rolling machine recipes missing

### ISSUE THREAD

**Issue by Willy347** [TechReborn/TechReborn#1174]
MC: 1.12
forge: 14.21.1.2387
TR: 2.6.1.124 and 2.6.2.139

the rolling machine doesn't have any recipes in 1.12 so there is no way of making coils. by that logic there is no way to make a blast furnace or make steel so it is not possible to progress any further in the mod

**Comment by modmuss50** [comment]
Ah, I think I know whats up, thanks for reporting 👍
