### ISSUE TITLE
compatibility issue 1.12

### ISSUE THREAD

**Issue by Willy347** [TechReborn/TechReborn#1175]
versions above 2.6.1.124 are not compatible with the atm 3 modpack
crash report in attachment 
[crash-2017-07-02_23.21.04-client.txt](https://github.com/TechReborn/TechReborn/files/1118115/crash-2017-07-02_23.21.04-client.txt)

**Comment by modmuss50** [comment]
Update reborn core

**Comment by Willy347** [comment]
sorry
