### ISSUE TITLE
1.12 - Water mill produces too many energy (config files don't accept float value for energy)

### ISSUE THREAD

**Issue by ExDomino** [TechReborn/TechReborn#1176]
Forge : 14.21.1.2387
RebornCore : 3.2.3.83
TechReborn : 2.6.4.144

Hello, I just tested both Water mill and Solar panel. I noticed that a single Water mill placed into water produces two times more energy than a Solar panel. In fact, the Water mill produces as energy as water connected to it. So if the Water mill is inside water with water on each sides, it will produces 4 FE/tick (day and night) when the Solar panel only produces 1 FE/t (day only) and is more expansive. My suggestion is to divide the Water mill production by 10. It could only produce a maximum of 0.5 FE/t if totally immerged.

Config files don't accept float values, so you cannot modify the energy of the Water mill for 0.1. Also, the default value for Wind mill is indicated 1.25 but is set to 2 without modification.

**Comment by Skillotic0703** [comment]
The problem is that the windmill should be more expensive than the solar panel!

**Comment by ExDomino** [comment]
Windmill more expansive, ok. But, what about the Watermill ?
You know, that thing you put into the water and that generates a tons of energy.

**Comment by Skillotic0703** [comment]
With GT, the water mill used to be crafted with aluminium ingots so yeah it should also be more expensive
!
