### ISSUE TITLE
Data Storage Circuit still has a place holder recipe

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#118]
It has both the correct recipe and a placeholder recipe
![dd](https://cloud.githubusercontent.com/assets/7843312/9363652/fc37c642-46ea-11e5-8c00-ee806beb5b61.PNG)
![ddd](https://cloud.githubusercontent.com/assets/7843312/9363653/fc398554-46ea-11e5-848e-85dd16bbf0d3.PNG)

**Comment by Carbon-Ghost** [comment]
I have a request for the assembling machine, may you make it able to have 3 slots input and 3 slots output please ? It will allow to have catalysts if I want to use a Minetweaker script :)

**Comment by modmuss50** [comment]
@Carbon-Ghost can you make that a new issue, it will get lost here
