### ISSUE TITLE
[1.12] Client kicked when looking at the sawmill interface.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1182]
I have a working sawmill, and when I open it now it kicks me, here is the stacktrace from my client.

Nothing is shown on the server.

https://gist.github.com/ProsperCraft/a1cfc77e47c822bc428e53546dc4c10f

**Comment by modmuss50** [comment]
Huh, is this happening when you open the gui? or after you click something in the gui?

**Comment by modmuss50** [comment]
Ah, got it

**Comment by ProsperCraft** [comment]
Opening it, I had kicks when standing near it as well but have not isolated my client log on those
