### ISSUE TITLE
Crash with Buildcraft 7.99.5

### ISSUE THREAD

**Issue by MonzterAssassin** [TechReborn/TechReborn#1185]
https://pastebin.com/0v1hMWvg

I'm running newest versions on 1.11.2 (and I understand you're on 1.12) but according to the dev on Buildcraft Discord it was because TR was using BC 7.99.4's API.

**Comment by modmuss50** [comment]
Yeah, that needs fixing.

**Comment by Terpo** [comment]
good that it is only a small issue :) 
changed dependency of bc to 7.99.6 in https://github.com/TechReborn/TechReborn/blob/1.11.2/build.gradle#L123

and https://github.com/TechReborn/TechReborn/blob/1.11.2/src/main/java/techreborn/compat/buildcraft/BuildcraftCompat.java#L54
```
FluidPowerManager.fluidPowerValues.put(fuel.getFluid().getFluid(),
					(double) fuel.getPowerPerCycle() / RebornCoreConfig.euPerFU); 
```

**Comment by modmuss50** [comment]
Fixed by removing the FluidPowerManager thing as its no longer used in TechReborn. Once BC is on 1.12 and stable I will update it to support our new fluid power system.
