### ISSUE TITLE
Oil texture bug on (1.12)

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#1186]
http://i.imgur.com/Kiuwo5a.png

**Comment by modmuss50** [comment]
This is because you are using an older version of colossal chests. Please try updating that.

**Comment by ImAK9** [comment]
What if i told you i don't have it? lol

**Comment by ImAK9** [comment]
What has Colossal Chests todo with Tech Reborn?

**Comment by modmuss50** [comment]
Humm, that mod used to break our fluid rendering. Can you try with just TechReborn and Reborncore?

**Comment by ImAK9** [comment]
Sure

**Comment by modmuss50** [comment]
I just checked with the colossal chests dev and he hasn't pushed his fix to curse yet.

**Comment by Kris1432** [comment]
Will be looking into stress testing this bug.

**Comment by tterrag1098** [comment]
This is happening on ATC as well, though we do have CC

**Comment by modmuss50** [comment]
It's happening on unstable without CC, but works fine on its own. So I assume another mod is breaking it. But I guess we are doing something wrong as it's only our fluids. ¯\_(ツ)_/¯

**Comment by covers1624** [comment]
https://github.com/CoFH/Feedback/issues/366 ??

**Comment by modmuss50** [comment]
Could well be that, I will take a look when I get home on Monday. Thanks for pointing that out.

**Comment by Kris1432** [comment]
from looking at the CoFH issue, this seems to be resolved, can you confirm that this is fixed with the latest versions? @PrinceApache

**Comment by covers1624** [comment]
I linked the issue as a similar thing in the backend of the fluid stuff might be happening, this mostlikely has no direct relation to the CoFH issue.

**Comment by modmuss50** [comment]
I will test with the latest unstable update to see if its still an issue.

**Comment by modmuss50** [comment]
Seems to be working in the latest unstable update, can you guys test by updating all your mods to see if its been fixed? If it has I will close this issue.

**Comment by Kris1432** [comment]
I wanna say its fixed on our end, go ahead and close this issue.
