### ISSUE TITLE
[1.10.2] Fusion reactor problems

### ISSUE THREAD

**Issue by dmarcuse** [TechReborn/TechReborn#1187]
First off I'm not sure if these is fixed in 1.11 or 1.12 versions of the mod, if they are please let me know.

I've found a few issues with the fusion reactor that make it impractical and difficult to use:

- The reactor seems to always consume the startup energy, even when continuing from a previous cycle - e.g. put in 2 tritium and 2 deuterium cells and charge it up, when the first cells are completely used, the startup cost will be taken again.

- When the reactor is charging to start the reaction, fluxducts attached to the top or bottom of the controller seem to drain the internal buffer instead of allowing the reactor to charge up. This does *not* happen when using TechReborn or IC2 cables.

- There doesn't seem to be a way to automate loading/unloading of cells/items. Itemducts will connect to the controller, but can't actually insert/extract items.

**Comment by Vectrobe** [comment]
This applies to the 1.12 builds as well, the reactor's basically unusable at this point as neither does it produce much power (it's not supposed to use energy after the first start, it's much like glowplugs in a diesel engine), nor can you actually automate it. The only thing it's good for currently is iridium and platinum, even then the UU matter method is way cheaper... (way too cheap actually, the fusion recipes are supposed to be a fraction cheaper than the UUM needed...)

**Comment by dmarcuse** [comment]
Yeah, it's disappointing. Fusion reactors provided a fun end goal for me but they're not even worth it in the current state.

**Comment by Vectrobe** [comment]
I'm actually considering now whether we should have a second reactor tier, the second tier being the newer version that greg made that used liquids directly. The gimmick then being that the second tier only runs off the helium3 recipe, needing either a limited He source or a tier 1 reactor running H2+H3, the resulting plasma is then piped out to generators.

I feel this makes a lot of sense in a design perspective and allows a smooth, upwards progression while having the awesomeness that is the newer generation reactor, we may nerf the basic reactor however to be more of a crafting machine than a high tier generator, but still fix it to be more useful than it currently is.

Now what other recipes could we have with fusion...

**Comment by dmarcuse** [comment]
Honestly I'd prefer if the current reactor was just scrapped and replaced with the larger, more modular one, maybe with the recipes rebalanced as needed. It would also solve the issue of only having 6 sides available for all forms of I/O with the current one. To keep the progression, it could work similarly to the reactors from GT4, where you can upgrade the casings and coils to access new recipes.

If both are kept, I don't really see the point in limiting the tier 2 reactor if it's supposed to be an upgrade from the first one - disabling recipes like iridum and UUM on the tier 1 reactor would make more sense to me, or making it less efficient or slower than the tier 2 reactor.

**Comment by joshricker** [comment]
Is this actively getting worked on? I'm all for the larger reactor. But I wish it would say in game that the fusion reactor was useless at making power. Just crafted and tried to use it in an Age of Engineering pack and sucks to find out I've wasted the better part of two days getting the infrastructure and materials needed for this thing.

**Comment by craft90** [comment]
I concur with the others in this thread. I have only tested the fusion reactor in creative but it's really disappointing that it has to restart all the time. As it's now it consumes way more power than it generates. It makes the fusion reactor pretty useless, except for making materials I reckon.

**Comment by drcrazy** [comment]
It shouldn't reset now. I\o issues duplicated in #1237
