### ISSUE TITLE
None of the gears have recipes

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#119]
The Bronze, Iron, Titanium, Steel and Tungstensteel gears don't have recipes.

Not sure if you intend to use the old gregtech recipe of 4 rods, 4 plates and a wrench, but another option, the new sort of community standard ala COFH mods is 4 ingots around an iron ingot. 

eg, 

![ffff](https://cloud.githubusercontent.com/assets/7843312/9364165/5098db06-46ee-11e5-8454-b1682446ba14.PNG)
![ddd](https://cloud.githubusercontent.com/assets/7843312/9364166/509adf3c-46ee-11e5-9de8-5cc6301ddc71.PNG)

**Comment by Carbon-Ghost** [comment]
I have another standard to propose, the old BC standard, so you can craft the gear with the vanilla/cofh standard, but if BC is here, you will need to use stone gear for everything except titanium and tungstensteel which would require diamond gears ^^

**Comment by Carbon-Ghost** [comment]
So what option did you used ?

**Comment by modmuss50** [comment]
I did the cofh way, I think I'm gonna go back to the old way.

**Comment by TheQuantumGeneral** [comment]
Would be a lot more #Gregtech appropriate

**Comment by Carbon-Ghost** [comment]
Can you make it using BC gears if BC is detected if possible please ? Will just save me 9001 ln of minetweaker haha xD

**Comment by modmuss50** [comment]
I will see if the bc gears are in the ore dic, if they are I will set the ore dic name for our gears

**Comment by Carbon-Ghost** [comment]
Well, I wanted being able to craft all metal/gems gears with a stone gear as a "base frame" gear ^^

And please config for that for not making me add another layer of 9001 ln of MT script xD
