### ISSUE TITLE
Energy consumption/production tooltip

### ISSUE THREAD

**Issue by Waisse** [TechReborn/TechReborn#1191]
Simple, just add a way of knowing how much each machine consume/produce in-game.

**Comment by drcrazy** [comment]
Any specific machine? Most of them are showing energy usage in JEI.

**Comment by codewarrior0** [comment]
That's the catch. Lots of machines have EU usage assigned to the individual recipes so you can't simply say "This machine uses 10 EU/t". But some machines, such as the generator or electric furnace, *do* have a constant EU usage or output. 

Currently, the tooltips just tell you the maximum transfer rate into or out of the machine. When possible, they should also tell you the machine's constant EU usage or output, or else say something like "EU usage varies according to recipe."

**Comment by drcrazy** [comment]
For machines (not generators) JEI usually says how much it will use per recipe. If there is a machine without energy usage shown in JEI - please, name it here

**Comment by codewarrior0** [comment]
All of them.

**Comment by drcrazy** [comment]
It is not so.

For example, Alloy Furnace energy usage shown in JEI:
![image](https://user-images.githubusercontent.com/1382352/30330125-dcc11c7e-97dc-11e7-9803-6772fc1bc0c6.png)

**Comment by codewarrior0** [comment]
I thought this is what we're talking about.

![image](https://user-images.githubusercontent.com/307683/30330228-30aaea3a-9770-11e7-9c53-255e8598aab9.png)

**Comment by modmuss50** [comment]
We could display the average or something. ¯\_(ツ)_/¯

**Comment by drcrazy** [comment]
What do you mean 'average' ? Across all recipes?

**Comment by modmuss50** [comment]
Closing as its not really possible without a lot of work, look at the recipe in JEI to see how much power it requires. The tool tips are the max values.
