### ISSUE TITLE
[1.12] Crash with Industrial Foregoing

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1194]
The 1.12 version crashes when Industrial Foregoing is installed with it. I believe it has something to do with the fact that its Plastic Sheets use the ore dict entry for rubber.

https://pastebin.com/Sk6pnPXG

**Comment by modmuss50** [comment]
Huh, ok. That shouldn't be too hard to fix.

**Comment by CluelessPhil** [comment]
Oh thank god some noticed this too :)

**Comment by TheLimePixel** [comment]
Hmm, in the Reborn Core changelog you said it's fixed, but I now get a new one: 
https://pastebin.com/J7jgRq1x

**Comment by modmuss50** [comment]
Did you update TR?

**Comment by TheLimePixel** [comment]
oh, it didn't show up on CF a few minutes ago. It had the bug where it showed the last time it updated, but it didn't show the update.
