### ISSUE TITLE
1.10 Crash while breaking cables.

### ISSUE THREAD

**Issue by Matikari** [TechReborn/TechReborn#1195]
Modpack used is "A Grim Life" through the Twitch Curse Launcher. We just recently added Tech Reborn to the pack. We came to have the issue where we were unable to pickup cables, discovered server side but is also a problem on a SP game. Testing through mod disabling we were able to get cables to be picked up once we disable both Better with Mods and More Bees (Forestry).

On a SP test I reduced the pack to only have Better/mods, Forestry/More Bees and tech reborn. Each test was done on a newly generated world.

Crash when attempting to break cable
----------(Breaks by hand, Breaks by wrench holding L-mouse, Crash when using an Iron Pickaxe)
[crash-2017-07-10_08.54.11-client.txt](https://github.com/TechReborn/TechReborn/files/1135932/crash-2017-07-10_08.54.11-client.txt)

Removed Better/Mods - Crash on game loading
[crash-2017-07-10_08.55.17-client.txt](https://github.com/TechReborn/TechReborn/files/1135936/crash-2017-07-10_08.55.17-client.txt)

Readded Better/Mods - Removed More Bees - Crash on Trying to break cable
-----------(Breaks by hand, Breaks by wrench holding L-mouse, Crash when using an Iron Pickaxe)
[crash-2017-07-10_08.57.44-client.txt](https://github.com/TechReborn/TechReborn/files/1135946/crash-2017-07-10_08.57.44-client.txt)

Removed both Better/mods and More bees while Leaving in Forestry
----------Works just fine, no issues with breaking the cables

Results with the Modpack to full
-------Nothing with Hand/Wrench or Tools while holding L-mouse does no interaction, no tool swinging.
Will crash without a log if I move my aim away from and back onto the cable while I hold the L-Mouse.

Full pack with only Better/mods and More Bees disabled
------------Works just fine, no issues with breaking the cables

**Comment by DaedalusGame** [comment]
cursory looks at the relevant classes makes me assume that cable multiparts might not expose a BlockStateContainer with the block field set...?
No clue about that CTD tho.

**Comment by drcrazy** [comment]
Not reproducible in 1.12.1
