### ISSUE TITLE
[1.12] Dupe bug with TE support

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1198]
By the looks of it you've created a process of duping materials with your TE integration.  The Compressor uses only 1 of an item for making a plate, while the TE Pulverizer turns 1 plate into 9 of the corresponding dust allowing you to have 9 times the amount of the certain material that you started with:
 
![image](https://user-images.githubusercontent.com/25333164/28248743-012c4306-6a4a-11e7-87a3-b10b2d62c1d8.png)

**Comment by modmuss50** [comment]
Humm, yeah. Good point.

**Comment by Skillotic0703** [comment]
Lign 50 in techreborn/compat/thermalexpansion/RecipeThermalExpansion.java.
Change "RecipeMethods.getMaterial(plate, 9, RecipeMethods.Type.DUST));" to "RecipeMethods.getMaterial(plate, 1, RecipeMethods.Type.DUST));"

**Comment by TheLimePixel** [comment]
While we're on this topic, I'd like to mention that you also forgot to fix the gem-plate and redstone-plate recipes in the Compressor.
![image](https://user-images.githubusercontent.com/25333164/28279604-4c0048d2-6b21-11e7-9ff9-1e74f9eb53cb.png)

**Comment by modmuss50** [comment]
Fixed.
