### ISSUE TITLE
Output stack is null or empty

### ISSUE THREAD

**Issue by trilexcom** [TechReborn/TechReborn#1199]
hi Tech Reborn team

i added MalsisDoor and MalisisCore to my pack we have techreborn in 1.12 version installed version number TechReborn-1.12-2.6.9.163-universal when i try to launch the game i get this error msg i wanted to know if its a tech reborn error or should i report it MalisisDoor Mod person, because i only get this error after adding that mod 

here is the pastebin https://pastebin.com/4DPi8sw3

Thank you very much 

Mat

**Comment by Fundryi** [comment]
I have the exact same issue. Hope this can be fixed quick! :)
