### ISSUE TITLE
Disable IC2 Iridium reinforce plate when Tech Reborn is installed.

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#120]
The IC2 version of this plate should be disabled as it bypasses the required rolling machine, macerator and implosion compressor.

**Comment by Carbon-Ghost** [comment]
Or simply change the recipe of it :)

**Comment by TheQuantumGeneral** [comment]
They're ore dict, what would be the point of two types of the same plate?

**Comment by Carbon-Ghost** [comment]
Erm... You have a point, nvm then ;)

**Comment by modmuss50** [comment]
So just remove the recipe?

**Comment by Carbon-Ghost** [comment]
Yup :3 Also I have a small suggestion change to the assembler for allowing more complex recipes with minetweaker ^^ Gonna open a new "issue" for that :D

**Comment by modmuss50** [comment]
ok thanks :)

**Comment by modmuss50** [comment]
Im not sure if all the recipes are in for it? can you check?

**Comment by TheQuantumGeneral** [comment]
Yeah, there is a crafting recipe that should be a rolling machine recipe, for the iridium alloy ingots, but the implosion compressor recipe is in, can do the whole process.
