### ISSUE TITLE
[1.12] Small energy glitch with IC2 glass fiber cable

### ISSUE THREAD

**Issue by lynxx131** [TechReborn/TechReborn#1200]
I am using TR in MC 1.12 with IC2 de-duplication enabled and things are working quite well.

One small thing I noticed is that if I provide too much energy to a TR machine via an IC2 glass fiber cable the machine doesn't explode it does however correctly explode with other cable types such as gold cables.

My test setup is: 

IC2 MFE (512EU/t) -> glass fiber cable -> Industrial Blast Furnace (Explosion expected but doesn't happen)
IC2 MFE (512EU/t) -> gold cable -> Industrial Blast Furnace (Explodes as expected)

For reference:

IC2 CESU (128EU/t) -> any appropriate cable -> Industrial Blast Furnace (Works as expected)

So in most cases explosions work as expected it's just things don't explode when using IC2 glass fiber cable. Also worth noting that if I overpower an IC2 machine with a glass fiber cable it explodes as expected.

Admittedly probably not a huge issue but probably something worth putting on the backlog for when there's time.

Forge Version: 14.21.1.2413
Reborn Core Version: 1.12-3.2.4.86-universal
TechReborn Version: 1.12-2.6.9.163-universal
IC2 Version: industrialcraft-2-2.8.7-ex112

**Comment by Vectrobe** [comment]
probably a energy tier miss-match, modern IC2 (really should have been named IC3) has 5 tiers, TR only has the 4 tiers that were around with gregtech (excluding greg's 5th tier, which is probably where the bug is).

**Comment by drcrazy** [comment]
Not reproducible anymore.

Blast furnace exploded as expected being connected to MFE via IC2 glass fiber cable.

![image](https://user-images.githubusercontent.com/1382352/31691209-f188794a-b39d-11e7-9864-6441e8a3b041.png)
