### ISSUE TITLE
[Suggestion] Remove plates

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1203]
You seem to reproduce a version of Gregtech where plates were not yet implemented. So I would suggest to just remove them because they are useless. They just add an annoying crafting step.

**Comment by Skillotic0703** [comment]
I mean, remove the recipes that use them and remove their crafting recipe. Don't remove the item in itself, it could be useful for modpack makers!

**Comment by Prospector** [comment]
what recipes use them?

**Comment by drcrazy** [comment]
Example of usage: advanced machine block

**Comment by Prospector** [comment]
Oh advanced alloys? Yeah those use plates, and always have.

**Comment by drcrazy** [comment]
A lot of machines in 1.12.1 use plate instead of ingots.
