### ISSUE TITLE
[1.12] TechReborn machines don't explode

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1204]
Battery boxes can accept any voltage without exploding

**Comment by drcrazy** [comment]
How it is connected? I mean using IC2 cables or TR cables?

**Comment by Skillotic0703** [comment]
Even when using IC2 and not respecting tiers, they don't explode.

**Comment by Skillotic0703** [comment]
But it's ok.

**Comment by drcrazy** [comment]
Duplicate for #1252
