### ISSUE TITLE
[1.12] Tooltip problem

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1205]
The MFE and MFSU have wrong tooltips. The MFE I/O 128 EU/t and the MFSU I/O 512 EU/t which is correct!

**Comment by drcrazy** [comment]
Screen plzz

**Comment by Skillotic0703** [comment]
![2017-07-21_15 58 38](https://user-images.githubusercontent.com/12701912/28466688-81b1daa4-6e2d-11e7-8bcc-c7c1716cfef5.png)

**Comment by Skillotic0703** [comment]
The displayed I/O Rate should be 512 EU

**Comment by drcrazy** [comment]
I suspect that 'High' tier is 512 FE or 2048 EU or 512 RF. May I ask you to try to switch tooltip display from EU to FE, please?

**Comment by Skillotic0703** [comment]
No it shows 8192 RF/FE I already verified that!
