### ISSUE TITLE
Couple bugs on the latest 1.12 edition + suggestion.

### ISSUE THREAD

**Issue by Lynxn** [TechReborn/TechReborn#1207]
Testing the mod in a single player world, it seems a lot of the machines are weird. Not only the fact that the furnace *cough* lacks upgrade slots *cough*, but it seems as if energy Transfer is bugged and the items Desync. 
I was play with the IDSU, it accepted power but then didn't give any out, but then randomly decided to start outputting after a couple minutes. The same with the mfsu, yet the mfe seemed fine. As far as I could tell the Adjustable SU didn't want to output at all as well. That and when I go put items in a machine they don't visually appear inside the machine until I close and re open the gui. Then there seems to be some weird cool down in the grinder that is such that when it finishes an item it doesn't start the next item for like half a second. As far as I can tell the basic machines like the grinder and electric furnace are way to slow right now to be viable, ic2 ones are better and they're typically seen as worse compared to most other mods. This is partly due to only being able to have 4 upgrades in the grinder and the furnace not having any. I'll record these if you'd like tomorrow so you can see, and possibly explain a bit more seeing as this is probably sloppy due to it being late and typing on my phone.

**Comment by drcrazy** [comment]
PLease, report individual issues
