### ISSUE TITLE
[1.10.2] Coal Dust makes IC2 Raw Carbon Fiber

### ISSUE THREAD

**Issue by llloyd4** [TechReborn/TechReborn#1210]
The recipe for Raw Carbon Fiber in IC2 and in TR are exactly the same, so when I try to craft the TR one I get the IC2 one instead. This, in turn, leads me down the rabbit hole of making the IC2 Carbon Plate, which can't be used in a TR Advanced Machine Block. So...

Minecraft 1.10.2
TechReborn 1.10.2-2.1.17.233
Reborn Core 1.10.2-2.13.6.142
IC2 - 2.6.234-ex110

**Comment by perci100** [comment]
The techreborn one is shapeless, so move a coal dust one block away from the 2 by 2 grid to create the TR Carbon fibre.
