### ISSUE TITLE
Can't remove recipes from Rolling machine

### ISSUE THREAD

**Issue by FiberSprite** [TechReborn/TechReborn#1215]
Hello, So I'm trying to use craft tweaker to remove a recipe from the machine roller, the recipe for iron bars will not remove. 

The script: http://wolfbrotech.com/admin/pastebin/view/4bfc4d05
The Log: http://wolfbrotech.com/admin/pastebin/view/0dff6326
TechReborn Version: 1.10.2-2.1.17.233
I cant figure it out why the recipe wont remove. can anyone help me?

**Comment by FiberSprite** [comment]
Can anyone help me figure this out, please?

**Comment by drcrazy** [comment]
Not reproducible on latest TR.
script mods.techreborn.rollingMachine.removeRecipe(<minecraft:iron_bars>); removes iron bars,

![image](https://user-images.githubusercontent.com/1382352/30233829-c7dbff10-9500-11e7-8fba-a3c6ef008b54.png)
