### ISSUE TITLE
Can't Macerate Basalt or Marble

### ISSUE THREAD

**Issue by NoctisNocturnal** [TechReborn/TechReborn#1218]
seems like Industrial Craft 2 can't recognize those blocks on the recipe, it simple don't accept, so i can't make calcite dust

**Comment by Skillotic0703** [comment]
You can't even put them in the TR Grinder so that's not a problem with IC2.

**Comment by modmuss50** [comment]
I think this is related to: https://github.com/Chisel-Team/Chisel/issues/507

**Comment by Skillotic0703** [comment]
It also happens with only quark so i don't think so.

**Comment by NoctisNocturnal** [comment]
yep, the other post, its mine too, the thing is... i cant make calcite dust, cuz to do so, i need basalt dust or marble dust, i know it's some kind of conflict, by the way is there a TR grinder?

**Comment by modmuss50** [comment]
Yes there is, it may be disabled if you IC2 though.

**Comment by NoctisNocturnal** [comment]
AHHHHH, probably i've missed that... dam, i even add gregs tech to the mod, to make the dusts craftble... gonna try out, and post it back.

**Comment by NoctisNocturnal** [comment]
nope, i've tried grinder and even industrial grinder, but no luck, gonna try bunch of diferent settings, like with and without IC2, Chisel, and so on, but the thing is, it isn't even showing on the recipes, thanks for all support til now!

**Comment by drcrazy** [comment]
There is no explicit recipe for grinding marble or basalt in TR, unfortunately. It might still work if mod with marble will have it as OreMarble and not just marble.

**Comment by modmuss50** [comment]
I can add it as a recipe if needed

**Comment by drcrazy** [comment]
I'm trying to do that )

**Comment by NoctisNocturnal** [comment]
indeed, i've really tried all sorces of "evil" but no, it changes to a common block, not ore anymore...

**Comment by NoctisNocturnal** [comment]
Ok, now iam totally lost, i've installed only tech reborn, and still have marble and basalt dust, but no basalt ou marble to be grinded, macerated ou any other way possible to turn into dust, so, definitely iam missing something, my minecraft its version 1.10.2 , thanks folks!

**Comment by drcrazy** [comment]
You need to additionally install mod that provide marble itself.

**Comment by NoctisNocturnal** [comment]
yep, but for a stand alone mod, its very wierd...

**Comment by NoctisNocturnal** [comment]
![sem titulo](https://user-images.githubusercontent.com/30579489/28801251-04d99d12-7627-11e7-8de2-9c640734bfe9.png)

Now i've installed Project Red, this mod contains Marble and Basalt, but even now i can't make Dust from both of this items, any light?

**Comment by drcrazy** [comment]
Yes, now it is devs turn to add necessary recipe

**Comment by NoctisNocturnal** [comment]
I've managed to find a way around, add two recipes on the macerator from IC2.

MarbleOreDict:stoneMarble = techreborn:dust@32;
BasaltOreDict:stoneBasalt = techreborn:dust@4;

Thanks for all the support! Hugs!
