### ISSUE TITLE
[v1.12] Some items from TR have not correct energy storage

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1219]
Some items from TR have not correct energy storage:
1. Lapotronic energy orb: 80k FE instead 80m FE
2. MFSU: 400k instead 40m
3. Steel jackhammer: 4m instead 40k
4. Nano-saber: 400k instead 4m
5. Diamond drill: 400k instead 40k
6. Diamond jackhammer: 80k instead 40k
7. Electric treetap: 20480 FE instead 40k

**Comment by drcrazy** [comment]
Lapotronic Energy Orb will have 400M FE
MFSU will have 40M FE
Drill, Chainsaw and Jackhammer will have 40k, 400k and 4M  FE for steel, diamond and advanced versions
Nano saber will have 
Electric treetap will have 40k FE
Nano-saber will have 160k FE

**Comment by drcrazy** [comment]
Fix available on curse starting from TechReborn-1.12.1-2.7.0.205
