### ISSUE TITLE
[1.12] (Version::2.6.10.170) Missing Texture

### ISSUE THREAD

**Issue by PandaPaw** [TechReborn/TechReborn#1221]
The oil is missing texture

**Comment by modmuss50** [comment]
Can you provide a full mod list with versions? First make sure all mods are updated.

**Comment by PandaPaw** [comment]
I am using All the mods 3 on the twitch launcher so all mod are proberly not upp to date, but most of them are because the pack had an upptate yasterday

**Comment by PandaPaw** [comment]
http://i.imgur.com/rRyVupv.png

**Comment by modmuss50** [comment]
I believe this should be fixed, I'm not 100% sure what mod caused it. Can you try again using the latest version of the pack?

**Comment by unkidrik** [comment]
I also have oil texture missing on the same pack. I have unlocked the packed and updated all mods but still have no texture. I have tried on multiple world types, this made no difference.

**Comment by drcrazy** [comment]
Not reproduced in latest ATM3 with all updated as of 5-OCT-2017 mod including forge v2500. 

![image](https://user-images.githubusercontent.com/1382352/31199550-6ed5ab7c-a960-11e7-8671-c235273d9c25.png)
