### ISSUE TITLE
[1.12] Industrial Grinder and Crafttweaker

### ISSUE THREAD

**Issue by tgstyle** [TechReborn/TechReborn#1222]
Trying to add a recipe with null for output stack 2-4 says output stack null or empty. Is this not possible? Input stack 2 as null works fine.
mods.techreborn.grinder.addRecipe(<techreborn:dust:20> * 4, null, null, null, <enderore:ore_ender>, null, <liquid:water>, 20, 128);

**Comment by ZigTheHedge** [comment]
The same here. Reason: CT returns ItemStack.EMPTY instead of null when null is passed in Zenscript. Should be pretty easy to fix: https://github.com/TechReborn/TechReborn/blob/d5a31188013566ca6ecd577c3e09123d5b55e48b/src/main/java/techreborn/api/recipe/machines/IndustrialGrinderRecipe.java#L42-L49

**Comment by drcrazy** [comment]
Can you use air?

**Comment by modmuss50** [comment]
those if checks need to make sure the stack isnt empty. But should still do a null check.

**Comment by ZigTheHedge** [comment]
@drcrazy, nope, we get "Output stack should not be empty" when using minecraft:air.

**Comment by ZigTheHedge** [comment]
@modmuss50 indeed. Should be something like:
```
if(output1 != null)
    if(!output1.isItemEqual(ItemStack.EMPTY))
        addOutput(output1);
```

**Comment by modmuss50** [comment]
`if(output1 != null && !output1.isItemEqual(ItemStack.EMPTY))` is what needs to be done. If I get a chance it will only take 10 mins to fix.

**Comment by modmuss50** [comment]
Could even put those checks in the addOutput method.

**Comment by ZigTheHedge** [comment]
I'm not a java guy, and have no idea - whether it is smart enough not to check second condition, if first one is already false, otherwise it is quite possible to get NPE ;) But you're the boss ;)

**Comment by drcrazy** [comment]
Guys, can you test CT support for Industrial Grinder, please?
Pick jenkins build here: https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.12/208/artifact/build/libs/TechReborn-1.12.1-2.7.0.208-universal.jar

**Comment by ZigTheHedge** [comment]
We've got crush here:
https://gist.github.com/ZigTheHedge/851a742253e809e974cb0a96be87a3dd

**Comment by drcrazy** [comment]
Have you updated reborn core? You can pick latest from curse

**Comment by drcrazy** [comment]
CraftTweaker2-1.12-4.0.4
RebornCore-1.12.1-3.3.0.99-universal
TechReborn-1.12.1-2.7.0.209-universal

CT script:
mods.techreborn.grinder.addRecipe(<minecraft:diamond>, null, null, null, <minecraft:dirt>, null, <liquid:water>, 200, 20);

Results:
![image](https://user-images.githubusercontent.com/1382352/30084581-a328bdb4-929b-11e7-913e-6f0539a7872f.png)
