### ISSUE TITLE
[1.12] [Suggestion] - Grinder - Easier Recipe 

### ISSUE THREAD

**Issue by llloyd4** [TechReborn/TechReborn#1225]
Hello! I was starting out with Tech Reborn as my starting mod just to learn it more when I noticed the starting macerator (Grinder) needs diamonds. I'll probably get shot down for this, but, all I can do is suggest something politely. Ic2 1, which this mod is a spiritual successor to, always used flint, not diamonds, if I recall correctly. Makes it easier early game since diamonds are usually used right off for a diamond pick or diamond drill.  Just a suggestion to make the recipe a little easier.

**Comment by CrossVas** [comment]
Whait a second. TechReborn is a mod based on GregTech 2 and old IC2. It isn't just IC2.
Hence it use GregTech 2 recipe for most TR blocks. 
From the other side You can use CraftTweaker to make recipe more easily)

**Comment by drcrazy** [comment]
Yes, TR based on ideas\recipes from GT. A lot of time passed since GT and I agree that grinder, being teh very basics should be less expensive. For expensive stuff there is an Industrial Grinder. Anyway modmuss50 AFK for a week, so no changes for that week )
