### ISSUE TITLE
Can't charge TR items in IC2 energy storage

### ISSUE THREAD

**Issue by meerple** [TechReborn/TechReborn#1228]
Hi, I am playing All The Mods 3 on MC 1.12. The 'deduplicate' config option is on, which is supposed to integrate TR into IC2. I made a steel chainsaw. I had to use Forestry's worktable, it wouldn't craft in a regular crafting table for some reason. But my real problem is that I can't put the chainsaw into any of IC2s energy storage things, and I can't craft a TR energy thing to charge it. Thanks.

**Comment by Skillotic0703** [comment]
I already opened an issue about this problem. You should close yours. #1202

**Comment by modmuss50** [comment]
This was removed when we removed the core mod. It would require a large amount of duplicated code to bring back.
