### ISSUE TITLE
LESU outputs 1/4 the energy it had stored

### ISSUE THREAD

**Issue by Vectrobe** [TechReborn/TechReborn#1229]
An LESU controller, filled with X amount of FE, will output only 1/4 of that amount to any target block, the remaining 3/4 is lost. This also means that if you loop the block end-to-end it'll quickly discharge itself.

**Comment by drcrazy** [comment]
LESU was having 359996FE. Than it was connected to charge-o-mat with 400k FE internal storage. 359992FE was transfered from LESU to Charge-o-mat. So, not reproducible in TR 2.6.12.186 and RebornCore 3.2.6.92

There could be issue with energy transfer for long cables, not for LESU itself. Going to test long cables separately

![image](https://user-images.githubusercontent.com/1382352/29743001-90f218f0-8a91-11e7-819a-12475d31b0e2.png)
