### ISSUE TITLE
Cloaking Device can't be shift-clicked into chest slot

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#123]
All the other back armour pieces like the lapotronic pack, and the lithium pack can be shift clicked in, this one can't

**Comment by gigabit101** [comment]
it dose not extend item Armour that is why

**Comment by modmuss50** [comment]
I had to add the right click to inv

**Comment by modmuss50** [comment]
To fix this it will break a lot of things, it will move all the meta data for the parts, and will need a new item

**Comment by modmuss50** [comment]
It would break all current worlds. Not going to fix

**Comment by Prospector** [comment]
This should be possible in 1.9, since mojang did it with skulls and pumpkins.
