### ISSUE TITLE
Crashes when Output/Input to side of Sawmill

### ISSUE THREAD

**Issue by thebody1403** [TechReborn/TechReborn#1238]
I'm using TechReborn-1.10.2-2.1.17.233, RebornCore-1.10.2-2.13.6.142 and Forge-12.18.3.2422.
The game has crashed when using Refined Storage Importer and Ender IO Item Conduits to the side of the Sawmill. The Sawmill does have the entire multi-block structure.
Crash Log when using Refined Storage Importer:
[2017-08-15-5.log.gz](https://github.com/TechReborn/TechReborn/files/1225745/2017-08-15-5.log.gz)
Crash Log when using Ender IO Item Conduit:
[2017-08-15-6.log.gz](https://github.com/TechReborn/TechReborn/files/1225746/2017-08-15-6.log.gz)
Edit: MC 1.10.2 obviously

**Comment by thebody1403** [comment]
Just tested with input from top of the Sawmill with the Ender IO Item Conduit. Still crashed.

**Comment by drcrazy** [comment]
Not reproducible in 1.12

I've checked with xnet transferring wood from chest to side of Sawmill. 
![image](https://user-images.githubusercontent.com/1382352/30885232-19f716ae-a31b-11e7-9dbe-79dc8f518836.png)
