### ISSUE TITLE
[MC 1.12] Strange energy glitch i.e. cables producing energy for free

### ISSUE THREAD

**Issue by craft90** [TechReborn/TechReborn#1240]
So I ran into a strange little bug which I highly doubt it intentional. I have a very basic set-up (Generator, Battery Box, cables, Extractor, Grinder, Powered Furnace and some Extra Utils 2 transfer pipes between Grinder & Furnace). However when I connected in a Tesla Machine (Latex processor) I noticed that it was gaining energy. Despise both the Battery box and the Generator being empty and no fuel burning. With the One Probe I could see that power was being transferred through the cables. It didn't seem to occur with newly placed cables but somewhere down the line. Sure all the other machines had full buffers but it didn't seem to draw power from them either. So I tried to start the furnace. It worked and it gained energy. Despise the generator being cold. It gained like 5 T per tick so quite a sustainable amount. And it keeps going.

**Comment by benstreb** [comment]
I found that the diesel generator just kept producing energy, even after it ran out of oil. I suspect this is the same underlying issue,

**Comment by drcrazy** [comment]
@benstreb, do you also has tesla?
