### ISSUE TITLE
[MC 1.12.1] Diesel Generator not properly clearing NBT-data in cells

### ISSUE THREAD

**Issue by craft90** [TechReborn/TechReborn#1244]
Another little annoyance I ran into. If you put a cell into the Diesel Generator with fuel it clears it out seemingly properly. However the Industrial Electrolyser refuses to use those cells. Advanced tool tips showed that there's still a NBT-data tag in the used cells. Upon further research I saw that while the cells seems to have 0 NBT tags after use, once you place it in your inventory it gets a NBT-tag.

**Comment by drcrazy** [comment]
Can you test the following with newly created and used cells:
1) Use cell on water source to get water cell. Is it working for both new and used?
2) Use water cell on ground to get water out of the cell. Can you re-use emptied cell in Electrolyser?

Thank you in advance.

**Comment by craft90** [comment]
1. Yes, both used and new can be used to get water cells by clicking water.
2. I'm unable to empty the cells by clicking on the ground, regardless if they're new or old. However, by using the Extractor I was able to empty an old cell filled with water. That one did work in the Electrolyser.

**Comment by drcrazy** [comment]
Thank you for testing. Both inability to drain cell and excessive NBT data is fixed in TR build >= 184

**Comment by craft90** [comment]
It seems to still be an issue in the new build (2.6.12.181). Cell in diesel generator has the tool-tip NBT-tags: 0 but as soon as you place it in your inventory it gains 1 NBT tag and then it won't work until filled with water and emptied via Extractor.

**Comment by craft90** [comment]
My sincerest apologies! I just checked the new releases. I was sure I had updated it but I was two versions behind. This issue is fixed in 2.7.0.205 Once again, I'm sorry for making such a stupid mistake.

Also, I'd like the new GUI. Much cleaner and user friendly than the old one. :)

**Comment by drcrazy** [comment]
No prob. Github definitely miss 'Fix version' field )
