### ISSUE TITLE
[1.12.1] Machines not exploding when using IC2 EU

### ISSUE THREAD

**Issue by lynxx131** [TechReborn/TechReborn#1252]
I am currently running with IC2 dedupe enabled and I have noticed that the Industrial Blast Furnace and Industrial Electralyzer appear to be the only machines I can make explode by providing too much EU.

I have tried the following machines connected to an IC2 MFSU and none of them explode:

Industrial Centrifuge
Implosion Compressor
Vacuum Freezer
Industrial Grinder

They work as normal and when I measure with an EU reader it seems they just draw their rated EU as indicated by their tooltip.

If I use an Industrial blast furnace with an MFSU it explodes as expected but only when connected via an IC2 cable. If I connect it directly to the face of the MFSU it behaves as above where the blast furnace will just draw its rated 128EU/t from the MFSU.

The Industrial Electralyzer exhibits the same behavior as described above for the Industrial Blast Furnace.

Versions:

MC 1.12.1
Forge: 1.12.1-14.22.0.2462-universal
RebornCore: 1.12.1-3.2.6.92-universal
TechReborn: 1.12.1-2.6.12.185-universal

**Comment by drcrazy** [comment]
Not reproduced. 

Industrial grinder just exploded upon being placed. 
![image](https://user-images.githubusercontent.com/1382352/31257213-0003c306-aa40-11e7-9be0-bb29759e72d7.png)

You need to use IC2 power source and IC2 cables to have machines exploded.
