### ISSUE TITLE
[1.12] QuantumChest really weird display bugs

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1255]
TechReborn-1.12.1-2.6.13.195-universal
RebornCore-1.12.1-3.2.7.97-universal
The number of items in the quantum chest is correctly displayed in TOP. But the number of items displayed in the quantum chest GUI is weirdly displayed:
Between 0 and 191 it displays the correct number.
Between 192 and 320 it displays 64 Stored.
Between 321 and 447 it displays the correct number.
And I don't understand the exact logic of this so you'll have to figure it out.
EDIT: The same bug happens with the digital chest!

**Comment by modmuss50** [comment]
I recommend you use the Quantum storage mod.

**Comment by Skillotic0703** [comment]
It has other features that I don't want

**Comment by Skillotic0703** [comment]
TechReborn has to have a functionnal quantum chest. It's not a problem if you can't fix this today, tomorrow, this week or even this year but I want to see that bug fixed. I want to see a complete version of TechReborn in the future!
