### ISSUE TITLE
[1.12] Iridium reinforced blocks are not hard at all

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1259]
Iridium reinforced stone and Iridium reinforced tungstensteel blocks should be completely unvulnerable to nuke/nuclear reactor explosions, yet they are not even hard enough to resist to a simple TNT explosion!

**Comment by drcrazy** [comment]
Blast resistance fixed. Hardness is same as previous.

**Comment by Skillotic0703** [comment]
thank you!

**Comment by drcrazy** [comment]
Fix available on curse starting from TechReborn-1.12.1-2.7.0.205
