### ISSUE TITLE
[1.12] Lithium batpack sends energy as packets of 100 EU

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1260]
Let's define some variables.
energyBuffer is the quantity of energy an item can hold
energyStore is the quantity of energy stored in the item.
If energyBuffer - energyStore is inferior to 100 EU, the amount of energy spent by the lithium batpack is 100 regardless of the amount of EU that is needed to fully charge the item.
So for example, a steel drill/chainsaw consumes 50 EU per use. If you take a fully charged steel drill and you use it once, the lithium batpack will loose 100 EU to charge it.

**Comment by craft90** [comment]
Huh in my experience the drill takes 200 FE per operation. But that's probably a unit mismatch as I do not use IndustrialCraft2.
