### ISSUE TITLE
[1.12] Diamonds missing from Grinder recipe

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1261]
Well the title says it all. As I know, before the last update the Grinder had diamonds in its recipe. Is this intentional or a bug?
![image](https://user-images.githubusercontent.com/25333164/30002291-0374d60a-90a6-11e7-8bb6-443262360c5a.png)

**Comment by drcrazy** [comment]
Yes, Recipe for grinder made same as for ic2 macerator. They are same machines thus it will not worth to made grinder with diamonds if you can make macerator with gravel )
