### ISSUE TITLE
[1.11.2] Internal Server Error

### ISSUE THREAD

**Issue by carif** [TechReborn/TechReborn#1263]
Whenever someone throws a Dreadium Katana Sword from AbyssalCraft (**edit: also happens with other items etc. from other mods and Vanilla Items (like vanilla seeds to name an example)**) to the ground, he gets kicked from the Server with the following message:
https://pastebin.com/T9X7Yk6J

It should be noted that the log indicates that the problem is caused by the following line
in [TechReborn](https://github.com/TechReborn/TechReborn/blob/ce856ab1dc07f725dce35540fe4c9e04ea246d54/src/main/java/techreborn/events/OreUnifier.java#L61):

Minecraft 1.11.2
Forge Mod Loader version 13.20.1.2454
TechReborn-1.11.2-2.3.3.181
AbyssalCraft Integration-1.11.2-1.5.0
AbyssalCraft-1.11.2-1.9.4-pre-4

**Comment by drcrazy** [comment]
Not reproduced

![image](https://user-images.githubusercontent.com/1382352/30121244-d5c246f8-9333-11e7-8648-b4a79ec94424.png)
