### ISSUE TITLE
[MC 1.12x] Gas turbine suffering from extra NBT data in cells aswell

### ISSUE THREAD

**Issue by craft90** [TechReborn/TechReborn#1267]
So yeah, I reported an issue with the Diesel Generator where used cells retained a NBT data tag which kept them from being used in the Industrial Electrolyser. Apparently the Gas Turbine suffers from the same issue where a used cell has a NBT data which stops it from being used unless filled and emptied. With Actually Additions advanced tool tips I managed to get some extra info. Apparently the NBT data tag is an empty fluid NBT data tag. All it says is 
NBT -
{Fluid:{}}

Funnily enough it even stops the cells from the Diesel and the Gas from stacking (the Diesel one used to contain oil while the Gas ones used to contain hydrogen). The Extractor recognizes the cells as empty and refuses to empty them unless first filled with water from a pond in world.

This issue is still present with 
TechReborn-1.12.1-2.6.12.181-universal.jar and
RebornCore-1.12.1-2.0.1.6-universal.jar
N.B. This isn't a RebornTech only modpack. So I wouldn't know if the issue is caused by mod incompatibility. But I imagined it shouldn't as I have no other mods which should affect the cells. Unless adding new fluids would. Like Forestry does. I also don't have IndustrialCraft2.

**Comment by craft90** [comment]
Thermal Generator has the same issue with fuel via cells. While testing that, I noticed that the Thermal Generator doe not keep view data. So while the One Probe said their internal tanks were full the GUI showed 0 fluid and 0 energy. Until I attempted to put the cell in. Then it freaked out.

**Comment by drcrazy** [comment]
Duplicate for #1244. Reason is same. I will take a look later today.

**Comment by craft90** [comment]
I guess so. I thought that I should open another one for the Gas Turbine. Sorry for making another issue report... I didn't know. I also tried in a world with just Tech Reborn, Actually Additions and The One Probe. The issue remained. So it shouldn't be some other mod making a mess.
Also, I was wrong. The empty bad fluid cells actually do stack. At least in a fresh world.
Oh btw, strangely enough the bad cells fit in the item input slot (where you put dusts and stuff)

**Comment by drcrazy** [comment]
yeah, NBT-containing empty cells stack with NBT-containing empty cell and do no stack with empty cells w\out NBT. All 4 fluid generators and, probably, industrial grinder affected. Easiest way to fix cells is to click on water to get water cell and then empty it by clicking anywhere in the world

**Comment by craft90** [comment]
It seems to be fixed in the latest version, at least for the generators (I've not tested the Industrial Grinder or the Semi-fluid generator tho)
