### ISSUE TITLE
[1.12.1] RF/FE is not flowing in to machines properly

### ISSUE THREAD

**Issue by tgstyle** [TechReborn/TechReborn#1273]
TR - 2.7.1.224
RC - 3.4.0.104

You can see a fluxduct below the machine here. Power flow is restricted even though it can receive up to 25000 RF. Transformer upgrade makes no difference. Removing the overclockers makes no difference.

![2017-09-11_19 58 31](https://user-images.githubusercontent.com/5832709/30305005-c45e085e-972d-11e7-996d-b24fd1442fd6.png)
![2017-09-11_19 58 55](https://user-images.githubusercontent.com/5832709/30305006-c63ae7f0-972d-11e7-811e-beeea925b878.png)

**Comment by Catonyx** [comment]
I think it's being throttled by the leadstone energy conduits, rather than the machine

**Comment by tgstyle** [comment]
That is not a Leadstone, that is a Resonant.
