### ISSUE TITLE
[1.12.1] Hologram view does not work

### ISSUE THREAD

**Issue by Dourmouki** [TechReborn/TechReborn#1276]
In a few machines i tryed..its the first time i use this mod so i would appriciate to be fixed
i am using this TechReborn-1.12.1-2.7.2.233-universal for MC 1.12.1

**Comment by drcrazy** [comment]
Not reproducible. Some multiblock machines expected to be on top of multiblock. Thus if you place them on ground multiblock hologram will be below them. You can check how to build multiblock on wiki: https://wiki.techreborn.ovh/doku.php?id=blocks

![image](https://user-images.githubusercontent.com/1382352/30594497-ef88ffc8-9d56-11e7-9475-d340e44c6801.png)
