### ISSUE TITLE
[1.12.1] Crash,  Failed to get ore name:ingotDiamond

### ISSUE THREAD

**Issue by erwin1234777** [TechReborn/TechReborn#1277]
Welp, havent had that issue before, however i think ModernMetals is the culprid. saw the same with titanium on another issue, figured i should post too to let you know that diamond is also causing a crash, not only titanium. https://pastebin.com/8jMz64Pk

**Comment by drcrazy** [comment]
Hi @erwin1234777,

What mod adds DIamond ingot? Do you also have infinitic? 

BR,
drcrazy

**Comment by erwin1234777** [comment]
Infinitic? I dont that mod. If you're talking about PlusTic i do have it. And i have no clue on what adds diamond ingot.
