### ISSUE TITLE
Machine Casing and Machine Block share recipes. 

### ISSUE THREAD

**Issue by llloyd4** [TechReborn/TechReborn#1278]
Ok, so, on 1.10.2, the IC2 Machine Casing uses 8 iron plates, and all iron plates are ore dictionaried together, says in the tool tip "accepts any plateIron", when I go to craft it I get a Machine Block from Tech Reborn instead and the recipe (Compressor from IC2) won't accept the Machine Block in place of a Machine Casing. 

Then again this is a bit weird, I am trying to make a Rolling Machine from Tech Reborn and the recipe requires two IC2 Compressors, only IC2 Compressors and nothing else. Which I can't craft as I can't make a Machine Casing. >.<

I poked at the settings, and 

    # This attempts to fully integrate TR with ic2 recipes (Beta)
    B:"Remove Duplicates when IC2 is installed"=true

So... >.< :(

**Comment by drcrazy** [comment]
Due to very-very limited support for 1.10.2 I suspect there will be no code changes. If you will turn off IC2 deduplicates you will be able to craft IC2 casing
