### ISSUE TITLE
Diesel generator generating small amount of energy

### ISSUE THREAD

**Issue by Zafaranec** [TechReborn/TechReborn#1279]
Hi, I don't know is only bug or feature, but Diesel generator have wrong amount of energy for fuels.
Oil in semifluid generator generate(or in JEI I see) 64K EU but in Diesel generator have only 16K EU.
Nitrodiesel in old table on ftb wiki have 400K EU but in game have only 36K EU.
for unknown reason is for oil better generator semifluid than diesel but should be same.

sorry for my bad English but not is my native language.

**Comment by Skillotic0703** [comment]
Let me check the amounts generated in Gregtech 2 and I will tell you soon what's the problem here !

**Comment by Zafaranec** [comment]
awesome, thanks for your hard work on this awesome project.

**Comment by drcrazy** [comment]
Rádo se stalo!

**Comment by Zafaranec** [comment]
huh, czech language?

**Comment by Zafaranec** [comment]
jak jsi to věděl?

**Comment by drcrazy** [comment]
By your nickname. It's a Czech surname as far as I understood

**Comment by Zafaranec** [comment]
oh Ok :D
