### ISSUE TITLE
No Kanthal or Nichrome heating coils

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#128]
These don't appear to exist as items or textures though the alloys/ingots do. Not sure if you plan to add them but they were in Gregtech as part of the higher heats tiering.

**Comment by modmuss50** [comment]
Anyone got any textures?

**Comment by Carbon-Ghost** [comment]
I should have them ( original ones ) , should I add them in the todo list ?

**Comment by modmuss50** [comment]
Na, just post here. I can fix this quickly

**Comment by Carbon-Ghost** [comment]
crap still searching for them, I found the faithful one xD Though wait for a bit brb

**Comment by Carbon-Ghost** [comment]
holy shit  I think I am going to kill Grag on how he named his textures ( numbers.... ) GRAAAAAAAG !

**Comment by Carbon-Ghost** [comment]
![19 1](https://cloud.githubusercontent.com/assets/10200094/9744941/1fd3cd56-566f-11e5-895f-ef4c49538dee.png)
![20 1](https://cloud.githubusercontent.com/assets/10200094/9744945/2913a288-566f-11e5-9d6d-1813960b5cb9.png)
![21 1](https://cloud.githubusercontent.com/assets/10200094/9744949/2fb4e354-566f-11e5-903f-41e8186a268c.png)

**Comment by Carbon-Ghost** [comment]
all coils I found

**Comment by modmuss50** [comment]
Ok thanks, I will get them from the mod if they are not correct.

**Comment by Carbon-Ghost** [comment]
those are from GT assets btw, just forgot which one is which color to metal wise ^^''

**Comment by modmuss50** [comment]
I will have a look when I can get into an old GT world.

**Comment by Carbon-Ghost** [comment]
kk ^^

**Comment by modmuss50** [comment]
Yellow one Kanthal
Red one Nichrome
Orange one Cupronickel

**Comment by Carbon-Ghost** [comment]
:D Well gonna go sleep gn8

**Comment by modmuss50** [comment]
Night o/

https://puu.sh/k4vaW/15f9eeb632.png
https://puu.sh/k4vbM/37b0eefdb0.png
https://puu.sh/k4vdA/06faec1e14.png

**Comment by modmuss50** [comment]
Turns out they are in the mod ;( should of checked before asking you sorry
