### ISSUE TITLE
broken techreborn oil texture

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#1280]
I suspect an incompability with Optifine. I use Minecraft 1.12.2 and TechReborn 2.7.4.243.
![2017-09-29_00 03 46](https://user-images.githubusercontent.com/17103411/30992417-14c72652-a4aa-11e7-95e7-7207ba91e3b8.png)

**Comment by modmuss50** [comment]
Can you ensure all your mods are fully update including forge? This was an issue a while back, that was fixed when some other mod updated.

**Comment by drcrazy** [comment]
Duplicate for #1221
