### ISSUE TITLE
Industrial blast furnace 1.12

### ISSUE THREAD

**Issue by Zafaranec** [TechReborn/TechReborn#1281]
Hi, I have problem with industrial blast furnace, on wiki I read, must have constant energy 128EU/t and for this is recommended have dedicated MFE, I have this setup connected with gold cable but not working, energy is drained from internal storage and slowly recharging for use. I don't know, where is problem.

**Comment by drcrazy** [comment]
You can use workaround until fix will be on curse - place two cables between MFE and Industrial Blast Furnace.

**Comment by Zafaranec** [comment]
oh Ok, how, when MFE have only one output? I add second MFE, that looks like it's working, but fix would be nice :) , and what is problem, packet transfering or machine work on different energy level?

**Comment by drcrazy** [comment]
MFE->Cable->Cable->Blast Furnace
Issue is that single cable tries to put energy both back to MFE and to Blast furnace in equal shares. Put to MFE fails, thus no energy loss. But blast furnace is getting only half energy per tick, e.g. 64eu\t. If you have two cables than cable connected to Blast Furnace will try to give energy only to Blast furnace and not to other cable. Thus blast furnace will get full amount, e.g. 128 EU\t.

**Comment by Zafaranec** [comment]
oh nice, this working, thanks, but have one additional question, all changes apply with tiny delay, this look like cables have some internal buffer, that is correct?

**Comment by drcrazy** [comment]
yes, cable do have internal buffer

**Comment by Zafaranec** [comment]
thank for all.
