### ISSUE TITLE
Industrial Blast Furnace can't maintain charge

### ISSUE THREAD

**Issue by iWasntHere** [TechReborn/TechReborn#1283]
The Industrial Blast Furnace can't seem to keep a charge when powered.
The tooltip states that it takes in 512 FE per tick, but the actual power use seems to be way higher than that, making the machine quickly drop to 0% charge, and only continuing when the charge reaches around 1k.
Maybe I'm doing something wrong, but this doesn't seem to be intended behavior. All of the other machine's I've used don't have this problem.

**Comment by drcrazy** [comment]
Duplicate for #1281
