### ISSUE TITLE
Wrench

### ISSUE THREAD

**Issue by VPDeadlyHunter** [TechReborn/TechReborn#1288]
Hello, I have a problem with the wrench. Maybe I do not know how to shoot cars with wrench, or it's a bug of your mod. Correct the bug or help remove the machine. Thank you.

**Comment by modmuss50** [comment]
What are you trying to do with the wrench?

**Comment by drcrazy** [comment]
As a workaround you can set in config that wrench is not required and use pickaxe to remove machine.

**Comment by VPDeadlyHunter** [comment]
I'm trying to remove a machine with wrench (Generator).

**Comment by VPDeadlyHunter** [comment]
Tell me in which config you need to change the value to get the machine with a pick.

**Comment by drcrazy** [comment]
config\reborncore.cfg

Change  "Wrench required" to false

**Comment by drcrazy** [comment]
Issue is with updated forge. Wrench works on 2493. And does not work on 2500+

**Comment by modmuss50** [comment]
My guess is, https://github.com/MinecraftForge/MinecraftForge/commit/025495f98b3b0c3738c7698b2ff848a22f2e5dd0 broke it. I will take a look at some point.

**Comment by drcrazy** [comment]
Yeah. I can confirm that forge 2497 is fine and 2498 is not fine
