### ISSUE TITLE
Crash using Modern Skyblock 2 

### ISSUE THREAD

**Issue by fane0info** [TechReborn/TechReborn#1289]
Hello there. 

I just crashed three times using the Modern Skyblock 2 modpack version 2.5.3
I created some recipes in AL2 (AE2 branch). When trying to create a Fusion coil I got the crash.

[crash-2017-10-06_19.36.31-server.txt](https://github.com/TechReborn/TechReborn/files/1363355/crash-2017-10-06_19.36.31-server.txt)

[2017-10-06-5.log.gz](https://github.com/TechReborn/TechReborn/files/1363363/2017-10-06-5.log.gz)

If any other informations are required I will be happy to provide them.

**Comment by jusvit** [comment]
```java
Time: 10/6/17 7:36 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at techreborn.items.ItemCells.isCellEqual(ItemCells.java:55)
	at techreborn.init.recipes.IngredientCell.apply(IngredientCell.java:42)
	at net.minecraftforge.oredict.ShapedOreRecipe.checkMatch(ShapedOreRecipe.java:136)
	at net.minecraftforge.oredict.ShapedOreRecipe.func_77569_a(ShapedOreRecipe.java:96)
	at appeng.helpers.PatternHelper.isValidItemForSlot(PatternHelper.java:243)
```

**Comment by drcrazy** [comment]
I've just crafted fusion coil using AL2 without issues. Maybe it crashed during crafting of some other items, rather than Fusion Coil itself?

![image](https://user-images.githubusercontent.com/1382352/31311196-d4e17490-abaf-11e7-9f6f-4e3a4776ab57.png)

**Comment by fane0info** [comment]
Crafting the recipe by hand was fine. Of course that I made a lot of components by auto-crafting. Cannot pinpoint which one of them was causing the crash. I reverted back to a backup and crafted the coils by hand. 

I thought that it might help to post such a crash here.

**Comment by drcrazy** [comment]
Berillum cell for neutron deflector could be an issue according to crash log. But I was able to craft it automatically without crashing. 

Can you start auto-craft of coil and check crafting monitor?
