### ISSUE TITLE
Centrifuge quite broken

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#129]
GUI not updating. 
![capture](https://cloud.githubusercontent.com/assets/7843312/9364419/96a7b6b6-46ef-11e5-90dd-c40040a700f9.PNG)

Relogged to see if it updated, became all mangled. 
![dd](https://cloud.githubusercontent.com/assets/7843312/9364418/9325faca-46ef-11e5-8532-aca030751eca.PNG)

Also, at very least I am pretty positive this recipe doesn't work.
I've let it run with one peice of rubber wood and 5 cells for a long time to no avail, but if I leave a stack of rubber wood in there, walk away for a while and check back, it tends to have done something. 
![capture](https://cloud.githubusercontent.com/assets/7843312/9364527/1b907ec6-46f0-11e5-83c6-bcffb0369555.PNG)

**Comment by modmuss50** [comment]
Are we going to move to the new gui that @Carbon-Ghost made?

**Comment by TheQuantumGeneral** [comment]
My votes still on the legacy design, new one looks too similar to the electrolyzer imo.

**Comment by Carbon-Ghost** [comment]
So which one was used in the end ?

**Comment by joflashstudios** [comment]
For the record, I agree with @TheQuantumGeneral. Go with the old design. It's nice because it visually represents an operating centrifuge.

**Comment by Carbon-Ghost** [comment]
We wanted to use new one for new users sake, I also prefer new one, but for a new user of GT reborn ( like me before ) the GUI can be confusing piping wise, and is just way to complex, even Greg agreed on that and changed it in the new GT :P

**Comment by modmuss50** [comment]
we could have a config? not sure what the default would be.

**Comment by Carbon-Ghost** [comment]
Default should be the new one, for new users sake, config will be here for nostalgic users, but you said that GT reborn wouldn't be a perfect GT4 "port/remake" for hardcore fans :P
