### ISSUE TITLE
[1.12] Thermal Generator accepting Lava too slowly

### ISSUE THREAD

**Issue by Timeslice42** [TechReborn/TechReborn#1291]
Eyeballing it the thermal generator is using about 4mb per second. It is only accepting about 2-3mb per second from attached pipes.

This is a little rediculous.

**Comment by jusvit** [comment]
![capture](https://user-images.githubusercontent.com/4002351/31315867-e63a42b8-ac6c-11e7-9ae4-b6c87486785a.PNG)
I don't think it accepts lava too slow. The underlying problem is that the tank GUI capacity isn't updating to show the amount of lava inside it. (Unless you reload world)
