### ISSUE TITLE
[1.12.1] Cables stop transmitting power after each new session

### ISSUE THREAD

**Issue by Timeslice42** [TechReborn/TechReborn#1296]
Tech Reborn: 1.12.2.2.7.7.283
Reborn Core: 1.12.2-3.4.6.131
Forestry: 1.12.2-5.5.6.198
Actually Additions: 1.12.1-r121

Any time I load this world I have to remove **all** of the cables in this setup and replace them before the machines will recieve any power.

G = Generator (generator)
S = Storage (batbox)
T = Transformer (lv->mv)
E = EU consumer
R = RF consumer

The machine you can't see under the chest is an AA double furnace. I had this same issue when it was a TR electric furnace. The forestry machines (from left to right) are a carpenter and a squeezer. My anecdotal evidence suggests that it is the combination of EU and RF machines on the same line with the transformer at the end that is causing this issue.

![2017-10-09_20 51 20](https://user-images.githubusercontent.com/2825989/31364705-96fd5780-ad34-11e7-8ecd-3612b6360f80.png)

Log file, just in case: 
[latest - Copy.zip](https://github.com/TechReborn/TechReborn/files/1370225/latest.-.Copy.zip)

**Comment by drcrazy** [comment]
Hmm. I'm not able to reproduce this in SSP. Are you playing any modpack?

I've set similar thing using TR generator, TR grinder, TR transformer and Thermal foundation redstone furnaces as RF consumers. After logging out and in everything still fine.

Difference between your setup and mine is that I've used updated version of TR (TechReborn-1.12.2-2.7.8.297). May I ask you to update both TR and RC and re-check, please?

![image](https://user-images.githubusercontent.com/1382352/31463022-4d6c4000-aed7-11e7-8579-0142f7becd83.png)

**Comment by drcrazy** [comment]
I was able to reproduce that issue. And hopefully fix it )
Issue was not in combination of EU and RF machines but rather in specific update sequence of tile entities. And different behavior for energy providers like generator or bat box and cables

**Comment by drcrazy** [comment]
On the second thought I haven't fixed it (

**Comment by Timeslice42** [comment]
I'm using the latest release versions. Do you want me to go to curseforge and download the latest beta/alpha versions? Or do you have everything you need from me?

**Comment by drcrazy** [comment]
Yes, I have everything I need.
