### ISSUE TITLE
[1.12.1] Vacuum Freezer miss multiblock button in GUI

### ISSUE THREAD

**Issue by accessdenied0** [TechReborn/TechReborn#1297]
MC-Version: 1.12.1
MinecraftForge-Version: 14.22.1.2478
TechReborn-Version: 1.12.2-2.7.7.283
Reborn-Core-Version: 1.12.2-3.4.6.131

Hello Reborn-Team,

I played a modified version of Modern Skyblock 2 and tried to cool off some Tungsteel. I looked up if there would be made some changes, but there were none. So I tried to use a Water-cell or Ice in it, didn't work. Replacing - didn't work.

The Chat, as well the console said nothing, so there is sadly no log here. If it is still required, I can upload the Forge log later.

access_denied

**Comment by drcrazy** [comment]
Do you have correct multiblock for VacuumFreezer?

**Comment by accessdenied0** [comment]
If it is a multi-block structure, changes this issue from: "Vacuum Freezer refuses to work" to "Vacuum Freezer Multi-block structure detection broken."

[On your Wiki](https://wiki.techreborn.ovh/doku.php?id=blocks:vacuum_freezer), which is sadly very incomplete, is no clue on the page itself there is a multi-block structure involved or how these need to be assembled. So I missed that, sorry...

Besides that: I might be a bit spoiled from your Blast-Furnace, which indicates if there is a structure missing or not. (The guide I'm very thankful about included)

I tested it with a [Gregtech specified structure](http://puu.sh/xVspA/93f8f642c3.jpg) and [inverted it, too](http://puu.sh/xVsk8/67a79773bb.jpg) just in case i might understood something wrong [here.](http://feed-the-beast.wikia.com/wiki/Vacuum_Freezer) I'm clumsy sometimes.

Both cases didn't work. Energy was left in the Freezer.

**Comment by drcrazy** [comment]
As for now Vacuum freezer expects to have 3x3 platform of reinforced casings below it

**Comment by drcrazy** [comment]
Fixed in TR build >=295
