### ISSUE TITLE
Overclocker and energy upgrades not working

### ISSUE THREAD

**Issue by Dannez** [TechReborn/TechReborn#1298]
Minecraft 1.11.2
Forge latest build
TechReborn latest 1.11.2 release

The overclocker and energy upgrades do not work in the machines, namely the grinder, generator and alloy furnace - which has double the number of upgrade slots - and the electric furnace does not have any upgrade slots. Is this an intentional feature?
Overclockers do not seem to speed up machines, whereas energy upgrades show the internal capacity is boosted, but the machines won't accept power.
Tested using TR cables and machinery, then Thermal cables/RF production, still change to machines with upgrades.

Please fix :)

**Comment by modmuss50** [comment]
overclockers seem to work fine for me? 

I can confirm the power issues.

**Comment by modmuss50** [comment]
Should be fixed, I would recommend updating to 1.12 to get the fixes.
