### ISSUE TITLE
Debugging - Model Errors and Block Interctions - MC1.12.2 Forge 512

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TechReborn/TechReborn#1299]
Debugging
https://gist.github.com/P3rf3ctXZer0/e2746bb3adcc937870c5b08e441a5ebd

Debug Crash Log
https://gist.github.com/P3rf3ctXZer0/a8cfefd4d67fd0e7327ccdf223f3cfca

**Comment by modmuss50** [comment]
That crash log is something you have trigged and is completely pointless.

The other outputs are just warnings, and dont actually effect gameplay. But your not the first to ask about them, so I will leave this open in the hope that I can either "fix" them or suppress them

**Comment by modmuss50** [comment]
Actually, im closing this, its not an issue.
