### ISSUE TITLE
All Helium and NaK coolant cells missing or using temporary recipes

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#130]
For example

![capture](https://cloud.githubusercontent.com/assets/7843312/9364566/6ce09982-46f0-11e5-8dc7-0bf01c0fe8dc.PNG)

**Comment by gigabit101** [comment]
we have not added all the cells

**Comment by modmuss50** [comment]
Shall we?

**Comment by modmuss50** [comment]
All of the cells are in, just a load of recipes need adding.

**Comment by modmuss50** [comment]
Sorry that It took a while, I didnt have access to a 1.4.7 instance. But now it do! I had to add the recipe that requires the fusion reactor as a shapeless.
