### ISSUE TITLE
1.12.2-2.7.8.297 Crafttweaker change broke null in scripts

### ISSUE THREAD

**Issue by tgstyle** [TechReborn/TechReborn#1303]
Script entry is this

mods.techreborn.centrifuge.addRecipe(<enderore:dust_ender>, <minecraft:blaze_powder>, null, null, <techreborn:dust:19> * 2, null, 1840, 5);

Generates this error

https://gist.github.com/tgstyle/63502ce96339fe93b762baec453021ec

I believe it was due to this change

https://github.com/TechReborn/TechReborn/commit/23ccd878bd35dc848e4c7b19c2cc8135318e9dcb#diff-5c3208eba10e5e4bbc08fac88f1c0236

-			return null;
+			return ItemStack.EMPTY;

**Comment by modmuss50** [comment]
Yeah, it would have been. Sorry about that, I should really get a full script that tests all the machines.
