### ISSUE TITLE
[1.12.X] Flux-Infused OmniWrench support

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1307]
You are currently supporting the crescent hammer from TE. And all the blocks that can be dismantled by the crescent hammer should be able to be dismantled by the flux-infused omniwrench from Redstone Arsenal. I don't know if it's a bug but if it's not, could you add support for the omniwrench please?

**Comment by modmuss50** [comment]
Yeah, should be easy to add.

Also, if you know of any mods that also add wrenches let me know.

Current supported list: https://github.com/TechReborn/RebornCore/blob/1.12/src/main/java/reborncore/RebornCore.java#L109

**Comment by Skillotic0703** [comment]
The crescent hammer and the flux-infused wrench are the most important because they are supported by a large variety of mods.
