### ISSUE TITLE
Crash when inserting item into quantum chest

### ISSUE THREAD

**Issue by DrZoddiak** [TechReborn/TechReborn#1308]
**Minecraft version:** 1.10.2
**Mod version:** 2.1.18.235
**Forge version:** 12.18.3.2511

Crash happens when 2 stacks of any block are put into quantum chest. 
Specifically it creates a ticking entity that then crashes the server.
Below is the crash report.

https://gist.github.com/DrZoddiak/35907d03e23911b1a4b176bf3bce0936

**Comment by drcrazy** [comment]
Due to limited support for 1.10.2 please, use https://minecraft.curseforge.com/projects/quantumstorage mod. TR will detect that QS is there and will not register TR own quantum chest.
