### ISSUE TITLE
Iron Furnaces Drop Basic Frames

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1309]
Iron Furnaces drop Basic Machine Frames when broken, but yet they aren't in their recipe. This is mainly an issue for me as I have Basic Machine Frames gated mid-game, but Iron Alloy Furnaces are used at the beginning of my pack.

**Comment by drcrazy** [comment]
You can change to not require wrench to drop block. In this way Iron furnace will be dropped instead of frame

**Comment by TheLimePixel** [comment]
Actually, nvm. It's Electric Furnaces, not Iron Furnaces. It's a simple recipe change.
