### ISSUE TITLE
[1.12.X issue] Rubber Wood logs can't be placed horizontally

### ISSUE THREAD

**Issue by dancc7t** [TechReborn/TechReborn#1310]
Hello i am playing TechReborn on 1.12.2, i have all updated to the last version.

I am creating a gallery for all blocks for decorative purposes and i noticed i cant place rubber wood logs horizontally like the rest of the wooden blocks, i tried placing it alone, shift+rightclicking and i also tried with the wrench of the mod, none of this worked.

This is a feature all wood blocks in minecraft have, it would be very nice if you can add this in the next update.

Thanks.

**Comment by modmuss50** [comment]
This isn’t possible/not easy to add as the meta data is being used for the sap spots. In the future this may become possible. Sorry about that.
