### ISSUE TITLE
Chainsaw is not usable until full charge

### ISSUE THREAD

**Issue by Toby343** [TechReborn/TechReborn#1312]
I'm using the steel chainsaw and I have a source of energy in my inventory to charge it as I go (thermal expansion hardened capacitor in this case but I think it happens with all). What is happening is when the chansaw is charging which is after a block break, it glitches being unable to break a block until it's at full charge again. I have to turn the capacitor off to stop charging to use the chainsaw. The same happens for the steel drill. Also I've noticed when the chainsaw is completely out of power it still breaks logs fine as if it was charged.

**Comment by drcrazy** [comment]
What Minecraft version do you use?
What Tech Reborn version do you use?

**Comment by Toby343** [comment]
Minecraft 1.12.2
Tech Reborn 1.12.2-2.7.9.301
Modpack All The Mods 3 version 4.2
