### ISSUE TITLE
Cloaking Device

### ISSUE THREAD

**Issue by misteryman526** [TechReborn/TechReborn#1314]
I'm using the current release version of TechReborn in the 1.10 FTB Beyond modpack (I added the newest update myself). I've made a Cloaking Device but it doesn't seem to actually DO anything. I'm able to charge it, but can't interact with it in any other way. According to old Wiki descriptions it's supposed to be wearable in the Chestplate slot and grant you total invisibility but I can't put it in any of my armor slots. Holding it in my main or off-hand doesn't do anything nor does right or left or shift-right, shift-left clicking with it in hand.

**Comment by drcrazy** [comment]
Fixed in 1.12.  Not sure if it will be back-ported to 1.10.
