### ISSUE TITLE
Output Power from Fusion Reactor

### ISSUE THREAD

**Issue by BeLink13** [TechReborn/TechReborn#1316]
Can you fix the fusion reactor so that you can output energy from it like in Gregtec?

**Comment by drcrazy** [comment]
what MC version? In 1.12 you can output from top and bottom sides

**Comment by BeLink13** [comment]
Thank you for the fast answer. I play it in the Minecraft Version 1.10.2 in the FTB Beyond Modpack. Before i wrote this, I proofed the version of TR in the pack (1.10.2-2.1.17.233) and the changelogs to the newest version (1.10.2-2.1.18.235) but I found nothing about the fusion reactor.

**Comment by drcrazy** [comment]
huh. TR for 1.10 is not in the best shape.

**Comment by modmuss50** [comment]
Sorry, 1.10 isnt supported. Please update to 1.12
