### ISSUE TITLE
Assembler more slots requests for complex minetweaker recipes

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#132]
Everything in the title, I want to request 3 input & 3 ouputs slots, would allow me to have 2 inputs + 1 "catalyst" = 1 or 2 outputs + 1 "catalyst" for exemple, the possibilities will be enormous :D

**Comment by modmuss50** [comment]
I dont see the need for this just for a modpack.

**Comment by Carbon-Ghost** [comment]
Well more for minetweakering, not simply modpack, might have been interesting, GT5 have a more complex assembler that's why I also wanted one in GT reborn ^^

**Comment by modmuss50** [comment]
We might add an advanced one? @Mattabase @gigabit101 would you be happy with this?

**Comment by Carbon-Ghost** [comment]
That would be nice for minetweakering for complex recipes where you would need some GT progression ^^
