### ISSUE TITLE
Import/Export From Rolling Machine?

### ISSUE THREAD

**Issue by MaxAstro** [TechReborn/TechReborn#1320]
There doesn't seem to be any way to automate the rolling machine - neither the import upgrade nor the export upgrade seem to want to work with it, and no pipes that I've tried function either.

**Comment by drcrazy** [comment]
Starting from 1.11.2 Rolling machine can output from the bottom. As for input it is not clear to what crafting grid slot machine should import ingredients. For example, iron bars recipe contains 6 iron ingots. Rails recipe contains 6 iron ingots and a stick. If you will drop ingots first and then stick to input "slot" machine will start crafting iron bars as soon as it will have 6 iron ingots and will not wait for stick to make rails.

**Comment by MaxAstro** [comment]
Good to know for output.

For input, perhaps you could simply have a toggle that causes the machine to not craft it's last stack of resources?  Then any new resources would get added to the existing recipe and the recipe would never clear.

**Comment by Aphenon** [comment]
The old rolling machine from Railcraft did have this automate-able behaviour, where it left the last set of crafting ingredients in the machine as a pattern,
