### ISSUE TITLE
[1.12] Rolling Machine enhancement

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1321]
You should change the behavior of the rolling machine. You should have a ghost item system with an inventory. You set the recipe in the rolling machine and once the items are in the inventory it starts crafting. That helps for the automation.

**Comment by modmuss50** [comment]
How about a bit like how the auto crafting table works?

**Comment by Skillotic0703** [comment]
Yes

**Comment by Skillotic0703** [comment]
It would be an autocrafting table but with an alternate list of crafts.

**Comment by modmuss50** [comment]
Doing this will require a large amount of work, as I would need to put a lot of effort into a GUI to select the recipes. I really think there are better things I can spend my time on. Maybe in the future but not now. Sorry about that.

**Comment by drcrazy** [comment]
Also having recipe selection might now work with craftweaker\minetweaker

**Comment by cryptiklemur** [comment]
Basic integration with AE2/Refined Storage would be incredible.
