### ISSUE TITLE
[Suggestion] Stainless Steel

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1323]
I know that your goal is to take the best features of each version of Gregtech 2-4. I would suggest you to add stainless steel (from GT4) because it would give a use to manganese:
![image](https://user-images.githubusercontent.com/12701912/31962792-d438c87a-b8fe-11e7-84ca-43ba8afb1d51.png)
The gray item is iron dust, the blue one is nickel dust, the white one is manganese dust, the pink one is chrome dust.
Stainless steel is used for a lot of crafts (mining drill, chainsaw, electric treetap, mixed metal ingots, diamond/wolframium grinder, reinforced machine casing, industrial centrifuge, industrial electrolyzer and a lot of other crafts).
Even if you don't add crafts, could you at least add the stainless steel dust, ingot and plate for pack makers please?

**Comment by drcrazy** [comment]
THere is no textures for stainless steel in TR.

**Comment by Skillotic0703** [comment]
Maybe Yulife can make one no?

**Comment by modmuss50** [comment]
No need.
