### ISSUE TITLE
Refined Iron Steel recipe conflict

### ISSUE THREAD

**Issue by leytilera** [TechReborn/TechReborn#1324]
TechReborn ha a recipe conflict with my mod, the material api. when i smelt iron in a furnace my mod Outputs an Ingot with the oredict entry ingotSteel but your refined iron has not this entry. please add the oredict entry ingotSteel to Refined iron.

**Comment by Prospector** [comment]
Refined iron is not steel, it's its own material

**Comment by leytilera** [comment]
oh, ok. in the old ic2 it was steel because of that i thought that it is also steel here.
