### ISSUE TITLE
Disconnect while using Industrial Grinder

### ISSUE THREAD

**Issue by Bigcheese** [TechReborn/TechReborn#1325]
Just got a disconnect while grinding Iridium Ore in an Industrial Grinder. I had the GUI open and as soon as the operation finished I was disconnected from the server. There was no error on the server side and when I reconnected the products were there.

MC: 1.12.2
Forge: 14.23.0.2512
TechReborn: 2.7.9.301
Log: [tr-error.log](https://github.com/TechReborn/TechReborn/files/1416597/tr-error.log)

**Comment by lugiaf** [comment]
My server kick me after Industrial Grinder work finished... XD

MC: 1.12.2
forge: 14.23.0.2512
TechReborn: 2.7.10.327
RebornCore: 3.4.9.143
modlist: https://pastebin.com/yMgEJrdu

**Comment by modmuss50** [comment]
Yeah, ok. I really do need to fix this bug. ASAP.

**Comment by modmuss50** [comment]
Fixed in https://github.com/TechReborn/RebornCore/commit/546ace48131a3ffdb52dee19fb6d8b9e84e76cee Updated reborn core once its on curse.

**Comment by modmuss50** [comment]
Let me know of any new issues
