### ISSUE TITLE
[1.12.2] Transformer upgrade spelling issue

### ISSUE THREAD

**Issue by FnordMan** [TechReborn/TechReborn#1327]
Namely, they're called "Tranformer upgrade"
![2017-10-29_17 14 08](https://user-images.githubusercontent.com/7041560/32149031-df4d6de8-bccc-11e7-8f0b-f8adcc8fba14.jpg)

**Comment by modmuss50** [comment]
This was fixed a while back, https://github.com/TechReborn/TechReborn/commit/3f1e7b9111350815342662c44dd73e5b9819b286 I need to get an update out.
