### ISSUE TITLE
Iridium Vein Size Issues

### ISSUE THREAD

**Issue by TonyPrindel** [TechReborn/TechReborn#1330]
I've been messing around with ore gen options for Tech Reborn, and have run into issues where vein size for Iridium seems to be hard stuck on 1 despite my attempts to change it.

My steps for changing are as follows:
1. Set "veinSize": x≠1, (where x is my desired vein size)
2. Set config file to read only to prevent mod override
3. Start Minecraft
4. Generate new world
5. Use World Stripper to reveal ore gen

No matter the value for x, iridium seems to only generate in vein sizes of 1. 

I am wondering if this is a problem with iridium spawning specifically, or with all ores having some sort of hard set max for vein size. Either way, I'd like to ask that this be addressed.

Thank you!

version info:
MC: 1.12.2
Forge: 14.23.0.2528
Reborn Core: 3.4.2.113
Tech Reborn: 2.7.10.327

test instance used no other mods

**Comment by modmuss50** [comment]
Yeah, this is a limitation of the way I fixed the world gen. 

see here: https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/world/TechRebornWorldGen.java#L221

I can fix this. Also you say the mod is overriding the config file?

**Comment by TonyPrindel** [comment]
Oh, no, I just prefer to lock my configs as a just-in-case mechanism. I don't believe I ran into any write issues.

Glad to hear this will be addressed. I'll add that it'd be cool if all ores were unlocked (if hard limits exist with all of them), provided it wouldn't be too much of a bother to do so.

Thank you so much for the response! If you need any further information from me, please don't hesitate to ask.

**Comment by drcrazy** [comment]
![image](https://user-images.githubusercontent.com/1382352/32733450-57aed356-c8a0-11e7-9651-2f3e4de0077c.png)
