### ISSUE TITLE
Removing Iron Furnace crafting recipe blocks Crafttweaker

### ISSUE THREAD

**Issue by Niuttuc** [TechReborn/TechReborn#1335]
I tried to remove specifically the iron furnace eight iron ingot shaped recipe using Crafttweaker, but removing specifically this recipe (I didn't try everything but removing other techreborn recipes at random works fine) stops Crafttweaker to modify recipes afterwards.

The problematic line:
[SCRIPT](https://pastebin.com/aq0fKXP4)
[Resulting erroring log](https://pastebin.com/9z55M4PF)

**Comment by modmuss50** [comment]
Uhh, I have a bad feeling about why this is the case. I will take a look.

**Comment by drcrazy** [comment]
Issue is with CraftTweaker itself. 
It  is not able to remove Vanilla Iron Leggings for example. Every recipe with empty slot in inputs will produce error due to missing null check. Maybe this is already fixed in https://minecraft.curseforge.com/projects/crafttweaker/files/2487573
