### ISSUE TITLE
[1.12.2 Latest Version]Tech Reborn Oil causing a Stacktrace Error

### ISSUE THREAD

**Issue by Preminenc3** [TechReborn/TechReborn#1336]
[crash-2017-11-04_13.08.58-client.txt](https://github.com/TechReborn/TechReborn/files/1443455/crash-2017-11-04_13.08.58-client.txt)

**Comment by modmuss50** [comment]
Try without optifine

**Comment by modmuss50** [comment]
Closing as no response was given.
