### ISSUE TITLE
FPS dropped when placing the TR machine [1.12.2]

### ISSUE THREAD

**Issue by lugiaf** [TechReborn/TechReborn#1338]
1. no TR machine
2. place Blast Furnace
3. Industrial Grinder x8 , Blast Furnace x4, Industrial Electrolyzer x2, Extractor x1

![2017-11-07_11 06 50](https://user-images.githubusercontent.com/32650275/32474396-b14c8264-c3af-11e7-8a7a-673c1ff30b11.png)
![2017-11-07_11 07 04](https://user-images.githubusercontent.com/32650275/32474386-a1aa744c-c3af-11e7-81ed-c0412ff67516.png)
![2017-11-07_11 13 42](https://user-images.githubusercontent.com/32650275/32474389-a7a2a644-c3af-11e7-8a5b-2fe79b85c34f.png)

i can not play X(

Forge: 14.23.0.2512
Reborn Core: 1.12.2-3.4.10.147
Tech Reborn: 1.12.2-2.8.0.333
modlist: https://pastebin.com/DkSdtDTJ

**Comment by modmuss50** [comment]
I can confirm this could be an issue.
