### ISSUE TITLE
[1.12] Plasma Generator not outputting correct amount

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1339]
The plasma generator is currently outputting 400 EU/t whereas it should output 2048 EU/t .

**Comment by Skillotic0703** [comment]
And also 1000 mB should get you 8192K EU

**Comment by drcrazy** [comment]
400 EU\t is generation rate, not output. Please, see screen below.
As for energy per bucket I've used this link to set value: 
https://ftb.gamepedia.com/Plasma_Generator_(GregTech_4)


![image](https://user-images.githubusercontent.com/1382352/32704930-9bde8620-c81e-11e7-9957-7ed4d2c69ccb.png)
