### ISSUE TITLE
SpongeForge Low tps

### ISSUE THREAD

**Issue by SawFowl** [TechReborn/TechReborn#1345]
Timings
https://timings.aikar.co/?id=b0040837a1504e4480e68531e6292f1e

**Comment by modmuss50** [comment]
Can you provide more information. Have you placed compressed air down? What version of the mod are you using? This isnt a lot of help.

**Comment by SawFowl** [comment]
The latest version of the mod.

All that was installed. I'm sorry, of course, I have everything in Russian, maybe you will not understand everything in the screenshots.
https://imgur.com/a/Zs8NB

**Comment by modmuss50** [comment]
Does this happen without sponge forge? As I dont usually provide support for it.

**Comment by SawFowl** [comment]
Without Sponge did not check. I'm only dealing with the server. Perhaps the problem was not with these blocks. In the spawn of the world, a failure occurred and some of the blocks were replaced by others, although the server delay decreased after I removed and then placed the structures that you can see in the screenshots.
If I have any more useful information, I'll let you know. If you need lists of mods and plugins on the server, then I can provide it.

**Comment by drcrazy** [comment]
"techreborn:techreborn_techreborn.compressedair" is an itemblock for CompressedAir fluid. And this is strange stuff. Block for compresed air is "fluidcompressedair". Players are not able to get "techreborn:techreborn_techreborn.compressedair" in a legit way.

**Comment by SawFowl** [comment]
I also did not use it, then the load on the server looks even stranger.

**Comment by modmuss50** [comment]
Please remove Sponge Forge, and reopen if the issue is still there.

**Comment by SawFowl** [comment]
Unfortunately this is no longer clear, after the server reboot the id of the blocks from the mod has changed to random, the delay has disappeared, but I now have to make a map of the past.

**Comment by SawFowl** [comment]
I'll try to put the update you did yesterday. If the problem recurs, I'll let you know.

**Comment by modmuss50** [comment]
Please remove sponge forge, and then come back for support.
