### ISSUE TITLE
Environmental Tech and Tech Reborn problem

### ISSUE THREAD

**Issue by GLugia** [TechReborn/TechReborn#1346]
Tech Reborn constantly retrogens ores while the Void Ore Miner is running. It's been causing the server to freeze but the client is fine. I'm not getting any errors either. It's just really tedious since I would prefer to not have to mine much (if at all) during my mid-game antics. I have noticed that I haven't been getting any of Reborn's ores through the miner so it may be that the mod is trying to generate ores for the miner to harvest but failing to do so which then leads to it re-attempting repeatedly.

I do understand Environmental Tech is in a sort of alpha state for 1.12 but I wanted to point this out since it could be bug on Reborn's side.  And here's my log:

https://pastebin.com/njf9mfj3

This happened about every 1-2 seconds according to the log. Turning of retrogen in the config solves the problem but I'm still not getting any of the ores.

**Comment by modmuss50** [comment]
Was TechReborn added later after the world was first generated?

**Comment by GLugia** [comment]
No. I added Tech Reborn during a world save that was set to creative and allowing cheats. The current world I play on was created after I added it and is survival without cheats.

**Comment by modmuss50** [comment]
I dont know how this could be our issue (Feel free to prove me wrong), I would recommend disabling retro gen and opening an issue on the ET tracker if you still have issues. Please let me know if you or the dev of ET have any ideas.
