### ISSUE TITLE
No energy use on eletric furnace with 4 speed upgrades

### ISSUE THREAD

**Issue by Yzelast** [TechReborn/TechReborn#1349]
Hey guys, after some time of playing my pack i think i found a bug with the eletric furnace.

After placing the fourth speed upgrade, the machine runs without energy cost.

I also recorded a video to show the bug occuring : https://youtu.be/bAKCsHID_54

forge 1.12.2-14.23.1.2557
techreborn 2.10.0.364
reborncore 3.5.1.166

**Comment by ZeekDaGeek** [comment]
Side note: Your a bunch of your friends phone numbers are in that video, you may want to edit, reupload it and update your ticket. <;

**Comment by Yzelast** [comment]
Oops, totally forgot this. This is another video: https://youtu.be/VTnJ0RJF7Mg
i made another because i edited the first one wrong and it was faster to make another.
Furthermore i did a minor forge update from 14.23.1.2557 to  14.23.1.2558

**Comment by modmuss50** [comment]
humm, that is a strange one. I think I know whats up. Should be an easy fix.
