### ISSUE TITLE
Rolling machine doesn't accept items from top

### ISSUE THREAD

**Issue by Locomotivers** [TechReborn/TechReborn#1351]
So I've trying to automate rolling machine with different mods (Integrated Tunnels, AE2) since R function doesn't work. but when I tried to input to the top side. Items won't go in at all. 

Here is a short video about it 

https://youtu.be/-doSzUQEDSw

forge - 14.23.1.2256
reborn core - 3.5.0.162
tech reborn - 2.10.0.364

**Comment by drcrazy** [comment]
Duplicate for #1321
