### ISSUE TITLE
Automation Woes

### ISSUE THREAD

**Issue by fallenhunter1** [TechReborn/TechReborn#1352]
Automation problem.

Been at this all day. off and on.

Seems that the Industrial grinder has a few issues, some might intentional, most should not.

1) I have not found a way to pipe water into said machine directly. Using an ender IO tank, and a bucket, atm.  Is this a piping issue or am I missing something.

2) Piping in Ores, the ores seem to go into any slot it feels like. No pattern I can find.
   Piping in buckets works just fine as long as there is ore in the processing slot. else it winds up in the ore processing  slot too. And the ore, esp any overflow, winds up in the bucket slot. 

Mostly had to babysit the thing all day. The Electrolyzer seems fine tho.

3 Water cells, do not seem to be fill-able (Its possible this is cause of the pack, however). by any automatic process. Ender IO tanks, bottler, etc. none seem to work.

Details:
Modpack, Age of Engineering  V1.1.2 (thus my comment on possible pack problem, highly modified configs).
TechReborn: 2.1.18.235 according to the Mod list screen.
Reborn Core 2.13.6.140 
Reborn Core-MCMultiPart 2.13.6.142

If more info is needed, let me know.. will check this again tomorrow.

Fallenhunter
Somewhere in Backwoods, Ohio

**Comment by drcrazy** [comment]
You can pipe water in 1.12
Piping ores just fixed.

![image](https://user-images.githubusercontent.com/1382352/33572130-17efe7ba-d943-11e7-9027-bc5db9e46b3d.png)
