### ISSUE TITLE
Potential bugs

### ISSUE THREAD

**Issue by ATMT88** [TechReborn/TechReborn#1354]
Hello TechReborn admins, 

Recently I found some potential bugs.

1. display problem and crash. Under 1.10.2 and 1.11.2, there are some display problems with the conductive threads and machines.
 Crash sometimes happens when putting multiple items into the digital/quantum box.

2. problem of the conductive thread. In 1.12 version, part of the threads are super-conductive, such as HV thread.

If I use a HV thread (long enough) to connect two empty MFSU, then put an energy crystal with 400,000FE into the input port.
Theoretically, I should have the same 400,000FE on the output port, but I got 3456 extra FE.

3.unusable AESU
Input is fine, output failed. Cannot put anything into the boxes, some buttons are not usable.
Same with IDSU.

**Comment by drcrazy** [comment]
Hello @xuexiaobin , 
Is p.3 about 1.12 ?

**Comment by drcrazy** [comment]
Just tested.
AESU transfers energy fine. Grinder got energy from it.
![image](https://user-images.githubusercontent.com/1382352/33721277-a18b4a4c-db77-11e7-903e-026641896da4.png)

There is an issue with GUI, like actual output rate is not show, Reproduced only in SMP.
![image](https://user-images.githubusercontent.com/1382352/33721473-2a2f75ee-db78-11e7-94ee-9483281403b3.png)
