### ISSUE TITLE
[1.12.2] Transformers not outputting to IC2

### ISSUE THREAD

**Issue by VermillionX** [TechReborn/TechReborn#1355]
With the IC2 Transformers config enabled so that the TR transformers are useful, they won't output to adjacent IC2 blocks through their output sides.

**Comment by modmuss50** [comment]
Working as intended:

![2017-12-17_21 28 16](https://user-images.githubusercontent.com/4324090/34083993-43442b6e-e371-11e7-87da-5747bb4ed6e4.png)
![2017-12-17_21 28 21](https://user-images.githubusercontent.com/4324090/34083994-44db8332-e371-11e7-919c-00534d164307.png)
![2017-12-17_21 28 23](https://user-images.githubusercontent.com/4324090/34083996-462c6940-e371-11e7-8e43-91f332d9242d.png)
