### ISSUE TITLE
[1.12+] Allow discharging IC2 items

### ISSUE THREAD

**Issue by OneEyeMaker** [TechReborn/TechReborn#1357]
Hello.
Mostly, the title says it all. Energy containers (and other machines) of this mod allow charging IC2 items, but not allow discharging.
It can be done simply, because IC2 API (find it on [Jenkins](http://jenkins.ic2.player.to/job/IC2_112/16/)) provides such methods (check ```ic2.api.item.IElectricItemManager```). Just by adding similar helper method:
https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/utils/IC2ItemCharger.java#L34

If there are reasons, why this functionality isn't implemented, please mention ones.
And thank you for your mods!

**Comment by modmuss50** [comment]
Yeah, that should be possible.
