### ISSUE TITLE
[1.12] Error in console

### ISSUE THREAD

**Issue by VimbaTheFish** [TechReborn/TechReborn#1359]
I do't know, does it have any influence on gameplay, but anyway, error in console: https://pastebin.com/ZhayKTar

forge-1.12.2-14.23.0.2551-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2742.jar

**Comment by modmuss50** [comment]
Seems like an issue with sponge forge, but I should be able to fix it.
