### ISSUE TITLE
All 4 versions of TechReborn on curse crash with IC2.Classic.Version.1.1.0.19. both Forge 1448 and 1492

### ISSUE THREAD

**Issue by VenomFrog** [TechReborn/TechReborn#136]
im just testing compad with these two and i cant get TechReborn to even launch by itself, so i tried with IC2 Classic and still, crash on startup, both versions of forge, all 4 versions. 
Not sure if this is right place, but TechReborn-Classic is empty.
Thank you!

**Comment by modmuss50** [comment]
We have a special version in the works to work with ic2 classic. We will work on it when we have a stable build for the normal ic2

**Comment by VenomFrog** [comment]
Okay! I'm sorry for creating an issue for that, just wasnt aware you are working on one :) good to hear, love the mod!

**Comment by modmuss50** [comment]
You can see the current state of it here: http://modmuss50.me:8080/job/TechReborn-Classic/

It has not been updated in a while but it should work. There is no recipes yet.

**Comment by VenomFrog** [comment]
aah, thank you very much! Ill fave that link. Can't wait for actual IC2 release!

Is the Reborn-Classic version something you see realistically finishing as well?

**Comment by modmuss50** [comment]
Yes but it could be a while.

**Comment by VenomFrog** [comment]
Aah well the stable IC2 release is priority :)
Thanks for answering my questions!

**Comment by Carbon-Ghost** [comment]
Though modmuss, may I request to update TechReborn Classic with the new AESU & IDSU gui and stuff, Modtweaker integration and the thermal generator changes pretty please =3 ?

**Comment by modmuss50** [comment]
Im working on merging the changed from the past 2 months

**Comment by Carbon-Ghost** [comment]
thanks :D

**Comment by modmuss50** [comment]
We can make it work on one version, we wont need to have 2 in the future. It needs a bit of work to make that happen but it wont be too hard. and over 120 changes are now merged http://modmuss50.me:8080/job/TechReborn-Classic/

**Comment by Carbon-Ghost** [comment]
nice, but there will be a hotfix version of ic2 soon...
