### ISSUE TITLE
[Suggestion] Add fluid handling capabilities to the Assembling Machine

### ISSUE THREAD

**Issue by KAfable** [TechReborn/TechReborn#1360]
I know this goes beyond the scope of GT that TR was based on, but would it be possible to add fluid tanks/fluid handling/consumption to the Assembling Machine?

**GUI Changes**
The UI has some whitespace on the left you can add for a vertical bar representing the tank similar to the one  in the industrial grinder. It'll also probably need a slot below that to allow players to shift click portable tanks, cells, or buckets to fill up the bar.

**Fluid Inputs**
Not sure if this will make a big change from the mods current progression, but from a modpack perspective, if a modpack author wants to use a machine that has both item and fluid inputs, the only choice they have is to use the Forestry Carpenter (which isn't very high techlike) or use Modular Machinery (which for some applications is kinda overkill, although it is very customizable). I figured the TR assembling machine could be a good inbetween with the crafttweaker support you already offer.

**Comment by modmuss50** [comment]
To even think about doing this the machine needs to be moved to the new gui system.

**Comment by KAfable** [comment]
Does that mean it's not likely to happen? If so, I can close the issue if you want, only a suggestion that would make life easier for a pack dev like me.

**Comment by modmuss50** [comment]
Sadly I dont think this is going to happen. There are plenty of other machines you could use to use fuel. If you really want it to happen I urge you to make PR. Thanks for the suggestion.
