### ISSUE TITLE
Gold Block in Compressor makes Iron Plates

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1361]
See Video:

https://pudding.tk/YUtoqSRM.mp4

Minecraft-Version: 1.12.2
Mod-Version: TechReborn-1.12.2-2.9.1.354-universal
ModPack: Modern Skyblock 2 Version 2.7.2.2

**Comment by drcrazy** [comment]
Not reproduced.

![image](https://user-images.githubusercontent.com/1382352/33822768-d10714aa-de69-11e7-96c6-1eeb702a438d.png)
