### ISSUE TITLE
Gold Block in Compressor makes Iron Plates Part 2

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1362]
See here: https://github.com/TechReborn/TechReborn/issues/1361

Dont close >.<

i think the bug comes with Thermal Foundation

**Comment by drcrazy** [comment]
I saw video. Clean install of MC with TR only doesn't have this issue. Please, report to whatever mod register Block of Gold with ore dictionary name as 'blockMetal'

**Comment by modmuss50** [comment]
I think this might be our issue. Ill take a look at it when I get a chance
