### ISSUE TITLE
multi block

### ISSUE THREAD

**Issue by deathtar** [TechReborn/TechReborn#1363]
i am working on building a mod pack i have your mod in it every think seems to be working fine except when i place any part on a multi block other than the main block
and yes i do have the latest version
it crashes my server and my game

**Comment by deathtar** [comment]
i am working on building a mod pack i have your mod in it every think seems to be working fine except when i place any part on a multi block other than the main block
and yes i do have the latest version

**Comment by deathtar** [comment]
it crashes my server and my game

**Comment by covers1624** [comment]
Not really helpful, we can't read minds or log on to your computer to grab the crash report. Please provide it through a service such as http://pastebin.com or https://gist.github.com/

**Comment by deathtar** [comment]
[crash-2017-12-07_15.49.31-server.txt.zip](https://github.com/TechReborn/TechReborn/files/1550140/crash-2017-12-07_15.49.31-server.txt.zip)

**Comment by deathtar** [comment]
[crash-2017-12-07_15.49.31-server.txt](https://github.com/TechReborn/TechReborn/files/1550141/crash-2017-12-07_15.49.31-server.txt)

**Comment by deathtar** [comment]
sry i dint think about adding that i hope this can be fix i really want to add this to my mod pack

**Comment by drcrazy** [comment]
Please, update Reborn Core to at least RebornCore-1.12.2-3.5.0.162

**Comment by deathtar** [comment]
this is the one i have and have had
TechReborn-1.12.2-2.10.1.375-universal.jar

**Comment by drcrazy** [comment]
yes, this is an old one
In recent RC version there is a change in internals for multiblock casings. And this change is both in RC and TR. You have updated TR which requires more recent RC. )
