### ISSUE TITLE
#1319 issue still present on the latest release (importer upgrade placing items in output slot)

### ISSUE THREAD

**Issue by aerde** [TechReborn/TechReborn#1364]
Hi! 
Playing on Modern Skyblock 2 modpack, Tech reborn and Reborn core are completely up to date, forge 2562, reborn core .171.
Importer upgrade when placed into electric furnace, still fiiling output slot. Also, don't know if it's a bug or not, importer interface (when right-click on it) doesn't display any changes on clicking checkbox buttons. This checkboxes are always checked in gui. It's only a visual bug, but slightly annoying.

**Comment by modmuss50** [comment]
Ah electric furnace, that doesn't use the same crafting system as the other tiles.

Ill take a look at the gui.

**Comment by aerde** [comment]
Thanks for fast reply!
So I just should avoid using this upgrade in electric furnace, I suppose. Hope this will change some time =)
