### ISSUE TITLE
Crescent Hammer

### ISSUE THREAD

**Issue by Dannez** [TechReborn/TechReborn#1367]
Forge 1.12.2-14.23.1.2566 (Latest)
Tech Reborn 1.12.2-2.10.0.364
Reborn Core 1.12.2-3.5.1.166

Using a crescent hammer on the ultimate hybrid solar panel crashes the game. Untested on other solar panels (due to crash).

**Comment by modmuss50** [comment]
all ready fixed in 2.10.1.375
