### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by NotTooSlick** [TechReborn/TechReborn#1370]
I am testing this mod for a 1.12 pack I am helping with, mod version 2.7.10.327.

The crash occurs anytime I place any of the Machine Casings and it creates https://pastebin.com/36EGLFJD that report. Tested with the Standard, Reinforced and Advanced. I'd assume it would also crash servers.

The Recycler doesn't produce anything regardless of what I put inside it.

There are no recipes to use with the assembler (not sure if that's intentional nothing I tried worked).

That is all I have encountered so far.

**Comment by modmuss50** [comment]
Update reborn core to fix the first one.

The assembler isn’t supposed to have recipes.

The recycler should work, I’ll take a look at it.

**Comment by NotTooSlick** [comment]
One more thing, it seems when some machines are full and an item is inserted to trigger an operation, the capacity bugs out and does this .. https://cdn.discordapp.com/attachments/364455317985165313/392081362175262720/unknown.png
(This specifically was with the Electric Furnace, but I've also seen it in the Grinder)

Note that it is not connected to any powersource or any cable at the time.

**Comment by Tarus5** [comment]
Im not sure but i think the casing block crash hasnt been fixed in the newest patch, i still get the same crash after trying to log in https://pastebin.com/3C0RyWQB

**Comment by modmuss50** [comment]
Did you update reborn core?

**Comment by Tarus5** [comment]
now its fine i think thx

**Comment by modmuss50** [comment]
Recycler works fine.
