### ISSUE TITLE
TPS goes down when having AutoCraftingTable 

### ISSUE THREAD

**Issue by JoeSGT** [TechReborn/TechReborn#1374]
Here are my version 
Forge 1.12.2-14.23.1.2565
TechReborn 1.12.2-2.10.3.386
RebornCore 1.12.2-3.5.3.174

it seem having Autocraftingtable is causing my server to lag extreme
`	
Minecraft::tickTileEntity - techreborn:TileAutoCraftingTableTRcount(124540)  total(31.12% 291.779s, 59.96% of tick)avg(2.34ms per - 29.98ms/12.80 per tick`

here is the timings report 
https://timings.aikar.co/?id=cc328c9b62a24f88846283614cbcaf3d

is there a way to fix this issue thanks

**Comment by modmuss50** [comment]
Humm. I’ll profile it more. What recipe are you using? And are you using the book to set the recipe?

**Comment by JoeSGT** [comment]
Sorry im not sure player on my server lag the server hardcore with using those
but if you would like i can look into it a bit more?

**Comment by JoeSGT** [comment]
I did some testing and if you place down to about 17 autocraftingtable
the TPS start to go down

**Comment by JoeSGT** [comment]
This is very bad performance, because let's say you have 30 players
and those players each place 1 down in there base then the TPS goes straight down

**Comment by DumbSlayer** [comment]
omg I've crashed so many servers with this xD

**Comment by modmuss50** [comment]
It should be a bit better now, ill work on it some more when I have some more time. Locking this issue to keep the kids out.
