### ISSUE TITLE
1.12 Error in console

### ISSUE THREAD

**Issue by VimbaTheFish** [TechReborn/TechReborn#1383]
Every version is latest

Error in console: https://pastebin.com/A9HAXGgJ

spongeforge-1.12.2-2555-7.0.0-BETA-2797.jar
TechReborn-1.12.2-2.11.0.399-universal.jar

**Comment by modmuss50** [comment]
What version of reborn core are you using?

**Comment by VimbaTheFish** [comment]
RebornCore-1.12.2-3.6.0.178-universal.jar
