### ISSUE TITLE
Crashing When Using the Wrench

### ISSUE THREAD

**Issue by InterPlay02** [TechReborn/TechReborn#1384]
Hello!

I'm here today to tell you that this is the second crash I had due to this... "action".
When I right click, with a wrench in hands, in a block that was not made to be rotated, the game crashes.
I am talking about the wrench from Tech Reborn.
Here is the crash log:
https://pastebin.com/JhSkgvB8
I got this crash log when Tried to rotate one of the solar panels... The advanced one.
And my suggestion is: Instead of crashing the game, this action should simply... do nothing. Right?
Is that a good idea?
Ok, just joking...
I hope you fixe it for people! =]

**Comment by drcrazy** [comment]
Please, update both TechReborn and RebornCore to latest versions. 
Duplicate for #1358
