### ISSUE TITLE
[1.12.2] Crash with Cresent Hammer of Thermal Expansion

### ISSUE THREAD

**Issue by Draskh** [TechReborn/TechReborn#1387]
I clicked with a Cresent Hammer of Thermal Expansion on a auto crafting table and the game crashed. 
[crash-2017-12-28_10.16.29-client.txt](https://github.com/TechReborn/TechReborn/files/1591288/crash-2017-12-28_10.16.29-client.txt)

**Comment by modmuss50** [comment]
Update TechReborn, Duplicate of #1358
