### ISSUE TITLE
[1.12] Plasma Generator JEI GUI bug

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1390]
![2017-12-29_00 09 46](https://user-images.githubusercontent.com/12701912/34425498-b78645ac-ec2c-11e7-965f-f5821a497b25.png)
When I look the recipes of the plasma generator in JEI, I get this visual glitch.

**Comment by drcrazy** [comment]
It is already fixed in recent release TechReborn-1.12.2-2.11.0.410
