### ISSUE TITLE
1.12 Error spammin in console

### ISSUE THREAD

**Issue by VimbaTheFish** [TechReborn/TechReborn#1393]
TechReborn-1.12.2-2.11.0.399-universal.jar
RebornCore-1.12.2-3.6.0.178-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2797.jar

https://pastebin.com/dk5fe09v

I saw it spamming today a lot of times, don't know why does it happens

**Comment by VimbaTheFish** [comment]
Updated to the latest versions of RC and TR, problem is still exist.

**Comment by modmuss50** [comment]
Sponge forge is most likely causing this, I can only assume it messes with ray tracing, and is returning a null RayTraceResult. I have added a check for this that will hopefully fix it.

**Comment by covers1624** [comment]
Null is a valid result for World.rayTrace btw, even under vanilla forge.

**Comment by modmuss50** [comment]
ah, I wasn't aware of that, that should fix the issue then. Thanks covers.
