### ISSUE TITLE
[1.12.2] Some recipes do not use Ore Dictionary (Compatibility with other mods)

### ISSUE THREAD

**Issue by Draskh** [TechReborn/TechReborn#1394]
I tried to craft a carbon plate but it failed because a recipe accepts only coal dust of Tech Reborn. But the items are unified so only Thermal Expansion coal dust is craftable. The recipe of Tech Reborn will not work if it not change to listalldustCoal. 
Then I tried to smelt electrum but that failed too because the machine only accepts silver ingots of Tech Reborn. This recipes should be changed to listallingotsSilver.
I do know which recipes are affected but I think the recipes should be reworked. I don't use much Tech Reborn stuff in my modpack. So I think that wouldn't be accidentally the two recipes that can't be used.

**Comment by xiaoschannel** [comment]
same problem here. just curious though, why this happens at all? not a problem i'd expect from pros like you guys

**Comment by drcrazy** [comment]
Carbon plate recipe shapeless and was causing issues with IC2. Like it was using ore dictionary and was producing TR plates and not IC2 and IC2 requires IC2 plates and there was no way to get them. I will think on what could be done with carbon plates.

**Comment by drcrazy** [comment]
As for alloy smelter it is already accepting any silver ingots. 

![image](https://user-images.githubusercontent.com/1382352/34849524-b119dc6c-f733-11e7-9f28-4b4823442088.png)
