### ISSUE TITLE
[1.12.2] Crash when placing fusion control computer and impossible to automatically import items

### ISSUE THREAD

**Issue by tregeiw2** [TechReborn/TechReborn#1395]
When i place down a fusion control computer i crash instantly. (Only Tech Reborn and JEI installed)

Also since 'TechReborn-1.12.2-2.11.1.420' i can no longer import items into the fusion control computer.
I tried vanilla hoppers and also several options from other mods (Itemducts, Mekanism pipes, ESD from Actually Additions) but none have worked

**Comment by ZeekDaGeek** [comment]
Also fusion recipes seem to start when they don't have enough power if you put the items in manually.

**Comment by modmuss50** [comment]
I cannot reproduce the issues with it starting when the input power isn't full.
![java_2018-01-12_19-53-09](https://user-images.githubusercontent.com/4324090/34892735-50a74d3e-f7d2-11e7-99dd-f6516b4abe43.png)

The crash has been fixed. If you can provide more info @ZeekDaGeek can you open another issues. Thanks.
