### ISSUE TITLE
Thermal Generator crashes

### ISSUE THREAD

**Issue by sironin** [TechReborn/TechReborn#140]
Description: Ticking block entity

java.lang.StackOverflowError: Ticking block entity
at techreborn.tiles.TileThermalGenerator.getTankInfo(TileThermalGenerator.java:105)
(the above line repeats 2048 times)

replication instructions:
Using extrautils for fluid transport:
Place thermal generator
Place drum full of lava
place liquid transfer node on drum going into thermal generator
Game crashes as above
Not sure if this is an extrautils problem or a techreborn problem.  The same test works fine with wooden fluid extraction pipe from buildcraft instead of the liquid transfer node.

**Comment by modmuss50** [comment]
This was an issue with a lot of the machines, Im just testing the fix now
