### ISSUE TITLE
How can I Translate this?

### ISSUE THREAD

**Issue by InterPlay02** [TechReborn/TechReborn#1402]
Hello!

This is what I'm talking about:
![faltando traduzir 2](https://user-images.githubusercontent.com/23037423/34632627-ba79667c-f25d-11e7-9ca4-4b90987bf373.png)
![faltando traduzir 1](https://user-images.githubusercontent.com/23037423/34632643-c595ae6c-f25d-11e7-86b0-afa3daa16bc9.png)

Is this related to Hwyla, or to Tech Reborn?

**Comment by modmuss50** [comment]
This is techreborn, it would be really easy to add it to the lang file. Thanks for bringing it up.

**Comment by drcrazy** [comment]
@InterPlay02 Is your question about block name or about energy stuff?

**Comment by InterPlay02** [comment]
Energy stuff... =]

**Comment by InterPlay02** [comment]
As you can see, the block names are already translated.

**Comment by drcrazy** [comment]
It's hard to judge if Compressor is already translated )))

**Comment by InterPlay02** [comment]
I understand you. Brazilian Portuguese is more similar to English than you can imagine.

**Comment by drcrazy** [comment]
Should be translatable now. Power info for most of machines is actually from RebornCore, so please, feel free to add pt_br translation to RebornCore
