### ISSUE TITLE
Distillation Tower Crafttweaker Support

### ISSUE THREAD

**Issue by Kevun1** [TechReborn/TechReborn#1403]
Currently, it looks like there's no Crafttweaker support for Tech Reborn's Distillation Tower. It would greatly help out in the modpack I'm working on if CT support was added.

Btw, thanks a lot for your work on the mod!

**Comment by drcrazy** [comment]
Hi @Kevun1 ,

it is there for some time already. What version do you use?
As I can see you can add and remove recipes to Distillation Tower,

https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/compat/crafttweaker/CTDistillationTower.java
