### ISSUE TITLE
(Suggestion) Liquid Rubber Processing System

### ISSUE THREAD

**Issue by ArticulatedDrunk** [TechReborn/TechReborn#1405]
So the idea is you tap rubber trees more like you would in real life. Drilling a hole and then placing the tap in the tree and collecting the sap that leaks out. This segways brilliantly into a liquid processing system for rubber. The idea was to have it pumped/channeled off into a machine or series of machines for processing for a cooler/more immersive way to process and increase the yield of rubber than the extractor. For early game you could set up an extremely inefficient drying system to still obtain a smeltable rubber. Heck maybe even leave in the rubber processing for the extractor and then just have this for a higher tier of processing above that.

Credit for the idea is explained below:
Prompt for the conversation from Vyraal1 on the discord.

Modmuss and I were talking about how you would go about automating rubber collection in the discord. Original idea was a machine at the bottom or top of a tree that just collected it into its inventory but as we talked we thought of the tap mechanic itself and I suggested making it more realistic. Drilling a hole in the tree and then placing in a tap and putting a bucket below it to collect the sap. Modmuss had the idea to make it a liquid system then and the main idea took form here.

**Comment by modmuss50** [comment]
There is a lot of room for improvement here, but like I said on discord I don't think im going to get the time over the coming months to sit down and do everything needed to something like this. So if anyone else wants to have a crack at this hit me up on discord.

**Comment by modmuss50** [comment]
This isnt going to happen soon, but we have been talking about it for a while so it may happen at some point.

Thanks for your suggestion.
