### ISSUE TITLE
[1.12] Can't remove Iridium from the Industrial Grinder

### ISSUE THREAD

**Issue by MasterEnderman** [TechReborn/TechReborn#1409]
Script:
```
mods.techreborn.grinder.removeRecipe(<techreborn:ingot:7>);
mods.techreborn.grinder.removeInputRecipe(<techreborn:ore:1>);
```

I know that I only need one of the lines but i tried both.

CraftTweaker.log output;
```
[INITIALIZATION][CLIENT][INFO] Removing tile.techreborn.grinder.name recipe for Iridium Ingot
[INITIALIZATION][CLIENT][INFO] Removing tile.techreborn.grinder.name recipe
```

I still can process Iridium Ore in the industrial Grinder.

RebornCore: 3.6.1.183
TechReborn: 2.11.1.420
Forge: 14.23.1.2587

**Comment by drcrazy** [comment]
Please, use mods.techreborn.industrialGrinder. There are two grinders in TR. Simple one is not processing Iridium ore by default. So no reason to remove Iridium from it.

**Comment by MasterEnderman** [comment]
so this documentation is outdated?
https://wiki.techreborn.ovh/doku.php?id=development:mt

**Comment by drcrazy** [comment]
Yeah, it looks so

**Comment by drcrazy** [comment]
Wiki for industrial grinder CT support updated
