### ISSUE TITLE
Various Texture Issues v842

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#141]
![2015-09-13_23 31 14](https://cloud.githubusercontent.com/assets/7843312/9836908/97ff5ac6-5a6f-11e5-9faf-95342fe0f6f3.png)

**Comment by TheQuantumGeneral** [comment]
All 3 missing inventory textures, only centrifuge gets a texture when placed.

**Comment by TheQuantumGeneral** [comment]
Also, I think a lot of blocks are rendering with the wrong orientation or something in inventory form, most of them seem to be facing backwards/upside down?

![2015-09-13_23 38 21](https://cloud.githubusercontent.com/assets/7843312/9836940/91588ed0-5a70-11e5-8481-3623a9f977e2.png)

**Comment by modmuss50** [comment]
Ah when we moved to tile based meta it must have broken the facing texture, should be an easy ish fix
