### ISSUE TITLE
Fusion reactor problems still in 1.10.2

### ISSUE THREAD

**Issue by Mac15001900** [TechReborn/TechReborn#1416]
It is possible to backport the fix to #1187 to 1.10.2? It would make fusion reactors a lot more usable.

**Comment by drcrazy** [comment]
@Mac15001900  Can you try this build, please? 
https://jenkins.modmuss50.me/job/TeamReborn/job/TechReborn/job/TechReborn-1.10.2/237/artifact/build/libs/TechReborn-1.10.2-2.1.18.237-universal.jar

**Comment by Mac15001900** [comment]
Thank you very much, that helped with both item insertion and reaction resetting.

One bug I noticed though is that once you start a reaction and take out the fuel the reaction still completes, producing both energy and the item, without consuming any fuel (I guess this is probably still being worked on but wanted to let you know just in case).

**Comment by drcrazy** [comment]
ok, i will check. thank you for testing

**Comment by drcrazy** [comment]
@Mac15001900  May I ask you to test once again, please?
https://jenkins.modmuss50.me/job/TeamReborn/job/TechReborn/job/TechReborn-1.10.2/lastSuccessfulBuild/artifact/build/libs/TechReborn-1.10.2-2.1.18.239-universal.jar

**Comment by drcrazy** [comment]
Fixed in TechReborn-1.10.2-2.1.19.240
