### ISSUE TITLE
[1.12.2] Wrenching Computer Cube or Auto Crafting Table

### ISSUE THREAD

**Issue by VermillionX** [TechReborn/TechReborn#1417]
Wrenching a Computer Cube or Auto Crafting Table yields a crash and doesn't even remove the block.

**Comment by modmuss50** [comment]
Can you post the crash log if possible?

**Comment by VermillionX** [comment]
[crash-2018-01-23_13.38.47-client.txt](https://github.com/TechReborn/TechReborn/files/1656185/crash-2018-01-23_13.38.47-client.txt)
