### ISSUE TITLE
PDA issues v842

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#142]
When you press the config button and come back to the PDA all the buttons stop working and the background dissapears

![2015-09-13_23 41 43](https://cloud.githubusercontent.com/assets/7843312/9836961/2d706a4a-5a71-11e5-949e-4187d556750c.png)

Also, pressing the back button produces two separate sounds, a click which is normal, but also some weird secondary noise which is really, not right.

Also, I know its W.I.P but as a critique, the pure black background is very harsh. Something silvery/grey/metallic would be a bit more pleasant, or anything but black.

**Comment by gigabit101** [comment]
I know it needs a new Gui texture and yes it a WIP

**Comment by Carbon-Ghost** [comment]
Assign me for textures :P
