### ISSUE TITLE
Can I share this mod with the minecraft forum in China?

### ISSUE THREAD

**Issue by 6Bpencle** [TechReborn/TechReborn#1420]
The mod is very interesting ,I very like it.I think you can do it better.So I want to share this mod with the minecraft forum in China.This is [website](http://www.mcbbs.net/thread-777062-1-1.html),and let more friends use it.I hope you can agree!

**Comment by modmuss50** [comment]
sure, just make sure you keep it updated. 👍

**Comment by drcrazy** [comment]
Maybe it will worth to mention that Tech Reborn depends on Reborn Core. You already mentioned Forge as requirement. Reborn Core is a second requirement for Tech Reborn.
