### ISSUE TITLE
The game crash when I click “configuring slot”

### ISSUE THREAD

**Issue by DTouble** [TechReborn/TechReborn#1421]
crashlog: The game crashed whilst rendering screen
              Error: java.lang.NullPointerException: Rendering screen

**Comment by DTouble** [comment]
both reborncore and techreborn are updated to the latest version

**Comment by modmuss50** [comment]
I need the full log

**Comment by DTouble** [comment]
[crash-2018-01-28_22.01.36-client.txt](https://github.com/TechReborn/TechReborn/files/1671138/crash-2018-01-28_22.01.36-client.txt)
[latest.log](https://github.com/TechReborn/TechReborn/files/1671139/latest.log)

**Comment by DTouble** [comment]
another bug: using crafting table causes the game to crash
[crash-2018-01-29_09.44.02-client.txt](https://github.com/TechReborn/TechReborn/files/1671904/crash-2018-01-29_09.44.02-client.txt)

**Comment by drcrazy** [comment]
I can reproduce it only in SMP. 
Steps to reproduce:
1) Place electric furnace in the world
2) Open GUI
3) Open slot config

https://pastebin.com/0Yexnqcq

**Comment by modmuss50** [comment]
<img width="1680" alt="screen shot 2018-01-29 at 13 11 42" src="https://user-images.githubusercontent.com/4324090/35511983-ffe885f8-04f5-11e8-8a46-8061ca9b021f.png">

interesting, I cannot get it to crash, even when opening the slot config gui. Ill have to have a good look at this.

**Comment by modmuss50** [comment]
anyway, ive added 2 null checks so that commit should catch it.

**Comment by DTouble** [comment]
Actually，It is "clicking the red part" causes the game to crash. I'm sorry for that

**Comment by modmuss50** [comment]
yeah, that fix should fix it, if not ill have to take a better look at it.

**Comment by DTouble** [comment]
thanks a lot. I really like this mod and I appreciate for your contribution！
BTW，will that fix the auto crafting table bug as well？

**Comment by modmuss50** [comment]
No, ive opened another issue about it: https://github.com/TechReborn/TechReborn/issues/1423
