### ISSUE TITLE
Auto crafting table crash

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#1423]
https://github.com/TechReborn/TechReborn/files/1671904/crash-2018-01-29_09.44.02-client.txt

**Comment by modmuss50** [comment]
@DTouble were you on a server when you saw this crash?

**Comment by DTouble** [comment]
no

**Comment by DTouble** [comment]
the log said something about rending screen. it is as same as the configuring slot crash. I think maybe they are the same issue？ 
I asked my friend to test configuring slot and the game crashed. But I haven't test auto crafting table on his pc yet

**Comment by modmuss50** [comment]
no its not, Ive seen this crash before once or twice, im just not sure of a way to reproduce it in a dev environment.

**Comment by DTouble** [comment]
evertime i try it will crash on the latest version. btw, it works well on 1.10. Hope
that it can help

**Comment by modmuss50** [comment]
Any chance you could zip up your world and send it to me? As I cannot get it to crash, but I have seen this issue before. Failing that if someone can get the crash log while in a dev env it would help a lot.

**Comment by DTouble** [comment]
[crash save.zip](https://github.com/TechReborn/TechReborn/files/1681496/crash.save.zip)
just a new world

**Comment by modmuss50** [comment]
Ok, thanks for that. It seems like it only happens when running in an obfuscated environment. now the question is why.

**Comment by modmuss50** [comment]
Hi, I think ive fixed it. Any chance you can grab a dev build from the links bellow: 

https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.12/
https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.12/

Note: you will need the dev version of reborn core as well as I changed some stuff. Let me know how it goes. Thanks for you help.

**Comment by DTouble** [comment]
How do i use it? Just like the universal edition?
If it is, then i cant start the minecraft with them. The game crashed at the process that forge was loading mods

**Comment by drcrazy** [comment]
@DTouble 
You need to take dev version of both TR and RC.
Direct links for jars:
https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.12/lastSuccessfulBuild/artifact/build/libs/RebornCore-1.12.2-3.6.5.201-dev.jar

https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.12/lastSuccessfulBuild/artifact/build/libs/TechReborn-1.12.2-2.12.2.467-dev.jar

**Comment by DTouble** [comment]
Sure, I take them both and put them in mods folder.

**Comment by DTouble** [comment]
Iet me ask my friend to give it a shot

**Comment by modmuss50** [comment]
no not those ones @drcrazy you need the universal jars:
https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.12/201/artifact/build/libs/RebornCore-1.12.2-3.6.5.201-universal.jar

and

https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.12/467/artifact/build/libs/TechReborn-1.12.2-2.12.2.467-universal.jar

**Comment by drcrazy** [comment]
You said that dev version is needed ))

**Comment by drcrazy** [comment]
Looks weird 

![image](https://user-images.githubusercontent.com/1382352/35649010-b668bac0-06e8-11e8-8008-167fe2094eee.png)

And this is forge 2594, not 2555 as in original crash log

**Comment by drcrazy** [comment]
forge version 2555 also fine in SSP

**Comment by DTouble** [comment]
It does fix it.
