### ISSUE TITLE
Nitrofuel Cells

### ISSUE THREAD

**Issue by VermillionX** [TechReborn/TechReborn#1424]
Probably missing a 0 in the energy values, but anyway...
Nitrofuel Cells require 96kFE to be made by the Chemical Reactor from 1 Oil Cell and 1 Nitrogen Cell and gives 2 cells. They produce 96k FE per cell in a diesel generator, while the oil cell that produces them makes 256k FE in a semifluid generator.
... why?

**Comment by modmuss50** [comment]
yeah, sounds like they need a buff

**Comment by drcrazy** [comment]
oil should do 64k FE per cell as per https://wiki.industrial-craft.net/index.php?title=Semifluid_Generator
