### ISSUE TITLE
Electric Furnace flicker on 4 overclockers

### ISSUE THREAD

**Issue by bpwhelan** [TechReborn/TechReborn#1425]
The Electric furnace flickers when it's processing items really fast, which causes massive fps drop.

Betterfps and foamfix were installed during recording. After recording i installed optifine, which seems to remove the fps drop altogether. Note the FPS counter in the F3 view, and on the right where it shows Active: flickering between "True" and "False."

https://youtu.be/M9jtSaOWLTI

Apologies for the podcast going in the background. Politics OP :P

**Comment by modmuss50** [comment]
Ah yeah, that should be an easy fix. Thanks for spotting it.
