### ISSUE TITLE
Grinder giving lapis dust for ALL dyes

### ISSUE THREAD

**Issue by bpwhelan** [TechReborn/TechReborn#1426]
Simply put, Grinder is grinding bone meal and other dyes into lapis dust. Looks like the grinder is accidentally checking for dye -> lapis dust instead of dyeBlue -> lapis dust.

https://prnt.sc/i7y61y

https://prnt.sc/i7y68c

**Comment by modmuss50** [comment]
Yep, that should be an easy fix.
