### ISSUE TITLE
AutoCraftingTable low performance 

### ISSUE THREAD

**Issue by JoeSGT** [TechReborn/TechReborn#1429]
Hey i crash when i place rolling machine
version i use is 
TechReborn: 1.12.2-2.12.2.467-universal
reborncore: 1.12.2-3.6.5.201-universal
only reason why i update to the jenkins build because my server starting cpu and tps starting to tick up high due to autocrafting table 
https://timings.aikar.co/?id=e3419304a509444dace15721742253e3 
https://pastebin.com/QBriVka3

**Comment by JoeSGT** [comment]
it seem just having a few my TPS is still going high 
https://timings.aikar.co/?id=3f093b6f807e4c48a8d9e44767a88814
is there a way to disable this item without having players losing there items that inside the autocrafting table

**Comment by modmuss50** [comment]
Crash fixed. I need to look at the ATC in more detail when I get a chance.

**Comment by modmuss50** [comment]
What have you got in the auto crafting table? have you got a recipe crafting? Or is there just a recipe selected? Any chance you can use sampler to get me a more detailed profile of the lag?

**Comment by JoeSGT** [comment]
I dont know how to mess with Sampler but there just a recipe selected only 3 of them laggin the server

**Comment by JoeSGT** [comment]
![4f0992f371c06d5e5390a1c9bfd12ead](https://user-images.githubusercontent.com/30296350/36174278-dffde126-10d9-11e8-8c41-4afbaa81500c.png)
as you can see proof of what lagging and i hope it help using WarmRoast.

**Comment by JoeSGT** [comment]
possibly have to do something with this
https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/tiles/TileAutoCraftingTable.java#L133-L162

**Comment by modmuss50** [comment]
Ah ok, that helps a lot, thanks. The actual issue is here, as it checks for valid recipes each tick. Some things need to be cached to make it work. https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/tiles/TileAutoCraftingTable.java#L95-L98

**Comment by JoeSGT** [comment]
Glad to hear that it help. I'm happy that i learned warmroast xD thanks! for working on this issue

**Comment by DumbSlayer** [comment]
I've use this to lag servers lol love this bug

**Comment by JoeSGT** [comment]
since this fix is not going to get fix soon is there a way to disable ?

**Comment by JamesMC100** [comment]
I am having the same exact problem please fix @modmuss50 
There are already players using it and my TPS is at 1-2 most of the time really bad!!!!

**Comment by modmuss50** [comment]
ok, i've added high priority, if the worst comes to the worst I will have to disable it for a bit. I've been super busy doing other work the last few weeks.

**Comment by drcrazy** [comment]
@JoeSGT  May I ask you to test with dev build from here: https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.12/493/artifact/build/libs/TechReborn-1.12.2-2.12.3.493-universal.jar

RebornCore-1.12.2-3.6.8.214-universal.jar available on curse should be fine.

**Comment by JoeSGT** [comment]
it seem it worked. i can still autocraft but not lagging the server
EDIT: it seem i cannot use the pipes too take the items out automatically

**Comment by drcrazy** [comment]
Have you configured output side using tab with wrench icon?

**Comment by JoeSGT** [comment]
yes i have it's fine until this get an fix and not a temporary fix

**Comment by modmuss50** [comment]
Ok, it seems @drcrazy has disabled the slow custom recipe lookup. This will be re-added when I/or someone else works on improving this code to also work for the Rolling Machine.
