### ISSUE TITLE
Kanthal and Nichrome heating coils are using placeholder recipes

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#143]
Kanthal can't be made yet though, but Nichrome can. 

![capt1ure](https://cloud.githubusercontent.com/assets/7843312/9836983/0555722a-5a72-11e5-9847-f8c29eb02143.PNG)
![capture](https://cloud.githubusercontent.com/assets/7843312/9836982/0550c4b4-5a72-11e5-8ce9-cf36df5d0cea.PNG)

**Comment by Carbon-Ghost** [comment]
Why aren't they using my textures ( aka Grag ones ? )

**Comment by modmuss50** [comment]
I dont know, I will dig them up and add them
