### ISSUE TITLE
Generator Bugs

### ISSUE THREAD

**Issue by VermillionX** [TechReborn/TechReborn#1430]
**Visual Bugs:**
When putting fuel into any of the TechReborn generators the GUI loses its shit. Random-colored bars appear on the right side of the screen; Random GUI corners appear below the progress bar and the progress bar % value ... well, exists. And will keep counting up as long as it's being fuelled.
![2018-02-04_15 00 30](https://user-images.githubusercontent.com/10645298/35773689-fdf5d9cc-09bd-11e8-8dbe-2beaeaf0a004.png)

**CraftTweaker Support Problems:**
Adding new fuels to some of the generators, in this case the Gas Turbine gives completely ridiculous power outputs.
I'm trying to add Thermal Foundation Naphtha to the Gas turbine at 1,250,000 FE per bucket (the same as output in a dynamo). The amount for this should be 312.5 which is ridiculously using EU as the energy value (WHY?!?! Everything in TR has input and output values in FE!), which factoring in the x4 conversion of EU into FE/RF should put it at 1.25m FE: It doesn't.
Anything over 300 outputs 3m FE per bucket, while putting 299 outputs exactly 2m RF per bucket and anything under 290 or so gives exactly 1m FE. It's just picking random values.

**Comment by drcrazy** [comment]
@VermillionX  Can you share you CT script for fluid generator, please?

**Comment by VermillionX** [comment]
```
mods.techreborn.fluidGen.addSemiFluid(<fluid:creosote>, 20);
mods.techreborn.fluidGen.addSemiFluid(<fluid:biomass>, 6.25);
mods.techreborn.fluidGen.addSemiFluid(<liquid:fluidchlorite>, 45);
mods.techreborn.fluidGen.addGasFluid(<liquid:ic2biogas>, 16.25);
mods.techreborn.fluidGen.addGasFluid(<liquid:ic2oxygen>, 12.5);
mods.techreborn.fluidGen.addGasFluid(<liquid:ic2hydrogen>, 15);
mods.techreborn.fluidGen.addGasFluid(<liquid:refined_oil>, 265);
mods.techreborn.fluidGen.addDieselFluid(<liquid:refined_fuel>, 299);
mods.techreborn.fluidGen.addDieselFluid(<liquid:biodiesel>, 150);
mods.techreborn.fluidGen.addDieselFluid(<liquid:bio.ethanol>, 150);
```
