### ISSUE TITLE
crash on oak log pick up 1.12

### ISSUE THREAD

**Issue by TheNimbleNinja** [TechReborn/TechReborn#1432]
when i break a tree log and pick it up my game crashes.

[crash-2018-02-04_18.06.24-server.txt](https://github.com/TechReborn/TechReborn/files/1693478/crash-2018-02-04_18.06.24-server.txt)
once i removed ur mod it stoped crashing from this.

**Comment by modmuss50** [comment]
Looks like the crash is happening with: https://minecraft.curseforge.com/projects/from-the-ground-up
