### ISSUE TITLE
Error robot opencomputers when using techreborn

### ISSUE THREAD

**Issue by tuckypetr** [TechReborn/TechReborn#1436]
The robot does not accept any degraded tree blocks in tree harvesting. He throws them into the world and does not save the inventory. With the same program, but the extracted blocks of stone receive, it will be stored in the inventory. Uses tools from Industrial Craft 2. Tested without the tool, but with the same result. 
forge-1.12.2-14.23.1.2555, MC 1.12.2, OpenComputers-MC1.12.1-1.7.1.43, RebornCore-1.12.2-3.5.0.162-universal, TechReborn-1.12.2-2.9.1.354-universal, 

https://youtu.be/sxLpNhfZ7R0
https://youtu.be/ANEep8jU434
https://youtu.be/F_EGR3mHYaI

**Comment by modmuss50** [comment]
Interesting, I’ll have to take a look at how OC detects wood.

**Comment by modmuss50** [comment]
Took a bit of digging to find the issue, but it now works as expected.

**Comment by tuckypetr** [comment]
Thanks
