### ISSUE TITLE
Export energy from Fusion Control Computer?

### ISSUE THREAD

**Issue by Bobo3012** [TechReborn/TechReborn#1443]
Hey, i tried now all possible ways I know but nothing will work...

I've got the following problem:
I play the Modern Skyblock 2 Modpack and using there the Fusion Control Computer. I read in all wikis that it can be a decent energy producer for mid- and late-game. But I have no idea how i export the energy to a capacitor or something like that.
The computer has its 400 MRF and when it starts he loose the needed start energy and fill itself until the 400 MRF. Everything above gets lost instead of getting exported. Is there anyway to get this energy? 

Thanks for every help and advice i will get :D

MC version 1.12.2
TechReborn version 1.12.2-2.10.4.394

**Comment by drcrazy** [comment]
Fusion reactor provides energy from top and bottom sides. And accepts energy from other sides. So you have to connect it with two cables, one to give energy to reactor and second cable to drain energy from reactor.

@Bobo3012 Did you have a chance to connect two cables to reactor?

**Comment by Bobo3012** [comment]
Hey, well that was easier than i thought xD but i hadnt even the idea that this could be the problem. well my plan was to build a tower of this structures, so until now there was top and botton side blocked. i guess i have to rebuild it with 1 free block between the computers, so i can place enery output there. 

Thanks alot for the fast and helpful answer :)
