### ISSUE TITLE
Some energy issues and ic2 e-net problems

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1444]
- Some values seem to be similar to those from IC2 exp whereas they should be the same as those in IC2 before 1.6.
Copper cables transfer 512RF/128EU instead of 128RF/32EU
Gold cables transfer 1536RF/384EU instead of 512RF/128EU
Glass Fibre cables transfer 32768RF/8192EU instead of 2048RF/512EU
HV Cables transfer 6144RF/1536EU instead of 8192RF/2048EU

- Low tier machines and storage units explode whereas the others don't when they get too much power. It would be cool if they all exploded or if none exploded.
For example battery boxes, grinders and alloy smelters explode whereas MFEs, Blast Furnaces and  Charge-O-Mats don't.

**Comment by drcrazy** [comment]
1. wont fix. TR based on IC2 pre-exp, but it doesn't mean that we should have it absolutely same to the point

2. Not reproduced. Blast furnace just exploded on screen below
![image](https://user-images.githubusercontent.com/1382352/37004552-d8ae6644-20e1-11e8-80d3-63658eb31a37.png)

I suspect explosion occurs when you connect +2 tiers power source to TR machine,
