### ISSUE TITLE
Machine animations continue to move even when machine is idle.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1446]
When you use a techreborn machine it starts showing a working animation on the front when its done, it keeps on going, even through reboots.

**Comment by modmuss50** [comment]
Is this all of the machines, or a specific one? Do you have any upgrades?

**Comment by ProsperCraft** [comment]
No upgrades, I have seen it in three machines, have not tried more.

**Comment by kristofersokk** [comment]
For me too, grinder, compressor and alloy smelter seem to work continuously (red color, animations). But electric furnace does not. (All 4 have overclocker upgrades).
Modern Skyblock 2 pack
