### ISSUE TITLE
[Suggestion] - Fission Reactors

### ISSUE THREAD

**Issue by Dannez** [TechReborn/TechReborn#1447]
It's cool and all that Tech Reborn has fission reactors, but...

CAN YOU DO THIS?!! https://i.redd.it/y50piklzq3801.gif

Oops, I meant can we have fission reactors? It would be neat, there's already fusion power, fission power would be nice. I'm thinking a system similar to IC2, but also with heavier fission materials like Nuclearcraft, and it would play a nice part in power progression.

Thankyou for reading. ;)

**Comment by modmuss50** [comment]
possibly, but dont expect it soon or anything.

**Comment by modmuss50** [comment]
This isnt going to happen any time soon due to a few reasons. We have been talking about it for a while, so it may happen at somepoint.

Thanks for your suggestion.
