### ISSUE TITLE
Breaking Machines only dropping machine frame

### ISSUE THREAD

**Issue by sweetsosweet** [TechReborn/TechReborn#1448]
First time using your mod, but when I break machines they are only dropping a machine frame back. I broke a grinder, an electric furnace and a compressor to move them, but the only item I got back was a machine frame.

I'm running forge-14.23.2.2623, RebornCore-1.12.2-3.6.8.214-universal, TechReborn-1.12.2-2.12.3.477-universal

Here's my modlist:

> [1.12][forge2413]mod_PickupWidelySMP_v1.2.4.zip
> [1.12][forge2413]mod_StorageBox_v3.1.9.zip
> AdChimneys-1.12.1-3.2.1.2-build.0079.jar
> AdditionalEnderBlocks-2.0-1.12.2.jar
> aether_legacy-1.12.2-v2.0.jar
> AmbientSounds_v2.2.3_mc1.12.2.jar
> antiqueatlas-1.12.2-4.4.6.jar
> AppleCore-mc1.12.2-3.1.1.jar
> AppleSkin-mc1.12-1.0.9.jar
> armorsoundtweak-2.0.3.jar
> Aroma1997Core-1.12.2-2.0.0.0.b144.jar
> AutoRegLib-1.3-15.jar
> backpacks 1.12.2 - 3.4.3.jar
> Bamboozled-1.12-1.0.10.jar
> barkbooks-1.12.2-1.2.jar
> BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
> BetterPlacement-1.0.0-1.jar
> BiblioCraft[v2.4.3][MC1.12.0].jar
> BiomesOPlenty-1.12.2-7.0.1.2322-universal.jar
> blockcraftery-0.1.3.jar
> Blur-1.0.4-14.jar
> bonsaitrees-1.0.3-b67.jar
> Bookshelf-1.12.2-2.3.528.jar
> Born In A Barn V1.8-1.12-1.0.jar
> BowInfinityFix-1.11.x-1.12.x-rv5.jar
> Bullseye-1.12-3.0.3.jar
> CarryOn MC1.12.2 v1.7.2.jar
> Cavern_1.12.2-v2.1.1.jar
> cedendcake-12.2-0.1.jar
> Chameleon-1.12-4.1.3.jar
> Charset-Lib-0.5.0.196.jar
> Charset-Tablet-0.5.0.194.jar
> chickens-6.0.3.jar
> Chisel-MC1.12.2-0.2.0.31.jar
> chiselsandbits-14.14.jar
> clarity-1.1.jar
> ClearSpam-0.4.jar
> cloak-0.0.4.jar
> coloredtooltips-1.0.0.jar
> comforts-1.12.2-1.1.0.2.jar
> CompactStorage-3.0-10.jar
> CraftingCraft_1.12-6.1.3.jar
> CraftingTweaks_1.12.1-8.1.6.jar
> CreativeCore_v1.9.18_mc1.12.2.jar
> CTM-MC1.12-0.2.3.12.jar
> ctwatercan-1.12.2-0.5.6.jar
> CubicVillager-0.30.0.jar
> CustomBackgrounds-MC1.12-1.1.1.jar
> dailies-1.12.2-6.jar
> dazzle-1.0.jar
> DeadWood-1.2.jar
> DeepSeaExpansion-1.12.2-Preview-A6.jar
> Ding-1.12.1-1.0.1.jar
> ElevatorMod-1.12.2-1.3.5.jar
> elulib-0.1.12.jar
> EnderCompass-1.12-1.2.6.1.jar
> Erebus-1.0.21.jar
> Exotic+Birds+1.12.2-1.4.0.jar
> extraalchemy-0.3.8.1-release.jar
> FamiliarFauna-1.12.2-1.0.0.jar
> FasterLadderClimbing-1.12-0.1-146.jar
> Faucets and Filters-1.0.2.jar
> fencejumper-1.12-1.0.3.jar
> FenceOverhaul-1.3.4.jar
> Ferdinand's Flowers-1.10.0-1.12.jar
> flatcoloredblocks-mc1.12-6.6.jar
> FoamFix-1.12.2-0.9.2-Anarchy.jar
> ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar
> Forgelin-1.6.0.jar
> FTBLib-4.2.5.jar
> furnaceonastick-1.0.jar
> furnus-1.12.2-2.1.5.jar
> Futurepack-1.12.2-26.3.138.jar
> GiacomosFishingNet-1.12.2-1.6.1.jar
> gigaherz.commons-1.12.1-0.6.4.jar
> globalxp-1.12.x-v1.4.jar
> gravestone-1.10.1.jar
> harvestables-1.2.1.jar
> Hwyla-1.8.23-B38_1.12.jar
> iChunUtil-1.12.2-7.1.4.jar
> imaginary-1.0.3-1.12.jar
> InGameInfoXML-1.12.2-2.8.2.94-universal.jar
> Inspirations-1.12.2-0.1.2.jar
> InventoryTweaks-1.63.jar
> ItemPhysic Full 1.4.10 mc1.12.2.jar
> itemzoom_1.12.1-1.10.jar
> jei_1.12.2-4.8.5.159.jar
> JRFTL[1.12.2]-1.1.jar
> jukebox-1.2.jar
> KleeSlabs_1.12-5.3.2.jar
> landlust-1.12.2-0.3.6.jar
> librarianlib-1.12.2-4.7.jar
> limelib-1.12.2-1.7.9.jar
> LittleTiles_v1.5.0-pre72_mc1.12.2.jar
> LunatriusCore-1.12.2-1.2.0.42-universal.jar
> Mantle-1.12-1.3.1.21.jar
> MCMultiPart-2.4.1.jar
> mendingfix-1.0.1-1.12.2.2618.jar
> middletorch-6.0.1.jar
> miniheads-1.0.7a-1.12.jar
> miniportal-1.0.jar
> moarboats-1.12.2-1.2.1.jar
> MobDismemberment-1.12.2-7.0.0.jar
> mod_autofish_forge-1.12-1.7.jar
> morechickens-1.12.2-3.1.0.jar
> moreoverlays-1.13-mc1.12.1.jar
> MouseTweaks-2.8-mc1.12.1.jar
> mylittlemobgrinder-1.12.2-1.0.2.jar
> mysticalworld-0.1.1.jar
> naturalbabyanimals-1.1.3-mc1.12.x.jar
> NaturesCompass-1.12.2-1.5.1.jar
> netherchest-0.2.2.jar
> NetherEx-1.12-2.1.14.15.jar
> nethergoldore-1.1.1-mc1.12.x.jar
> NHCore-1.12-4.0.3.jar
> nibbler-1.12.2-0.4.1.jar
> NoMobSpawningOnTrees-1.2.1-mc1.12.jar
> NoMoreRecipeConflict-0.10(1.12.2).jar
> NotEnoughIDs-1.5.4.2.jar
> OpenGlider-1.12.1-1.1.0.jar
> OptiFine_1.12.2_HD_U_C8.jar
> OreExcavation-1.4.113.jar
> Paint All the Things-1.1.jar
> paintingselgui-PSG Revamed-1.12.2-1.1.0.1.jar
> persistentcake-1.12-2.0.0.jar
> placeableitems-3.2.jar
> Placebo-1.12.2-1.2.0.jar
> Plants-1.12.2-2.6.2.jar
> Quark-r1.4-122.jar
> QuickLeafDecay-MC1.12.1-1.2.4.jar
> RebornCore-1.12.2-3.6.8.214-universal.jar
> redstonepaste-mc1.12-1.7.5.jar
> refinedstorage-1.5.31.jar
> roost-1.12-1.2.0.jar
> rustic-0.4.10.jar
> SaltyMod_1.12.1_e_.jar
> shulkerbox-1.3.0.jar
> simplebedding-1.1.1.jar
> sit-1.12.x-v1.1.jar
> SmoothFont-1.12.2-1.10.jar
> SmoothWater-0.1.3.jar
> solcarrot-1.12.1-1.2.0.jar
> SoundFilters-0.10_for_1.12.jar
> stairdoors-1.0.jar
> StepupFix-1.12.2-1.0.0.4.b15.jar
> stg-1.12.2-1.2.3.jar
> StorageDrawers-1.12.2-5.3.5.jar
> superblocks-mc1.12-4.1.jar
> supersoundmuffler-1.12.1-1.0.2.9.jar
> TechReborn-1.12.2-2.12.3.477-universal.jar
> teleportingxp-1.1.1.1.jar
> TheBetweenlands-3.3.0-core.jar
> TheBetweenlands-3.3.0-universal.jar
> ToolBelt-1.12.0-1.7.1.jar
> toolbox-0.2.3.jar
> TorchLever-1.0.jar
> torchmaster_1.12.2-1.6.1.53.jar
> twilightforest-1.12.2-3.6.345-universal.jar
> underphangables-1.12.0-1.0.0.jar
> UnlimitedChiselWorks-0.1.10.jar
> Uppers-0.0.4.jar
> vanillafoodpantry-mc1.12.1-4.1.0.jar
> Wawla-1.12.2-2.5.251.jar
> Xaeros_Minimap_1.14.9_Forge_1.12.jar
> XaerosWorldMap_1.2.4_Forge_1.12.jar
> Xtones-1.12-1.0.8-11.jar
> YABBA-1.0.11.jar

**Comment by modmuss50** [comment]
You need to use a wrench to break the machines. Shift right click with it.

**Comment by sweetsosweet** [comment]
Why would that not be stated anywhere in the game? First I crafted the manual which led to an internet link, so I then downloaded the charset tablet, specifically so I could figure out how to use the mod, and nowhere in the getting started stages does it mention or suggest crafting a wrench or how to use it. I'll cheat back in the items, but maybe make your mod more transparent.

**Comment by modmuss50** [comment]
Ok, that is a fair comment. That can easily be added to the wiki. Thanks for checking out the mod.
