### ISSUE TITLE
Minetweaker support

### ISSUE THREAD

**Issue by bookerthegeek** [TechReborn/TechReborn#1449]
## Heyo ##
According to [This Page](https://wiki.techreborn.ovh/doku.php?id=development:mt), we can generate the Minetweaker support information for all your mods that are installed by enabling ```MT Doc generation``` in RebornCores' config file. We have determined this is a lie. :wink: That config option is not in any config generated by any of the TechReborn mods. 

### Versions ###
Minecraft 1.12.2
Forge 14.23.2.2618
RebornCore 3.6.8.214
StevesCarts 2.4.17.88
TechReborn 2.12.3.477

#### An additional request ####
An easy centralized location for CraftTweaker documentation is at [Read The Docs](https://crafttweaker.readthedocs.io/en/latest/#), and can be edited on GitHub [Here](https://github.com/CraftTweaker/CraftTweaker-Documentation). This makes it easier for people to find it as it is centralized. Not required in the slightest, but nice and easy to use.

**Comment by modmuss50** [comment]
I recently changed the way the docs are auto generated. They are now generated a build time, and not at runtime. You can always find them on the jenkins. I should really look into uploading them to a more accessible place. There is a link bellow.

https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.12/490/artifact/build/libs/TechReborn-1.12.2-2.12.3.490-universal-crafttweaker.txt
