### ISSUE TITLE
Removing UUMatter recipes from craftingtable with crafttweaker isn't working.

### ISSUE THREAD

**Issue by Guinaro** [TechReborn/TechReborn#1450]
I have tried to use the crafttweaker functionality recipes.removeShaped(<output>, input[][]) on UUMatter recipes. But crafttweaker fails to remove those recipes.
See https://github.com/CraftTweaker/CraftTweaker/issues/476
I'm guessing Tech Reborn registers this recipe in a different way or later, so that crafttweaker doesn't find it, or simply cannot remove it.

Guinaro

**Comment by modmuss50** [comment]
They are registered in the same way as all off our other crafting recipes. https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/init/recipes/CraftingTableRecipes.java#L244

**Comment by Guinaro** [comment]
Short update.
I found a way to remove them based on name. 
recipes.removeByRecipeName("techreborn:...);
Still it seems stranges that when providing the exact output as given by /ct recipes it doesn't work.
So currently low priority if fixable. Workaround gives intended result: removal of 1 recipe, still wondering why shaped doesn't work.

**Comment by modmuss50** [comment]
That commit there should fix it. 

Explanation: 
The Ingredient.fromItem method creates a stack with the ore dict wildcard meta, so crafttweaker wont be detecting it. This should fix it.
