### ISSUE TITLE
Cannot insert scrap into Matter Fabricator

### ISSUE THREAD

**Issue by TvL2386** [TechReborn/TechReborn#1451]
Hi devs!

I'm either doing something wrong or discovered a bug.
I'm trying to insert scrap into a Matter Fabricator using Mekanism pipes, Itemducts or XNet, but none of them work. Note: I use XNet just fine for automating the Implosion Compressor, Industrial Blast Furnace and a bunch more of your (multi)blocks.

Manually inserting the scrap works fine, so the Matter Fabricator should just accept it. Doesn't matter which side I try to insert it in.

I am playing ATM3 (MC 1.12.2) with:
RebornCore-1.12.2-3.6.2.187-universal.jar
TechReborn-1.12.2-2.11.1.420-universal.jar
forge-1.12.2-14.23.1.2587-universal.jar

I've created my own tiny pack with the above versions, containing just:
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
RebornCore-1.12.2-3.6.2.187-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
TechReborn-1.12.2-2.11.1.420-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar

With latest versions it still occurs:
RebornCore-1.12.2-3.6.9.216-universal.jar
TechReborn-1.12.2-2.12.4.496-universal.jar

![the_setup](https://user-images.githubusercontent.com/459167/37061193-f36a9244-2192-11e8-85d3-cd37eb5736db.png)
![chest_contents](https://user-images.githubusercontent.com/459167/37061192-f3510d88-2192-11e8-8e18-d53c8de101fc.png)

**Comment by modmuss50** [comment]
Have you used the config slots options in the MatterFabricator's gui?

You will need to click on the slots and select an input side. I do plan on adding default slot configuration values in the future to make simple machines "work out of the box"

Let me know if you still have issues.

<img width="867" alt="screen shot 2018-03-06 at 22 13 23" src="https://user-images.githubusercontent.com/4324090/37061571-cfa9564e-218b-11e8-8882-d475b73e3eb4.png">

**Comment by TvL2386** [comment]
oh my god.... *facepalms*
