### ISSUE TITLE
Feature request - chunkloader behavior - online player only.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1452]
Would you please consider adding the config option to 

1. Only load chunks if player is online.
- For performance on large servers.

2. Load chunks on server start?
- This would keep chunks from loading when the server starts which help avoid crashloops.

3. How many chunks to load max?

**Comment by modmuss50** [comment]
1. yeah that should be possible
2. thats a good idea, could wait 30 seconds or so before loading the chunks
3. sure

I dont actually think the chunk loader works right now, so this stuff here will be good to keep in mind when I get around to adding/fixing it.

**Comment by ProsperCraft** [comment]
Sorry I should have been more clear - 

2. Load the chunks when first visited by the player. - can be configurable.

**Comment by modmuss50** [comment]
Ok, I started looking into this, and its totally possible to do. However I feel like there are allready mods that do it better. FTB Lib has the map that you click on to select chunks for teams. That has configs to do all of the suggested things above. ChickenChunks also has a lot of theses options. 

Our chunk loader may get done one day, but I dont have the time or energy to spend a few days of dev working on this. Pull requests will be accepted if someone else is interested. 

Thanks a lot for your suggestion.
