### ISSUE TITLE
[Server]Fatal error with changing the input in some machines

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1453]
hello, we have a little problem on our server. namely: every time someone sets the auto input, some players fly from the server with a fatal error. the server itself does not crash and the client does not. only this fatal error comes again and again.

https://screen.pudding.tk/4ic1k532m4.png

Mod: TechReborn-1.12.2-2.12.3.477-universal
Core: RebornCore-1.12.2-3.6.8.214-universal
ModPack: Modern Skyblock 3 - 3.1.5.3
Minecraft: 1.12.2

**Comment by modmuss50** [comment]
Is there anything in the client or server log at the time that this happens?

**Comment by ghost** [comment]
here is the log: https://paste.myftb.de/umelavuwup
