### ISSUE TITLE
Crafttweaker add a way to disable ore dict checking

### ISSUE THREAD

**Issue by CelestialPhoenix** [TechReborn/TechReborn#1455]
Using CraftTweaker to add new processing recipes;
`mods.techreborn.compressor.addRecipe(<minecraft:iron_block>, <ore:ingotIron>*9, 200, 5);`

Script does not throw any errors with /ct syntax
Compressor takes 1 iron ingot and produces 1 iron block
(iron plate recipe removed, otherwise it produces iron plates)

Multiple item output is perfectly fine
`mods.techreborn.compressor.addRecipe(<minecraft:iron_block>*9, <ore:ingotIron>*9, 200, 5);`
Produces 9 iron blocks from 1 ingot.

Reborn Core 3.6.9.216
Tech Reborn 2.12.4.496
Forge 14.23.1.2607

**Comment by modmuss50** [comment]
Ore Dictionary entries cannot have a size. The following works:

`mods.techreborn.compressor.addRecipe(<minecraft:iron_block>, <minecraft:iron_ingot>*9, 200, 5);`

**Comment by CelestialPhoenix** [comment]
I see- it automatically adds in the ore-dictionary function. Thats pretty clever. I like it.

However it does cause a slighty different issue;
`mods.techreborn.compressor.addRecipe(<minecraft:lapis_block>, <minecraft:dye:4>*9, 200, 5);`
allows any `ore:dye`, `ore:dyeBlue`, and `ore:gemLapis` to be used in the recipe. 
(causes things like _Botania's floral dyes_ or _Minecraft's bonemeal_ to work in the recipe)

Removing the additional ore tags from lapis would work, but would likely screw up the other mods relying on those tags.

Is there a way I can just use the ore:gemLapis tag or target specifically <minecraft:dye:4>?

Thanks for the help

**Comment by modmuss50** [comment]
ah ok, what I need to do is add some methods to allow you to disable the auto ore dict checking for recipes. I will most likely do this next week.

**Comment by modmuss50** [comment]
Ok, OreDict checking can be disabled like so:

`mods.techreborn.alloySmelter.addRecipe(<minecraft:gold_ingot>, <minecraft:iron_ingot>, <minecraft:diamond>, 20, 100).setUseOreDict(false);`

Note the `.setUseOreDict(false);` this should work on all recipes that use the RecipeCrafter.
