### ISSUE TITLE
Can't remove recipes from TechReborn with CraftTweaker

### ISSUE THREAD

**Issue by MinerTomotomo** [TechReborn/TechReborn#1456]
(I'm not good at English, sorry)
I want to remove recipes with CraftTweaker but, recipes are available.

↓Scripts
`recipes.remove(<techreborn:dragon_egg_syphon>);`
`recipes.remove(<techreborn:solar_panel:*>);`

Mod Version
・RebornCore-1.12.2-3.6.10.218-universal
・TechReborn-1.12.2-2.12.5.501-universal
・CraftTweaker2-1.12-4.1.6

**Comment by modmuss50** [comment]
I bet this is same as the last bug. Ill see if I can find a way to fix it for all recipes.

**Comment by Guinaro** [comment]
For now I recommend to try  to remove based on name in crafttweaker, for me that did the trick.

**Comment by modmuss50** [comment]
Both are working as expected in my dev environment. This will need some more looking at.

**Comment by MinerTomotomo** [comment]
Thank you for your replies and verifying.
I verified about this bug in a state of only 3 mods are loaded.(Rebon Core, Tech Reborn, CraftTweaker)
As a result of Verification, I succeeded in removing from TechReborn recipes.
When I realized this bug, I was using many other mods...

Mod List
https://writening.net/page?hNgMj5
I'm sorry that my English isn't good :_(

**Comment by modmuss50** [comment]
I dont think there is a lot more I can do to try and fix this.
