### ISSUE TITLE
Plasma generator power reserve issue.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1460]
https://gyazo.com/799f3b480e69eadedfea696153c4c2ff

The plasma generator power stores on the right reset every time you open the interface.

**Comment by modmuss50** [comment]
This was on a server with sponge forge.

**Comment by modmuss50** [comment]
This needs confirming on a forge + TR + RC server, and then ill look into it more. But there is no reason this should be broken.

**Comment by modmuss50** [comment]
Closing due to no response, open another issue if the issue can be reproduced.
