### ISSUE TITLE
Advanced drill 3x3 bypasses the hardness of the block next to the soft block.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1463]
Example- if you have obsidian and mine it with the drill directly it takes a while, but if you hit the cobble next to it its instant.

**Comment by PhoenixSmith** [comment]
That is usually a problem with all 3x3 mining devices. Only in 1.7.10+ did Tico start factoring the other blocks.

**Comment by drcrazy** [comment]
Setup to brake:
![image](https://user-images.githubusercontent.com/1382352/37804266-8ce447b8-2e44-11e8-8015-b705d91e4c88.png)

State after drilling:
![image](https://user-images.githubusercontent.com/1382352/37804277-95c749a2-2e44-11e8-8e7d-954a0483ad08.png)


Side effect - if you will aim at obsidian Advanced Drill will break log and planks. It is fine, you've paid the price by spending time on hard block.

**Comment by ProsperCraft** [comment]
Thank you.
