### ISSUE TITLE
[1.12.2] Iron/Electric Alloy Smelter Input Consumption Bug

### ISSUE THREAD

**Issue by KAfable** [TechReborn/TechReborn#1464]
Given the following CT script: 

```
var ingotRefinedIron = <techreborn:ingot:19>;
mods.techreborn.alloySmelter.addRecipe(ingotRefinedIron, <ore:ingotIron>, <ore:ingotIron>, 200, 32);
```

Whenever I make refined iron in the alloy smelter, it ends up using two of the inputs from the first slot instead of using one ingredient from each slot, as a result it leads to some unintuitive ingredient usage as shown below: 
![image](https://user-images.githubusercontent.com/26587049/37843762-3a0a4904-2e9c-11e8-9a22-9ea2f375dd7d.png)

**Comment by modmuss50** [comment]
This is possible to fix, it will require a bit of reworking how the items are used in all of the machines, so I will need to ensure that I dont break anything to badly.

**Comment by drcrazy** [comment]
Alloy smelter aimed to make alloys from two different metals. If you need to smelt same two ingots into one, please, use furnace

**Comment by modmuss50** [comment]
Yeah I’d agree with that. The alloy furnace is designed for 2 different things into one. It’s not worth the time required to fix it.
