### ISSUE TITLE
[Suggestion] option to tweak machines's energy consuption per tick

### ISSUE THREAD

**Issue by Yzelast** [TechReborn/TechReborn#1469]
Hi guys, i'm having some problems to change energy usage of machines. When trying to balance my pack i found out that i can't change the energy per tick usage of any of the machines, i can only change the internal buffer and input rate.I wanna ask if would be to hard to add this option.

Furthermore, i have two more issues:
   1. I noticed that now we have a generators.cfg inside the techreborn folder, but only the solar panels are listed there.The other generators shouldn't be there too?
 
  2. Why some of the basic machines are not listed inside machines.cfg? I did not find the config of the grinder nor the eletric furnace by example...

Using forge 1.12.2-14.23.2.2631 and techreborn 1.12.2-2.12.8.521

**Comment by modmuss50** [comment]
The power per tick is done for each recipe, so it is not possible to add a config for it. I can take a look at the missing configs as well.

**Comment by drcrazy** [comment]
You have two options to tweak TR:
1) Use configs provided
2) Use crafttweaker

Energy usage for crafting done via recipes thus via crafttweaker. There is no point to replicated CT functionality to tweak recipes. 

As for missing #2  - yes, not all machines are yet configurable. This will could be worked out.
