### ISSUE TITLE
[Question]: How can I open a line of communication with you?

### ISSUE THREAD

**Issue by Lanse505** [TechReborn/TechReborn#147]
Hello!

Just as the titel states, I'd like to get in touch with you about featuring Tech Reborn in a mod pack i'm making and I'd like to have an open-ish line of communication either through IRC/Teamspeak/Slack/etc so I can talking to you about Tech Reborn Related stuff.

I'm reachable either in #rr on Esper.irc (my name is Lanse), 
Or on ts.minecraftia.net:1337 Alt. ts.resonant-rise.com Alt. 198.245.50.74

Best Regards
Lanse

**Comment by gigabit101** [comment]
#TechReborn on esper or themattabase.com ts TechReborn room

**Comment by Lanse505** [comment]
Thank you ^^

**Comment by modmuss50** [comment]
We should put contact info in the readme
