### ISSUE TITLE
Red/Yellow Garnet Plate is missing?

### ISSUE THREAD

**Issue by Syndesi** [TechReborn/TechReborn#1471]
Hi,

I'm currently developing a modpack and while adding some recipes, I found out that Red/Yellow Garnet Plates do exist, but don't have any recipes at all while Ruby, Sapphire and Peridot do.

**Comment by Syndesi** [comment]
This might also close #872, but kenijey's issue is for the 1.11.2 version.

**Comment by Syndesi** [comment]
Interestingly the mentioned refined iron plate and obsidian plate isn't craftable too.

**Comment by drcrazy** [comment]
I will look into it
