### ISSUE TITLE
LESU Storage losing stored energy

### ISSUE THREAD

**Issue by Leftorius** [TechReborn/TechReborn#1476]
Good morning,

I just created my first LESU and found out, if I restart/relog into minecraft all my energy is gone except the internal storage of the lesu controller. First I thought it was an chunk bug, but I build it completly in one chunk!

so could this be an desync error? or something else?

TechReborn-1.12.2-2.13.2.561-universal
RebornCore-1.12.2-3.7.2.245-universal
Forge: 14.23.2.2654

I'm using ATM3 but I modified it a little.

**Comment by modmuss50** [comment]
Can Confirm
