### ISSUE TITLE
Sawmill and CraftTweaker

### ISSUE THREAD

**Issue by BaseCrusher** [TechReborn/TechReborn#1478]
Hello there,

I realized yesterday, that the industrial sawmill is copying the recipes from the crafting table recipes. Cause I changed all logs to output 2 planks and wanted the sawmill to output 6. More like Gregtech did at one time. So I used the remove all line for the sawmill recipes just to find out that all the recipes still where implemented. :/

I added some recipes aswell and they where buggy. I used a loop to add the log recipes to the sawmill and somehow the recipes got messed up and you could put diffrent logs for the same output plank, which shouldn't be possible. Since the recipe in the crafting table is working fine i dont think that it is a fault of my script.

Here an example script that should reproduce the problem (pls consider, that I'm using forestry, bop, binnies mods, ...):
https://pastebin.com/S93NMgnC

**Comment by modmuss50** [comment]
I have added a config to allow this to be changed, `config\teamreborn\techreborn\recipes.cfg`
