### ISSUE TITLE
Compatibility between Tech Reborn and IC2

### ISSUE THREAD

**Issue by BaseCrusher** [TechReborn/TechReborn#1479]
So there are still some compatibility issues with IC2. I don't know if they are wanted, just not implemented yet or never going to be implemented.

1: You can't charge Tech Reborn items in IC2 machines/energy storages like batbox or the MFE.

2: The cables of Tech Reborn don't connect to IC2 machines.

3: You can't charge Tech Reborn machines with IC2 batteries ...

The second isn't that harmfull, since you can jsut use the IC2 cables. But i think it would be nice to be able to charge Tech Reborn items in when using mainly IC2.

**Comment by modmuss50** [comment]
1. Not currently possible as our items don't work with ic2 power system. No plans to fix.
2. Our cables are FE only, I dont plan to change this.
3. You should be able, that might be a bug, needs looking into.

**Comment by modmuss50** [comment]
3. was an easy fix, the others are more complex + wont happen. Sorry.
