### ISSUE TITLE
Nickel

### ISSUE THREAD

**Issue by aleksRF** [TechReborn/TechReborn#148]
Add NickelOre please

**Comment by gigabit101** [comment]
why do we need Nickel ??

**Comment by Carbon-Ghost** [comment]
I guess for stainless steel if you guys readd it, though I am against it because I don't see any point readding it ;P

**Comment by gigabit101** [comment]
there is know need for Nickel in TechReborn as  it was not in gtech

**Comment by aleksRF** [comment]
for Invar for Thermal Generator

**Comment by gigabit101** [comment]
@aleksRF nickel is not a ore in are mod it is made with machines
