### ISSUE TITLE
Dupe bug - digital chests - Thermal expansion Wrench - sponge environment.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1481]
##version
TechReborn-1.12.2-2.13.2.561-universal

##Video
Wrench one get two.
https://www.dropbox.com/s/aj7fr3qyxtq5kn4/Minecraft%201.12.2%204_11_2018%203_01_50%20PM.mp4?dl=0

**Comment by owen-pi** [comment]
Hi, I'm the guy that found it/recorded it. 2 things, the TechReborn wrench does the same thing, and it also works with quantum chests. Thanks.

**Comment by ProsperCraft** [comment]
This is still happening, please re-open.
 ThermalExpansion-1.12.2-5.4.2.27-universal.jar

**Comment by Prospector** [comment]
Are you certain you're on the latest Tech Reborn and Reborn Core?

**Comment by ProsperCraft** [comment]
Yes

https://i.gyazo.com/782e24bbd38486a49e4b60d5db52d26f.png

https://i.gyazo.com/e4530e85bb76c2034ccb14678fba3dd2.png
