### ISSUE TITLE
Quantum tank does not accept item piping

### ISSUE THREAD

**Issue by Froggy800** [TechReborn/TechReborn#1484]
I was trying to automate the filling of empty cells and apparently the only way to do it is to use a quantum tank (both Ender IO and Mekanism tanks cannot fill/empty fluid cells - should I open a separate issue for this?).
The problem is that while the quantum tank allows both the piping of fluids and the filling of cells, it doesn't accept the piping of items, both in and out (there's no config button in the tank's interface,).
I also noticed that there are 4 invisible slots on the left of the GUI that highlight upon mouse over - I thought it was worth mentioning.
Tested on forge version 14.23.2.2611 and TechReborn 1.12.2-2.14.0.584 (latest as of today).

**Comment by modmuss50** [comment]
Fixed it:
![2018-04-14_00-14-57](https://user-images.githubusercontent.com/4324090/38761235-ebf27d98-3f78-11e8-8735-c2371ae85966.gif)

**Comment by modmuss50** [comment]
I might also look into why you cannot fill them with other mods.

**Comment by Froggy800** [comment]
That was fast. Thanks a ton!

**Comment by Froggy800** [comment]
I did some more mod interaction testing and I found out that the only tank (other than the Quantum Tank) that can empty the cells is the Black Hole Tank from Industrial Foregoing; the tank doesn't allow the insertion of empty liquid containers by default, so it can only be used to empty them, making it useless for my specific situation.
