### ISSUE TITLE
[1.12.2] IC2 Recipes don't work on the latest version

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1486]
I'm not sure whether it was changes in the newer TechReborn or IC2 versions, but, although I have IC2 recipes enabled, there are just normal recipes.

**Comment by modmuss50** [comment]
Can you explain some more? I don't really understand what you mean?

**Comment by TheLimePixel** [comment]
Although in the config, IC2 Recipes=true, no recipe has been disabled as if it's off.

**Comment by modmuss50** [comment]
I think the config you are after, is in recipes.cfg and is called `deduplicate` This removes the cross over between techreborn and ic2.

I think you are looking at the config in compat.cfg, that config should be true, unless you know you dont need it.

**Comment by TheLimePixel** [comment]
Oh... Sorry then.
