### ISSUE TITLE
Can't open any machines

### ISSUE THREAD

**Issue by Stephenator0316** [TechReborn/TechReborn#1487]
Just went through and updated my mod list, including TR and RC. Now I can't open any TR machines ;w;

Other mod machines and inventories are working fine though

https://www.youtube.com/watch?v=gzp3IPMa-LY

Another thing to note: Fission reactor is still running and producing power

**Comment by modmuss50** [comment]
Is anything in your logs?

**Comment by Stephenator0316** [comment]
Anything specifically?

**Comment by Stephenator0316** [comment]
I don't mean to be an asshole, I just don't know what to look for xD

**Comment by modmuss50** [comment]
When you right click on the machine does anything show up in the log file?

**Comment by Stephenator0316** [comment]
Which log file and where?

**Comment by Stephenator0316** [comment]
If you want the fml-client-latest.log here it is

pastebin.xyz/p?q=TjNVbWc

**Comment by Stephenator0316** [comment]
I'm sorry for being stupid ;w; I just want this issue fixed

**Comment by modmuss50** [comment]
I have no idea what could be causing this, they work fine in dev. You dont appear to have anything in the logs, can you check that you have fully updated both TechReborn and RebornCore?

**Comment by Stephenator0316** [comment]
You wanna hear a joke? Twitch's desktop app. That's the fucking joke.

I had gone through my mods and made sure they were all up to date (all 273 of them) and it decided to only update every other one. So I was not running the most up versions. 
Sorry for wasting your time, and I hope you have a good day!

**Comment by modmuss50** [comment]
No worries, gald you found the issue and got it sorted :)
