### ISSUE TITLE
[Suggestion] More configs for energy etc..

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1491]
It would be neat if we could customize a bit more the energy values for each machine and cables and tiers:
- It would be great to be able to choose how many EU/t each machine consumes
- How many EU/t each machine can input
- How many EU/t each cable can transfer
- How many EU/t each generator generates
- What is the tier of each machine, generator and cable
Thank you in advance! TechReborn is really getting better and better!

**Comment by drcrazy** [comment]
How many EU/t each machine can input - already done.
It would be great to be able to choose how many EU/t each machine consumes - done via recipes
How many EU/t each generator generates - done via recipes

Tier calculates automatically based on input or output rate. 

I could be wrong. As for me it looks like the only missing thing is ability to change transfer rate for cables. If not may I ask you to provide examples, please?

**Comment by Skillotic0703** [comment]
You're actually right. Can I ask for a config option to choose how many EU storage units store (batbox, mfe, mfsu, aesu, idsu) and what is their output rate?
