### ISSUE TITLE
New Fusion Reactor GUI issues

### ISSUE THREAD

**Issue by Froggy800** [TechReborn/TechReborn#1494]
I love the new reactor, it's a really nice idea for a resource sink; there are however some problems with the controller interface:
- the buttons used to change the size of the coils ring are only clickable while in side configuration mode (I don't know how to call it, it's the one that you access with the wrench button on the left)
- even then, you can only toggle between minimum and maximum size (6-50)
- the block preview button doesn't work, even in side config mode
Tested on Forge version 14.23.3.2655

**Comment by modmuss50** [comment]
1. Humm intresting
2. max is 50 min is 6
3. humm

Have you got the latest reborn core version? 3.8.0.264

**Comment by Froggy800** [comment]
Yup, I'm running TechReborn 2.15.0.602 and RebornCore 3.8.0.264. I tried running another instance with just those two mods +JEI but all the problems persist, so it doesn't appear to be a mod interaction issue; I also tried updating to the latest version of Forge (14.23.3.2670), but nothing changed.
Regarding the point 2 from before: what I meant is that I can only choose 6 or 50, nothing in-between; I also noticed that when I change the ring size the in-game button click sound is much louder than normal,

**Comment by modmuss50** [comment]
Can confirm, not sure what gone wrong here, as it was working fine.
