### ISSUE TITLE
Sawmill and VacFreeze multiblocks reversed?

### ISSUE THREAD

**Issue by CelestialPhoenix** [TechReborn/TechReborn#1499]
The sawmill and vacfreeze have each other's multiblock (based off my memory of Gtech in 1.4.7)
-sawmill was a 3x3x1 of casing with the sawmill block in centred top.
-vacfreeze was a 3x3x3 of casing with the vacfreeze block centred on side
Currently vacfreeze is 3x3x1 and the sawmill is the 3x3x3.
[https://imgur.com/a/TFRjHrI](https://imgur.com/a/TFRjHrI)

[Though I don't mind the chunkier looking sawmill, however the vacfreeze looks a little wierd]

Reborn Core 3.7.5.259
Tech Reborn 2.14.0.584
Forge 14.23.2.2611

**Comment by modmuss50** [comment]
To be honest I dont feel like it matters that much. TR isnt supposed to be a 1-1 clone of GT. It could be changed, but it would break peoples pre-existing worlds for no gain.

Thanks for opening the issue, but it wont be fixed.
