### ISSUE TITLE
Crash without Tinkers' construct

### ISSUE THREAD

**Issue by Stormageddon223** [TechReborn/TechReborn#150]
TechReborn crashes without Tinkers' but if I load in only ic2 TR and not TC it works but in another modpack without crashes and with it doesn't, here's the pastebin: http://pastebin.com/Az2FGqHP

**Comment by modmuss50** [comment]
One of the mods you are using is doing something weird.

**Comment by modmuss50** [comment]
Try with this build, http://modmuss50.me:8080/job/TechReborn/857/artifact/build/libs/TechReborn-0.4.3.857-universal.jar

**Comment by Stormageddon223** [comment]
Thanks,now it works with the new build,sorry for the late answer but i
didn't had my computer for a month so I couldn't test it out

2015-09-19 20:21 GMT+02:00, Modmuss50 <notifications@github.com>:
