### ISSUE TITLE
[1.12.2] Industrial grinder filter input doesn't keep products from entering.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1503]
https://gyazo.com/9421fbdbb25774c232e9f6b4256a0e53

**Comment by ProsperCraft** [comment]
Other blocks have the same issue.

**Comment by modmuss50** [comment]
I think ive fixed it on all the machines that have the issue, let me know if other machines are still broken. Thanks.

**Comment by Ristovski** [comment]
@modmuss50 This does not appear fixed in v5.2.0, Iron Furnace for example still pulls incompatible items.
