### ISSUE TITLE
Cables not transmitting power and not visually connecting to generators , machines , energy stores.

### ISSUE THREAD

**Issue by rioninnimo** [TechReborn/TechReborn#1505]
It cant be that everyone else have this issue and uses IC2 cables ? Right ? What is happening , can someone test ?
  
 Details:
- Debugger tool shows that cable adjacent to generator gains some FE (forge energy? ) and generator internal store drains its energy. After certain amount of FE in cable reached generator stops outputting it .
- Machines and energy stores never accept energy from such cable , all sides of MFE and batbox tried.
- Generators adjacent to machines and energy storages(battery box , MFE) properly transmit energy to adjacent machines ( calling it EU in GUI ).
- If Industrial Craft Experimental installed IEExp wires work properly and transfer EU. But TechReborn cables still not work.
- Mobs and player standing on uninsulated copper wire running from generator recieve elecrodamage. Even though wire visually not connected to generator.
 Mods:
TechReborn-1.12.2-2.15.4.624-universal.jar
RebornCore-1.12.2-3.8.0.264-universal.jar
1.12.2-forge1.12.2-14.23.2.2611

 Yes , just that , no Optifine , not even JEI.

 What is happening , am i alone ? People cant possibly play like that.

**Comment by drcrazy** [comment]
Not reproducible. 

![image](https://user-images.githubusercontent.com/1382352/39523066-0ef8722c-4e1d-11e8-8840-fb6dcff80ac7.png)
