### ISSUE TITLE
Empty cells will not pull lava from Thermal Expansion portal tanks, 

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1506]
TechReborn-1.12.2-2.15.4.624-universal

Empty cells will not pull lava from Thermal Expansion portal tanks, 

Universal fluid cells from Ic2 work on the TE tank.

**Comment by modmuss50** [comment]
Isn't this a duplicate of #1504 as it was fixed in build 628 (not released yet)
