### ISSUE TITLE
Industrial Centrifuge will not spin lava anymore after last update.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#1507]
After updating to TechReborn-1.12.2-2.15.4.624-universal the industrial Centrifuge will not spin lava cells it has 64 cells in it, and nothing has happened for half an hour.

https://i.gyazo.com/d2b3891b8e24df010e7d958a31f2bf40.png

**Comment by modmuss50** [comment]
![java_2018-05-06_12-05-13](https://user-images.githubusercontent.com/4324090/39672623-c31e2354-5125-11e8-8a53-50fd150046ef.png)

working fine in dev, I cannot reproduce.
