### ISSUE TITLE
Font size in PDA is too small for Unicode

### ISSUE THREAD

**Issue by oldjunyi** [TechReborn/TechReborn#151]
Tested under 1600 x 900 Fullscreen, GUI Scale: Large (same as auto)
The OpenGL scale ratio should not less than 1.0 for Unicode font, otherwise some lines of pixels will be missing.
![temp](https://cloud.githubusercontent.com/assets/641817/9986064/febcc424-6069-11e5-89d1-c0d40209c36f.png)

**Comment by gigabit101** [comment]
this will be solved soon been working on a PDA config page for you to set things like that

**Comment by gigabit101** [comment]
The Pda will be rewritten in 1.8.9

**Comment by modmuss50** [comment]
@gigabit101 what about the pda just links to the wiki. The wiki can be updated by anyone, and doesn't need a mod update to update. We just need someone to help write it.

**Comment by modmuss50** [comment]
The multiblock stuff can stay in the pda

**Comment by covers1624** [comment]
^^ I like that idea.

**Comment by modmuss50** [comment]
We might be able to go as far as right click a block with the pda and it opens the relevant wiki page.
