### ISSUE TITLE
generator recipe is not working

### ISSUE THREAD

**Issue by bear989** [TechReborn/TechReborn#1510]
the recipe is in JEI but doesnt craft for ic2 re battery 

ic2 generators dont work in TR recipes
or have a recipe to change from one to another

**Comment by modmuss50** [comment]
Just to make this a bit clearer the ic2 battery will not work in our generator recipe as it wants the full battery and not the empty one that is given when crafted. I think it needs some nbt or something.

**Comment by modmuss50** [comment]
not TechReborn, another mod is breaking it.
