### ISSUE TITLE
Assembling Machine JEI issues

### ISSUE THREAD

**Issue by Froggy800** [TechReborn/TechReborn#1514]
I was playing around with the Assembling Machine and I found the following issues:
- The JEI recipe window is all sorts of broken (see image below)
- Using the "+" button to automatically place items from the recipe viewer removes the two machine upgrades in the top slots, if present. No item is placed in the input slots
- tile.techreborn.assemblingmachine.name is not localized
- [EDIT: ignore this one, I did something dumb] The craftTweaker integration doesn't allow you to specify an amount for the item output; for example, using [this script](https://pastebin.com/FfKdzVBJ) makes the machine only outputs a single item 

Tested on TechReborn 1.12.2 2.15.6.642, RebornCore 1.12.2 3.8.1.271, jei 1.12.2 4.9.1.175 and Forge 14.23.3.2655

I would also like to request the addition of a basic circuit board item, like the one in Gregtech that is made in the Assembling Machine (I can easily do it with other mods, but I thought it was worth asking)
![2018-05-13_08 39 56](https://user-images.githubusercontent.com/25703114/39964645-a2a2aaa2-5678-11e8-8732-5bed9b3b6fad.png)

**Comment by modmuss50** [comment]
I think this was fixed just after I pushed the last update. So it will be fixed in the next one.

**Comment by drcrazy** [comment]
YEs, JEI support for assembly machine was fixed just after release build )

**Comment by Froggy800** [comment]
Just to make sure you know, the second issue from the previously posted list is still there.

**Comment by drcrazy** [comment]
You mean "Using the "+" button to automatically place items from the recipe viewer removes the two machine upgrades in the top slots, if present. No item is placed in the input slots", right?

**Comment by Froggy800** [comment]
Yes.
(Sorry for the late reply, I've been away for a while)
