### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot get property PropertyDirection as it does not exist in BlockStateContainer{block=minecraft:air}

### ISSUE THREAD

**Issue by Myriadtail** [TechReborn/TechReborn#1515]
Mod Version: 2.15.5.638
Minecraft Version: 1.12.2
Pack: All The Mods 5.9.5
Crashlog: [Here](https://pastebin.com/UJuYLW9A)

Loosely put, there's bad cleanup within Forge in regards to blockstates like these.  Vazkii had to [fix this](https://github.com/Vazkii/Botania/commit/0085bc2415b379b76a2e264ac797ea35edbea298) in Botania after a player breaks a Mana Pool without replacing it exactly where it was, and Forge is still checking that block even if it's no longer there.  This has appeared elsewhere in Compact Machines 3 (Forge is trying to check the size of the Compact Machine when it's not there) and is now appearing in Tech Reborn.

**Comment by modmuss50** [comment]
Ive fixed it in that one location, but other blocks may have similar issues. Due to it being a forge bug I dont mind fixing them when they appear. So let me know if you find it on any other blocks. Thanks.
