### ISSUE TITLE
crash with RSWires

### ISSUE THREAD

**Issue by Leftorius** [TechReborn/TechReborn#1517]
with TechReborn-1.12.2-2.15.5.638-universal it works fine. But newer versions crashing with this:

https://pastebin.com/eVmezYj5

**Comment by drcrazy** [comment]
What mod adds teslatite dust?

**Comment by Leftorius** [comment]
I think it's Quacklib
https://minecraft.curseforge.com/projects/quacklib?gameCategorySlug=mc-mods&projectID=276915

but it's called Nikolite. (JEI doesn't show any teslatite, so I'M not sure! but it works fine with TechReborn 5.638 (build from 6th. May) but nothing newer.

Do I have a chance to find out what mod could cause this?

**Comment by drcrazy** [comment]
Are you playing particular modpack?

**Comment by Leftorius** [comment]
I modified ATM3, so almost. But if I remove RSWires, then it works! 

I don't know why but now it works. I deleted Techguns and now it works, so funny circumstances

**Comment by modmuss50** [comment]
I installed RS wires and failed to reproduce the issue, but ive had a go at fixing it.

Before we used to have teslatite dust, but this was removed. so now the recipe checks to see if another mods adds dustTeslatite and it will use that. Let me know if the issues still persists after you update. Thanks.
