### ISSUE TITLE
Industrial blast furnace guide imcomplete multiblock when working

### ISSUE THREAD

**Issue by waitLH** [TechReborn/TechReborn#1518]
When my industrial furnace is smelting,it guide "imcomplete multiblock".I replace the furnace block but it still guide this.Only if i dig up all machine casing block and build it in another place,it can work.But a few minutes later,it guide "imcomplete multiblock" again.
All machine casing are in the same chunk,and i load the chunk by FTBUtilities.
Modpack FTBContinuum-1.0.2-1.12.2
Forge 14.23.3.2689
Mod 2.15.6.642
![qq 20180519161253](https://user-images.githubusercontent.com/23034672/40266613-50d6cf10-5b81-11e8-9d19-4b10cacafac1.png)
![qq 20180519161313](https://user-images.githubusercontent.com/23034672/40266626-9456510c-5b81-11e8-85f8-1e77bb08517c.png)

**Comment by drcrazy** [comment]
I can't reproduce it in Continuum 1.0.2.

I see some weird check about no tile entities below multiblock. Do you have anything there, like chests, etc?

My blast furnace already processed some galena dust and it is still valid multiblock.

![image](https://user-images.githubusercontent.com/1382352/40268933-772c6000-5b7f-11e8-9787-32df45a08ce8.png)

**Comment by modmuss50** [comment]
Are you playing in single or multiplayer? Is there anything in the log (When you open / have the gui open?). 

Is the machine still working even though that message is being displayed?

**Comment by waitLH** [comment]
I'm playing in multiplayer game,server is download from twitch too.Today i replace the 2 air block to lava,and this issue didn't happen again.I think you can try to use air inside and whether this issue happen

**Comment by waitLH** [comment]
When the message being displayed,the machine didn't working.

**Comment by modmuss50** [comment]
I cannot re-produce this, ensure that the mutliblock is correct with no extra casing touching the outside.

**Comment by derGrinch69** [comment]
i have the same issue. after several rebuilds (in different junks) it works again for a few sec. or minutes. playing on smp server (FTBContinuum-1.4.1-1.12.2) aswell. And by the way ... i am pretty sure it has something to do with feral lanterns illuminating the inside of the blastfurnace.

**Comment by drcrazy** [comment]
there should be either air or lava inside blast furnace. This is how it works. BTW, placing lava inside furnace will give you almost free heat bonus. )

**Comment by derGrinch69** [comment]
oh, thanks .... good to know! ^^

**Comment by campbebj** [comment]
I was able to reproduce this by placing a casing adjacent to the complete multiblock. not sure why it invalidates it. this doesnt occur with industrial grinder. just the industrial blast furnace.
