### ISSUE TITLE
[Bug] Scrapbox drops not showing up in JEI

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1519]
When I look up scrapbox drops in JEI, they don't show up:
![image](https://user-images.githubusercontent.com/12701912/40269119-cb25f21c-5b79-11e8-8f54-a5214a5058c1.png)

**Comment by drcrazy** [comment]
Check the compat config. Is Show Scrapbox enabled there? It is disabled by default.

**Comment by modmuss50** [comment]
Works fine once enabled in the `compat.cfg` config file.

**Comment by Skillotic0703** [comment]
Yeah sorry I didn't know there was a config for that!

**Comment by drcrazy** [comment]
No problem, it is always better to ask
