### ISSUE TITLE
[Bug] Scrapbox crafttweaker support is broken

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1520]
The scrapbox support seems to be broken. Here's the script I'm using:

mods.techreborn.scrapbox.removeAll();

//Living Root
mods.techreborn.scrapbox.addScrapboxDrop(<botania:manaresource:20>);

//Rubber Sapling
mods.techreborn.scrapbox.addScrapboxDrop(<techreborn:rubber_sapling>);

This script does exactly nothing.

**Comment by Xavion3** [comment]
That's the exact script? Because that script won't work, it'll throw a syntax error. You need < > around the item names like this or crafttweaker won't recognise them as items.

```
mods.techreborn.scrapbox.removeAll();

//Living Root
mods.techreborn.scrapbox.addScrapboxDrop(<botania:manaresource:20>);

//Rubber Sapling
mods.techreborn.scrapbox.addScrapboxDrop(<techreborn:rubber_sapling>);
```
