### ISSUE TITLE
Larger fusion reactor sizes scale energy poorly in comparison to cost

### ISSUE THREAD

**Issue by Xavion3** [TechReborn/TechReborn#1521]
Due to the power multiplier going up linearly but the amount of fusion coils required scaling with the cube of the size pretty sure based off the maths I could work out the larger sizes are far more expensive then the power you get.

For the extreme case, the size 50 reactor you have to spend 3172 fusion coils to build the ring and get a power multiplier of 45. A more tame reactor like a size 12 needs only 40 fusion coils and has a multiplier of 7, even adding the costs of the fusion reactor that means the incredibly expensive maximum size reactor produces only 6.5x as much power despite cost over 75x as many resources to build.

My attempts to actually work out the numbers got a size 12 as the most efficient size, anything past there and you rapidly reach the point where you can build several fusion reactors for the same cost to get several times the power which seems to largely defeat the point of allowing for such incredibly large sizes in the first place.

**Comment by modmuss50** [comment]
Yes you are correct, I am aware of this. I was thinking of adding some recipes that required the larger reactors at some point, but I need some ideas for this.

I first had it square the size to get the power modifier but that caused the machines to produce millions of RF. 

Current code:

https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/tiles/fusionReactor/TileFusionControlComputer.java#L274

Old code: https://github.com/TechReborn/TechReborn/blame/9d0a2a0ddc29a0875820c90fd14dbcbd6af446c1/src/main/java/techreborn/tiles/fusionReactor/TileFusionControlComputer.java#L274

Im not sure what the best would be as I dont want the machine to be expensive, but then I dont want it to be incredibly OP. People who have played with the current version already have enough power at this point, and they create the largest reactor just as something to do.

Anyway, if anyone has any suggestions for balance changes or new recipes that could only work with larger reactors please let me know. Thanks a lot ;)

**Comment by Xavion3** [comment]
A simplistic method would be make it scale with the amount of coils instead of the radius, but this would make smaller sizes practically useless. A size 12 being only 2.5x a size 6 in power. Actually, doing some maths you basically can't make the largest sizes viable without doing that. The amount of coils required just goes up too fast that to keep power on par you'd need it increasing faster than it used to.

Although millions of RF isn't too notable even now, a size 14 is where you hit 1 million RF/t with the current linear scaling. The resources to build a current max size reactor if split up between many smaller reactors hits around 60 million RF/t, or just around 5.75MRF/t with a normal one.

So it really comes down to how much you want, even the several hundred thousand RF per tick of the size 10-12 is more than enough in pretty much all cases.

The idea of recipes that require larger sizes sounds good, the trick is what to do with them. More tiers of plasma for more power generation doesn't help the issue at all, and UU matter already handles the field of resource generation reasonably so it does leave things in an odd spot.

There are some other options still, a simple case would be allowing recipes to be overclocked. So a 2x multiplier could let it craft twice as fast for twice the RF/t, currently it looks like the multiplier does nothing to costs, only to power production if I'm reading the code right.

Maybe more materials being craftable on that note? That wouldn't help with the larger size problem, but being able to craft chrome could help with things like expanding fusion reactors, a few options exist, Aluminium + Sodium, Sulfur + Oxygen, or Titanium + Helium for example. Making it craftable from UU mater would also solve that, but restricting some materials to fusion reactor crafts could be interesting.

For big fusion reactors you may have to start adding more fictional materials, exotic materials that allow you to make better machine upgrades such as IC2 Classic's quantum overclockers or how GT5u made neutronium allow for better tiers of machines and armour.

**Comment by modmuss50** [comment]
Ok, ive tweaked it a bit. Using 1/2(x-5)^1.8

Max Size:

![java_2018-06-09_12-14-00](https://user-images.githubusercontent.com/4324090/41190894-a05e7700-6bde-11e8-902f-62ed4181db67.png)

Medium size

![java_2018-06-09_12-22-56](https://user-images.githubusercontent.com/4324090/41190965-dfe93e18-6bdf-11e8-8aa2-3839ef8b7054.png)

Smaller size

![java_2018-06-09_12-24-32](https://user-images.githubusercontent.com/4324090/41190976-1abc666e-6be0-11e8-9145-f72fdfc829e3.png)

I feel like this is almost impossible to get perfect, but this will do for now. Feel free to suggest some more values to make it work a bit better.
