### ISSUE TITLE
[1.12.2] Severe Problem causing the game to crash after updating Reborn Core

### ISSUE THREAD

**Issue by Draskh** [TechReborn/TechReborn#1525]
See here.

[crash-2018-05-27_02.11.22-client.txt](https://github.com/TechReborn/TechReborn/files/2042053/crash-2018-05-27_02.11.22-client.txt)

**Comment by evieluvsrainbows** [comment]
Same issue here. Please fix soon :)

[crash-2018-05-26_22.17.40-client.txt](https://github.com/TechReborn/TechReborn/files/2042266/crash-2018-05-26_22.17.40-client.txt)

**Comment by modmuss50** [comment]
That should fix it, going to push a hotfix now.
