### ISSUE TITLE
Energy-using tool info on HUD

### ISSUE THREAD

**Issue by tomdodd4598** [TechReborn/TechReborn#1526]
Hey there,

Just a quick question - is there a way to configure where the energy info for held tools appears on the HUD?

There also seems to be a bracket missing on the end of _"(inactive"_ in that tool-tip.

Thanks in advance!

**Comment by tomdodd4598** [comment]
Awesome - thanks a bunch!

**Comment by drcrazy** [comment]
It will be available on curse with next release of RebornCore.
