### ISSUE TITLE
Electric Furnace causing crash on startup

### ISSUE THREAD

**Issue by ParkerJones** [TechReborn/TechReborn#1527]
I'm creating a custom modpack and I'm having an issue with a crash while TechReborn is loading.
 
Crash Log:
[crash-2018-05-28_02.38.59-client.txt](https://github.com/TechReborn/TechReborn/files/2043971/crash-2018-05-28_02.38.59-client.txt)
 
Any suggestions? Thank you very much for your time.

**Comment by modmuss50** [comment]
You need to install reborn core

**Comment by drcrazy** [comment]
reborncore                 | 3.8.5.290  
installed
