### ISSUE TITLE
Make machines harder to break with a pickaxe

### ISSUE THREAD

**Issue by BlayTheNinth** [TechReborn/TechReborn#1528]
It's happened twice now that I've accidentally broken one of my machines and lost a frustrating amount of progress (modpack with non-vanilla recipes) simply because I'm so used to breaking things with my pickaxe and Tech Reborn lets it happen so easily.

I think it's safe to assume that a player will probably never want to break a machine with a pickaxe and lose the machine, so it would be really helpful if the breaking speed could be reduced for them as a kind of "reminder" or "hint" to players who've played modded before. Currently I can break it almost as fast as cobblestone, when it should be more around the speed of breaking a chest with the wrong tool.

I personally don't see how the whole wrench mechanic adds to the fun of the game, it just seems like a forced inconvenience to me - but making it more clear ingame would at least be a good compromise.

**Comment by modmuss50** [comment]
3 Days ago this was added (To RebornCore) after someone else suggested it. 

https://github.com/TechReborn/RebornCore/commit/78fcae19e575de3ca8be80bf157fe63c54eb605e

The wrench can be disabled by a config option, its one of the things that some people love and some people hate. I will have a think about changing the default option for 1.13 possibly.

**Comment by BlayTheNinth** [comment]
Ah, nice! Alright, hopefully I'll remember to be careful until FTB updates then. :)

**Comment by modmuss50** [comment]
Quick update on this, wrenching machines will be disabled in the next version of FTB continuum.
