### ISSUE TITLE
[Request] Blacklist for rubber tree spawn

### ISSUE THREAD

**Issue by Draskh** [TechReborn/TechReborn#1529]
I noticed that there is no option to blacklist biomes to prevent tree spawing. Sometimes they are in biomes where they shouldn't, e.g. some BOP biomes and Abyssalcraft. 

Could this be added to the config? Black or whitelist?

**Comment by modmuss50** [comment]
Yeah, I dont see why not. In 1.13 I do plan on making all of the world gen a bit more configurable, but I don't really want to break the current world gen config in 1.12. Adding a simple blacklist should be possible without breaking things.

**Comment by Draskh** [comment]
That would be nice. Thank you.

**Comment by modmuss50** [comment]
Added see bellow for an example ores.json config file:

https://gist.github.com/modmuss50/1768561b270c53085df63f19b19e658f#file-ores-json-L178-L181

just use the biome registry name to blacklist it.

**Comment by Draskh** [comment]
That's great, thank you. :)
