### ISSUE TITLE
Major Performance Issue

### ISSUE THREAD

**Issue by mtimyself** [TechReborn/TechReborn#1532]
I have just reported a major performance issue with the version of TR in use in FTB's Continuum pack.
Since that is a major pack and it relies very heavily on your mod you might want to see if you can lend a helping hand.

https://github.com/FTBTeam/FTB-Continuum/issues/140

**Comment by modmuss50** [comment]
I will get around to taking a look at this when I have some time, but I have a few exams this week so its going to have to wait.

**Comment by modmuss50** [comment]
Ok, this has been made better by some changes to the balance of the input speed and the speed of the electric furnace.

The best thing you can do to get a better playing experience is to enable forge's threaded chunk rendering, this reduces the impact of the block updates a lot.

![2018-06-05_22-09-57](https://user-images.githubusercontent.com/4324090/41003138-de62f658-690d-11e8-8353-6f3b87334350.gif)

I will ask about getting this config enabled by default in the FTB contiunm pack as it helps a lot with this issue.

There is more work to be done on this to ensure that it is impossible for the block to be constantly changing blockstate but that is for when I have more time.
