### ISSUE TITLE
TR gem armor can't be repaired on anvil with a material it consist.

### ISSUE THREAD

**Issue by zcaliptium** [TechReborn/TechReborn#1534]
If your armor is broken and you want to repair it then you can't do it. :sob:
Seems like repair material not defined for armor item.

Noticed that issue when tried to repair sapphire armor with sapphire gem.

**Comment by modmuss50** [comment]
![java_2018-06-08_18-32-43](https://user-images.githubusercontent.com/4324090/41172015-5b753910-6b4a-11e8-831a-680b7242f8ba.png)

Fixed for all tools and armor, nice spot

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/TechReborn/commit/548d393820b982b7f96dddb8a598aa69258cec65
