### ISSUE TITLE
Sawmill Recipe change certain Ore Dictionary Entries for logWood

### ISSUE THREAD

**Issue by mallrat208** [TechReborn/TechReborn#1538]
TechReborn Version: 2.14.12.690
RebornCore Version: 3.8.7.295
Forge Version: 14.23.4.2707

I think this is actually two bugs. The First is that the Sawmill Recipes are directly modifying the Ore Dictionary entry for logWood and the second is that the actual recipes themselves make some incorrect assumptions as to itemstack meta value.

https://github.com/TechReborn/TechReborn/blob/05bab2ec4cdd83558c6291cafca85af758f486c2/src/main/java/techreborn/init/recipes/IndustrialSawmillRecipes.java#L71

When the option is enabled to add Sawmill Recipes, all Logs from Biomes O Plenty end up with the ore dictionary tags removed from the log ItemStacks. Disabling the sawmill recipes results in the ore tags showing up properly.  Checking with CraftTweaker shows that the log items are in fact registered, they are just registered with a meta value of 0, which is an invalid itemstack for the purposes of those items.  It looks to me that the problem stems from the Item having subtypes but not making use of the Wildcard entry for the OreDictionary declaration, 

https://github.com/TechReborn/TechReborn/blob/05bab2ec4cdd83558c6291cafca85af758f486c2/src/main/java/techreborn/init/recipes/IndustrialSawmillRecipes.java#L86

**Comment by modmuss50** [comment]
Interesting, I should copy the item-stacks after getting all of the wood logs.

Thanks for providing a clear issue 👍
