### ISSUE TITLE
Fusion Control Computer not consuming provided items

### ISSUE THREAD

**Issue by wbayer81** [TechReborn/TechReborn#1539]
Hello Dev Team,

first of all thank you for this great mod and your effort developing it!
But I've found a way to generate massive amounts of RF at no cost.

With the correct setup of energy storage, item pipes and redstone clock neither of the required items to get a fusion going are consumed.
I've attached a screenshot of my setup.
A possible solution would be to consume both input items as soon as the reaction is started.

![fusion](https://user-images.githubusercontent.com/20745026/41189203-4d976d60-6bca-11e8-823f-05255e8a4d7f.png)

**Comment by modmuss50** [comment]
Nice spot, yeah I will make it use the items first
