### ISSUE TITLE
Crash with Normal GT reborn

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#154]
GT reborn  ( normal ) crashes when you open the creative search function ( http://paste.ee/p/JKmcJ ) or try to use the NEI recipe functions ( http://paste.ee/p/ZDmaz ), that seems to be caused by a null item ( from Speiger ), the IC2 version is the classic one, I can provide you the list of mods I am using if you need to.

**Comment by modmuss50** [comment]
So the issue is only when ic2 classic is installed?

**Comment by Carbon-Ghost** [comment]
Gonna test with experimental, but it was tested with latest "recommended" TechReborn, so unless other people tested it and crashed with experimental, I am pretty sure it only occurs when classic is here.

**Comment by modmuss50** [comment]
It might be because of old dependences, I just saw that the ic2-classic api updated.

**Comment by Carbon-Ghost** [comment]
oh kk, that might explain some stuff... btw you need to assign values to the thorium and plutonium fuel rods to the steam reactor, else game might go on drugs again :P

**Comment by modmuss50** [comment]
Just waiting on a compilable version of the ic2 classic api. Ive made a comment on the broken commit.

**Comment by Carbon-Ghost** [comment]
Kk

**Comment by modmuss50** [comment]
Did updating the apis fix this?

**Comment by Carbon-Ghost** [comment]
gonna try it...

**Comment by modmuss50** [comment]
It might be a mod conflict

**Comment by modmuss50** [comment]
Its been reported working fine with the latest version on irc.

**Comment by lilmoefow** [comment]
Im using Forge 1492, TechReborn-0.5.0.873-universal, IC2.Classic.Version.1.1.1.5 and im getting this crash when trying to launch the game(not sure if this is relevant to this current post, just didn't want to open a new one just in case)

http://pastebin.com/jkkW7ui9 thats my crash log...

**Comment by modmuss50** [comment]
That was fixed with, https://github.com/TechReborn/TechReborn/commit/3a256ad6f1db7fd16e90b3cfbc6908466f009776 use http://maven.modmuss50.me/TechReborn/TechReborn/0.5.0.878/TechReborn-0.5.0.878-universal.jar

**Comment by lilmoefow** [comment]
Alright sweet,  now if there were actual recipes for the items.  :p.  I don't mind adding them myself with minetweaker for now though

**Comment by modmuss50** [comment]
I need to go through all of the ic2 recipes, and tweak them for ic2 classic. I will make this a priority because a lot of people have been asking for it.

**Comment by lilmoefow** [comment]
Why not just use the original recipes that GT4 used back in 1.4.7 ... seeing as thats pretty much what IC2C is doing with its mod.

**Comment by modmuss50** [comment]
So recipes with ic2 are not working?

**Comment by lilmoefow** [comment]
I loaded it with TechReborn-0.5.0.878-universal, and industrialcraft-2-2.2.780-experimental,  using Forge 1492 and only a few items have recipes, pretty much all the machines have no recipes.

**Comment by modmuss50** [comment]
ok thanks, I will look into it now
