### ISSUE TITLE
[Suggestion] The Fusion Control Computer should tell you how many Fusion Coils are needed for the size you're making

### ISSUE THREAD

**Issue by aaronhowser1** [TechReborn/TechReborn#1540]
Right now we have to do trial and error, and if we don't have enough we have to break all of the Fusion Coils manually and then go down a size, then repeat if you still don't have enough.

**Comment by modmuss50** [comment]
Yeah, that should be possible, I guess I should make it shows in stacks and items as well

**Comment by aaronhowser1** [comment]
It'd also be good if the recipes were shapeless. Like, right now it won't work if Deuterium is in the left slot and Tritium is in the right

**Comment by modmuss50** [comment]
Yeah, that would make sense, ill include that I work on the other open issue.

**Comment by modmuss50** [comment]
![java_2018-06-10_11-34-40](https://user-images.githubusercontent.com/4324090/41200732-47f39950-6ca2-11e8-97b3-799c5a5748a6.png)

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/TechReborn/commit/dace0e56d0390ee1f2a134831bc99c76023ae623
