### ISSUE TITLE
Is this fixed in later versions? Wrench problem on at least Transformers.

### ISSUE THREAD

**Issue by henkaa** [TechReborn/TechReborn#1543]
Hi.
I am playing on a server with Modern Skyblock 3 departed. (version 3.3.1.4 of the modpack). It is using 1.12.2-2.15.2.608 of Tech Reborn and I found an issue on it that I want to confirm if it is fixed or not :)

On some machines (I noticed this on the Transformers) using a wrench makes the item disapear, but could be removed using the pickaxe and on some the wrench works.

So I tried a pickaxe on one of my solar panels (luckely not to expensive one) and it turned into a machine frame (as expected).

Should I try the configuration to disable wrench? Is that needed to be done on server or client side if so?

**Comment by henkaa** [comment]
I noticed a change when testing a later version of the modpack which is using 1.12.2-.2.15.11.688
I tried on transformers, battery box and solar panel with wrench and pickaxe. This was the result
Transformer: 
- wrench: nothing happens
- pickaxe: picks item
Battery box:
- wrench: picks item
- pickaxe: picks item
Solar panel:
- wrench: picks item
- pickaxe: gives basic machine frame

**Comment by drcrazy** [comment]
Nope it is not fixed yet. In general all machines are fine now. Almost all generators too. Energy storage and transformers and lamp are not fine
