### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by frank89722** [TechReborn/TechReborn#1544]
After I update techreborn from 2.15.9.663 to newer version (all version after that have same issue)
my game crash on startup
crash report: https://pastebin.com/VHbRKWNg

**Comment by drcrazy** [comment]
Are you playing any specific mod pack?

**Comment by modmuss50** [comment]
Fixed with, https://github.com/TechReborn/RebornCore/commit/1db9942d9aeb3a08a25b248a96fe7a2a3a5e83c0
