### ISSUE TITLE
Empty cell with NBT tag not working in machine

### ISSUE THREAD

**Issue by jottafan** [TechReborn/TechReborn#1545]
https://github.com/FTBTeam/FTB-Continuum/issues/201

Playing ftb continuum 1.2.1

My ideas: make machine accept empty cell with or without tag, aslong as its empty. Or if possible make better interaction with extra cells 2 to fix the issue

BrockWS : "Looks like an issue with TR, only happens when placed back into the players inventory and not when emptied by the terminal"

**Comment by modmuss50** [comment]
Im not too sure if this is our issue or not tbh.

**Comment by modmuss50** [comment]
![java_2018-07-16_21-59-55](https://user-images.githubusercontent.com/4324090/42783368-b9073e2c-8943-11e8-91fc-0a3d94484b7a.png)

Seems to work fine, I believe the issue was due to the custom recipes in the pack.
