### ISSUE TITLE
Battery charge/discharge issue

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1547]
![2018-06-13_20 20 35](https://user-images.githubusercontent.com/12701912/41370196-403825b2-6f47-11e8-96a4-e42dc49a9da8.png)
I inserted a full battery (which contains 10k EU) and I used it to charge a grinder which stores 1k EU. However the battery lost 1024 EU (10k - 8,976k) instead of 1000 EU.
This issue doesn't happen in a battery box or an mfe. However when I try to charge an empty battery with a battery box which contains 10k EU, the battery only gains 5k EU and if I use an MFE to do the same experience the battery only gains 1264 EU.

**Comment by drcrazy** [comment]
It should be fixed now. Feel free to retest either dev build from Jenkins or wait till release build on curse. 

Discharging battery:
![image](https://user-images.githubusercontent.com/1382352/41668317-c6fcece8-74b7-11e8-8151-5cc5df6c842f.png)


Charging battery:
![image](https://user-images.githubusercontent.com/1382352/41668333-cdda96f0-74b7-11e8-86f8-4356a6f35002.png)
