### ISSUE TITLE
[HWYLA] Energy change doesn't automatically update

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1548]
TR has WAILA/HWYLA integration and when we look at a block that can store power there's an information called "energy change" but it's updated only if you right-click the block and you get out of the GUI. It would be neat if it was updated automatically.

**Comment by drcrazy** [comment]
HWYLA is client side. And energy calculations are done on server. Server to client sync of energy will require too much data to send every tick.
