### ISSUE TITLE
Transformer upgrade weird behaviour

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1550]
The transformer upgrades correctly upgrade the tier of a machine but once a machine reaches the insane tier, adding a transformer upgrade causes the machine to reach the infinite tier. And adding another one gets the machine back to insane tier.

**Comment by drcrazy** [comment]
Fixed by https://github.com/TechReborn/RebornCore/commit/21c3e6d2bda8104d1522389dc7f94b36d103d2f5
