### ISSUE TITLE
 Generators using ore dictionaryed fluids

### ISSUE THREAD

**Issue by Lach01298** [TechReborn/TechReborn#1554]
I think the generators (gas, diesel, and semi-fluid) should be able to use ore dictionaryed fluids.
e.g. the diesel generator should be able to use diesel from immersive petroleum and other mods and the gas generator should be able to use hydrogen from mekinism and other mods.

**Comment by modmuss50** [comment]
This is an issue, but I don't think it is currently possible to fix due to not being able to remap fluids. I will leave this open as I am currently looking into other possible fixes.

**Comment by modmuss50** [comment]
Im closing this as it has been fixed in our prep branch for 1.13, sorry about this but breaking worlds this late into 1.12 isnt really an option for us.
