### ISSUE TITLE
Client crash. (Referred by RFTools team)

### ISSUE THREAD

**Issue by TheDarkPreacher** [TechReborn/TechReborn#1559]
I reported this crash to the RFTools team, they told me to report it to your team.

RFTools Issue: https://github.com/McJtyMods/RFTools/issues/1801#issuecomment-400867908

Crash log paste: https://pastebin.com/7Z3Wet3u

Coop Life 2 Modpack, Minecraft 1.12.2, Forge 14.23.4.2705, RFTools version 1.12-7.53, McJtyLib version 1.12-3.01, Tech Reborn version 1.12.2-2.15.15.712

They said that since lines 18-20 reference Tech Reborn to report it to you. (Which makes no sense to me, since there was not a Tech Reborn item involved with the crash.)

**Comment by drcrazy** [comment]
Hi @TheDarkPreacher 

Can you, please, check if issue is already fixed with recent TR and RC release ?
Specifically, I'm talking about TechReborn-1.12.2-2.16.0.746 and RebornCore-1.12.2-3.9.0.315

**Comment by modmuss50** [comment]
Should be fixed with, https://github.com/TechReborn/RebornCore/commit/2d5422ab354792524e438ff8341efb565b8db577
