### ISSUE TITLE
ore dusts show wrong grinder recipe in jei with jenkins MOH

### ISSUE THREAD

**Issue by falizure** [TechReborn/TechReborn#1563]
when running a pack that includes tech reborn 1.12.2 2.16.0.746 with reborn core 1.12.2 3.9.1.318, forge 1.12.2 14.23.4.2705, and running titanium 0.1.0.19 matter overdrive horizon 1.0.0.4 attempting to look up the recipe for matter overdrive iron, gold and tritanium dusts in jei all 3 show the same recipe, tritanium ingot to tritanium dust when processed in the tech reborn grinder, instead of ether all 3 showing their respective ingot to dust assuming it defaulted to MO dust versions for whatever reason or show no recipes at all instead of the incorrect recipe for iron and gold dust, when actually placing ingots into the grinder however iron and gold ingots do come out as iron and gold dust from tech reborn and tritanium ingot to dust is as expected so it appears to only be a recipe lookup.

**Comment by modmuss50** [comment]
I have no idea what is causing this issue. The recipes we are adding look be ok. 

https://gist.github.com/modmuss50/0f77dfddfc2079b8494c52add12211ec

My only guess is its something to do with JEI or our JEI plugin. MOH still seems to be in early alpha if that, so fixing this isnt a priority.
