### ISSUE TITLE
Cannot remove IC2 compat compressor recipes with crafttweaker

### ISSUE THREAD

**Issue by SlyCedix** [TechReborn/TechReborn#1565]
https://i.imgur.com/NHMz3c7.png
https://i.imgur.com/IPmZvSt.png

https://pastebin.com/6Z7fr9b1

I am both removing all recipes and removing the specific recipe I need gone, and neither actually remove the recipe.

It isn't a massive issue, because the recipe that the compressor should be using is the one being used

https://i.imgur.com/BCd1LhX.png

But it is quite annoying because I am trying to establish unification in my pack

**Comment by drcrazy** [comment]
Plate recipe removed successfully with CT.
![image](https://user-images.githubusercontent.com/1382352/42480597-fb8e8316-83e6-11e8-91a0-2adc7d25c042.png)
