### ISSUE TITLE
Found a crash at startup in the latest version

### ISSUE THREAD

**Issue by Altarya** [TechReborn/TechReborn#1566]
[log](https://pastebin.com/QWy9Ep7H)

It might be something registering in TC, but i thought i'd report here first

**Comment by modmuss50** [comment]
Are you using a mod pack?

**Comment by Altarya** [comment]
I am, but i am actually the Modpack's maker

**Comment by drcrazy** [comment]
What is mod pack name?

**Comment by Altarya** [comment]
Stable-127, there is an experimental version on curse, although quite unfinished and is using very outdated versions of TR and well everything else in it, since i released it back in February.

And i am the sole developer of it, hence why i haven't updated it yet, but i'm slowly making progress, but as of late i can't even get the game to launch, thanks to some errors at different loading stages, I've fixed the ones that happened at earlier stages of game load with this being the latest one happening at the point the game loads recipes.

**Comment by modmuss50** [comment]
Is there anyway you could possibly send me an export of the pack that is crashing? Or remove mods one by one until you find what is causing the crash with TR?

If you need to send the link privately feel free to send me a message on discord, if not I can have a guess at fixing it and send you a dev build to try out.

**Comment by Altarya** [comment]
I can send you a link via discord yes, while going through the mods one by one, which i have been doing for a couple days(200 mod modpack... it takes a while)

Would you need me to join the TR server or just send it with a DM?

**Comment by modmuss50** [comment]
Either works fine, the TR discord is: https://discord.gg/teamreborn

**Comment by modmuss50** [comment]
Closing as I don't believe this to be a TR issue, another mod is breaking the item -> block map.
