### ISSUE TITLE
Energy Capacity option for Energy Crystal

### ISSUE THREAD

**Issue by dancc7t** [TechReborn/TechReborn#1567]
Hello, i was wondering if it would be possible to add an option in the config file to change the energy capacity of energy crystals, it only has 400kFE, just the same as a lithium battery, and 10 times less than its IC2 colleague, whilst lapotron crystals have both the same capacity.

Thanks.

**Comment by drcrazy** [comment]
Hi @danikk14g  

Energy capacity for energy crystal already there. Check items.cfg file for 
    # Energy Capacity for Energy Crystal (FE) [Default=4000000]
    I:energyCrystalMaxCharge=4000000
