### ISSUE TITLE
Material Injector (from old gt/ig) suggestion. (+problem solved)

### ISSUE THREAD

**Issue by 34486** [TechReborn/TechReborn#1570]
I am using the latest version because I didn't want that dupe with the fusion reactor, so anyways I sneak right click with the Techreborn wrench on LESU controller, and the game froze and crashed. 
[crash-2018-08-03_20.03.34-client.txt](https://github.com/TechReborn/TechReborn/files/2259065/crash-2018-08-03_20.03.34-client.txt)

Hopefully this is an easy fix! Thanks! 

Also, Not sure if I should make another thread for a simple request/addon from old gt/ig but can there be like the material and matter injectors or whatever for the fusion reacotr to add liquids so i can pump in deut and hydrogen 3 in a liquid form instead of cells? (Maybe even the old reactor design that can still be upscaled?) 

Thanks!

**Comment by modmuss50** [comment]
To fix the crash update RebornCore.

Liquids in the fusion reactor, thats not a bad idea, im not sure how the details would work however

**Comment by 34486** [comment]
Oh, I should have checked to make sure I had the latest of reborncore.. sorry.  Thanks though! Oh wow TechReborn was just updated 8 hours ago too, I didn't expect that! 

Anyways, yea the old gt/ig had like material injectors to inject fluids and cells into the thing, (Essentially I hope you all can duplicate the old gt/ig fusion reactor design, but you know, make it so it can still be scaled up.... :) hehe) 

Edit: How can this thread be changed to suggestion?

**Comment by modmuss50** [comment]
Having a block that takes the 2 fluids + some cells (as cells are used for the output) that inserts it into the main block might be an idea. Ill give it some thought.

**Comment by 34486** [comment]
Oh wow thanks!

**Comment by modmuss50** [comment]
Ok, we had a think about this, you can use the quantum tank to fill up cells with fluid, and then use that put the cells into the reactor. I plan on adding a fluid config like the item slots that allows for auto exporting/importing fluids.

**Comment by 34486** [comment]
But thats like essentially what I am doing, accept with AE2 n' Extra cells, export the cells into the reactor, n gather the heliumplasma up all using ae2. So it already has support for importing and exporting automatically, right?

**Comment by drcrazy** [comment]
as for Items - yes, cells could be imported \ exported automatically. Both pulled from machine or pushed by machine.

**Comment by modmuss50** [comment]
Ok, I dont see a use case for having a separate block to do this, but I have worked on adding a fluid config that allows machines with tanks to push and pull fluids between them, this should make it possible to do without any extra mods.

**Comment by 34486** [comment]
Oh yea! That works too, so I can have like a tank from TB and just use that as the material injector... awesome! Thanks!
