### ISSUE TITLE
Option to enable/disable mod loot in chests

### ISSUE THREAD

**Issue by dancc7t** [TechReborn/TechReborn#1572]
Hello, i am playing a survival world prior the release of my modpack, in which techreborn is a mid game mod, requiring a certain level of progression and metallurgic capabilities, but i happen to see machine frames and alloy ingots among other ingots in almost every chest i find, some chests are totally full of loot, so i am trying to disable loot of some mods. It would be great if you can add a config option to enable/disable loot in chests.

Also i found a block/item with a glitched texture whose itemname is also machine frame in some of the chests. 

Thanks.

Minecraft version: 1.12.2
Forge version: 14.23.4.2747
TechReborn version: 2.16.2.769

**Comment by drcrazy** [comment]
Ability to enable \ disable TR loot in chests will be in world.cfg file.
