### ISSUE TITLE
NPE on server startup

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/TechReborn#1574]
Issue:  1.12.2-2.17.0.782 crashes dedicated server Forge 1.12.2 build 2750

Notes:
     NPE on startup

crash report:
https://gist.github.com/68862d054e6a45876a641979b160e1db

fml server latest:
https://gist.github.com/017d253f2132524549a8d3ed71859d2d

**Comment by modmuss50** [comment]
Fixed, going to release a fix. When I added the new tile I thought there was a bug but forgot what I did to cause/fix it.
