### ISSUE TITLE
Mekanism support

### ISSUE THREAD

**Issue by EngineerXL** [TechReborn/TechReborn#1575]
Hey! Is there a way to make Mekanism fluids and gases compat with TechReborn? I suggest to make fluid-dict. Also, it will be nice to see oil compat (Thermal Expansion, Immersive Petroleumm GalactiCraft etc.).

**Comment by modmuss50** [comment]
Ok, fluids are a bit broken in TR (see #1554), but should be a lot better in the last update (in the fluid generators). I tested build-craft oil and that seemed to work well, if other mods dont work I can test them.

I am happy to add support for other mods, how ever I am not familiar with Mekanism so I dont really know what would be a good idea to add support for. I assume you mean power generation from the fluids?

**Comment by EngineerXL** [comment]
Not only power generaion. For example we can make compressed air = oxygen. So, compressed air will be USEFUL, as Purification chamber needs it to work. Same with Lithium, Sodium, Hydrogen, Deiterium, Tritium, Chlorine, Sulfuric acid

**Comment by EngineerXL** [comment]
Same would be nice with GalctiCraft (Sulfuric Acid, Nitrogen etc)

**Comment by EngineerXL** [comment]
Example (Immersive Tech & Mekanism): 
![image](https://user-images.githubusercontent.com/37447286/44136510-b153bb12-a075-11e8-8a52-925283b17a17.png)

So, if there are no steam from another mods Immersive Tech registers own steam. I'd like to see this system implemented in TechReborn
