### ISSUE TITLE
Energy Issues.

### ISSUE THREAD

**Issue by 34486** [TechReborn/TechReborn#1577]
Slight issue with some numbers, I have an Adjustable storage unit, and it says I put out 64k eu/t, and then I put an LESU next to it (I am trying to find out how the asu works) and it was receiving 128 eu/t, also when I use a wrench to break a storage block, shouldn't it keep its energy in it? 

Edit: Running TechReborn-1.12.2-2.17.1.786-universal and RebornCore-1.12.2-3.10.0.332-universal at the time of this edit and post they were the latest versions released, if a new version comes out I'll check it out.

Forge 2705 for 1.12.2

Thanks!

Edit: Also ASU doesn't keep its input value thing, but DOES keep storage, maybe its just the single LESU controller because it isnt able to keep a greater value if it had a greater one before. 

Edit 2: Found another small problem, Plasma Generators don't display their on-state while on, sometimes, they drain and generate power and consume HP, but they don't seem to look like they are on. Also, Are the progress bars supposed to go really fast? 

Edit 3: Uh, I went to charge my LESU block, and its charge rate was waaay past 8k eu, it was like 48k eu... and yes it was actually charging that fast.. is that supposed to happen or did I change something in the configs????

**Comment by drcrazy** [comment]
Are you playing on 1.12 ?

**Comment by 34486** [comment]
Oh yes, sorry. I'll edit in build stuff and what not. 

Also is the fusion reactor also supposed to have fluid input/output config, and have an option for two tanks, for helium and deuterium, and each tank maxes at 1 bucket so you cant have 1534 mb, unless you can work it out so it consumes in mb, but idk how you would do it.

**Comment by drcrazy** [comment]
IC2 eNet doing second transfer per tick thus doubling transfer rate )

**Comment by drcrazy** [comment]
Plasma generator on:
![image](https://user-images.githubusercontent.com/1382352/47990635-10e93e80-e0f9-11e8-9f72-baa7c8f9e6f1.png)

Plasma generator off:
![image](https://user-images.githubusercontent.com/1382352/47990662-2199b480-e0f9-11e8-8546-d71f02e2542c.png)
