### ISSUE TITLE
[Suggestion] Add some Energy-Powered Armor.

### ISSUE THREAD

**Issue by CrossVas** [TechReborn/TechReborn#1579]
Hey,
I noticed that TR has regular gems armor, but it has not energy-powered one.
It will be great to have at least 2nd and 3th tier of armor (first tier goes to Gems Armor).

**Why?**

Because such a High-Tech mod and no Electric-Armor? No!!

**It must have some.**

Thanks.

**Comment by modmuss50** [comment]
We keep coming back to this, the main issue with adding this is we currently do not have a texture artist. Its on our future-todo list but with 1.13 coming up and no texture artist I dont think its going to happen any time soon.

If someone wants to help out feel free to reach out to me on our discord. Thanks for the suggestion.
