### ISSUE TITLE
Suggestion: Weighted Item Stacks in Crafttweaker

### ISSUE THREAD

**Issue by Guinaro** [TechReborn/TechReborn#1586]
Would it be possible to support Weighted stacks for the various machines.
This would be especially useful in the Industrial Centrifuge, Industrial Grinder, ... 
E.g.
mods.techreborn.industrialGrinder.addRecipe(<techreborn:dust:24>*2, <minecraft:gravel>,<techreborn:dust:24>%50,<techreborn:smalldust:14>%20, <minecraft:gold_ore>, null, <liquid:water> * 500, 100, 10);

This recipe would yield:
Garanteed: 2 gold dust and 1 gravel
50% Chance of an extra gold dust
20% Chance of an Small Pile of Copper Dust.

Using Mercury could yield 3 gold dust, 30% of an extra gold dust, 25% of a Copper Dust
...

In essence: it would allow greater flexibility and allow for an element of chance in the production lines.

The same functionality could enhance other machines: Industrial Centrifuge, Industrial Sawmill, Extractor, ...

Guinaro

**Comment by modmuss50** [comment]
It would require a large amount of work that would also require a lot of testing to ensure it didnt break the current code that has gone mostly untouched for a few years without issues.

Right now I dont think its worth the time to implement this even though its a good idea. Sorry about that.

**Comment by Guinaro** [comment]
No problem, will just need to rethink some ideas how to integrate Tech Reborn into my modpack. Hopefully you keep it in mind to implement this if a rewrite ever happens.

Guinaro
