### ISSUE TITLE
Fluid ID's?

### ISSUE THREAD

**Issue by Freebi85** [TechReborn/TechReborn#1589]
Hello Guys ;-)

Just a Question.

What is the item id (flui id) for Tech Reborn's oil and some other fluids for implementing this in other machines.

Thx

**Comment by modmuss50** [comment]
They can all be found here:

https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/init/ModFluids.java#L38

all of our fluids have the `fluid` prefix witch causes some incompatibilities for other mods. Forge does not provide a way to remap fluids so we are unable to fix this without breaking worlds in 1.12.2. They have been set the to correct names in the 1.13 prep branch.
