### ISSUE TITLE
Incorrect recipes removing

### ISSUE THREAD

**Issue by EngineerXL** [TechReborn/TechReborn#1590]
Mods:
CraftTweaker 4.1.9
TechReborn 2.17.1.786
RebornCore 3.10.0.332

Issue: Trying to remove lava recipe from centrifuge, but CraftTweaker removes ALL recipes included any amount of any cells. So, I got Helium-3 recipe removed too...

Script: mods.techreborn.centrifuge.removeInputRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "lava", Amount: 1000}})*16);

CraftTweaker.log: https://pastebin.com/puBL4yCx

Additional: same issue occurs with all machines, e.g. Electrolyzer recipes

**Comment by EngineerXL** [comment]
Also I have another problem... If I set OreDict value in machines recipes [tested with Electolyzer and Centrifuge], it will ignore count of items [LOL]
Script: `<ore:boneMeal>.add(<minecraft:dye:15>); industrialElectrolyzer.addRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidcalcium", Amount: 1000}}), null, null, null, <ore:boneMeal>*3, <techreborn:dynamiccell>, 20, 106);
centrifuge.addRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidmethane", Amount: 1000}}), null, null, null, <ore:listAllfruit>*32, <techreborn:dynamiccell>, 5000, 5);`
![image](https://user-images.githubusercontent.com/37447286/44629855-d4ad9b00-a95d-11e8-9260-8ffe3df66ab9.png)
![image](https://user-images.githubusercontent.com/37447286/44629948-34587600-a95f-11e8-90af-2b4d6fb688d0.png)

**Comment by drcrazy** [comment]
Can you try to remove recipe with the following CT script, please?

```
mods.techreborn.centrifuge.removeInputRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "lava", Amount: 1000}}) * 16);
```

**Comment by drcrazy** [comment]
Please, see comment regarding oredict usage here: https://github.com/TechReborn/TechReborn/issues/1592
