### ISSUE TITLE
Compressor recipes added by Crafttweaker have incorrect input

### ISSUE THREAD

**Issue by Charnuz** [TechReborn/TechReborn#1592]
Adding a recipe to the compressor via crafttweaker accepts any item that is within oredicts that the original item is in.

For example, this [script](https://pastebin.com/s90YX77L) produces a recipe that accepts any item within the **listAllfruit** oredict, even though it should only be an apple.

![image](https://user-images.githubusercontent.com/16440978/44635186-fdd32900-a967-11e8-961e-ade2de5d73a0.png)

Running mc 1.12.2, forge 14.23.4.2756, techreborn 2.17.1.786, crafttweaker 4.1.9

**Comment by modmuss50** [comment]
You can disable ore dict checking for recipes using `setUseOreDict`

See the wiki page here: https://wiki.techreborn.ovh/doku.php?id=development:mt#minetweaker_support

Let me know if you need help with it.

**Comment by EngineerXL** [comment]
It works perfectly for me
![image](https://user-images.githubusercontent.com/37447286/44948730-9582bc80-ae2b-11e8-9b11-16b71594cd86.png)
