### ISSUE TITLE
In servers, large machines can not be used.

### ISSUE THREAD

**Issue by Juncanthia** [TechReborn/TechReborn#1595]
Minecraft Version 1.710
TechReborn-1.7.10-0.7.21.1131-universal (Aug 20, 2018)
Forge-1614

Sorry，my English is poor, but I need to you help me solve this problem.
In single mode，I put the raw materials inside, the progress bar can move.
But in server ,I put the raw materials inside, however the progress bar don't move. Waiting for a long period there is still no output.

I hope you can solve my problem.Thanks!

**Comment by modmuss50** [comment]
1.7.10 is no longer supported (unless its a critical server crash, like the recent update).

Make sure you have the same configs/mods on both the client/server as the recipe may not exist on the server.
