### ISSUE TITLE
ArrayIndexOutOfBoundsException BuildersWand & Cable

### ISSUE THREAD

**Issue by yaroslav4167** [TechReborn/TechReborn#1596]
[https://paste.dimdev.org/seqecumake.mccrash](https://paste.dimdev.org/seqecumake.mccrash)

**Comment by modmuss50** [comment]
This has already been fixed, https://github.com/TechReborn/TechReborn/commit/c1be3fb765490cbddac96f8c4a90c1cec682b750

The fix has not been pushed as a release just yet.
