### ISSUE TITLE
Latest versions IC2 and TR crash occurs

### ISSUE THREAD

**Issue by BlayzerQ** [TechReborn/TechReborn#1598]
When installing the IC2 and TechReborn of the latest versions 1.12 crash occurs

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IndustrialCraft 2 (ic2)
Caused by: java.lang.NoSuchFieldError: inputFactory
	at ic2.core.IC2.load(IC2.java:193)

industrialcraft-2-2.8.97-ex112
RebornCore-1.12.2-3.10.0.332-universal
TechReborn-1.7.10-0.7.21.1131-universal
Forge 14.23.4.2758
[latest.log](https://github.com/TechReborn/TechReborn/files/2342821/latest.log)

https://gist.github.com/BlayzerQ/b24cff567e4d9576eb29802470cfacd4

**Comment by modmuss50** [comment]
Can you confirm that this only happens when only ic2 is installed without TR or other mods being in the pack?

**Comment by BlayzerQ** [comment]
Yes, only ic2 dont cause crash

**Comment by modmuss50** [comment]
Can you try updating to a newer forge version as you are using a very old version

**Comment by BlayzerQ** [comment]
Whoops, my bad. I`am install 1.7.10 version TR on 1.12. Sorry.
