### ISSUE TITLE
Crash when looking up the industrial grinder

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1599]
By simply looking up the industrial grinder in creative/when crafting my game freezes and then proceeds to crash. This problem doesen't affect other machines.
[crash-2018-09-02_15.54.35-client.txt](https://github.com/TechReborn/TechReborn/files/2343418/crash-2018-09-02_15.54.35-client.txt)

**Comment by modmuss50** [comment]
Can you make sure you have the latest version of reborn core

**Comment by modmuss50** [comment]
Looking at the versions please update TechReborn to fix the issue
