### ISSUE TITLE
[Suggestion]Allow machine recipe cutomization via minetweaker

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#160]
Just as the title suggests :)

**Comment by modmuss50** [comment]
you can, we just need documentation :) I will leave this open till we get it

**Comment by Carbon-Ghost** [comment]
you mean like the actual machine recipe or the machine processing recipe ? I guess the second one right ?

**Comment by gigabit101** [comment]
Techreborn has built in minetweeker support so anyone cam add recipes to are machines

**Comment by Carbon-Ghost** [comment]
Can they remove it though ? Also is that the file in the config ?

**Comment by gigabit101** [comment]
You need to use the minetweeker mod

**Comment by gigabit101** [comment]
But with minetweeker you can make new recipes to be used in the machines and remove any recipe from them

**Comment by modmuss50** [comment]
http://www.blamejared.com/modtweaker/

**Comment by modmuss50** [comment]
That file in the config does nothing but list them out, I should disable that
