### ISSUE TITLE
[Help Wanted] [Question] How to insert Biomes correctly in Blacklist

### ISSUE THREAD

**Issue by Draskh** [TechReborn/TechReborn#1600]
How do I insert the Biomes ID names correctly in the config file?
 
https://pastebin.com/gPdhUcg3 I tried this, but the .json is invalid.

**Comment by Prospector** [comment]
You need each biome in its own quotes. Like so:

`["minecraft:ocean", "minecraft:plains", "minecraft:desert"]`
