### ISSUE TITLE
Crash when nuke is blown up by an explosion

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1601]
When any type of explosion causes a nuke block to break, the game has a chance of crashing. This appears to be a random chance, but if you try it a few times you should get the crash.

Steps to reproduce:

1. Place a nuke in the world.
2. Place a block of TNT adjacent to the nuke.
3. Place a lever adjacent to the TNT, and flip it.
4. The TNT explodes, either causing a crash, or igniting the nuke.

[Crash Log](https://pastebin.com/cZ7iiNXx)

![2018-09-08_16 13 31](https://user-images.githubusercontent.com/22420959/45259483-002f7d00-b383-11e8-87e0-b01f55322faf.png)

**Comment by modmuss50** [comment]
Have you changed the config value for the fuze time?

**Comment by coderbot16** [comment]
I don't think so, here's the relevant section of my current config as a reference:
```
nuke {
    # Should the nuke explode, set to false to prevent block damage [Default=true]
    B:enabled=true

    # Nuke fuse time (ticks) [Default=400]
    I:fuse=400

    # Nuke explision radius [Default=40]
    I:radius=40
}
```

**Comment by modmuss50** [comment]
ah, ok. I think I see how its happened

**Comment by modmuss50** [comment]
ok, just tested it, @drcrazy fixed it a few days ago with https://github.com/TechReborn/TechReborn/commit/c56da8cf18fc7dc6dd53bf1d7cabc17fabeb6cf6 it will be included in the next release
