### ISSUE TITLE
Needs explanation text for "Configure Slots" GUI

### ISSUE THREAD

**Issue by douglasg14b** [TechReborn/TechReborn#1605]
The configure slots GUI doesn't explain itself. Why is there two red slots, what does each represent? What do the blue and red colors represent when clicking on the sides of the cube after click on a red slot?....etc

**Comment by modmuss50** [comment]
good suggestion, tool tips can be added to most of the things.

**Comment by douglasg14b** [comment]
@modmuss50 Another reason I'm asking is because I have no idea how it works, and the wiki ends with `I have made a video going over the basics of the system:` with no link.

**Comment by modmuss50** [comment]
Thats a fair enough comment, If I get a chance I might look into adding a dedicated page on the wiki for it.

The video is embedded right under that line of text.
