### ISSUE TITLE
[1.12.2] Wrong display name

### ISSUE THREAD

**Issue by TheSnowyChickens** [TechReborn/TechReborn#1606]
Hi, I think I don't need to explain the little issue. :) 

Iron Alloy Furnace:
![grafik](https://user-images.githubusercontent.com/29357962/45599617-11196780-b9ef-11e8-9e65-723cd3b98c03.png)

Iron Furnace:
![grafik](https://user-images.githubusercontent.com/29357962/45599622-2393a100-b9ef-11e8-9abf-ae7af8a922b8.png)

The GUI from the Electrical Furnace is okay, as example.

MC: 1.12.2
Forge: 2759
TR: 2.17.3.815
RC: 3.10.0.332

Yes, I have Optifine installed. And many other mods (150)

**Comment by modmuss50** [comment]
Are you using the default language? (en_US)?

**Comment by TheSnowyChickens** [comment]
Yes

**Comment by TheSnowyChickens** [comment]
Further blocks:
- Industrial Chunkloader

More I can't found, I looked through all machines. :)

**Comment by TheSnowyChickens** [comment]
Hello agian,
the "Industrial Chunkloader" still has this problem in TechReborn-1.12.2-2.17.4.824 + RebornCore-1.12.2-3.10.1.335-universal.
(the other 2 blocks are now correct)

![2018-09-24_01 45 59](https://user-images.githubusercontent.com/29357962/45934228-a7bfc880-bf9b-11e8-98c4-f9e2ee10c140.png)

**Comment by Prospector** [comment]
I didn't even know the chunk loader worked
