### ISSUE TITLE
No apparent way to handle the Fusion Reactor's output using the EU power system

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1607]
When support for the RF power system is disabled, there's no way for one to route the 1,000,000 EU/t possible output from the fusion reactor to any sort of machine, storage, or cable. The way GregTech solved this was with the Superconductorwire / Supercondensators, able to handle 1M EU packets and convert them down to 8192/2048 EU packets, but TechReborn does not have either of these. This may be a fringe feature as TechReborn is often used in an RF environment, and this only really applies to an EU environment, but would be nice to have nonetheless.

**Comment by modmuss50** [comment]
yeah, I see your point. Our own cables actually use FE so we would need to add a new cable that uses the EU power system from ic2.

In 1.7 this was quite easy, running in eu only mode is a bit of a pain to support as you can see. Dont expect to see this getting fixed soon, but it is a valid issue

**Comment by coderbot16** [comment]
I'm considering making a custom TechReborn addon to provide some features like this if they don't fit into the RF/FE focus. Luckily the issue isn't super pressing since the fusion reactor is the ultimate endgame goal of my pack, so there is time for myself to code in the feature as I don't imagine there will be any hopes of reaching endgame even within a few weeks of playing the pack.

**Comment by modmuss50** [comment]
I dont think this will get fixed by us as we are moving all the internal power over to FE slowly. I think having a separate IC2 addon with more cables will be the best option for solving this issue.

You could use an energy storage device such as an MFSU to store some more energy if needed.
