### ISSUE TITLE
(suggestion) more ores ?

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#1608]
I wondered if TechReborn would add more metals in the future, notably transition and post transition metals, without adding all the ton shit of metals and gems of GregTech, it would add more depth, interactions, and possibilities with TechReborn for making powerful tools, alloys, and use in machines. What do you think about it ?

**Comment by Prospector** [comment]
TR already adds a pretty absurd amount of ores so I think any future content will just continue to add uses to the existing ores, some of which are barely used at all.

**Comment by 0Navis0** [comment]
Well I understand your point of view, but some ores would deserved to be added and used in such a big tech mod. I notably think to Lithium, Sodium, Potassium, Rubydium, Cesium, Beylium, Calcium, Magnesium, Strontium, Baryum, Zirconium, Halnium, Vanadium, Niobium, Tantalum, Molybdemum, Mangnagnese, Rhenium, Ruthenium, Rhodium, Osmium, Palladium, Cadmium, Mercury, Boron, Aluminium, Gallium, Indium, Thallium, Silicium, Germanium, Antimony, Bismuth, Tellurium... which could be completed with materials like Phosphorus, Selenium, Iodine...
