### ISSUE TITLE
Game-Crashing Issue

### ISSUE THREAD

**Issue by araevingaming** [TechReborn/TechReborn#1609]
Multiple Machines have a missing tooltip error in JEI and when I tried to build one of the machines, my game crashed and got this crash log https://paste.ee/p/kZoZy

**Comment by modmuss50** [comment]
Can you check you have the latest version of reborn core AND TechReborn?

**Comment by modmuss50** [comment]
Please update TechReborn and Reborn Core and see if that fixes the issue

**Comment by modmuss50** [comment]
update RebornCore and TR
