### ISSUE TITLE
 Mod interaction issue: Liquid Duplication glitch involving BuildCraft Fragile Fluid Shards and Thermal Generators

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1610]
Steps to reproduce: 

1. Install BuildCraft, Reborn Core, and TechReborn.
2. Place down a BuildCraft tank, and place a bucket of lava into it.
3. Break the tank, releasing 2 fragile fluid shards with lava.
4. Place a lava fluid shard into the Thermal Generator.
5. Observe that the tank fills without draining the fluid shard.

Additional information: 
I originally reported this issue to BuildCraft (https://github.com/BuildCraft/BuildCraft/issues/4275), but they recommended that I report it here as well since it is not immediately clear which mod is responsible for the bug. 

Note that this is a liquid duplication glitch rather than just infinite energy as it is possible to extract fluid back from the Thermal Generator by placing empty fluid containers in the input instead of filled ones.

![2018-09-29_21 37 01](https://user-images.githubusercontent.com/22420959/46253403-e805c780-c42f-11e8-8ba6-e5961895ac8f.png)
![2018-09-29_21 37 15](https://user-images.githubusercontent.com/22420959/46253404-e9cf8b00-c42f-11e8-8bc2-1bbaffcbe7cf.png)

**Comment by modmuss50** [comment]
its odd that it works in some gens but not others, I will take a look at this.

**Comment by coderbot16** [comment]
I only tested it with the Thermal Generator, but I would assume it would work with all fluid generators due to the shared code.

**Comment by coderbot16** [comment]
Sorry, I was one version behind. After updating to the latest versions, the issue is gone. (https://github.com/TechReborn/RebornCore/commit/e7bab4f26030500c4d7e839e1e66034f95c04443). My issue was actually a duplicate of https://github.com/FTBTeam/FTB-Continuum/issues/369.
