### ISSUE TITLE
[Suggestion] Inclusion of Nano and Quantum Suits, Nuclear Reactors and more?

### ISSUE THREAD

**Issue by Spearkiller** [TechReborn/TechReborn#1612]
I'm sure we all remember the Nano and Quantum Suits from IC2, and I've always wondered why they weren't bought over to Tech Reborn, so... that's my suggestion. Potentially even a tier between Nano and Quantum and one above as well for an Insane Tier armor. The inclusion of the more general armor pieces like Night Vision Goggle, Rubber boots, and the Hazmat Suit would be nice to see as well (Despite the non-inclusion of the Nuclear set of machines, such as the Nuclear reactor and all that, which would give the Coolant items more of a use. It'd be nice to see a new way of making High Voltage that isn't just solar panels.)

If any of this has been discussed on the team or there's a specific reason as to why it's not in the mod i'd like to know please :)

**Comment by drcrazy** [comment]
There is only one reason for not having them in mod - there are no textures.

**Comment by Spearkiller** [comment]
If you haven't got an artist on hand, I mean, I'd be happy to help make them if you wanted to? 

I've tried using the Tech Reborn style before in my own personal texture packs, and I also have a sample of my own style as well, [shown in a small album here](https://imgur.com/a/FWw4Sfl), though I am by no means the best artist out there, but I'd be willing to do my best 😅

**Comment by modmuss50** [comment]
hi, @Spearkiller those textures look amazing 👍 nice work.

If you are willing to help us with textures that would be great as we have a lot of ideas but we wouldn't be able to make them look good so the help would be appreciated. 

Do you have discord so we can chat a bit with a bit more ease? Our server invite link is here: https://discord.gg/teamreborn

If not we can figure out another way to communicate.

**Comment by modmuss50** [comment]
Closing as this is in progress and will be merged into master when done.
