### ISSUE TITLE
Quantum chest and ME Sytem do not talk to each other properly

### ISSUE THREAD

**Issue by DevilAdvocate02** [TechReborn/TechReborn#1613]
![2018-09-23_21 08 47](https://user-images.githubusercontent.com/22227958/46568255-496bf000-c974-11e8-8849-580924847816.png)
![2018-09-23_21 09 14](https://user-images.githubusercontent.com/22227958/46568257-5557b200-c974-11e8-8ffe-a62d4d1c475c.png)

I have setup a Quantum chest wall directly linked via the Storage bus to the ME system but for some reason the correct quantity contained in the chest is not reflected in the system for example I have over 5 million iron ore in the chest but the system only shows 128.
I am trying to run this on the Continuum pack version 1.5.2

**Comment by modmuss50** [comment]
We use the commonly supported IDeepStorageUnit api to allow other mods to see large inventory's I dont believe AE supports this anymore. Sorry about that.
