### ISSUE TITLE
Alloy Smelter using specific ingots instead of direct ore dictionary.

### ISSUE THREAD

**Issue by Flanks255** [TechReborn/TechReborn#1614]
If the modpack uses Unidict, and the Tech Reborn ingots are removed from the oredict.
The Alloy Smelter will only take Tech Reborn Ingots, instead of any other mods(IE: TR copper vs TF copper).

Most likely from checking the oredict based off the ingot itself instead of by oredict name.

Using TR: 2.17.4.824

**Comment by modmuss50** [comment]
Ive started on this issue, this will now require each recipe to be changed over to use the oreDict name + the size.
