### ISSUE TITLE
java.lang.IllegalArgumentException: Duplicate id: TileLathe

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#162]
Seem that there is a conflict with advanced rocketry mod (http://minecraft.curseforge.com/projects/advanced-rocketry) that causes a crash on startup

http://pastebin.com/cMkFNRQ9

**Comment by covers1624** [comment]
All TileEntitys form TechReborn should have "TechReborn:" appended to the front of the name registered to avoid conflicts with other mods.

**Comment by gigabit101** [comment]
Yeah I did start doing that but forgot
