### ISSUE TITLE
Electric Furnaces do not properly sync their progress value when Overclocker upgrades are applied

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1621]
Issue in the title.

To reproduce:

 1. Place down an Electric Furnace connected to an adequate power supply.
 2. Add 2 overclocker upgrades to the furnace.
 3. Observe the progress indicator. It progresses at the normal slow speed, but only reaches the halfway point before smelting is complete.

It appears this was just an oversight since `TileElectricFurnace` doesn't extend `TileGenericMachine` like the other machines in the mod. I discovered this issue when trying to use the electric furnace code as the base to implement an Induction Furnace, and discovered the issue when I noticed that it did not properly sync its speed when heated up, since I changed the speed just by overriding the speedMultiplier based on the heat.

**Comment by modmuss50** [comment]
There are a few reasons why TileElectricFurnace does not extend TileGenericMachine.

- It uses minecraft's recipe list, and not our own custom recipe list that is used by all other machines

It may be possible for us to move to using it at a later date, but its going to be easier to fix these issues than doing that.

**Comment by coderbot16** [comment]
Ah, I see. In any case, that is the most probable reason for the bug, since the person implementing Overclocker upgrades most likely added the proper code to TileGenericMachine but just forgot to check the electric furnace edge case.

It seems like the easiest way to fix the issue is to just make `TileElectricFurnace::gaugeProgressScaled` take the speed multiplier into account.

**Comment by coderbot16** [comment]
(I'm not sure what just happened, I tried to post a reply and it kept on failing with a network error, I see it created a bunch of spam on discord but none of the created comments in the discord log actually exist here???)

**Comment by coderbot16** [comment]
Regarding the network errors, looks like GitHub is investigating some problems as of 10 minutes ago https://status.github.com/messages
