### ISSUE TITLE
Chargable items use FE even when TechReborn is in EU-only mode

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1625]
I disabled FE support for my modpack with the intent of isolating the RF and EU power systems from each other for balancing reasons. However, it appears that electric items unconditionally use CapabilityEnergy, unlike blocks which will conditionally disable it based on the config. This effectively nullifies the separation, since energy cells can be charged in storage units, and batteries can be charged in energetic infusers.

It appears that this is related to an issue that I've observed where batteries and the like are not chargable in IC2 energy storage units, so perhaps it is possible to make electric items use the IC2 power API as well which would allow both problems to be fixed.

**Comment by drcrazy** [comment]
Powered items from TR are RF based. Config values are in EU due to legacy reasons.
