### ISSUE TITLE
No GUI for Wind mills or solar panels.

### ISSUE THREAD

**Issue by 34486** [TechReborn/TechReborn#1626]
I don't know if its a bug or something not developed yet or if its not intended, but the GUI for the solar panels and the windmills, they don't exist. 
Thanks!

(I don't see any errors from TechReborn, so it MIGHT be intentional? Idk? If it is, can it be added :)?

**Comment by Prospector** [comment]
There is no GUI, but what would you want on it? I mean it would just be a power bar or something; doesn't seem terribly useful

**Comment by drcrazy** [comment]
Nothing to show there. Everything available on The One Probe tooltip.

**Comment by 34486** [comment]
Alright, wasn't sure. I was thinking it might have some indicator of what light level it is getting. 

Thanks.

**Comment by Prospector** [comment]
It isn't based off light level; it either has view of sun straight above or not. It *should* have a texture that shows if it's on or not.

**Comment by coderbot16** [comment]
If the solar can see the sun the indicator on the sides of the block will light up, yeah. IC2 / Advanced Solars did have GUIs for their solar panels, but the only purpose of them was for charging items, basically a glorified batbox with a sun indicator.
