### ISSUE TITLE
[Suggestion] Tooltips

### ISSUE THREAD

**Issue by Hunter00064** [TechReborn/TechReborn#1627]
Not sure where we could post suggestions, but it would be nice to have more tooltip info like transfer rate on cables.

And I would like something that was from IC2, machines exploding if incorrect voltage was inputted. And tooltips for each machine to specific what input it needs/takes

**Comment by drcrazy** [comment]
I\o rates are in The One Probe tooltip. Do you have it?

**Comment by Hunter00064** [comment]
I do have probe, but I prefer it if it were in inventory tooltip/description and for people who prefer waila/wawla

**Comment by Hunter00064** [comment]
I think what I said in the posted suggestion was wrong, not in tooltip but under it but above the mod name, kinda like how Thermal Expansion has RF/T in its fluxduct descriptions

**Comment by drcrazy** [comment]
ok, I'll check

**Comment by drcrazy** [comment]
Machines are already having tier in tooltip. Cables got one. Explosions are there if machines are getting power from IC2 cables\blocks.
