### ISSUE TITLE
Solar panels not generating

### ISSUE THREAD

**Issue by HexFlareheart** [TechReborn/TechReborn#1628]
We just updated to the latest version of Tech Reborn today, on a server I'm running, and all of our solar panels appear to have completely ceased functioning. None of them appear to be generating any energy; we've tried having them output into multiple types of power transmission (including regular glass fibre cables, which my entire personal setup is based around), and they seemingly don't operate at all, regardless of time of day. Creative solar panels still work, but I'm assuming that's probably because they're solar panels in name only.

We're running a complex mod setup, but I went ahead and tested on a completely clean setup (same versions of reborncore and techreborn, with no other mods installed on a brand new profile), and they still didn't work, so as far as I know it's not related to any other mods in use.

**Comment by LegendLZD** [comment]
Perhaps reborncore causes the bug.
Looks like we should degrade reborncore version to fix the bug.
And I hope the next reborncore version will fix it

**Comment by modmuss50** [comment]
I will look at this issue as soon as I have time, thanks for opening an issue.
