### ISSUE TITLE
Scrapbox-inator recipe

### ISSUE THREAD

**Issue by bigenergy** [TechReborn/TechReborn#1631]
MineCraft 1.12.2
TechReborn-1.12.2-2.17.7.840

**Cannot be crafted, as recipes entered incorrectly**

![screenshot_8](https://user-images.githubusercontent.com/17977139/48317369-12879a80-e602-11e8-972d-6b4726ba9202.png)
![screenshot_9](https://user-images.githubusercontent.com/17977139/48317371-17e4e500-e602-11e8-8706-26f782e5e176.png)
![screenshot_10](https://user-images.githubusercontent.com/17977139/48317372-19aea880-e602-11e8-9ef4-1b0e95e9a776.png)
![screenshot_11](https://user-images.githubusercontent.com/17977139/48317482-1a483e80-e604-11e8-892a-cfc98b0a3385.png)

**Comment by bigenergy** [comment]
Waste material cannot be obtained without a Scrapbox-inator

**Comment by drcrazy** [comment]
Please, use Recycler (Переработчик) to get scrap (Утильсырье).
