### ISSUE TITLE
Industrial Centrifuge gives too much copper and tin from bronze centrifuging

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1632]
Centrifuging a single bronze dust produces 2 tiny piles of tin dust, and 6 tiny piles of copper dust. It should only produce 1 pile of tin and 3 piles of copper, or consume 2 bronze dust.

https://imgur.com/a/d9MElNG

**Comment by drcrazy** [comment]
Same as in original GT. (http://feed-the-beast.wikia.com/wiki/Industrial_Centrifuge) Alloys are centrifuged with less loss compare to non-alloy metals. Compare with brass and electrum. 

Feel free to change recipe using crafttweaker for particular mod pack reasons. CT doc is here: https://wiki.techreborn.ovh/doku.php?id=development:mt#centrifuge

**Comment by coderbot16** [comment]
Is this in relation to the 3 copper / 1 tin => 2 bronze recipe that old GT used, or in relation to the 3 copper / 1 tin => 4 bronze recipe that most current mods use? The old GT recipe returned 2x only because the standard bronze recipe was 3C + 1T=> 2B, since that made sense. 

If TechReborn does use the halved bronze recipe as its standard, then I can change the recipe in my own pack. I just thought this was not intended since it can be used to duplicate copper and tin in combination with Thermal Expansion.
