### ISSUE TITLE
I broke it again...

### ISSUE THREAD

**Issue by LocalBoomer** [TechReborn/TechReborn#1633]
I think this one is missed "update markers" somewhere idk...

https://paste.dimdev.org/fupebaqozi.mccrash

**Comment by modmuss50** [comment]
Do you have any custom crafttweaker scripts? Does it work with the none beta version of TechReborn?

**Comment by LocalBoomer** [comment]
Wait.. I think I had an outdated reborn core testing with the new one now

Edit 1: Sorry I have 450+ mods in this pack loading takes a while... (nearly 10 mins now)

**Comment by LocalBoomer** [comment]
Yeah loaded to main menu this time so I think it was just an outdated RebornCore. Sorry about that

**Comment by modmuss50** [comment]
No worries, gald you got it sorted. Thanks for testing. This new version of TR is beta for a reason so please let me know if things arent working correctly.

**Comment by LocalBoomer** [comment]
No, no thank you for the awesome mod! happy to test for you :)
