### ISSUE TITLE
IC2 Classic support

### ISSUE THREAD

**Issue by Todorxd** [TechReborn/TechReborn#1634]
Hey,
I wanted to add your mod to my Mod Pack but I found out that your mod doesn't really like IC2 Classic. When I start the game it just crashes and I would love to have both, your mod and IC2 Classic in my mod pack. Here's the crash log:
[crash-2018-12-03_16.42.43-client.txt](https://github.com/TechReborn/TechReborn/files/2640224/crash-2018-12-03_16.42.43-client.txt)

**Comment by modmuss50** [comment]
in progress, will be done soon.

The major blocker is not having any contact to the dev, or the ability to run the mod doesn't help.
