### ISSUE TITLE
World Interaction [SUGGESTION]

### ISSUE THREAD

**Issue by Feranogame** [TechReborn/TechReborn#1635]
I'm really liking Tech Reborn, but there is a problem: Tech Reborn things just do more Tech Reborn things, like a clicker game. It does not interact with the world and in the end the machines do nothing, just more machines. Tech Reborn has a really good system but it is wasting its potential. It could have automatic farms, more gear, even tree farms, item generators, etc. The only "useful" item is UU Matter but it just do some basic things. I think Tech Reborn should have more stand-alone potential as it isn't a really "friendly" with other tech mods.

EDIT: There are more "useful" items, but it stays the same, nothing special at all.

**Comment by modmuss50** [comment]
You are correct, I would love to add loads of new machines and tools that are useful.

We are currently working on modular armor that has upgrades.

A new fission reactor is planned.

This has only just come about due to us finding a new texture artist. Things are progressing slowly.
