### ISSUE TITLE
Config Request

### ISSUE THREAD

**Issue by Damien-Reave** [TechReborn/TechReborn#1637]
At the moment, two machines (Industrial Centrifuge and Industrial Grinder) have a secondary slot that is intended for a specific item, and other items cannot be placed into that slot. I'm hoping that a config setting can be set which will allow for modpack creators to disable this and use both input slots for various items in their custom recipes.

**Comment by modmuss50** [comment]
You should be able to put anything there?

https://wiki.techreborn.ovh/doku.php?id=development:mt#centrifuge

takes 2 inputs? Can you give me an example recipe that doesnt work?

**Comment by drcrazy** [comment]
Hi Damien-Reave, 

second input slot for Industrial Grinder dedicated to fluid containers. Same for centrifuge.
