### ISSUE TITLE
Invalid Inputs

### ISSUE THREAD

**Issue by bookerthegeek** [TechReborn/TechReborn#1638]
# Heyo # 
How are you doing today? Updated TechReborn to the latest on curse and suddenly my wip pack is not loading. So sad. After much restarting and disabling of mods and gnashing of teeth I've narrowed it down for you to an interaction between your amazing mod and one on the other end of the spectrum (Tech spectrum. It is also pretty amazing.)
### Mod List ###
- BetterWithMods 3.19-1017
- Forge 14.23.5.2784
- Minecraft 1.12.2
- RebornCore 3.12.0.378
- TechReborn 19.0.870
### [Crash Report](https://gist.github.com/bookerthegeek/046cd4b5ebf87b4554dbff800d14995b) ###
```
java.security.InvalidParameterException: input is invalid!
	at techreborn.api.recipe.BaseRecipe.addInput(BaseRecipe.java:137)
	at techreborn.api.recipe.machines.VacuumFreezerRecipe.<init>(VacuumFreezerRecipe.java:36)
	at techreborn.init.ModRecipes.addVacuumFreezerRecipes(ModRecipes.java:329)
	at techreborn.init.ModRecipes.init(ModRecipes.java:93)
	at techreborn.Core.registerRecipes(Core.java:133)
```
### Additional Info ###
I'll be reporting this to the dev's of BWM also. Link to GitLab issue [HERE](https://gitlab.com/BetterWithMods/BetterWithMods/issues/1281).

**Comment by modmuss50** [comment]
Intresting I’ll take a look when I get a chance

**Comment by modmuss50** [comment]
BWM fixed it.
