### ISSUE TITLE
[Suggestion]Allow changing machine recipes processing time / eu requirement in techRebornRecipes.json

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#164]
Just like the old GT

**Comment by modmuss50** [comment]
that file has been disabled, as it did nothing. use MT instead for now. But I may implement that as its a good idea.

**Comment by Carbon-Ghost** [comment]
Syntax pretty please ? :/ 

Do we also require ModTweaker ? Just as a useful side information in case of problems ^^

**Comment by modmuss50** [comment]
You can find it here http://www.blamejared.com/modtweaker/

**Comment by modmuss50** [comment]
No mod tweaker is needed

**Comment by Carbon-Ghost** [comment]
kk

**Comment by gigabit101** [comment]
there is no need we have MT support
