### ISSUE TITLE
Rolling Machine tries to charge from its 3rd input slot

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1645]
While testing my energy support patches I discovered that the Rolling Machine was not discharging batteries. While this initially spooked me, since I thought that I had broken something, I tested other machines and they seemed to work fine. Inspection of the source reveals that the GUI has the energy slot as index 10, but the charge code has the energy slot as index 2. While index 2 in many machines is the energy slot, the rolling machine is a special case since 0-8 are input slots.

Relevant source code locations:

* Call to TilePowerAcceptor#charge https://github.com/TechReborn/TechReborn/blob/b399e211faf74c98bf1ea386a20cef7590d7e418/src/main/java/techreborn/tiles/tier1/TileRollingMachine.java#L118
* Charge slot assignment in ContainerBuilder https://github.com/TechReborn/TechReborn/blob/b399e211faf74c98bf1ea386a20cef7590d7e418/src/main/java/techreborn/tiles/tier1/TileRollingMachine.java#L337

![2018-12-27_22 55 17](https://user-images.githubusercontent.com/22420959/50505877-c5814b80-0a2a-11e9-8932-a4a4c6c62a33.png)

**Comment by drcrazy** [comment]
Thank you for spotting!

**Comment by coderbot16** [comment]
You're welcome! 👍
