### ISSUE TITLE
Crash with auto crafter

### ISSUE THREAD

**Issue by Snownee** [TechReborn/TechReborn#1646]
https://paste.dimdev.org/amonosaboj.mccrash

**Comment by drcrazy** [comment]
Any reasons why you use not latest reborn core?

**Comment by Snownee** [comment]
I have tested with latest RebornCore and it occurred too.

**Comment by modmuss50** [comment]
Part of the crash log seems to be missing, and for some reason the crash log is mapped? 

Are you running this in a dev env? Or do you have a mod that changes the crashlog? Can you try without mods that alter the crashlog and see what you get?

**Comment by Snownee** [comment]
I cannot reproduce this crash somehow (using Reborn Core 3.12.0 or 3.12.1) sorry : (

Not dev env. No that kind mod I think.

**Comment by furtabs** [comment]
This is most certiantly still a bug

**Comment by furtabs** [comment]
https://pastebin.com/xJVyYVen

My team members known about it for ages but " I have not had the time to report it " but has time to write a craft tweaker script

**Comment by Snownee** [comment]
Not the same issue
