### ISSUE TITLE
Recipe deduplication issues, UniDict compat.

### ISSUE THREAD

**Issue by LumberWizard** [TechReborn/TechReborn#1649]
These are actually two issues, both of which have to do with recipe deduplication:
1. With recipe deduplication enabled, the compressor from TR is unobtainable, however recipes for plates for the gems and such are not added to the IC2 compressor (though the Thermal Expansion Compactor and NuclearCraft compressor or whatever it's called does get the recipes, and the metal press from Immersive Engineering gets a few of them as well).
2. With UniDict installed and deduplication enabled, refined iron seems to only be available from the TE induction smelter, and anything that calls for refined iron plates seems to need steel plates instead. A solution could be to just use iron and iron plates for everything, or make recipes that allow for additional compat with UniDict for refined iron with deduplication.

**Comment by modmuss50** [comment]
1) I could add all TR compression recipes to IC2
2) I re-enabled refined iron, I could add a recipe for it?

**Comment by modmuss50** [comment]
Fixed #2 with https://github.com/TechReborn/TechReborn/commit/0228d721792e00259594bfd680ed4a0ab120d972

I will look into #1
