### ISSUE TITLE
[Bug] GUI Bug

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1650]
TechReborn 1.12.2-2.19.1.877
RebornCore 1.12.2-3.12.1.385
Forge 1.12.2 - 14.23.5.2796

![image](https://user-images.githubusercontent.com/12701912/50605207-e2ea6580-0ec1-11e9-8f50-c21e9ed93c6f.png)

**Comment by Skillotic0703** [comment]
![image](https://user-images.githubusercontent.com/12701912/50605975-61e09d80-0ec4-11e9-87c7-4cd431373020.png)

**Comment by modmuss50** [comment]
![java_2019-01-03_13-39-41](https://user-images.githubusercontent.com/4324090/50640532-0dd5c780-0f5d-11e9-8988-39630324db87.png)

![java_2019-01-03_13-40-04](https://user-images.githubusercontent.com/4324090/50640547-1b8b4d00-0f5d-11e9-84ed-8e23d97de3a3.png)

Fixed recently in dev builds.
