### ISSUE TITLE
Industrial Sawmill uses wrong units in JEI

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1654]
In JEI, the industrial sawmill says that all recipes take 128FE/t when they really take 128EU/t. 

On another note, it looks like the TR Industrial Sawmill is worse than even the GT2 sawmill since the TR sawmill takes 2x the energy (4x the EU/t and 1/2 the time). In its current state, the TR sawmill takes 30 times the energy of the TE sawmill to do virtually the same thing, convert 1 log into 6 planks + and some sawdust.

**Comment by coderbot16** [comment]
For the second part, I'm not suggesting to make the TR sawmill the same as the TE sawmill, I'm just saying it would be nice to close the gap a bit. You could make it draw 32EU/t (still have an input rate of 128EU/t) and operate for 5 seconds, meaning it would take 3.2K EU (12.8K FE equivalent), making it take 8.5x the energy instead of over 30x the energy.

**Comment by drcrazy** [comment]
there is a config option to change amount of planks per log. One can set it to 60 per log )
