### ISSUE TITLE
Make TR wrench work on IC2 blocks

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#1658]

**Comment by StoneLegion** [comment]
Not sure if this is possible and in the scope. But could you also make IC2 Wrench work fully on TR Blocks?

**Comment by modmuss50** [comment]
What do you mean @KaneHart, it should work just fine?

**Comment by StoneLegion** [comment]
Ahh right now you can't shift + right click the TR machines to pop them. All it does is spin them around like it normally does without shift + part. I could make a new ticket for it if you like. Sorry did not mean to hijack this one.

**Comment by coderbot16** [comment]
I don’t think what you did is considered “hijacking”, both refer to the general issue of ic2/tr wrench compatibility.

**Comment by modmuss50** [comment]
Fixed, all wrenches should work everywhere now
