### ISSUE TITLE
Ender Pearl Abuse

### ISSUE THREAD

**Issue by catemiko** [TechReborn/TechReborn#1659]
Ender pearl abuse with EnderIO pearl dust.
![image](https://user-images.githubusercontent.com/28825932/51845657-88221d80-234a-11e9-92d8-3aee1ece3587.png)

**Comment by modmuss50** [comment]
I think in this case its going to be best for the pack dev to fix. I dont want to start removing recipes from ender io. If you have a better suggestion let me know.
