### ISSUE TITLE
Blast furnace recipe added via minetweaker must have 2 input materials

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#166]
For example, the folloing expression will work
mods.techreborn.blastFurnace.addRecipe(<techreborn:ingot:28>, null, <techreborn:dust:81>, <IC2:itemDust:2>, 9000, 120, 2500);

And the following will not
mods.techreborn.blastFurnace.addRecipe(<techreborn:ingot:28>, null, <techreborn:dust:81>, null, 9000, 120, 2500);

Is my grammar wrong or there is a bug?

**Comment by modmuss50** [comment]
It looks like a bug

**Comment by modmuss50** [comment]
It was working with:
```
    mods.techreborn.blastFurnace.addRecipe(<techreborn:ingot:28>, null, <techreborn:dust:81>, null, 9000, 120, 2500);
```

**Comment by wormzjl** [comment]
nice, but it seems that you repeated this 2 times in the commit :P
        PlateCuttingMachineRecipe r = new PlateCuttingMachineRecipe(oInput1, MinetweakerCompat.toStack(output), ticktime, euTick);
        PlateCuttingMachineRecipe r = new PlateCuttingMachineRecipe(oInput1, MinetweakerCompat.toStack(output), ticktime, euTick);

**Comment by modmuss50** [comment]
I know, I forgot to saved, it was fixed in the next commit https://github.com/TechReborn/TechReborn/commit/cb6551c7ca3ba1b15ed6de53c587da14e65e23e0
