### ISSUE TITLE
Overclocker scaling is very different compared to IC2

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1662]
A while back I was working on a mod that was a TechReborn equivalent of AdvancedMachines. However, I realized that all of my machines were outclassed by TR machines with 4 overclockers.

Investigation into the speed and power scaling algorithms reveals that while the power scaling is exponential, the speed scaling is... confusing. Here is the scaling to my understanding:

 * 1 overclocker: 1.33x (1/0.75)
 * 2 overclockers: 2x (1/0.50)
 * 3 overclockers: 4x (1/0.25)
 * 4 overclockers: 100x (1/0.99)

I propose adding a config option for an alternative speed scaling method that matches the basic exponential method used for power scaling. If you'd like, I can make some PRs to TR and RC to add the config option.

**Comment by modmuss50** [comment]
I dont know how ic2 does it, but ours is very rough and not a lot of thought went into it.

Would it be worth replacing our current scaling? I dont want the machines to feel slow or under-powered however.

**Comment by coderbot16** [comment]
The was IC2 does it is it makes the speed multiplier 0.7^n and the power multiplier 1.6^n (where n is the number of overclockers). For example, 1 overclocker is 70% speed / 160% power, 2 is 49% speed / 256% power, 3 is 34% speed / 410% power, and so on.

The main concern with outright replacement of the scaling is if it breaks builds based on the super fast machines, which is why I was thinking of the config option.

Slowness/underpoweredness might be an issue because unlike IC2, TR overclocker upgrades don't stack. With IC2 you can have 64 overclockers in 1 machine, but in TR you can have only 4 at maximum. Perhaps we could either make upgrades stack up to 16 inside machines, or introduce compacted versions of the upgrades?

**Comment by coderbot16** [comment]
Just so you know, https://github.com/TechReborn/RebornCore/pull/104 would fix this issue.

**Comment by modmuss50** [comment]
PR was merged.
