### ISSUE TITLE
IC2 Experimental Version & TR Comparability issues.

### ISSUE THREAD

**Issue by StoneLegion** [TechReborn/TechReborn#1665]
This is going be kind of a wall and a mess. I honestly was starting to get overwhelmed. Rather just fix them all via CraftTweaker my 2nd time around I thought I report them here. 

Bug Reports:
Tech Reborn:

- [x] Refined Iron should not exist in recipes / creation of them. It also shows IC2 Refined Iron when you enable compatibility as well. 
- [x] Recipes that would need to be fixed to steel or say iron plate, etc would be: Iron Fence, Iron Alloy Furnace, Sawmill, Kanthal Heating Coil, as these don’t have working recipes without using refined Iron. 
- [x] Basic / Advance Machine Frame’s should not exist as IC2 has its own. The recipe exists to make it as well as converting ic2’s into it.
- [ ] When breaking a TR Machine it should give you back an IC2 Frame instead of the TR versions for Basic / Advance. 
- [x] Compressed Air Cell from TR should be allowed to be extracted in IC2 Extractor. Right now no TR cell’s can be extracted. IC2 only allows in their version to extract Air Cell as well. Because TR Deals with so many cell’s it would not be a big deal if all cell’s were extracted though some might not want that.
- [x] Industrial Centrifuge: 16 TR Rubber Wood to 8 TR Sap should be changed to IC2 as well as 4 TR Sap to 14 TR Rubber
- [x] IC2 Rubber to TR Rubber recipe should be removed.
- [x] Tech Reborn “Battery” Should be removed and only allow IC2’s Re-Battery Instead.
- [x] Tech Reborn “Energy Crystal” Should be removed and only allow Energy Crystal Instead.
- [x] Tech Reborn “Lapotron Crystal” Should be removed and only allow IC2’s Lapotron Crystal Instead.
- [x] Couple of recipes show TR’s Carbon Plates and they can’t be crafted as were using IC2’s version. Like Advance Machine Casing that should not exist anyways and TR Nanosaber
- [x] Remove All Blocks to Plates Recipes via the IC2 Compressor. Not only this makes it easy to make plates that should only be used via IC2 Cutter / Metal Former it also creates a duplicate copy.

**Comment by modmuss50** [comment]
What ic2 configs are you using?

Are you using ic2 classic, and what setting is trs compat mode set to?

**Comment by drcrazy** [comment]
> Remove All Blocks to Plates Recipes via the IC2 Compressor. Not only this makes it easy to make plates that should only be used via IC2 Cutter / Metal Former it also creates a duplicate copy.

Already done via config

**Comment by modmuss50** [comment]
Mostly fixed, not seen any issues in a while with this.
