### ISSUE TITLE
New version crashes with Forestry 3.6.X

### ISSUE THREAD

**Issue by Rongmario** [TechReborn/TechReborn#167]
http://hastebin.com/gutebuzulu.coffee

**Comment by Rongmario** [comment]
+        System.out.println();
+        if(!Version.VERSION.split(".")[0].equals("4")){
+            CompatManager.INSTANCE.compatModules.remove(this);
+        }

This is where is going wrong, I'm guessing is this:
if(!Version.VERSION.split(".")[0].equals("4"))

**Comment by modmuss50** [comment]
I dont think we can support forestry 3.x.x

**Comment by Rongmario** [comment]
Closing issue since forestry version checker is removed - will reopen if this happens IF another check is implemented later
