### ISSUE TITLE
[Suggestion] Change Vacuum Freezer Multiblock

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1672]
I think the Vacuum Freezer multiblock should be changed to how it was in the FTB Ultimate days because it's currently too easy to make.
Could you please change the multiblock to this instead: https://ftb.gamepedia.com/Vacuum_Freezer_(GregTech_4)

**Comment by Skillotic0703** [comment]
![image](https://user-images.githubusercontent.com/12701912/53351996-52a92980-3922-11e9-8ce7-5e716e47adb3.png)

**Comment by modmuss50** [comment]
Yeah, 1.13 this can happen, dont want to break worlds this late into 1.12

**Comment by coderbot16** [comment]
Maybe it would be possible to do something like with the overclocker scaling - make a config option to use the proper structure that is false by default for 1.12 compatibility

**Comment by modmuss50** [comment]
Yeah, that could work.

**Comment by drcrazy** [comment]
1.12 has it toggle off via config in machines.cfg. A little bit different structure compare to GT4. Reinforced casings top & bottom and advanced casing for middle.
