### ISSUE TITLE
Make Shift-clicking upgrades into a Recycler not put excess into the input slot

### ISSUE THREAD

**Issue by MyNameIsKodos** [TechReborn/TechReborn#1675]
I'm using TechReborn version 2.18.1.863 and when I shift click a stack of more than 4 overclock upgrades into a recycler, the first four go into the proper slots, but the rest of the stack gets eaten by the newly upgraded recycler before I can get a chance to remove them.

**Comment by modmuss50** [comment]
Fixed, will be in the next update. Ensure you update reborn core as well.
