### ISSUE TITLE
Consider adding a machine that fills cells and other cotainers with fluid.

### ISSUE THREAD

**Issue by levicc00123** [TechReborn/TechReborn#1683]
Something similar to the Fluid transposer from Thermal Expansion, or Forestry's bottler is what I want.

**Comment by modmuss50** [comment]
Nice idea, should be easy to add, not sure when ill get around to add it but I have some ideas.

**Comment by drcrazy** [comment]
Gimme textures, plzz )

**Comment by gdm413229** [comment]
Could be known as the Fluid Canner if added in.

**Comment by Prospector** [comment]
Don't tanks do this?

**Comment by gdm413229** [comment]
Tanks can fill cells with fluid, the fluid canner could be an expert-mode exclusive machine.  When expert mode is active, you can't fill the cells with fluid via tanks and the world ... as the cells have to be filled with vacuum prior to filling.

**Comment by drcrazy** [comment]
Thermal and EFab tanks only can fill cells if you click with cell on them. Thus if you need to fill several stacks it becomes not so handy.

**Comment by modmuss50** [comment]
In theory the quantum tank can do this now, I think it has slot configuration.

**Comment by voidsong-dragonfly** [comment]
The quantum tank is a bit late to have it though. Maybe a 32 bucket tank that does this? Been looking for this exact functionality.

**Comment by jusvit** [comment]
> The quantum tank is a bit late to have it though. Maybe a 32 bucket tank that does this? Been looking for this exact functionality.

Possible functionality could be added in #1576 ?

**Comment by Prospector** [comment]
This was implemented with the lower tier tanks
