### ISSUE TITLE
IOreDictEntries can't be assigned amount through CT

### ISSUE THREAD

**Issue by Yoghurt4C** [TechReborn/TechReborn#1684]
![image](https://user-images.githubusercontent.com/11313954/53998281-39894f80-4150-11e9-86f3-c4cd717cb7e8.png)
![image](https://user-images.githubusercontent.com/11313954/53998288-4312b780-4150-11e9-86bd-3595bd9aa0dd.png)
assigning amount to IItemStacks works as expected, however
TR 2.21.0.951
CT 4.1.15

**Comment by modmuss50** [comment]
Sadly this is going to be a lot of work to fix and most likely not worth the effort at least in 1.12. For now just use standard item stacks
