### ISSUE TITLE
[1.12.2] Crash on creating multi-block structure (repro w/ blast furnace)

### ISSUE THREAD

**Issue by vladbarcelo** [TechReborn/TechReborn#1685]
Title. Got a server crash while completing a blast furnace multi-block structure.

TR Version: TechReborn-1.12.2-2.20.13.940-universal
RC Version: RebornCore-1.12.2-3.13.0.400-universal
[Crash log](https://pastebin.com/1rKpR8LR)
[Config](https://pastebin.com/EPBkMERZ)

**Comment by modmuss50** [comment]
Update Reborn Core and TechReborn

**Comment by vladbarcelo** [comment]
Fixed, thanks.
