### ISSUE TITLE
Implosion Compressor wont form or accept form

### ISSUE THREAD

**Issue by Solverbolt** [TechReborn/TechReborn#1689]
![2019-03-17_03 31 32](https://user-images.githubusercontent.com/38087746/54489033-6b439a00-4865-11e9-97af-b998137543fb.png)
![2019-03-17_03 31 40](https://user-images.githubusercontent.com/38087746/54489034-6b439a00-4865-11e9-98b1-7aa1152e6536.png)
![2019-03-17_03 32 00](https://user-images.githubusercontent.com/38087746/54489035-6b439a00-4865-11e9-8d5f-f3d49e88399f.png)
![2019-03-17_03 32 12](https://user-images.githubusercontent.com/38087746/54489036-6b439a00-4865-11e9-8341-9634cecf9ce6.png)
![2019-03-17_03 32 14](https://user-images.githubusercontent.com/38087746/54489037-6b439a00-4865-11e9-811c-5dfed4279afa.png)

Followed the layout, both using the hologram that the machine produces and following the Wiki. Does not form, cannot be used.

**Comment by coderbot16** [comment]
TR is slightly different than GT in this case, you need to replace the 8 standard casings with reinforced casings. This should help: [Wiki Page](https://wiki.techreborn.ovh/doku.php?id=blocks:implosion_compressor)

**Comment by coderbot16** [comment]
Could you send a screenshot of the hologram? If there is an issue with that it would definitely be something that needs to be fixed.

**Comment by modmuss50** [comment]
Use the hologram, it might help you.

![2019-03-17_14 58 39](https://user-images.githubusercontent.com/4324090/54493227-4bdc5980-48c5-11e9-87db-9ce6d6b38d0f.png)

![2019-03-17_14 59 03](https://user-images.githubusercontent.com/4324090/54493230-50087700-48c5-11e9-9cb1-ac5c43a934ad.png)

![2019-03-17_14 59 02](https://user-images.githubusercontent.com/4324090/54493232-55fe5800-48c5-11e9-97e8-54301a899135.png)
