### ISSUE TITLE
macerator easy recipe

### ISSUE THREAD

**Issue by bear989** [TechReborn/TechReborn#169]
when running IC2 Exp #780 with hard recipe enabled

**Comment by bear989** [comment]
after more testing this is do to some other mod blocking it. when just running IC2 and Techreborn it's the hard recipe

**Comment by Rongmario** [comment]
mod list please?

**Comment by Rongmario** [comment]
Check with Immersive Engineering in your pack :)

**Comment by bear989** [comment]
I do have IE, but it is also in the new pack without the issue, only maan
change is updated forestry and removed rekia's mods, my guess is another
Rekia issue

**Comment by Rongmario** [comment]
So you do have Reika's Mods?

**Comment by bear989** [comment]
I rebuilt the pack without reika's and the recipe works, without and older
version it doesn't, this is the old pack here I have the easy recipie

**Comment by Rongmario** [comment]
Ok, thanks for the information!

**Comment by bear989** [comment]
your welcome, I rebuilt the pack cause of a fluid handler issue keeping me
from updating your mod in the old pack, the pack and series is based on
Techreborn so Reikia had to go

**Comment by Rongmario** [comment]
For your information: I'm not the mod creator, I'm just a kind guy helping haha - the mod creator looks bit stressed so I'm helping him decipher the problems. I even referenced your issue in Reika's issue tracker - thanks :+1:

**Comment by bear989** [comment]
opps missed the name change on the emails, thanks for the help

**Comment by Rongmario** [comment]
No worries ^_^

**Comment by ReikaKalseki** [comment]
Who is the developer of Tech Reborn? I have never heard of it, much less added code for it.

**Comment by modmuss50** [comment]
Me and @gigabit101 are the main developers.

**Comment by bear989** [comment]
ok, great job with the mod so far, keep up the good work! are you guys
gonna spliy up the ore gen a bit eventually?

**Comment by ReikaKalseki** [comment]
OK....do you have any ideas?

**Comment by Rongmario** [comment]
You must of had fiddle with IC2?

**Comment by modmuss50** [comment]
Can you confirm that is one of @ReikaKalseki mods?

**Comment by Rongmario** [comment]
@bear989 please reply, pretty urgent to have mod compatibility fixed

**Comment by bear989** [comment]
I can do some testing, but no at the time I cant confirm it was the issue,
It just was the onlt mods I removed when the problem stopped

**Comment by bear989** [comment]
I apologize to Reikia, it seems after testing this was a issue in
Techreborn itself. builds 873 - 878 wiith IC2 exp gave easy recipe with
hard mode selected. after updating to 891 the recipe was back to hard
again. I must have removed DragonAPI and updated at the same time, giving
false results.

**Comment by ReikaKalseki** [comment]
...
