### ISSUE TITLE
[Suggestion] Superconductor cables and supercondensator [ultimate transformer]

### ISSUE THREAD

**Issue by gdm413229** [TechReborn/TechReborn#1690]
The original GregTech mod for MC 1.4.7 had the superconductor cables which were the best cables when it comes to transferring ultra-mega-high voltage power across long distances.  Those cables could be invaluable for fusion power plants alongside the supercondensator, which is the top-tier transformer.  Supercondensators accept EU packets up to 2.147 billion units via it's high voltage side and steps the packets down to 8192 or 2048 EU per packet on it's low voltage sides.

**Comment by modmuss50** [comment]
Mostly done with this: https://github.com/TechReborn/TechReborn/commit/1d78c60e51cc834de0d9b69a746172430f328b93

The aesu can be used as a transformer for now.
