### ISSUE TITLE
Industrial Blast Furnace misreporting tier when fitted with transformer upgrades

### ISSUE THREAD

**Issue by xenoflot** [TechReborn/TechReborn#1694]
TR 2.21.2.960
TR Compat 1.0.0
RB Core 3.13.8.430
Forge 14.23.5.2815

Hi folks,

Playing Sky Odyssey with the above mod versions.

I have a bunch of Quantum Solars so my power supply is Extreme. My Industrial Electrolyzer's power bar reports Extreme tier with 2 transformer upgrades in it, but my Industrial Blast Furnace does not.  It's just reporting Medium regardless of the number of transformer upgrades in it.

Having already blown up one machine, it was a very nervous moment taking a leap of faith and connecting it with only 2 transformers. No boom, phew! If this hasn't already been addressed, it'd be great if it could be.

Thanks!

**Comment by drcrazy** [comment]
No worries it is cosmetic only. Transformers upgrades are working fine for Industrial Blast Furnace.
