### ISSUE TITLE
OpenComputers Integration

### ISSUE THREAD

**Issue by MyNameIsKodos** [TechReborn/TechReborn#1696]
When hooking up a TR machine to an OpenComputers Computer via an OC Adapter, all TR devices show up as `tr_machine`

I am opening this issue at modmuss's request.

**Comment by NocturnalScream** [comment]
having an OC Integration would be mindblowing! full surveileince of your fusion reactor :)

**Comment by modmuss50** [comment]
I dont see this being worked on in 1.12, I may rewrite this if OC ever gets to 1.14/1.15/
