### ISSUE TITLE
Matter Fabricator overclocker upgrades

### ISSUE THREAD

**Issue by LoveAlmstrom** [TechReborn/TechReborn#1699]
Maybe add overclocker upgrade slots to matter fab?

**Comment by drcrazy** [comment]
Matter fabricator is already fast with scrapboxes. Speed up of scrap processing time could be easily be done via crafting scrapboxes from scrap and feeding fabricator with scrapboxes.

**Comment by LoveAlmstrom** [comment]
It more for it to be even faster cause I easily fill all the slots with scrap

**Comment by drcrazy** [comment]
Craft scrapboxes from scrap
