### ISSUE TITLE
(0.5.1.879) Breaking Industrial Grinder with Pick Crash

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#170]
http://pastebin.com/yP00VEYD

**Comment by Rongmario** [comment]
Looks like a memory leak, not sure - user has got 4gb of RAM allocated.

**Comment by modmuss50** [comment]
It is because it cannot find the ic2 machine when ic2 is installed, something I forgot to fix when we enabled standalone support.

**Comment by modmuss50** [comment]
Quick fix is in, https://github.com/TechReborn/TechReborn/commit/e257c424e2aa4f8c7addb127854aed8144425d10 

I will do a full fix for this tomorrow

**Comment by Rongmario** [comment]
Wouldn't full fix require a machine block from TechReborn itself?

**Comment by modmuss50** [comment]
I don't have a working dev env on my laptop, I will do the full fix for it tomorrow and put it in a central class.
