### ISSUE TITLE
Dupe bug matter fab + tesslocators

### ISSUE THREAD

**Issue by LoveAlmstrom** [TechReborn/TechReborn#1700]
When activating all slots on matter fab, it starts duping the item in the slots

**Comment by modmuss50** [comment]
@latvianmodder any ideas on this?

**Comment by modmuss50** [comment]
Im closing this, spent a while trying to reproduce it. @LatvianModder if its me please let me know, but im confused.

https://www.twitch.tv/videos/402525572
