### ISSUE TITLE
overclocker going bye bye

### ISSUE THREAD

**Issue by LoveAlmstrom** [TechReborn/TechReborn#1702]
https://clips.twitch.tv/LittleSquareOkapiAllenHuhu

I do not know what to say

**Comment by taotaogong** [comment]
> https://clips.twitch.tv/LittleSquareOkapiAllenHuhu
> 
> I do not know what to say

I have the same problem with you , and i find out how to fix the save file.
you can send your save file to my email address.
675621280@qq.com

**Comment by modmuss50** [comment]
Update it’s already been fixed
