### ISSUE TITLE
Ultimate solar panels array out of bounds exception when placed rappidly.

### ISSUE THREAD

**Issue by ShadowKing345** [TechReborn/TechReborn#1704]
Hello.
Like the title says I am getting an array out of bounds exception when I place a ultimate solar panel to quickly in my game. 
I should note that it is on top of glass fiber cables.

Here is the crash report.
[crash-2019-04-08_10.15.26-client.txt](https://github.com/TechReborn/TechReborn/files/3053106/crash-2019-04-08_10.15.26-client.txt)

I am using version 1.12.2-2.21.2.960
on ftb Sky Odyssey version 1.0.0

**Comment by modmuss50** [comment]
This has been fixed please update the pack when the update is out. It should be quite soon.
