### ISSUE TITLE
Cables not connecting and transfering power to IC2 machines

### ISSUE THREAD

**Issue by LoveAlmstrom** [TechReborn/TechReborn#1705]
The top tier cables do not connect to IC2 machines. creative solar panel does not ouput directly either

**Comment by coderbot16** [comment]
TechReborn cables currently do not support EU at all, since IC2 cables are quite different than normal FE cables. I’ll look into this issue at some point, since support would be nice.

**Comment by shinyafro** [comment]
The issue as well its seems in the ultimate reloaded pack is they don't seem to even connect to the fusion control computer, as they seems to carry only RF. Ill see if its because of some config changes the pack authors did that screwed it up but for now i am just noting it here.

**Comment by modmuss50** [comment]
It’s not because the pack author screwed up, it’s because our cables don’t work on EU.

**Comment by shinyafro** [comment]
Fair enough. Might be worth making the fusion reactor able to output to FE/RF when energy is selected to be EU so you can take advantage of the full power.

**Comment by drcrazy** [comment]
Ability to connect to IC2 machines requires too much efforts and could be a risk for existing worlds. Besides that TR cables are quite bad in transfer logic thus no changes for 1.12
