### ISSUE TITLE
Recipe for Carbon Cells is broken

### ISSUE THREAD

**Issue by NocturnalScream** [TechReborn/TechReborn#1706]
If the IC2 Compat mode is enabled, the centrifuge recipe for the carbon cells made out of 16 rubber wood, will only accept techreborns rubberwood and not ic2 rubberwood. This is problematic since the techreborn rubberwood is not accesible anymore when the compat mode is active making it impossible to use this recipe. Also the output of sap should be changed to sticky resin for ic2 for the same reason

**Comment by NocturnalScream** [comment]
https://github.com/TechReborn/TechReborn/issues/1665 
its stated there already

**Comment by modmuss50** [comment]
Im going to reopen this issue as its easier to keep track of.
