### ISSUE TITLE
Small piles of dust broken recipe

### ISSUE THREAD

**Issue by TheFuze** [TechReborn/TechReborn#1713]
Small piles of dust do not turn into pulverized, full piles of their respective types. specifically having issues for Gold, Platinum and Tin. I am playing on Direwolf 20 1.12.2 all mods were up to date as of this week, We did add a few mods, specifically Embers Rekindled, TechReborn, Gravisuite, NeID's, and Enchanting Plus.

All the other small piles work just fine. as far as I can tell though I have not tested them all.

**Comment by drcrazy** [comment]
It is an unidict issue. Either check unidict configs or report to mod author. 

I've took latest release version of DW20, added TR and checked recipes. 
Dust recipes were from unidict rather then thermal or any other mods. 
Then I removed unidict and now I'm able to craft gold dust from small piles.

![image](https://user-images.githubusercontent.com/1382352/58167539-d316c680-7c94-11e9-8179-7427ac5d0af2.png)
