### ISSUE TITLE
Consider buffing the nano saber, or adding a config option for its damage

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#1714]
My friend was testing out the nano saber and found out that it's pretty weak (only 5 hearts of damage):
![nanosaber tooltip](https://cdn.discordapp.com/attachments/282333464253169664/574750384527114273/unknown.png)

Perhaps it would be possible to buff it up to the level of IC2 (8-10 hearts), or at least add a config option to adjust its damage?

**Comment by estebes** [comment]
Buffed default damage to 20. Also added a config option for it.
```java
@ConfigRegistry(config = "items", category = "stats", key = "nanoSaberDamage", comment = "Damage value for the Nano Saber (when active)")
	public static int nanoSaberDamage = 20;
```

**Comment by coderbot16** [comment]
Still not resolved on 1.15! Thanks for resolving on 1.12, but can this issue be re-opened for 1.15+?

**Comment by modmuss50** [comment]
Sure

**Comment by coderbot16** [comment]
Thanks!
