### ISSUE TITLE
Redstone controls for machines

### ISSUE THREAD

**Issue by warplord** [TechReborn/TechReborn#1717]
Hello, I love Tech reborn.

But I want to suggest something - can we please have a way to make machines respond to redstone signal? So they can be turned off/controlled with a redstone signal? Or at least an upgrade that will let us have that functionality for the specific machine it is installed in? 
Many other mods have that, I feel like it would be awesome to have here as well. Thanks.

**Comment by modmuss50** [comment]
Mostly done now, needs a small bit of work to polish it up.
