### ISSUE TITLE
Fusion Reactor Energy Output Question

### ISSUE THREAD

**Issue by rourke750** [TechReborn/TechReborn#1718]
Hey quick question, whats the best way to harness power from the Fusion Reactor.  Currently running latest version of FTB Reloaded and what I've been seeing is that the energy conversion mod is the best bet but it still seems like that doesn't 100% solve it.
Is there a cable or something I can use plus a transformer?

Thanks.

**Comment by drcrazy** [comment]
Haven't tested by myself. Superconductor cable should be able to handle reactor output.
