### ISSUE TITLE
All 3 player detectors have the same crafting recipe

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/TechReborn#1719]
![image](https://user-images.githubusercontent.com/3880072/58341836-c7520e00-7e14-11e9-8c7a-69d0fa91d71c.png)

![image](https://user-images.githubusercontent.com/3880072/58341848-d20ca300-7e14-11e9-8eab-e4672c8378e1.png)

![image](https://user-images.githubusercontent.com/3880072/58341861-db960b00-7e14-11e9-8da3-7c8a68024ea1.png)

on Minecraft: 1.12.2
on Forge: 14.23.5.2838
on TechReborn: 1.12.2-**2.22.1.979**

**Comment by drcrazy** [comment]
It is absolutely fine. You can craft one and then change to another one by clicking it with wrench.
