### ISSUE TITLE
Crash when placing IDSU

### ISSUE THREAD

**Issue by Yarntheory** [TechReborn/TechReborn#172]
As the title says, my client crashes whenever I try to place an IDSU. I am testing the newest build (build 906), but i was also getting this crash in build 879.

Crashlog:

http://pastebin.com/fR5ayhPU

**Comment by Rongmario** [comment]
Can you give a full crashlog (full .txt), mod list should be included in there too.

**Comment by Yarntheory** [comment]
Sure thing! I'm mostly testing stability and cross-mod compatibility (mostly with IC2 classic atm). I was testing with just NEI, so I could check recipes and the like.

Also, is there a version of forge that is recommended? I've been using 1448.

http://pastebin.com/6iGjceUC
