### ISSUE TITLE
Speed upgrade wrong behavior

### ISSUE THREAD

**Issue by luigge** [TechReborn/TechReborn#1721]
Hello again this is my second report

problem is: I am playing on ftb ultimate reloaded 1.12.2 and the overclock update does not increase the speed of the machine, just the amount of the energy that has inside but the speed remains the same.
[bug.zip](https://github.com/TechReborn/TechReborn/files/3221740/bug.zip)
here is the video, as you can see the machine process 1% every second and even with the upgrade it is the same 1% every second.

**Comment by drcrazy** [comment]
Speed upgrade is not recalculated during craft. Next craft will be faster.
