### ISSUE TITLE
Oredict/Recipe weirdness with Immersive Railroading

### ISSUE THREAD

**Issue by CvoidWyvern** [TechReborn/TechReborn#1722]
Immersive Railroading adds the oredict "railBed" to things like dirt, sand, gravel, wood, concrete, and bricks. This seems to be used by Tech Reborn as a recipe is added showing all of them in the grinder, centrifuge, and compressor.

This leads to situations where one input for the grinder is shown twice in JEI with different outputs, as well as things like concrete compressing to wooden plates and getting clay from centrifuging wood.

**Comment by modmuss50** [comment]
IR should not be using the ore dict for this. The ore dict is designed to register items that are identical and that can be replaced with any other item in the list.

I will have to black list this.

**Comment by estebes** [comment]
This should not be an issue anymore.
