### ISSUE TITLE
[Suggestion] Current Iridium Processing Makes No Sense

### ISSUE THREAD

**Issue by voidsong-dragonfly** [TechReborn/TechReborn#1724]
When Iridium Ore is put through a grinder, it comes out as a perfectly shaped ingot ready for use, not dust as with everything else put through the grinder. When I grind up ore, there are no large coherent sections that would look like ingots, just dust once the stone is washed out. I suggest making the grinder give iridium dust and then need the IBF to get ingots?

**Comment by estebes** [comment]
I rewrote the iridium processing tree and it should now be much better. With IC2 installed it will use IC2 iridium instead.
