### ISSUE TITLE
Tech reborn machinces when picked up

### ISSUE THREAD

**Issue by tsonayoshi** [TechReborn/TechReborn#1725]
Tech reborn machines with ovrclock upgrade when picked up with a wrench, the upgrades disappear
im playing DDSS

**Comment by drcrazy** [comment]
Can't reproduce. Wrench dismantled centrifuge and upgrades were dropped together with block itself. 
Do you have any vacuum hopper \ ranged collectors \ etc nearby?

![image](https://user-images.githubusercontent.com/1382352/60897214-59e92800-a270-11e9-8919-ca4820f2917b.png)

**Comment by drcrazy** [comment]
Stale issue.
