### ISSUE TITLE
Fusion Reactor Survival Attainability at Higher Radii

### ISSUE THREAD

**Issue by voidsong-dragonfly** [TechReborn/TechReborn#1726]
The mind-boggling amount of chrome needed for higher radii of the fusion reactor (32+) means there will likely never be a survival attempt at it, as you cannot even use UU-matter to make chrome. In a custom pack I added UU recipes for some items, like chrome and sap, and even then it took ~8 hours of AFKing with 24 recyclers on a single matter fabricator to make a size 13 reactor. To cut down on the amount of coils needed for higher radii and to make the reactor make more sense (nowhere for the plasma to be currently), maybe have it be hollow? This would cut down massively on the amount of chrome needed and allow enhanced superconductors to be made in survival.

I have attached my custom scripts here:

[TechReborn.txt](https://github.com/TechReborn/TechReborn/files/3269963/TechReborn.txt)

**Comment by modmuss50** [comment]
Ive seen people build it in survial, there isnt a huge amount gained from the lager versions.

For now ill leave it be, not going to touch it on 1.12 anyway.
