### ISSUE TITLE
Tech Reborn & RS storage bug.

### ISSUE THREAD

**Issue by IppSwitch** [TechReborn/TechReborn#1732]
https://github.com/kreezxil/World-of-Dragons/issues/277

Possible issue between Refined Storage and Tech reborn
(Currently undergoing more testing)

**Comment by IppSwitch** [comment]
So i have finished my testing and found that the issue is that the Tech reborn cables prioritize Tech Reborn machine blocks over other mods. I have remedied this by using Thermal Expansion - FluxDuct and power is now being outputted to all attached blocks. 

I hope this information helps, if you click on the attached link above you can go threw my findings. I am inexperienced with mods but i hope this assists you in some way.

**Comment by estebes** [comment]
This is not a bug as much as is Cable logic. They search for potential ways to tiles to send energy to and then send them energy. The problem is that this happens always in the same order meaning some tiles will be favored. I made so it is random so that this issue does not happen.
