### ISSUE TITLE
Multiple input in Fusion Reactor

### ISSUE THREAD

**Issue by brachy84** [TechReborn/TechReborn#1734]
newest versions 1.12.2

I tried to make crafttweaker recipes where it takes 8 ultimate catalysts and 4 eternal singularitys to make 1 infinity catalyst.
The recipe works, but if I put in one of each item the reactor starts processing the items which should not happen. 

Another thing: I wanna  be able to set the size requirement of the reactor for each recipe

**Comment by drcrazy** [comment]
It is intentionally set to be 1xitem + 1xsecond item -> One or several other items. Minimum Torus size support added to CT here: https://github.com/TechReborn/TechReborn-ModCompatibility/commit/e43239907009f817bae5b54ccdea4e3613d2bdb8
