### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by FrostCreeper07** [TechReborn/TechReborn#1735]
I'm having an issue with your mod, minecraft crashes whilst loading with this error java.lang.NoClassDefFoundError: techreborn/items/tools/ItemAdvancedDrill, now it may be something completly stupid on my end but can you guys tell me just what the problem [here](https://pastebin.com/BSMaKvnZ) is the crash log any help would be appreciated. BTW i already have the latest versions of Forge for 1.12.2, Tech Reborn & Reborn Core so that's not the issue.

**Comment by estebes** [comment]
Cannot reproduce. Must be some mod interaction.

**Comment by modmuss50** [comment]
Could it be an outdated ic2 version without the drill api?

**Comment by estebes** [comment]
Could be. Support for them was only added in build 117 and @AnimalLover567 seems to be using build 108

**Comment by FrostCreeper07** [comment]
I just updated to the latest beta of ic2 that issue is fixed.
