### ISSUE TITLE
[Suggestion] Additional rubber wood blocks

### ISSUE THREAD

**Issue by IronPiston** [TechReborn/TechReborn#1739]
Currently, rubber wood planks can't make fences, fence gates, doors, trapdoors, or a boat like other vanilla woods in 1.12. Could these be added?

**Comment by drcrazy** [comment]
Full list:
- [x] Rubber log
- [x] Rubber plank
- [x] Rubber button
- [x] Rubber door
- [x] Rubber fence
- [x] Rubber fence gate
- [x] Rubber pressure plate
- [x] Rubber slab
- [x] Rubber stair
- [x] Rubber trap door
- [ ] Rubber boat

Anything else?

**Comment by IronPiston** [comment]
I assume that development is exclusively for 1.14 now, but is it possible for these to be back ported to 1.12?

**Comment by drcrazy** [comment]
Little to no chance for backport.  Also boat won't be implemented until texture available.
