### ISSUE TITLE
Industrial Blast Furnace Question

### ISSUE THREAD

**Issue by LegendLZD** [TechReborn/TechReborn#1741]
Please forgive me a little bad English again:)
Tech Reborn version:TechReborn-1.12.2-2.23.2.1007-universal
Reborn Core version:RebornCore-1.12.2-3.14.1.457-universal
Forge version:14.23.5.2838
When industrial blast furnace which using advanced machine casings(the highest level) and 2 buckets of vanilla lava，it has just 2880 heat.So it cannot smelt hot tungstensteel ingot(3000 heat) when just use vanilla minecraft and tech reborn:(
Please fix it.Thanks!

**Comment by drcrazy** [comment]
You need to use coils to get to 3k heat. Either kanthal or nichrome.

**Comment by estebes** [comment]
![Screenshot from 2019-07-29 10-50-37](https://user-images.githubusercontent.com/6414656/62039027-c5c70c80-b1ee-11e9-893a-690b7df86115.png)

To help you further. That table tells you how to achieve the needed temperatures.

**Comment by LegendLZD** [comment]
OK! Thanks a lot!
