### ISSUE TITLE
Processing certus quartz in grinder

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1742]
I can’t grind my certus quartz crystals into dust in regular grinder,which is kinda illogical,since the ore itself can be grinded  into dust

**Comment by estebes** [comment]
You will have to explain your issue better :P

**Comment by ghost** [comment]
> You will have to explain your issue better :P
Sorry,edited

**Comment by estebes** [comment]
Because certus quartz is a thing added by another mod. I will see about adding compat with AE2.

**Comment by drcrazy** [comment]
Should be fixed by https://github.com/TechReborn/TechReborn-ModCompatibility/commit/b228222c7a7974420454f97c54a414a387367cf7
