### ISSUE TITLE
JEI recipe oddity potentially related to Assembly Machine recipes (ingredient quantities >1)

### ISSUE THREAD

**Issue by AlodoTrobell** [TechReborn/TechReborn#1744]
Greetings ye,

There appears to exist an oddity related to JEI recipe registration when having TechReborn installed.

Basically, it leads to JEI reporting strange recipes such as this one, in which the ingredient quantities are off:

![grafik](https://user-images.githubusercontent.com/30476323/62639575-17cf0700-b940-11e9-9c18-c9e43f0ef8cf.png)

Having tested with a larger modpack, I noticed a pattern, in which any item that is at least once used in >1 quantity in recipes for the TechReborn assembling machine would exhibit the same issue(, such as recipes of other mods requiring an electrum plate suddenly requiring 4 instead of 1). TechReborn's own recipes seem to be affected as well. So I suspect that the recent assembling machine addition might be somewhat related.

![grafik](https://user-images.githubusercontent.com/30476323/62640163-3aadeb00-b941-11e9-9196-a0c28646065d.png)

This issue does not seem to affect the vanilla recipe viewer, so heads-up at this point that this might be a cross-mod kinda deal in the end. (Apologies if this ends up being on JEI's plate more than yours in the end.)

Client (mod) setup used to produce the issue:
- Minecraft 1.12.2 + Forge 14.23.5.2838
- JEI v1.12.2-4.15.0.268
- RebornCore v1.12.2-3.15.5.467
- TechReborn v1.12.2-2.24.1.1017

As far as I could tell, the issue does not seem to actually affect the recipes under the hood. It's merely the display to the user that is odd.

Ye got any idea what might cause this kinda behaviour?

Sincerely - Alodo

**Comment by estebes** [comment]
Should be fixed.

**Comment by AlodoTrobell** [comment]
Woah, that was quick!
Yeah, I can confirm, it's fixed in the DEV build.
Thank you very much!
