### ISSUE TITLE
Strange Hologram Behavior

### ISSUE THREAD

**Issue by IndiePhunq** [TechReborn/TechReborn#1748]
When active, the multiblock hologram make the player's arm transparent, disappears while sneaking, and moves with the player's point of view during the first person sneaking animation.
Versions:
Fabric API - 0.3.0+build.207
Reborn Core - 4.0.0.80
Tech Reborn - 3.0.0.78

**Comment by modmuss50** [comment]
Fixed, will be in the next RebornCore version.
