### ISSUE TITLE
Unusable Sawmill

### ISSUE THREAD

**Issue by IndiePhunq** [TechReborn/TechReborn#1750]
Sawmill is in the center of its multiblock, rendering it inaccessible.

Mods:
Fabric API - 0.3.0+build.207
Reborn Core-1.14.4-4.0.3.95
REI - 2.9.7+build.143
Tech Reborn - 1.14.4-3.0.2.88![javaw_936l9PhWAN](https://user-images.githubusercontent.com/42917867/62659741-303c2300-b93a-11e9-93db-b07cba1a0c14.png)

**Comment by drcrazy** [comment]
It is hologram rendering issue. 

Sawmill usable if multiblock built in the following way:
![image](https://user-images.githubusercontent.com/1382352/62660621-37355680-b977-11e9-8ff1-1717f266ba5c.png)

**Comment by modmuss50** [comment]
Fixed, dont forget to put water in the middle as the hologram currenlty doesnt show that as it needs fixing.
