### ISSUE TITLE
Translations are missing

### ISSUE THREAD

**Issue by ferdavs98** [TechReborn/TechReborn#1757]
Hello, I’m changing the language of the game to Russian, but the language of the mod does not change.
https://drive.google.com/file/d/1RoLqfpnasSZVOuHkdYcNRjeLfxfQWboW/view?usp=sharing

**Comment by drcrazy** [comment]
There is no Russian translation for 1.14 yet.

**Comment by modmuss50** [comment]
This will take some work as I will need to hook up crowdin to 1.14.4

**Comment by ferdavs98** [comment]
Thank you for working on the mod. You are the best

**Comment by modmuss50** [comment]
Done, 1.12 translations are set in stone, https://translate.techreborn.ovh/project/techreborn has been updated to the 1.14.4 branch. Please let any issues be known.
