### ISSUE TITLE
Trees Do Not Float compat - axe durability is not used

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1758]
Using trees do not float/treecapitator and when breaking the tree with an axe, it doesn't get used. No durability goes down.

**Comment by drcrazy** [comment]
Can you give a link for Treecapitator you used in your pack, please? There are several versions of that mod available.

**Comment by ghost** [comment]
tdnf-1.5.0+build.49.jar
Trees do not float. :)

**Comment by modmuss50** [comment]
Also look at log breaking sound.

**Comment by ghost** [comment]
and particles as well.
