### ISSUE TITLE
NEI Matter Fabbricator Handler is missing

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#176]
Same as title.
Tech Reborn 0.5.3.908
I Hope these bug reportings that I'm doing helps!
Sorry for possible english mistakes!

**Comment by gigabit101** [comment]
Dose not need one

**Comment by Xen1290** [comment]
Why ? Nei handler are always useful...

**Comment by gigabit101** [comment]
It makes UU from scrap that's it and that will be in the PDA

**Comment by Xen1290** [comment]
Yes, but someone doesn't know that. And it's annoyng search in wikis or something when you have nei. For me This thing is one of the reason of ic2 fall, lack of documentation and comfort. Sorry for possible english mistakes.

**Comment by gigabit101** [comment]
Fine

**Comment by Xen1290** [comment]
Thanks for reopening the issue
