### ISSUE TITLE
1.14.4 Copper rarer than emeralds/not spawning?

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1761]
Found 4 pieces of copper in 4 different caves, very, very rare.

**Comment by modmuss50** [comment]
I can take a look at this, should be possible to write a quite command or something to compare it to the 1.12 version.

**Comment by modmuss50** [comment]
After playing in survival for a bit the numbers seem good. Can you check the depth that you were mining at? as they spawn between y level 60 and 20.

**Comment by ghost** [comment]
I was at y level 45 or so, maybe a problem with my world actually.

**Comment by modmuss50** [comment]
After playing it seems like the levels are fine.
