### ISSUE TITLE
1.14.4 tag rubber planks as planks

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1767]
I can't do stick or anything with them.

**Comment by modmuss50** [comment]
They are, but for what ever reason they are not working with crafting recipes.

![](https://ss.modmuss50.me/javaw_2019-08-09_20-06-54.png)

**Comment by Shnupbups** [comment]
You need to tag them with the item tag as well. Item tags are used in recipes, not block tags.
