### ISSUE TITLE
Client doesn't start, server starts [1.14.4]

### ISSUE THREAD

**Issue by jan-tennert** [TechReborn/TechReborn#1769]
If I start the server with the mod it works. But If I start the client with the mod the error comes:

https://hasteb.in/xevazaso.sql

**Comment by modmuss50** [comment]
What version of TechReborn and RebornCore are you using? Along with the fabric API?

**Comment by jan-tennert** [comment]
The newest:  159 (Fabric) 4.0.5.109 (Reborn Core) 3.0.4.104

**Comment by modmuss50** [comment]
fabric-api-0.3.1+build.208.jar
RebornCore-1.14.4-4.0.5.109.jar
TechReborn-1.14.4-3.0.4.108.jar

works for me, make sure you are using all these versions.

**Comment by jan-tennert** [comment]
I'll try

**Comment by jan-tennert** [comment]
Not working :(

**Comment by ferdavs98** [comment]
> fabric-api-0.3.1 + build.208.jar 
> RebornCore-1.14.4-4.0.5.109.jar 
> TechReborn-1.14.4-3.0.4.108.jar
> 
> работай для меня, сделай так, чтобы ты использовал все эти версии.

Thx bro, working

**Comment by jan-tennert** [comment]
Good Mod.....

**Comment by modmuss50** [comment]
Can you send the full crash log please with the list of mods and their versions?

**Comment by modmuss50** [comment]
Closing as cannot repoduce and no log was provided, and others dont seem to be having the issue.
