### ISSUE TITLE
Missing Localizations

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#177]
Hi @modmuss50 , I found some missing localization, maybe this help you:
From config file:
config.techreborn.allowExpensiveWatermill.tooltip
config.techreborn.allowExpensiveWindmill.tooltip
config.techreborn.allowBopRecipes.tooltip
config.techreborn.allowForestryRecipes.tooltip
config.techreborn.allowNaturaRecipes.tooltip
config.techreborn.aesuMaxOutput.tooltip
config.techreborn.aesuMaxStorage.tooltip
config.techreborn.baseLesuOutput.tooltip
config.techreborn.cloakingDeviceEUTick.tooltip
config.techreborn.cloakingDeviceMaxCharge.tooltip
config.techreborn.cloakingDeviceTier.tooltip
config.techreborn.dragoneggsiphonerPower.tooltip
config.techreborn.extraOutputPerLesuBlock.tooltip
config.techreborn.heatGeneratorOutput.tooltip
config.techreborn.lapotronicOrbMaxCharge
config.techreborn.lapotronicOrbTier.tooltip
config.techreborn.lesuStoragePerBlock.tooltip
config.techreborn.showChargehud.tooltip
config.techreborn.allow.UUrecipesAluminumDust.tooltip
config.techreborn.allow.UUrecipesCoal.tooltip
config.techreborn.allow.UUrecipesCopperDust.tooltip
config.techreborn.allow.UUrecipesDiamond.tooltip
config.techreborn.allow.UUrecipesEmerald.tooltip
config.techreborn.allow.UUrecipesEmeraldOre.tooltip
config.techreborn.allow.UUrecipesGoldDust.tooltip
config.techreborn.allow.UUrecipesGoldOre.tooltip
config.techreborn.allow.UUrecipesIronDust.tooltip
config.techreborn.allow.UUrecipesIronOre.tooltip
config.techreborn.allow.UUrecipesLapis.tooltip
config.techreborn.allow.UUrecipesLeadDust.tooltip
config.techreborn.allow.UUrecipesPlatinumDust.tooltip
config.techreborn.allow.UUrecipesRedStone.tooltip
config.techreborn.allow.UUrecipesResin.tooltip
config.techreborn.allow.UUrecipesTinDust.tooltip
config.techreborn.allow.UUrecipesTitaniumDust.tooltip
config.techreborn.allow.UUrecipesTungstenDust.tooltip
config.techreborn.allow.hiderecipes.tooltip
config.techreborn.allow.uurecipesBone.tooltip
config.techreborn.allow.uurecipesCactus.tooltip
config.techreborn.allow.uurecipesCocoa.tooltip
config.techreborn.allow.uurecipesEnderPearl.tooltip
config.techreborn.allow.uurecipesFeather.tooltip
config.techreborn.allow.uurecipesGlass.tooltip
config.techreborn.allow.uurecipesGlowstoneBlock.tooltip
config.techreborn.allow.uurecipesGrass.tooltip
config.techreborn.allow.uurecipesInk.tooltip
config.techreborn.allow.uurecipesIridiamOre.tooltip
config.techreborn.allow.uurecipesLava.tooltip
config.techreborn.allow.uurecipesLilypad.tooltip
config.techreborn.allow.uurecipesObsidian.tooltip
config.techreborn.allow.uurecipesSnowBall.tooltip
config.techreborn.allow.uurecipesSnowBlock.tooltip
config.techreborn.allow.uurecipesStone.tooltip
config.techreborn.allow.uurecipesSugarCane.tooltip
config.techreborn.allow.uurecipesVine.tooltip
config.techreborn.allow.uurecipesWater.tooltip
config.techreborn.allow.uurecipesWood.tooltip
config.techreborn.allow.tungstonOre.tooltip
config.techreborn.bauxiteOre.rare.tooltip
config.techreborn.cinnabarOre.rare.tooltip
config.techreborn.copperOre.rare.tooltip
config.techreborn.galenaOre.rare.tooltip
config.techreborn.iridiumOre.rare.tooltip
config.techreborn.leadOre.rare.tooltip
config.techreborn.olivineOre.rare.tooltip
config.techreborn.pyriteOre.rare.tooltip
config.techreborn.rubyOre.rare.tooltip
config.techreborn.sapphireOre.rare.tooltip
config.techreborn.sheldoniteOre.rare.tooltip
config.techreborn.silverOre.rare.tooltip
config.techreborn.sodaliteOre.rare.tooltip
config.techreborn.sphaleriteOre.rare.tooltip
config.techreborn.tinOre.rare.tooltip
config.techreborn.tungstenOre.rare.tooltip
From the game:
techreborn.recipe.implosioncompressor
techreborn.recipe.chemicalReactor
Rolling Machine name: Rolling machine should be --> Rolling Machine
NEI Rolling Machine handler name: rollingcrafting should be --> Rolling Machine Recipe
Centrifuge --> Industrial Centrifuge
Tech Reborn 0.5.3.908
I Hope these bug reportings that I'm doing helps!
Sorry for possible english mistakes!

**Comment by Xen1290** [comment]
@modmuss50 Found more missing localizations!:
fluid.tile.techreborn.glyceryl
fluid.tile.techreborn.berylium
fluid.tile.techreborn.chlorite
fluid.tile.techreborn.helium3
fluid.tile.techreborn.deuterium
fluid.tile.techreborn.helium
fluid.tile.techreborn.calciumcarbonate

**Comment by Xen1290** [comment]
@gigabit101 you missed some things:
techreborn.recipe.implosioncompressor
techreborn.recipe.chemicalReactor
Rolling Machine name: Rolling machine should be --> Rolling Machine
NEI Rolling Machine handler name: rollingcrafting should be --> Rolling Machine Recipe
Centrifuge --> Industrial Centrifuge
fluid.tile.techreborn.glyceryl
fluid.tile.techreborn.berylium
fluid.tile.techreborn.chlorite
fluid.tile.techreborn.helium3
fluid.tile.techreborn.deuterium
fluid.tile.techreborn.helium
fluid.tile.techreborn.calciumcarbonate
item.techreborn.cell.empty.name
keys.techreborn.category
keys.techreborn.config
tile.techreborn.supercondensator.name

**Comment by gigabit101** [comment]
dam it will do later
