### ISSUE TITLE
Crash when using wrench on generator

### ISSUE THREAD

**Issue by BigBear0812** [TechReborn/TechReborn#1771]
Hello, I found that my game crashes when I try to use the wrench to either rotate or disassemble a generator. I was wondering if this is a known bug with the Minecraft 1.14.4 fabric version or am I missing something.

[Crash Report](https://pastebin.com/47JFhnF6)

TechReborn-1.14.4-3.0.4.108
RebornCore-1.14.4-4.0.5.109
Fabric Loader 0.4.8_build.159

**Comment by ghost** [comment]
I'm not a helper or anything, but to disassemble, just break with a pickaxe

**Comment by shedaniel** [comment]
This is an error by casting the client player to server player. https://github.com/TechReborn/TechReborn/blob/a906fad739304491881923db2c40797858264916/src/main/java/techreborn/items/tool/ItemWrench.java#L47 should check `!world.isClient()`
