### ISSUE TITLE
Crash when placing Interdimensional SU

### ISSUE THREAD

**Issue by Chuwar** [TechReborn/TechReborn#1778]
- fabric-loader-0.4.8+build.159-1.14.4
- fabric-api-0.3.1+build.208
- RebornCore-1.14.4-4.0.7.122
- TechReborn-1.14.4-3.0.5.123
*** Exception ticking world ***
[1.txt](https://github.com/TechReborn/TechReborn/files/3496921/1.txt)

**Comment by modmuss50** [comment]
Humm yeah, this needs a full rewrite.

**Comment by modmuss50** [comment]
Rewritten them :D
