### ISSUE TITLE
Some items still hardness issues?

### ISSUE THREAD

**Issue by Chuwar** [TechReborn/TechReborn#1779]
Breaking one hit by hand and disappear.
- Player Detector
- Alarm
Breaking one hit by hand but don't disappear.
- Incandescent  Lamp
- LED Lamp
Mods
- fabric-loader-0.4.8+build.159-1.14.4
- fabric-api-0.3.1+build.208
- RebornCore-1.14.4-4.0.7.122
- TechReborn-1.14.4-3.0.5.123

**Comment by modmuss50** [comment]
Fixed, thanks again.
