### ISSUE TITLE
Industrial Centrifuge recipes doesn't decrease input stack amount properly

### ISSUE THREAD

**Issue by drcrazy** [TechReborn/TechReborn#1786]
There were 7 dusts in centrifuge. Processing is not starting due to 3 dust required but craft takes only 1 dust, thus x5 output crafted.

![image](https://user-images.githubusercontent.com/1382352/63131269-bfde7300-bfc5-11e9-8512-cb2d8af3ed7f.png)

**Comment by drcrazy** [comment]
Same with invar recipe in alloy smelter

**Comment by modmuss50** [comment]
Fixed, thanks for reporting.
