### ISSUE TITLE
1.14: World bricked when lava bucket placed in thermal generator

### ISSUE THREAD

**Issue by grondag** [TechReborn/TechReborn#1789]
https://paste.ee/p/Kgc2X

Crash was immediate.  World won't restart.  Maybe lava buckets aren't supposed to go in there?

**Comment by drcrazy** [comment]
Lava cells work fine with Thermal generator in TR 3.0.6.133 & RC 4.0.8.125. Can you try to have them updated in your instance?

**Comment by modmuss50** [comment]
Yeah, I feel like I fixed this one, might have not pushed it out yet though?

**Comment by modmuss50** [comment]
Yeah, I did fix this one: https://github.com/TechReborn/TechReborn/commit/ff8b497c54eb55f9561f55911d6681d8629c4370

**Comment by grondag** [comment]
Ah, I was certain we had the latest build but seems not.  At least not on the server machine - that may be the problem.  Will update and see what happens.  Thanks.
