### ISSUE TITLE
1.14: World bricked when any ore is placed in industrial grinder

### ISSUE THREAD

**Issue by notfood** [TechReborn/TechReborn#1790]
Crash was immediate. World won't restart. Shift clicking any ore will go into the bucket slot, followed by a crash.

#### Files used:
- fabric-api-0.3.1+build.208.jar
- RebornCore-1.14.4-4.0.9.128.jar
- TechReborn-1.14.4-3.0.7.138.jar

#### Log:
![output](https://user-images.githubusercontent.com/5370107/63221756-3ebce280-c163-11e9-8af3-5b93548a3533.gif)

[latest.log](https://github.com/TechReborn/TechReborn/files/3512792/latest.log)

**Comment by drcrazy** [comment]
Ore should go to the slot on the right from tank.  Shift-click should put ore there (

**Comment by modmuss50** [comment]
Fixed crash, and fixed being able to put the ore in that slot.
