### ISSUE TITLE
Can't craft Lava Cell

### ISSUE THREAD

**Issue by Chuwar** [TechReborn/TechReborn#1795]
No recipe for Lava Cell.(I need lava cells cuz it easy for brings many lava for my Thermal Generator)
RebornCore-1.14.4-4.0.10.138
TechReborn-1.14.4-3.0.8.151

**Comment by modmuss50** [comment]
Right click the cell on lava?

**Comment by Chuwar** [comment]
It work! Sorry for my mistake.
