### ISSUE TITLE
AOBD incompatibility 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#18]
This is more than likely on AOBD's side having not made a specific case for Tech Reborn, figured it might be worth sharing

Here's a clean crash report with just Tech Reborn and dependencies.
http://pastebin.com/agT2XzwV

Here's a crash with 150 or so other mods. looks like AOBD is trying to make some ores be processed by your mod and not quite knowing how. 
http://pastebin.com/BPQ1EwU5

**Comment by modmuss50** [comment]
Thanks for reporting this, If it has an api we can use that. Not sure why it should crash.

**Comment by modmuss50** [comment]
For some reason it looks a recipe with the same input has been added as one that has been added before.

**Comment by joflashstudios** [comment]
Fixed in 2b17e7e949112df3d29e6c186aac033776abf21e
