### ISSUE TITLE
[1.12.2] crashes on startup (problem with compatibility)

### ISSUE THREAD

**Issue by joinmod** [TechReborn/TechReborn#1808]
hello i have a problem with mod compatibility part
I found in logs that it is caused due to NBTTag or fluid cells from unknown mod
Crash log:
https://paste.dimdev.org/napoyidura.mccrash

P.s yes i have a lot mods and my pc can handle this...

UPD: buildcraft caused this problem, without him game is starting
i have a modular ver. (7.99.24.2)
UPD2: I found that the core for the galaxy space addon for the galacticraft is also the cause of the error
if i turn off techreborn or buildcraft or AsmodeusCore (for galaxy space): game is starting

**Comment by TheSnowyChickens** [comment]
Hi,
it is possible, that my issue is the same like the issue from joinmod ?

https://paste.dimdev.org/riloporuzi.mccrash
