### ISSUE TITLE
Does this work with IC2Classic by speiger officially? Or do you still require Techreborn-Classic?

### ISSUE THREAD

**Issue by VenomFrog** [TechReborn/TechReborn#181]
Just curious what state its at, if THIS current version works well with IC2Classic, or to wait until this is officially released and wait for a release at http://modmuss50.me:8080/job/TechReborn-Classic/.

Thank you!

Not sure where to label it as a QUESTION, my apologies if this doesn't belong here.

**Comment by modmuss50** [comment]
The main version works just fine with it, that is from when it wasn't possible to do it in both. I should delete that build.
