### ISSUE TITLE
No recipe for bronze dust.

### ISSUE THREAD

**Issue by Merisdarkmon** [TechReborn/TechReborn#1811]
Hi,
Can't find any way to make bronze dust.
There is only recipe from small pile of bronze dust, bronze nuget, bronze block.
There is no recipe to create the bronze dust only the exchanges from one form to another.
On the wiki site there is no information how to create the dust or the ingot from other materials and jei won't have any repices.
Minecraft version 1.14.4
Fabric api 0.3.1+build.208
Reborn Core 4.0.12.146
Tech Reborn 3.0.10.184
Thanks for help.
MerisDarkmon

**Comment by drcrazy** [comment]
Bronze dust made by grinding bronze ingot which is made by smelting copper and tin in Alloy smelter. REI provides all this info ingame
