### ISSUE TITLE
[1.14.4] Wrong fluid in plasma generator, crash on load save

### ISSUE THREAD

**Issue by mlengka93** [TechReborn/TechReborn#1812]
Description: Ticking block entity
 
java.lang.ClassCastException: net.minecraft.class_1792 cannot be cast to reborncore.common.fluid.container.ItemFluidInfo

https://pastebin.com/j5EzTaLp

**Comment by mlengka93** [comment]
i put a wrong fluid in plasma generator and it instantly crash, and save file won't load unless i remove the mod first (obviously).

**Comment by drcrazy** [comment]
Can't reproduce. 

![image](https://user-images.githubusercontent.com/1382352/63642516-f18fc200-c6c8-11e9-9d7a-49c87bdd5ca7.png)


What fluid you put into it?

**Comment by mlengka93** [comment]
im testing the generator, here's what i did:
- fill the generator with heliumplasma cell until full
- then try another cell
- crash when put helium coolant i guess, im not sure, try to switch all things with cell names in it.
