### ISSUE TITLE
Long range weapon, high-tech armor and nuclear energy

### ISSUE THREAD

**Issue by LukkyM4n** [TechReborn/TechReborn#1815]
Hello! When will the long-range weapons (like a mining laser), energy armor (like a nano- and quantum) and a nuclear reactor be added? Without them, the modification seems incomplete.

**Comment by modmuss50** [comment]
Great ideas!

We had some things like this planned but havent had the time to get around to adding them, over the last few months we have been working hard updating the mod to 1.14.4 once the mod is stable and not crashing on 1.14.4 we can think about adding some new things.

Thanks for the suggestions, hopefully one day we will be able to add something like this.
