### ISSUE TITLE
TR furnaces do not yield experience

### ISSUE THREAD

**Issue by Gitcurt777** [TechReborn/TechReborn#1817]
Experience Issue. 
New to this github. Though I've been playing Minecraft and mods since beta.
Im playing the newest version I know of. With core on Fabric. With other mods. Everything seems fine. Except I get no experience from the mods furnaces. I can burn all the dusts and anything vanilla in a vanilla furnace. Then i get experience from everything. But anything cooked in your mods furnaces. Yields absolutely no experience. In fact. No Machines yield experience for me. If they are supposed to. Major bummer...
Could be a mod conflict I suppose. Though it would be an odd one. I have no idea what one. If it is a conflict.
But if you may know.
Here is my mod list.

Tech Reborn 184
RebornCore 146
Animal Net
Appleskin
Battle Towers
Cosmetic Armor
Fabric Api
Voxel Map
Fishtraps
REI
Terrestria

**Comment by mdkdir** [comment]
This is still an issue with electric furnaces.
