### ISSUE TITLE
[1.14.4] Inventory Bug

### ISSUE THREAD

**Issue by Gitcurt777** [TechReborn/TechReborn#1818]
Two right slots in inventory. Top corner and just below it. Do not allow Items into Machines. 
Instead, causes item to be thrown. 

Also. Not sure if this is from your mod. But this happened more than once.
Sugar in last hotbar slot. Used down to one. Then try to throw away. Becomes 12 sugar.

**Comment by modmuss50** [comment]
I did notice the first bug, and I know what causes it.

The 2nd thing im not sure, and not sure how it could be TR.
