### ISSUE TITLE
Solid Canning Machine. How to use?

### ISSUE THREAD

**Issue by Gitcurt777** [TechReborn/TechReborn#1819]
Nothing on the wiki. Used to play IC a lot. There is no recipe for a Tin Can. So not sure how to use this machine. Does it not can food and other items?

**Comment by modmuss50** [comment]
The solid canning machine is a new machine that was added to allow sloid items to be inserted into cells.

If you have a mod like REI (JEI for 1.12.2) you will be able to see all the recipes that this machine has. For questions like this the TeamReborn discord server is a good place to go.

**Comment by Gitcurt777** [comment]
Got ya. Thank you.
