### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#182]
Hi! Some recipes are missing:
- [x] Lithium Backpack
- [x] Lapotron Pack
- [ ] Omni tool
- [ ] Advanced Drill
- [ ] Lazurite Chunk
- [x] Iridium Neutron Reflector
- [ ] Mass Hole Device
- [ ] Diamond Plate
- [ ] Other Plates
- [x] Fusion Coil
- [x] Lightning Rod
- [x] Fusion Control Computer
- [x] Plasma Generator
- [x] AESU
- [x] IDSU
- [ ] Aerospace Advanced Reinforced Duct Tape FAL-84
- [ ] Iridium Reinforced Block
- [ ]  Iridium Reinforced Tunstensteel blocks is missing, while Tungstensteel Block's recipe is storage instead of what it was in GT (reinforced stone + cooled Tunstensteel Ingot)
- [ ] Chrome Dust
- [ ] Endstone Dust
- [ ] Netherrack Dust
- [ ] Ender pearl Dust
- [ ] Iridium Ingot
- [ ] Nickel Ingot
- [ ] Platinum Ingot
- [ ] Tungstensteel Ingot
- [ ] Zinc Ingot
- [ ] Hydrogen
- [ ] Resin Centrifuge to Rubber
- [ ] All Machine Hulls (and they have no uses)
- [ ] Basic Circuit Board
- [ ] All Fluid Cells (see #207)
- [ ] Extracter Recipe of all cells
- [ ] All nuggets

TechReborn-0.5.5.943-universal
I Hope these bug reportings that I'm doing helps!
Sorry for possible english mistakes!

**Comment by lilmoefow** [comment]
Can confirm that the recipe are missing with only industrialcraft-2-2.2.780-experimental, TechReborn-0.5.3.908-universal, and NotEnoughItems-1.7.10-1.0.4.107-universal.  

Not sure if this is the same issue as #187

**Comment by modmuss50** [comment]
No the other one is a crash

**Comment by Barhandar** [comment]
> Aerospace Advanced Reinforced Duct Tape FAL-84

Pretty sure that it missing a recipe is part of the point... that is, the recipe for it is missing in old GregTech as well.

**Comment by wormzjl** [comment]
Additions:
chrome dust
endstone dust
netherrack dust
ender pearl dust
Iridium ingot
nickel ingot
platinum ingot
Tungstensteel ingot
zinc ingot
hydrogen
resin centrifuge to rubber
All machine hulls (and they have no uses)
All fluid cells (see https://github.com/TechReborn/TechReborn/issues/207)

Extracter recipe of all cells

**Comment by MrBretze** [comment]
Basic Circuit Board crafting ?

**Comment by modmuss50** [comment]
Done: PlasmaGenerator;Aesu;Idsu;FusionControlComputer

**Comment by Xen1290** [comment]
I've updated the first post with the all additions, now once you have done the recipes, simply mark the objects in the list.

**Comment by modmuss50** [comment]
ah!, Thats very usefull! Thanks :+1:

**Comment by Calenria** [comment]
Data Orb and Data Control Circuit seem to be missing.

**Comment by Xyic0re** [comment]
Assembling machine, missing recipe and uses

**Comment by modmuss50** [comment]
see #339
