### ISSUE TITLE
[1.14.4]Energy Overload? Graphic bug.

### ISSUE THREAD

**Issue by Gitcurt777** [TechReborn/TechReborn#1820]
Lets see if I can explain this.

If my batteries fill up while my generator is running. The generator will get stuck in on. Only visually. Also. If I use an energy crystal to keep a machine filled. The machine may appear to stop working or appear to work forever. Once the energy reaches full while its running.

These instances are fixed by removing and replacing the machine. Or by relogging. Though happen enough to be a Bug.

**Comment by modmuss50** [comment]
Fixed.
