### ISSUE TITLE
[TechReborn-1.12.2-2.24.1.1017] Peridot Tools & Armor Recipe BUG

### ISSUE THREAD

**Issue by jimmytrouser** [TechReborn/TechReborn#1821]
I am using (02/08/19 TechReborn-1.12.2-2.24.1.1017-universal.jar) and all the recipies using green peridots for some reason require 8 in each slot rather than 1 in each crafting slot.  When I roll back to (23/07/19 TechReborn-1.12.2-2.23.2.1007-universal.jar) there is no bug.  Even when I choose (false) in general.enableGemTools the recipe is still bugged.  This occurs when it is the only mod in the pack and when it is twinned with PRoject-Red.
![2019-08-29_12 55 00](https://user-images.githubusercontent.com/7896905/63938261-4716f680-ca5c-11e9-91a0-a104819298f5.png)

**Comment by estebes** [comment]
This is already fixed in the latest versions

**Comment by jimmytrouser** [comment]
Thank you.
