### ISSUE TITLE
[1.14.4]Compatibility issue with Cosmetic Armor.

### ISSUE THREAD

**Issue by Gitcurt777** [TechReborn/TechReborn#1823]
![2019-08-29_08 46 12](https://user-images.githubusercontent.com/54503925/63955696-00180980-ca3a-11e9-964c-d4e322d8f75d.png)

Using an MFE shows my cosmetic armor/shield in the left slots.

**Comment by modmuss50** [comment]
This is correct, the armor slots on the side are to allow you to access your armor easily without needing to open your player inv.

When not using powered armor there isnt a lot of point in it, but its intended to be like this.

**Comment by drcrazy** [comment]
It shows shield instead of boots. And boots instead of leggings. And leggings instead of chest. And chest instead of helm. And doesn't show helm at all

**Comment by drcrazy** [comment]
Closed by https://github.com/TechReborn/RebornCore/commit/2131feae3349074119f19f7fb573d13fd8609293
