### ISSUE TITLE
[19w34a]Rolling machine not working

### ISSUE THREAD

**Issue by RealCorebb** [TechReborn/TechReborn#1824]
![image](https://user-images.githubusercontent.com/33654314/64026795-0f01d780-cb72-11e9-9a4c-8ba7d78650be.png)

The rolling machine cant not make the item.Sometimes it works fine, but sometimes it will not work.And in the REI.Sometimes i can left click to see the recipe of the rolling machine's item (eg. heating coil),but sometimes it can't. By the way, i am running it on a server,lots of player have the same problem. 

fabric-api-0.3.2+build.212-1.15
(have the same problem in older version)

Pleax fix it,Thanks.

**Comment by modmuss50** [comment]
This isnt working as you have the lock enabled, this lock is there to keep atleast 1 of each input in the machine. Adding more items or disabling the lock will fix it.

**Comment by RealCorebb** [comment]
Sorry.But i still think there are some issues.
I try again.And it only work one time .Even i unlock or adding lots of items.
If I do something wrong, I am sorry to bother you.
![image](https://user-images.githubusercontent.com/33654314/64039885-48e0d700-cb8e-11e9-98be-e1409cdeb1c7.png)
![image](https://user-images.githubusercontent.com/33654314/64040052-b260e580-cb8e-11e9-84ae-aec0b04f34cf.png)

**Comment by modmuss50** [comment]
No worries, ill reopen the issue and take a look when I get a chance.

**Comment by drcrazy** [comment]
Please, use 19w38b version
