### ISSUE TITLE
Crash on 19w35a

### ISSUE THREAD

**Issue by RealCorebb** [TechReborn/TechReborn#1825]
![image](https://user-images.githubusercontent.com/33654314/64031758-a881b700-cb7b-11e9-9f48-3550346ba5be.png)

Using latest Fabric and Fabric API for 19w35a.
And the mod is also the latest of 1.15

If i create a fresh new world,it will not crash.
So i think is the problem is SolarPanel

**Comment by modmuss50** [comment]
I havent updated it to 19w35a, 19w34a will work. I will get around to this at soon.

**Comment by modmuss50** [comment]
I’ve released a 37a build. Don’t expect me to keep up with all snapshots, possibly every other one just to keep on top of updating.
