### ISSUE TITLE
[1.14.4] Error while loading some recipes.

### ISSUE THREAD

**Issue by cyb3rm4n** [TechReborn/TechReborn#1828]
All the errors will eb on the log file: https://hastebin.com/ahaxevaror.md

**Comment by drcrazy** [comment]
One of mods in your pack messing up with c:aluminum_ingot tag. Can you try to remove them one by one to find out which one?

**Comment by cyb3rm4n** [comment]
the error is thropwn by REI (i think)

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/TechReborn/commit/0b39eb986378edd78b894cbec4b500cd39bfe36e
