### ISSUE TITLE
[Suggestion] Implement IC2 armor and GraviSuite items

### ISSUE THREAD

**Issue by Vintschente** [TechReborn/TechReborn#1829]
Nano armor:

- normal nano armor (maybe slightly weaker like 0,5-1 less armor and 0,5 less armor toughness per piece) from IC2 
- upgradeable (not different item) nano chestplate (with 3/4 creative flight speed but make this upgrade version cost different effortful materials like half a stack of feathers, 8 ender eyes, 2 ghast tears or something alike (no elytra which defeats the whole point)
- upgradeable (not different item) boots that negate fall damage

Quantum armor:
- quantum armor as upgrade from nano armor and more expensive materials than it is now (1-1,5 more armor and 0,5 to 1 more armor toughness per piece than diamond armor)
- customizable/upgradeable so they don't become different items and just get enhancements like: night vision, saturation, hill step up, flight speed, running speed, poison resistance, wither resistance, fire resistance, water breathing, normal speed in water etc.

Quantum chestplate and boots should only be craftable from the upgraded versions of the nano chestplate and boots but quantum chestplate gets like 5/4 of creative flight.

Vajra:
- I have noticed that the advanced drill, jackhammer and chainsaw are all already implemented and I was wondering why the Vajra isn't?
- as it is and was an endgame multi-tool wouldn't it be fitting to craft it out of the advanced drill, jackhammer and chainsaw and other endgame resources including alloys or alike that one can only get with fully upgraded multi-blocks from TR?
- same ability as it had already (mine everything instantly, toggleable silktouch) and add hoeing and shearing

Best Regards

**Comment by modmuss50** [comment]
I started looking into armor a while back, sadly I dont really have the time. Something may come at somepoint.
