### ISSUE TITLE
[TechReborn-1.12.2-2.24.1.1017] semi_fluid_generator soft crashes client

### ISSUE THREAD

**Issue by robbob4** [TechReborn/TechReborn#1832]
Crashes: 
1. https://pastebin.com/A8UTkV6r
2. https://pastebin.com/gvYrrgQB
3. https://pastebin.com/YgNFbbQ6
4. https://pastebin.com/QjThVm9X
5. https://pastebin.com/A5TQVT1W

Related: https://github.com/TechReborn/TechReborn/issues/723 ?

I seem to be having an infrequent crash when just standing in the chunk with a Semi Fluid Generator processing Creosote Oil (Thermal Foundation) pumped in from a Stone Tank (Fluid Tank) from the top. It sits next to an Oil Generator (Actually Additions) which has Crystallized Oil (Actually Additions) in its tank. Upon writing this issue, all sides were set to pump in (default setting), but I will see if configuring only the side with the tank intended for this machine will resolve my problem. Only one player at a time will be disconnected from the server. Other players and the server will remain online.

I am using TechReborn-1.12.2-2.24.1.1017 from modpack https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles (version 5.7b).

Please let me know if any additional information is needed. I will also reply if my change to the fluid configuration of the block seems to resolve the issue, or if I experience another crash that points to a TechReborn Semi Fluid Generator.

**Comment by robbob4** [comment]
Still crashes after the fluid input side change: https://paste.dimdev.org/asamuyoleb.mccrash

**Comment by drcrazy** [comment]
@robbob4  Please, feel free to re-open if not fixed.
