### ISSUE TITLE
[1.14.4] Power lighting is not functional

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#1833]
Pretty much title. Both incandescent and LED lamps do not produce light while powered (they also have what I believe to be larger than intended hitboxes).

![image](https://user-images.githubusercontent.com/12499779/64346417-171da500-cfc0-11e9-9534-3e9c92e30480.png)

**Comment by erindal** [comment]
They drain power and the texture seems to change when they do.

**Comment by modmuss50** [comment]
Fixed, took a bit of debugging to figure out why it broke.
