### ISSUE TITLE
TechReborn-1.12.2-2.24.1.1032-universal - CraftTweaker recipe now Fails

### ISSUE THREAD

**Issue by AbieTheFishman** [TechReborn/TechReborn#1838]
Update from TechReborn-1.12.2-2.24.1.1017-universal.jar

Fails on extractor addRecipe
mods.techreborn.extractor.addRecipe(<enderio:item_material:5>,<minecraft:sand>, 100, 10);

[crafttweaker_break.log](https://github.com/TechReborn/TechReborn/files/3597552/crafttweaker_break.log)

**Comment by Silverrain2004** [comment]
hello Guys... i have the same Problem here... all my recipes are broken.. its just like TechReborn loose compatibility to Crafttweaker after Update completly. Are you Guys working on a Fix?
