### ISSUE TITLE
[1.14.4] Lithium batteries use empty cells in their recipe

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#1840]
As opposed to the (I would assume) intended lithium cell.

![image](https://user-images.githubusercontent.com/12499779/64723637-e695a980-d49e-11e9-92ec-8de7851a412a.png)

**Comment by modmuss50** [comment]
Humm, this is a slight pain to fix as vanilla doesnt support NBT in recipes...

**Comment by erindal** [comment]
Maybe a temporary compressor recipe that puts two lithium cells into a lithium cell pack?
