### ISSUE TITLE
[Fabric, 1.14.4] Electric furnace doesn't allow input filtering

### ISSUE THREAD

**Issue by rapus95** [TechReborn/TechReborn#1844]
![2019-09-18_18 39 55](https://user-images.githubusercontent.com/5960902/65167912-ba9c9a00-da43-11e9-85d8-890633e45211.png)

**Comment by modmuss50** [comment]
Right now this isnt possible due to the furnace not going though our recipe system, it shouldnt be too hard to add support for this.
