### ISSUE TITLE
[1.14.4] Titanium Ingot

### ISSUE THREAD

**Issue by LukkyM4n** [TechReborn/TechReborn#1845]
Where to find or how to create a titanium ingot? Neither in the wiki, nor in the game (REI mod) there is no information on how to get this ingot.

**Comment by LukkyM4n** [comment]
I found it

**Comment by valkyrienyanko** [comment]
How did you find it?

**Comment by drcrazy** [comment]
In REI )
or in wiki (https://wiki.techreborn.ovh/doku.php?id=items:ingot:titanium_ingot)

**Comment by valkyrienyanko** [comment]
The REI and wiki link you sent does not explain how to get it from the world. (1.18.2 Fabric)

**Comment by drcrazy** [comment]
Hmm. 
1. According to ingot page Titanium ingot made from smelting 4x small dusts. 
2. Small dusts are from Bauxite dust (https://wiki.techreborn.ovh/doku.php?id=items:small_pile:small_pile_of_titanium_dust)
3. Bauxite dust is made from Bauxite Ore (https://wiki.techreborn.ovh/doku.php?id=items:dust:bauxite_dust)
4. Bauxite ore spawns in Overworld (https://wiki.techreborn.ovh/doku.php?id=world_generation:ore:bauxite)


I believe same data available in REI.


Thus both REI and wiki explain how to get titanium ingot from the world.

**Comment by valkyrienyanko** [comment]
I see now thanks. All I saw was making titanium from titanium in the REI and this is what initially confused me.
