### ISSUE TITLE
[1.12.2] Unable to open Iron Alloy Furnace since 2.24.1.1017 > 2.24.1.1032 update

### ISSUE THREAD

**Issue by WolfBV** [TechReborn/TechReborn#1846]
**Describe the bug**
When attempting to right-click an Iron Alloy Furnace from the mod Tech Reborn, the furnace's gui does not appear, similar to trying to right click a fence post or dirt block.

**To Reproduce**
1. Create a singleplayer world
2. Use creative mode to give yourself an Iron Alloy Furnace from Tech Reborn
3. Place the furnace on the ground
4. Attempt to open it with a right-click

**Versions:*
 - Minecraft: 1.12.2
- Tech Reborn: 2.24.1.1017, 2.24.1.1032
- Reborn Core: 3.16.0.469, 3.16.2.473
 - Forge: 14.23.5.2844, 14.23.5.2847

**Comment by WolfBV** [comment]
I wasn't sure whether or not to link the issues, don't even know how I'd do that, but here is the github issue I first made on the Bane of Dragons modpack when I had this problem: https://github.com/kreezxil/Bane-of-Dragons/issues/13

**Comment by Sixdd6** [comment]
Same issue here, cannot interact with the Iron Alloy Smelter.

Minecraft 1.12.2
Forge 14.23.5.2847
Tech Reborn 2.24.1.1032
Reborn Core 3.16.2.473
