### ISSUE TITLE
Two Coal Plate

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#185]
![1](https://cloud.githubusercontent.com/assets/8685029/10395169/c55851f4-6e9b-11e5-8e3e-9154dfa475fe.png)
![2](https://cloud.githubusercontent.com/assets/8685029/10395173/c775002c-6e9b-11e5-97d0-23431416f1d4.png)
Tech Reborn 0.5.3.908
I Hope these bug reportings that I'm doing helps!
Sorry for possible english mistakes!

**Comment by modmuss50** [comment]
Reporting the bugs is great, I will get around to fixing some tonight. Thank you!

**Comment by Xen1290** [comment]
Thanks!
