### ISSUE TITLE
[1.14.4] Lamps still not giving off light.

### ISSUE THREAD

**Issue by Delliardo** [TechReborn/TechReborn#1850]
Both lamps are still not giving off any light and the flat lamps have a very large hit box.

![2019-09-29_19 02 14](https://user-images.githubusercontent.com/4108176/65840972-cc582a00-e2ec-11e9-9734-5090a37092a8.png)

Mod folder:
![c968418e25c0eb7c1a9be463550cee72](https://user-images.githubusercontent.com/4108176/65840978-d712bf00-e2ec-11e9-8102-5ffe9a246f7b.png)

**Comment by modmuss50** [comment]
Humm, I did fix this, ill need to look again at it.

**Comment by modmuss50** [comment]
Seems to be an issue with the cables not applying the side correctally when moving power.

**Comment by modmuss50** [comment]
Fixed
