### ISSUE TITLE
[1.14.4] REI recipes don't work for filled cells.

### ISSUE THREAD

**Issue by IronGem** [TechReborn/TechReborn#1854]
REI 3.1.5 Build 30
TechReborn 3.0.17 build 250
RebornCore 4.0.19 build 187
libCD 1.3.2

Whenever I click (or Key R or U) on a recipe for a filled cell in REI, I am brought to the same recipe list for any fluid, usually for Empty Cells.  I am unable to find out how to obtain certain fluids or how to use them in other recipes (i.e. How to obtain lithium for lithium batteries).

![TechReborn cell recipe bug](https://user-images.githubusercontent.com/1959530/66776732-4dcec100-ee84-11e9-8cb5-5b986842b8d7.png)

Please let me know if you need any further information.

**Comment by voidsong-dragonfly** [comment]
Lithium comes from clay, sodium from the same. Methane is centrifuging food/rubber wood, what else?

**Comment by IronGem** [comment]
Yes, I have been able to find most of these recipes using a Gregtech4 wiki, but the fact remains that they dont work yet in REI
