### ISSUE TITLE
[1.14.4] Not Sure If Bug; Solar Panels can be crafted without the previous Solar Type Tier

### ISSUE THREAD

**Issue by AndaPlays** [TechReborn/TechReborn#1861]
![66741723-70f27400-ee76-11e9-9f03-5f9cee93ae5a](https://user-images.githubusercontent.com/37880697/66924575-21a17480-f02b-11e9-933c-7ee3e85a564e.png)

**Comment by drcrazy** [comment]
Same was in 1.12 some time ago. Changed in this commit to 1.12: https://github.com/TechReborn/TechReborn/commit/593b9775bdfd764b044ca6f384e9ea71caded762#diff-a3ead91a65fd16d4ccdca7e1bc047d49

Options are fine.
