### ISSUE TITLE
Fluids and some ore not rendering in world

### ISSUE THREAD

**Issue by wendigo1** [TechReborn/TechReborn#1865]
Worlds wont load Fluids and some ores. 
Missing items only show up in menu but not naturally rendering in game.

I have no mods installed except TechReborn and fabric
vanilla java client launcher.

game version fabric-api-0.4.1+build.245-1.14
TechReborn-1.14.4-3.0.17+build.250

**Comment by modmuss50** [comment]
Can you send a screenshot, im not really sure what you mean.

Thanks

**Comment by drcrazy** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/1382352/67934416-ec735580-fbd8-11e9-8169-bf807df77c4f.png)
