### ISSUE TITLE
[1.14.4] Interdimensional SU bug with power input/ouput

### ISSUE THREAD

**Issue by ToukaDouka** [TechReborn/TechReborn#1868]
The Interdimensional SU takes input from power correct sides but does not display the power value in the block GUI. It can still charges items placed inside it and the debug tool displays the correct power contained in the block. It can not output power from any side.

Tested on Minecraft 1.14.4
TechReborn-1.14.4-3.0.17+build.250
RebornCore-1.14.4-4.0.19+build.187
fabric-loader-0.6.2+build.166-1.14.4

No other mods loaded

![2019-10-24_17 15 43](https://user-images.githubusercontent.com/13713911/67610837-2d3b1c80-f74a-11e9-9f3d-f4f26b549080.png)

![2019-10-24_17 15 54](https://user-images.githubusercontent.com/13713911/67610815-1268a800-f74a-11e9-9362-41e2fb73e4ce.png)

**Comment by modmuss50** [comment]
Are you on a server?

I may have fixed it with my tweaks to the cables? as its working for me.

![](https://ss.modmuss50.me/java_2019-10-26_22-04-17.png)

**Comment by ToukaDouka** [comment]
I encountered the Interdimensional SU bug in an unmodded SP creative map while i was trying to test another bug. Haven't gotten the chance to build it in survial mp yet. I think the Adjustable SU is working perfectly right now though.

**Comment by modmuss50** [comment]
Ahh, I was testing the wrong block....

**Comment by modmuss50** [comment]
Can confirm this, I think I broke it when moving to the new power net
