### ISSUE TITLE
Recipe issue with IC2 Experimental  with Beta 908 and newer 

### ISSUE THREAD

**Issue by walkerjonny** [TechReborn/TechReborn#187]
Hi,
I'm getting the following ambiguous recipe error on game loading:
http://pastebin.com/ZJQvd084
This happens with the released Beta 908 and all newer builds on the Jenkins server.

**Comment by modmuss50** [comment]
Does it just happen with Techreborn and ic2?

**Comment by modmuss50** [comment]
It looks like another mod is adding this recipe.

**Comment by walkerjonny** [comment]
OK, I found the reason.
It an other add-on to IC2, the Iridium Mod, that adds Iridium Ore to the Worldgen and also to the IC2 recipes.
Maybe you have changed something there, because it works with Techreborn Build 879.

**Comment by modmuss50** [comment]
Mind sending me a link to that mod?

**Comment by walkerjonny** [comment]
Look there:
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10700

**Comment by modmuss50** [comment]
The thing is that mod does every that we do.

**Comment by walkerjonny** [comment]
Just a question: Might it be possible that you have changed the output amount for the recipe 
[[1xgt.blockores@84, 1xtile.oreIridium@0, 1xtile.techreborn.ore@1] -> [2xitem.techreborn.crushedore@8]] 
from 1xitem.techreborn.crushedore@8 to 2xitem.techreborn.crushedore@8?
I did a test where I added the Iridium Mod as the last mod and then I got that ambiguous recipe:
[[1xtile.oreIridium@0] -> [1xitem.crushedIridium@0]]
So I assume that you have changed the output amount and that causes that issue now.

**Comment by gigabit101** [comment]
why are u using that mod we add Iridium ore to world gen already ??

**Comment by modmuss50** [comment]
That mod is not compatible as we do everything it does.
