### ISSUE TITLE
[1.14] [Minor Visual Bug] Weird UI when control + middle clicking a multiblock machine and placing it down.

### ISSUE THREAD

**Issue by Spearkiller** [TechReborn/TechReborn#1870]
When playing in Creative, and you control + middle click an active multiblock machine and then place it down, the UI takes on a very interesting appearance (https://i.imgur.com/aoT79rn.png)

**Comment by drcrazy** [comment]
It's not a bug, it's a feature. When you pick block in creative it is copied with NBT tags, which includes inventory. Gray overlay 'Incomplete multiblock' also overlays inventory stacks properly.
