### ISSUE TITLE
Item/block descriptions missing

### ISSUE THREAD

**Issue by Ushupiuck** [TechReborn/TechReborn#1875]
With Tech Reborn 3.0.18+build.256 & Reborn core 4.0.20+build.190, Text fails to display on items & blocks.

Complete mod list:

Mods:
  [✔️] Allure-1.1.5
  [✔️] appleskin-mc1.14-fabric-1.0.7
  [✔️] ArcaneMagic-1.0.0-beta5
  [✔️] betterthanmending-fabric-1.0.0
  [✔️] chunk-activator-1.2.0+mc1.14.4
  [✔️] cotton-1.0.0-rc.3
  [✔️] diggusmaximus-1.0.6
  [✔️] extradoors-1.2.0
  [✔️] fabric-api-0.4.1+build.245-1.14
  [✔️] foamfix-0.12.1
  [✔️] Hwyla-fabric-1.14.2-1.9.17-66
  [✔️] InventorySorter-1.5.7
  [✔️] LibGui-1.3.2
  [✔️] modmenu-1.7.11+build.121
  [✔️] optifabric-0.5.2
  [✔️] OptiFine_1.14.4_HD_U_F4
  [✔️] RebornCore-1.14.4-4.0.20+build.190
  [✔️] RoughlyEnoughItems-3.1.5+build.31
  [✔️] SimpleVoidWorld-3.0.0
  [✔️] SoulShards-fabric-1.14.4-1.0.11-13
  [✔️] TechReborn-1.14.4-3.0.18+build.256
  [✔️] terrestria-1.0.11+build.40
  [✔️] traverse-2.0.8+build.26
  [✔️] vanilla-hammers-1.6.3

**Comment by drcrazy** [comment]
Can you post a screenshot, please?

**Comment by elec2** [comment]
I can confirm it's at least missing at the electric charchable tools, i beleve the machine blocks and the reenforced iron bars.

**Comment by Ushupiuck** [comment]
As soon as I wake up tomorrow, I'll send a screenshot. Configs too if necessary

**Comment by elec2** [comment]
> I can confirm it's at least missing at the electric charchable tools, i beleve the machine blocks and the reenforced iron bars.

Sorry, its just in German... i trough all unnamed Tags would be original language.

**Comment by Ushupiuck** [comment]
Haven't gotten to play yet, but now that Elec2 mentions this, I am using the pirate language. That might be it
