### ISSUE TITLE
[1.14.4] REI not displaying a broad range of recipes involving machines since last update

### ISSUE THREAD

**Issue by ToukaDouka** [TechReborn/TechReborn#1878]
Not sure if this is more of an REI bug or a TechReborn bug but I'm writing it up here since it started with the last TechReborn build.  REI doesn't display some recipes that require machine processing.  A very large range of recipes do not show up but there are exceptions. 

Sometimes recipes are still shown if you use the REI overlay and right/left click on the blocks/items but not when using the [Show Recipe] and [Show Uses] keybinds in REI. 

For example, a lot of recipes that involve a grinder do not show up when using REI .
REI won't show you can grind iron ore in a grinder/industrial grinder but it does show you can grind ruby ore in both a grinder/industrial grinder.

It seems pretty random which recipes show up in REI but it would be safe to say that more recipes don't show up in REI than do. 

Even though the recipes don't show up in REI, they still work in the machines.

Machines affected include:
- Extractor
- Industrial Electrolyzer
- Industrial Centrifuge
- Grinder/Industrial Grinder
- Blast Furnace
- Assembly Machine
- Alloy Furnace
-Compressor
and maybe some more.

I tried updating REI and removing all mods except for the ones listed below but the issue still persists.

Mods:
- TechReborn-1.14.4-3.0.19+build.262
- RebornCore-1.14.4-4.0.21+build.192
- fabric-api-0.4.0+build.240-1.14
- RoughlyEnoughItems-3.1.6+build.33

Let me know if you would like more information.

_As a side note, I know I've been submitting a lot of issues lately. Thanks for taking the time to look into them. I really enjoy playing around with this mod and appreciate it when issues are fixed!_

**Comment by ToukaDouka** [comment]
I actually think the issue is way simpler than i originally thought. REI just won't display recipes for anything you don't have the exact stack size for. For example, If you have 1 Silicon cell or 3 Silicon cells it won't show the recipe for Silicon plates. If you are holding EXACTLY 2 Silicon cells it will show the recipe.

**Comment by modmuss50** [comment]
Uhh I know what caused this. I’m gonna have to talk to the REI dev about some of this

**Comment by ToukaDouka** [comment]
Thanks for looking into it!

**Comment by modmuss50** [comment]
About to push a build fixing the major issue here, there is still some more work to be done on this issue though.

**Comment by drcrazy** [comment]
It looks like it is fixed.
