### ISSUE TITLE
1.14 LibCD Index out of bound exception for libCD recipe

### ISSUE THREAD

**Issue by drcrazy** [TechReborn/TechReborn#1879]
This is causing exception on sample provided for shulker shell. 

https://github.com/TechReborn/TechReborn/blob/1b35ef88ee14998d17b75de53f0617e204c70ce2/src/main/java/techreborn/compat/libcd/TRTweaker.java#L439

**Comment by LemmaEOF** [comment]
@drcrazy Is this happening in a dev environment?

**Comment by drcrazy** [comment]
yes

**Comment by LemmaEOF** [comment]
I know the exact problem, then. The LibCD import in build.gradle is out of date; this was fixed in production a little while back. Update it to 1.5.0+1.14.4 and it should work!

**Comment by drcrazy** [comment]
Didn't helped (

![image](https://user-images.githubusercontent.com/1382352/68028561-3f770680-fcc6-11e9-97e7-95dd9a810d85.png)

And still:
```
[16:38:23] [ForkJoinPool.commonPool-worker-3/ERROR]: Error parsing TechReborn rolling machine recipe - Index: 5, Size: 4
```

**Comment by LemmaEOF** [comment]
Huh. I'll try to look at this soon.

**Comment by drcrazy** [comment]
Should be fixed.
