### ISSUE TITLE
[1.14.4] Power storage drained when connected directly to Fiber Cable.

### ISSUE THREAD

**Issue by Kjasi** [TechReborn/TechReborn#1880]
On my server, when I connect a Fiber cable to the output of an MFE or BatBox, (even when connected to nothing else, just a single cabled coming out of the box) the power will be drained from the MFE at about 1K a second. However, when I use another cable, such a shielded copper cable, coming out of the MFE, the power is no longer drained. (Right now, I'm using a copper cable out of the MFE, and connecting to the rest of my power grid, which is all Fiber.)

I first noticed this in 256, and it's still happening in 264. I have not tested this in single-player, but I suspect it may also happen there.

**Comment by ToukaDouka** [comment]
Are you sure it isn't just the internal storage of each cable filling up? Each glass fiber has a storage of 32k I believe.

**Comment by Kjasi** [comment]
Maybe, but then the MFE would still get drained when I use a copper cable, to fill up all the other fibers. This is not the case. When using a copper cable directly out of the MFE, even hooked up to my Fiber network, no drain. Hook up a single fiber directly to the output of the MFE, and the MFE will get completely drained, and it never regains any amount of power. (Instantly drained when power comes into it.)

**Comment by Kjasi** [comment]
okay, WTF? I started up to take screen shots (I tested just before I posted, and this was true) but now it's not working the way I said it was... Which means it's working as intended... Without any changes...

Guess I miss-filed an issue.
