### ISSUE TITLE
Recipe duping

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#189]
In ic2, 1 tin plate makes 3 cells
8 lava cells can be centrifuged to 17 tin ingots ->dupe

Also seem that removing this recipe via minetweaker is not working, the expression I used is:
mods.techreborn.centrifuge.removeRecipe(<IC2:itemCellEmpty:2>);

**Comment by modmuss50** [comment]
I will take a look

**Comment by modmuss50** [comment]
to remove this recipe use 

    mods.techreborn.centrifuge.removeInputRecipe(<IC2:item.itemCellLava>);

In minetweaker remove recipe removes all recipes that make that item, not all recipes that that item is made into, in the case of the centrifuge I have added another method to the centrifuge to allow you do do what you wanted to do.

**Comment by Barhandar** [comment]
IC2E/IC2C distinction error. The old recipe assumes the old results, while IC2E has changed the results. Maybe make the centrifuge result automatically adjust based on how much cells per tin that recipe outputs? That'd certainly be in line with pervasiveness GT is famous for.
