### ISSUE TITLE
[1.15pre] Blast furnace heat calcultion

### ISSUE THREAD

**Issue by Yoghurt4C** [TechReborn/TechReborn#1893]
the industrial blast furnace might be a bit too lazy in checking its consistency; assembling it, then repeatedly breaking and putting back any number of casings (as long as the entire structure isn't disassembled) causes it to continuously increase its maximum heat capacity, seemingly without a limit
https://files.catbox.moe/loe7vh.webm
![image](https://user-images.githubusercontent.com/11313954/69417891-9ce0ff00-0d2a-11ea-9117-ba98d01da8be.png)

**Comment by modmuss50** [comment]
Yeah, something seems slighly off with the whole thing.

**Comment by liach** [comment]
Also if you misplaced a block during construction and fixed it, the machine will say the multiblock structure is invalid

Both the heat and invalid things are fixed by a server restart.

**Comment by modmuss50** [comment]
@liach thats what I noticed, not sure whats casuing it. Prob a bad port somewhere, ill take a look at it again shortly.
