### ISSUE TITLE
[1.15pre] fusion reactor misbehaving

### ISSUE THREAD

**Issue by Yoghurt4C** [TechReborn/TechReborn#1894]
-energy production recipes (the ones that say `E/t: -2048`) don't start
-right-clicking fusion cores on the controller doesn't work, it just opens the gui

```
Thanks for reporting an issue! However, before you report an issue, please read the following:

 * We will not backport to an old version of minecraft. Do not suggest this
 * Make sure you're using the latest version of TechReborn, RebornCore, and Forge before reporting a bug!
 * Don't argue with any TechReborn developers. What they say goes. Feel free to suggest a way to implement something, but if they say no, don't push it.
 * If you want to suggest something please open an issue, and it will get tagged as a suggestion.
 
 Make sure to delete all this text before you report your issue.
```

**Comment by modmuss50** [comment]
Ive worked on it a bit, should be better might still have a few issues. So let me know how it goes.

**Comment by Yoghurt4C** [comment]
![image](https://user-images.githubusercontent.com/11313954/69733030-be345780-113d-11ea-83b1-e0dc75e883fb.png)
now it starts, but only when the fusion reactor is at ~80% internal energy capacity and it doesn't produce energy after the first tick, this doesn't seem intentional

**Comment by Yoghurt4C** [comment]
new problem: the controller block's inventory blanks out when the server shuts down, probably happens when the chunk is unloaded too

**Comment by modmuss50** [comment]
Should hopefully be all fixed now
