### ISSUE TITLE
Suggestion - Compatibility LibBlockAttributes

### ISSUE THREAD

**Issue by 1a2s3d4f1** [TechReborn/TechReborn#1896]
![](https://upload.cc/i1/2019/12/01/YLzZRK.png)
This tank use LibBlockAttributes But  Thermal Generator can not get lava
[Simple Pipes](https://minecraft.curseforge.comprojects/simplepipes)
[libblockattributes](https://minecraft.curseforge.com/projects/libblockattributes)
Could you compatibility LibBlockAttributes?

**Comment by modmuss50** [comment]
I am aware of LBA, ive not looked too deeply at it, if I can add support in a way that is optinol then it might be a possiblity.

**Comment by Juuxel** [comment]
For TR->LBA, you could do something like what LBA does for Silk support:
https://github.com/AlexIIL/LibBlockAttributes/blob/0.5.x-1.14.x/src/main/java/alexiil/mc/lib/attributes/fluid/compat/silk/SilkFluidCompat.java

**Comment by modmuss50** [comment]
Ah, I didnt know that was a thing. That seems easy enough. Does LBA have a 1.15 version?

**Comment by Juuxel** [comment]
It doesn't have an official release, but I've heard of people mixing into LBA to fix it.

Another thing about fluid compat is that TR seems to use mB, while LBA uses droplets (1620).

**Comment by modmuss50** [comment]
LBA for 1.15.1 includes RC support.
