### ISSUE TITLE
Crash in industrial grinder fluid ui panel

### ISSUE THREAD

**Issue by liach** [TechReborn/TechReborn#1897]
When I open the fluid widget panel in the ui of an industrial grinder (no multiblock structure), the client crashes. Playing bee merry modpack for 1.15 pre 3.

https://gist.github.com/7f25df34cb770ea3f5fc1e5085de68b3

**Comment by liach** [comment]
This crash happens for semifluid generator "configure fluid" tab too.

**Comment by modmuss50** [comment]
Fixed.
