### ISSUE TITLE
[1.15-pre6] Cells in recipes are blank on servers 

### ISSUE THREAD

**Issue by zeflap** [TechReborn/TechReborn#1903]
Server:
![1575964097](https://user-images.githubusercontent.com/4191012/70506359-beb3f180-1b32-11ea-91b4-6123aeb4eed8.png)
![1575964058](https://user-images.githubusercontent.com/4191012/70506335-b0fe6c00-1b32-11ea-9bba-467067d89a85.png)

Singleplayer
![1575964190](https://user-images.githubusercontent.com/4191012/70506373-c8d5f000-1b32-11ea-97c8-8ba380002967.png)
![1575964232](https://user-images.githubusercontent.com/4191012/70506377-cbd0e080-1b32-11ea-84d0-b38d4bf15d45.png)

probably also a thing for @shedaniel ?

**Comment by modmuss50** [comment]
Prob an issue with my recipe syncing code, ill take a look.

**Comment by modmuss50** [comment]
Fixed, was 2 stupid mistakes.
