### ISSUE TITLE
Making the cables waterloggable (1.14+)

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1907]
I saw that in the Fabric version of the mod, you made iron fences waterloggable, so it would make sense if cables would be waterloggable too.

Also a small idea:
I don't really know if Tech Reborn has energy loss, but if it does, it would be cool if it would be bigger in water (if the cable isn't insulated of course). It also would be neat if underwater, the radius where you get shocked by an uninsulated cable is was bigger.

**Comment by modmuss50** [comment]
Good idea. Can prob do something intresting. Will be for 1.15 tho

**Comment by modmuss50** [comment]
Good idea. Can prob do something intresting. Will be for 1.15 tho
