### ISSUE TITLE
Thorium and plutonium cell no longer works in the IC2 nuclear reactor?

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#191]
what happened?
I remember that they can be used some times ago?

**Comment by modmuss50** [comment]
We need to add the reactor

**Comment by wormzjl** [comment]
can we get the one working for ic2 reactor back?

**Comment by modmuss50** [comment]
Wait, do you mean nuclear reactor or fusion reactor?

**Comment by wormzjl** [comment]
nuclear reactor in fact

**Comment by modmuss50** [comment]
Ah, I got confused.

**Comment by wormzjl** [comment]
When I was testing techreborn months age I remember that these cells was working...Did my memory get messed up XD?

**Comment by modmuss50** [comment]
I don't think so, @gigabit101 might know?

**Comment by gigabit101** [comment]
Not yet needs to be implemented

**Comment by wormzjl** [comment]
Derp for me :3

**Comment by Carbon-Ghost** [comment]
Will it be able to support IC2 classic thermoelectric reactor ( normal ) and the steam one ? ( new )

**Comment by gigabit101** [comment]
when Ic2 gets to 1.8.9

**Comment by wormzjl** [comment]
what's the point of delaying this to 1.8 anyway?
