### ISSUE TITLE
Electric furnace uses 800 FE per item 

### ISSUE THREAD

**Issue by Imnuts7** [TechReborn/TechReborn#1920]
Since coal/charcoal produces 4k FE in a generator, this makes smelting using the electric furnace very inefficient and is nothing like what is described in the 'Getting started' section on the wiki.

**Comment by jusvit** [comment]
Hello, I've done some testing and I got the following:

(Using 1 iron ore block)
1 coal in generator > electric furnace produces 5 iron ingots
1 coal in furnace produces 8 iron ingots

Approximately the same time-frame.

Therefore a vanilla furnace is 60% more efficient than a non-upgraded electric furnace in this circumstance.

**Comment by lumphrey** [comment]
this is also present in 1.14.4 (build 273) - will the fix for 1.15 be ported over?

**Comment by jusvit** [comment]
> this is also present in 1.14.4 (build 273) - will the fix for 1.15 be ported over?

Sure
