### ISSUE TITLE
Basic generator create power without fuel

### ISSUE THREAD

**Issue by Daktyl198** [TechReborn/TechReborn#1922]
Tech Reborn 3.1.0+build.59
Fabric 0.4.25+build.282
Modpack: All the Mods: Fabric, version 0.1.4

After setting down the generator, it produces infinite power without the need of fuel.
Gif attached:
![InstantGif_2019 12 24-00 29](https://user-images.githubusercontent.com/2475672/71395608-a5a44980-25e4-11ea-98e7-e89e6e3c9218.gif)

**Comment by drcrazy** [comment]
@Daktyl198  Issue fixed on TR side. But it might appear anywhere else, because some other mod assigned burn time for air. Feel free to dig deeper to find out what mod caused this.

**Comment by Daktyl198** [comment]
I would love to dig deeper. Unfortunately, TR generator is the only block that does this. Every other furnace-style block requires a burnable item to be inserted to work, including all of the Fabric Furnaces blocks.

Does TR check for inserted fuel differently than vanilla/other mods? I also can't find a mod in the pack that modifies air to be burnable, either on accident of purpose.
