### ISSUE TITLE
Solar panels stopped working - Failed to create block entity techreborn:solar_panel

### ISSUE THREAD

**Issue by Trnrr** [TechReborn/TechReborn#1925]
Using build TechReborn-1.15-3.1.0+build.62.jar
Fabric 1.15.1

I restarted my server today and the solar panels I have in my base all stopped working. I had to go around and replace them a few times and then they started working again. This showed in console when the server booted https://gist.github.com/Trnrr/7eefbc16aba2a9e60e142602b066f99a

**Comment by jusvit** [comment]
I believe this was fixed when I merged my PR in. However @modmuss50 hasn't made a build since.

**Comment by Trnrr** [comment]
Ok no problem. Also was rubber wood fences not dropping anything fixed yet? Or should I make a issue for that?

**Comment by jusvit** [comment]
Nope hasn't been fixed yet, I'd create an issue. Could you backup your world and update the Tech Reborn mod to: [Tech Reborn Build 80 jar](https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.15/lastSuccessfulBuild/artifact/build/libs/TechReborn-1.15-3.1.0+build.80.jar) and see if the solar panels still mess up when restarting server?

I think you also need to update reborn core: [Reborn core build 55 jar](https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.15/lastSuccessfulBuild/artifact/build/libs/RebornCore-1.15-4.0.28+build.55.jar)

**Comment by Trnrr** [comment]
I will update both right now and check.

**Comment by Trnrr** [comment]
Updating Tech Reborn and Reborn Core to those versions fixes the issue :)
