### ISSUE TITLE
Rubber Wood Fences do not drop anything

### ISSUE THREAD

**Issue by Trnrr** [TechReborn/TechReborn#1926]
Using
TechReborn-1.15-3.1.0+build.80.jar
RebornCore-1.15-4.0.28+build.55.jar

1. Place rubber wood fence
2. Chop it down
3. Get nothing :(

**Comment by jusvit** [comment]
Additional note:  Rubber gate, button, pressure plate and door also have this issue. Maybe potentially more, seems like an underlying issue.

**Comment by drcrazy** [comment]
Fixed by https://github.com/TechReborn/TechReborn/commit/c7b23a581e0d92b8fd7258630b8aa3504890b9fd
