### ISSUE TITLE
Machine power tiers and upgrades

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#193]
I was testing with IC2 uncomplication, wich brings the old ic2 classic e-net to ic2 experimental.
http://forum.industrial-craft.net/index.php?page=Thread&threadID=11586
As the classic e-net, everything with a wrong voltage will go boom

With this mod, all low voltage machines from techreborn now blows up when connected to an IC2 CESU (128 voltage), which is normal.
But I've found that the industrail blast furnace (128 eu/t max) also blows up with this voltage, where the chemical reactor (same voltage) does not.
Those machines on 512 eu/t tier had no issues, and the industrial grinder should be on 128 eu/t tier.

Also the transformer upgrades (both one from ic2 and from techreborn) are not working. I guess that upgrades are not implemented yet?

**Comment by modmuss50** [comment]
Upgrades are not done yet, no
