### ISSUE TITLE
Some sequences of recipes end with more than they started with, repeatably

### ISSUE THREAD

**Issue by cplir-c** [TechReborn/TechReborn#1933]
Centrifuging bronze dust and re-alloying it doubles your bronze.
Electrolyzing methane and chemical reacting the carbon and hydrogen together again pentuples your methane and your cells.
Centrifuging magma cream and chemical reacting the blaze powder and slime balls together again doubles your magma cream.

I might add REI screenshots later.

 - Minecraft: 1.15.1
 - Mod Loader: Fabric

I'm playing on the Bee Merry modpack server, and I set up a fusion reactor that uses the methane loop to make hydrogen for fuel.

**Comment by modmuss50** [comment]
Closed via https://github.com/TechReborn/TechReborn/commit/52de2fc59f526f67bba85ec58a4c788ab8965e75
