### ISSUE TITLE
Description missing for interdimensional SU advancement

### ISSUE THREAD

**Issue by drcrazy** [TechReborn/TechReborn#1939]
**Describe the bug**
Missing description for interdimensional SU advancement

**Screenshots**
![image](https://user-images.githubusercontent.com/1382352/71636710-023ae080-2c45-11ea-9477-14bfccf3eebc.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15
 - Mod Loader: fabric

**Comment by jusvit** [comment]
This is resolved in my PR, just need to finish unit system up and then we can merge.
