### ISSUE TITLE
Crash with Stockpile

### ISSUE THREAD

**Issue by Lukas-Dragoneye** [TechReborn/TechReborn#1941]
In first sorry for my english.

![2020-01-02_16 13 17](https://user-images.githubusercontent.com/53571175/71674297-1d0f7100-2d7b-11ea-9667-a5477132d8f6.png)

When machine have auto output and try give item but barrel is full game crash forever.
Mc 1.15.1 fabric

https://pastebin.com/qVZ21CJN

**Comment by Quu1337** [comment]
Happened to us as well, when the barrel gets full, server crashed every time the machine tried to insert more stuff into the barrel.
Got it "fixed" by removing power cable (in that ~1sec time the server was non-crashing) and restarting as many times as it took the machine to run out of power.

**Comment by modmuss50** [comment]
humm, im not sure if thsi is a stockpile issue or our issue

**Comment by vhd** [comment]
The best foolproof thing you can do is to put a hopper in the middle.
There is a partial fix upcoming at TR part, but the way Stockpile handle inventory is incompatible with most mods that can transfer items more than one at a time.

**Comment by modmuss50** [comment]
Closing, as I think its a stockpile issue now.
