### ISSUE TITLE
Right-clicking on blocks with omni-tool places tool as torch

### ISSUE THREAD

**Issue by WrongWeekend** [TechReborn/TechReborn#1942]
**Describe the bug**
Right-clicking any block with the omni-tool with torches in your inventory places the omni-tool as a torch and consumes it, resulting in the expensive tool being lost forever. I assume this is related to an undocumented torch-placing mechanic with the tool. In creative mode, the torches are placed, but the tool is not consumed.

**Steps to Reproduce**
- Equip an omni-tool
- Carry torches in the player inventory
- Right click a solid block with the omni-tool

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: Fabric
 - Fabric Loader: 0.7.3+build.176
 - Fabric API: fabric-api-0.4.27+build.286-1.15
 - Tech Reborn: TechReborn-1.15-3.2.0+build.87
 - Reborn Core: RebornCore-1.15-4.0.29+build.56

The bug was reproduced with only the above items installed.

**Additional context**
This bug was originally found using a build that had been provided via discord to fix an issue with the LESU, but was able to be reproduced with the latest stable build of Tech Reborn listed above.

**Comment by WrongWeekend** [comment]
Already covered by issue #136 in RebornCore

https://github.com/TechReborn/RebornCore/issues/136

**Comment by drcrazy** [comment]
Should be fixed starting from RC build #66 (Available on jenkins here: https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.15/lastSuccessfulBuild/artifact/build/libs/RebornCore-1.15-4.0.29+build.66.jar )
