### ISSUE TITLE
Multiblock holograms are unlit

### ISSUE THREAD

**Issue by jusvit** [TechReborn/TechReborn#1947]
When previewing multiblock layouts ingame, the blocks are dark and not representative of what they are.

![image](https://user-images.githubusercontent.com/4002351/71759443-35a99380-2f01-11ea-8184-9c7c226eaebe.png)

![image](https://user-images.githubusercontent.com/4002351/71759448-435f1900-2f01-11ea-820c-042b47c9b771.png)

**Comment by Prospector** [comment]
fixed this
