### ISSUE TITLE
Saw mill has wrong multiblock structure

### ISSUE THREAD

**Issue by DaFuqs** [TechReborn/TechReborn#1949]
**Describe the bug**
The wiki mentiones the sawmill machine has to be put on top of machine frames.
The hologram shows the frames all around the machine, though (missing offset?)

The machine doesn't work with the multiblock from the wiki ("incomplete multiblock") and I wasn't able to test the structure from the hologram, because the machine is not accessible that way.
I couldn't test if the machine 

**Screenshots**
![sawmill](https://user-images.githubusercontent.com/26429514/71767182-bcfb0500-2f09-11ea-8c15-db26d3141de7.png)

**Environment:**
 - Fabric
- Tech Reborn 3.2.1+build.107

**Comment by modmuss50** [comment]
seems like the offset is incorrect, should be an easy fix.

**Comment by modmuss50** [comment]
Fixed, dont forget to put the water in the center of it.
