### ISSUE TITLE
TO_DO : Easy mode IC2 classic e-net compatibility

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#195]
Gonna test it, but I doubt it works, basically easy mode e-net is a feature in IC2 classic that removes explosions from it's machines when they are overcharged with a higher voltage, instead the machines will just stop accepting power ^-^

**Comment by Carbon-Ghost** [comment]
Note this is kinda important, as it might create problems in some cases...

**Comment by gigabit101** [comment]
so no explosions ??

**Comment by modmuss50** [comment]
Does it work?

**Comment by Carbon-Ghost** [comment]
No, easy mode E-net is usual e-net etc.. but instead of explosions, a more softcore method of voltage is applied, basically machines or cables that receive a voltage too high won't accept power.

**Comment by Carbon-Ghost** [comment]
As the tester of IC2 classic, I can confirm it works so far with : ARS, RC, AE2, Mekanism and some addons of IC2 exp.

**Comment by modmuss50** [comment]
We use the ic2 API, unless we are doing something wrong it's not our problem.

**Comment by Carbon-Ghost** [comment]
Gonna test, but in pure theory it should work, my concerns is the TechReborn custom explosion thingies, but will do basic tests..

**Comment by modmuss50** [comment]
Custom explosions are for when it rains on a machine, not for too mutch power.

**Comment by Carbon-Ghost** [comment]
kk, gonna test compat, last time I checked ( alpha ) it didn't worked...

**Comment by modmuss50** [comment]
Im closing this as I dont think it would be our falult

**Comment by Carbon-Ghost** [comment]
Kk
