### ISSUE TITLE
Upgrading tools removes enchantments

### ISSUE THREAD

**Issue by DaFuqs** [TechReborn/TechReborn#1952]
Low priority, if not intended.

Upgrading the drill and other tools starts them out as "new" items, regarding of nbt of the previous tool. Since vanilla doesn't support nbt crafting, I guess? I have seen a NBT crafting library for fabric around, maybe that could help.

**Environment:**
- Fabric
- Tech Reborn 3.2.1+build.107

**Comment by modmuss50** [comment]
Fixed power with:

https://github.com/TechReborn/TechReborn/commit/bc47a03451e2d49e3791516d1835a5a2640d5155

**Comment by modmuss50** [comment]
Enchatments are a bit more of a pain, need to come up with a good way to check to see if the items should try and take the ingredients enchatments.

**Comment by Prospector** [comment]
Shoot, wrong reference. This one wasn't fixed

**Comment by LegendLZD** [comment]
I have a suggestion about this.
I hope this feature can be worked on Tech Reborn 1.12.2
