### ISSUE TITLE
Make fluid storage tanks upgradeable

### ISSUE THREAD

**Issue by WrongWeekend** [TechReborn/TechReborn#1953]
The new fluid storage blocks can only be created by lateral conversions from item storage blocks from an equivalent tier, and lower tier tanks cannot be upgraded directly to higher tier tanks. I believe that there should be crafting recipes to use a tank to craft the next tier of tank similar to how the item storage blocks are upgraded.

The new tank upgrade tree could start with the basic storage tank or by creating a crude storage tank made with fluid cells and iron ingots.

**Comment by Prospector** [comment]
this would be rather hard without changing the current recipes

**Comment by Sturmlilie** [comment]
+1 for a crude storage tank, maybe just a barrel surrounded with rubber for insulation (barrels in real life are used for fluids too). In early game basic tank units are unnecessarily expensive and way too large at the same time.
