### ISSUE TITLE
Cant Craft a Battery 1.15-3.2.1+build.107 

### ISSUE THREAD

**Issue by HenryChelt** [TechReborn/TechReborn#1966]
**Describe the bug**
I cant craft a battery,
I've reinstalled still the problem

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/59744162/72176233-e1f1eb00-33d5-11ea-95ba-804ba16c55fd.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15
 - Mod Loader: fabric

**Comment by drcrazy** [comment]
Wrong recipe. Check REI for correct one. It was changed recently.
