### ISSUE TITLE
Can't enchant armor at the enchanting table

### ISSUE THREAD

**Issue by coco9515** [TechReborn/TechReborn#1974]
**Description**
Can't enchant armor from this mod at the enchanting table.

**Steps to Reproduce**
- Take any armor piece (bronze / ruby / peridot / sapphire)
- Place in the enchanting table
- No enchantements are proposed

**Screenshots**
![image](https://user-images.githubusercontent.com/42412909/72223354-1698aa80-356e-11ea-98ad-b7dd28f80397.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: fabric loader

**Logs**
https://pastebin.com/h8ztphiP

**Additional context**
I try it on a server, then on a solo map : same result.

**Comment by Prospector** [comment]
A fix for this will be in the next release
