### ISSUE TITLE
The tags in TR use singular names instead of plural, the convention 

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#1976]
This is a difficult change since every recipe using TR tags needs to change as well

**Comment by modmuss50** [comment]
All of the tags where auto generated and use the same as cotton resources. Can you provide a specific example where its wrong?

**Comment by modmuss50** [comment]
see: [https://github.com/CottonMC/CottonResources/tree/master/src/main/resources/data/c/tags/blocks](https://github.com/CottonMC/CottonResources/tree/master/src/main/resources/data/c/tags/blocks)

**Comment by Prospector** [comment]
Damn, they did it wrong too. See vanilla for plural convention.

**Comment by modmuss50** [comment]
No need to change it.
