### ISSUE TITLE
Include Sweet Berries as ingredients for plant balls & methane cell

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1977]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Sweet Berries are a new vanilla foodstuff.  It has no uses in TR yet.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by modmuss50** [comment]
Seems easy enough

**Comment by WrongWeekend** [comment]
The same should be applied to kelp as well.
