### ISSUE TITLE
Crash with IC2 classic

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#198]
Seems like latest version have a crash with IC2 classic when I open the creative tab, I think it's caused by the same reason as before ;_; http://paste.ee/p/BfYMU

PS : Not related but a test server for IC2 classic and TechReborn ( and another mod that is a spiritual successor of AE1 named Logistic Storage once it's released ) will be created soon for testing purposes, you are ofc invited ;)

**Comment by modmuss50** [comment]
Ok, I can confirm something is broken, I cannot event get the game to load, https://gist.github.com/modmuss50/f77e10a52428cc8f4300

**Comment by modmuss50** [comment]
Im not sure if im breaking something, or ic2 classic is broken

**Comment by Carbon-Ghost** [comment]
IC2 never had this problem before... Speiger told me that it probably was on your side but yeah :/

**Comment by modmuss50** [comment]
I will take a closer look when I get get the game to load with classic

**Comment by Carbon-Ghost** [comment]
kk :D

**Comment by Speiger** [comment]
That bug is on your Side modmuss50 and the crash with IC2 Classic is because you updated the dev version of IC2 Classic but did not reset the config...
