### ISSUE TITLE
Ranged weaponry

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1981]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd love the addition of energy based ranged weaponry.  Not energy based in the sense of a laser gun persé.  I'm thinking more in the direction of three tiers of techified bows and crossbows, from standard, advanced to industrial tech level.  These weapons would have increase fire rate and damage as their tier goes up.  Instead of ammo they'd use stored energy, and/or an alternative ammo like iron nuggets (thinking crossbow-railgun).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lxn12596** [comment]
space-broken gun

**Comment by WrongWeekend** [comment]
One option would be an electrically operated crossbow loaded made from carbon fiber and other synthetic materials that would have the same operating mechanics and enchantment options as the vanilla crossbow, but with greater power.

Another would be some sort of electric compressor-blowgun or air rifle that can fire arrows or other throwable objects like splash potions or snowballs with greater range and accuracy, or even activated TNT like out of a dispenser. This weapon would probably use some sort of internal inventory to be manually loaded with a stack of projectiles.

As for regular bow-type weapons, some sort of modern compound bow would work as a stronger durability-based alternative although I can't think of a way to tie in electric power in a way that makes sense.

**Comment by drcrazy** [comment]
Not as for now. Maybe in some distant future. Another option is to have someone to create PR on this.
