### ISSUE TITLE
[main/FATAL]: Reported exception thrown!

### ISSUE THREAD

**Issue by toddchou** [TechReborn/TechReborn#1982]
Everything works when TechReborn-1.15-3.2.1+build.107.jar is installed.
TechReborn-1.15-3.2.2+build.131.jar is loaded I will encounter "[main/FATAL]: Reported exception thrown!"

Frequency: 1/1
How to Reproduce:
1. Added TechReborn-1.15-3.2.2+build.131.jar to MultiMC5 on Windows and Linux 
2. Minecraft client on Windows joined the Linux server
3. Craft new blocks on Crafting Table.
4. Client will disconnect from the Linux server.
5. Linux server still is alive.

Client logs is https://paste.ee/p/J9yKb

**Comment by modmuss50** [comment]
Seems like a version mismatch between RC and TR.

You have an old version of RC, use this one: https://www.curseforge.com/minecraft/mc-mods/reborncore/files/2858044

**Comment by toddchou** [comment]
My issue is fixed by using TechReborn-1.15-3.2.2+build.131.jar and  RebornCore-1.15-4.1.1+build.74.jar.
Thank you for the help.
