### ISSUE TITLE
Crash when trying to search compressed air in creative menu. 

### ISSUE THREAD

**Issue by AltimusX** [TechReborn/TechReborn#1985]
I was actually looking for something with om in it but the log shows it was a failure to render compressed air, at first I thought it was that mod causing it but it was none of those mods causing it. 
Closest thing I can think is maybe it is NBT that is changing it.

https://pastebin.com/adYH1uiV

This is the last bug before we have a 1.15.2 pre 2 stable branch for Fabric: All in One.

**Comment by modmuss50** [comment]
Ah, I need to release the 1.15.2 version

**Comment by modmuss50** [comment]
Just pushed out a new version that should be compatible with 1.15.2 and 1.15.1
