### ISSUE TITLE
Rubber sappling crash

### ISSUE THREAD

**Issue by ponoyoshi** [TechReborn/TechReborn#1989]
**Describe the bug**
If you plant a rubber sappling, then wait for it to grow or use some bone meal the game will instantly stop.

**Steps to Reproduce**
- Get a rubber sappling
- Place it on the ground
- Use some bone meal on it or wait it for grow

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: fabric

**Logs**
[Logs file](https://github.com/TechReborn/TechReborn/files/4093487/latest.log)

**Comment by modmuss50** [comment]
humm, it seems the 1.15.2 version isnt backwards compatible. I will need to look into this. For now use 1.15.2 or an older version
