### ISSUE TITLE
Wiki Completion

### ISSUE THREAD

**Issue by milkev** [TechReborn/TechReborn#2002]
**Is your feature request related to a problem? Please describe.**
Finish the wiki. Its annoying to want to make something, but have no information aside from intuition. eg, I know what the wires do (transfer energy) but how fast does anything other than copper transfer energy?  and the cloaking device, id assume it makes you invisible, or some equivalent, but how much energy does it hold? how much does it consume? i dont know, and because of this i dont hold any real interest in making it to find out, and if i did make it i still wouldnt know exact things like energy storage.
ive been watching the wiki for a couple weeks as i go through my own world and want to know what things are for, and i havent noticed anything getting info pages.

**Describe the solution you'd like**
Finish the wiki.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/22010128/73039631-060ced80-3e14-11ea-82e4-4360ff26df58.png)

**Comment by drcrazy** [comment]
While wiki is not in best shape you can use creative mode to check particular items

**Comment by ghost** [comment]
@drcrazy can I somehow contribute to the Wiki?

**Comment by drcrazy** [comment]
Sure. Ping me in discord https://discord.gg/teamreborn

**Comment by JessiAuro** [comment]
I'd argue that documentation for the mod should be completely overhauled to be managed in source control. This would offer several benefits:
- Everything is in one place
- Contributing to/updating the docs would use the same tooling as the developers (git, github, CI deployments, etc)
- The documentation could be built along with the source code, using a templating system like Jinja and/or Jekyll.

Crafting recipes, localization, etc is already defined in a structured manner in the resources folder, so it wouldn't be a major technical feat to generate the documentation from that data using templates.

Don't get me wrong, setting this up would be quite a bit of work, but once it's going it will just magically adjust to any changes made to crafting recipes, translation strings, etc, taking a lot of the tedium out of maintaining the documentation.

This would also allow you to have properly versioned documentation, so the user can always be sure that what they are reading is intended for the version of the mod they are using. This is the strategy a lot of modern open source projects use.

I'd be surprised if something like this doesn't already exist for minecraft mods, but I haven't really looked into that.

**Comment by ghost** [comment]
If I understand you right, this would mean the wiki can be indirectly updated through pull requests?  I'd be happy to help out with his, if your suggestion gets accepted.

**Comment by JessiAuro** [comment]
> If I understand you right, this would mean the wiki can be indirectly updated through pull requests? I'd be happy to help out with his, if your suggestion gets accepted.

What I'm proposing is largely throwing the wiki out entirely for documentation that is generated directly from the codebase.

The documentation wouldn't be a separate entity that has to be babysat whenever the code changes, the documentation would be the code itself.

What I'm envisioning would probably be a Jekyll site with a bunch of templates for blocks, items etc into specifics like machines, wires, tools, etc, with all the details (recipes, names) being derived from the resource data of the mod.

You could then simply attach any additional information to the template for a specific item/block, and let the templating engine do all the hard work of generating the website itself.

After it's set up, the only time you would have to touch the templates is when a new item is added or functionality is fundamentally changed in a way that needs to be explained. Everything else would be automated.

**Comment by ghost** [comment]
Wow!  That sounds impressive.  I didn't know this was a thing. :-D
Still, if the dev team doesn't think they have time for this, I'd be happy to help out a few hours a day to migrate all additional information from the current wiki.

How difficult would it be to translate the generated information to an always-up-to-date in-game book?

With a version for 1.12, 1.15 and soon 1.16, is it feasible to separate the version-specific information without too much duplicate work?

**Comment by JessiAuro** [comment]
Depending on my free time the next week, I might play around with this idea in my own branch to sort of provide a demonstration of what I'm talking about.

An in game book would be possible, but might not have a lot of overlap, or would require a mod capable of parsing the templates which might be more pain than it's worth. I would need to do a lot more digging before I could really judge the practicality of that.

In the long term it might make more sense to write a module for REI that could load additional documentation from the mod's resources but that's outside the scope of my current knowledge of minecraft modding.

Backporting it to any version of the mod post-flattening probably wouldn't be too hard but would likely be more work than it is worth.

**Comment by drcrazy** [comment]
Feel free to play with it. I will be happy to review your findings and apply them to TR if possible.

**Comment by JessiAuro** [comment]
> Feel free to play with it. I will be happy to review your findings and apply them to TR if possible.

Okiedoke, looking around [Orchid](https://orchid.run/) seems very promising and it supports plugins. It's written in Java so I'd have to do some learning there but should integrate nicely into the build process.

Might even be able to utilize some of fabric's development libraries to make my job easier.

The ideal scenario here would be the development of a general purpose plugin for Orchid that could be used by any fabric mod to easily generate documentation.

All of this is technically possible, it's just a matter if my motivation holds up lol.

**Comment by modmuss50** [comment]
This seems to be an ongoing convosation that would be best suited in the wiki channel on the discord server. (Poke me on there if you want adding).

Sadly I dont have hours of time to make the wiki perfect, and my writing skills are far from great. 

Closing this "issue" as this isnt an ideal place to discuss the changes.
