### ISSUE TITLE
Fractional values are incorrect after 10M value

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2006]
**Describe the bug**
Fractional values are incorrect after 10M value, to be precise they're always at 0

**Steps to Reproduce**
- Grab anything that can be charged up to the value that's more than 10 million E
- Charge until the integral part of the value becomes two-digit
- Look how the fractional part stays at 0 all the time when item's being charged/discharged
**Screenshots**
![2020-01-24_23 27 56](https://user-images.githubusercontent.com/50599445/73101758-77769a00-3f01-11ea-9701-eb8751c21b44.png)
![2020-01-24_23 29 50](https://user-images.githubusercontent.com/50599445/73101768-7c3b4e00-3f01-11ea-877b-37aeaf35903a.png)
While it says 10.0M it can easily be at 10.9M because it's been charging for a while
Same thing with the Charge'O'Mat 
![2020-01-24_23 28 12](https://user-images.githubusercontent.com/50599445/73101867-b0167380-3f01-11ea-892a-1d2210a23cf0.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: fabric
 - Mod Version: 1.15-3.3.1,  build 170

**Logs**
 - No actual logs required

**Additional context**
 - No additional context

**Comment by modmuss50** [comment]
Fixed with https://github.com/TechReborn/RebornCore/commit/35797d72140e7cf9164e600b3a06db9a0f73f5f3
