### ISSUE TITLE
Crash when not using 16x texture pack

### ISSUE THREAD

**Issue by MrBretze** [TechReborn/TechReborn#201]
log: http://hastebin.com/olucojavop.tex

juste reload the resource pack

**Comment by modmuss50** [comment]
Did you have a resource pack installed?

**Comment by modmuss50** [comment]
Or a different resolution one?

**Comment by MrBretze** [comment]
I have tested to installed the faithful resource pack in 32x32 dimension

**Comment by MrBretze** [comment]
My try catch fix this, i dont no why

**Comment by modmuss50** [comment]
It would, but that will break the lesu connected textures

**Comment by modmuss50** [comment]
The issue is when the textures are a different size. It is using a 32x32 lapis texture, with a 16x16 boarder

**Comment by modmuss50** [comment]
I've pulled your fix, but I need to get a proper fix for this, as now the connected textures for the lesu will be broken
