### ISSUE TITLE
Most TR tools can be used to extract sap from rubber trees.

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2013]
**Describe the bug**
All TR tools which don't strip logs, can be used to extract sap from rubber logs.  This feature makes treetaps relatively useless.

**Steps to Reproduce**
- Make a TR powered tool
- Right click a rubber log to tap it
- Success

**Environment (please complete the following information with the version):**
 - Minecraft:  1.15.2
 - Mod Loader: Fabric
 - TR: TechReborn-1.15-3.3.1+build.167 / RebornCore-1.15-4.2.1+build.91

**Comment by modmuss50** [comment]
easy fix
