### ISSUE TITLE
QoL Enchantments for electric treetaps

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2014]
**Is your feature request related to a problem? Please describe.**
This is a quality of life request.  Being able to get more yield from rubber trees with the electric treetap seems like a good investment while saving up for a greenhouse.  As an added bonus, this would translate to there being less rubber logs in the world, and less checks needed by the server to spawn sap.

**Describe the solution you'd like**
Being able to enchant the electric treetap with a fortune book (anvil only) would allow players to save time and build smaller rubber farms.  Optionally balancing it further by using more stored power with a bigger harvest.

**Describe alternatives you've considered**
Making Silicon more readily available would allow players to skip rubber entirely and use the Assembling Machine to craft Electronic Circuits instead.  As it is, Silicon is relatively hard to get large quantities of.  With sand being its most abundant available source, 32 pieces are required for a single silicon plate.  If the sand method is still preferred, I'd like to suggest the inclusion of a machine that can generate cobble.

**Additional context**
My current rubber farm, yielding about 6 stacks of rubber after extraction.  Just enough for one stack of Electronic Circuits.
![image](https://user-images.githubusercontent.com/918422/73131317-44b7c900-4009-11ea-93bd-f76bd3affc14.png)

**Comment by drcrazy** [comment]
Craft wire mill. It will reduce rubber usage

**Comment by Linguardium** [comment]
i would like to see automation involved in this. 
If you get to the point where you are harvesting entire stacks of circuits at a time, it is clear automation should be happening.
what about a constant tap that pulls sap out as a fluid over time and then a condenser/dryer that solidifies buckets/partial buckets into sap. this would allow one to constantly build a supply of sap.

iirc, there is also the option of automating the tree farm and breaking down the wood for sap by using bonemeal (like all other vanilla tree farms).

**Comment by jusvit** [comment]
Okay I've implemented resin basin, the premise behind it is you place it on a rubber tree and it'll automatically harvest any rubber and deposit it to a container underneath it. It also has a 40% chance to give two sap instead of one.

Later on, we'll probably do some sort of tree farm so you can just extract the rubber.

![image](https://user-images.githubusercontent.com/4002351/86903834-368edc80-c153-11ea-9a5a-d0dc5419a3a5.png)
