### ISSUE TITLE
Unable to apply Unbreaking via the Anvil

### ISSUE THREAD

**Issue by LuminaSapphira** [TechReborn/TechReborn#2016]
**Describe the bug**
Unable to apply certain enchantments to electric tools via the anvil.

So far, this just seems to include Unbreaking. (I'm fairly sure this isn't intended since there seems to be code handling unbreaking for the tools).

**Screenshots**
![image](https://user-images.githubusercontent.com/1103450/73141413-a439c700-4051-11ea-89e7-3fcf66471560.png)
( Book is Unbreaking III )

**Environment**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric v0.7.6+build.179
 - Fabric API v0.4.29+build.290-1.15
 - Tech Reborn v3.3.1+build.167
 - Reborn Core v4.2.1+build.91

**Additional context**
I've confirmed that Unbreaking is able to be applied via the Enchanting Table.

This also affects the `/enchant` command.
![image](https://user-images.githubusercontent.com/1103450/73141457-2de99480-4052-11ea-9f16-c529beed9990.png)

**Comment by Prospector** [comment]
Mojang changed the enchant so tools without durability cannot have unbreaking anymore. It sorta makes sense tbh. Especially since the tools can't break anyway, it's probably unnecessary to have unbreaking make them last longer.

**Comment by drcrazy** [comment]
On the other hand unbreaking wildly used to not consume power. 
Should we try to apply it anyway?

**Comment by LuminaSapphira** [comment]
The unbreaking enchantment is able to be applied via the enchanting table though - and it is used in the code to reduce power cost by adding a chance to not consume power on usage. If Unbreaking isn't desired for this effect, is it possible to add a new enchantment for powered tools that specifically reduces power draw?

**Comment by Prospector** [comment]
Perhaps but power isn't exactly hard to acquire tho.

**Comment by LuminaSapphira** [comment]
Agreed, though it could be an earlier-game way to slow down power drain so recharging as often isn't necessary prior to getting the charging packs

**Comment by modmuss50** [comment]
This is an issue, but there isnt a really a clean way to fix it sadly. I dont think its big enough to worry about for now. Sorry about that.
