### ISSUE TITLE
Crash when placing Auto Crafting Table

### ISSUE THREAD

**Issue by deagahelio** [TechReborn/TechReborn#2017]
My game crashes every time I try to place down an Auto Crafting Table. I'm running the latest 1.12.2 version

Crash log: https://paste.dimdev.org/ugivugofiw.mccrash

**Comment by deagahelio** [comment]
Nevermind, seems like it was fixed here already.

**Comment by DevTimur** [comment]
You sure about that?
https://paste.dimdev.org/igimutasem.sql
That's with version **TechReborn-1.12.2-2.26.3.1066-universal**
Can you re-open issue? So I don't make duplicates.

**Comment by drcrazy** [comment]
It is fixed in dev. Will be released in a couple of days, I hope.
