### ISSUE TITLE
Auto Crafting Table places facing wrong way (or sides are confused)

### ISSUE THREAD

**Issue by joncooke** [TechReborn/TechReborn#2021]
Minecraft: 1.15.1
Build: 131

The front side of the Auto Crafting Table (ACT) seems to be the one with the 9 small white squares on the top face in the near right position.
Normally when you place a block it faces you automatically.
However when placing the Auto Crafting Table that side isn't facing the player, so if you place the table down and start setting up the auto input/output then you'll set the wrong sides as input/output.

Otherwise once you work out which is the real front face the input/output works fine.

**Comment by modmuss50** [comment]
Seems to be working as intended for me. It could be made more clear by having a front texture but for now I think its fine.
