### ISSUE TITLE
LESU's capacity is limited by 2.2GE and 4293 storage blocks.

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2024]
**Describe the bug**
LESU works fine until you reach 4293 lesu storage blocks, when you place 4294th block it goes back from 2.2GE to 0. (limited by 32 bit int)

**Steps to Reproduce**
- Place LESU Controller
- Now connect 4294 blocks to it

**Screenshots**
An animated screenshot:
https://vimeo.com/388701603

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1 (but it doesn't really matter)
 - Mod Loader: fabric

**Logs**
No logs

**Additional context**
No

**Comment by ghost** [comment]
I also suggest adding Tera (T), Peta (P) and Exa (E) symbols for bigger values.

**Comment by drcrazy** [comment]
-640k-  4k lesu storage blocks should be enough for anybody ^_^
