### ISSUE TITLE
Tech reborn + Flymod = Client failure to load

### ISSUE THREAD

**Issue by AltimusX** [TechReborn/TechReborn#2025]
This pastebin has all the relevant data.
https://pastebin.com/gWagvdsy

It's something to do with  fly mod calling something in statement library that conflicts with some code in tech reborn.

Any version of flymod and any version of tech reborn causes this crash.

**Comment by modmuss50** [comment]
Can you try with just TR and the fly mod you are using? as this crash doesnt seem to have anything to do with either.

**Comment by modmuss50** [comment]
Closing as no response.
