### ISSUE TITLE
Allow the use of End Crystals in the Implosion Compressor

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2027]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently the only catalyst that can be used in the Implosion Compressor is TNT.  However, End Crystals are also an explosive, both more powerful and expensive than TNT to craft.  Because of this, I'd love it if End Crystals could be used as an alternative to TNT in the Implosion Compressor, with half or 1/4th the amount needed than TNT.

**Describe alternatives you've considered**
N/A

**Additional context**
End Crystal wiki page: https://minecraft.gamepedia.com/End_Crystal

**Comment by JessiAuro** [comment]
I really like this idea, I find I never really enjoy the tedium of gathering the resources necessary for crafting large amounts of TNT, so I would appreciate having more flexibility there.
