### ISSUE TITLE
Add catalyst option to minetweaker

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#203]
Self explainatory, I want to remove a bunch ( a lot ) of recipes that causes EMC loops, and need the assembler to add a recipe, I need 1 diamond + Quantum Manipulator = 1 quantum infused diamond but the manipulator is not consumed as it's a catalyst. 

TLDR why I need that xD
( and basically do the same with 1 nether star 1 Quantum Manipulator = 1 quantum infused nether star and then you combine the 2 in an assembler again to have an alchemical diamond used for project E recipes ).

**Comment by Carbon-Ghost** [comment]
And how to set BF temperature requirement + smelting ?

**Comment by modmuss50** [comment]
mods.techreborn.blastFurnace.addRecipe(<minecraft:glass>, <minecraft:grass>, <minecraft:diamond>, <minecraft:dirt>, tickTime, eu/tick, neededHeat);

**Comment by Carbon-Ghost** [comment]
so glass + grass = diamond + dirt ? and may I get all the machines syntax ? I will make some documentation ;) 

And is it possible to have a catalyst in the Assembler ?

**Comment by modmuss50** [comment]
http://www.blamejared.com/modtweaker/ All the documentation is there.

catalyst is it possible with other machines? It may be possible

**Comment by Carbon-Ghost** [comment]
I don't think so, I just know new GT adds the option to have a catalyst element in assemblers... And I need one ( basically doesn't get consumed or stays by going as an output ).

**Comment by modmuss50** [comment]
It may be possible, I will look into it at some point

**Comment by Carbon-Ghost** [comment]
:3

**Comment by Barhandar** [comment]
That's what .reuse() overloads are for.

**Comment by modmuss50** [comment]
It needs to be in minetweaker not in code

**Comment by modmuss50** [comment]
Actully you are right, MT has this built in I just need to add support for it

**Comment by Carbon-Ghost** [comment]
But will it work in a machine ? Because normally .reuse is usually for the crafting table and is kinda bugged especially with autocrafting systems, and normally returns items to inventory, so you sure it will work ?

**Comment by Barhandar** [comment]
.reuse() keeps the item in place in crafting grid, .giveBack() drops it into inventory, either override the item's regular crafting behavior. And whether it'll work in a machine depends on said machine's code.

**Comment by Carbon-Ghost** [comment]
Yes but in vanilla crafting table iirc it give back the item when you finish the crafting, either way was very bugged with autocrafting systems...

**Comment by modmuss50** [comment]
I will have to look at the Minetweaker API a bit more. Im not very familiar with it so if other things are missing feel free to tell me.

**Comment by Carbon-Ghost** [comment]
kk

**Comment by modmuss50** [comment]
This requires a massive rework of the machine crafting system. It will happen sometime but not soon

**Comment by Carbon-Ghost** [comment]
Kk, gonna close that for now, it's ok for me as I can find an alternative ;)
