### ISSUE TITLE
[MC 1.15.2 - TechReborn 3.3.3+build.182] Possible Blocks Conflict

### ISSUE THREAD

**Issue by Dragonsissiy** [TechReborn/TechReborn#2031]
**Describe the bug**
Ores and possibly other items conflict with Simple BC Pipes. The ores will still be present in the game, but when looking at them via REI, mouse-over or MC creative menu they don't exist.

**Steps to Reproduce**
- 1) Install Simple BC Pipes
- 2) Look at ores in game, try to spawn with creative mode, try to use REI menu for the ores and cables.

**Screenshots**

![CurrentModsList](https://user-images.githubusercontent.com/60621847/74003489-9d4f6600-4927-11ea-88f3-12442173620b.PNG)

![LookingAtMCIron](https://user-images.githubusercontent.com/60621847/74003272-e18e3680-4926-11ea-9859-afda177bbbb5.png)

![LookingAtTR_TinOre](https://user-images.githubusercontent.com/60621847/74003277-e6eb8100-4926-11ea-8d3a-c5d612cd1e71.png)

![LookingAtMenu_MissingBlocks](https://user-images.githubusercontent.com/60621847/74003282-ece16200-4926-11ea-924d-49c515baa7cc.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
No crashes as of yet.

**Additional context**

Thank you for making this mod! I really appreciate it and use it heavily. I was excited to finally have a pipe mod to go along side this, only for these two mods to conflict. I wanted to include it here as well in case a collaborative effort becomes necessary. Please let me know if there is any other information I can try to provide. 

Other thread for reference:
https://github.com/AlexIIL/SimplePipes/issues/36

**Comment by AlexIIL** [comment]
After some debugging it turns out this is an issue with how SimplePipes scans blocks for facades - essentially it scans the block just after it is registered (but before the item is registered)  and calls `Block.asItem()`, which then looks up the item to find... nothing. It then caches nothing for next time (woops) and then the correct item is registered.

So it's a SimplePipes bug.

**Comment by modmuss50** [comment]
Thanks for looking into this. Glad we found the issue.
