### ISSUE TITLE
1.15.x Add Tech Reborn ores to the vanilla blast furnace.

### ISSUE THREAD

**Issue by furtabs** [TechReborn/TechReborn#2037]
**Is your feature request related to a problem? Please describe.**
Let Tech Reborn Ores smelt in the Blast Furnace from vanilla. 

**Describe the solution you'd like**
Add tech reborn ores to the vanilla registry

**Describe alternatives you've considered**
Hacky Datapacks Magic

**Additional context**
All the Mods Fabric modpack

**Comment by JessiAuro** [comment]
This should be possible using datapack json (looking into the specifics atm) but manually writing out the JSON is a pretty huge waste of time when it would just be the standard smelting values halved.

A much smarter way of handling it would be to use a gradle build task to generate the blasting recipes from the standard smelting ones. I'll poke at this a bit, I need to learn about the nuances of Gradle anyways and this seems like a somewhat simple means of doing so.

FYI, datapack magic isn't hacky, it's a core feature of the official game 😉.

**Comment by drcrazy** [comment]
Closed by Jessifir
