### ISSUE TITLE
Industrial Grinder missing recipe in REI GUI

### ISSUE THREAD

**Issue by ahkui** [TechReborn/TechReborn#2042]
**Describe the bug**
REI recipe is missing

**Screenshots**
<img width="519" alt="image" src="https://user-images.githubusercontent.com/14049597/74546791-1719cc00-4f86-11ea-9c7c-568d0f8538d8.png">

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric

**Comment by drcrazy** [comment]
Do you have other mods installed? Can you mouseover fluid slot, please?

**Comment by ahkui** [comment]
mouseover is show like empty slot
<img width="602" alt="Screen Shot 2020-02-18 at 11 05 53 AM" src="https://user-images.githubusercontent.com/14049597/74700581-f4660c80-523e-11ea-98fd-f560cd006cdb.png">

**Comment by ahkui** [comment]
my mod list:
- _ding-3.0.0.jar
- _extra-pressure-plates-1.1.3.jar
- _Flamingo-1.15-1.16.jar
- _i-blame-x-1.0.1+1.14.4.jar
- _ninjatips-1.0.31.15.jar
- _NonCorrelatedExtras-0.2.1.jar
- [1.15.2]+SuperAxes-1.0.4.jar
- adabraniummod-1.0.1-1.15.2.jar
- Adorn-1.7.1+1.15.2.jar
- angelring-1.15.1-1.0.jar
- appleskin-mc1.15-fabric-1.0.8.jar
- Aquaculture-1.15.2-2.0.8.jar
- aquarius-1.4.0+1.15.jar
- bambootweaks-1.15.2-1.1.3.jar
- BBOutlineReloaded-1.0.14-1.15.1-fabric.jar
- better-wither-skeletons-1.0.0.jar
- bigbuckets-1.1.0.jar
- blockus-1.3.2.jar
- BowInfinityFix-1.15.2-fabric-rv8.jar
- bucket-hat-1.0.1.jar
- bulkyshulkies-1.0.4.jar
- bunch-o-trinkets-1.0.0.jar
- CleanView-1.15.2-v1-fabric.jar
- climaticworldtype-1.1.4.jar
- coloredflames-1.1.9r1+1.15.2.jar
- compostrecipes-1.1.0.jar
- conv-things-0.4.0.jar
- corail_woodcutter-fabric-1.0.0-1.15.1.jar
- Couplings-1.3.1.jar
- craftingpad-1.0.4.jar
- creeper-spores-1.3.3.jar
- CustomSkinLoader_Fabric-14.12-SNAPSHOT-109.jar
- data-loader-1.1.0+mc1.14.4.jar
- demeter-1.1.3.jar
- diggusmaximus-1.2.6.jar
- DungeonCrawl-1.15.2-1.6.1.jar
- durabilityviewer-1.15.2-fabric0.4.23-1.7.jar
- dynamic-fps-1.1.0.jar
- easierchests-1.15-fabric0.4.23-1.4.jar
- elytra_swap-1.2.2-1.15.2.jar
- EnchantedToolTips-1.2.4.jar
- endfestation-1.15.1-1.0.0.jar
- exotic-blocks-mc115-1.2.112.jar
- exotic-matter-mc115-1.17.295.jar
- expandedstorage-3.8.34+1.15.2.jar
- extradoors-1.4.2-1.15.jar
- fabriblocks-1.1.7.jar
- fabric-api-0.4.32+build.292-1.15.jar
- fabric-diagonal-panes-0.2.0.jar
- fabric-drawer-3.2.0-1.15-pre1.jar
- fabric-installer-0.5.2.39.jar
- fabric-language-kotlin-1.3.61+build.1.jar
- fabric-title-changer-1.0.1.jar
- fabricmod_VoxelMap-1.9.14_for_1.15.1.jar
- fairenchanting-1.1.1.jar
- fancyfountainpassage-1.3.1.jar
- fermion-mc115-1.14.154.jar
- Flonters-1.0.2+1.15.1.jar
- floradoubling-1.15.2-20w06a-1.0.0.jar
- furniture-7.0.0-pre16-1.15.1.jar
- GamemodeOverhaul-1.0.1.6.jar
- glassdoor-1.4.3.jar
- glassential-fabric-1.15.1-1.1.3.jar
- glowingbeds-1.0.2.jar
- godown-0.1.0.jar
- HealthOverlay-1.15-2.2.10.jar
- hollowlogs-1.0.0.jar
- horse-stats-vanilla-1.0.4.jar
- Hwyla-fabric-1.15.2-1.9.20-71.jar
- i-am-very-smart-1.5.0+mc1.14.4.jar
- illuminations-0.4.0-1.15.1.jar
- imbuedtorches-1.1.0.jar
- improved-stations-1.2.4.jar
- InventorySorter-1.6.3.jar
- irishwolves-1.0.0.jar
- itemscroller-fabric-1.15.2-0.15.0-dev.20200212.183513.jar
- kayak-0.1.1.22.jar
- libblockattributes-all-0.6.4.jar
- libcd-2.2.2+1.15.2.jar
- LibGui-1.4.0.jar
- libmultipart-all-0.3.4.jar
- libnetworkstack-base-0.3.4.jar
- LightOverlay-4.2.jar
- linkedstorage-1.1.1.jar
- lithium-mc1.15.2-fabric-0.3.1.jar
- llamasteeds-2020.02.08.jar
- malilib-fabric-1.15.2-0.10.0-dev.20+arne.2.jar
- Mambience-1.0.0.jar
- minihud-fabric-1.15.2-0.19.0-dev.20200121.203515.jar
- mobropes-1.15.2+1.0.2.jar
- modmenu-1.8.5+build.23.jar
- moreberries-1.2.3.jar
- mousewheelie-1.4.0+1.15.2-pre1.jar
- notenoughcrashes-1.2.3+1.15.1.jar
- phosphor-mc1.15.1-fabric-0.3.6.jar
- RebornCore-1.15-4.2.2+build.97.jar
- Retro-Exchange-1.15-3.1.0.jar
- RoughlyEnoughItems-3.4.4.jar
- SereneSeasons-1.15.1-3.0.0.44-universal.jar
- sheet-lib-1.4.0+1.15.2.jar
- shulkerboxtooltip-1.4.5+1.15.jar
- shulkercharm-1.1.2+1.15.2.jar
- simpleteleporters-2.2.0-1.15.jar
- SimpleVoidWorld-3.1.0.jar
- SmoothScrollingEverywhere-2.3.jar
- sneakthroughberries-1.15.2-20w06a-1.0.1.jar
- strongandfairanvils-0.3.0.jar
- Sweed-1.1.1.jar
- sweet-tooth-1.1.2-1.15.jar
- SwordEffects-1.1.1.jar
- TechReborn-1.15-3.3.4+build.189.jar
- terrestria-1.2.0.jar
- TheHallow-1.1.3-beta+1.15.1.jar
- Tooltipped-1.1.jar
- Torcherino-2.11.60+1.15.2.jar
- traverse-2.1.9+build.17.jar
- trinkets-2.4.1.jar
- trumpet-skeleton-fabric-1.1.1.jar
- vanilla-hammers_1.15.2-1.7.1.jar
- vanilla-toolsets-1.2.2.jar
- VanillaParts-1.1.2+1.15.1.jar
- VariablePaxels-1.15-1.0.2.jar
- villager-hats-fabric-1.15.0-1.0.0.jar
- WildWorld-1.2.0+1.15.jar
- working-scheduler-1.1.3-1.15-pre1.jar
- yet-another-gravestone-mod-1.2.1.jar

**Comment by modmuss50** [comment]
Im not sure what the issue is here?

**Comment by ahkui** [comment]
![Grinder 640 10fps](https://user-images.githubusercontent.com/14049597/76087624-8157e680-5ff1-11ea-8426-3ff34db0faa3.gif)

**Comment by serpi90** [comment]
> Im not sure what the issue is here?

As far as i understand, recipes for grinder do not show correctly.
Tested it on singleplayer and it works as expected:
![image](https://user-images.githubusercontent.com/5396311/76487873-932af680-6402-11ea-8daa-5826906dd6e3.png)

On multiplayer it does not:
![image](https://user-images.githubusercontent.com/5396311/76487926-b6ee3c80-6402-11ea-8eaa-d8ad61616377.png)
Neither the image nor the tooltip show on the fluid part of the recipe.

MC Version 1.15.2
## Client Mods:
- Adorn-1.8.0+1.15.2.jar
- appleskin-mc1.15-fabric-1.0.8.jar
- bambooeverything-1.15.2-1.0.0.jar
- betterthanmending-1.1.1.jar
- corail_woodcutter-fabric-1.0.1-1.16.jar
- durabilityviewer-1.15.2-fabric0.4.23-1.7.jar
- fabric-api-0.5.1+build.294-1.15.jar
- fabric-diagonal-panes-0.2.0.jar
- fabric-furnaces_1.15pre4-1.2.0.jar
- fabric-language-kotlin-1.3.61+build.1.jar
- fabricmod_VoxelMap-1.9.14_for_1.15.1.jar
- glassdoor-1.4.3.jar
- Harvest-1.14-fabric-1.0.4.jar
- Hwyla-fabric-1.15.2-1.9.20-71.jar
- inventoryprofiles-fabric-1.15.2-0.2.0.jar
- LightOverlay-4.3.jar
- mamiyaotaru
- modmenu-1.10.1+build.30.jar
- OfflineSkins-1.15.2-v1-fabric.jar
- okzoomer-2.1.2.jar
- orderly-1.2.1+build.4-1.15.jar
- phosphor-mc1.15.2-fabric-0.4.2.jar
- RebornCore-1.15-4.2.4+build.102.jar
- RoughlyEnoughItems-3.6.4.jar
- tdnf-mc115-1.8.69.jar
- TechReborn-1.15-3.3.5+build.196.jar
- terrestria-1.2.1+build.29.jar
- traverse-2.1.11+build.23.jar

## Server Mods:
- Adorn-1.8.0+1.15.2.jar
- appleskin-mc1.15-fabric-1.0.8.jar
- bambooeverything-1.15.2-1.0.0.jar
- betterthanmending-1.1.1.jar
- corail_woodcutter-fabric-1.0.1-1.16.jar
- Couplings-1.3.1.jar
- fabric-api-0.5.1+build.294-1.15.jar
- fabric-furnaces_1.15pre4-1.2.0.jar
- fabric-language-kotlin-1.3.61+build.1.jar
- glassdoor-1.4.3.jar
- Harvest-1.14-fabric-1.0.4.jar
- phosphor-mc1.15.2-fabric-0.4.2.jar
- RebornCore-1.15-4.2.4+build.102.jar
- RoughlyEnoughItems-3.6.4.jar
- sewing-machine-1.1.5_mc-1.15.1.jar
- tdnf-mc115-1.8.69.jar
- TechReborn-1.15-3.3.5+build.196.jar
- terrestria-1.2.1+build.29.jar
- traverse-2.1.11+build.23.jar
