### ISSUE TITLE
Lots of useless dusts

### ISSUE THREAD

**Issue by justastranger** [TechReborn/TechReborn#2046]
**Is your feature request related to a problem? Please describe.**
Andesite, Diorite, and Granite dusts have no recipes and no uses. Diorite and Granite are ground into quartz dust now. Basalt dust has a use, but has no recipe. Flint dust has no recipe. Marble dust has a use, but once again has no recipe. Calcite can be crafted, but has no use.

**Describe the solution you'd like**
Recipes, simply put.

I'm whipping up a datapack to fill in a bunch of recipe gaps, and with the help of LibCD these recipes can be conditional based on which mods are loaded. If terrestria is loaded, I have the datapack set up to tag all their basalt blocks as "#c:basalt" (I'm surprised that the terrestria dev didn't do something similar themself...) and create a recipe that grinds them 1:1 into basalt dust. Blockus has marble, IIRC, and something similar can be set up to provide a recipe for marble dust.

[techreborn_custom_recipes.zip](https://github.com/TechReborn/TechReborn/files/4215411/techreborn_custom_recipes.zip)

None of the recipes should be overpowered and should be pretty easy to just add straight to the mod. I would've loved to have done this through a Pull Request but I don't have a development environment set up or enough data to do so.

**Comment by justastranger** [comment]
The datapack also adds a use for the carbon_fiber fluid, with 2 cells being blasted into a carbon plate, being a more efficient way of making the item than with coal dust and a compressor. It can only be crafted after ashes become available.

It also adds a canning recipe for calcite -> calcium carbonate cell, so that it is analogous to how sulfur can be canned and uncanned, as well as the ability to use calcite dust instead of calcium carbonate cells in the blast furnace to make refined iron from pyrite and iron ore.

It also adds an old method of creating compressed air using a compressor and an empty cell.

The prismarine shard recipes were for the sake of uncrafting the blocks lossily as well as having a symmetry for the prismarine shard -> prismarine crystal grinder recipe.

**Comment by justastranger** [comment]
Manganese, Olivine, and Phosphorous still lack any use or recipes. Thinking of making phosphorous compostable with the compostingrecipes mod. Saw Dust could be used to create charcoal like how Thermal Expansion used to do it, but I think that'd probably require at least one more item to be made.

**Comment by drcrazy** [comment]
ok. I'll wait for you then

**Comment by justastranger** [comment]
The Compost Recipe mod for Fabric is unfortunately non-functional at the moment. I opened an [issue](https://github.com/haykam821/Compost-Recipes/issues/1) on their repository, but we'd have to wait for a fixed 1.15 release.

**Comment by Sturmlilie** [comment]
@justastranger , I took the liberty of adding tags and grinder recipes for the blockus blocks (marble, limestone) to your pack. I hope it's not confusing that limestone grinds into marble dust, but from my little research they're chemically identical.

[techreborn_custom_recipes_v2.zip](https://github.com/TechReborn/TechReborn/files/4466537/techreborn_custom_recipes_v2.zip)

**Comment by ghost** [comment]
Can this datapack be added to the base mod?

**Comment by Sturmlilie** [comment]
I'll fix up a pull request

**Comment by jusvit** [comment]
Okay so I made the dusts a little more logical and the ones with recipes craftable. As for the useless dusts, in time hopefully recipes will be used for them. I'll keep an eye out for potential uses for them.

**Comment by Sturmlilie** [comment]
Why have a recipe for basalt dust when basalt exists in the world? (And since 1.16 on vanilla even; same for Marble but I won't complain since it requires Blockus)

**Comment by justastranger** [comment]
Yeah, basalt dust should just be coming straight from basalt now that's it's a vanilla block

**Comment by jusvit** [comment]
> Why have a recipe for basalt dust when basalt exists in the world? (And since 1.16 on vanilla even; same for Marble but I won't complain since it requires Blockus)



> Yeah, basalt dust should just be coming straight from basalt now that's it's a vanilla block

I did these changes in 1.15, when we fully move to 1.16, they'll change.

**Comment by justastranger** [comment]
Makes sense
