### ISSUE TITLE
Missing tags on items

### ISSUE THREAD

**Issue by justastranger** [TechReborn/TechReborn#2047]
**Describe the bug**
A number of plates, dusts, and nuggets are not tagged.

Plates:
-  Advanced Alloy Plate
-  Bronze Plate
-  Carbon Plate
-  Chrome Plate
-  Coal Plate
-  Invar Plate
-  Iridium Alloy Plate
-  Lapis Lazuli Plate
-  Lazurite Plate
-  Magnalium Plate
-  Nickel Plate
-  Obsidian Plate
-  Quartz Plate
-  Red Garnet Plate
-  Redstone Plate
-  Refined Iron Plate
-  Silicon Plate
-  Tungstensteel Plate
-  Wood Plate
-  Yellow Garnet Plate

Nuggets:
-  Bronze Nugget
-  Chrome Nugget
-  Diamond Nugget
-  Emerald Nugget
-  Hot Tungstensteel Nugget
-  Invar Nugget
-  Nickel Nugget
-  Refined Iron Nugget
-  Tungstensteel Nugget

Dusts:
-  Almandine Dust
-  Andesite Dust
-  Andradite Dust
-  Ashes
-  Basalt Dust
-  Bauxite Dust
-  Bronze Dust
-  Calcite Dust
-  Charcoal Dust
-  Chrome Dust
-  Cinnabar Dust
-  Clay Dust
-  Coal Dust
-  Dark Ashes
-  Diorite Dust
-  Emerald Dust
-  Ender Eye Dust
-  Ender Pearl Dust
-  Endstone Dust
-  Flint Dust
-  Galena Dust
-  Granite Dust
-  Grossular Dust
-  Invar Dust
-  Lazurite Dust
-  Magnesium Dust
-  Manganese Dust
-  Marble Dust
-  Netherrack Dust
-  Nickel Dust
-  Obsidian Dust
-  Olivine Dust
-  Phosphorous Dust
-  Pyrite Dust
-  Pyrope Dust
-  Quartz Dust
-  Red Garnet Dust
-  Saltpeter Dust
-  Saw Dust
-  Sodalite Dust
-  Spessartine
-  Sphalerite
-  Sulfur
-  Uvarovite
-  Yellow Garnet

All of the small dusts.

I might whip up a solution and attach it for you. Once again sorry that I'm not doing a pull request.

**Comment by justastranger** [comment]
I just finished creating tags for the rest of the nuggest, big dusts, and plates.
Small dusts sounds like an even bigger pain

[techreborn item tags.zip](https://github.com/TechReborn/TechReborn/files/4216464/techreborn.item.tags.zip)

**Comment by justastranger** [comment]
And here are the rest of the ingots.

[techreborn missing ingot tags.zip](https://github.com/TechReborn/TechReborn/files/4216511/techreborn.missing.ingot.tags.zip)

**Comment by drcrazy** [comment]
advanced alloy plate is TR specific. Maybe IC2 has something like this. But IC2 is not a thing for 1.15. There are some other items TR specific and not found in other mods.

Anyway, thank you for your efforts!

**Comment by justastranger** [comment]
Even if it is, so far, only used by TR, having everything tagged nicely is... well... nice.

I also finished making the item tag files for all of the small dusts.
[techreborn small dust tags.zip](https://github.com/TechReborn/TechReborn/files/4217548/techreborn.small.dust.tags.zip)

**Comment by drcrazy** [comment]
Closed by https://github.com/TechReborn/TechReborn/commit/6824caa3f523dd7bcebd5d4b58da4e83f1cd566c

Thank you a lot for your efforts!!
