### ISSUE TITLE
Can't get power from BatBox/MFE after updating

### ISSUE THREAD

**Issue by viveleroi** [TechReborn/TechReborn#2048]
**Describe the bug**

I updated the mod from `TechReborn-1.12.2-2.24.3.1043-universal.jar
 Download
` to `TechReborn-1.12.2-2.26.3.1066-universal.jar` and my MFE, which is full power, no longer outputs power. My cables are attached to the red dot side, there's no redstone signal, and this worked fine before I shut down the server to update.

The same issue happens with a BatBox I have elsewhere. It powers up, but no power can be output.

I'm using insulated copper cables.

Edit: Downgrading this and reborn core (just assuming they're closely tied) solves it.

**Steps to Reproduce**
- Use an MFE in an older build
- Use an MFE in `TechReborn-1.12.2-2.26.3.1066-universal.jar`

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.12.2
 - Mod Loader: Forge

**Comment by LegendLZD** [comment]
This bug had been fixed in the latest version of Techreborn
Download the latest version on jenkins
Latest Version:2.27.0.1072

**Comment by EnterFor** [comment]
> 此错误已在Techreborn的最新版本中修复。在curseforge上
> 下载了最新版本。
> 最新版本：2.27.0.1072

I had the same problem
Curseforge is only 1066?
No 1072 was found

**Comment by EnterFor** [comment]
Sorry, I found it

**Comment by LegendLZD** [comment]
> > 此错误已在Techreborn的最新版本中修复。在curseforge上
> > 下载了最新版本。
> > 最新版本：2.27.0.1072
> 
> I had the same problem
> Curseforge is only 1066?
> No 1072 was found

Oh!I'm sorry.Download the latest version on jenkins
Here is the link: https://jenkins.modmuss50.me/job/Team Reborn/job/TechReborn/

**Comment by EnterFor** [comment]
> > > 此错误已在Techreborn的最新版本中修复。在curseforge上
> > > 下载了最新版本。
> > > 最新版本：2.27.0.1072
> > 
> > 
> > I had the same problem
> > Curseforge is only 1066?
> > No 1072 was found
> 
> Oh!I'm sorry.Download the latest version on jenkins
> Here is the link: https://jenkins.modmuss50.me/job/Team Reborn/job/TechReborn/

I have a question, why wasn't it released to curseforge?
Is this an unstable version?

**Comment by drcrazy** [comment]
Yes. It has issues with update from previous version. Like machines are not properly loaded. Might be  issue with update from some specific version

**Comment by EnterFor** [comment]
If I change 1072
Does RebornCore need to be updated to 3.19.0.516?

**Comment by drcrazy** [comment]
Yes. Latest TR from Jenkins requires latest RC from Jenkins

**Comment by modmuss50** [comment]
Fixed, will be in the next version.
