### ISSUE TITLE
Transferring end ores generation to overworld ores does not work !

### ISSUE THREAD

**Issue by MrLador** [TechReborn/TechReborn#2060]
I wanted to transfer the ore generation from end to overworld via a file "ores.json".
Moved end ore to the overworld ore section and changed the height. When checking the performance, it turned out that this does not work at all. Everything was checked 4 times in different created worlds.

 - Minecraft: 1.12.2
 - Forge Version: 14.23.5.2847

**Comment by modmuss50** [comment]
Sadly this was a limitation of our ore config. I would recommend disable our ore gen and using a mod such as cofh core to do it
