### ISSUE TITLE
Auto Crafting Table eats transmutation stones

### ISSUE THREAD

**Issue by coderbot16** [TechReborn/TechReborn#2061]
**Describe the bug**
Auto Crafting Table eats transmutation stones instead of leaving them as input ingredients

**Steps to Reproduce**
- Put 1 transmutation stone in the auto crafting table with an appropriate recipe
- Watch the stone disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/22420959/76707209-8c261180-66aa-11ea-92dd-a1e544e8b56f.png)
![image](https://user-images.githubusercontent.com/22420959/76707215-96e0a680-66aa-11ea-8e0a-006ed5fde03d.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://paste.ee/p/UD7j8

**Additional context**
Happens with https://github.com/modmuss50/Retro-Exchange

**Comment by modmuss50** [comment]
I thought I fixed this...

**Comment by modmuss50** [comment]
apparenly I never pushed the retro exchange part of it, ffs

**Comment by coderbot16** [comment]
It doesn't appear like it's been pushed yet?

**Comment by Ayutac** [comment]
Should work with new AutoCraftingTable
