### ISSUE TITLE
Powered hovercraft for long distance transport

### ISSUE THREAD

**Issue by WrongWeekend** [TechReborn/TechReborn#2064]
**Is your feature request related to a problem? Please describe.**
The latest TR version uses Fabric which currently lacks any mods that provide useful forms of long-distance player transportation. A number of Forge mods (including IC2) have motorboats or cars, but given that TR isn't meant to be a transportation mod I figured it would be best to have just one vehicle than can act as an upgrade/replacement for both vanilla boats and horses.

**Describe the solution you'd like**
A hovercraft vehicle would essentially be a boat with amphibious capabilities, able to quickly cross both water and dry land. It would float on water even when inactive, but require energy to move. The energy would be provided by a battery or other energy storage item inserted into a GUI slot. Like horses and unlike vanilla boats, it would be capable of climbing up single blocks without a jump.

Real-life hovercrafts are generally not capable of sustained flight and would fail catastrophically if operated over pools of lava, though perhaps the latter may be bypassed with an upgrade or upgraded version of some sort to make it more useful in the Nether.

**Describe alternatives you've considered**
Another option would be separate water and land vehicles, but that would require more work and result in less useful content. The quantum armor's flight could also be enhanced, but it's not the best solution for the mid-game and not suitable for transporting mobs, cargo, or additional players like the equivalent of an amphibious boat would.

**Additional context**
The design I had in mind would be based on a small racing hovercraft as seen in this video:
https://www.youtube.com/watch?v=RmPebbNKoQ4

The actual model could use the shape proportions of the vanilla boat, minus the oars and with a rubber cushion and square shaped fan guard. I may be able to provide the model myself.

**Comment by modmuss50** [comment]
That could be really fun, sounds like a lot of work so not sure if it will be a thing. Ill leave this open though.

**Comment by drcrazy** [comment]
Not as for now. Maybe in some distant future. Another option is to have someone to create PR on this.
