### ISSUE TITLE
Crash after using storage unit block

### ISSUE THREAD

**Issue by AmphyEX** [TechReborn/TechReborn#2068]
**Describe the bug**
Crash after placing down storage unit block.

**Steps to Reproduce**
- Place storage unit block down
- Server goes into a crash loop

**Screenshots**

**Environment (please complete the following information with the version):**
Minecraft 20w12a
Fabric ver 311

**Logs**
[crash-2020-03-25_06.34.55-server.txt](https://github.com/TechReborn/TechReborn/files/4384938/crash-2020-03-25_06.34.55-server.txt)

**Comment by modmuss50** [comment]
Seems to be an issue with sorcerycraft. You dont even seem to have TechReborn installed.
