### ISSUE TITLE
Make sodium explode in water.

### ISSUE THREAD

**Issue by crabdancing** [TechReborn/TechReborn#2069]
I'm always frustrated when I dump sodium in water and it doesn't explode.

Please make it so when you dump sodium in water, it explodes.

**Comment by modmuss50** [comment]
Ok.

Dropping a bucket of sodium into water will cause an explosion. Sodium cells are safe as they are fully enclosed.

**Comment by crabdancing** [comment]
@modmuss50 what about sodium source blocks? By right clicking with sodium cell I can place a sodium source block adjacent to water blocks. Those will still not explode with the changes you made! :P

**Comment by modmuss50** [comment]
I’ll look into it, that may be more complex
