### ISSUE TITLE
invisible cell and bucket from Optifine 1 15 2

### ISSUE THREAD

**Issue by Miros77** [TechReborn/TechReborn#2071]
**invisible cell and bucket from Optifine 1 15 2**
invisible cell and bucket with fluid from Techreborn preview_OptiFine_1.15.2_HD_U_G1_pre10

**Screenshots**
![2020-03-30_16 36 51](https://user-images.githubusercontent.com/59547044/77941098-4a0fe900-72c2-11ea-8e1e-f9f6d306df77.png)

 - Minecraft: [1.15.2]
 - Mod Loader: [fabric-loader-0.7.8+build.184-1.15.2

]

**Logs**
[latest.log](https://github.com/TechReborn/TechReborn/files/4404344/latest.log)

**mods**
optifabric-1.0.0-beta7.jar
preview_OptiFine_1.15.2_HD_U_G1_pre10.jar
TechReborn-1.15-3.3.6+build.205.jar
fabric-api-0.4.32+build.292-1.15.jar

**Comment by modmuss50** [comment]
This is becuase OptiFabric has to disable fabric's rendering api to even work. At somepoint I will look into fixing this in OptiFabric.

Ive opened an issue to track this over on the OptiFabric repo: <https://github.com/modmuss50/OptiFabric/issues/157>
