### ISSUE TITLE
An API is required

### ISSUE THREAD

**Issue by hYdos** [TechReborn/TechReborn#2072]
**Is your feature request related to a problem? Please describe.**
Once your at the end of tech reborn there isn't much to do. so i decided to make a mod extending it and found out how hard it is to do it (its possible but requires reflection, etc)

**Describe the solution you'd like**
I would like an api where blocks and items can be easily added. You would be able to access things like:

- The amount of energy coming in

- Weather or not energy should be outputted

- Change the gui for an block

- get the energy amount in an item

- specify weather or not a multiblock is required

**Describe alternatives you've considered**
As i said above i considered using reflection but that proved to be a very big hassle to get working properly.

**Comment by modmuss50** [comment]
Energy stuff should all be exposed via `PowerAcceptorBlockEntity` or the energy api.

Do you want to change guis for existing blocks?

Multiblocks arent great right now, you might be best doing your own thing.

**Comment by hYdos** [comment]
apparently ramidzk is working on a multiblock system. and ill check out the PowerAcceptorBlockEntity class.

**Comment by hYdos** [comment]
oh and i dont want to edit guis for existing blocks so far. i should be fine with what i can access now. Thanks :)

**Comment by modmuss50** [comment]
I think we sorted all this out
