### ISSUE TITLE
Auto Crafter is unable to pull from Storage Units

### ISSUE THREAD

**Issue by Martmists-GH** [TechReborn/TechReborn#2073]
**Describe the bug**

When configured to auto-input from and auto-output to adjacent Storage Units, the Auto Crafter simply does nothing.

**Steps to Reproduce**
- Place an auto-crafter between two Storage Units
- Tell it to auto-input/output

**Screenshots**
![Screenshot_20200331_154907](https://user-images.githubusercontent.com/16361449/78033808-2b176280-7367-11ea-852f-9f7569f2730e.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric
- Modpack: AOF Mini

**Comment by modmuss50** [comment]
Working for me, make sure the storage unit is set to output on those sides.

**Comment by Martmists-GH** [comment]
ah, guess that's why it doesn't work. Is Auto Input not supposed to override that, like it does with chests?

**Comment by modmuss50** [comment]
chest dont limit what can go in and out of their sides. the machines are set with slot config, this also means for the other machine. 

A possible solution to this might be to set a defualt side config for machines.
