### ISSUE TITLE
Compatibility with Elytra (Trinket)

### ISSUE THREAD

**Issue by Limitrophic-Researcher** [TechReborn/TechReborn#2074]
**Is your feature request related to a problem? Please describe.**
When using Quantum Chestplate, the booster feature overrides the Elytra mechanics in the air, preventing an Elytra worn in the Cape Trinket slot from working.

**Describe the solution you'd like**
If a player has an Elytra equipped in addition to the Chestplate, then it is reasonable to assume that they would prefer the Elytra's flight mechanics to the boost jumps. On detecting that the player is wearing an Elytra, disable the booster effect to allow Elytra flight. Creative flight doesn't impact Elytra flight except by preventing repeatedly tapping jump to activate, so it wouldn't need to be changed.

**Additional context**
Applies to Fabric versions of Tech Reborn. Interaction with [Trinkets](https://github.com/emilyploszaj/trinkets/) mod or any other mod that allows for Equipped with Elytra state without equipping it as a Chestplate.

**Comment by modmuss50** [comment]
Looks like something I will need to support on a mod to mod basis.
