### ISSUE TITLE
superconductor Cable not transmitting correct energy outperformed by Insulated HV Cable

### ISSUE THREAD

**Issue by mholland999** [TechReborn/TechReborn#2076]
Connect super conductor cable to created solar panel and then to string of machines, energy does not increment correctly.

change cable to insulated HV Cable, power suddenly is restored to flow.
minecraft 1.15.2
Fabric

**Comment by mholland999** [comment]
TechReborn-1.15-3.3.5+build.196.jar
RebornCore-1.15-4.2.4+build.102.jar
fabric-language-kotlin-1.3.61+build.1.jar
fabric-api-0.5.1+build.294-1.15.jar

**Comment by drcrazy** [comment]
Superconductor cable has a very huge internal buffer. Millions of energy will be used to fill that buffer first, compare to thousands for HV.
