### ISSUE TITLE
Wiki explanation of blocks like storage, the item config screen and how to properly configure

### ISSUE THREAD

**Issue by mholland999** [TechReborn/TechReborn#2077]
Your Wiki page is short a lot of information for fans of your mod.  I have used simlar mods and I get the blue orange green configuration for input output.  However understanding which input/output the block should be set to to properly work is not always straight forward.  information like you need a hopper in between machines etc would be nice. for example how does a storage block work?  A hopper on top not directly pointing into the storage block does not allow inventory to pass.  so there is no way to allow for a hopper or conveyor line to feed items to be auto sorted into storage. manually sorting your vast inventory is PAINFULLY NOT FUN.  also interaction notes like ctrl click or double right click to put all items in this bin or left click to pull 1 item and shift left click for a whole stack would also be handy to know.  happy to help contribute in some way if possible.  love the mod, just want more details on missing info.

**Comment by ghost** [comment]
Articles on the storage units would be nice. I just started using this mod and noticed they were missing from the wiki after I found them in REI.

**Comment by jusvit** [comment]
> Articles on the storage units would be nice. I just started using this mod and noticed they were missing from the wiki after I found them in REI.

Added info for storage and tank unit, thanks for suggestion.

Storage unit: https://wiki.techreborn.ovh/doku.php?id=mods:techreborn:basic_storage_unit

Tank unit:
https://wiki.techreborn.ovh/doku.php?id=mods:techreborn:basic_storage_unit

**Comment by jusvit** [comment]
As for the other suggestions, the wiki is still growing, we're always looking for people interested in help adding to it. If you want to help, hit up modmuss50 on our discord channel.

I'll make sure to add some more - clarification on the input/output tomorrow.
