### ISSUE TITLE
Recipe dependency loop (v3.3.5, 1.15.2)

### ISSUE THREAD

**Issue by crabdancing** [TechReborn/TechReborn#2078]
The following applies to TechReborn version 3.3.5, for Minecraft 1.15.2.

Let's say, I want an industrial grinder.

This requires that I make, among other things, diamond grinding heads.

Diamond grinding heads need diamonds and steel.

Steel can only be made in a blast furnace.

Blast furnaces are made with cupronickel heating coils.

Cupronickel heating coils are made with nickel.

Nickel can be extracted... with an industrial grinder. :|

Still, this doesn't make the game impossible. All the player has to do is build a big machine for making a lot of cheap items -- maybe using cobble generators or chickens, then parade the items into a recycler and box opener and then massive storage chests, and leave it running for maybe a couple of hours realtime to make sure she gets enough nickel...

But I feel like nickel probably shouldn't be the single most valuable metal in the game? :P

**Comment by WrongWeekend** [comment]
You can get small piles of nickel dust by putting copper dust in a centrifuge.

**Comment by crabdancing** [comment]
Oh... how embarrassing! I missed that.

Thanks @WrongWeekend

**Comment by aelfwyne** [comment]
Better documentation of the skill tree would stop these issues being opened, just saying. It is nearly impossible to figure out the tech tree for this mod as the wiki is incomplete and does not explain obscure paths to getting the correct resources.

**Comment by Ayutac** [comment]
there is a patchouli add on for TR by now.

**Comment by moshner** [comment]
Patchouli link: https://www.curseforge.com/minecraft/mc-mods/tech-reborn-patchouli
