### ISSUE TITLE
Continuous Explosions (Standalone 0.5.5.941)

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#208]
Any machine/generator filled with any amount of power explodes continuously.

**Comment by modmuss50** [comment]
Was it raining? Try turning the config off. If not its a bug.

**Comment by parcel31u** [comment]
Not raining and config for machines to explode is set to false.

**Comment by modmuss50** [comment]
huh, ok. I will take a look

**Comment by parcel31u** [comment]
The machines themselves don't explode, they cause explosion around them and spew out fire.

**Comment by modmuss50** [comment]
Huh, I will need to look into it.

**Comment by gigabit101** [comment]
Wait since when did are machines explod??

**Comment by Carbon-Ghost** [comment]
Wait... Small question, will this be able to support classic easy mode e-net ? Or there will be a new config option for that ?
