### ISSUE TITLE
crashes on startup 20w14a

### ISSUE THREAD

**Issue by marios-andr** [TechReborn/TechReborn#2080]
Minecraft Version: 20w14a
Fabric Loader Version: 0.8.2 + build.194
Tech Reborn Version: 3.3.5 + build.11
Reborn Core Version: 4.2.4 + build.8
Platform: MultiMC

Minecraft crashes on startup
[latest.log](https://github.com/TechReborn/TechReborn/files/4443214/latest.log)

**Comment by modmuss50** [comment]
Humm, that log doesnt appear to have a crash in it?

**Comment by modmuss50** [comment]
There was never a 14a version, use 15a
