### ISSUE TITLE
REI favourites cover Tech Reborn upgrade slots

### ISSUE THREAD

**Issue by Tanath** [TechReborn/TechReborn#2084]
**Describe the bug**
Favourites cover Tech Reborn upgrade slots. Mousing over shows tooltips for both things.

**Steps to Reproduce**
- Install Tech Reborn & [REI](https://minecraft.curseforge.com/projects/roughly-enough-items).
- Place Tech Reborn machines. Upgrade slots on left in interface are accessible.
- Add 1 or more full rows of favourites in REI. Note they cover the upgrade slots.

**Screenshots**
![screenshot](https://imgur.com/TvWMkP6.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric

**Additional context**
[REI says](https://github.com/shedaniel/RoughlyEnoughItems/issues/312) they have an API to implement exclusion zones which should be used to avoid this.

**Comment by modmuss50** [comment]
Fixed
![](https://ss.modmuss50.me/java_2020-04-11_15-26-17.png)
