### ISSUE TITLE
In-game Wiki DoA

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2085]
**Is your feature request related to a problem? Please describe.**
The latest version of Charset Tablet is for 1.12.2. The in-game wiki just links me to the website.

**Describe the solution you'd like**
Can you provide an in-game wiki that provides the wiki in-game?

**Describe alternatives you've considered**
I can jump back and forth between my web browser and Minecraft, but that's inconvenient.

**Comment by jusvit** [comment]
There are many built in documentation for TR. In 1.15 there's advancements to guide you through the modpack in addition to the tooltips explaining each block. As it stands, 1.12 isn't being actively developed on therefore is very unlikely. 

However, if anyone wants to improve upon the in-game manual or add functionality for Charset, support is most welcomed.
