### ISSUE TITLE
Configurable Ore Spawn Rates?

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2087]
**Is your feature request related to a problem? Please describe.**
Ruby gear is more powerful than diamond gear, but rubies are fairly common. I'm loving this mod, but rubies would be game-breaking on my server if the spawn rate says the same. 

**Describe the solution you'd like**
I want to be able to configure the spawn rate of ore so I can keep rubies in the game but make them much rarer.

**Describe alternatives you've considered**
I could just switch off rubies in the config, but I want to keep them, just at a lower rarity. I haven't seen a way to change the spawn rate in the config.

**Comment by modmuss50** [comment]
I think the real fix for ruby tools is to make them less powerful. However I do also want to redo the ore configs to be fully customisable.

**Comment by ghost** [comment]
That also would be okay with me, especially with netherite on the way. Do you have any idea when that might be implemented?

**Comment by ghost** [comment]
Will there be a ruby gear nerf also? Someone in the discord said reducing ruby ores could mess up chrome in the endgame.
