### ISSUE TITLE
[Question] Removal of Tech Reborn recipes using LibCD or Vanilla Datapacks

### ISSUE THREAD

**Issue by TalEdd** [TechReborn/TechReborn#2089]
Is there a way to remove recipes for Tech Reborn using LibCD or datapacks, as I specifically need to remove the enchanted golden apple recipe from the Chemical Reactor, as that item has special uses in our server.

**Comment by drcrazy** [comment]
Yes for both

**Comment by TalEdd** [comment]
How may I go about doing that? What is the code required to remove it in a datapack, or in LibCD as I can remove all vanilla recipes using RecipeTweaker.removeRecipesFor(), but it doesn't remove Tech Reborn recipes.

**Comment by Sturmlilie** [comment]
The way I did it was by overwriting the original recipe (ie. exact same namespace/path) with a json containing an empty object `{}`. Don't know if that's the intended way but it hasn't broken anything yet.

**Comment by modmuss50** [comment]
https://wiki.techreborn.ovh/doku.php?id=development:libcd

this wiki page should help
