### ISSUE TITLE
Removal of Assembly Machine

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#209]
The assembly machine was removed in 0.5.4.932. Can you at least add it to Techreborn addons with the modtweaker compatibility?

**Comment by modmuss50** [comment]
Im sure I can do something :)

**Comment by Carbon-Ghost** [comment]
Wait it was removed ? Curses D:

**Comment by modmuss50** [comment]
I think it was removed becuase it did not exist in old greg tech. I may add a config or put it back into addons

**Comment by Carbon-Ghost** [comment]
It actually did exist, the last set of releases in 1.4.7 included it...

**Comment by modmuss50** [comment]
@gigabit101 what was the reason you removed it?
