### ISSUE TITLE
Craft storage units using barrels added by blockus

### ISSUE THREAD

**Issue by crabdancing** [TechReborn/TechReborn#2090]
It's annoying to craft crude storage units when you have blockus installed, because blockus adds a bunch of new barrel types (oak, birch, jungle, etc).

I would like it if crude storage units were craftable using _any_ type of barrel from blockus.

**Comment by Sturmlilie** [comment]
I added this to my datapack:
File `data/techreborn/recipes/crafting_table/unit/storage/crude_storage_unit_blockus.json`  
```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "WWW",
    "WBW",
    "WPW"
  ],
  "key": {
    "B": {
      "tag": "blockus:barrels"
    },
	"P": {
      "item": "minecraft:paper"
    },
	"W": {
      "tag": "minecraft:planks"
    }
  },
  "result": {
    "item": "techreborn:crude_storage_unit"
  }
}
```

**Comment by jusvit** [comment]
relates to #2091

**Comment by modmuss50** [comment]
Sloved
