### ISSUE TITLE
Question about Item Plates Textures

### ISSUE THREAD

**Issue by TheUntamed** [TechReborn/TechReborn#2092]
How did you create the textures for all the plates? They have the colors of the different materials but the shades and shadows are the same for all textures. It doesn't look like they were all created manually and I would like to know how you created them.

**Comment by Spearkiller** [comment]
In actual fact, they were all made manually, but in a similar way to some other mods that add plates/dusts like JAOPCA, among others.

I started with a base grey-scale texture for everything; plates, blocks, dusts, so on and so forth. What some modders would do to save time would be to then change the colours on each items model, but this can lead to darker colours not looking right. What I did was I took these base textures, and copied them for each material, and made a colour palette for each metal with the same amount of shades as the base palette, and then just recoloured them individually -- this also now means whenever something new needs texturing we have a defined colour set for each metal. This also allowed us to get the exact same colours for things like gold plates/dusts, coal plates, essentially anything.

Hope that makes sense and answers your question :)

**Comment by TheUntamed** [comment]
Do you still have this base plate texture?

**Comment by Spearkiller** [comment]
Of course I do, in case I need to make a new plate texture. It's nothing exciting to look at.
![template](https://user-images.githubusercontent.com/10781437/79676628-14647d00-823c-11ea-9c94-b3835ff42c94.png)

**Comment by drcrazy** [comment]
Seems like initial question is answered.
