### ISSUE TITLE
Industrial Grinder always says "Incomplete Multiblock" MC 1.15.2, Tech Reborn 3.3.8 build 216 Fabric

### ISSUE THREAD

**Issue by JillSwift** [TechReborn/TechReborn#2098]
**Describe the bug**
Industrial Grinder always says "Incomplete Multiblock"

**Steps to Reproduce**
Build grinder's multiblock, 9 standard machine casings (3x3) on the bottom, 8 advanced machine casings on the next level in a square, then 9 (3x3) standard machine casings on the top. Attach the industrial grinder block to the middle layer in the center.

Open the industrial grinder's GUI with a right click to the grinder block.

The GUI will say "Incomplete Multiblock" despite the structure being there.

**Screenshots**
![completed industrial grinder structure](https://i.imgur.com/IhRjDZW.jpg)
![GUI claiming it ain't there](https://i.imgur.com/ZRHwbbW.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric Loader 0.8.2 build 194
 - Tech Reborn: 3.3.8 build 216

**Logs**
No errors or warnings in the log.

**Additional context**
NA

**Comment by Seedbeat** [comment]
Do you placed a water at middle layer? See pic:
![изображение](https://user-images.githubusercontent.com/25617135/80321081-0e196680-8823-11ea-88e4-d536f6c6d398.png)

**Comment by JillSwift** [comment]
No, but only because I missed that part of the instructions 😢

Thank you, Seedbeat

**Comment by BloxMaster3** [comment]
now mine is saying the same thing but I DO have water in the middle
