### ISSUE TITLE
Ability to use batteries directly with right-click

### ISSUE THREAD

**Issue by DenisNovac** [TechReborn/TechReborn#2099]
**Is your feature request related to a problem? Please describe.**
There was this handy feature in IC2 when you could have small batteries with you and charge devices with right-click. And there is no low-tier batpacks (only the Lithium-Ion Batpack). So you're stuck with your portable devices at the beginning without portable energy cells. 

**Describe the solution you'd like**
I think, it's good idea to copy this ability to use batteries directly from IC2.

**Comment by KnatteAnka** [comment]
or is it easier to have it if its in the off hand it charges the item in hand?

**Comment by DenisNovac** [comment]
> or is it easier to have it if its in the off hand it charges the item in hand?

I guess it is.
