### ISSUE TITLE
Rubber from Dandelions

### ISSUE THREAD

**Issue by WrongWeekend** [TechReborn/TechReborn#2100]
**Is your feature request related to a problem? Please describe.**
Depending on world generation settings, players may not be able to access naturally spawning rubber trees, and by extension rubber. Either the player spawns in a large biomes region where rubber trees do not spawn (like mountains, plains, jungle, savanna, desert, or a survival island) or has a buffet or superflat world consisting of a single biome without rubber trees. This prevents the player from accessing the vast majority of content in the mod. If I read WorldGenerator.java correctly, rubber trees are coded to spawn only in regular forests, swamps, taiga, and their variants.

**Describe the solution you'd like**
The ability to craft dandelions into sap, or use a treetap on a dandelion or extract the sap (destroying the dandelion in the process). Since the extractor currently uses dandelions to make yellow dye, a more efficient dandelion to sap recipe could be assigned to the grinder as shown around 2:00 in the video below.

Dandelions can appear in any biome (naturally or with bone meal on grass blocks) except swamps, which generate rubber trees anyway.

**Describe alternatives you've considered**
Vines could also work as a source of sap, as the rubber vine was formerly an important source of natural latex. However, any player that has access to vines is also likely to have access to rubber trees (except in the jungle).

Wandering traders could also be modified to sell rubber saplings. The saplings could also become part of the mod's basic level loot table.

**Additional context**
Dandelion sap contains latex with the same properties as the latex from rubber trees. Experiments with producing dandelion rubber were done in Germany and the USSR during WWII, but were abandoned with the end of the war and advances in synthetic rubber. More recently, a German company was able to make high performance automobile tires from dandelion rubber:

https://www.youtube.com/watch?v=bvVJL2GYRHY

**Comment by drcrazy** [comment]
I've added sapling back to chests in villages, desert pyramids, dungeons, etc. 
If you really need rubber from dandelions then add recipe via data pack, CraftTweaker, LibCD. 

It is hard to balance this recipe for every type of map (regular, superflat, skyblock, etc.) thus balance changes are expected from pack makers.

**Comment by drcrazy** [comment]
PS. I was really eager to do that recipe on a first thought.
