### ISSUE TITLE
Naming of Machine casing is wrong on the wiki (1.12.2-2.27.1.1076)

### ISSUE THREAD

**Issue by soultoyo** [TechReborn/TechReborn#2102]
The naming of the machine casing on the wiki is incorrect for the current version of tech reborn,

The advanced casing is now the last tier of machine casing and what was the advanced casing is now the reinforced machine casing.

I don't know whether the naming for the machine casing needs to be updated on the wiki or whether the naming of the machine casing in game needs to change to reflect the manual.

If you need more information let me know and I'll be happy to help out :).

**Comment by drcrazy** [comment]
Wiki is in a process of very-very slow update to 1.15 version. Thus naming is fine for 1.15.
