### ISSUE TITLE
Gems use c:name_gem tag instead of c:name

### ISSUE THREAD

**Issue by lukebemish** [TechReborn/TechReborn#2106]
**Is your feature request related to a problem? Please describe.**
As the title says. This breaks compatibility with mods that use the c:name format, such as Cotton Resources.

**Describe the solution you'd like**
A simple solution, that keeps compatibility all around, would be to nest the c:name_gem tags inside of the c:name tag. so, for instance, c:red_garnet would contain c:red_garnet_gem, which already contains techreborn:red_garnet_gem.

**Comment by drcrazy** [comment]
Probably it is better to report this to Cotton Resources due to gems not following the common logic of material_form format.
For example:
copper_dust, copper_plate, copper_gear
ruby_dust, ruby_plate and ruby_gem, not just ruby.

**Comment by lukebemish** [comment]
Okay. I just brought this up in CottonMC/CottonResources#57. Thanks!

**Comment by drcrazy** [comment]
TR will continue to use the following naming convention: <material>_<form> at least for 1.16.x

Mod Pack authors can adjust tags using data pack.
