### ISSUE TITLE
Server crashes on start after placing a solar panel

### ISSUE THREAD

**Issue by thejimmyw** [TechReborn/TechReborn#2109]
**Describe the bug**
Placing a solar panel in the world and restarting the server causes a complete lock up upon loading the world either triggering the watchdog or completely freezing require a force kill if the watchdog timer is disabled. The client sees an empty world which triggers the crash, with no clients the server doesn't appear to crash.

**Steps to Reproduce**
- Place any ~~basic~~ solar panel in the world
- Restart server and attempt to rejoin

**Screenshots**
https://imgur.com/a/T1M907u

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric 0.8.2+build.194

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/0f6wU9BE

**Additional context**
While testing the bug to fully narrow down the reproducing steps, it seems I found another issue that is related. I created an empty creative world on the same server, placed a single ~~basic~~ solar panel down in the vicinity of the spawn and restarted the server (typing stop in console, waiting for it to stop then starting again). This caused the server to freeze on "Preparing spawn area", unlike the previous crashes which only occured after the player loaded in. See: https://pastebin.com/sbctZfiA

**Comment by alexcraig** [comment]
I'm experiencing the same crash: https://pastebin.com/i4XfpGSy

**Comment by modmuss50** [comment]
Appears to be an incompatblity with the chainmail mod

**Comment by ghost** [comment]
Sorry, Issue was on my part, updating Torcherino to [2.11.66](https://www.curseforge.com/minecraft/mc-mods/torcherino/files/2970953) will fix this issue.

**Comment by ghost** [comment]
I'm seeing this as well and I've not got the chainmail mod in the mix. 

I'll see if I can reliably reproduce this on a new creative server with just Tech Reborn plus deps and report back.

**Comment by ghost** [comment]
Sorry for the noise, I mistyped a grep; removing chainmail (via expandedstorage) does indeed stop the crash.
