### ISSUE TITLE
Cells and buckets have invisible textures when OptiFine installed

### ISSUE THREAD

**Issue by prc94** [TechReborn/TechReborn#2112]
TR fluid cells' and buckets' textures turning invisible when OptiFine is on.

**Screenshots**
https://imgur.com/a/mqV8hZ8

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric
 - TechReborn: 3.3.11+build.224
 - OptiFine: 1.15.2_HD_U_G1_pre17

**Logs**
https://pastebin.com/VEEGYhPx

**Comment by modmuss50** [comment]
Optifabric issue: https://github.com/modmuss50/OptiFabric/issues/157
