### ISSUE TITLE
Remake of IC2 Hazmat Suit, Scuba Helmet and Rubber Boots

### ISSUE THREAD

**Issue by prc94** [TechReborn/TechReborn#2113]
### \*\*Describe the solution you'd like\*\*
Functional remake of IC2's Hazmat Suit (Scuba Helmet, Hazmat Chestplate + leggings and rubber boots) with its advantages like underwater breathing via scuba helmet and some kind of compressed air, Rubber Boots fall damage reduction and fire protection with full set of armor.
#### For reference:
[Scuba Helmet](https://wiki.industrial-craft.net/index.php?title=Scuba_Helmet)
[Hazmat Suit](https://wiki.industrial-craft.net/index.php?title=Hazmat_Suit) (Chestplate)
[Hazmat Suit Leggings](https://wiki.industrial-craft.net/index.php?title=Hazmat_Suit_Leggings)
[Rubber Boots](https://wiki.industrial-craft.net/index.php?title=Rubber_Boots)

**Comment by drcrazy** [comment]
Not as for now. Maybe in some distant future. Another option is to have someone to create PR on this.
