### ISSUE TITLE
Tweak combat stats of chainsaw and, maybe, drilll, to fit better with vanilla combat system.

### ISSUE THREAD

**Issue by prc94** [TechReborn/TechReborn#2116]
### \*\*Describe the solution you'd like\*\*
Make chainsaw dealing more damage with slower attack speed, for it to be more realistic and fit well with vanilla minecraft axes. I suppose it should have attack damage of, like, 10 and so the attack speed near 0.8 for basic variant and so on for advanced ones. And about drill... well, i suppose it should have attack damage similar to pickaxe, but faster attack speed (like you can actually drill enemy). If you don't have enough time to bother on that i can arrange a pull request with that tweaks.

**Comment by drcrazy** [comment]
Already done by https://github.com/TechReborn/TechReborn/commit/38aaeabf3cc349ec7f05eba4b97ac93350eee6e5
