### ISSUE TITLE
Publish translated version for 1.14

### ISSUE THREAD

**Issue by PhoneixS** [TechReborn/TechReborn#2120]
Hello,

I have translated the mod in https://translate.techreborn.ovh to spanish and I would like to ask if you could publish a new version with the translation but for Minecraft 1.14 wich is what I'm currently using.

**Comment by modmuss50** [comment]
Yes, that should be fine, ive seen your PR.

**Comment by modmuss50** [comment]
1.14 is no longer supported.

**Comment by modmuss50** [comment]
You should be able to apply your translations with a resource pack.
