### ISSUE TITLE
[1.12.2] Centrifuge crafttweaker recipes are not working

### ISSUE THREAD

**Issue by skyline918** [TechReborn/TechReborn#2123]
**Describe the bug**
Centrifuge crafttweaker recipes are not working at all on 1.12.2 latest. No error from crafttwekaer

**Steps to reproduce the behavior**
- Create [script](https://pastebin.com/LB8jg1nD) which replaces bronze decomposition recipe, removes blaze powder electrolyzer recipe, and adds test andradite recipe
- Check electrolyzer recipes was both added and removed, but centrifuge recipe was not

**Environment**
 - Minecraft: 1.12.2
 - Forge
 - Baubles-1.12-1.5.2.jar
 - CraftTweaker2-1.12-4.1.20.574.jar
 - jei_1.12.2-4.15.0.268.jar
 - modtweaker-4.0.18.jar
 - MTLib-3.0.6.jar
 - RebornCore-1.12.2-3.19.3.524-universal
 - TechReborn-1.12.2-2.27.2.1079-universal
 - Thaumcraft-1.12.2-6.1.BETA26.jar
 
**Logs**
[crafttweaker.log](https://pastebin.com/y1ww7hj0)
[latest.log](https://pastebin.com/QDrsXvPT)

**Additional context**
My main scripts (not that script) worked an older versions of Tech Reborn 1.12.2, I did not changed them, but update to TechReborn-1.12.2-2.27.2.1076 breaks centrifuge ones. This is very bad for my server, becuase of  bronze powder duplication (it is possible to fix that recipe on mod side?)

**Comment by drcrazy** [comment]
Please, update TR and RC to latest version
