### ISSUE TITLE
Solar panel energy generation should scale with light incidence angle

### ISSUE THREAD

**Issue by Sturmlilie** [TechReborn/TechReborn#2127]
**Is your feature request related to a problem? Please describe.**
I think everyone who has played TR will agree that solar panels are extremely OP and just blow every other generator out of the water; this is a bit sad because setting up and managing an energy generation process (eg. from natural / grown resources) can be quite fun. Solar panels OTOH just sit there.

**Describe the solution you'd like**
The simplest iteration of this feature I could think of is: Make energy production during the day proportional to the sine of the light incidence angle, with the angle being 90° during noon and 0° during sunrise/set. For consistency, I'm suggesting the minimum of this to be capped to the night generation rates, so the E/t don't go down to zero during sunset and jump back up again when night falls (I'm interpreting night generation as "ambient light generation" here).  
Without tweaking the existing day/night generation rates, this is already a nerf in two ways:
* Energy generation is no longer consistent and must be buffered where necessary
* The total amount of energy produced during one day is 2 over pi, or roughly 60% times that of the current flat generation

In my opinion, solar panels are still OP even with this change, simply due to their high raw output, but this can be tweaked via the config; maybe a consensus on more sensible default values can be reached.

Edit: On fabricord it has been suggested to make this feature optional via config.

**Describe alternatives you've considered**
Just tweaking the default day generation rates works, but I think this feature can make panels actually more interesting.

**Additional context**
I've made a prototype of my suggestion which you can try out:  
[**[jar link]**](https://srv-file14.gofile.io/download/vwDbCI/TechReborn-1.15-3.3.11+build.local.jar)  
[**[source code]**](https://github.com/Sturmlilie/TechReborn/tree/solar_angle)  
[**[video demonstration]**](https://youtu.be/kcd8kq8pFkU) (daylight cycle sped up by 60x)

**Comment by jusvit** [comment]
I mean it isn't a bad idea, I like the uniqueness, wouldn't just throw it out. Don't see any reasons it couldn't be something you could enable in config, and allow modpack creators to balance.

**Comment by Sturmlilie** [comment]
I'm not throwing it out, just not sure I wanna spend more time on TR right now. The idea and my mockup code are still there, I won't delete the branch. If there is some actual input / consent on the game design aspect of it I'll probably finnish it though.

**Comment by Technici4n** [comment]
Implemented in #2497.

**Comment by Sturmlilie** [comment]
Rip sinusoidal output :(
