### ISSUE TITLE
1.15.2 Fabric | Advanced Solar Panel Tile Entity Bricks the World

### ISSUE THREAD

**Issue by Mustang-Dood** [TechReborn/TechReborn#2128]
I placed an Advanced Solar Panel.  Everything works fine.

Exit the world.

When you try to load the world again, the chunk does not load.  Your player loads in, but everything that should be in the chunk is just air.  Nothing is ticking, and you cannot move. You cannot save and exit either, it just hangs.  

If you remove the level.dat so the players position is moved away from the chunk you were in, you can load the world.  However, as soon as you are close enough for the chunk to load, everything stops ticking, the chunk is empty, and you cannot exit and save.  Basically the exact same state as when you load into the chunk.

The only way to fix this, is to use MCASelector, edit the chunk, and delete the tile entity for the advanced solar panel.  That will let you load the world, and you have to remove the advanced solar panel block or it will brick your world again.

fabric-api-0.11.1+build.312-1.15
RebornCore-1.15-4.2.9+build.115
TechReborn-1.15-3.3.11+build.224

**Comment by Spirit-Sound** [comment]
I have the same error:
[crash-2020-06-08_20.39.17-server.txt](https://github.com/TechReborn/TechReborn/files/4747597/crash-2020-06-08_20.39.17-server.txt)

**Comment by DanShu15** [comment]
Seems like the same issue I had https://github.com/TechReborn/TechReborn/issues/2126 We just took out Expanded Storage as a work around for now

**Comment by jusvit** [comment]
As  @DanShu15  mentioned, this is a problem with NinjaPhenix's noncorrelatedextras mod. The developer appears to have fixed it in a commit 10 days ago on [COMMIT](https://github.com/NinjaPhenix/FabricMods/commit/4c8a35f9e9aef2bd5cbade3cbbc8724c10d9b092). Try updating the noncorrelatedextras mod to [LATEST VERSION](https://github.com/NinjaPhenix/FabricMods/releases/tag/noncorrelatedextras-0.3.0%2B1.15.2)
