### ISSUE TITLE
1.15.2 No item recipe

### ISSUE THREAD

**Issue by pavlouha** [TechReborn/TechReborn#2129]
Hello! I can't craft Energy Crystal: no recipe in Recipe book; following a wiki scheme does nothing. May be it must be produced in some machine?

**Comment by DanShu15** [comment]
Looks like you want the Assembling Machine
a silicon plate and 2 synthetic redstone crystals
Are you using REI to view recipes?

**Comment by pavlouha** [comment]
No, I don't. Seems like I should install this. Thank you.

**Comment by DanShu15** [comment]
It's pretty snazzy. Mouse over an item and press R to see it's recipes, U to see it's uses, search for items at the bottom or @(modname) to filter for mods. Pretty much a must-have for me
