### ISSUE TITLE
Greenhouse Controller Compatibility Issue with Stockpile Item Barrel

### ISSUE THREAD

**Issue by sdaugherty** [TechReborn/TechReborn#2132]
**Describe the bug**
Tech Reborn causes crash when trying to put item into a Stockpile Item Barrel which will not accept it.

**Steps to Reproduce**
- Set up a Greenhouse controller
- Plant potatoes
- Route all output to a stockpile item barrel containing potatoes (therefore, only accepting potatoes)
- Wait. Eventually Greenhouse Controller harvests a poisonous potato, and crash occurs when trying to transfer it to container which won't accept it.

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric (fabricloader@0.8.4+build.198)
- Fabric API: fabric-api-0.11.1+build.312-1.15
- TechReborn: TechReborn-1.15-3.3.11+build.224
- Reborn Core:  RebornCore-1.15-4.2.9+build.115
- Stockpile: stockpile-1.1.3+1.15.1

**Logs**
https://gist.github.com/sdaugherty/1f04bbc5866612592bcc431bf5ada66f

**Additional context**

**Comment by sdaugherty** [comment]
worked around by deleting the inventory of the stockpile barrel from nbtexplorer and then removing the stockpile barrel on next login

**Comment by jusvit** [comment]
Appears to be an issue with the stockpile mod and the developer is no longer maintaining the mod. I would suggest using a storage unit as an alternative which has the same functionality.

See https://github.com/branchpanic/stockpile/issues/96

**Comment by sdaugherty** [comment]
Thanks. Did not realize that Stockpile had been abandoned.
