### ISSUE TITLE
Server crash opening iron furnace GUI

### ISSUE THREAD

**Issue by tambry** [TechReborn/TechReborn#2138]
**Describe the bug**
Opening the iron furnace GUI causes a server crash. Doesn't happen in singleplayer.

**Steps to Reproduce**
1. Run a dedicated server.
2. Place iron furnace.
3. Try to open GUI.

**Environment:**
 - Minecraft: 1.16-rc1
 - Mod Loader: fabric

**Logs**
[latest.log](https://github.com/TechReborn/TechReborn/files/4809919/latest.log)

**Other mods**
* https://www.curseforge.com/minecraft/mc-mods/fabric-api/files
* https://www.curseforge.com/minecraft/mc-mods/compactstorage/files
* https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric
* https://www.curseforge.com/minecraft/mc-mods/reborncore/files
* https://www.curseforge.com/minecraft/mc-mods/techreborn/files
* https://www.curseforge.com/minecraft/mc-mods/adorn/files
* https://www.curseforge.com/minecraft/mc-mods/extra-alchemy/files
* https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files
* https://www.curseforge.com/minecraft/mc-mods/rswires/files
* https://www.curseforge.com/minecraft/mc-mods/traverse/files
* https://www.curseforge.com/minecraft/mc-mods/ok-zoomer/files
* https://www.curseforge.com/minecraft/mc-mods/mo-glass/files
* https://www.curseforge.com/minecraft/mc-mods/improved-stations/files
* https://www.curseforge.com/minecraft/mc-mods/veggieway-fabric/files

**Comment by jusvit** [comment]
#2141
