### ISSUE TITLE
TR Nuke NoSuchMethodError

### ISSUE THREAD

**Issue by ArchieBeepBoop** [TechReborn/TechReborn#2143]
**Describe the bug**
The Tech Reborn nuke crashes the server as it finds a nosuchmethoderror in RebornExplosion.<init>

**Steps to Reproduce**
- Join a dedicated server with tech reborn
- Place a nuke
- Light up the nuke with redstone

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric 0.8.8+build.202

**Logs**
https://pastebin.com/udn5GRHu

**Comment by modmuss50** [comment]
Fixed, https://github.com/TechReborn/RebornCore/commit/6217b92da74ce9ebd7d635237bbec54c09269d6b
