### ISSUE TITLE
Fabric Resource Pack Marked as for Outdated Version [1.16]

### ISSUE THREAD

**Issue by Avakining** [TechReborn/TechReborn#2146]
**Describe the bug**
The built-in resource pack for Tech Reborn is marked by Minecraft as out of date.

**Steps to Reproduce**
- Run a 1.16 instance with reborn core and tech reborn installed
- Open resource pack selector
- see that the resource pack is out of date

**Screenshots**
<img width="388" alt="Screen Shot 2020-06-27 at 23 17 46 873" src="https://user-images.githubusercontent.com/25210618/85936853-75f43800-b8cc-11ea-8e45-d33c5bb9f40e.png">
<img width="388" alt="Screen Shot 2020-06-27 at 23 17 52 840" src="https://user-images.githubusercontent.com/25210618/85936854-77bdfb80-b8cc-11ea-92bc-b6e258d96ca5.png">

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric 0.6.1.45

**Additional context**
This is because the pack.mcmeta file has a line that reads `"pack_format":4,`. It should be updated to `"pack_format":5,` for 1.15+.

**Comment by modmuss50** [comment]
These should not be showing in the list, I think this is a fabric api issue that I need to look into.

**Comment by jusvit** [comment]
Known fabric issue, unrelated to Tech Reborn.
