### ISSUE TITLE
[Suggestion]Better Multiblock Error System

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#215]
I suggest to use the Forestry Apiary Error System, I think it's better and more intuitive.
Now:
![2015-11-01_12 49 20 2](https://cloud.githubusercontent.com/assets/8685029/10868824/339a845a-809b-11e5-8c54-8e42b8008b55.png)

How Forestry(4.x) is:
![2015-11-01_12 52 52 2](https://cloud.githubusercontent.com/assets/8685029/10868822/30eb1c56-809b-11e5-953d-3f649900196d.png)
TechReborn-0.5.5.943-universal
I Hope these bug reportings that I'm doing helps!
Sorry for possible english mistakes!

**Comment by modmuss50** [comment]
You can get an in world rendering of it.

**Comment by Xen1290** [comment]
Perfect, thanks! @modmuss50
