### ISSUE TITLE
Placing a solar panel causes server to hang while preparing spawn area on next launch

### ISSUE THREAD

**Issue by fstrace4** [TechReborn/TechReborn#2150]
Place any solar panel near the spawn point on a server hosted world.
Shut down the server.
Launch the server.
It will hang somewhere in the "Preparing spawn area" phase.

If you place the solar panel a long way away from the spawn point, everything seems to work just fine.

**Comment by sdaugherty** [comment]
Not sure what version of Minecraft you are running, and there's no logs, 
However, I also had a similar issue recently - if you are also using expanded storage, update it.

**Comment by fstrace4** [comment]
Yes, I was using expanded storage in 1.15.2. Updating expanded storage fixed the issue. Thanks!
