### ISSUE TITLE
Wrench Doesn't Perform a Block Update

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2152]
**Describe the bug**
Using the wrench on a block such as the player detector does not block update the surrounding area.

**Steps to Reproduce**
- Use a wrench on a player detector with a redstone lamp directly next to it.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
None

**Additional context**
None

**Comment by modmuss50** [comment]
seems to work fine for me?

**Comment by drcrazy** [comment]
Can't reproduce.

Before: 
![image](https://user-images.githubusercontent.com/1382352/92478535-f5668780-f1ea-11ea-84b7-3b8365db207a.png)

After:
![image](https://user-images.githubusercontent.com/1382352/92478588-07e0c100-f1eb-11ea-9b07-b8d41cb8d309.png)
