### ISSUE TITLE
Basic Storage Unit 

### ISSUE THREAD

**Issue by Smakthatwaffle** [TechReborn/TechReborn#2155]
In minecraft 1.16 with Fabric, the Basic Storage Unit has a few bugs. When I first crafted it, it seemed like it was working as it was intended. But after I logged off and got back on the next day it was very buggy. When you right click it, it doesnt open. When you have any item in your hand it will open. When I try to put in iron in it. A stack stays in the out and a stack stays in the in. Then I cant add anymore. As you can see in the screenshot. Please let me know if you need me to give a better description of the bugs. Thanks. 
![2020-07-05_03 50 20](https://user-images.githubusercontent.com/67860654/86531030-c4787800-be72-11ea-8fd1-31fffbda4107.png)

**Comment by jusvit** [comment]
Hi, I attempted to reproduce the two issues you mentioned but to no avail. I tried on both dedicated and singleplayer (Unloading and loading world). Could you clarify reproducible steps in a new world or provide a video, that'd be quite helpful. Thanks.

**Comment by jusvit** [comment]
Wait I think I've reproduced, will investigate.
