### ISSUE TITLE
Step-up transformers

### ISSUE THREAD

**Issue by bentterp** [TechReborn/TechReborn#2158]
**Is your feature request related to a problem? Please describe.**
To make energy transport more efficient, a higher voltage requires fewer packets on the wire.

**Describe the solution you'd like**
It would be good if transformers could be configured so they could both step-up an step-down

**Describe alternatives you've considered**
Alternatively, separate step-down transformers could be added as recipes.

**Comment by drcrazy** [comment]
Energy tiers are not used a lot in 1.16 as for now. We will revisit this idea in future version. Thank you a lot for suggestion.
