### ISSUE TITLE
Turn Off Equipped Gear In Corner 

### ISSUE THREAD

**Issue by Xwicked-knightX** [TechReborn/TechReborn#2160]
PLEASE Tell me theres a way to get rid of or move the Equipped items hud from the top corner!? its directly in front of the fps display making it so i have no clue what my fps is......

**Comment by benjamin-bussey** [comment]
Within your minecraft folder:

config/reborncore/client.json

Change "value": true line to "value": false within the "Show stack info" tree.

**Comment by Xwicked-knightX** [comment]
Thank you!
