### ISSUE TITLE
Cannot Craft Wrench

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TechReborn/TechReborn#2163]
**Describe the bug**
With all the correct materials, I am unable to craft a wrench

**Steps to Reproduce**
Add ingredients as shown

**Screenshots**
![2020-07-13_09 14 34](https://user-images.githubusercontent.com/17887664/87321466-8110b000-c4e9-11ea-8e0f-66024178e34e.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: fabric 0.8.9+build.203
- TechReborn-1.16-3.4.2+build.48

**Logs**

[latest.log](https://github.com/TechReborn/TechReborn/files/4913388/latest.log)

**Comment by jusvit** [comment]
What modpack are you using? There might be some conflicts. It works fine with just Tech Reborn 
![image](https://user-images.githubusercontent.com/4002351/87322370-ae547100-c570-11ea-94c6-27ea083f1819.png)

**Comment by ClaudiusMinimus** [comment]
Fast response!
I too realized it was a conflict. It is a pack I'm working on - not published yet. I'm not sure which mod, but here are two screenshots and the list of mods.

![2020-07-13_09 21 12](https://user-images.githubusercontent.com/17887664/87322123-45c2b100-c4ea-11ea-83c1-7dc1b56406e5.png)
![2020-07-13_09 21 08](https://user-images.githubusercontent.com/17887664/87322121-452a1a80-c4ea-11ea-8a89-35c206bf6be4.png)

  [✔️] [1.16.1]+SuperAxes-1.1.3
  [✔️] Adorn-1.9.1+1.16.1
  [✔️] adventurez-1.0.5
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] AppleSkin-mc1.16.1-forge-1.0.14
  [✔️] authme-1.16.1-1.2.1
  [✔️] automated-crafting-1.1.2+1.16.1
  [✔️] bambootweaks-2.0.0+1.16.1
  [✔️] better-signs-and-frames-mc-1.16.1-0.6.1
  [✔️] better-wither-skeletons-1.1.0
  [✔️] betterstones-0.0.3-1.16-1.16.1
  [✔️] borderless-mining-1.0.5+1.16
  [✔️] boss-loot-tables-1.0.0-1.16
  [✔️] bunch-o-trinkets-1.0.1
  [✔️] byg-1.0.6
  [✔️] campanion-1.1.10+build.24
  [✔️] CHAS-1.16-1.3-Fabric
  [✔️] chunk-activator-2.1.0+mc1.16.1
  [✔️] ChunkBorders-0.4.3-fabric-mc1.16
  [✔️] cleancut-mc1.16-2.1-fabric
  [✔️] cloth-api-1.0.6
  [✔️] Coal+Nugget-1.2.0.4
  [✔️] columns-1.1.0
  [✔️] config-2-4.5.6
  [✔️] cotton-1.0.5
  [✔️] cotton-resources+unspecified-1.7.1
  [❌] Couplings-1.3.1.jar (disabled)
  [✔️] craftingpad-1.16-fabric0.13.1-1.0.5
  [✔️] CraftingSpawn(1.16)-0.4.0
  [✔️] crusade-1.1.2+1.16.1
  [✔️] diggusmaximus-1.2.11-1.16
  [✔️] DuplicatEgg-1.0.1
  [✔️] durabilityViewer-1.16.1-forge32.0.38-1.7.1
  [✔️] EmeraldTools-Fabric-1.16.1-1.0.29
  [✔️] essentials-base-0.2.1+1.16.1
  [✔️] expandedstorage-5.3.15+1.16
  [✔️] ExtraDoors-1.8.1-1.16
  [✔️] fabric-api-0.14.1+build.372-1.16
  [✔️] fabric-crops-1.0.0
  [✔️] fabric-diagonal-panes-0.3.0
  [✔️] fabric-furnaces-1.3.0-1.16.1
  [✔️] fabric-language-kotlin-1.3.72+build.1
  [✔️] fabriccontrolling-1.1.0
  [✔️] fabricmod_VoxelMap-1.10.5_for_1.16.1
  [✔️] fatxporbs-0.0.7+1.16-rc1
  [✔️] flesh2leather-1.0.0
  [✔️] GamemodeOverhaul-1.0.2.0
  [✔️] gamestart-2.0.0-1.16.1
  [✔️] glassdoor-1.4.4-1.16
  [✔️] gottaclimbfast-mc1.16.1-1.0-forge
  [✔️] gravestones-1.4.0
  [✔️] GreaterEye-Fabric_1.16.1-1.0.21
  [✔️] grid-20w17a-fabric0.6.2-1.5
  [✔️] grind-enchantments-1.1.1+1.16.1
  [✔️] Harvest-fabric-1.16.1-1.2.12-26
  [✔️] HealthOverlay-1.16.1-3.5.10
  [✔️] Hwyla-fabric-1.16.1-1.9.22-75
  [✔️] i-am-very-smart-2.1.0+mc1.16.1
  [✔️] identity-1.2.1-beta-1.16
  [✔️] improved-stations-2.0.2-unstable (1)
  [✔️] infinitevillagertrading-1.16-fabric0.13.1-1.0.2
  [✔️] inventoryprofiles-fabric-1.16.1-0.3.3
  [✔️] InventorySorter-1.6.7-1.16
  [✔️] invisiblights-fabric-6.0
  [✔️] iron-jetpacks-0.2.3
  [❌] ironbarrels-2.3.0.jar (disabled)
  [✔️] jumpoverfences-1.16-0.0.3
  [✔️] keepinventory-command-0.2.5
  [✔️] kibe-1.16.1-1.1.5-BETA
  [✔️] lambdacontrols-fabric-1.3.2+1.16.1
  [✔️] landmark-0.1.6
  [✔️] layingbox-1.1.3
  [✔️] layingboxvanilla-1.0.1
  [✔️] leaf-decay-1.2.0-1.16.1
  [✔️] light-overlay-5.4.0
  [✔️] linkedstorage-1.3.5-1.16
  [❌] lithium-fabric-mc1.16.1-0.5.1.jar (disabled)
  [✔️] malilib-fabric-1.16.1-0.10.0-dev.21+arne.1
  [✔️] Mambience-2.1.0-1.16
  [📁] mamiyaotaru (folder)
  [✔️] Mechanized-1.9.0
  [❌] Missing+Bits-v1.16.1+Fabric+b1.jar (disabled)
  [✔️] Mo-Glass-1.2-MC20w28a
  [✔️] modmenu-1.12.2+build.17
  [✔️] MoreGems-Fabric_1.16.1-1.0.45
  [✔️] mostructures-1.0.0-pre2+mc.1.16
  [✔️] mousewheelie-1.5.0+mc1.16.1
  [✔️] muffle-0.1.0
  [✔️] Mycommands-1.16.1-17
  [✔️] no-trample-0.0.1-1.16
  [✔️] notenoughcrashes-1.2.4+1.16.1
  [✔️] okzoomer-3.0.1-20w12a
  [✔️] Origins-1.16-0.2.1
  [✔️] OverpoweredPickles-Fabric-1.16.1-1.0.19
  [✔️] Patchouli-1.16-38
  [✔️] player-roles-1.0.1
  [✔️] PresenceFootsteps-r26+1.16-rc1
  [✔️] quickshulker-1.1.5-1.16
  [❌] Random+Teleport-2.0.0+FABRIC-MC-1.16-RC1.jar (disabled)
  [✔️] randomconfigs-1.16.1-1.4.2.0-fabric
  [✔️] randompatches-1.16.1-1.21.2.1
  [✔️] RebornCore-1.16-4.3.1+build.35
  [✔️] reloadAudioDriver-1.0.0
  [✔️] repurposed_structures-1.0.1
  [✔️] rer-2.0.2
  [✔️] ResourcefulTools-Fabric_1.16.1-1.0.32
  [✔️] RingOfAttraction-Fabric_1.16.1-1.0.21
  [✔️] RingOfEnderchest-Fabric-1.16.1-1.0.21
  [✔️] RingOfGrowth-Fabric_1.16.1-1.0.19
  [✔️] RingOfMiner-Fabric_1.16.1-1.0.16
  [✔️] RoughlyEnoughItems-4.8.1
  [✔️] rswires-4.8.0
  [✔️] sand_dust-1.1.0
  [✔️] Silky-Spawners-2.0.0+build.1-1.16
  [✔️] SimpleBackpack_Fabric_1.16.1-1.0.24
  [✔️] simpledrawers-1.8.0-1.16.1
  [✔️] simplepipes-all-0.4.0
  [✔️] simpleteleporters-2.2.0
  [✔️] sleepvote-1.8+1.16.1
  [✔️] smoothbedrock-1.2.2
  [✔️] spinnery-3.0.50+fabric-1.16.x
  [✔️] staffofbuilding-1.2.0-1.16
  [✔️] stonecutter-tweaks-1.1.0-1.16
  [❌] stuffz-2.2.1.jar (disabled)
  [✔️] tdnf-mc116-1.10.90
  [✔️] TechReborn-1.16-3.4.2+build.48
  [✔️] textile_backup-1.2.4-1.16.1
  [✔️] TheVeggieWay_Fabric_1.16.1-1.0.28
  [✔️] torcherino-2.11.67+1.16-rc1
  [✔️] trapexpansion-1.3.2
  [✔️] trinkets-2.6.2
  [✔️] Trophy+Slots-7.0.1
  [✔️] ttkb-1.0.1
  [✔️] uncraftables-1.3.4-1.16.1
  [✔️] vanilla-hammers-1.9.1-1.16.1
  [✔️] vanillautomated-1.0.4
  [✔️] wands+1.16.1-1.1
  [✔️] WardBlocks-Fabric_1.16.1-1.0.14
  [✔️] WhereIsIt-1.16.1-1.7.2
  [✔️] WildWorld-1.2.3-1.16
  [✔️] winged-1.16-1.2
  [❌] worldedit_cui-1.16.1_b244.jar (disabled)
  [✔️] ynet-0.2.0+1.16.1

**Comment by ClaudiusMinimus** [comment]
I think the conflict is Cotton Resources

**Comment by Prospector** [comment]
It wasn't using the tags properly, should be fixed in the next release, whenever that goes out. (You can try the latest builds here, but be warned, I'm not sure what other changes have been made since the previous release: https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.16/)

**Comment by vpArth** [comment]
Thank you for fix. Unfortunately, build.84 conflicts with REI somehow, so, I craft a wrench, and switched back to build.72 =)
