### ISSUE TITLE
Cells and Buckets have invisible texture when Sodium installed

### ISSUE THREAD

**Issue by Logic530** [TechReborn/TechReborn#2166]
When [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium) installed, Cells and Buckets (either empty or full) become invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/22793670/87847754-068ec880-c90d-11ea-978e-1db34c393aa1.png)
Cells are after Debug Tool, which are all invisible.

**Environment**
 - Minecraft: 1.16.1
 - Mod Loader: fabric

**Logs**
I'm not sure what log to upload, since it is not a crash.

**Additional context**
Sodium is a performance improvement mod, which *should* have effect on how the game renders.

**Comment by modmuss50** [comment]
Sodium currently doesn’t implement the Fabric rendering API that TR uses to render the cells. I believe this is being worked on for an upcoming version of Sodium.
