### ISSUE TITLE
Basic tank only fills to 1%

### ISSUE THREAD

**Issue by bentterp** [TechReborn/TechReborn#2169]
**Describe the bug**
When I fill a basic tank using hydrogen cells, the tank only accept 35000 mb and then stops at 1% capacity

**Steps to Reproduce**
- Create and place basic tank
- Fill with hydrogen 

 - Minecraft: 1.16.1
 - Mod Loader: Fabric
 - TR: 3.4.3 build 72

**Comment by jusvit** [comment]
35000 MB is the limit of the basic tank, so there's something funky going on with the used %. Just from general testing, it seems to work fine for me. Is there a more specific scenario when this happens?

![image](https://user-images.githubusercontent.com/4002351/87870769-8fc9fc00-c9ee-11ea-9c7f-9a199bd05e03.png)

**Comment by bentterp** [comment]
![image](https://user-images.githubusercontent.com/5476397/87874344-5e8b0500-c9c9-11ea-90fa-4554fbf444cc.png)

I can empty the tank and re-fill it again, same result. No errors in the logs.
Also, in-game docs claim a soemwhat higher capacity as you can see in the screenshot.

But, if it works as intenden then this is not that important.

**Comment by KnatteAnka** [comment]
Question do you have multiple basic tanks and can test if that behave the same way?

**Comment by bentterp** [comment]
Yes, I have two basic tanks, one had hydrogen and one had compressed air, both showed the low percentage
And the Advanced Tank seems to suffer from the same:
![image](https://user-images.githubusercontent.com/5476397/87910074-b24d2b00-ca69-11ea-98c8-4caddc1d6c1c.png)

**Comment by KnatteAnka** [comment]
Hmm looks like there is some problem on your end. have you tried in singelplayer and creative and see what the max capacity is?
for me it is shown correct capacity
![image](https://user-images.githubusercontent.com/10638776/87937790-a9724e80-ca95-11ea-9317-676d36362848.png)

**Comment by bentterp** [comment]
Yes, I get the same capacities in singlemode-creative

In machines,json on the server, the config seems right:
```
    "BasicTankUnitCapacity": {
      "comment": "How much liquid a Basic Tank Unit can take (Value in buckets, 1000 Mb)",
      "value": 35
    },
    "IndustrialTankUnitCapacity": {
      "comment": "How much liquid an Industrial Tank Unit can take (Value in buckets, 1000 Mb)",
      "value": 500
    },
    "QuantumTankUnitCapacity": {
      "comment": "How much liquid a Quantum Tank Unit can take (Value in buckets, 1000 Mb)(Compat: \u003d\u003d MAX_VALUE)",
      "value": 2147483
    },
    "QuantumStorageUnitMaxStorage": {
      "comment": "Maximum amount of items a Quantum Storage Unit can store (Compat: \u003d\u003d MAX_VALUE)",
      "value": 2147483647
    },
    "AdvancedTankUnitMaxStorage": {
      "comment": "How much liquid an Advanced Tank Unit can take (Value in buckets, 1000 Mb)",
      "value": 200
    }
```


Doh! Config is different in my client, must have been me messing around at some point. So the display is based on the client's config but the behavoiur is based on the server's - makes kinda sense
😊
