### ISSUE TITLE
Auto crafting table can't craft items from UU-matter

### ISSUE THREAD

**Issue by Grimoire-of-Chemist** [TechReborn/TechReborn#2170]
**Describe the bug**
Auto crafting table can't craft items from UU-matter

**Steps to Reproduce**
- Place an auto crafting table and charge it
- Arrange a recipe regarding UU-matter

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: fabric

**Comment by modmuss50** [comment]
Can confirm, not sure why tho
