### ISSUE TITLE
Materials for industrial mills and industrial blast furnaces

### ISSUE THREAD

**Issue by xzdxp** [TechReborn/TechReborn#2173]
The version is 1.16

Industrial mills need steel, industrial blast furnaces need nickel, while nickel acquisition needs industrial mills and steel acquisition needs industrial blast furnaces. However, using waste materials to acquire nickel is too slow. I hope this can be improved.

**Comment by KnatteAnka** [comment]
You know that you can get Small Pile of Nickel dust in a Industrial centrifuge?

**Comment by xzdxp** [comment]
> 您知道您可以在工业离心机中得到一小堆镍粉吗？

But industrial centrifuges need tungsten, and tungsten needs industrial blast furnaces to get it.

**Comment by xzdxp** [comment]
> 您知道您可以在工业离心机中得到一小堆镍粉吗？

Thank you, I seem to have forgotten this.
