### ISSUE TITLE
Machines don't pull from Barrels

### ISSUE THREAD

**Issue by astocky** [TechReborn/TechReborn#2174]
**Describe the bug**
After updating to TechReborn-1.16-3.4.4+build.86 machines (grinder and electric furnace) that would drag input from Vanilla Barrels and automatically output to barrels (with version TechReborn-1.16-3.4.3+build.72), no longer take input from barrels. They will still take input from hoppers on the same side, and auto output still works.

**Steps to Reproduce**
Build machine, configure input and output (top input, bottom output, both automatically), put items into top barrel, nothing happens.
Replace top barrel with vanilla hopper and then it works normally (but much slower)

**Screenshots**

**Environment (please complete the following information with the version):**
Minecraft 1.16.1
TechReborn-1.16-3.4.4+build.86
fabric-api-0.16.0+build.384-1.16.1
fabric loader 0.9.0 build 204

**Comment by KnatteAnka** [comment]
i can confim that i have the same problem for Grinder, electric furnace, compressor and more.
 
**Environment (please complete the following information with the version):**
Minecraft 1.16.1
TechReborn-1.16-3.4.4+build.86
RebornCore-1.16-4.3.3+build.61
fabric-api-0.16.0+build.384-1.16.1
Jumboloader 2.0.0

**Comment by KnatteAnka** [comment]
Even hopper to input side is not working! (hopper places at generators left side )

**Comment by KnatteAnka** [comment]
Can confim that this bug is fixed with last release today
