### ISSUE TITLE
Most products and resources missing icons?

### ISSUE THREAD

**Issue by Silentdarkness12** [TechReborn/TechReborn#2176]
**Describe the bug**
Looking at Tech Reborn's item listings in Roughly Enough Items, I see that a number of products from Tech Reborn and other resources are missing their icons.

**Steps to Reproduce**
- Irrelevant, it happens automatically

**Screenshots**
[https://i.imgur.com/0KWkwSs.png](url)
https://i.imgur.com/SPjWVQX.png

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: fabric

**Logs**
[https://pastebin.com/pdwH7JBw](url)

**Additional context**
I should mention that Sodium is being used if that's somehow causing the icons to not render for whatever reason. Also i'm not using a texture pack of any sort, or a shader, or anything else I can think of that would cause these icons to not work. In fact here is a list of my mods in the offchance there's a conflict I don't know of. [https://i.imgur.com/LVps1gW.png?1](url)

**Comment by KnatteAnka** [comment]
Known issue of sodium that does not support the needed render
https://github.com/jellysquid3/sodium-fabric/issues/5
Also affecting optifine. Think a fallback will be implanted to next release to show base texture of the item and not a invisible item.

**Comment by modmuss50** [comment]
Yes what @KnatteAnka said
