### ISSUE TITLE
Invisible cells

### ISSUE THREAD

**Issue by Duzhk** [TechReborn/TechReborn#2179]
All the cell textures, whether empty or liquid are completely invisible

**Comment by KnatteAnka** [comment]
Can we keep this open as this is a known issue because of Sodium cant render it. this way new bug reports is not started each day!
https://github.com/jellysquid3/sodium-fabric/issues/5
also #2176

**Comment by Redd56** [comment]
can confirm still occurs, any thoughts on a 2ndary way to render it when sodium is installed?
also the cells show up but now its the 2nd layer that doesnt show. the one with the fluid. or atleast for me

**Comment by modmuss50** [comment]
I have added a fallback when using an incompatible mod. What version of tech reborn are you using?

**Comment by Redd56** [comment]
3.5.4 build 122

**Comment by Redd56** [comment]
the cells render, but the item inside the cells do not

**Comment by Redd56** [comment]
though the coolant cells actually do render
also buckets dont have their contents rendered
