### ISSUE TITLE
[IC2 Classic] Cable not connected

### ISSUE THREAD

**Issue by MrBretze** [TechReborn/TechReborn#218]
All cable could not connect to TechReborn machine

http://puu.sh/l5C4T/353359a3b1.jpg

http://puu.sh/l5C9e/7c5d2bdaeb.jpg

Tested on build 955

**Comment by modmuss50** [comment]
Mind testing with the newest version? Also check that your config has EU enabled.

**Comment by MrBretze** [comment]
I tested this week because i am not my cumputer

**Comment by MrBretze** [comment]
Yes it work

**Comment by modmuss50** [comment]
Great :)
