### ISSUE TITLE
Inconsistent biofuel fluid textures [TechReborn-1.16-3.4.5+build.95]

### ISSUE THREAD

**Issue by loleq2105** [TechReborn/TechReborn#2180]
**Describe the bug**
The bifuel fluid has a 32x texture when it's a source block and a 16x one when it's a flowing fluid block.

**Steps to Reproduce**
look at both fluid variants of biofuel

**Environment (please complete the following information with the version):**
- Minecraft 1.16
- Fabric 

**Additional context**
You should make all of the biofuel's textures 16x. The inconsistency breaks the immersion a bit.

![2020-07-28_14 40 09](https://user-images.githubusercontent.com/52840858/88666839-e4e9ca00-d0e0-11ea-9ffa-7e7bef47c68c.png)

**Comment by drcrazy** [comment]
Duplicate for #2309
