### ISSUE TITLE
Certain armor pieces made fo sertain gemstones have an unusually high armor rating [TechReborn-1.16-3.4.5+build.95]

### ISSUE THREAD

**Issue by loleq2105** [TechReborn/TechReborn#2181]
**Describe the bug**
Certain armor pieces made of certain gemstones have an unusually high armor rating.
Look at:
- ruby leggings (7)
- perdiot leggings (8)
- all shapphire armor pieces (4)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric

**Additional context**
dunno if that's intentional or not

**Comment by drcrazy** [comment]
Yes, it is intentional.

Full set defense of each gem armor still gives you 16. For reference, full iron set  gives you 15.
More stats for armor is in table here: https://wiki.techreborn.ovh/doku.php?id=items#armor
