### ISSUE TITLE
All cell cannot be translated into Chinese,E.g. water cell,lava cell.

### ISSUE THREAD

**Issue by NoWhereMee** [TechReborn/TechReborn#2184]
I think it is because of using NBT tabs.

**Comment by drcrazy** [comment]
We have TR translation on crowdin.com

Cells are translated like this:
1) We have "%fluid% cell" string, which is translated to Chinese. 
![image](https://user-images.githubusercontent.com/1382352/96286069-7e41c180-0fe8-11eb-9bbd-b1f40b8b5024.png)

2) We have translation for specific fluids
![image](https://user-images.githubusercontent.com/1382352/96286130-9580af00-0fe8-11eb-946f-aa29398a6cd3.png)

Cell translation is a replacement of a placeholder %fluid% with actual translation. This might not fully work for some languages and produce weird results in some cases, but it is the only way to have cells for fluids from other mods.

**Comment by drcrazy** [comment]
Feel free to fix TR translation to Chinese here: https://crowdin.com/project/techreborn
