### ISSUE TITLE
Item/block textures issues within modpack use

### ISSUE THREAD

**Issue by NxD136** [TechReborn/TechReborn#2188]
**Describe the bug**
A bunch of tiems and-or blocks do not appear to have textures.

**Steps to Reproduce**
- Open inventory
- Scroll to or search for Tech Reborn items/blocks

**Screenshots**
![Snag_31a11bd](https://user-images.githubusercontent.com/51761243/89119342-d0f4ee00-d47b-11ea-8497-c9bdfcfb68c8.png)

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.1]
 - Mod Loader: [Fabric]
 - Modpack containing over 200 mods

**Logs**
Pastebin : https://pastebin.com/Y70yuxrH  |  latest log

**Additional context**
If the problem is a compatibility issue with another mod, please send any pointers my way to help me resolve the issue for my modpack. Which you can find at [this link](https://www.curseforge.com/minecraft/modpacks/textiles-continuum)

**Comment by KnatteAnka** [comment]
Do you have optifine or sodium installed? there exist a problem on there end that do that they dont show some renderings. 
May be Linked to #2176 and #2179

**Comment by NxD136** [comment]
I have sodium installed. That's a bummer since a lot of people want sodium for the fps increase. Do you know if there is any talk chance of a fix either on your end or on Sodium's end? Just wondering because I really do not want to let go either of those two mods.

**Comment by jusvit** [comment]
> I have sodium installed. That's a bummer since a lot of people want sodium for the fps increase. Do you know if there is any talk chance of a fix either on your end or on Sodium's end? Just wondering because I really do not want to let go either of those two mods.

Sodium is working on a fix jellysquid3/sodium-fabric#5, there is not much we can do on our end besides just removing the fluid renderer when sodium is installed on the cells (e.g, just blank cells) which isn't much of an alternative. Therefore I think we'll just wait for sodium to put fourth their fix.

**Comment by Nixill** [comment]
> there is not much we can do on our end besides just removing the fluid renderer when sodium is installed on the cells (e.g, just blank cells) which isn't much of an alternative.

If you ask me, it's better than having invisible items in inventories/REI and wondering why you suddenly aren't seeing tooltip names after putting something down or aren't picking up items even though it looks like you have open slots. Could you at least make a "1" render on single cells?
