### ISSUE TITLE
Wikipedia page incomplete

### ISSUE THREAD

**Issue by Kriegermadmax** [TechReborn/TechReborn#2189]
**Describe the bug**
Your Wikipedia page with the recipes is incomplete and it makes it impossible for you to play the modpack properly and easily.

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**
-

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by modmuss50** [comment]
I would recommend using https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items to view all of the recipes in the game.

**Comment by drcrazy** [comment]
Keeping wiki up to date is an ongoing effort. Developers and wiki authors are doing their best to have wiki updated. Unfortunately we simply do not have enough time for that. Feel free to join wiki team.
