### ISSUE TITLE
Single use wooden plates

### ISSUE THREAD

**Issue by Moddingear** [TechReborn/TechReborn#2190]
**Describe the bug**
Wrenching a wooden plate makes it disappear, without looting

**Steps to Reproduce**
Place a wooden plate on some insulated cable
Right click the plated cable
The plate disappears without looting

**Environment (please complete the following information with the version):**
All Of Fabric 1.5.1 and 1.4.2 [Minecraft 1.16.1]

**Comment by vhd** [comment]
Actually - it was intended that way 😢 
The reason was to make more use for wooden plates.
On the other hand, this is now more predictable behavior for modded minecraft 😉
