### ISSUE TITLE
Quantum armor should use energy to defend enemies' attack

### ISSUE THREAD

**Issue by LegendLZD** [TechReborn/TechReborn#2191]
**Describe the solution you'd like**
In vanilla minecraft,diamond armor and netherite armor have armor toughness,but quantum armor in Tech Reborn doesn't have .I think if armor toughness can add to quantum armor,it will become more useful and more powerful.
(Outdated,look my new idea)

**Comment by ghost** [comment]
According to the [wiki](https://minecraft.gamepedia.com/Armor#Damage_protection), armor can only defend against 80% of incoming damage.  Armor toughness by itself has no special protection.  Toughness is just twice as efficient at stopping damage than a normal defense point.

The Quantum suit has a total of 80 defense points, this exceeds (by far) the amount of points needed to get the 80% damage reduction.  Adding toughness would not make the quantum suit stop more damage, unless the armor cap calculation is changed as well.

Are you noticing specific situations where the quantum suit's protection is under par?

**Comment by oOLegendOo** [comment]
OK,I know my suggestion is useless now.
So I close this myself

**Comment by LegendLZD** [comment]
I have another idea.
Quantum armor can store 160 million energy in total (40 million for each),but energy can only be used to active some functions.If the energy can be used to defend enemies' attack,it will be better.

**Comment by drcrazy** [comment]
Closed by https://github.com/TechReborn/TechReborn/commit/5861d411261cc2e2c172d9f7178130c60b76fdfa
