### ISSUE TITLE
Cannot Grind Marble

### ISSUE THREAD

**Issue by blu006** [TechReborn/TechReborn#2192]
**Describe the bug**
Cannot use the grinder to grind marble to marble dust

**Steps to Reproduce**
- Place Marble in grinder (grinder does not grind marble to marble dust)

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: fabric
 - Mod version v3.4.5+build.88

**Comment by Sturmlilie** [comment]
Cause lies in the detection of modded tags: https://github.com/TechReborn/RebornCore/issues/159

**Comment by drcrazy** [comment]
Should be closed by b59c535c3d5869d0c4c2d8939ef4af3159e050e8

Please, reopen if not.
