### ISSUE TITLE
Omni-Tool doesn't correctly harvest some Ores.

### ISSUE THREAD

**Issue by MonsterActual** [TechReborn/TechReborn#2196]
**Describe the bug**
The Omni-Tool's harvest abilities are not set correctly. It CANNOT harvest (disappears upon breaking) Copper, Tin, or Galena ores, but CAN harvest Iron ore blocks.

EDIT/UPDATE: The Advanced Drill has the same problem.

**Steps to Reproduce**
- Equip Charged Omni-Tool (Edit: or Advanced Drill)
- Break Ore Block

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric, "All of Fabric 3"
- Tech Reborn v3.4.5+build.88

**Comment by ghost** [comment]
This bug also affects the Basic Drill. The Basic Jackhammer works fine, though.

Version: 1.16.1
TechReborn-1.16-3.4.5+build.88
