### ISSUE TITLE
TechReborn cells aren't registered as fluid containers

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn#22]
I don't know the technical details, but TechReborn cells aren't registered as containing their fluid in the same way as ic2 cells, forestry cans, etc. Due to this, TechReborn fluid cells can't be piped out via liquid transposers, used in generators, etc.

**Comment by modmuss50** [comment]
We are going to remove them because ic2 adds its own ones, The recipes need fixing to support this chnage

**Comment by Carbon-Ghost** [comment]
Wait I don't understand, if you want your mod being independent from IC2, how are we gonna transport around stuff in cells ?

Also it's fully independent right ? Not only energy Wise ?

**Comment by modmuss50** [comment]
At the moment its not. Thats a good, point

**Comment by joflashstudios** [comment]
I'm closing this for the time being since we've moved to universal fluid cells. This may change in the future.
