### ISSUE TITLE
No Rubber Trees On Server [1.16.2]

### ISSUE THREAD

**Issue by nephatrine** [TechReborn/TechReborn#2200]
**Describe the bug**
Rubber trees do not seem to be spawning when running the mod on a dedicated server. Using the same seeds in singleplayer, I am able to locate trees without issue.

**Steps to Reproduce**
- Install on server.
- Explore server.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric 0.9.1+build.205
 - RebornCore-1.16-4.4.0+build.67
 - TechReborn-1.16-3.5.1+build.101

**Comment by KnatteAnka** [comment]
Have you verifyed with a new world?

**Comment by nephatrine** [comment]
Yes. It looks like ores from TechReborn are not generating naturally either so I think all of TechReborn's worldgen is effectively not working when installed serverside in 1.16.2.

**Comment by ghost** [comment]
Can confirm on a 1.16.2 server running the latest versions.

**Comment by modmuss50** [comment]
Can you please try with fabric-loader 0.9.2 this may fix the issue.

**Comment by ghost** [comment]
You're right, with fabric-loader 0.9.2 Rubber Trees and TR ores are generated.
![image](https://user-images.githubusercontent.com/918422/90612403-4268c680-e208-11ea-85d5-dcdea86dbf5d.png)

**Comment by modmuss50** [comment]
Awesome! That’s great news thanks for testing.
