### ISSUE TITLE
Issues with Hot Tungstensteel bar

### ISSUE THREAD

**Issue by thornwhip** [TechReborn/TechReborn#2201]
**Ender IO item filters do not always catch Hot Tungstensteel bars*

**Steps to Reproduce**
- Place ender IO item conduit down with industrial furnace as the out source and place 2 chests; one for ashes on for ingot. Place in basic item filter. Click the gear; drag hot ingot to either white list or black list (bug is apparent in both).  Watch as some Hot ingots make it into the black listed chest for ingot and some make it into the white listed chest for dark ashes.

**Comment by drcrazy** [comment]
Is it about 1.12? Have you tried metadata filter?

**Comment by drcrazy** [comment]
No response
