### ISSUE TITLE
Filterer

### ISSUE THREAD

**Issue by ayushaanand** [TechReborn/TechReborn#2202]
Please make such a hopper which can filter a certain item which is configurable by player and sends it to connected inventory. If it is not the correct item, the hopper will pass it to next hopper and implement it to 1.16.1. I am making a raid farm and really want to sort undying totems and crossbows. Please implement such a feature to 1.16.1 .

**Comment by ghost** [comment]
You could just install https://www.curseforge.com/minecraft/mc-mods/ezpas to do the sorting for you.  It has whitelist pipes that can be configured extensively.

**Comment by jusvit** [comment]
Filtering is on the way. Give it 10 weeks or so, it's apart of the item conduits that are currently under development.

**Comment by ayushaanand** [comment]
I tried ezpas and it works but is a little bit 
confusing to use.Thank you Katorone for suggestion.
