### ISSUE TITLE
Incompatible with new libcd? (crash at launch)

### ISSUE THREAD

**Issue by crest1993** [TechReborn/TechReborn#2203]
**Describe the bug**
Incompatible with new libcd?

**Steps to Reproduce**
Vanilla Hammer use new libcd and it crash the game if i installed both of the tweak

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

[log](https://pastebin.com/tX5ZSkWj)

**Additional context**

**Comment by ghost** [comment]
I have:
- TechReborn-1.16-3.5.1+build.101
- RebornCore-1.16-4.4.0+build.67
- fabric-api-0.18.0+build.397-1.16
- fabricloader@0.9.2+build.206
- vanilla-hammers-2.0.5-1.16.2
This crash isn't happening for me.

You're using Fabric Loader 0.9.1+build.205, could you try updating?

**Comment by modmuss50** [comment]
Looks like Lib CDs api broke

**Comment by LocalityHD** [comment]
download the latest 1.16.1 version of libcd. For some reason all of the 1.16.2 versions cause vanilla hammers and tech reborn to crash the game when loaded together.

**Comment by psecegm** [comment]
LibCD removed Tweaker code as of the 1.16.2  release:


1.16.2 Update: The Great Scale-Back
    Update to Minecraft 1.16.2
    Remove tweakers and all associated systems. This is a breaking change.
    LibCD is now 47 KB (15% the size of 2.5.0), small enough to JiJ without worrying about excess bloat.

Tweakers will return in a new project with an altered scope. Please be patient while I work on this.

**Comment by drcrazy** [comment]
Should be fixed by 4b6036530c07b5faa06cc58593de959601b26231
