### ISSUE TITLE
Void inputted items for creative storage units/tanks

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2205]
**Is your feature request related to a problem? Please describe.**
While testing mods I often chain machines together with creative storage units in between.
Items inputted to the creative storage unit stay in the IN slot, eventually locking the source machine or pipes.

**Describe the solution you'd like**
A creative storage unit/tank can safely void the inputted item/liquid when it is the same to which it's configured to.

**Describe alternatives you've considered**
Outputting to a block like Kibe's trashcan is an option, but makes it impossible to detect when other mods deposit the wrong items, or when machines produce the wrong items.  Using a quantum storage unit would be fine for long-term testing, but is less optimal for stresstesting a sufficiently provisioned network.

**Comment by drcrazy** [comment]
@Katorone  What about bucket or cell item in tank unit? Should they also void?

**Comment by ghost** [comment]
Only the actual liquid should be voided.  Leftover cells or buckets should be returned like other tank units do.  
I'm considering that handling the buckets/cells is part of the test setup.  The player can either void excess buckets/cells, or they could be testing the network with a limited amount of cells, in which case it's useful to know if any go missing.
