### ISSUE TITLE
Add liquid canning machine or liquid pump

### ISSUE THREAD

**Issue by Kashouryo** [TechReborn/TechReborn#2207]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to create water/other liquid cells automatically. While a lot of devices requires water to work.

**Describe the solution you'd like**
Add a pump-like device that pumps water from the water block and fills empty cells. while pumping liquid, remove the liquid block that it just pumped, so it won't replace fluid replicator's job.

**Describe alternatives you've considered**
liquid tanks can directly pull water from the water block.

**Additional context**
Thank you for bringing this cool open source fabric mod! you guys are awesome!

**Comment by ghost** [comment]
If you're on a recent version of TR, there is the drain.
For water, you can put a drain under a (water source block, and on top of a tank.  You can then fill cells automatically with water through that tank.

This as an aside, personally I'd love a kind of pump or drain that could deal with flowing liquids as well, so it could be used to drain lakes of lava, for instance.

**Comment by Kashouryo** [comment]
Thank you for your time! The drain is the exact item that I was looking for.
