### ISSUE TITLE
Tanks allow stacking fluid buckets

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2209]
**Steps to Reproduce**
- Place a Tank Unit. Fill it with two buckets of water.
- Right click it with a stack of two empty buckets.
- You get a stack of two water buckets, which isn't allowed in vanilla.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric

**Additional context**
I did it in creative, but it should also work in survival.

**Comment by jusvit** [comment]
Thanks for reporting, fix is underway.
