### ISSUE TITLE
[1.16.2 versions] Conflict With Vanilla Hammers and Tech Reborn

### ISSUE THREAD

**Issue by KingShibaInu** [TechReborn/TechReborn#2211]
Upon opening the game with just Vanilla Hammers with any 1.16.2 version and Tech Reborn with any 1.16.2 version installed the game proceeds to crash. I've contacted the author of Vanilla Hammers and they've responded with, "TechReborn is pulling an old version of LibCD. I'm pulling the new 1.16.2 version which removed a few features, they're using the 1.15.2 version."

- open the game

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric-loader-0.9.3+build.207-1.16.2

[crash-2020-07-04_22.25.48-client.txt](https://github.com/TechReborn/TechReborn/files/5179109/crash-2020-07-04_22.25.48-client.txt)

**Comment by drcrazy** [comment]
Duplicate for #2203
