### ISSUE TITLE
Player placed rubber wood still gives sap

### ISSUE THREAD

**Issue by alex-gillott** [TechReborn/TechReborn#2212]
During a playthrough with Tech Reborn version 1.16-3.4.5-build.50, my friends and I have discovered that we can build pillars of rubber wood up to sky limit and use a resin basin to create obscene and unbalanced quantities of rubber in a short period of time.
This is due to player-placed rubber wood still producing sap, and obviously we can place as much as we please.

Gather loads of rubber wood
Build pillar of rubber wood
Place basin at bottom
Place chest under basin

![2020-09-06_17 55 34](https://user-images.githubusercontent.com/20886909/92330898-71859180-f06a-11ea-8134-4ddcab3f654f.png)
![2020-09-06_17 57 09](https://user-images.githubusercontent.com/20886909/92330900-72b6be80-f06a-11ea-85a5-d82c712d82c2.png)

Environment:
 - Minecraft 1.16
 - Fabric Modloader

**Additional context**
This may or may not be intentional behaviour, but it really doesn't feel balanced in regards to rubber production (As you can make 14 rubber with 4 sap, the quantities get quite out of hand)

**Comment by drcrazy** [comment]
Back in 1.12 and earlier there was no easy way to save log state, e.g. was it grown or placed. As an enhancement we will look into adding this information to log block.

**Comment by PhoneixS** [comment]
What about checking if it is connected to leaves?

**Comment by drcrazy** [comment]
Player can place leaves )

**Comment by alex-gillott** [comment]
The way I've seen has been through the usage of damage values (Or using NBT in the later versions)
The tree spawns the log blocks with a damage value of 1, say, and damage 1 logs can produce sap. When broken, they drop damage value 0 logs, which can't produce sap

**Comment by trinity-1686a** [comment]
Another fix would be to limit how many blocks a resin basin is checking. If it can only check for 10 blocks (maybe even a configurable amount?), it is as balanced as if it was put to a tree, even when it's hand placed wood. It's probably easier to implement that way
