### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by DariusSG** [TechReborn/TechReborn#2214]
**Describe the bug**
The games keep trying to load textures

**Steps to Reproduce**
Steps to reproduce the behaviour:
Launch the game and watch it keep restarting.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Fabric Loader 0.9.3+build.203
 - Fabric API 0.20.1build 401

**Logs**
[latest.log](https://github.com/TechReborn/TechReborn/files/5181157/latest.log)
%Pastebin has a size limit of 512kb%

**Additional context**
Apparently, AE2 is also affected but it is a different issue.

**Comment by drcrazy** [comment]
Fix your mod pack. 
```
[12:59:15] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474cfa, also found 0.1.3+12a8474c4e, 0.1.3+12a8474ca7
 - Conflicting versions found for fabric-networking-v0: used 0.1.10+e00ecb5f4e, also found 0.1.10+e00ecb5fa7
```
For example, you have several fabric API loaded. 

Issue has nothing to do with either TR or RC.
