### ISSUE TITLE
Uncharged basic jackhammer works like it was charged.

### ISSUE THREAD

**Issue by Adirelle** [TechReborn/TechReborn#2217]
**Describe the bug**
The uncharged jackhammer seems to work like it was charged.

**Steps to Reproduce**
1. Create a jackhammer.
2. Enchant it.
3. Use it until discharged.
4. Continue using it as it was loaded.
5. ???
6. Profit !

**Screenshots**
![2020-09-10_23 04 05](https://user-images.githubusercontent.com/24633/92806565-6b6d1900-f3ba-11ea-93b1-691a64aa23c7.png)

**Environment:**
 - Minecraft: 1.16.2
 - Mod Loader: fabric
 - fabric-api: 0.20.1+build.401-1.16
 - TechReborn: 1.16-3.5.3+build.115
 - RebornCore: 1.16-4.4.1+build.69

**Comment by jusvit** [comment]
Son of a gun, I thought I fixed this, stupid enchantments.

**Comment by Adirelle** [comment]
Sry for the double post. I think firefox tricked me.
