### ISSUE TITLE
Tanks will not retain liquids

### ISSUE THREAD

**Issue by cablerunner** [TechReborn/TechReborn#2218]
**Describe the bug**
When you break a tank, it will not retain the liquids.

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by jusvit** [comment]
It states on the GUI you must wrench it for it to retain the liquid.
