### ISSUE TITLE
Bugs with Digital chest

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#222]
![2015-11-02_10 55 35 2](https://cloud.githubusercontent.com/assets/8685029/10879335/bb972be8-8153-11e5-8009-779bc2d677d2.png)
Wrong icon texture
TechReborn-0.5.5.959-universal

**Comment by modmuss50** [comment]
The tool tip is not useless because when you break the block with items in you can see what's in there.I do see your point though.

**Comment by Xen1290** [comment]
Sorry, I messed up with the issues, for this thing the icon texture is wrong like this https://github.com/TechReborn/TechReborn/issues/213

**Comment by modmuss50** [comment]
I can see what you mean, you wern't wrong.

**Comment by Xen1290** [comment]
Perfect, thanks and sorry!
