### ISSUE TITLE
Inconsistent ArrayOutOfBounds with Astromine.

### ISSUE THREAD

**Issue by vini2003** [TechReborn/TechReborn#2220]
With an Astromine Buffer set to output to an Autocrafting Table, and the table set to Auto Input from its side, a crash happens, although with no direct links to Astromine itself, when placing an item on the grid. Unable to consistently reproduce.

[LINK](https://gist.github.com/vini2003/3cb9695a2a8402080226e221287b42ef)

```
tech_reborn_version=3.5.3+build.116
reborn_core_version=4.4.1+build.69
```

I maintain Astromine; feel free to tell me if this is on my end or not, but I am unable to pinpoint it.

**Comment by vini2003** [comment]
The linked issue is not the same as I am getting; but I discovered this when testing that.

**Comment by drcrazy** [comment]
Astromine discontinued. Won't fix
