### ISSUE TITLE
Unable to output from machines in to AE2 ME Interface

### ISSUE THREAD

**Issue by Naosyth** [TechReborn/TechReborn#2221]
**Describe the bug**
When setting up Tech Reborn machines for auto crafting with an AE2 network, ME Interfaces are able to input ingredients in to the machine (e.g. coal gets successfully inserted in to a grinder), but the output from the machine does not get automatically output back in to the ME Interface. The machine is configured to auto output to the correct side. I've also verified that other blocks, such as hoppers, are capable of inserting in to the ME Interface.

This is on 1.16.2 Fabric

**Steps to Reproduce**
- Place ME Interface on one side of Tech Reborn machine
- Configure machine to accept input items from the side with the interface
- Configure machine to auto output back from the side with the interface
- Machine gets input ingredients, but does not push the output back to the interface

**Screenshots**
![image](https://user-images.githubusercontent.com/1323992/93014115-13bde180-f563-11ea-9805-4a4a3dca975f.png)
![image](https://user-images.githubusercontent.com/1323992/93014122-21736700-f563-11ea-94e9-2b8307bfbec1.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric
 - Tech Reborn: 3.5.2 build 110

**Comment by modmuss50** [comment]
Ive taken a look at this, the ME interface is not a minecraft `Inventory` thus the machine cannot insert into it. I might be wrong but I think this is a bug with AE2.

**Comment by Naosyth** [comment]
That's possible, I'm not really familiar with how these things are implemented, but I do know it was possible to output to interfaces directly in the past, and I also tested that hoppers could push items in to interfaces. I didn't test any other machines though, so maybe hoppers are a special case.

**Comment by drcrazy** [comment]
Yes, hoppers are special case. LBA, used by AE2, have special mixin to change hopper behaviour.
