### ISSUE TITLE
Advanced jackhammer duplicates itself

### ISSUE THREAD

**Issue by Adirelle** [TechReborn/TechReborn#2222]
**Describe the bug**
When activated, the advanced jackhammer drops serveral copies of itself along with the mined blocks.

**Steps to Reproduce**
1. Build an advanced jackhammer.
2. Activate it.
3. Mine.
4. Profit !

**Screenshots**
Look at all these advanced jackhammers !
![2020-09-14_19 52 49](https://user-images.githubusercontent.com/24633/93120582-e3da1f80-f6c3-11ea-9f45-83e59aa00407.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric

**Comment by ghost** [comment]
Do you have Allure?

**Comment by Adirelle** [comment]
Yep. And I just noticed that this does not happen in my "debug" setup, with only TechReborn..

**Comment by ghost** [comment]
I suspect you're encountering this conflict: https://www.curseforge.com/minecraft/mc-mods/allure/issues/3
As of yet it's not solved.

**Comment by drcrazy** [comment]
Fixed on Allure side
