### ISSUE TITLE
Assembling Machine causes crash

### ISSUE THREAD

**Issue by jannikac** [TechReborn/TechReborn#2224]
**Describe the bug**
The Problem occurs in Sky Odyssey.
I dont know if this occurs in vanilla, but in Sky Odyssey the game just crashes after placing a Assembling Machine.
You then have to remove the block with a tool like MCedit, otherwise the game crashes immediately after loading the world.

**Steps to Reproduce**
- Launch sky odyssey
- Create a world from any template
- Go to creative and place an assembling machine

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.12.2
 - Mod Loader: forge
 - Tech Reborn version: TechReborn-1.12.2-2.27.1.1076-universal
 - Reborn Core Version: RebornCore-1.12.2-3.19.3.524-universal
 - Sky odyssey 1.2.0

**Logs**
- [crash report](https://github.com/jannikac/misc/blob/master/crash.log)
- [latest log](https://github.com/jannikac/misc/blob/master/latest.log)

**Additional context**

**Comment by drcrazy** [comment]
Can you try with latest TR version, please? 
TechReborn-1.12.2-2.27.3.1084-universal.jar

**Comment by jannikac** [comment]
The game now crashes before starting. Here are the crash reports.

- [crash report](https://github.com/jannikac/misc/blob/TechReborn-1.12.2-2.27.3.1084/crash.log)
- [latest log](https://github.com/jannikac/misc/blob/TechReborn-1.12.2-2.27.3.1084/latest.log)

**Comment by jannikac** [comment]
Forgot to update RebornCore. Game now start and everything is working.

Working with:
- RebornCore-1.12.2-3.19.4.529-universal
- TechReborn-1.12.2-2.27.3.1084-universal

**Comment by mtbrenner** [comment]
Had the same issue in SkyOdyssey, works for me after updating current pack version 1.3.0 with

- RebornCore-1.12.2-3.19.5-universal
- TechReborn-1.12.2-2.27.3.1084-universal
