### ISSUE TITLE
Cloaking Device doesn't work

### ISSUE THREAD

**Issue by TheVoidX3** [TechReborn/TechReborn#2226]
**Describe the bug**
When you are using that cloaking Device you just flicker
**Steps to Reproduce**
- First Step get cloaking Device
- Second Step use it

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by drcrazy** [comment]
What version of MC?

**Comment by TheVoidX3** [comment]
1.16.2

**Comment by TheVoidX3** [comment]
It says that

**Comment by drcrazy** [comment]
Can't reproduce on 1.16.3.  Have you put it into chest armor slot?

![image](https://user-images.githubusercontent.com/1382352/94197504-8feaea00-febe-11ea-8266-351ce53dd75b.png)

**Comment by TheVoidX3** [comment]
I have found it sometimes works and sometimes doesn't and I am on 1.16.2
