### ISSUE TITLE
Game crashes when breaking windmills

### ISSUE THREAD

**Issue by Nyanxikun** [TechReborn/TechReborn#2228]
**Describe the bug**
Game crashes when breaking windmills with pickaxes or shift-right-click using wrenches.

**Steps to Reproduce**
- First Step, break the windmill with pickaxes or wrenches.
- Second Step, profit.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: Fabric

**Logs**
[crash-2020-09-23_13.18.56-client.txt](https://github.com/TechReborn/TechReborn/files/5269852/crash-2020-09-23_13.18.56-client.txt)

**Comment by drcrazy** [comment]
Can't reproduce in 1.16.3. Can you retest with later RC& TR, please?

![image](https://user-images.githubusercontent.com/1382352/94198162-857d2000-febf-11ea-90fe-3d7a886dbbb2.png)

**Comment by Nyanxikun** [comment]
I figured this is an issue with shaders/optifine, not with TR. Sorry for the misinformation!

**Comment by drcrazy** [comment]
It is absolutely fine. Better report and close than not report.
