### ISSUE TITLE
Clarification on Gregtech Port Version

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#223]
@modmuss50 I have a question, TechReborn is a port of Gregtech 2 for 1.4.7, right?
The last GT Version for 1.4.7 is 2.90h, but on readme says that TechReborn is a port is from 2.78(This version doesn't exist on GT tread, only 2.90h is available). So why assembling machine is back and the other things removed because are between 2.78 and 2.0 not?
Sorry for possible english mistakes.

**Comment by modmuss50** [comment]
The assembly machine has been added back because pack devs found it useful. We don't add any recipes to it.

**Comment by Xen1290** [comment]
Ok, perfect, thanks.
