### ISSUE TITLE
Advanced jackhammer cant break ancient debris

### ISSUE THREAD

**Issue by R3DRUMVNE** [TechReborn/TechReborn#2231]
**Describe the bug**
Advanced jackhammer cant break ancient debris

**Steps to Reproduce**
Try to break ancient debris with an advanced jackhammer.

**Screenshots**
Imgur video: [tap](https://imgur.com/a/oQeamHZ)

**Environment (please complete the following information with the version):**

- Minecraft version: 1.16.3
- Mod Loader: fabric-loader-0.9.3+build.207-1.16.3, fabric-api-0.21.0+build.407-1.16, RebornCore-1.16-4.4.2+build.73, TechReborn-1.16-3.5.4+build.122

**Comment by drcrazy** [comment]
Jackhammer is a good tool to break stone, dirt and sand. 
Ores shouldn't be broken by Jackhammer
