### ISSUE TITLE
Interdimension SU doesn't work interdimensionally 

### ISSUE THREAD

**Issue by Caridmum** [TechReborn/TechReborn#2236]
Interdimensional SU's don't link in different dimensions. They work overworld-to-overworld but neither overworld-to-nether nor overwold-to-end

minecraft 1.16.2, fabric, TR 1.16-3.5.3+build.115

![2020-09-30_21 27 19](https://user-images.githubusercontent.com/11216708/94768349-0e82d400-0364-11eb-891c-b1cbe1118ef1.png)
![2020-09-30_21 27 27](https://user-images.githubusercontent.com/11216708/94768351-0f1b6a80-0364-11eb-89ad-5fee671c4e8d.png)
![2020-09-30_21 27 42](https://user-images.githubusercontent.com/11216708/94768356-104c9780-0364-11eb-884b-d438accaa0fb.png)
![2020-09-30_21 27 51](https://user-images.githubusercontent.com/11216708/94768357-10e52e00-0364-11eb-95ab-5bd3d4500134.png)

**Comment by drcrazy** [comment]
Is you chunk loaded in overworld while you are in the nether?  What chunkloader do you use?

**Comment by Caridmum** [comment]
Yep, spawn chunks and industrial chunkloader in that test world with just TR and Kibe chunkloader on my AoF 3 server.

**Comment by DragonGodGrapha** [comment]
It seems as though the storage is being saved per dimension. Filling up a unit in the overworked leads to an empty unit in the nether, but multiple units in the nether share the storage

**Comment by lMaxTl** [comment]
I have the same issue
