### ISSUE TITLE
Add a metal workbench

### ISSUE THREAD

**Issue by Miros77** [TechReborn/TechReborn#2237]
you can use it to create everything that is available in TechReborn

and needed for a new villager
https://github.com/TechReborn/TechReborn/issues/2234

**Comment by Miros77** [comment]
craft
![крафт](https://user-images.githubusercontent.com/59547044/94859214-d8fde980-043c-11eb-9ca1-c4b504489d2d.PNG)

**Comment by R3DRUMVNE** [comment]
If implemented, add the item of this metal workbench to the auto workbench crafting recipe.

**Comment by Miros77** [comment]
Good idea

2020-10-02 9:02 GMT+03:00, Medwokee <notifications@github.com>:

**Comment by drcrazy** [comment]
Not as for now. Maybe in some distant future. Another option is to have someone to create PR on this.

**Comment by Miros77** [comment]
> PR

what is it PR?
