### ISSUE TITLE
Clarification on Iron Alloy Furnace

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#224]
@modmuss50 This machine didn't exist on GregTech, and is OP, it's an Induction Smelter that uses coal o similar fuel to work, and you can make bronze,invar etc very easy. What's its very functionality?

**Comment by modmuss50** [comment]
@gigabit101 can you help clarify?

**Comment by modmuss50** [comment]
@Mattabase ?? ^^

**Comment by Carbon-Ghost** [comment]
I agree, I see no point on keeping it... Not that it's OP but it's not really are relevant feature nor is really required and wasn't here on old GT.

**Comment by gigabit101** [comment]
its for map makers again and will be hidden behind config

**Comment by Carbon-Ghost** [comment]
...
