### ISSUE TITLE
OmniTool Does not provide techreborn Ores

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [TechReborn/TechReborn#2240]
**Describe the bug**
OmniTool Does not provide tech reborn ores when mining

**Steps to Reproduce**
- Get out Omni tool
- Mine Tech Reborn Ore (Lead, Copper, Etc)

**Environment (please complete the following information with the version):**
 - Minecraft 1.16.3
 - Mod Loader: Fabric

**Logs**
[https://paste.ee/p/tYyeO](https://paste.ee/p/tYyeO)

**Additional context**
Drills work fine, only seems to be affecting the Omnitool

**Comment by drcrazy** [comment]
Duplicate for #2196
