### ISSUE TITLE
It is impossible to craft copper wire without insulation

### ISSUE THREAD

**Issue by GGenAva** [TechReborn/TechReborn#2241]
Everything is translated by google translator.

** Please describe the error **
It is impossible to craft copper wire without insulation. There is no such recipe. Even in a wire making machine (if accessed through a JEI), it is impossible to make wire from copper ingots.

** Actions to play **
- It's just impossible to craft

** Screenshots **
Even in the wire machine, the wire is empty at the crafting site.
! [2020-10-05_18 14 17] (https://user-images.githubusercontent.com/72380208/95056191-b3702900-0737-11eb-8b28-526a99064fb6.png)

** Environment (please include the following information with the version): **
 - Minecraft: [eg 1.16.3]
 - Mod Loader: [Fabric]

** Magazines **
I can't do that.

** Additional context **
Mod version 1.16-3.5.4 + build.122

**Comment by drcrazy** [comment]
Cant' reproduce. Check if there are any changes in recipes by mod pack author.
ru_RU: Не воспроизводится. Может автор мод-пака что-то поменял.

![image](https://user-images.githubusercontent.com/1382352/95066514-2dd68400-070b-11eb-8e87-73f743f26f85.png)

**Comment by GGenAva** [comment]
Попробую удалить все остальные моды. Может тогда ошибка устранится.

**Comment by GGenAva** [comment]
Я нашёл конфликтующий мод.
Iron Chests 1.16.2-v1.1.2
