### ISSUE TITLE
I cant start a server on aternos, is shows followin error

### ISSUE THREAD

**Issue by Namonato** [TechReborn/TechReborn#2243]
I`m trying to start a server on Aternos with tech reborn mod, i`m not programmer, but i did everything according to instruction, i set up an Fabric to the server, installed Fabric API, got right version of modes and everything, please help me to solve my issue

Error is the following: 

[19:55:04] [main/INFO]: Loading for game Minecraft 1.15.2
--
2 | [19:55:06] [main/FATAL]: A critical error occurred
3 | net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: techreborn requires {fabric @ [*]}
4 | at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169) ~[fabric.jar:?]
5 | at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:605) ~[fabric.jar:?]
6 | at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric.jar:?]
7 | at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric.jar:?]
8 | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric.jar:?]
9 | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric.jar:?]
10 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
11 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
12 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
13 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
14 | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric.jar:?]
15 | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric.jar:?]
16 | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric.jar:?]
17 | Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
18 | at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric.jar:?]
19 | at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric.jar:?]
20 | at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric.jar:?]
21 | at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric.jar:?]
22 | at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167) ~[fabric.jar:?]
23 | ... 12 more

**Comment by modmuss50** [comment]
You also need to install https://www.curseforge.com/minecraft/mc-mods/fabric-api into the mods folder.

**Comment by Namonato** [comment]
> You also need to install https://www.curseforge.com/minecraft/mc-mods/fabric-api into the mods folder.

I already did it, what can be wrong?
![image](https://user-images.githubusercontent.com/72464176/95239623-dec84600-0813-11eb-80c3-a6cacaf46cff.png)

**Comment by modmuss50** [comment]
Can you double check as the error is `techreborn requires {fabric @ [*]}` saying that it cannot find fabric (api) in the mods folder

**Comment by Namonato** [comment]
> Can you double check as the error is `techreborn requires {fabric @ [*]}` saying that it cannot find fabric (api) in the mods folder

Check the screenshot, i have build 328, may be i have to install another version?
