### ISSUE TITLE
Implement the Industrial Chunk Loader

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [TechReborn/TechReborn#2244]
**Is your feature request related to a problem? Please describe.**
After a cursory google/curseforge search, looks like chunk loaders are available only for Forge. TechReborn has a hidden half-baked implementation that does not work.

**Describe the solution you'd like**
It would be nice to have the Industrial Chunk Loader as a craftable block in the Fabric mod ecosystem.

**Describe alternatives you've considered**
Switch to Forge? Use portal-based chunk loading hacks? Both are undesirable.

**Comment by modmuss50** [comment]
It may be just missing a recipe. As far as I know it’s fully working.

**Comment by 0xfeeddeadbeef** [comment]
I assumed the reason it was 'hidden' was that it didn't work. Also, I tried to use it in single-player, and, obviously, it had no effect there.

**Comment by drcrazy** [comment]
Implemented.
