### ISSUE TITLE
Jackhammers can mine ores

### ISSUE THREAD

**Issue by R3DRUMVNE** [TechReborn/TechReborn#2246]
**Describe the bug**
Jackhammer can break ores and they drop.

**Screenshots**
imgur: [tap](https://imgur.com/a/EWMLZUE)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: fabric-loader-0.9.3+build.207-1.16.3, fabric-api-0.22.1+build.409-1.16, RebornCore-1.16-4.4.2+build.73, TechReborn-1.16-3.5.4+build.122

**Comment by drcrazy** [comment]
Jackhammer speed on ores nerfed. It has Iron mining level thus some ores will still drop if mined directly, not via AOE.
