### ISSUE TITLE
(Probably) A list of recipes that should support tags but don't

### ISSUE THREAD

**Issue by Neubulae** [TechReborn/TechReborn#2247]
I haven't gone thru many and may probably update later but `mixed_metal_ingot`'s crafting recipe doesn't.
Oddly enough, it tagged aluminum/titanium/etc but not bronze or brass.
![image](https://user-images.githubusercontent.com/24774842/95722191-30565200-0ca6-11eb-918e-735d9cd55845.png)
Industrial Machine Frame/Casing doesn't support various Chrome plates but Titanium.
Tank units not supporting coal dusts and tungstens.
Probably every *unique* ore and alloy aren't supported.

**Comment by drcrazy** [comment]
I've fixed some recipes. Please, feel free to reopen with more examples.
