### ISSUE TITLE
Bronze dust creation recipe is missing

### ISSUE THREAD

**Issue by pinter-gabor-at** [TechReborn/TechReborn#2248]
**Describe the bug**
Usually in tech mods there is a recipe for creating bronze dust from 3 copper dusts and 1 tin dust.

**Steps to Reproduce**
- See recipes in Just Enough Items or Roughly Enough Items. Look for Bronze Dust.
- Try to mix copper dust and tin dust in any of the usual quantities in a crafting table. There is no way to produce bronze dust.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: fabric

**Comment by pinter-gabor-at** [comment]
I think this is the way to do it. Add these lines to /src/main/resources/data/techreborn/recipes/crafting_table/dust/bronze_dust.json

```
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "techreborn:copper_dust"
    },
    {
      "item": "techreborn:copper_dust"
    },
    {
      "item": "techreborn:copper_dust"
    },
    {
      "item": "techreborn:tin_dust"
    }
  ],
  "result": {
    "item": "techreborn:bronze_dust"
    "count": 4
  }
}
```

**Comment by drcrazy** [comment]
Tech Reborn doesn't have recipes to craft alloy dusts at all. Neither for bronze nor for invar, electrum, etc. 

We prefer Alloy Smelter -> Grinder workflow which is easy to automate.

Feel free to add these recipes in your modpack though.

**Comment by pinter-gabor-at** [comment]
Thank you. You are right. Alloy smelter is better. I missed it.
