### ISSUE TITLE
Omni-Tool doesn't have the right mining level

### ISSUE THREAD

**Issue by IsaacBStark** [TechReborn/TechReborn#2249]
**Describe the bug**
Omni-Tool doesn't have the right mining level. It can mine say, Redstone, but not other ores of the same level, like Lead.

**Steps to Reproduce**
- First Step: Make Omni-Tool
- Second Step: Attempt to Mine Lead, or any other same level ore

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2
 - Mod Loader: fabric
 - Mod Version: 1.16-3.5.3+build.115

**Additional context**
Playing in 'All of Fabric 3' v2.1.3

**Comment by drcrazy** [comment]
It is already fixed: #2240
