### ISSUE TITLE
[Suggestion] Add the ore dictionary unification

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#225]
Like old gregtech, when I hold something, techreborn transform that item in it's item.
Example:
Bronze Ingot (Mekanism) --> When I hold that in the inventory --> Bronze Ingot (Tech Reborn)
And also, enforce to output only tech reborn things.

**Comment by Carbon-Ghost** [comment]
and a config to disable that, as it was sometimes annoying...

**Comment by modmuss50** [comment]
It would have one :)

**Comment by Carbon-Ghost** [comment]
:3

**Comment by wormzjl** [comment]
Just make sure that this can be turn off completely by config, I've got too many bad experiences with gt5 unification

**Comment by modmuss50** [comment]
Ive added it, its disabled by default.

**Comment by Xen1290** [comment]
Thanks!
