### ISSUE TITLE
Java 14 and Java 15 Crash

### ISSUE THREAD

**Issue by AminoX99** [TechReborn/TechReborn#2250]
**Describe the bug**
The game is crashing when trying to play with java 14 or java 15

**Steps to Reproduce**
- Download Techreborn, Reborncore and Fabric api
- Put those 3 mods in a folder
- Launch the game with java 14 or java 15
- Crash

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.3]
 - Mod Loader: [Fabric]

**Logs**
It is the first time im reporting with a crash log, I tried using paste.gg

https://paste.gg/p/anonymous/6067e692331d4bf2b4136126dcb36066

**Additional context**
Fabric loader version: fabric-loader-0.10.3+build.211-1.16.3
Fabric api version: fabric-api-0.24.1+build.412-1.16.jar
Techreborn version: TechReborn-1.16-3.5.4+build.122.jar
Reborncore version: RebornCore-1.16-4.4.2+build.73.jar
java 14 version: jdk-14.0.2.12-hotspot
java 15 version: jdk-15.0.0.36-hotspot
java 14 arguments: -XX:+UnlockExperimentalVMOptions -XX:+UseZGC
java 15 arguments: -XX:+UseZGC (UnlockExperimentalVMOptions doesnt work on java 15 for some reason, I used only ZGC)

Also I'd like to point out that java 8 works perfectly fine

**Comment by drcrazy** [comment]
Java 8 recommended by Fabric: https://fabricmc.net/wiki/player:tutorials:java:windows

**Comment by modmuss50** [comment]
Java 15 is fully supported, I don’t believe this crash has anything to do with the java version.

**Comment by modmuss50** [comment]
This seems to be a wider issue? can you post the whole log?

Im running just fine with java 15, I have not encounted such an error before.

**Comment by AminoX99** [comment]
Alright hang on a second, I will post it now

**Comment by AminoX99** [comment]
https://paste.gg/p/anonymous/e5886adb01574df092502f88706dbf69

here is the log from latest.log

**Comment by AminoX99** [comment]
I'll try updating Tech reborn, Reborn core and fabric api to the latest version and then test again, maybe it will solve the problem or make it more clear on where it is crashing.

**Comment by modmuss50** [comment]
I cannot repoduce this, I use java 14 and 15 in dev and prod without issue.
