### ISSUE TITLE
Power display bug

### ISSUE THREAD

**Issue by LegendLZD** [TechReborn/TechReborn#2251]
**Describe the bug**
Power display have problem in the latest TR.This problem maybe caused by Reborncore

**Screenshots**
I have two pictures for example
![2020-10-23_21 06 08](https://user-images.githubusercontent.com/44722752/97007343-da21c280-1573-11eb-9d44-bc043ad33dcc.png)

![2020-10-23_21 06 00](https://user-images.githubusercontent.com/44722752/97007334-d5f5a500-1573-11eb-9d14-1d854de8e0d4.png)

**Environment (please complete the following information with the version):**
 - Minecraft:1.16.3
 - Mod Loader:fabric
 - Reborncore Version:RebornCore-1.16-4.4.2+build.81(Jenkins Latest)
 - TechReborn Version:TechReborn-1.16-3.5.4+build.135(Jenkins Latest,not important for this bug)

**Comment by drcrazy** [comment]
Yes, dev build is not behaving properly yet. Will be fixed in next two days

**Comment by drcrazy** [comment]
Fixed by https://github.com/TechReborn/RebornCore/commit/804a82bacc1adf166b16218d888331a5292222ed
