### ISSUE TITLE
Jackhammer broken

### ISSUE THREAD

**Issue by DaFuqs** [TechReborn/TechReborn#2253]
- When hammering stone with an activated (advanced) jackhammer (3x3 mode) the stone is broken, but +8 is added to the amount of the jackhammer (so after breaking once you have 9 jackhammers in the stack; can also exceed 64 later)
- When the jackhammer is at 0 power and another block is broken the jackhammer vanishes 

Tried:
Tech Reborn 3.5.4 build 122
Tech Reborn 3.5.3 build 115
on MC 1.16.2

**Comment by exline22** [comment]
I am having the same issue with the Industrial Jackhammer in 5x5 mode, though it seemed to be adding even more than 8 at a time.  Didn't try it on 3x3 mode when after it started glitching dozens of Industrial Jackhammers.

**Comment by drcrazy** [comment]
Do you have Allure mod installed?

I can't reproduce it in dev env. 

Just broke 8 blocks and haven't got any additional jackhammers

![image](https://user-images.githubusercontent.com/1382352/97209576-92967300-17cd-11eb-88d7-7fb81731c5f5.png)

**Comment by DaFuqs** [comment]
Indeed I have! I couln't reproduce it in my test instance with just TR either. 
After updating Allure from 1.2.6 to 1.2.7 the jackhammer doesn't duplicate and destroys itself anymore.

Sorry for reporting and thank you for the tip! Definitely was someting on Allures end. The last changelog even says "Fixed bug with tools being duplicated after use!"

**Comment by exline22** [comment]
Updating Allure also solved the problem for me.  Thanks so much for digging
into this and solving it even outside of your mod!
