### ISSUE TITLE
Omni-Tool can only break vanilla ores

### ISSUE THREAD

**Issue by DaFuqs** [TechReborn/TechReborn#2256]
**Describe the bug**
That includes tech reborn ores, like copper and lead.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.2 and also 1.16.3
 - Mod Loader: fabric 0.10.3 build 211
 - Tech Reborn 3.5.4 build 122
 - Reborn Core 4.4.2 build 73
 - Tested with Tech Reborn, Reborncore, hwyla and can i mine this block installed.

**Additional context**
Other powertools seem to work fine. Basic jackhammer and drill can mine everything besides obsidian tier, advanced versions can mine obsidian tier, like iridium ore, too.

**Comment by drcrazy** [comment]
Already fixed in dev. 

![Uploading image.png…]()
