### ISSUE TITLE
Astromine compat: Grinder

### ISSUE THREAD

**Issue by DaFuqs** [TechReborn/TechReborn#2257]
Astromine adds a bunch of new ores and variants for (vanilla) ores. Here is a list of ores for the grinder with amounts analog to the Astromine Triturator.
All dusts are functionally identical / oredicted to the tech reborn ones, so the results can also be exchanged to the TR ones (those that exist, that is).

**Grinder Recipes:**
astromine:meteor_metite_ore     => 6x astromine:metite_tiny_dust

astromine:asteroid_metite_ore   => 2x astromine:metite_dust
astromine:asteroid_asterite_ore => 2x astromine:asterite_dust
astromine:asteroid_stellum_ore  => 2x astromine:stellum_dust
astromine:asteroid_galaxium_ore => 2x astromine:galaxium_dust
astromine:moon_lunum_ore        => 2x astromine:lunum_dust
astromine:asteroid_coal_ore     => 2x astromine:coal_dust
astromine:asteroid_iron_ore     => 2x astromine:iron_dust
astromine:asteroid_gold_ore     => 2x astromine:gold_dust
astromine:asteroid_redstone_ore => 2x astromine:redstone_dust
astromine:asteroid_lapis_ore    => 2x astromine:lapis_dust
astromine:asteroid_diamond_ore  => 2x astromine:diamond_dust
astromine:asteroid_emerald_ore  => 2x astromine:emerald_dust

astromine:meteor_metite_cluster     => 3x astromine:metite_tiny_dust
astromine:asteroid_metite_cluster   => 2x astromine:metite_dust
astromine:asteroid_asterite_cluster => 2x astromine:asterite_dust
astromine:asteroid_stellum_cluster  => 2x astromine:stellum_dust
astromine:asteroid_galaxium_cluster => 2x astromine:galaxium_dust
astromine:moon_lunum_cluster        => 2x astromine:lunum_dust
astromine:asteroid_coal_cluster     => 2x astromine:coal_dust
astromine:asteroid_iron_cluster     => 2x astromine:iron_dust
astromine:asteroid_gold_cluster     => 2x astromine:gold_dust
astromine:asteroid_redstone_cluster => 2x astromine:redstone_dust
astromine:asteroid_lapis_cluster    => 2x astromine:lapis_dust
astromine:asteroid_diamond_cluster  => 2x astromine:diamond_dust
astromine:asteroid_emerald_cluster  => 2x astromine:emerald_dust
astromine:asteroid_copper_cluster   => 2x astromine:copper_dust
astromine:asteroid_tin_cluster      => 2x astromine:tin_dust
astromine:asteroid_silver_cluster   => 2x astromine:silver_dust
astromine:asteroid_lead_cluster     => 2x astromine:lead_dust

minecraft:netherite_scrap => astromine:raw_netherite_dust

**Duplicates that already have recipes thanks to the dictionary**
astromine:asteroid_copper_ore
astromine:asteroid_tin_ore
astromine:asteroid_silver_ore
astromine:asteroid_lead_ore
astromine:copper_ore
astromine:tin_ore
astromine:silver_ore
astromine:lead_ore

**Byproduct suggestions for the industrial grinder:**
Besides metite the materials seem pretty rare currently and more or less netherite - and resource gated (lots of copper, steel, metite).

metite: Titanium? ("withstands huge pressures"; also found in the overworld, netherite-tools only)
lunum: Lapis? Sapphire? (bright blue metal, moon only)
asterite: Red Garnet? Ruby? (Red gem. "Fragments of long dead stars)
stellum: Phosphor? (Orange metal, "vibrating with energy")
galaxium: Obsidian? Pyrope? (dark purple gem. "overwhelming dark shine")

**Comment by drcrazy** [comment]
Vanilla or common like clusters (gold, copper, etc.) should be tagged on astromine side. They have tagged  astromine:asteroid_tin_ore but skipped that for astromine:asteroid_tin_cluster. Maybe there is a reason for that. Maybe just overlooked.
