### ISSUE TITLE
Unbreaking and Mending can be applied to Lapotron Crystal

### ISSUE THREAD

**Issue by copygirl** [TechReborn/TechReborn#2263]
Unbreaking and Mending can be applied to Lapotron Crystal. Possibly other rechargeables, too. I doubt this is intentional, and I haven't tested the effects too much but it seemed like some of the XP I picked up went into the item.

Additionally, I want to note that it appears the Omni-Tool can accept Unbreaking but as far as I can see, no other tool does? May I ask which tools are intended to have it and which don't? (Note: I've seen #2016.)

### Screenshot
![image](https://user-images.githubusercontent.com/272586/97488127-1b441900-195e-11eb-80d7-a4a1824b26f9.png)

### Environment
**Minecraft:** `1.16.3`
**Tech Reborn:** `3.6.1`

**Comment by Bluberry-Kat** [comment]
the reason the omni-tool accepts unbreaking is because it actually *has* durability.
i made a separate issue for that here #2295
