### ISSUE TITLE
"Unable to get CCW facing of down" crash when other player places wind mill on server

### ISSUE THREAD

**Issue by copygirl** [TechReborn/TechReborn#2267]
Sometimes, when my friend moved wind mills on the server (to fix some issues with and figure out Astromine :laughing:), it caused me to crash out of the game while I was nearby. I can only assume this might be due to some machine state being synced a packet, and therefore a tick too late.

### Environment
**Minecraft:** `1.16.3`
**Tech Reborn:** `3.6.1`

### Logs
```
java.lang.IllegalStateException: Unable to get CCW facing of down
	at net.minecraft.class_2350.method_10160(class_2350.java:290)
	at techreborn.client.render.entitys.TurbineRenderer.render(TurbineRenderer.java:58)
	at techreborn.client.render.entitys.TurbineRenderer.method_3569(TurbineRenderer.java:41)
	at net.minecraft.class_824.method_23079(class_824.java:107)
```
Full MultiMC log: https://paste.ee/p/0dhuM

**Comment by modmuss50** [comment]
Yes, I think you are correct. What I have done is set the default facing to north as I believe all blocks should be able to use this before they get their facing set correctally. If there are still issues please open another issue.

Thanks
