### ISSUE TITLE
Tech Reborn storage units not keeping meta data/stored item contents

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2269]
**Describe the bug**
https://github.com/TeamAOF/All-of-Fabric-3/issues/153

**Comment by jusvit** [comment]
Translation: Items with NBT data is wiped when placed in a storage unit. As it only saves the item and the amount, I didn't think about the NBT data. A solution to this would to also store the item's NBT data alongside the item and amount (Also don't allow items with multiple NBT). Seems simple enough to fix, if no one else fixes this, I'll do it next week.

**Comment by drcrazy** [comment]
I think there is no point to store items with NBT at all. Most of them will be a single item stored in storage. For example, energy is stored in NBT, and same Basic Drill with different amount of energy won't stack. Same applies for enchants, portable storages, etc

**Comment by jusvit** [comment]
> I think there is no point to store items with NBT at all. Most of them will be a single item stored in storage. For example, energy is stored in NBT, and same Basic Drill with different amount of energy won't stack. Same applies for enchants, portable storages, etc

Either way, it should either reject items with NBT or store it. Not wipe the item.

**Comment by Technici4n** [comment]
It appears this is not an issue apparently ? https://streamable.com/tqwbdp

Would require testing with danks specifically...

**Comment by drcrazy** [comment]
Can't reproduce with Dank 3

Content before storage:
![image](https://user-images.githubusercontent.com/1382352/99287666-9c9b1700-284b-11eb-8374-ce9bc0dbca12.png)

Dank 3 in storage:
![image](https://user-images.githubusercontent.com/1382352/99287720-aae93300-284b-11eb-8a57-311c8864e9d7.png)


Content after getting back from storage unit:
![image](https://user-images.githubusercontent.com/1382352/99287777-b9cfe580-284b-11eb-9dfb-064f961d8a24.png)
