### ISSUE TITLE
Machines not implimented from GregTech 2

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#227]
- [ ] Distillation Tower
- [x] Vacuum Freezer
- [ ] Electric Crafting Table 
- [ ] Magic Energy Absorber
- [ ] Magic Energy Converter
- [x] Player Detector
- [x] TechReborn Computer Cube

These are the most important machines.

TechReborn-0.7.0.1036-universal
RebornCore-1.0.0.10

**Comment by Xen1290** [comment]
Updated the issues with other missing machines

**Comment by Xen1290** [comment]
Now this is the "machines not implemented from GregTech 2" issue.

**Comment by modmuss50** [comment]
Ok thanks for that.

**Comment by Xen1290** [comment]
:+1:

**Comment by modmuss50** [comment]
Ive updated the list, the chunkLoaded will be put it add-ons at some point.

**Comment by wormzjl** [comment]
And the electric sorting machine that used to separate small dust from normal dusts

**Comment by modmuss50** [comment]
see #339
