### ISSUE TITLE
Missing tags in recipes

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2270]
**Describe the bug**
Some TR recipes should be tagged to support Modern Industrialization's materials too.

Should tag invar plates:
![image](https://user-images.githubusercontent.com/13494793/98121258-5b038700-1eaf-11eb-89fa-0c64f9f576aa.png)
Should tag coal dusts: (and same for tier 1 solar panels)
![image](https://user-images.githubusercontent.com/13494793/98121295-66ef4900-1eaf-11eb-925f-5eb75f4660dd.png)
Should tag chrome ingots:
![image](https://user-images.githubusercontent.com/13494793/98121313-6e165700-1eaf-11eb-94f9-db3369b2522d.png)
![image](https://user-images.githubusercontent.com/13494793/98121340-75d5fb80-1eaf-11eb-96fb-4c3b40eba180.png)

I'll add more when I find them.

**Comment by drcrazy** [comment]
Thanks for spotting. Feel free to re-open with more findings or report a new one.
