### ISSUE TITLE
Overlapping upgrade tooltips

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2271]
**Describe the bug**
The tooltips overlap.
![image](https://user-images.githubusercontent.com/13494793/98121493-a5850380-1eaf-11eb-820a-3db2f7e5718d.png)

Also, clicking on the upgrade drops it instead of picking it up with the cursor for some reason?

**Steps to Reproduce**
- Put an Overclocker Upgrade in a Compressor

**Environment (please complete the following information with the version):**
 - TR version: 3.6.1 built from this repo a few days ago

**Comment by drcrazy** [comment]
Fixed by https://github.com/TechReborn/RebornCore/commit/f15ff1a8223c8c209d64c1f5545df0fb08165012
