### ISSUE TITLE
[1.16.3] Advancements not localized.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#2272]
**Describe the bug**
Seen on our discord link bot.

ServerLink: Goshen has made the advancement [advancements.techreborn.treetap]
ServerLink: Goshen has made the advancement [advancements.techreborn.sap]

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: Fabric

**Comment by ProsperCraft** [comment]
Duct_Butter has made the advancement [advancements.techreborn.root]

**Comment by drcrazy** [comment]
Can't reproduce. Both in game and in logs

![image](https://user-images.githubusercontent.com/1382352/98235731-48eb1c80-1f73-11eb-9556-6a0641eac328.png)

![image](https://user-images.githubusercontent.com/1382352/98235797-64eebe00-1f73-11eb-9266-ca20d5b49186.png)
