### ISSUE TITLE
cells are displayed like this

### ISSUE THREAD

**Issue by Miros77** [TechReborn/TechReborn#2273]
![image](https://user-images.githubusercontent.com/59547044/98154902-881f5c00-1ee6-11eb-880a-5cb89582d543.png)

installed Sodium

**Comment by jusvit** [comment]
https://github.com/jellysquid3/sodium-fabric/issues/5

Issue with Sodium not TR, the cell(without textures) were added as a temporary means but the rest is not in our control.

**Comment by Miros77** [comment]
Astromine has no such problems

**Comment by Miros77** [comment]
Astromine uses the models separately
