### ISSUE TITLE
Industrial Centrifuge and Rolling Machine doesn't work and doesn't accept energy

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#228]
![2015-11-03_11 46 41 2](https://cloud.githubusercontent.com/assets/8685029/10906309/b9cf651e-8220-11e5-9442-9ecd234e5584.png)
Also, in the rolling machine the Energy slot isn't clickable
![2015-11-03_11 50 36 2](https://cloud.githubusercontent.com/assets/8685029/10906407/8a9e39d6-8221-11e5-8327-e0aa580091e3.png)

TechReborn-0.5.6.963-universal

**Comment by MrBretze** [comment]
#233

**Comment by modmuss50** [comment]
I fixes this.
