### ISSUE TITLE
Datapacks can't seem to override TR recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2280]
**Describe the bug**
I am trying to make a datapack to make _Tech Reborn_ compatible with _Vanilla Tweaks' More Stairs_ tweak, which doubles the output of all staircase crafting recipes. I rooted around in the mod's jar file to copy the structure of its _data/techreborn/recipes/crafting_table/storage_blocks_ directories, copying them all into the datapack and removing all of the files that weren't the staircase recipes. I them edited them all to change the _count_ argument number from four to eight. This is how _Vanilla Tweaks_ makes its changes to vanilla, and a method I have had success with for mods such as TerraformersMC's _Cinderscapes_ and _Terrestria_.

This did not work: all of the staircase recipes yielded four staircases instead of the datapack's eight. I tried to move the recipes to a different namespace id, which still did not work, as didn't changing the recipes to input or output different, arbitrary items such as dirt. When I replaced _stair_ in all of the recipe names with _stairs_, I was able to get some of the recipes, like aluminium stairs, to work, albeit with two recipes appearing in the recipe book, whilst others, like invar, copper and zinc stairs, did not work at all, and still outputted four staircases. This would imply that _any recipe using the names [metal]_storage_block_stair does not work in any namespace._ I cannot figure out why only some of the recipes work and others do not when they are given different names.

I would like you to take a look at the datapack provided below to see what may be wrong with it, and, if Tech Reborn is doing something to hinder its interpretation of datapacks, I would like to see this fixed. The ideal end goal here is for this datapack to be able to _replace_ the existing staircase recipes, without more than one staircase recipe appearing for each staircase type in the recipe book.

**Steps to Reproduce**
- Download this demo datapack: [tr recipe override demo.zip](https://github.com/TechReborn/TechReborn/files/5505340/tr.recipe.override.demo.zip)
- Place this datapack into the datapacks folder of any save, and boot up the save.
- Attempt to craft any staircase added by Tech Reborn. The recipe outputs four staircases instead of the intended eight. :x: 
- Open the datapack, and move all of the recipes from _data/techreborn/recipes/crafting_table/storage_blocks_ to _data/minecraft/recipes_.
- Run /reload in the save, and try to craft the staircase again. It still outputs four staircases. :x:
- Open the datapack once more, move the recipes back, and rename all of them to their current name with _stairs_ instead of _stair_.
- Run /reload in the save, and try to craft an aluminium staircase. Eight staircases are outputted, but the recipe book now has two aluminium staircase recipes. :x:
- Try to craft a copper staircase. Only four staircases are outputted. :x:

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: Fabric

**Comment by drcrazy** [comment]
Can't reproduce. 

I've changed 3 stairs recipes through datapack:
![image](https://user-images.githubusercontent.com/1382352/99260233-29ce7380-282c-11eb-8922-17de040d6158.png)


Each one with different amount of stairs as output
![image](https://user-images.githubusercontent.com/1382352/99260016-ed9b1300-282b-11eb-86d0-06615f9dc650.png)

![image](https://user-images.githubusercontent.com/1382352/99260051-f7bd1180-282b-11eb-886e-5c7aadfe4d9d.png)

![image](https://user-images.githubusercontent.com/1382352/99260121-06a3c400-282c-11eb-96aa-7c8e5ff11ca1.png)
