### ISSUE TITLE
Machine screens are not closed when broken

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2289]
**Describe the bug**
Machine screens are not closed when broken.

**Steps to Reproduce**
- Place a Generator
- Have one player open it and other player break it. The GUI remains open, and this can void items.

**Comment by modmuss50** [comment]
Fixed: https://github.com/TechReborn/RebornCore/commit/01a21d6f5a06ec19d4897b476ba07fb85c1fe51c
