### ISSUE TITLE
All machines doesn't accept power (EU)

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#229]
From #228 I found that every techreborn machine doesn't accept energy EU.
Releated mods:
TechReborn-0.5.6.963-universal
Uncomplication-1.7.10-0.1.2.1.b55 http://forum.industrial-craft.net/index.php?page=Thread&threadID=11586
industrialcraft-2-2.2.791-experimental
I think is Uncomplication, that add the Classic E-Net to IC2 Exp. I'll try without Uncomplication.

**Comment by Xen1290** [comment]
No, without uncomplication same result.

**Comment by modmuss50** [comment]
Ok, there is something wrong, I think I know what it might be.

**Comment by Xen1290** [comment]
Config file: https://gist.github.com/Xen1290/4d3cb098a5b97eb3811a

**Comment by modmuss50** [comment]
Mind trying with the lastest build on the jenkins?

**Comment by Xen1290** [comment]
Oh, I tried first with build 963(When I've done the report, sorry I forgot to post the result) and only with cables I could power machines. Batteries, ic2 debug item et don't work, and then 966(latest) same result only with cables. Sorry @modmuss50
