### ISSUE TITLE
Game Crashes Immediately As It Launches

### ISSUE THREAD

**Issue by ThatCrispyToast** [TechReborn/TechReborn#2291]
**Describe the bug**
Game Crashes Immediately as Window Launches with "java.lang.NoSuchMethodError"

**Steps to Reproduce**
- Click Play In the Minecraft Launcher with the Mod Installed

**Screenshots**
![image](https://user-images.githubusercontent.com/61917048/99153707-2f835800-2678-11eb-9839-f70cdb65dddb.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: fabric

**Logs**
https://pastebin.com/gcukQ4nG

**Additional context**
Have These Mods Installed
![image](https://user-images.githubusercontent.com/61917048/99153734-838e3c80-2678-11eb-917e-933142dffb18.png)

**Comment by drcrazy** [comment]
Please, update TechReborn to latest release version.
