### ISSUE TITLE
Omni-Tool has durability for some reason.

### ISSUE THREAD

**Issue by Bluberry-Kat** [TechReborn/TechReborn#2295]
**Describe the bug**
The Omni-Tool, somehow, has lost durability. I was under the impression it didn't have any.

**Steps to Reproduce**
I don't actually know how to repro the tool losing durability, but the problem is that it has durability at all, imo.
**Screenshots**
![image](https://user-images.githubusercontent.com/20749209/99836379-00675d80-2b34-11eb-9f1a-54ef9c320f0a.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4 
 - Mod Loader: Fabric Loader 0.10.6+build.214, Fabric API 0.25.4+1.16

**Comment by drcrazy** [comment]
Can't reproduce.


![image](https://user-images.githubusercontent.com/1382352/102788324-81c04300-43b3-11eb-8002-4c3ff3165cb6.png)
