### ISSUE TITLE
Quantum Armor is completely bypassed by Age of Exile damage

### ISSUE THREAD

**Issue by marximpotato** [TechReborn/TechReborn#2298]
Describe the bug:
When Age of Exile is installed with TechReborn, the different types of RPG damage (elemental, fire, water, etc.) are not recognized by the armor as damage, so you take damage like you're not wearing any armor. 

- Install Age of Exile and TechReborn on the same world
- Give yourself quantum armor
- Take damage and realize that the armor is useless

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.3]
 - Mod Loader: [fabric]

**Additional context**
I think the armor just isn't recognizing of Age of Exile damage as damage, and subsequently doesn't lose any energy to protect the user against the damage.

**Comment by drcrazy** [comment]
Can you check with latest RC (RebornCore-1.16-4.7.0+build.126.jar) & TR (TechReborn-1.16-3.8.0+build.205.jar), please?

**Comment by drcrazy** [comment]
No response for a long time.  Feel free to re-open if it is still not applied.
