### ISSUE TITLE
Wrong NEI Handler Recipes hitboxes

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#230]
See this:
![2015-11-03_12 04 15 2](https://cloud.githubusercontent.com/assets/8685029/10906866/51d8d01c-8225-11e5-9c92-991cccdb5e17.png)
![2015-11-02_10 55 18 2](https://cloud.githubusercontent.com/assets/8685029/10906868/54358314-8225-11e5-89b5-b5808f3e5d5b.png)

<strong>Also, only one arrow has the hitbox for open all recipes.<strong>

![2015-11-11_14 43 53 2](https://cloud.githubusercontent.com/assets/8685029/11092326/ca40b2fa-8882-11e5-9ba3-c491f7e828ff.png)
TechReborn-0.5.6.963-universal

**Comment by MrBretze** [comment]
I tested to fix this this week

**Comment by gigabit101** [comment]
The recipe hitbox dose not need to be in NEI guis can we just check for that ?? @modmuss50

**Comment by modmuss50** [comment]
no, and the same happens for the vanilla crafting table

**Comment by modmuss50** [comment]
Not sure what the issue is here then?

**Comment by gigabit101** [comment]
When inside of a recipe handler the recipes button is there

**Comment by Xen1290** [comment]
Exactly, not only in the nei handlers, try to open the machines and try to show all nei recipes how i've done in these screenshot

**Comment by modmuss50** [comment]
I still dont know what is wrong with this? Is it just the place where you have to click is out?

**Comment by gigabit101** [comment]
The recipes button is showing up inside the recipe handler

**Comment by gigabit101** [comment]
and its not in the right place

**Comment by modmuss50** [comment]
It does that in the vanilla crafting table, no way to fix.

**Comment by gigabit101** [comment]
well its overlapping slots

**Comment by modmuss50** [comment]
ok, That should be easy to fix.

**Comment by gigabit101** [comment]
same as #329
