### ISSUE TITLE
Industrial grinder filtering

### ISSUE THREAD

**Issue by requiamer** [TechReborn/TechReborn#2300]
**Describe the bug**
The item filter for cells/buckets on the input side is not working. The me system won't put buckets/cells if the filter option is checked and will just lock any autocrafting. If you don't put the option it will sometime put ores instead of bucket/cells and lock the system (this is a random occurrence). 
**Steps to Reproduce**
-just set up an autocrafting me system with encoded patterns and interface (i didn't check item pipes)

**Screenshots**

**Environment (please complete the following information with the version):**
All of fabric 3 version 2.4.4

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by xanthian** [comment]
1.16.5 no longer maintained.
