### ISSUE TITLE
Hopper under grinder crashes game

### ISSUE THREAD

**Issue by TheChay** [TechReborn/TechReborn#2301]
**Describe the bug**
Hopper under grinder crashes game

**Steps to Reproduce**
- Place grinder
- Place hopper under grinder 

**Screenshots**
https://im2.ezgif.com/tmp/ezgif-2-59077170f608.gif

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.4]
 - Mod Loader: [fabric]

**Logs**
[crash-2020-12-03_23.03.56-server.txt](https://github.com/TechReborn/TechReborn/files/5638786/crash-2020-12-03_23.03.56-server.txt)

**Comment by drcrazy** [comment]
It is exception from LBA. It is of a latest version?

https://github.com/AlexIIL/LibBlockAttributes/blob/a519e0de7cc74e1ffae9b530c289684835e1c66b/src/main/java/alexiil/mc/lib/attributes/CompatLeveledMap.java
