### ISSUE TITLE
Auto crafting table doesn't import items

### ISSUE THREAD

**Issue by AtelierAmber** [TechReborn/TechReborn#2305]
**Describe the bug**
Auto crafting table will not import items from either a chest, or a separate mod like ezpas pushing the items into it

**Steps to Reproduce**
- Set a recipe in the auto crafter
- Set the input to one side
- Place a chest on that side with the items
- Table won't pull in items

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: Fabric

**Comment by drcrazy** [comment]
Can't reproduce. 

Due to same textures on all sides it is always facing north. Easiest way for i/o is to pull or push from top and bottom. If this is not an option then you have to either check where north is or try with input from every side.
