### ISSUE TITLE
Oil lakes is not generated

### ISSUE THREAD

**Issue by roman901** [TechReborn/TechReborn#2307]
I can't find any likes of Oil for a while and looked into source code.

There's no any code, which can be able to gen it

**Comment by jusvit** [comment]
@modmuss50 Do we have oil lakes?

**Comment by drcrazy** [comment]
Not in 1.13+ yet

**Comment by roman901** [comment]
@justinvvitale @drcrazy but how I can get oil right now?

**Comment by hao0606** [comment]
So how can I get oil in 1.16.5

**Comment by xanthian** [comment]
1.16.5 is no longer maintained.
Oil is created from Centrifuging Soul Sand & Soul Soul.

**Comment by Ayutac** [comment]
Would still be a nice feature

**Comment by qqH95** [comment]
@xanthian hi, i have some problems with english, can u explain to me one more time how to get the oil. version 1.20.1
