### ISSUE TITLE
Biofuel and Oil fluids use 32x32 texture when still, and are always flowing

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2309]
**Describe the bug**
Vanilla Minecraft's water and lava use a 16x16 texture for when they are still, that depicts the fluid gently moving in place. Tech Reborn's biofuel and oil use a 32x32 version of their flowing textures when they are still. This does not match the resolution of the rest of the game, and makes these fluids look strange, as they shouldn't be flowing in place.

**Steps to Reproduce**
- Create a new world in Creative mode.
- Obtain and dump out Biofuel or Oil.
- Surround its source block in other blocks so it shouldn't flow. Observe the broken textures.

**Screenshots**
![2020-12-21_20 12 57](https://user-images.githubusercontent.com/69029346/102848157-f94c9d00-43c8-11eb-8e69-6c03a4126fc2.png)
![2020-12-21_20 22 22](https://user-images.githubusercontent.com/69029346/102848701-42e9b780-43ca-11eb-844c-da6cd0c32b21.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: Fabric

**Comment by xanthian** [comment]
Fixed in beta5
