### ISSUE TITLE
Many flowing fluids use 8x8 version of their still textures instead of 16x16 flowing texture

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2310]
**Describe the bug**
Vanilla Minecraft's water and lava have dedicated flowing textures for when they are flowing. Tech Reborn's myriad of fluids appear to use an 8x8 version of their still textures, which not only do not match the resolution of the rest of the game, but also do not visually appear to be flowing downwards.
This applies to ever fluid except for Biofuel and Oil. The full list follows:
- Beryllium
- Calcium
- Calcium Carbonate
- Carbon
- Carbon Fiber
- Chlorite
- Deuterium
- Diesel
- Electrolyzed Water
- Glyceryl
- Helium
- Helium3
- Heliumplasma
- Hydrogen
- Lithium
- Mercury
- Methane
- Nitro Diesel
- Nitrocoal Fuel
- Nitrofuel
- Nitrogen
- Nitrogen Dioxide
- Potassium
- Silicon
- Sodium
- Sodium Sulfide
- Sodium Persulfate
- Sulfur
- Sulfuric Acid
- Tritium
- Wolfranium

**Steps to Reproduce**
- Create a new world in Creative mode.
- Obtain and dump out any of the above fluid buckets. Observe the broken flowing textures.

**Screenshots**
![2020-12-21_19 54 30](https://user-images.githubusercontent.com/69029346/102847854-36645f80-43c8-11eb-81f7-23d8dfac3986.png)
![2020-12-21_19 54 51](https://user-images.githubusercontent.com/69029346/102847855-37958c80-43c8-11eb-8c0d-cf43b0d86cdf.png)
![2020-12-21_20 04 34](https://user-images.githubusercontent.com/69029346/102847857-382e2300-43c8-11eb-9afa-39c257901526.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: Fabric

**Comment by xanthian** [comment]
This is because all flowing textures are 16x (apart from the 2 listed).
I'll work on some 32x ones (probably just resize existing 😜 )

**Comment by xanthian** [comment]
fixed in beta5
