### ISSUE TITLE
Fluid interaction is awkward

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2312]
**Describe the bug**
Tech Reborn's fluids have no blocks that they turn each other into when they collide in the manner of vanilla water and lava, which means that they flow around each other and prevent each other from flowing in ways that are very strange and unappealing to the eye and mind. They also do this with vanilla water and lava.

**Steps to Reproduce**
- Create a new world in Creative mode.
- Pour out various Tech Reborn fluids near each other so that they flow into each other.
- Observe how they flow around each other, treating each other like solid blocks.
- Try pouring a Tech Reborn fluid or vanilla water or lava inside of a block occupied by a flowing Tech Reborn fluid. Note how this new fluid simply won't flow due to believing that it can't.

**Screenshots**
![2020-12-21_20 42 11](https://user-images.githubusercontent.com/69029346/102850149-96113980-43cd-11eb-8b96-09d6cbb4f2bd.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: Fabric

**Comment by drcrazy** [comment]
Fluid interaction is not planned for nearest future. It will have too many combinations and not a clear logic. 
Vanilla has only two fluids which is making interaction much much easier.
