### ISSUE TITLE
TR Fluids don't push entities

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2313]
**Describe the bug**
Tech Reborn's myriad of fluids do not push entities in the same manner as vanilla water and lava.

**Steps to Reproduce**
- Create a new world in Creative mode.
- Pour out any Tech Reborn fluid bucket.
- Drop the bucket into the fluid. It does not move the way it would if the fluid were vanilla water.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: Fabric

**Comment by drcrazy** [comment]
It is an entity who is checking if it is in lava or water. Exactly in lava and exactly in water. Entities do not know any other types of fluids. Making TR fluids a lava or a water will have side effects.
