### ISSUE TITLE
Lamps not correctly powered from above

### ISSUE THREAD

**Issue by Starjumper2821** [TechReborn/TechReborn#2314]
**Describe the bug**
When a lamp connects to a powered cable directly above it, it might briefly flicker but remains off.

**Steps to Reproduce**
- Place or find a cable
- Power the cable with any generator or energy storage
- Place a lamp directly benath the cable

**Screenshots**
![2020-12-23_16 51 45](https://user-images.githubusercontent.com/20238370/103014733-8e71a200-453f-11eb-93a8-123c285924d3.png)
![2020-12-23_16 52 05](https://user-images.githubusercontent.com/20238370/103014739-903b6580-453f-11eb-8c51-2f3a47173840.png)
![2020-12-23_16 52 29](https://user-images.githubusercontent.com/20238370/103014743-90d3fc00-453f-11eb-94fd-663c42a02e6e.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: Fabric Loader 0.10.8
 - Fabric API: 0.28.1+1.16
 - Reborn Core: 4.5.0+build.84
 - Tech Reborn: 3.6.1+build.143

**Logs**
No relevant entries found.

**Comment by drcrazy** [comment]
Can't reproduce on TR 3.7.3. 

![image](https://user-images.githubusercontent.com/1382352/105493358-59857600-5cca-11eb-8e3f-81a9fab8a57e.png)

![image](https://user-images.githubusercontent.com/1382352/105493488-85a0f700-5cca-11eb-98c7-f8d763af0d02.png)
