### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by superon** [TechReborn/TechReborn#2317]
**Describe the bug**
client crash

**Steps to Reproduce**
this happened whilst searching REI, no clue how to reproduce it

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
fabric-api-0.28.4+1.16

**Logs**
https://pastebin.com/cg29tNeB

**Comment by drcrazy** [comment]
Can't reproduce. 

![image](https://user-images.githubusercontent.com/1382352/105628402-b3fb0f80-5e4d-11eb-9506-8483f2c980d0.png)

**Comment by superon** [comment]
riight? in all the time i've been playing this it has happened once and try as i might i've been unable to reproduce.
