### ISSUE TITLE
TR crash with REI

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2319]
**Describe the bug**
When hovering over fluids (probably from other mods, but I'm not sure) the client crashes

**Steps to Reproduce**
- Open REI
- Look up any Fluid replicator recipe
- Hover over with your cursor

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.4]
 - Mod Loader: [fabric 0.10.8]
 - Fabric API [0.29.0]
 - TR [3.7.2]
 - REI [5.8.10]

**Logs**
[Error message](https://pastebin.com/VQ9W1m4B)
**Note**
Looks like a similar issue was reported before but with other recipe types

**Comment by jusvit** [comment]
Same issue as #2318
