### ISSUE TITLE
List of unimplemented features / roadmap

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#232]
Just wondering if you have something like that, to prevent submitting unhelpful issues.

**Comment by modmuss50** [comment]
We have got https://github.com/TechReborn/TechReborn_TODO/issues But is missing some stuff. Feel free to make new issues there.

**Comment by modmuss50** [comment]
I've made a proper web page for this; http://www.techreborn.ninja/home/?page_id=56
