### ISSUE TITLE
Divide by zero error while using compressor

### ISSUE THREAD

**Issue by Chezzik** [TechReborn/TechReborn#2324]
My client crashed while playing All of Fabric 3 (v2.5.7).  It was right after opening my compressor.  My compressor was currently working at turning iron ingots into plates.

The crash log is here: https://paste.ee/p/H5DAL

Iron plates do not take 0 time to process.  So, I don't quite know what happened.

**Comment by jusvit** [comment]
Was probably something delay in syncing between server/client.
