### ISSUE TITLE
Iron Alloy Furnace/Smelter Crashing Game

### ISSUE THREAD

**Issue by Dragonsissiy** [TechReborn/TechReborn#2327]
**Describe the bug**
Calling up a recipe list for ingots smeltable in the alloy smelter or iron alloy furnace, or putting an invalid smelting recipe of any kind into said machines (so both inputs) causes a crash. Pressing U on some of these items can cause the crash as well. 

**Steps to Reproduce**
- Creative or Survival Mode
- Place a TechReborn Iron Alloy Furnace/Smelter 
- Put TechReborn or any other mod's ore in both the input and output slots. With/without fuel the machine.
- AND/OR put TechBorn copper ingots in both the input and output.
- Put anything at all that you think wouldn't have an output in it.
- Once something is placed in the output slot with the input slot filled it crashes.
- This crash makes the world permanently broken and unable to launch.

**Screenshots**

**List of Mods:**
![Current_Mod_list](https://user-images.githubusercontent.com/60621847/105619139-89a14780-5da4-11eb-83dd-fc525d46328f.PNG)

**Before Crash Step 1**
![BeforeCrash1](https://user-images.githubusercontent.com/60621847/105619084-ec461380-5da3-11eb-89c3-19486d82cbc2.PNG)

**Before Crash Step 2**
![BeforeCrash2](https://user-images.githubusercontent.com/60621847/105619088-f831d580-5da3-11eb-82c5-5af272298743.PNG)

**Right Before Crash Step 3**
![BeforeCrash3](https://user-images.githubusercontent.com/60621847/105619095-0aac0f00-5da4-11eb-88cb-c037661cf88e.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: Fabric
 - 41 Mods, will include screenshot.

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

Crash 1
https://pastebin.com/5qjvDaFL

Crash 2
https://pastebin.com/JCZvM0Ac

Crash 3 (when just putting copper ingots both inputs)
https://pastebin.com/S4s6MGKv

**Additional context**
Edited this to be more explanatory and accurate.

**Comment by drcrazy** [comment]
Can't reproduce. Try update TR&RC

![image](https://user-images.githubusercontent.com/1382352/105491105-d7478280-5cc6-11eb-932e-1b91570823b7.png)

**Comment by Dragonsissiy** [comment]
> Can't reproduce. Try update TR&RC
> 
> ![image](https://user-images.githubusercontent.com/1382352/105491105-d7478280-5cc6-11eb-932e-1b91570823b7.png)

Thank you, so far with the updated reborn core I don't seem to be having this issue. The update was added a couple days after I opened this ticket so makes sense why I missed it.

**Comment by Dragonsissiy** [comment]
> Can't reproduce. Try update TR&RC
> 
> ![image](https://user-images.githubusercontent.com/1382352/105491105-d7478280-5cc6-11eb-932e-1b91570823b7.png)

You're using the wrong furnace. Try the **Iron ALLOY Furnace** and it still crashes.

**Comment by Dragonsissiy** [comment]
I edited the original poste to include more descriptive screenshots to demonstrate how it crashes. Also included my updated mods list.

**Comment by drcrazy** [comment]
Same story with Iron ALLOY furnace

Ores with fuel
![image](https://user-images.githubusercontent.com/1382352/105627569-c0c93480-5e48-11eb-9dd8-cb54ac5e79a0.png)

Ores without fuel
![image](https://user-images.githubusercontent.com/1382352/105627580-cfafe700-5e48-11eb-8d31-fe11ccf1425a.png)


Ingots without fuel
![image](https://user-images.githubusercontent.com/1382352/105627595-dd656c80-5e48-11eb-8ccb-20c05245afc6.png)


Ingots with fuel
![image](https://user-images.githubusercontent.com/1382352/105627617-ef470f80-5e48-11eb-962d-6189162c55c6.png)

**Comment by drcrazy** [comment]
Can you try with fabric and TR&RC only?

**Comment by Dragonsissiy** [comment]
Figured it out. When I downloaded mythic metals, it downloaded the beta version 0.9.9 instead of the 0.9.8 version. With the 0.9.8 version everything behaves. I'll let them know. Thanks for the help!
