### ISSUE TITLE
[STARTUP CRASH] A triple crash has happened at the initializing stage.

### ISSUE THREAD

**Issue by doctor-something5000** [TechReborn/TechReborn#2328]
**Describe the bug**
The error "Initializing game, java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'techreborn'!" happens on reaching the Mojang loading screen then 3 crashes happen simultaneously.

**Steps to Reproduce**
- Have Tech Reborn
- Start Minecraft

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: Fabric

**Logs**
[Crash 1, 2 and 3](https://gist.github.com/doctor-something5000/aaa646e86458f9350d7c6ac856b0ea7e)

**Additional context**
JVM: GraalVM v20.0.3

**Comment by TheRealM18** [comment]
I believe that you are missing the core mod, as the "main" argument normally means you are missing something.... in this case, are you leading reborncore too.

**Comment by doctor-something5000** [comment]
Yes reborncore itself is already there in my mods folder.

**Comment by doctor-something5000** [comment]
This error also happens:"java.lang.NoClassDefFoundError: Could not initialize class techreborn.init.TRContent$Machine".

**Comment by doctor-something5000** [comment]
It seems that the error was caused by REI because ever since I've installed the recent version of REI this error has been fixed.
