### ISSUE TITLE
Other mod's tools stronger than Netherite should be able to break ores

### ISSUE THREAD

**Issue by ZenoMetal** [TechReborn/TechReborn#2329]
**Is your feature request related to a problem? Please describe.**
I am playing with Oh the biomes you'll go and the pickackes break Tech Reborns ores without dropping them, even though they are stronger than netherite.

**Describe alternatives you've considered**
A config file to manually add tools you want to be able to gather ores would be great, you could add the item id like byg:pendorite_pickaxe for example.

**Comment by Technici4n** [comment]
I believe this is a BYG issue, not a TR issue.
