### ISSUE TITLE
Divide by Zero Exception when moving item into machine

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2331]
**Describe the bug**
My friends and I have an AOF3 server, and one of their games crashed when she moved an item stack into a solid canning machine.

**Steps to Reproduce**
- move an item into a canning machine? idk..

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
[https://pastebin.com/Led0sDy2](https://pastebin.com/Led0sDy2)

**Comment by echoofskyz** [comment]
Got whats probably the same crash, 
[crash-2021-01-27_08.21.46-client.txt](https://github.com/TechReborn/TechReborn/files/5880802/crash-2021-01-27_08.21.46-client.txt)

**Comment by drcrazy** [comment]
Already fixed by https://github.com/TechReborn/TechReborn/commit/ea0db38b6aaa5a537f65d4d6cd6219228b178580
