### ISSUE TITLE
Auto Crafting Table cant lock recipe

### ISSUE THREAD

**Issue by Gamke92** [TechReborn/TechReborn#2332]
**Describe the bug**
Auto crafting Table wont lock the recipes

**Steps to Reproduce**
- chest next to Auto crafting Table
- put 2 planks in auto crafting table to craft sticks
- klick on the lock to "lock" the recipe
- set input for 2 slots in crafting grid to import from "plank" chest
- put 3 planks in chest
- table crafts 1x sticks
- 1 wood plank left
- table crafts wood button

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: Fabric
 - TechReborn: v3.7.3+build.192

**Comment by srnyx** [comment]
Please fix this it's breaking my farm

**Comment by srnyx** [comment]
Is there any plan to fix (or ETA on a fix) this cause no one has mentioned anything yet...

**Comment by drcrazy** [comment]
Yepp, auto crafting table need some luv.

**Comment by jusvit** [comment]
Semi-fixed in https://github.com/TechReborn/TechReborn/commit/48217d0327dae7a911d9b4a7e61731925f0e394b

When a crafting table is locked, it won't craft if any stack sizes are one and thus preserves the recipe.

**Comment by srnyx** [comment]
> Semi-fixed in [48217d0](https://github.com/TechReborn/TechReborn/commit/48217d0327dae7a911d9b4a7e61731925f0e394b)
> 
> When a crafting table is locked, it won't craft if any stack sizes are one and thus preserves the recipe.

THANK YOU! :D
