### ISSUE TITLE
Add support for 1.8.9 Legacy-Fabric

### ISSUE THREAD

**Issue by Flamarine** [TechReborn/TechReborn#2334]
**Is your feature request related to a problem? Please describe.**
No, I think.

**Describe the solution you'd like**
The example mod for Legacy-Fabric seems similar to the example mod for the current Fabric version.

**Comment by modmuss50** [comment]
I can offer you the 1.8.9 forge branch from 5 years ago: https://github.com/TechReborn/TechReborn/tree/1.8.9

I dont think this is something we are going to do officialy as its 100s of hours of work. Feel free to do it yourself. (Id recomend taking the 1.16 branch if you do)
