### ISSUE TITLE
Rubber Saplings causing crashes and not growing into trees when they don't.

### ISSUE THREAD

**Issue by buildershedd** [TechReborn/TechReborn#2335]
**Describe the bug**
Rubber Saplings causing crashes and not growing into trees when they don't.

**Steps to Reproduce**
Place several rubber saplings and let them grow(or use bone meal).
**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.5]
 - Mod Loader: [fabric]
 - OS: Linux - Ubuntu 20.04 LTS Focal(POP OS derivative)

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

[https://pastebin.com/w3hQP9yX](https://pastebin.com/w3hQP9yX)

**Additional context**
Terrestria is also being used but from the logs, it doesn't look like terrestria is the issue despite rubber also being implemented by the mod too.

**Comment by drcrazy** [comment]
Outdated RC&TR back from November.
