### ISSUE TITLE
Incorrect charge percentage on items, tools, and armor

### ISSUE THREAD

**Issue by DragonGodGrapha** [TechReborn/TechReborn#2336]
**Describe the bug**
The listed charge percentage on chargeable items is incorrect.
Examples:
32.3M/40M, 123% Charged
21.3M/40M, 186% Charged
0M/10M, 2147483647% Charged

**Steps to Reproduce**
Shift over any energy item without full charge to show charge percentage

**Environment**
 - Minecraft: 1.16.4 
 - Mod Loader: Fabric 0.11.1
 -  TechReborn: 1.16-3.7.3+build.192

**Comment by drcrazy** [comment]
Closed by https://github.com/TechReborn/RebornCore/commit/7cb89398235ce3133589afc10005837b63913524
