### ISSUE TITLE
Astromine compat with KubeJS go boom

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2337]
**Describe the bug**
TR screams about Astro compat when the mod is not present. Astromine is discontinued FYI.

**Steps to Reproduce**
Run TR with KubeJS & Rhino installed.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric Loader (0.11.1)

**Logs**
https://gist.github.com/ImAK9/e05b45fd5947624f7d33cdf78d928ff2

**Comment by ImAK9** [comment]
https://gist.githubusercontent.com/ImAK9/8a4a1387d9420cf65c48a98f010f0394/raw/1c0f1e4762daf506d26263d9eedae33f32180d70/gistfile1.txt

**Comment by drcrazy** [comment]
Astromine recipe are conditionally loaded by RC. It looks like KubeJS tries to load recipes anyway. TR&RC has no control on how KubeJS load or skip recipes.
