### ISSUE TITLE
The List of Bug's

### ISSUE THREAD

**Issue by DerMistkaefer** [TechReborn/TechReborn#234]
We have some bug's with your mod.

1. No Recipe for Item "Basic Circuit Board"
2. I can no crafting for example the "Lapatrconic Energy Orb" because the MetaData from the "Lapotron Crystal".
3. Ther is no OreDirectonary for "Iridium Ingot" and "Diamond Dust"
4. Option "Enable machine explosions when rain hits" leaves machine explosions when is rain and not when rain hit the machine.
5. When Option "Enable Connected textures" is active I don't can use a texturepack.
6. When I place a "Generator" next to the "Blast Furnace" or "Grinder" you have infinitely energy. When the buffer of the Generator is full. 

I have use 
industrialcraft-2-2.2.791-experimental
TechReborn-0.5.6.967-universal

I hope I can help you.

**Comment by modmuss50** [comment]
1. I know
2. Thanks
3. Thanks
4. Im gonna remove the explosions
5. I fixed, but will fix again. (Can I have logs when you try to apply texture pack?)
6. Whaaat?

**Comment by DerMistkaefer** [comment]
5. Oh you have fix this. I don't test in this version.
6. 
Structure:
![2015-11-06_20 27 07](https://cloud.githubusercontent.com/assets/15692249/11006607/de4f8c06-84c4-11e5-90e3-58780653c54a.png)

The Generator has Full Buffer and the Blast Furnace are working, but the Energy of the Generator are not loss. The same work with BatBox, MFE and MFSU when theres buffer is full. If the bufffer of the mfe mfsu are not 100% full he take energy.
![2015-11-06_20 27 18](https://cloud.githubusercontent.com/assets/15692249/11006628/fbe8de02-84c4-11e5-9da6-84989f5b069d.png)
![2015-11-06_20 27 29](https://cloud.githubusercontent.com/assets/15692249/11006644/13b065a0-84c5-11e5-94af-7dcb1e7993ed.png)

**Comment by modmuss50** [comment]
5. is working because you have a texture pack. :)
6. Thanks for showing me a way to reproduce this.

**Comment by DerMistkaefer** [comment]
Yes i say "5.. Oh you have fix this. I don't test in this version."

**Comment by modmuss50** [comment]
All are fixed
