### ISSUE TITLE
Fix bug with solar panels

### ISSUE THREAD

**Issue by AlgorithmLX** [TechReborn/TechReborn#2340]
hello playing with TechReborn 1.16.4 / 5 by creating a solar panel it generates energy even when the panel is full.  Screenshots below
Mod loader: Fabric
Version: 1.16.4/5

**Comment by IgroGames2227** [comment]
[Imgur](https://imgur.com/54htAzF)

**Comment by IgroGames2227** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="54htAzF"><a href="https://imgur.com/54htAzF">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by IgroGames2227** [comment]
https://imgur.com/54htAzF

**Comment by AlgorithmLX** [comment]
https://imgur.com/54htAzF

**Comment by drcrazy** [comment]
Should be already fixed by https://github.com/TechReborn/TechReborn/pull/2339
