### ISSUE TITLE
snapshots / 1.17 port

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2341]
This is less an issue and more an FYI that I'm working on porting RebornCore and TechReborn to 21w06a.
If you create an 1.17 branch I will open a work in progress pull request and we can discuss things there.

**Comment by modmuss50** [comment]
Done. 

This is something I was going to hold back on till the pre-releases as I dont have the time or energy to handle updating it each week to new snapshots. I have some larger changes that id like to get in before 1.17 is released so having the branches around isnt a bad idea.
