### ISSUE TITLE
All recipes using filled cells are broken

### ISSUE THREAD

**Issue by justastranger** [TechReborn/TechReborn#2344]
**Describe the bug**
Due to the lack of vanilla nbt crafting support (I don't know if this is a fabric-only limitation or not), pretty much every recipe in TR that requires a filled cell is broken, allowing any cell to be used.

**Steps to Reproduce**
 - look up recipes involving filled cells
 - attempt to craft them with empty cells or cells filled with other fluids

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: N/A

**Additional context**
You can integrate the NBT Crafting mod in order to solve this issue.

**Comment by drcrazy** [comment]
We do not have filled cells in vanilla crafting recipes. Only buckets. 

![image](https://user-images.githubusercontent.com/1382352/114390725-497d8400-9b9f-11eb-9b99-e1cd626ac459.png)



As for TR machines they are fine with NBT in cells.
