### ISSUE TITLE
Blast Furnace dosent form even though it's complete

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2345]
**Describe the bug**
Blast Furnace dosent form even tho it's fully complete.

**Steps to Reproduce**
- Honestly just grab AOF3 2.6.3 and update TR and RebornCore to latest.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: Fabric

**Comment by stods121** [comment]
Same thing happens to me :(

**Comment by drcrazy** [comment]
Fixed by https://github.com/TechReborn/RebornCore/commit/c9b8cb3601f94f7c445d070ad3adde4c292ef598
