### ISSUE TITLE
KubeJS compat breaks all Alloy Smelter recipes & more

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2347]
**Describe the bug**
With current KubeJS compat you cant make ANYTHING in the Alloy Smelter, you basically cant progress in TR at all.. On top of that you cant make the Lithium Battery or Energy Crystal due to this same bug.

**Steps to Reproduce**
- Install KubeJS.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
https://gist.github.com/ImAK9/16d7a5eff6d929def04ca5a6fd8d2c8f
^ All breaking recipes, also with the Astromine breaking recipes.

**Comment by ImAK9** [comment]
Should probably be on Reborn Core tracker but w/e...

**Comment by drcrazy** [comment]
KubeJS issue. Already fixed by KubeJS.
