### ISSUE TITLE
http://paste.ee/p/s7kK3 Crash with NEI

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#235]
http://paste.ee/p/s7kK3

Null items again, caused when loaded with IC2 classic. I think it's GT reborn side.

**Comment by gigabit101** [comment]
cant reproduce

**Comment by modmuss50** [comment]
The method that is crashing nei is not used by us. If it is us im not fixing it.

**Comment by Carbon-Ghost** [comment]
kk wasn't sure ^-^
