### ISSUE TITLE
The drills crash the game when mining anything other than stone/ores

### ISSUE THREAD

**Issue by altered-dev** [TechReborn/TechReborn#2350]
**Describe the bug**
I crafted a drill, tried to mine dirt and the game crashed

**Steps to Reproduce**
- Use the drill to mine dirt or anything else

**Screenshots**
none

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
https://pastebin.com/yvJLz9ym

**Additional context**
I am playing on a server and everyone else is having the same issue.

**Comment by Technici4n** [comment]
This log is not available, is it private?

**Comment by altered-dev** [comment]
> This log is not available, is it private?

Whoops, seems like guest pastes don't last for long. Updated the link

**Comment by altered-dev** [comment]
BTW, the issue doesn't seem to be true with the chainsaw, it works okay.

**Comment by WiIIiam278** [comment]
Also experiencing this issue, game crashes immediately when mouse button pressed when mining anything other than stone / ores. Server does not crash but throws error too. I'll throw in my logs too.

* [Game](https://pastebin.com/wuhgtCTw)
* [Server](https://pastebin.com/mg1ACQFC)

**Comment by drcrazy** [comment]
Duplicate for #2348 
Issue is in Origins: Classes
