### ISSUE TITLE
tech reborn blast furnace multiblock error

### ISSUE THREAD

**Issue by yunus-star** [TechReborn/TechReborn#2351]
blast furnace multiblock wont work how many times i do it i watched videos read guides nothing works i tried rotating it i tried doing it in 1 chunk only i tried different dimensions i tried different tiers of casings i tried with lava and with air but none of them worked.

-make a 3x3 machine casing behind a blast furnace and add a another 3x3 on top of it but with a hole in the middle with lava and another 3x3 with a hole and with lava and make a final 3x3 and give it energy.TLDR:just build the multiblock.
-try to start the machine

 - Minecraft:1.16.5
 - Mod Loader: fabric

**Comment by yunus-star** [comment]
oh and i am sure i am doing the machine right

**Comment by drcrazy** [comment]
This one is fixed in latest RebornCore: https://github.com/TechReborn/RebornCore/commit/c9b8cb3601f94f7c445d070ad3adde4c292ef598
