### ISSUE TITLE
Hoppers done work 

### ISSUE THREAD

**Issue by NishTheFishh** [TechReborn/TechReborn#2354]
Hoppers don’t work with iron furnaces or any machine for that matter in latest version 1.16.5 fabric mod loader 
Hoppers on top or connected to the side of iron furnace do not enter any ores from the hopper into the furnace

**Comment by drcrazy** [comment]
Do you have slot i\o configured?

Can't reproduce with proper slot configuration.
![image](https://user-images.githubusercontent.com/1382352/109536144-6d44a900-7ace-11eb-8ebf-42dab395a38a.png)
