### ISSUE TITLE
Switch energy API

### ISSUE THREAD

**Issue by Starjumper2821** [TechReborn/TechReborn#2355]
This is related to fabric

**Is your feature request related to a problem? Please describe.**
Industrial Revolution changed its API for energy handling. This broke interaction between TR cables and energy producers and IR machines. The author stated the new one was better and could handle more.

**Describe the solution you'd like**
Please consider also using FastTransferLib (it may become part of fabric itself according to the readme)
https://github.com/Technici4n/FastTransferLib

**Comment by Technici4n** [comment]
Hello, author of FTL here, I hope to PR a new `v1` improved API into TR energy once FabricMC/Fabric#1234 is merged, but that will require discussing which features exactly are necessary and how they should be added (simulation vs transaction comes to mind).

Do note that the energy part of FTL is specifically not considered for inclusion into fabric API.

**Comment by Technici4n** [comment]
In the meanwhile you can use IR cables, they will work just fine with TR machines and cables.

**Comment by drcrazy** [comment]
Pr merged, issue should be fixed. Feel free to reopen if it persist
