### ISSUE TITLE
Crashes on game startup

### ISSUE THREAD

**Issue by Zachs-Kappler** [TechReborn/TechReborn#2356]
**Describe the bug**
Adding TechReborn causes Minecraft to crash during startup. Error log states it has something to do with com.google.gson and JSON syntax errors.

**Steps to Reproduce**
- Install Minecraft Launcher.
- Setup profile for Vanilla 1.16.5.
- Install FabricMC using said 1.16.5 profile.
- Add FabricAPI, RebornCore, and TechReborn to mods folder.
- Start Minecraft from launcher with the Fabric Profile.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric
 - Java: OpenJDK 11.0.10
 - OS: elementaryOS "Hera" 5.1.4

**Logs**
https://pastebin.com/UGjHccvA

**Additional context**
I'm guessing this is an issue either with running TechReborn on Linux, OpenJDK/JRE 11, or is something silly like case-sensitivity that gets hand-waved on Windows. I even tried nuking my settings for Minecraft in case that could be the cause, but no dice.

**Comment by modmuss50** [comment]
Looks like one of your config files are corrupt

**Comment by Zachs-Kappler** [comment]
Ah, I should have thought of that since those use JSON now too. Deleting the TechReborn configs has fixed the issue.
