### ISSUE TITLE
Rubber Trees crash Minecraft when they grow from saplings

### ISSUE THREAD

**Issue by Zachs-Kappler** [TechReborn/TechReborn#2357]
**Describe the bug**
Growing Rubber Tree Saplings causes a crash.

**Steps to Reproduce**
- Plant a Rubber Tree sapling in a valid location it can grow.
- Wait for it to grow, because Bonemeal doesn't seem to work.
- The game will crash before the tree is generated, and reloading the world shows no tree was grown and is still a sapling.

**Environment (please complete the following information with the version):**
- Minecraft: 1.16.5
- ModLoader: Fabric
- RebornCore: 4.7.2 build 132
- TechReborn: 3.8.1 build 211
- OS: elementaryOS "Hera" 5.1.4
- Java: OpenJDK 11.0.10

**Logs**
https://pastebin.com/pj7brxiS

**Additional context**
I also haven't found any rubber trees as part of the worldgen. Either I'm unlucky or this issue is affecting them too.

**Comment by drcrazy** [comment]
Can you try with RC& TR only, please?

I can't reproduce this in dev env.
Just got this one from sapling. 

![image](https://user-images.githubusercontent.com/1382352/109536528-e0e6b600-7ace-11eb-8b1e-cb33e955df8c.png)

**Comment by Zachs-Kappler** [comment]
Tried removing everything but TechReborn and its dependencies, and rubber trees work as expected. I narrowed the issue down to [Snowy Leaves](https://github.com/Ashley1227/snowy-leaves), which is weird that the error log doesn't mention it at all.
