### ISSUE TITLE
TR cables don't visually connect to Astromine cables when the latter does

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2358]
**Describe the bug**
Tech Reborn cables do not visually connect to adjacent Astromine cables. Astromine cables do try to visually connect to Tech Reborn cables. This visual bug does not affect sending power through the line, despite the lines not being visually connected.

**Steps to Reproduce**
- Create a new world in Creative mode with Tech Reborn, Reborn Core, Fabric API and Astromine loaded.
- Place any Tech Reborn cable next to any Astromine cable. The Astromine cable changes shape to try to connect; the Tech Reborn cable does not.

**Screenshots**
![2021-02-28_00 47 31](https://user-images.githubusercontent.com/69029346/109412939-bb876a00-795f-11eb-8691-7652e2530f9a.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.1.6.5
 - Mod Loader: Fabric

**Comment by ghost** [comment]
I don't think TR should support a discontinued mod

**Comment by drcrazy** [comment]
TR cable connects to whatever block entity with condition that this entity either TR's own CableBlockEntity or supports Energy API. No other specific cases considered.
