### ISSUE TITLE
Thermal generator Needs tweaking to fit old Gtech style http://puu.sh/lrjy6/afd66db33b.jpg

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#236]
Doesn't have the time to check other cell consumers yet :P

**Comment by gigabit101** [comment]
Nope it is not a issue no other machine eg: forestry engines return the cells.

**Comment by wormzjl** [comment]
But the gt machines are known for not comsuming cells

**Comment by gigabit101** [comment]
well shit you are right http://puu.sh/lrjy6/afd66db33b.jpg
