### ISSUE TITLE
Shift+Clicking items out of TechReborn inventories doesn't merge them with existing stacks

### ISSUE THREAD

**Issue by The-Fireplace** [TechReborn/TechReborn#2365]
**Describe the bug**
When you have a partial stack of an item in your inventory and a partial stack in a TechReborn inventory, shift+clicking the item out of the Tech Reborn inventory doesn't merge it with the stack in the player's inventory. This is different from the vanilla container behavior, which merges the stacks.

**Steps to Reproduce**
- Have a partial stack of an item in your inventory
- Have a Tech Reborn inventory with a partial stack of the same item
- Shift+click the stack in the Tech Reborn inventory to withdraw it

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric
 - Tech Reborn: v3.8.1+build.211
 - Reborn Core: v4.7.2+build.132

**Logs**
https://paste.ubuntu.com/p/GdHgqVXnTC/

**Comment by Ayutac** [comment]
Still exists in Minecraft: 1.17, Fabric Loader 0.11.6, Fabric API 0.36.0, TR 5.0.3-beta+build.55

**Comment by xanthian** [comment]
Still present in 1.18.1 beta 5.
They do merge with items on your hotbar just not in your bag.
