### ISSUE TITLE
Can't cover cables with painting tool

### ISSUE THREAD

**Issue by Dararess** [TechReborn/TechReborn#2366]
**Describe the bug**
I don't know if its a bug or i don't know how it works or it is not yet added but you can't cover cables using painting tool. 

**Steps to Reproduce**
- shift right click any block with painting tool
- right click with painting tool on cable.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric loader 0.11.2 + fabric api 0.31.0
 - RebornCore 1.16 4.7.2 b:132
 - TechReborn 1.16 3.8.1 b:211

**Comment by drcrazy** [comment]
Painting tool paints wooden plate. Wooden plate covers cable.

**Comment by Somnioblivio** [comment]
Can you add this factoid to the Wiki please? 

Even better, add info to the the in-game tool tip to explain the use of wooden plates as cable covers. I incorrectly thought that the "covered" cables were the insulated versions... it seemed like an intuitive leap, but alas this was not the case... This overall experience was confusing to me for a while and i have to imagine that many others are frustrated or just assuming that the paintbrush is currently functionless.

thanks for the great mod! <3
