### ISSUE TITLE
Support for direct liquid input in electrolyzer

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#237]
i.e. directly electrolyzing water

**Comment by Speiger** [comment]
@modmuss50 do you have electrolyzed fluid?

**Comment by modmuss50** [comment]
CC @gigabit101

**Comment by gigabit101** [comment]
Yup this is supposed to be a thing

**Comment by gigabit101** [comment]
This needs to be done for making some of the cells for the fusion reactor
