### ISSUE TITLE
When charging mining tool, it is unuseble 

### ISSUE THREAD

**Issue by mlunax** [TechReborn/TechReborn#2370]
**Describe the bug**
When digging tool is charging, this is nearly unusuble because he changes.

**Steps to Reproduce**
- Any enabled battery or batpack in inventory
- Any diging tool from TechReborn
- Try to dig when tool blinks while NTB changes (charging)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Additional context**
I think the problem is in NTB and Minecraft behaviour when it changes.
But IC2 and other Forge mods fixed it.

**Comment by drcrazy** [comment]
Duplicate for #2232
