### ISSUE TITLE
Auto Crafting Table causes server lag

### ISSUE THREAD

**Issue by srnyx** [TechReborn/TechReborn#2379]
**Describe the bug**
The Auto Crafting Table is causing my server to lag

**Environment:**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
https://spark.lucko.me/fl8LzvercH

**Additional context**
![image](https://user-images.githubusercontent.com/25808801/115307823-c8dafc80-a137-11eb-864d-00470989e933.png)
![image](https://user-images.githubusercontent.com/25808801/115308033-2111fe80-a138-11eb-8381-8e68e99dee42.png)

**Comment by jusvit** [comment]
Recipe manager will no longer perform lookups each tick unless the inventory layout is changed (Items not counts) and instead buffers it.
