### ISSUE TITLE
[Bug report] My games crash to use inventory

### ISSUE THREAD

**Issue by minsto** [TechReborn/TechReborn#238]
Hello i try how mod TechReborn-0.5.6.963-universal today

some time to open my inventory for NotEnoughItems or neil or nothing this my games
or neil this my games is automatic.

crash and close minecraft games.?

please fix hit

Thank you very much :)

**Comment by covers1624** [comment]
Log?

**Comment by modmuss50** [comment]
There not a lot for us to go by? A log, or at least a way to reproduce this.

**Comment by Carbon-Ghost** [comment]
Are you using IC2 classic ?

**Comment by modmuss50** [comment]
It might be that null item...

**Comment by Carbon-Ghost** [comment]
And I think that is what is crashing the last thing, I think NEI doesn't know how to handle that... May you check what is causing that null item ? ( perhaps an item that doesn't load due to IC2exp missing ? ), that would solve a lot of problems.

**Comment by Carbon-Ghost** [comment]
Because I am kinda paused in my modpack making due to constantly crashing when I look up items recipes or go in creative :/

**Comment by modmuss50** [comment]
Im running with IC2-Classic, NEI and TR + RC and im not crashing

**Comment by Carbon-Ghost** [comment]
Latest versions ?

**Comment by modmuss50** [comment]
yes, It could be another mod on top of that.

**Comment by Carbon-Ghost** [comment]
Mmh lemme retry, one sec.

**Comment by modmuss50** [comment]
I can add a check for null items in the techreborn machine crafting?

**Comment by Carbon-Ghost** [comment]
Try that, I am gonna send you the modpack I am using for testing both IC2 classic and GT reborn...

**Comment by Carbon-Ghost** [comment]
ignore MT, script isn't finished yet

**Comment by modmuss50** [comment]
Mind testing with latest commit?

**Comment by Carbon-Ghost** [comment]
kk

**Comment by modmuss50** [comment]
I hope it will crash before you even get to the main menu.

**Comment by Carbon-Ghost** [comment]
well yeah, well not exatcly, it tells me I am missing Reborn core... wut ? and it took forever to load.

**Comment by modmuss50** [comment]
Reborn core is our new core mod, find it on the Jenkins. And yes it may slow down loading times

**Comment by Carbon-Ghost** [comment]
kk

**Comment by Carbon-Ghost** [comment]
Can't find it xD Also sorry back.

**Comment by Carbon-Ghost** [comment]
nvm

**Comment by Carbon-Ghost** [comment]
http://paste.ee/p/M7LE0 what about this time ?

**Comment by modmuss50** [comment]
ok, thats narrowed it down, the null item has been added as a furance recipe

**Comment by modmuss50** [comment]
https://github.com/Chicken-Bones/NotEnoughItems/blob/03ab33075d34f3c394b10df0d7834ce12da68e1b/src/codechicken/nei/recipe/FurnaceRecipeHandler.java#L148

The issue is its trying to get a Block from from an item that isn't an item.

**Comment by modmuss50** [comment]
Its a bug with NEI.

**Comment by Carbon-Ghost** [comment]
So there it's not the items thingies that are causing this ? Then what do I need to do to fix it then ? Because you said you tested with NEI and it didn't crash ...

**Comment by modmuss50** [comment]
I will see what I can do.

**Comment by Carbon-Ghost** [comment]
Thanks Modmuss :) ^-^

**Comment by modmuss50** [comment]
I had a quick look around the nei issue tracker, there are a lot of bugs relating to things like this. And most of them are untouched. And it doesn't look actively maintained. Especially on 1.7.

**Comment by Carbon-Ghost** [comment]
yeah saw that... Same goes for Endertanks which have been bugged for a while, and no recommended versions fixes it..

**Comment by gigabit101** [comment]
The non recommended version fix that carbon

**Comment by modmuss50** [comment]
Ive made a core mod that should fix that issue, http://modmuss50.me:8080/job/NotEnoughFixes/ Is hard to make a mod to fix crashes when I carn't test it. If you have any more NEI crashes please make an issue here: https://github.com/modmuss50/NotEnoughFixes/issues

**Comment by Carbon-Ghost** [comment]
kk thx

**Comment by modmuss50** [comment]
@Carbon-Ghost You gonna like this, https://gist.github.com/modmuss50/a6d62fdc56ca348da4bd

It crashes when an item is created with a null item :)

**Comment by modmuss50** [comment]
Mind running you pack with: http://modmuss50.me:8080/job/NotEnoughFixes/lastSuccessfulBuild/artifact/build/libs/NotEnoughFixes-1.2.0.2-universal.jar

**Comment by Carbon-Ghost** [comment]
Small problem, I am not at home so I don't have my computer with the pack xD
Gonna try it once I get there, well unless... brb..

**Comment by modmuss50** [comment]
Also, don't distribute this in the pack because its a mod designed to crash :)

**Comment by Carbon-Ghost** [comment]
lol

**Comment by Carbon-Ghost** [comment]
Ok, back from IRL stuff, I can't dl the NEF mod...

**Comment by Carbon-Ghost** [comment]
nvm, gonna test, NOW

**Comment by modmuss50** [comment]
:)

**Comment by modmuss50** [comment]
Im hoping you get a crash, or it fixes the nei one, Im working on a config setting for the crash with null stack so you will be able to include the nei fix in a pack.

**Comment by Carbon-Ghost** [comment]
thx :D

**Comment by Carbon-Ghost** [comment]
My pack is going to ROCK, like tekkit legends, but even better... Especially since I feel that small AE successor mod is going to have quite some success :D

**Comment by Carbon-Ghost** [comment]
wtf getting a random memory leap crash...

**Comment by Carbon-Ghost** [comment]
is that you ?

**Comment by modmuss50** [comment]
huh, should be, try without...

**Comment by Carbon-Ghost** [comment]
wait this time launching

**Comment by Carbon-Ghost** [comment]
Ok, for some reasons didn't crash on Startup... but again with NEI http://paste.ee/p/a5XHa

**Comment by Carbon-Ghost** [comment]
Maybe if we can't fix that, we can try to go back with a classic exclusive version ? There was no problems before at least :/

**Comment by modmuss50** [comment]
@Carbon-Ghost do you mind coming on IRC as I feel like we are spamming the github a bit?

**Comment by Carbon-Ghost** [comment]
link ? And I haven't used irc for a while :/

**Comment by modmuss50** [comment]
Ah, don't matter. Try with the newest version on the Jenkins, I've added some more checks

**Comment by Carbon-Ghost** [comment]
gonna try tomorrow. have to go, well gn8 ;)
