### ISSUE TITLE
Hoppers don’t work with tech reborn Grinders or any machine 

### ISSUE THREAD

**Issue by NishTheFishhh** [TechReborn/TechReborn#2384]
Placed hoppers above and below grinders with chest linking with the hoppers. Placed a grindable ore like iron and into chest and it stopped after reaching the hopper. Grinder is powered but doesn’t accept the ore. 
using latest version of tech reborn to date 4/921 along with up to date reborn core 1.16.5 version. Using fabric mod loader along with few other mods but none that should interfere with the mechanics of tech reborn

**Comment by supsm** [comment]
You need to configure the input/output sides in the grinder. Right click on the grinder, click on the wrench on the left, and select which face should be input/output

**Comment by drcrazy** [comment]
Can't reproduce in dev env. Probably you haven't configured input side, as per previous comment.

![image](https://user-images.githubusercontent.com/1382352/114390109-8006cf00-9b9e-11eb-8a21-116345e6268f.png)
