### ISSUE TITLE
Scrap box Details

### ISSUE THREAD

**Issue by GamerLogic** [TechReborn/TechReborn#2387]
When viewing the scrap box in REI I was trying to find what didn't come out of it things like Ender Dragon Egg and Wither stars is there a way to make that and is there a list of what stuff dont come out?

**Comment by drcrazy** [comment]
This is what's in: https://github.com/TechReborn/TechReborn/tree/1.16/src/main/resources/data/techreborn/recipes/scrapbox/auto

Everything else, including modded items are out by default. Modpack authors can change it though.
