### ISSUE TITLE
Fluid tank for industrial grinder will not pull a different liquid when tank is empty.

### ISSUE THREAD

**Issue by xevira** [TechReborn/TechReborn#2388]
**Describe the bug**
I was processing ore with a tank holding water above with the grinder set to pull in liquids.  While I was in the middle of refilling the tank with water, I decided to process the iridium ore I mined, which takes mercury to grind.  Upon placing the now filled tank back where it normally sits, the grinder would not pull in any water despite the internal tank being empty.  It is not taking into account the tank is empty, even when the last liquid in the tank was not water.  It requires that I prime the tank by placing a water cell in the input slot for the grinder to replace the fluid with being water instead of mercury, again despite the tank being empty.

**Steps to Reproduce**
- Place one bucket of liquid 1 to process ore 1
- Place filled tank of liquid 2 next to grinder (in my case, on top)
- Make sure grinder is set to pull in liquids.
- Make sure tank is set to output on correct side (in my case, on the bottom side)
- Notice nothing happening until you prime the tank again with a cell or bucket containing liquid 2.

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric 0.11.3

**Logs**
N/A

**Additional context**
N/A

**Comment by drcrazy** [comment]
What TR version do you use? I think this one was fixed in 3.6.0

**Comment by Technici4n** [comment]
Looking at the code it should be fixed. Please reopen if this is still happening in the latest 1.17 TR versions.
