### ISSUE TITLE
Crash on game startup (1.16.3 and 1.16.4)

### ISSUE THREAD

**Issue by TwoOxMon** [TechReborn/TechReborn#2395]
**Describe the bug**
Adding TechReborn causes Minecraft to crash during startup.

**Steps to Reproduce**
- Install MultiMC
- Setup profile for Vanilla 1.16.4
- Install FabricMC 
- Add FabricAPI, RebornCore, and TechReborn to mods folder
- Start Minecraft from MultiMC with the Fabric Profile

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3, 1.16.4
 - Mod Loader: Fabric
 - Java: OpenJDK 8
 - OS: Windows 10
 
**Logs**
https://pastebin.com/EVmgK0fb

**Comment by drcrazy** [comment]
Any particular reasons to use old RC?

**Comment by TwoOxMon** [comment]
It´s the newest supported version when choosing "Game Version" On CurseForge "Files" tab

**Comment by modmuss50** [comment]
Update or delete RC.
