### ISSUE TITLE
Sulfer dust doesn't want to combine.

### ISSUE THREAD

**Issue by Thomasdeontdeker** [TechReborn/TechReborn#2397]
If i want to make sulfer cell, it shows a recipe, 1 empty cell and 1 sulfer dust in a chemical reactor.

![image](https://user-images.githubusercontent.com/83987733/117731155-f4f51500-b1ed-11eb-93bf-69808e6f71dc.png)

Data:
 -Minecraft 1.165
 -Mod Loader: fabric
 -Modpack all of fabric 3
 -Tech reborn v3.8.2

I tested if the machine worked, it just normaly works with different recipes.

**Comment by drcrazy** [comment]
It should be solid canning machine, rather then reactor

![image](https://user-images.githubusercontent.com/1382352/124168032-44004d80-daad-11eb-81fc-6409ab277f9f.png)
