### ISSUE TITLE
Auto Crafting Table deleting durability items on craft

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2398]
Hi,

Whenever I try and use Croptopia tools with the Auto Crafting Table, it deletes the item instead of taking durability from the item like it should. Here is a video demonstration first showing how it should work, and then what is happening.
[External Youtube Video](https://youtu.be/b6plS-v7KCU)

I am using Croptopia 1.3.6 and Tech Reborn 3.8.2 build 220 on MC 1.16.5 on a server.

I have a suspicion that both items are meant to be transported to the bottom right slot like the bucket, but because the recipe uses two items that stay in the table, it is causing a problem.

Thanks

**Comment by drcrazy** [comment]
Duplicate for #2061
