### ISSUE TITLE
Near-zero energy amounts in cables still shock the player

### ISSUE THREAD

**Issue by The-Fireplace** [TechReborn/TechReborn#2400]
**Describe the bug**
When energy stored/being transferred is near-zero, cables still shock the player despite "no" energy being transferred.

**Steps to Reproduce**
- Have machines that are using energy with a setup like the following, with the right generator powering the machines, then run out of power
- See that the rightmost batbox has no energy
- See that the middle batbox has an increasingly tiny but never quite zero amount of energy stored
- Stand on the tin cable and get shocked still.

**Screenshots**
![image](https://user-images.githubusercontent.com/5914284/119244180-85f3b680-bb33-11eb-8023-8609058008d3.png)
![image](https://user-images.githubusercontent.com/5914284/119244186-8b510100-bb33-11eb-9109-eb441935f127.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric
 - Tech Reborn: v3.8.3+build.231

**Comment by Technici4n** [comment]
TR is now using integer energy amounts, so this should be fixed.
