### ISSUE TITLE
TR causes crash when used with IndRev

### ISSUE THREAD

**Issue by noclueumbreon** [TechReborn/TechReborn#2405]
**Description**
Causes a crash when used with Industrial Revolution's energy items.

**Steps to Reproduce**
Install both Industrial Revolution and TechReborn
Attempt to craft a battery or other item which uses power from Industrial Revolution

**Screenshots**
Excerpt from server owner's crash log:
![image](https://user-images.githubusercontent.com/9979380/120493114-8845e400-c36f-11eb-8b20-267546864599.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
https://pastebin.com/WJgyffiF

**Comment by heyjudek** [comment]
I have both of those mods and never had a crash (indrev-1.9.16-BETA and TechReborn-1.16-3.8.4+build.236). Could it be a third mod causing the issue?

**Comment by Technici4n** [comment]
Update indrev, this is not a TR issue.
