### ISSUE TITLE
Saplings not dropping from trees

### ISSUE THREAD

**Issue by BernardoGrigiastro** [TechReborn/TechReborn#2406]
Saplings not dropping from trees, leaves drops leaves, mined one tree got 9 logs and 59 leaves!

1.17-pre4
loader 0.11.3
fabric-api-0.34.8+1.17.jar
TechReborn-5.0.0-alpha+build.22.jar

**Comment by bentterp** [comment]
Tested holding leaves, holding axe and barehanded, no luck

**Comment by drcrazy** [comment]
![image](https://user-images.githubusercontent.com/1382352/121860561-a3b2d680-cd01-11eb-8756-6227866975f0.png)

**Comment by drcrazy** [comment]
Probably fixed by a49daa033948760f0b543872a9fdfb43b55daef4
