### ISSUE TITLE
Integer Limit Fusion Control Computer

### ISSUE THREAD

**Issue by Snoe0** [TechReborn/TechReborn#2407]
**Describe the bug**
The Fusion Control Computer doesn't cap its power, and instead goes to integer limit.

**Steps to Reproduce**
Power up the Fusion Control Computer with a radius of 7.

**Screenshots**
![image](https://user-images.githubusercontent.com/83789327/120700238-6c316800-c47f-11eb-9184-8dfdadd2abf1.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
It gives no errors, so I don't see how the logs could help but if it is requested later I will attach them.

**Comment by duncanwebb** [comment]
I noticed this too, that the energy stored can exceed its capacity. Also, the documentation on the wiki could be improved, as it does not say it needs 40ME to start working. Once it is working this is very neat but confusing when you don't know how it works.

**Comment by BigJoshEnergy** [comment]
> I noticed this too, that the energy stored can exceed its capacity. Also, the documentation on the wiki could be improved, as it does not say it needs 40ME to start working. Once it is working this is very neat but confusing when you don't know how it works.

Funny you posted this so recently; I just noticed the multiple issues with the documentation as well as how the Fusion Control Computer handles things. I'll be updating the wiki shortly and adding some extra bug reports as well. That said, here's a quick and dirty guide:
- Helium3 Cell: 40M Energy to Start Running
- Heliumplasma Cell: 40M Energy to Start Running
- Platinum Dust: 80M Energy to Start Running
- Iridium Ore: 90M Energy to Start Running

(Additionally, Platinum Dust and Iridium Ore don't actually consume extra power to create them - there's a bug where it actually gives you 2048 Energy * 1024 Ticks = 2,097,152 Energy.)

Actually, to add to the above reported bug: the power stored actually goes beyond the 2,147,483,647 on the backend, regardless of what size you select. If you use the console command `/data get block 204 102 128 PowerAcceptor.energy` (where 204 102 128 is the x y and z coordinates of your Fusion Control Computer) you can see how much power the block has stored in scientific notation (this is on Minecraft 1.16.5 Tech Reborn Version 3.8.4 Build 236). It far exceeds the 2.1G Energy that the machine is supposed to impose on the player. Just for fun I've been running mine in the background while I write this and I'm up to 155.3G Energy. ¯\\_(ツ)_/¯

**Comment by duncanwebb** [comment]
Thanks for this information, it is very helpful. One thing that I'm not sure about is does the fusion reactor only generate power when it is crafting cells?

As a tiny aside, the two size buttons on the right are swapped, the single arrow changes the size by 5 and the double arrow changes it by 1.

**Comment by Wdavery** [comment]
Yes, only generating during crafting. 
Also the swapped buttons should be fixed now, see #2412
