### ISSUE TITLE
Can't change Energy/Tick. It's not take the changes in the config file

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2408]
**Describe the bug**
I changed the Energy/Tick for Generators in the config-file but the Mod doesn't take any changes.

**Steps to Reproduce**
- Change values in the config-file
- Restart Server
- No Changes

**Screenshots**
![2021-06-06_01 12 01](https://user-images.githubusercontent.com/4640928/120907684-dd317500-c663-11eb-8b3b-f5093ee2c6e7.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/d1eXK4yg

**Additional context**

**Comment by drcrazy** [comment]
Can't reproduce. Please, make sure that you've changed proper generation rate (day or night) for a proper panel type. Ultimate in case of you screenshot.

![image](https://user-images.githubusercontent.com/1382352/122593321-29ba7e80-d06e-11eb-956f-07c5e2356b12.png)
