### ISSUE TITLE
game freezes

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [TechReborn/TechReborn#2409]
mc 1.17 release
java 16
CavesAndCliffsPreview.zip
fabric 0.11.3
fabric-api-0.35.2+1.17.jar
TechReborn-5.0.1-beta+build.29.jar

everything works fine, until
creating multistructure industrial blast furnace
in currrent game session, the furnace works like intendet,
but
closing the session ( close and save)
reopen the world again,
the launcher stops at 100 %
not showing joining world

It's always good to have a backup

regards

**Comment by drcrazy** [comment]
Duplicate for #2410

I know this one created earlier, but second one contains more details.
