### ISSUE TITLE
Items are still registered also when the Ore doesn't exist

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#241]
@modmuss50 Unfortunately, this isn't fixed, items are still registered also when the Ore doesn't exist.
![2015-11-11_13 04 04 2](https://cloud.githubusercontent.com/assets/8685029/11090791/2e0b6216-8875-11e5-9933-7b81cce5d24b.png)
TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by modmuss50** [comment]
I cannot easily remove the item. I can remove all recipes pointing to it though.

**Comment by Xen1290** [comment]
Oh ok, thanks!

**Comment by Xen1290** [comment]
Unfortunately, this isn't fixed @modmuss50 , see this:
![2015-11-12_15 19 03 2](https://cloud.githubusercontent.com/assets/8685029/11121226/dfa518a2-8954-11e5-8d94-dd761e435b66.png)
![2015-11-12_15 47 53 2](https://cloud.githubusercontent.com/assets/8685029/11121228/e0a6d8b2-8954-11e5-9e80-e20ccf68dec8.png)
![2015-11-12_15 47 58 2](https://cloud.githubusercontent.com/assets/8685029/11121229/e16490fa-8954-11e5-9ef4-8aefc249e886.png)
