### ISSUE TITLE
Something is weird between TechReborn and Trinkets (1.17)

### ISSUE THREAD

**Issue by Desempregago** [TechReborn/TechReborn#2411]
**Describe the bug**
Probably Trinkets thinking that the Quantum Suit pieces are trinket components

**Steps to Reproduce**
- Install Trinkets and equip any Quantum Suit part
- Crash

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric 1.17 (Loader: 0.11.6, API: 0.35.2)

**Logs**
[Crash Report](https://pastebin.com/gSBCfuGm)

**Comment by Desempregago** [comment]
PS: I think it's not Trinkets, but the Caelus API (trinkets' elytra flight code, also used in Curios API) that is messing something up

**Comment by Tyropop** [comment]
I've had this issue too, so I hope it gets a fix soon

**Comment by bbeezz** [comment]
Same happened to me. I have trinket elytra

**Comment by drcrazy** [comment]
Should be closed by 482fe4f01f70e5b1563e52b1fb133dfd58c605f4
