### ISSUE TITLE
[1.17] Ore configuration seems to be missing in world.json

### ISSUE THREAD

**Issue by olee** [TechReborn/TechReborn#2416]
**Describe the bug**
I created a new pack with tech reborn (first time user) and there seems to be no configuration for ores in world.json config file, even though it seems to have been added here: https://github.com/TechReborn/TechReborn/commit/7138a8d45bdfba8f25978ba32d476f49d185e84e.

**Steps to Reproduce**
Install and run (latest) version v5.0.2-beta+build.38

**Content of world.json**
```json
{
  "loot": {
    "enableOverworldLoot": {
      "comment": "When true TechReborn will add ingots, machine frames and circuits to OverWorld loot chests.",
      "value": true
    },
    "enableEndLoot": {
      "comment": "When true TechReborn will add ingots, machine frames and circuits to The End loot chests.",
      "value": true
    },
    "enableNetherLoot": {
      "comment": "When true TechReborn will add ingots, machine frames and circuits to Nether loot chests.",
      "value": true
    }
  }
}
```

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: fabric

**Comment by modmuss50** [comment]
The configurable ore gen is current disabled due to some changes in 1.17. I will need to change it a bit to make it work again.

**Comment by drcrazy** [comment]
Ore gen won't be a thing until 1.18
