### ISSUE TITLE
Clay block gives 5 clay items in grinder 

### ISSUE THREAD

**Issue by Watersfall** [TechReborn/TechReborn#2421]
https://cdn.discordapp.com/attachments/832334159728607326/860395550939021342/unknown.png

**Comment by drcrazy** [comment]
Already fixed in dev by ecff51d49849aa26de44302f52eb97b80475fe9d

**Comment by Watersfall** [comment]
That doesn't look like it fixes the clay dupe but ok

**Comment by drcrazy** [comment]
It's hard to understand by screenshot only. I saw texture issue on SS, and this was fixed.
