### ISSUE TITLE
Crash upon rendering item model in creative/REI menu.

### ISSUE THREAD

**Issue by lolman9998** [TechReborn/TechReborn#2429]
My game crashes when viewing some item model from this mod. I have no idea which one it is crashing on.

- Go into creative, or REI if installed.
- Go to Tech Reborn tab, or just scroll through REI.
- Scroll through items.

 - Minecraft: 1.17
 - Mod Loader: Fabric
 - Most recent version of the mod on curseforge

Log
https://pastebin.com/HeE3F1w2

Crash Report
https://pastebin.com/HWj2F8Vx

**Comment by lolman9998** [comment]
After more testing with the most recent code, after building a new version myself, I have more info about the crash. The item in question is near the bottom of the creative tab. Still no idea which one. Screenshot of where it crashes attached.
![image](https://user-images.githubusercontent.com/42286057/124645915-9fd62800-de59-11eb-804a-af607c77ad57.png)
It is very hard to get screenshots of where it crashes, due to how fast the window closes, but I hope this helps to narrow it down.

**Comment by drcrazy** [comment]
It is failing here "at techreborn.client.render.BaseDynamicFluidBakedModel.lambda$emitItemQuads$0(BaseDynamicFluidBakedModel.java:86)"

And this isn't happening in dev env. So hard to understand what is wrong.

**Comment by Jcewazhere** [comment]
Edit: For me it is the toxic goo block from "Thinking With Portatos" causing the crash. It's missing a texture/sprite in REI. When loaded alone TWP works and you just see the missing texture purple/black grid on that block in REI. If you try to place that block the game crashes. When loaded with Tech Reborn the fluid cell missing texture causes a crash. 
It's up to TWP's author to fix that texture and or Tech Reborn's to fix missing texture handling. 

Edit 2: There is a newer version of TWP released 6/22/2021 that doesn't have the toxic goo and thus fixes the problem, at least with this mod's missing textures. If it's another mod with missing textures for fluids then Tech Reborn may still crash when it tries to put it into a cell.

-------------------------------------------------------------------------------------------
I can verify this. It crashes when I try to search for 'ic' as in ice, and 'go' as in gold. 

From the crash report: 
-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: techreborn:cell

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: cell
	Item Damage: 0
	Item NBT: {fluid:"thinkingwithportatos:toxic_goo"}
	Item Foil: false

So it seems like some of the cells are not rendering properly in REI/creative tabs.

**Comment by drcrazy** [comment]
Thanks to @Jcewazhere to narrowing it down to  "Thinking With Portatos"

**Comment by Jcewazhere** [comment]
You're welcome. 
Though technically it could be any mod with a broken liquid block texture. When Tech Reborn tires to create a cell to hold that liquid the game crashes. So other mods could cause the crash if they happen to have broken/missing liquid block textures.

**Comment by lolman9998** [comment]
Yup, fixed. Thanks guys, I will report this to TWP.
