### ISSUE TITLE
Quantum chest armor crashes game

### ISSUE THREAD

**Issue by bbeezz** [TechReborn/TechReborn#2430]
Minecraft 1.17, latest Tech Reborn version, i charged the armor piece and when i tried to wear it directly through the MFSU, the game crashed. I cannot access anymore to the world. I also tried to wear it in another world and happened the same issue. I noticed that this problem happens only when the armor has energy inside. The crash log says:
[Launcher] Minecraft closed with exit code: -805306369
flush now
[Launcher] [Crash] Signature "PermGen error" matches!
[Crash] Signature "PermGen error" matches!
[Launcher] [Crash] Crash has been recognized!
[Crash] Crash has been recognized!
flush now

**Comment by bbeezz** [comment]
I've just read that other player that have trinket are experiencing the same issue, i forgot to mention that i have trinket elytra

**Comment by drcrazy** [comment]
Duplicate for #2411
