### ISSUE TITLE
Crash upon creating creating new save due to missing mod-related resource key

### ISSUE THREAD

**Issue by RowanSkie** [TechReborn/TechReborn#2433]
**Describe the bug**
I have a very complicated mod setup with dozens of mods and some of them catch game errors. When I create a new world, Not Enough Crashes catches a major error, disallowing the Fabric Biomes API to work due to what is apparently a missing resource key.

**Steps to Reproduce**
- Install TechReborn (and Not Enough Crashes)
- Create New World

**Screenshots**
> If applicable, add screenshots to help explain your problem.
No applicable screenshots. It's a crash log caught by Not Enough Crashes and attached below.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric

**Logs**
> Pastebin the log [e.g. `logs/latest.log`] and link it below:
- https://paste.ee/p/23TSt (MultiMC Log)
- https://pastebin.com/uGuZvVq6 (Log Caught by Not Enough Crashes)

**Additional context**
> Add any other context about the problem here.
- Does the mod need other dependencies? It is working on the main menu, after all.

**Comment by drcrazy** [comment]
Can't reproduce. There were changes in worldgen code, which might already fix this.
