### ISSUE TITLE
Shift Clicking with the Battery Box is inconsistent

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2437]
Place a Battery Box down (output not on top), put an energy source on it (e.g. Creative Solar Panel). It seems to be important that there is an energy flow. Take a chargable but empty tool (e.g. Advanced Chainsaw) into your hotbar, activate the Battery Box. Shift click on the tool in your hot bar and then on it in the Battery Box. Repeat. Now different behavior can occur.
 - Everything works as you would expect it to work (i.e. the shift click just switches the tool between hotbar and Box)
 - When shift clicking in the Box, it can happen that the tool is added to the hotbar, but also still displayed in the Box. Clicking on it or closing the Box and opening it again makes the icon disappear.
 - If the display is doubled as in the previous point, and you try to shift click on the tool in your hotbar, it can happen it is shown for a frame on the right side of the Battery Box before vanishing (and appearing on the left side, which is not visible because of the display bug)
 - At any point it can happen that shift clicking the tool can cause it to be thrown away instead of switching places, with no indication why.

**Environment**
 - Minecraft 1.17
 - Fabric Loader 0.11.6
 - Fabric API 0.36.0
 - TR 5.0.3-beta+build.55

**Additional Thoughts**
Might be related to #2365 and #2436

**Comment by drcrazy** [comment]
Can't reproduce on 1.20
