### ISSUE TITLE
Fusion Control Computer

### ISSUE THREAD

**Issue by BigJoshEnergy** [TechReborn/TechReborn#2439]
**Describe the bug**
The Fusion Control Computer doesn't allow you to output energy on any sides, despite this being a feature as described in the wiki.

**Steps to Reproduce**
- Attach a cable to any and all sides of a charged Fusion Control Computer
- Measure the energy within the cable using the Debug Tool item
- Every and all cable will show no charge, showing that they are not able to draw power from the device.

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric-api-0.36.0+1.16
 - TechReborn-1.16-3.8.4+build.236

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: Pastebin is currently down, using [this link](https://drive.google.com/file/d/1_o_73RGtG_8Ij2mgB1nyw7AtPx5sgwlI/view?usp=sharing) instead.

**Additional context**
N/A

**Comment by drcrazy** [comment]
Fusion reactor outputs energy only while crafting
