### ISSUE TITLE
Display stored power with IC2 Classic E-Net

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#244]
This tooltip(Power Stored)  is missing in all WAILA Tooltips, except for Saw Mill. See this:
![2015-11-11_13 24 33 2](https://cloud.githubusercontent.com/assets/8685029/11091895/41a96fde-887f-11e5-88df-b1dd1684b729.png)
![2015-11-11_13 24 37 2](https://cloud.githubusercontent.com/assets/8685029/11091896/42ac57fc-887f-11e5-9b64-0703d3568d0f.png)
TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by modmuss50** [comment]
The reason we dont display the power stored is that IC2 puts more energy than the machine can accept, This is a reason why machines dont explode in ic2. Its an ic2 bug that we dont want to expose to the end user.

**Comment by Xen1290** [comment]
I use IC2 Classic E-Net, that as far as I know works perfectly. So maybe you can add this only for Uncomplication and IC2 Classic user? @modmuss50

**Comment by Xen1290** [comment]
Thanks!
