### ISSUE TITLE
Industrial Centrifuge Crashes

### ISSUE THREAD

**Issue by GuildMenu** [TechReborn/TechReborn#2440]
The industrial centrifuge crashes my world the instant I place it. This happens to a few other blocks as well but I don't have any crash reports nor do I remember which blocks

**Steps to Reproduce**
Place an industrial centrifuge.

**Environment (please complete the following information with the version):**
 - Minecraft 1.8.9
 - FTB Launcher (Sky Odyssey)

**Logs**
https://pastebin.com/PnLj1ugQ

**Comment by drcrazy** [comment]
Sorry, 1.8.9 is too ancient and is not supported.
