### ISSUE TITLE
Diesel generator is a low tier but its fuel requires high tier machines

### ISSUE THREAD

**Issue by duncanwebb** [TechReborn/TechReborn#2442]
**Is your feature request related to a problem? Please describe.**
The distillation tower is a medium tier machine that require industrial machine casings (mid-game blocks). It is somewhat frustrating that the diesel generator only produces 32 E/t

**Describe the solution you'd like**
It would be great if casings could be added to the diesel generator to make it a higher tier machine and generate some reasonable power, I would like something that fills the gap between medium and extreme, providing 256-1024 E/t

**Describe alternatives you've considered**
An industrial diesel engine using higher level components. Various sizes of multi-blocks

**Additional context**
A couple of examples.
![diesel-1](https://user-images.githubusercontent.com/4198031/124588709-64d3f480-de59-11eb-8232-ea9f3218458f.png)
![diesel-2](https://user-images.githubusercontent.com/4198031/124588725-68677b80-de59-11eb-9d82-df917daf3123.png)

**Comment by drcrazy** [comment]
Generation rate not related to materials required. For example, Dragon Egg siphon. 
Also, both generation rate and output rate could be adjusted via config.
