### ISSUE TITLE
Add DashLoader support

### ISSUE THREAD

**Issue by alphaqu** [TechReborn/TechReborn#2443]
**Is your feature request related to a problem? Please describe.**
Sort of. The loading times of Minecraft are exponential where the more models you add the exponentially worse the loading times get.
**Describe the solution you'd like**
Adding DashLoader support through their [api](https://github.com/alphaqu/DashLoader/wiki) and allow TechReborn to cache and load super fast on the next launch.

**Describe alternatives you've considered**
There are not really any alternatives to DashLoader. Some help like LazyDFU but they remove a part of the loading that is mostly static.

**Additional context**
Api documentation: https://github.com/alphaqu/DashLoader/wiki

**Comment by modmuss50** [comment]
If this can be done fairly easilly without making it a hard dependency then sure. If there is anything that can be done to improve load times for everyone then I would be happy to do that.

Its not very clear from reading the docs what would need to be done on TRs side, it seems to handle models but most of TRs models are just the vanilla json models.

Profiling to get numbers about what is slow and why is where I would start before caching everything.

**Comment by alphaqu** [comment]
It's mostly custom BakedModel implementations and the API is designed to not require DashLoader as a hard dependency.
The documentation is relatively new and might not have 100% coverage.  If you find anything unclear please open an issue or just DM me on discord.

**Comment by alphaqu** [comment]
![image](https://user-images.githubusercontent.com/24830855/125092691-dd44ea80-e0d1-11eb-8c51-f7e563249e42.png)
This is with adorn and indrev which add about 50% more models. DashLoaders time increased by about 50%. But MCs time increased by 150% which in this case indicated that DashLoader scales linearly instead of exponentially.
