### ISSUE TITLE
Smelt Raw Ore Blocks

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2446]
Vanilla Raw Ore Blocks cannot be smelted in the Furnace, probably because smelting them would unbalance smelting, because in Vanilla all items take the same time. However, we don't have this restriction in TR, so I would like to see them added to the Electric Furnace or (if that isn't practical) at least the Industrial Blast Furnace.

**Comment by Bluberry-Kat** [comment]
> because in Vanilla all items take the same time 

How long a smelting recipe takes is actually just a key in the recipe json, even in vanilla. That means it could happen even in vanilla furnaces.

That being said, I'm pretty sure I disagree with this?  
Assuming a raw block takes the same time to smelt as a single raw ore, that means you have 9x more energy efficiency, for free, specifically for ores.  
Assuming a raw block takes 9x the time to smelt as a single raw ore, then why would the player bother to smelt a raw block over a raw ore?

Personally I'd rather just see vanilla parity here.

**Comment by Ayutac** [comment]
> That means it could happen even in vanilla furnaces.

neat, didn't know that.

> Assuming a raw block takes the same time to smelt as a single raw ore

Of course not. By
> However, we don't have this restriction in TR

I meant we don't have to smelt it as fast as normal ores. AND we can take another amount of energy as well.

> Assuming a raw block takes 9x the time to smelt as a single raw ore, then why would the player bother to smelt a raw block over a raw ore?

Why would a player bother to uncraft the raw block when he can just put it in like that?

This is not meant to be a feature that saves a lot of energy (though it could be done that a block only needs the energy and time of 8 raw ores, for those people who miss the extra step with dust), but merely quality of life that is nice to have. When I have enough eg raw iron for several blocks, why would I need to uncraft them, smelt them, then craft them into a block again?

**Comment by drcrazy** [comment]
Not possible for smelting kind of recipe. It expect result as a string, not as a compound. And doesn't explicitly support "count" tag. 

![image](https://user-images.githubusercontent.com/1382352/129200153-8d169ca1-fc44-49fc-9075-e6c11b2a149a.png)

**Comment by Ayutac** [comment]
@drcrazy Uhm, the result wouldn't be 9 iron of course but an iron block. And the cooking time can be provided, so it can be added very easily?

**Comment by drcrazy** [comment]
Hmm..  Yeah, iron block could be an option

**Comment by drcrazy** [comment]
Psst. It will require 1500 ticks to smelt block compare to 9*200 to smelt 9 ingots. Which should give a benefit for automation of raw ore -> raw ore block -> smelting process chain.
