### ISSUE TITLE
Game crashes with ModernBeta mod installed (1.17)

### ISSUE THREAD

**Issue by IMadeSourceUp** [TechReborn/TechReborn#2447]
Describe the bug:
It doesn't matter what type of generation the world has: ModernBeta or from Minecraft, game crashes anyway.
Minecraft 1.16.5 works fine, though.

- First Step:
Create new world or enter the existing one with mod installed
- Second Step:
Wait for it to crash.
Enviroment Info:
 - Minecraft: 1.17
 - Mod Loader: Fabric

Crash Report:
https://pastebin.com/cXx10281

Additional context:
I think this has to do something with (https://github.com/TechReborn/TechReborn/issues/2416#issue-925674778)

**Comment by modmuss50** [comment]
This should hopefully be fixed.
