### ISSUE TITLE
Raw ores are not tagged

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2448]
To match conventions used by IR and MI, raw ores should be tagged as `c:raw_xxx_ores`, and raw ore blocks should be tagged as `c:raw_xxx_blocks`. For example, `c:raw_tin_ores` and `c:raw_tin_blocks`.

**Comment by drcrazy** [comment]
I haven't found any "c" tags in MI. 
There are no c:raw_xxx_blocks in IR. Also I do not see usage for it with only block <-> 9 items recipe for crafting table.

**Comment by Technici4n** [comment]
MI generates them dynamically so you won't find them in the jar but they exist. ^^

IR needs to tag them as well. This allows the unification script to detect them and hide extra variants.
