### ISSUE TITLE
Machines doesn't accept Energy from items

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#245]
See:
![2015-11-11_13 52 05 2](https://cloud.githubusercontent.com/assets/8685029/11091918/79aa5470-887f-11e5-812a-197102ca071a.png)
![2015-11-03_20 33 27 2](https://cloud.githubusercontent.com/assets/8685029/11091919/7aceeb2c-887f-11e5-8880-a727fc5ec70f.png)
With cables everything works.

TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by modmuss50** [comment]
Ive merged them into one https://github.com/TechReborn/TechReborn/issues/252

**Comment by Xen1290** [comment]
Ok, thanks!
