### ISSUE TITLE
Extractor power usage is incorrect

### ISSUE THREAD

**Issue by mnsnownutt** [TechReborn/TechReborn#2451]
**Describe the bug**
Power usage with no upgrades is supposed to be 1,000E per tick, but even an industrial solar panel gets drained by it in the daylight and it is supposed to be generating 8,000E per tick.  I was trying to extract rubber from rubber tree logs.

**Steps to Reproduce**
Place an extractor and an industrial solar panel next to each other with no other machines drawing power from the industrial solar panel and then start extracting something.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric
![2021-07-11_16 35 12](https://user-images.githubusercontent.com/31514693/125210804-9be64380-e267-11eb-8a97-6adf0d537565.png)
![2021-07-11_16 35 21](https://user-images.githubusercontent.com/31514693/125210808-a1438e00-e267-11eb-9dec-08ad03c6f28d.png)

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by drcrazy** [comment]
Power usage depends on recipe. Rubber log to rubber recipe requires 10 E\t for 300 ticks. 
Industrial solar panel generates 8 E\t

So you are 2E\t short in your power gen

![image](https://user-images.githubusercontent.com/1382352/125869854-b828b2ee-7f18-470d-805f-40b6da78e002.png)
