### ISSUE TITLE
Sawdust, what to do with it

### ISSUE THREAD

**Issue by Morphyloon** [TechReborn/TechReborn#2452]
One of the few "useless" byproducts in Tech Reborn is sawdust from the Sawmill machine. I propose that a real life use be borrowed from the lumber industry. A new recipe to turn sawdust into charcoal, for fuel and other recipes that use charcoal. This will give the item a use, albit a marginal one, until a better idea comes along as well as not creating any new items in the database-- which would have to be added and updated to every process that uses burnable items.

A formless recipe for the crafting grid; 9 TR sawdust becomes 1 Minecraft charcoal

**Comment by Ayutac** [comment]
Sawdust + Slimeball = 9 Paper? Not usefull, but realistic :P

And still any "useless" byproduct is good for crafting UU matter.

**Comment by drcrazy** [comment]
Fixed by 69626d279be459a556214168b1ef7eda63c9ccf7
