### ISSUE TITLE
Crash at Start 

### ISSUE THREAD

**Issue by M4DMAXX** [TechReborn/TechReborn#2455]
Environment
 - Minecraft: 1.16.2
 - Mod Loader: Fabric

Description
-I have installed Fabric 1.16.2, Tech Reborn and other Mods. First it runs but at least i installed a few new Mods and now i got 
 following Crash

Crashlog:
[Techreborn Crash.txt](https://github.com/TechReborn/TechReborn/files/6812351/Techreborn.Crash.txt)

Im new at Fabric and appreciated any help

**Comment by M4DMAXX** [comment]
After testing something and made a 5 Mods only steps... i think thats something to do with the black powder mod

https://pastebin.com/NP9zeH6J

**Comment by drcrazy** [comment]
Any particular reason to use 1.16.2 and not 1.16.5 ?
I'm afraid mostly none of mod devs will address compatibility issues for 1.16.2

**Comment by M4DMAXX** [comment]
Actually Bad Connection only. I actually move to another city and Connection are bad until i finish the move

**Comment by drcrazy** [comment]
1.16.2 is not supported
