### ISSUE TITLE
Auto Crafting Table consumes Master Infusion Crystal

### ISSUE THREAD

**Issue by LycanMT** [TechReborn/TechReborn#2456]
**Describe the bug**
I'm trying to automate the essence infusion process in AOF 3 by connecting 4 Auto Crafting Tables together, each one with a Master Infusion Crystal. The crystal has infinite uses and isn't meant to be consumed, however when it's in the Auto Crafting Table it won't combine the essences while the recipe is locked due to the crystal being by itself. If I unlock the recipe, it will make the recipe but consume the crystal. 
**Steps to Reproduce**
- First Step: Set up an Auto Crafting Table to combine essences with a Master Infusion Crystal
- Second Step: Run the process

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 - Mod Loader: [e.g. forge, fabric] It's through CurseForge, the mod is All of Fabric 3

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by langenf1** [comment]
Have you found a workaround within AOF 3 for this bug besides AE2 auto crafting? I'm trying to auto craft supremium without having an entire AE2 setup yet.

**Comment by drcrazy** [comment]
Duplicate for #2061
