### ISSUE TITLE
Industrial Blast Furnace is delicate

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2458]
**Describe the bug**
The Industrial Blast Furnace doesn't like to be overcompleted. If the multiblock structure is completed (according to the IBF) and you add any Casing block to the multistructure (except if in front or below the IBF, it needs to be connected to the other casings), the IBF shows that the multiblock structure isn't completed. The Industrial Grinder does not care about additional casing blocks to its exterior though, so there is at least some inconsistency.

A side effect of this delicacy is that you cannot place the IBF adjacent to any other multiblock structure.

**Steps to Reproduce**
- start a new world in Creative
- build Industrial Blast Furnace to its multiblock satisfaction (lava doesn't matter)
- add any Casing Block adjacent to the existing Casing Blocks
- IBF will now complain the multiblock structure isn't completed

**Screenshot**
![2021-07-20_07 27 25](https://user-images.githubusercontent.com/7873396/126266766-91c759ce-b872-4595-8fd3-57a98de567ec.png)

**Environment:**
 - Minecraft 1.17
 - Fabric Loader 0.11.6
 - Fabric API 0.36.0
 - TR 5.0.3-beta+build.55

**Comment by drcrazy** [comment]
It is trying to assemble multiblock with that additional casing. And fails. This is by design.

**Comment by Ayutac** [comment]
Okay, cool and all, but then why does the Industrial Grinder behave differently?

**Comment by Nixill** [comment]
This could at least be better explained - maybe add an "🚫" or "❌" overlay atop adjacent casings when the hologram is turned on, and a paragraph or two about it in the wiki?

Also, the Industrial Blast Furnace is the only multiblock with this behavior. I second Ayutac's question of "why?".

Signed, someone who just spent twenty minutes trying to figure out why their IBF wasn't working.

(PS: I don't mind if you want me to open a new issue for it, but I also didn't want to clutter the issues log with what could've been seen as a duplicate.)
