### ISSUE TITLE
[1.17]A copper block crafts 4 plates.

### ISSUE THREAD

**Issue by Sandendaty** [TechReborn/TechReborn#2459]
**Describe the bug**
I put a block of copper into a TR compressor and it only produced 4 copper plates,unlike other metal block which could produce 9 metal plates.

**Screenshots**
![2021-07-20_17 53 16](https://user-images.githubusercontent.com/39406572/126308923-1ac9b09c-7460-4d9a-8375-c73028d64112.png)
![2021-07-20_17 53 27](https://user-images.githubusercontent.com/39406572/126309411-4b6dac7a-9dbe-4aca-be28-5af20654b946.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric loader 0.11.6
 - TR: 5.0.3-beta+build.55

**Comment by Ayutac** [comment]
Has been fixed in 779a2c8b60730612d4be53a1a823cace68a8074c but not in TR 5.0.3. Wait for next release ;)
