### ISSUE TITLE
IDSU/AESU/LESU don't show the Energy Bar

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#246]
<strong>Also IDSU has a wrong button under his name</strong>

![2015-11-11_13 31 39 2](https://cloud.githubusercontent.com/assets/8685029/11091998/1c1585c2-8880-11e5-932d-faf1de0ea676.png)
![2015-11-11_13 33 21 2](https://cloud.githubusercontent.com/assets/8685029/11092004/24720c04-8880-11e5-82ae-00455082cfeb.png)

TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by madzig21** [comment]
I cant even get my LESU to hold a charge it seems to discharge it self as soon as it gains.
example i input a full battbox connected to it one way so it just charges the LESU and as soon as it get 32 eu it drops to somthing like -56943 eu (number is random each time) *note im using 62 lesu blocks and one lesu interface block

**Comment by modmuss50** [comment]
Im merging this with the other one
