### ISSUE TITLE
1.17 Can't place cables on certain sides

### ISSUE THREAD

**Issue by SurpencerChaos** [TechReborn/TechReborn#2460]
**Describe the bug**
I can't place cables on certain sides of another, which side works changes with every placed cable but I can't connect power supplies with machines because of this. Happened on a survival server, not while testing in creative. 

**Steps to Reproduce**
Make a new world in survival
1. Optain the resources to craft an engine and multiple machines, e.g. furnaces and extractors 
2. Try to connect them starting first from the power supply, then from the mashines or take the shortest route possible with hight variations of the blocks

**Screenshots**
Wouldn't help if I included some. 

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric

**Additional context**
As I mentioned it only happened on the server, not while testing things in creative, it seems like a bug because if I try to lay out the cables I suddenly can't place them next to each other in the same direction, only on other sides, and that's something I'm not willing to accept because of the resources taken to craft the cables. 
Also first time here.

**Comment by jusvit** [comment]
Could you record a video?

**Comment by Technici4n** [comment]
The way cables connect was reworked recently, please reopen if you manage to reproduce this issue. (With a video if possible :))
