### ISSUE TITLE
Mod Menu integration and configurable ore generation

### ISSUE THREAD

**Issue by alecselle** [TechReborn/TechReborn#2461]
Some people are unfamiliar with modifying configuration files so adding _some_ of the mods settings to a graphical interface would be useful.

Whether this is implemented or not, I would like to have the option to disable specific or all ore generation. This would allow players to choose which mod's ores to use (like is common in forge mods).

**Comment by Ayutac** [comment]
@alecselle why did you close the issue?

**Comment by alecselle** [comment]
> @alecselle why did you close the issue?

Half of it was a duplicate #2416
