### ISSUE TITLE
fluid tank does not accept industrial revolution pipes

### ISSUE THREAD

**Issue by minecrafterseppe** [TechReborn/TechReborn#2462]
fluid tank does not accept industrial revolutions pipe 
this is the only pipe avaible in 1.17.1
in all of fabric 4

- First Step
- Second Step

**Screenshots**
![image](https://user-images.githubusercontent.com/13523046/127234234-c075479c-159a-4c72-afae-37985991acdd.png)

 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Additional context**
this is the only avaible pipe
but tech reborn does accept industrial foregoings power cables
but not the fluid cables?
so theres no way to make water be pumped automaticly

**Comment by Technici4n** [comment]
IR problem, should be fixed in the next IR release in a few days.
