### ISSUE TITLE
Drills break ores from other mods slowly

### ISSUE THREAD

**Issue by chrsrns** [TechReborn/TechReborn#2464]
**Describe the bug**
TR's drills have slow dig speed when digging Modern Industrialization's and Industrial Revolution's ores. I haven't yet tested it on other mods that have ores, so it's unknown to me if it's a problem specific to those two mods. 

**Steps to Reproduce**
- Download All of Fabric 4
- Create a test world in survival
- Get a charged Basic Drill
- Try to break ores from other mods.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://paste.ee/p/oibR8

**Additional context**
None so far.

**Comment by ghost** [comment]
Just to add to this it may be worth putting tech reborn drills into the vanilla pickaxe and shovels tag as that should help.

**Comment by xanthian** [comment]
doesn't seem to occur beta 5, 1.18.1
tested on MI ores with drill active and inactive.
breaking time identical to that of coal

**Comment by xanthian** [comment]
1.17.1 no longer maintained.
doesn't occur in 1.18.1 
can be closed
