### ISSUE TITLE
All chargeable tools are extremely overpowered for combat

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2468]
**Is your feature request related to a problem? Please describe.**
I think it's a big problem that the basic jackhammer does as much damage as a diamond sword but has an attack speed over 3 times faster.

**Describe the solution you'd like**
All chargeable tools which do more damage than your fists have ridicoulous attack speeds, make the attack speed of all chargeable tools 1.0, maybe 1.6 instead of 1.0 for the nanosaber. The damage values will be fine with these changes.

**Describe alternatives you've considered**
Should be easy to make the weapons balanced by changing a few numbers but if for some reason you think these current numbers are good for the mod atleast make them configureable.

**Additional context**
These overpowered super weapons ruined pvp on my server. It got so bad that I had to disable all pvp enabled zones. I would appreciate it if there was a build with these simple changes asap.

**Comment by Ayutac** [comment]
Not against the configuration file. However, I think that sticking a jackhammer into someone's body makes much more damage than a sword

**Comment by ghost** [comment]
> 
> 
> Not against the configuration file. However, I think that sticking a jackhammer into someone's body makes much more damage than a sword

It's a game, not real life, and it's much more fun when the game is balanced and you can't make a simple tool that does the same amount of damage as a diamond sword while being able to spam click like it's 1.8.
