### ISSUE TITLE
Suggestion: Adding BC like pipes to the mod for easy transport of blocks and fluids

### ISSUE THREAD

**Issue by NOOTLORD** [TechReborn/TechReborn#2469]
Maybe this has already being suggested if so my bad but i would like to see pipes added that behave a bit like the BC pipes.
The pipes would be able to carry fluids and blocks and be compatible with tanks etc. 
So far there are a big lack of pipe mods that do both things and it would be great to have it part of the mod itself.

**Comment by drcrazy** [comment]
There is a PR open for this (https://github.com/TechReborn/TechReborn/pull/2266).  It is not ready to be merged yet. Hope it will be ready in future.
