### ISSUE TITLE
Some bugs with Digital and Quantum Chest

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#247]
See these images, I hope you understand what I mean:
![2015-11-11_13 15 11 2](https://cloud.githubusercontent.com/assets/8685029/11092045/7cfd159e-8880-11e5-8e1d-8ffc616720f5.png)
![2015-11-11_13 15 33 2](https://cloud.githubusercontent.com/assets/8685029/11092046/7d0303a0-8880-11e5-9e3f-434a03c1d6b3.png)
![2015-11-11_13 16 12 2](https://cloud.githubusercontent.com/assets/8685029/11092049/7d5af20e-8880-11e5-825b-f7c06c46d87d.png)
![2015-11-11_13 16 17 2](https://cloud.githubusercontent.com/assets/8685029/11092047/7d080882-8880-11e5-9fa5-ef4a1b175b5a.png)
![2015-11-11_13 16 21 2](https://cloud.githubusercontent.com/assets/8685029/11092048/7d1081ec-8880-11e5-8349-a0a2da0bed7b.png)

<strong>This also happen with QUANTUM TANK</strong>

TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by modmuss50** [comment]
@gigabit101 does this exist in Quantum Storage?

**Comment by gigabit101** [comment]
no I fixed these in Quantum Storage already lol

**Comment by gigabit101** [comment]
https://github.com/gigabit101/QuantumStorage/commit/7448e11f0f84bce483d49567dc5edd50aa40dff8
and
https://github.com/gigabit101/QuantumStorage/commit/e0d82b10afa9305c3a750ae3b0719edbf0e89354

**Comment by Xen1290** [comment]
Thanks!

**Comment by gigabit101** [comment]
Your Welcome ??
