### ISSUE TITLE
Commented code in files

### ISSUE THREAD

**Issue by CoolKangaroo2022** [TechReborn/TechReborn#2470]
Hello! I find in your CONTRIBUTING.md that 

> The code is tidy (indentation, line length, no commented-out code, no spelling mistakes, etc).

However, I still witness some commented code lines in files, e.g., few commented code lines in [MultiBlockCasing.java](https://github.com/TechReborn/TechReborn/blob/ffa75aba8d9f03b60c78571ff6bd3a4038d96158/src/main/java/techreborn/multiblocks/MultiBlockCasing.java) have already existed for 5 years.
I also find commented code in the following files:
* src/main/java/techreborn/blockentity/storage/energy/lesu/LapotronicSUBlockEntity.java
* src/main/java/reborncore/client/gui/builder/slot/elements/SlotConfigPopupElement.java
* src/main/java/reborncore/client/gui/builder/slot/elements/FluidConfigPopupElement.java
* src/main/java/reborncore/client/gui/builder/GuiBase.java
* src/main/java/reborncore/client/gui/guibuilder/GuiBuilder.java
......

Would you like to remove these commented code lines?
If so, I may help with it and open a pull request.

**Comment by modmuss50** [comment]
I don’t follow a lot of those guidelines 😂 we could strictly enforce some with checkstyle rules but I don’t think it’s worth it.

Stuff is prob commented out for a reason so I’d leave it, it’s not causing any harm. If anything adjusting the guidelines to be less hypocritical might be a good idea.

**Comment by drcrazy** [comment]
Guideline written to have as clear code from contribution as possible. We are trying to follow it, but not to the point, especially during mod update between versions. Sometimes it is necessary to leave some code commented to revisit it later, when, for example, mod loader will have built-in support for that feature in TR.

Yes, some of them could be removed, some of them should stay.
