### ISSUE TITLE
Iron Furnace recipe is inaccessible with Blockus

### ISSUE THREAD

**Issue by mtb-xt** [TechReborn/TechReborn#2472]
**Describe the bug**
[Blockus](https://github.com/Brandcraf06/Blockus) mod has the same recipe for **iron plating** as used in TR for **Iron Furnace** - 8 iron ingots. After some updates to either of them, it is impossible to craft iron furnaces - both recipes are present in the recipe book, but crafting any of them creates the object from _blockus_ - **iron plating**.

**Steps to Reproduce**
- Have both TR and Blockus mods enabled
- Try to craft Iron Furnace recipee - you get iron plating instead
- Get frustrated...

**Screenshots**
![2021-08-15_21 29 25](https://user-images.githubusercontent.com/11381295/129474103-7b43cf4d-a9e2-4735-967b-45a10cebaa3d.png)
![2021-08-15_21 29 20](https://user-images.githubusercontent.com/11381295/129474109-c3d5c238-4452-4f98-a917-798ce4af91db.png)

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.17.1]
 - Mod Loader: - fabric@0.37.2+1.17

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://gist.github.com/mtb-xt/029fe71ba4188fd2c9c6eb1950dd94e0

**Additional context**

**Comment by Ayutac** [comment]
Iron Furnace has two recipes:

![2021-08-15_16 12 30](https://user-images.githubusercontent.com/7873396/129481389-2f73d519-9984-4900-896f-3b7e11741e65.png)

**Comment by drcrazy** [comment]
This kind of issues addressed by modpack authors. It is near to impossible to check all recipes from all mods to be sure, that there are no conflicts. 

You can change it by yourself using datapack if author of your modpack is not going to fix it.
