### ISSUE TITLE
REI Composite recipe view list not rendering correctly

### ISSUE THREAD

**Issue by BigFatWizard** [TechReborn/TechReborn#2476]
**Describe the bug**
Recipes that have multiple input fields or multiple output items aren't being displayed correctly in the selection list on the left for composite view of REI.
It will only show items required by the first input field, completely ignoring the second input.
It will render all output items on the same coordinates (but it does extend the size of the field downwards to give enough space for a second item)

**Steps to Reproduce**
- Open REI
- Select composite layout
- Check recipes for machines with multiple input fields and multiple item outputs (e.g. Blast Furnace, Implosion Compressor)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8786791/129699070-3b36af4e-ba67-4155-ab9d-3c874ce004b0.PNG)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric
 - Fabric API: 0.37.2
 - TechReborn: 5.0.6 beta

**Comment by drcrazy** [comment]
Won't fix because it conflicts with https://github.com/TechReborn/TechReborn/issues/2417
