### ISSUE TITLE
[1.17] [FF API] Fluid-based generators consumes fluids too slow

### ISSUE THREAD

**Issue by pipich3** [TechReborn/TechReborn#2478]
**Summary**

Fluid-based generators produce energy as expected but consume liquids too slow

**Steps to Reproduce**

- place a standalone fluid-based generator (e.g. Diesel generator)
- put 1 cell of fuel inside (e.f. Nitro Diesel)
- check the fluid consumption rate and energy production rate on the generator's UI

**Environment**

 - Minecraft: 1.17.1
 - Mod Loader: Fabric (CurseForge 0.180.1.3)
 - Fabric API: 0.37.2
 - RebornCore: 5.0.6-beta (build 94)
 - TechReborn: 5.0.6-beta (build 94)

**Reproduced on**

- Gas turbine
- Plasma generator
- Diesel generator

**Assumptions**

- consumption speed decreased 81 times
- related to the minor unit value decrease
- may be related to https://github.com/TechReborn/TechReborn/commit/fd9d776b4304527819c5a8e43c6ac66e9e5a0578

**Impact**

disbalance; just 1 cell of any fuel for such generators can provide energy slowly but almost forever

**Comment by dizzyd** [comment]
Fixed in #2499
