### ISSUE TITLE
crashing Block{minecraft:void_air}

### ISSUE THREAD

**Issue by morottao** [TechReborn/TechReborn#2479]
**Describe the bug**
when i use warpstone to teleport to my enderman farm with spawners over the ocean the game crashes, and Not Enough Crashes says the error is reborn core and tech reborn. 

**Steps to Reproduce**
- world seed: -3530776536097460116
- house: -375 55 112 (prefab house)
- enderman farm: 309 180 -54

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
https://paste.ee/p/HvDCx

**Comment by morottao** [comment]
the error stopped when i broke the water mill

**Comment by drakosoldier298** [comment]
I am also having this issue and have confirmed yes its the water mills

**Comment by dizzyd** [comment]
This is fixed in PR #2498 fwiw
