### ISSUE TITLE
Some slots bugs

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#248]
![2015-11-11_13 19 04 2](https://cloud.githubusercontent.com/assets/8685029/11092125/0d39661c-8881-11e5-8ea4-83c52c0139f7.png)
![2015-11-11_13 19 07 2](https://cloud.githubusercontent.com/assets/8685029/11092126/0d45cdc6-8881-11e5-9990-9321fb075c51.png)
This happen also in IDSU, AESU and all machines that have the upgrade slots.

TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by modmuss50** [comment]
Ive merged them into one https://github.com/TechReborn/TechReborn/issues/252

**Comment by Xen1290** [comment]
Thanks!
