### ISSUE TITLE
Quarry

### ISSUE THREAD

**Issue by imcasper** [TechReborn/TechReborn#2480]
**Is your feature request related to a problem? Please describe.**
When playing a tech mod, I want to be able to automate ore mining.

**Describe the solution you'd like**
Quarry:
- the ability to choose a drill
- pipes are needed (64 pipes - to the bottom)
- setting filters
- filling holes (the first three times to fall into the mine to death is fun, then annoying)
- drilling UNDER bedrock (as if the world continues downward)

Pipes:
- a basic level of. iron (max depth 32)
- improved level. refined iron (max depth 64)
- industrial level. steel (max depth 256)

Drill head:
- basic (radius 2, area 25 cells)
- improved (radius 3, area 49 cells)
- industrial (radius 5, area 121 cells)

Drilling rig:
One or more types with the possibility of upgrades.
Energy consumption and drilling speed depend on it.

- basic rig (cheap, requires a lot of energy for one mined block)
-industrial rig (expensive, little energy per one mined block) 

**Describe alternatives you've considered**
https://github.com/TechReborn/TechReborn/pull/2265
https://www.curseforge.com/minecraft/mc-mods/quarry-reborn

**Additional context**
I really like the buildcraft quarry
I don't like the 64x64x64 empty hole.
I don't like teleporting resources for 32 blocks.
I like the idea of a pipe to resources

**Comment by TheRealM18** [comment]
There is an addon for tech reborn, called quarry reborn... you could always use that.

**Comment by drcrazy** [comment]
Duplicate for #1946
