### ISSUE TITLE
the rock cutter has no energy limit 

### ISSUE THREAD

**Issue by imcasper** [TechReborn/TechReborn#2481]
**Describe the bug**
when charging, the digger fills up to a certain number.
-this is not 10K (as in the description)
-with each charge, the limit is different (first up to about 200, next up to about 500, etc.)

**Steps to Reproduce**
- make rock cutter
- put it into charger (low level charger)
- wait until charge level is fixed

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
https://www.udrop.com/5RZI/latest.log

**Comment by drcrazy** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/1382352/133907107-578e6a2e-277a-46ad-82bf-def57628e98c.png)

**Comment by imcasper** [comment]
First, you use other version.
My mod file: "TechReborn-1.16-3.8.4+build.236.jar".
Second, i found limit (exactly 400K).

**Comment by drcrazy** [comment]
Yepp, I've tested intentionally on 1.17 due to this: https://discord.com/channels/159382191292416000/616647997421256706/853943162514178070
