### ISSUE TITLE
Transformers don't transfer power

### ISSUE THREAD

**Issue by GreggsOfficial** [TechReborn/TechReborn#2488]
**Describe the bug**
Transformers seemingly have no function, as power directed through isn't stepped down or sent through the output. Additionally, connecting tiers directly has no negative repercussions, making transformers unnecessary. 

**Steps to Reproduce**
* Put any transformer between generator and machine, it won't charge
* Connect any tier generator to any lower tier machine, it works fine

**Screenshots**
![2021-08-29_03 28 12](https://user-images.githubusercontent.com/58743949/131236212-87a457e5-4dac-4c90-a172-4370802f83a8.png)
Furnaces connected to solar panels via either transformers or cables. Only the one on the right is smelting. Note the one on the right is being supplied directly by an extreme tier solar panel without issue. 

**Environment (please complete the following information with the version):**
* Minecraft: 1.16.5
* Mod Loader: Fabric
* Modpack: FTB Cotton 1.1.0
  * RebornCore-1.16-4.7.3+build.136
  * TechReborn-1.16-3.8.4+build.236

**Comment by XenoTheStrange** [comment]
Looks like they might be used if you want to specifically send less energy in one direction in a network. Load balancing is totally a thing. I haven't needed any yet, but it might be useful, idk.
Edit: I guess you could just use another lesser type of wire to do the same thing...

**Comment by drcrazy** [comment]
Actually they do. Input from multi-dot, output from single dot 

![image](https://user-images.githubusercontent.com/1382352/133906939-10565749-0a66-4685-b693-656f83009482.png)

PS. Wiki fixed.
