### ISSUE TITLE
Bauxite and Galena don't have the same mining level

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2489]
Is this by design? Because they share the property of needing special treatment unlike the other ores, I thought they would share a mining level as well, but Bauxite can be mined with a stone pickaxe while Galena can't

**Comment by dizzyd** [comment]
Looking at the code, this does appear to have been done on purpose - but no clue as to why. I'd generally agree (from a progression perspective) that Bauxite should require an iron pickaxe.
