### ISSUE TITLE
Energy Unit

### ISSUE THREAD

**Issue by steven1159** [TechReborn/TechReborn#2491]
**Is your feature request related to a problem? Please describe.**
 A lot of solar cause quite serious FPS decrease
**Describe the solution you'd like**
Increase energy transportation unit to maybe 10^-2 or bigger

**Comment by Technici4n** [comment]
How does the energy unit influence FPS?

**Comment by steven1159** [comment]
Sever TPS also getting unstable after I installed about one stack solar panel.
caculating energy number down to  10^-13 maybe is too heavy for performance also useless

**Comment by Technici4n** [comment]
Please install spark, run a profile, and put the result here. Decimal calculation is mostly irrelevant at the scale of minecraft.

**Comment by Technici4n** [comment]
Please reopen if you can provide profiling data on the latest version.
