### ISSUE TITLE
Machines half drained on SSP world load... every time.. normal or bug?

### ISSUE THREAD

**Issue by MelchiorGaspar** [TechReborn/TechReborn#2504]
**Describe the bug**
I noticed that when I load my survival single player world map... 
the machines like the electric furnace and electric grinder are not fully charged like it was when I saved & exited the map/world
and they were about half charged... is this normal or a bug??

I have attached my world having the issue and set the spawn point in my place.

**Steps to Reproduce**
- First Step:       Load a world with machines already powered and should be fully charged..
- Second Step:  exit/save world and reload game too if needed, then reload said map/world.
- Third step:     Check machines to see if they are fully charged still, 

**Screenshots**
![Minecraft active Mods list as of (2021-09-17)](https://user-images.githubusercontent.com/1712842/133825975-380c8f4f-2b54-4102-a33c-18256a75eee6.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: intermediary-fabric-loader-0.11.6-1.17.1.jar
 - fabric-api-0.40.1+1.17.jar

**Logs**
https://pastebin.com/EkV3C9Va

**Additional context**
[Mods config folder.zip](https://github.com/TechReborn/TechReborn/files/7187307/Mods.config.folder.zip)
[Minecraft_world_NewAge7.zip](https://github.com/TechReborn/TechReborn/files/7187329/Minecraft_world_NewAge7.zip)

**Comment by justinvvitale** [comment]
Are you sure this is affecting furnaces? I can only see it happening with the grinder, nothing else.

**Comment by jusvit** [comment]
Upon further investigation, the issue is caused by the Energy Storage Upgrade in any upgradeable machine.

When you have a storage upgrade on the machine (40k energy), it saves to NBT but when it loads from NBT, the capacity is more than the standard machine (1K energy) can handle, and only gives (1K energy) instead of 40k energy expected due to storage upgrade.

@Technici4n  is this related to your changes from #2474

**Comment by MelchiorGaspar** [comment]
Thx for the reply @justinvvitale 
ooh ok, 
yes I do have energy storage upgrades in each machine...
and thx for your investigation of my map...

**Comment by Technici4n** [comment]
> @Technici4n is this related to your changes from #2474

Probably. Should be fixed by #2507.

**Comment by MelchiorGaspar** [comment]
Thx @justinvvitale and @Technici4n for getting this fixed quick..
I await the patched .jar release.. :D ^_^
