### ISSUE TITLE
[1.17.1] Crash when /tp away from Lightning Generator

### ISSUE THREAD

**Issue by kwpugh** [TechReborn/TechReborn#2509]
**Describe the bug**

Using aa /tp or other modded methods of teleport to leave an area with a placed Lightning Generator causes  the game to crash.

**Steps to Reproduce**

- Place  a lightning gene with a rod on top
- /tp several thousand blocks away
- crash

**Environment (please complete the following information with the version):**
- fabric-api-0.40.1+1.17.jar
- RebornCore-5.0.8-beta+build.111.jar
- TechReborn-5.0.8-beta+build.111.jar

**Logs**

https://paste.ee/p/QjGTe

**Comment by dizzyd** [comment]
Should be fixed in #2510
