### ISSUE TITLE
Some bugs with the machines progress bars

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#251]
See:
![2015-11-11_13 18 11 2](https://cloud.githubusercontent.com/assets/8685029/11092515/5ef58b40-8884-11e5-815f-c3e93fae7576.png)
![2015-11-11_13 18 17 2](https://cloud.githubusercontent.com/assets/8685029/11092516/5ef9e442-8884-11e5-9beb-a6327e28a5f6.png)
![2015-11-11_13 43 40 2](https://cloud.githubusercontent.com/assets/8685029/11092517/5efd8fde-8884-11e5-818e-f9bcc325e3b8.png)
TechReborn-0.5.6.977-universal
RebornCore-0.0.0.5-universal

**Comment by modmuss50** [comment]
This has been around since I added crafting machines, when I get the chance I will fix it.

**Comment by Xen1290** [comment]
Oh, didn't know that.

**Comment by Xen1290** [comment]
Thanks!
