### ISSUE TITLE
RetroGen is not working on TechReborn-5.0.8-beta+build.111

### ISSUE THREAD

**Issue by JacobErnst98** [TechReborn/TechReborn#2511]
**Describe the bug**
Ore generation on existing worlds is not working even in new chunks.
Ore generation works fine on new worlds.

**Steps to Reproduce**
- Create a world without the mod installed in the mods folder
- Install the mod
- No ore from the mod is underground

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/PhYRhtpF

**Comment by modmuss50** [comment]
Retro gen is not supported, sorry.
