### ISSUE TITLE
Impliement Upgrade slots

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#252]
This will allow the machines to accept power through the slots and take upgrades.

**Comment by Speiger** [comment]
Well there is a problem @modmuss50 IC2 Exp Upgrades and IC2 Classic upgrades are totally differend...

**Comment by modmuss50** [comment]
Is there an API or something that I can hook into?

**Comment by Speiger** [comment]
IC2 Classic has a API in the API area and Exp has a API in their sourceCode...
The could colide^^

**Comment by Speiger** [comment]
for classic:
https://github.com/TinyModularThings/IC2Classic/blob/master/src/main/java/ic2/api/item/IMachineUpgradeItem.java
https://github.com/TinyModularThings/IC2Classic/blob/master/src/main/java/ic2/api/tile/IMachine.java

**Comment by modmuss50** [comment]
With it being in the source code it could be hard for me to use. With yours I can use JTraits to add it to the class

**Comment by Speiger** [comment]
well with sourcecode i mean simply its not in the API. so you require IC2 Exp to have the class aviable...

**Comment by modmuss50** [comment]
I was trying not to do that, but it looks like I may have to

**Comment by modmuss50** [comment]
its not as simple as just implementing the class and it works? I need to write some code to handle the items?

**Comment by Speiger** [comment]
Well actuall it is... But with Exp you have the problem that you can not detect it easy with @Optional

**Comment by Speiger** [comment]
So you have to implement these interfaces and have to be sure that Exp is installed.... (For machines and ItemUpgrades)

If you want to make that machines get supportet you have to simply check the upgrade slots and calculate the numbers. you do not have to support every function but that what you want to support. (onInstalling (classic only i think) and onTick should be supported)

**Comment by modmuss50** [comment]
Ok, that doesn't sound too bad. Thanks for the help

**Comment by Speiger** [comment]
only problem you will have if you support Exp then you need Special external TileEntites because @Optional is not working for Exp... So you can not remove the Interface from Your machines if you support Exp (only if you do it yourself). Other way around it is possible

**Comment by modmuss50** [comment]
Ive got away round that issue.

**Comment by Speiger** [comment]
cool

**Comment by gigabit101** [comment]
Might have to use are own till Ic2 gets to 1.8.9
