### ISSUE TITLE
Request : Release the assembler as a separate mod

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#253]
I am making a separate light pack without huge mods ( TechReborn, AE, etc.. ) that uses only light mods of my pack, small problem, I really need the assembler from TechReborn xD
May you branch out as a separate IC2 addon ? Kinda like the Quantum Storage mod ?

( PS : I would be grateful if this mod also included 1 or 2 more machines like a single block EBF xD Because I desperately need only those machines, kinda like very old GT when it had only a few machines, but this is purely optionnal )

**Comment by modmuss50** [comment]
Sorry but its not happening, the machine shouldn't even be in here but it is.

**Comment by Carbon-Ghost** [comment]
That's why I requested that as a branched out mod xD I am not sure how to port it myself without borking it,... I may "try" this week-end if you really can't but I fear doing something very wrong xD ( last time I did eclipse, I mutilated EE3 ).

**Comment by gigabit101** [comment]
well its in Tachreborn there is no recipe that  it for the pack maker to do
