### ISSUE TITLE
Uncomplication Crash, and tool tip not visable

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#254]
As title says.
TechReborn-0.5.6.995-universal
RebornCore-0.0.0.7-universal

**Comment by modmuss50** [comment]
Turns out it crashes: https://gist.github.com/modmuss50/07d46a6aa48d33eaf1d3

Not something I can fix

**Comment by modmuss50** [comment]
Waiting on: https://bitbucket.org/Aroma1997/uncomplication/issues/9/crash-with-techreborn

**Comment by Xen1290** [comment]
Oh, ok. For security, @Aroma1997

**Comment by Speiger** [comment]
@modmuss50 simply he requires to cancle it that the Exp Enet does not send the energy. The Classic enet is there to override it. Thats why the cancle Event...

**Comment by Xen1290** [comment]
Seems aroma fixed the issue @modmuss50 
https://bitbucket.org/Aroma1997/uncomplication/issues/9/crash-with-techreborn

**Comment by Aroma1997** [comment]
It was never broken...

**Comment by Xen1290** [comment]
I got another crash: @Aroma1997 @modmuss50 
https://gist.github.com/Xen1290/27c7cd470ebe13c2a071
Aroma1997Core-1.7.10-1.0.2.16
industrialcraft-2-2.2.793-experimental
Uncomplication-1.7.10-0.1.2.1.b58
RebornCore-1.0.0.9-universal
TechReborn-0.6.0.1015-universal

**Comment by modmuss50** [comment]
Seams like the same crash that I was having with the cables, I think @Aroma1997 had an attempt at fixing it, So try the latest version of Uncomplication.

**Comment by Xen1290** [comment]
@modmuss50 I'm using the latest version.

**Comment by Aroma1997** [comment]
@Xen1290 no, you're not uding the latest version. The latest version is .b59

**Comment by Xen1290** [comment]
Now yes, yesterday the latest version was b58. I'll try if this is fixed.

**Comment by modmuss50** [comment]
The crash is fixed. and I cannot see an easy way for walia to get client side only data.

**Comment by Xen1290** [comment]
Yes, fixed with b59

**Comment by Aroma1997** [comment]
And what was the thing with the tooltip?

**Comment by modmuss50** [comment]
I thought it was possible to show the amount of power in a machine in walia easily. It wasn't. So I couldn't fix it. It was nothing to do with your mod.
