### ISSUE TITLE
Can't find recipes for making liquids

### ISSUE THREAD

**Issue by imcasper** [TechReborn/TechReborn#2545]
I honestly doubt if this is a bug.
And whether it refers to this mod, or to the mod of help.
And whether it should work as intended by the authors:

**Can't find recipes for making liquids.**
- there are some recipes with capsules.
- poking the liquid does not open the recipe.
- it is also possible that the translations do not match for entity "liquid"  and for entity "capsule-with-liquid" with them.
- and may be fixed at last version

At least I'll be glad to know if it's a bug. And from whose side (you need to fix  or implement the feature)

**version**
TechReborn-1.16-3.8.4+build.236.jar

**Comment by drcrazy** [comment]
Dunno if vanilla can even do it with cell content being NBT and vanilla doesn't support NBT crafting.

Meanwhile, REI do it properly
![image](https://user-images.githubusercontent.com/1382352/134259328-ea869c3e-0127-4a7e-b1f3-4cf3d0f76d84.png)

**Comment by imcasper** [comment]
As I already wrote, the problem is probably related to the translation:
For example, I have a capsule with "mercury" and a liquid "ртуть" (mercury) 
And cant find recipes for "ртуть"

**Comment by drcrazy** [comment]
Переоткрыл. Гляну.

**Comment by shanoaice** [comment]
I am having similar problems here (using Chinese Translations), so this seemd to be related to translations? If this is the case maybe the trouble is at REI's side.

**Comment by shanoaice** [comment]
Tried to disable translations, yet still don't work. Recipies are totally wrong, whereas some usage is correct, some is not. Not sure whether it's REI's problem or Tech Reborn's problem.

**Comment by drcrazy** [comment]
It's not about translations. It's about how REI handle NBT items. Cells store fluids in NBT thus all cell are equal to REI
