### ISSUE TITLE
Missing ruby/sapphire tool recipes

### ISSUE THREAD

**Issue by arslan2012** [TechReborn/TechReborn#2556]
**Describe the bug**
Can't make ruby/sapphire sword axe etc.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Modpack: All of Fabric 4 0.0.9
 - Mod Loader: fabric 0.11.6
 - TechReborn-5.0.5-beta+build.85.jar

**Comment by Vapaman** [comment]
All of Fabric could have disabled those recipes intentionally. Also it is using an outdated version of the mod.

**Comment by Technici4n** [comment]
Yes, disabled by AOF4.
