### ISSUE TITLE
Creative Tank Unit Input/Input Crash

### ISSUE THREAD

**Issue by Frankiscophil** [TechReborn/TechReborn#2558]
**Describe the bug**
A crash caused by a Creative Tank Unit and Quantum Tank Unit set to Input next to each other. Sends you back to the Minecraft Launcher and keeps you from entering the world in which the crash happened.

**Steps to Reproduce**
- Place Creative Tank Unit and Quantum Tank Unit besides one another.
- Set the touching faces of both Tank Units to Fluid Input.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/DcMryAW8

**Comment by drcrazy** [comment]
Can't reproduce in dev env. 

Can you try with TR only, please?

Tank units:
![image](https://user-images.githubusercontent.com/1382352/136288133-ef9933da-d1be-45db-86a3-23f0ae1bc245.png)

Fluid i\o  for creative tank:
![image](https://user-images.githubusercontent.com/1382352/136288171-f848da21-04ea-4814-8234-9d26348ddf7e.png)

Fluid I\O for quantum tank:
![image](https://user-images.githubusercontent.com/1382352/136288235-5e077e68-894b-48d7-aee6-a2430b3bbdd0.png)
