### ISSUE TITLE
Charge Bench doesn't work

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#256]
![2015-11-12_15 23 02](https://cloud.githubusercontent.com/assets/8685029/11121406/fb8c43be-8955-11e5-985c-c5a4de5f9736.png)
This bench is connected to a power source.
TechReborn-0.5.6.995-universal
RebornCore-0.0.0.7-universal

**Comment by modmuss50** [comment]
@gigabit101 for charge bench, chunk loader is not added yet

**Comment by Xen1290** [comment]
Oh, didn't know that, sorry. I'll move Industrial Chunkloader to Machines not implement issues

**Comment by gigabit101** [comment]
Needs to moved to Techreborn addons anyway as not part of greg tech

**Comment by modmuss50** [comment]
It could have broken when I recoded the item power api

**Comment by modmuss50** [comment]
Very easy fix: https://github.com/TechReborn/TechReborn/commit/61a600713a7470e72f019c23ce5f70cc9c1c939c

**Comment by Xen1290** [comment]
Thanks!
