### ISSUE TITLE
Grinder grinds on nothing, cycling forever.

### ISSUE THREAD

**Issue by jangro** [TechReborn/TechReborn#2563]
**Describe the bug**
Grinder cycles on nothing after updating to the lastest version, 5.0.8-beta+build.111

**Steps to Reproduce**
This just happens with my grinder which existed before the update. If I break it and place it again, it still happens. 

**Screenshots**
![techreborn grinder grinds](https://user-images.githubusercontent.com/156739/136032013-bdad672c-1b7a-446c-9461-2df1d8c1c9b0.jpg)
Someone also posted a video in discord.

**Environment (please complete the following information with the version):**
Minecraft 1.17 
Fabric
Valhelsia Fabric Modpack 1.0.8

**Comment by drcrazy** [comment]
Can't reproduce in dev 

![image](https://user-images.githubusercontent.com/1382352/136286197-453b3dc5-3d90-43de-b995-c730f76d61f0.png)

**Comment by jangro** [comment]
Someone over on the Valhelsia discord says that removing Applied Energistics 2 resolves it. 
It's true that AE2 was added in the most recent version of Valhelsia Fabric, so that makes sense.

**Comment by Technici4n** [comment]
Might be the certus quartz tag change. We should probably investigate more because it clearly is a grinder bug. The invalid recipe should just not have been loaded at all.

**Comment by drcrazy** [comment]
I think we can release next version in a couple of days and check if it will fix the issue. @Technici4n what do you think?
