### ISSUE TITLE
IDSU is broken

### ISSUE THREAD

**Issue by FV214Hardiel** [TechReborn/TechReborn#2569]
**Describe the bug**
1) IDSU energy display doesnt work
2) 2 IDSU dont share energy

**Steps to Reproduce**
- Launch solo world
- Place IDSU
- Place charged battery to right
- Look at display
- Place second IDSU
- Try to charge another empty battery
- No energy
- Dismount first IDSU with wrench
- Place again
- Try to charge something
- No energy

**Video**
https://drive.google.com/file/d/1GNWjIo8GhKXeRpUf6hfUEU1tL9HTjRj3/view?usp=sharing

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric
 - Mods: no mods except Fabric API 0.40.1, Cloth Fabric Config 5.0.38, Fabric Language Scala 1.1.0 and TechReborn 5.0.9

**Additional context**
Charged IDSU also lose charge after re-entering the world

**Comment by modmuss50** [comment]
Seems to have been broken when moving over to the new energy api.
