### ISSUE TITLE
Game crashes when attempting to change battery box sides.

### ISSUE THREAD

**Issue by JakeYde** [TechReborn/TechReborn#2575]
**Describe the bug**
Was investigating configuring sides of the battery box as outputs when the game crashed.

**Steps to Reproduce**
- Place Battery Box
- Open Battery Box GUI
- Click configure slots.
- Change right side repeatedly

**Screenshots**
None

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric 0.11.7-1.17.1

**Logs**
https://pastebin.com/DZf3qmim

**Additional context**

**Comment by modmuss50** [comment]
Doesnt appear to be techreborn:
`svenhjol.charm.module.lava_bucket_destroys_items.LavaBucketDestroysItems.handleStackedItem`
