### ISSUE TITLE
Fluids don't render in containers

### ISSUE THREAD

**Issue by SplendidAlakey** [TechReborn/TechReborn#2576]
**Describe the bug:**

Whenever any fluid is put inside a tank unit, it does not render.

**Steps to Reproduce:**

- Place any tank unit down
- Fill it with any fluid by any means (I used buckets)

**Screenshots:**

![2021-10-15_05 21 18](https://user-images.githubusercontent.com/86702831/137428158-ff14e047-b714-4f4d-a0c2-b11b1a99b614.png)

![2021-10-15_05 21 21](https://user-images.githubusercontent.com/86702831/137428170-dbba6b31-c042-467c-9b76-8876276a8b47.png)

**Environment (please complete the following information with the version):**

 - Minecraft: 1.17.1
 - Mod Loader: fabric 0.11.7 + fabric-api-0.40.8+1.17
 - Tech Reborn: TechReborn-5.0.9-beta+build.131

**Logs**

Pastebin the log [e.g. `logs/latest.log`] and link it below:

[removed]

**Additional context**

Originally detected the issue with Industrial Revolution [here](https://github.com/GabrielOlvH/Industrial-Revolution/issues/330) then discovered that it happens with all industrial mods I use. In case of Industrial Revolution, only lava renders inside fluid containers. In case of Tech Reborn, no fluids render at all. Tested all mods separately to exclude the possibility of an incompatibility between them.

Update: I figured out the issue, it only happens of "Fabulous!" graphics settings for other mods, but for this one it's the same on all settings. If I'm just being stupid and that little window isn't even supposed to fill with water, then close this issue. If it is supposed to fill up, then the issue still persists on graphics settings other than "Fabulous!".

**Comment by drcrazy** [comment]
These slots are for fluid containers, not for fluids.

![image](https://user-images.githubusercontent.com/1382352/138414565-fe839f22-a909-41e7-a58d-4fe0410b9de4.png)
