### ISSUE TITLE
[Mod interaction] Storage units only expose the output stack to AE2 storage bus

### ISSUE THREAD

**Issue by Starjumper2821** [TechReborn/TechReborn#2579]
**Describe the bug**
An AE2 storage bus pointing into any of the storage units of Tech Reborn will only show up to a stack of the items in the storage system. This also restricts the amount of items that can be extracted at one time, especially for autocrafting.

**Comment by xanthian** [comment]
can confirm
![image](https://user-images.githubusercontent.com/7688001/148702959-cb08b842-194c-4263-9303-b0086a7cdc23.png)
![image](https://user-images.githubusercontent.com/7688001/148702972-120cce7c-4a9a-44c9-9c73-58df0c98f91b.png)
