### ISSUE TITLE
Digital/Quantum chest and Quantum Tank are still bugged

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#258]
See:
![2015-11-12_15 35 48](https://cloud.githubusercontent.com/assets/8685029/11121584/01e635de-8957-11e5-984d-2dab9b5bf002.png)
![2015-11-12_15 36 24](https://cloud.githubusercontent.com/assets/8685029/11121586/035ef3f6-8957-11e5-8065-1c4dc6685662.png)
![2015-11-12_15 36 29](https://cloud.githubusercontent.com/assets/8685029/11121589/04733324-8957-11e5-9cad-082ed6fa9caa.png)
TechReborn-0.5.6.995-universal
RebornCore-0.0.0.7-universal

**Comment by gigabit101** [comment]
Will sort when I get home I derped as for tank I will take a look but I never worked on that b4

**Comment by gigabit101** [comment]
I cant get the stack to render to the side like in your pic

**Comment by gigabit101** [comment]
But I have fixed the stacking issue

**Comment by Xen1290** [comment]
I think you misunderstood, the stack on the right is my mouse, the screenshot doesn't show it. Sorry.

**Comment by modmuss50** [comment]
oh, so there is a fake item in the slot?

**Comment by Xen1290** [comment]
I think so, but i'm testing the latest version right now.

**Comment by Xen1290** [comment]
Tested, all things fixed, except that I can confirm that there is a fake item in the slot.
@modmuss50 @gigabit101

**Comment by gigabit101** [comment]
@modmuss50 maybe we should syncwithall onInventoryChange aswell

**Comment by modmuss50** [comment]
it could help

**Comment by Xen1290** [comment]
Thanks!
