### ISSUE TITLE
Crude Storage Unit bug

### ISSUE THREAD

**Issue by Fellal1** [TechReborn/TechReborn#2580]
**Describe the bug**

**Steps to Reproduce**
- First Step : put crude storage to another crude storage
- Second Step : repeat 7 times this 

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric-api-0.40.8+1.17

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: https://pastebin.com/3aE2G2sw

**Additional context**
https://www.youtube.com/watch?v=u4DvKbl2ywM&ab_channel=Volendam

**Comment by xanthian** [comment]
but why..
its probably too much to write to nbt.
a solution to this would be to prevent storage being placed in storage.
(and the wrench, cos thats annoying)

**Comment by Ayutac** [comment]
Still persists in 1.19.2, TR 5.3.4 standalone. Also seems to hold for other units.

> Tried to read NBT tag that was too big; tried to allocate: 2097153bytes where max allowed: 2097152
