### ISSUE TITLE
Modded Fluid Cells

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#2581]
**Describe the bug**
If fluids from other mods is stored in a cell, placing it in the world will place a missing block (pink/black) and supposed to be these fluids are not placeable if tried placing it with a bucket. 

Mods like Modern Industrialization, MI fluids are not placeable.

**Steps to Reproduce**
- Store Steam fluid (Steam Bucket) from MI in a Tank Unit
- Collect Steam from the Tank Unit with an empty cell
- Placing it in the world will place a Missing Block

**Screenshots**
![2021-10-21_08 38 56](https://user-images.githubusercontent.com/89919587/138191529-cfd482ca-1c3a-4aa9-99e2-91b5d1eab46a.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Additional**
- Maybe a a fluid blacklist config?

**Comment by drcrazy** [comment]
Fixed by 808f4e9c8614912c2253331415944ded9fa7f6da

![image](https://user-images.githubusercontent.com/1382352/147889619-15f934f5-db18-4036-8915-08ccc520dae2.png)
