### ISSUE TITLE
CTRL+Clicking items out of tech reborn machines causes the client to crash

### ISSUE THREAD

**Issue by AlienXAXS** [TechReborn/TechReborn#2586]
**Describe the bug**
Client crashes when you CTRL+Click items out of a Tech Reborn machines (Tried Grinder and Extractor)

**Steps to Reproduce**
- (This is in AoF4, if that helps)
- Place down a Grinder, with power
- Insert something to be processed
- Attempt to take the resulting product out of the grinder while holding CTRL
- Game crashes with Transfer variant may not be blank error

**Screenshots**
- None

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/TKR09H05

**Additional context**
techreborn: Tech Reborn 5.0.9-beta+build.131
AoF 4 1.0.1

**Comment by Technici4n** [comment]
Fixed in Fabric API 0.42.0.
