### ISSUE TITLE
Add a programer art style resource pack.

### ISSUE THREAD

**Issue by Colonizor48** [TechReborn/TechReborn#2587]
Title. i posted this is discussions but literally no one responded to it and mine is not unique in this regard.

**Comment by Colonizor48** [comment]
This wouldn't be that hard. Just pull textures from the 1.12 branch and add them to a resource pack. Maybe with a few modifications to make it work. for the majority of items which ave been around since 1.12.

**Comment by Technici4n** [comment]
Please keep the issues for bug reports and the discussions for feature requests. If others are interested, they can upvote and comment it.

**Comment by Technici4n** [comment]
On a side note, if you want to PR this addition, feel free. But I don't think this feature is a priority for the dev team given their limited time.
