### ISSUE TITLE
Empty fluids containers

### ISSUE THREAD

**Issue by ineyoff** [TechReborn/TechReborn#2589]
I just downloaded latest verision and saw that all fluids containers are empty
![image](https://user-images.githubusercontent.com/93547501/139723773-dbe47755-5358-4fb4-a408-a08cbb29e396.png)

 - Minecraft: 1.17.1
 - Mod Loader: fabric

[latest.log](https://github.com/TechReborn/TechReborn/files/7455474/latest.log)

**Comment by drcrazy** [comment]
Can you try without sodium@0.3.2+IRIS2-build.9, please?

**Comment by ineyoff** [comment]
Ok, thank you!

ср, 10 нояб. 2021 г., 15:58 drcrazy ***@***.***>:

**Comment by HammelGammel** [comment]
Chiming in here because I had the same issue. Without Sodium, the cells are displayed correctly, whereas with Sodium, they all appear the same as in the screenshot above. Using _Sodium mc1.17.1-0.3.2_ without Iris

**Comment by KySoto** [comment]
just curious, are you guys using [Indium](https://www.curseforge.com/minecraft/mc-mods/indium)?

**Comment by HammelGammel** [comment]
Not me, no

EDIT: oh, I'm dumb - using Indium fixes it. Thanks for pointing that out :)
