### ISSUE TITLE
Crash - Clicking wrong slot with coal

### ISSUE THREAD

**Issue by JBB0** [TechReborn/TechReborn#2590]
**Describe the bug**
Game crashes when clicking the bottom left slot with coal in a Generator.

**Steps to Reproduce**
- Craft a Generator
- Place Generator anywhere
- Open Generator GUI
- Click bottom left slot with coal

**Environment (please complete the following information with the version):**
- Minecraft: 1.17.1
- Modloader: Fabric 0.11.7
- Mod Version: 5.0.9

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[https://pastebin.com/Hncb4gJJ](url)
**Additional context**

Tech Reborn addon "Quarry Reborn" by TED_inc is installed, although I don't think this addon has anything to do with the crash.

**Comment by Technici4n** [comment]
Fixed in Fabric API 0.42.0.
