### ISSUE TITLE
missing deepslate ore processing recipes

### ISSUE THREAD

**Issue by urmet** [TechReborn/TechReborn#2594]
**Describe the bug**
playing with AE2 and TR, only certus quartz and gold have grinding recipes for deepslate variants of ores

**Steps to Reproduce**
- mine deepslate iron ore
- send it to your automated ore processing plant
- have everything _grind_ to a halt because there's no grinding recipe for deepslate iron ore

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric
 - TR: 5.0.10-beta

**Comment by drcrazy** [comment]
Should be fixed by 2fc685682693caffb492c32e0209d9e6d3d4f1bd
