### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by xxlio109** [TechReborn/TechReborn#2598]
**Describe the bug**
Crash Report

**Steps to Reproduce**
unknown 

**Screenshots**
unknown 
**Environment (please complete the following information with the version):**
 - Minecraft：1.17.1 
 - Modpacks： AQM2 [v2.9.5a] Hotfix

**Logs**
https://gist.github.com/xxlio109/d0fdd7c7226cacca4fd6ce402d908054

**Additional context**
nope

**Comment by Technici4n** [comment]
Indrev issue.
