### ISSUE TITLE
Crashing from Energy Crystals + ShulkerBoxlToolTip + Inmis

### ISSUE THREAD

**Issue by itsdinkd** [TechReborn/TechReborn#2599]
Storing Energy Crystals from TechReborn (and maybe other crystals too) inside an Inmis backpack, crashes the game when you try to see the preview of the contents inside it (Tries to render the energy Crystal's stored energy).

**SOLUTION**: temporarily disable Shulker Box Tooltips and take the crystals out.

**Crash Report**: https://paste.corebot.dev/najatecoqa.php

**Link to SBTT Issue**: https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/70

**Comment by Ayutac** [comment]
Looks like fun! I'll have a look at it

**Comment by Jigmag** [comment]
After looking at the crash logs and the mods involved (Tech Reborn, Shulker Box Tooltip, and Dank Storage) in my own instance of this issue it seems to be related to the Energy mod's SimpleBatteryItem issue here: https://github.com/TechReborn/Energy/issues/17

**Comment by Ayutac** [comment]
It is a bug in ShulkerBoxTooltips, as they ignore maxCount apparently. I'll try to fix it there.

**Comment by itsdinkd** [comment]
Closing due to Shulker dev pretty much deprioritizing to the point where he won't fix it.
