### ISSUE TITLE
"Pipe"-mod whitelist/blacklist not recognizing different fluid cells

### ISSUE THREAD

**Issue by HammelGammel** [TechReborn/TechReborn#2601]
**Describe the bug**
Not sure if this should go here or to the Pipe mod.

With the current version of Tech Reborn and the [Pipe mod](https://www.curseforge.com/minecraft/mc-mods/pipe), only one fluid cell can be added to the whitelist/blacklist of a servo. The servo then accepts/rejects any type of fluid cell, no matter which cell was added to the whitelist/blacklist.

**Steps to Reproduce**
- with the pipe mod installed, place a chest with at least two different types of fluid cells
- place another chest with at least one block of air inbetween. Leave it empty
- connect the chests with an Item Pipe
- place a servo on the chest containing the fluid cells
- right click the servo and add a fluid cell to the whitelist

result: all types of fluid cells will be pulled into the empty chest. Other fluid cells cannot be added to the whitelist/blacklist anymore.

**Environment:**
 - Minecraft: 1.17.1
 - Mod Loader: fabric
 - RebornCore-5.0.11-beta (stable release has the same issue)

**Comment by vixhentx** [comment]
just match nbt

**Comment by drcrazy** [comment]
It's a NBT issue. Besides NBT all cells are equal.
