### ISSUE TITLE
Unused item list

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2605]
You're probably already aware of this on some kind of roadmap out of beta, just in case here are a list of items that as it stands have no use, some of which are byproducts of existing manufacturing processes

//Cells+Fluids

- [ ] Carbon Fiber 
- [ ] Chlorite
- [ ] Nitrogen Dioxide

//Plates

- [x] Red Garnet
- [ ] Ruby
- [ ] Sapphire
- [x] Silver
- [x] Yellow Garnet
- [x] Zinc

//Dust

- [ ] Andesite
- [ ] Granite
- [ ] Manganese
- [ ] Olivine
- [ ] Phosphorous

MC 1.17.1
TR 5.0.11-beta

**Comment by modmuss50** [comment]
I don’t think this is really an issue. There is no use in removing them, they can also be useful for pack devs to create new recipes with.

Over time as features are added we can try to use them where it makes sense. As it stands I don’t think there is anything to be done here

**Comment by drcrazy** [comment]
Let's have it open for a while. I will think about usage for these. No promises

**Comment by DonFlymoor** [comment]
Her are my thoughts
2 Carbon Fiber Cell + Blast furnace -> Carbon Mesh
Chlorite + Sodium + Chemical reactor -> Sodium Chlorite
Sodium Chlorite + Dyed item + Chemical reactor -> undyed item
Nitrogen Dioxide + calcium + Chemical reactor -> Bone meal x 8
Nitrogen Dioxide + ash Chemical reactor -> gunpowder x 8

Any plate + wood -> Plated wood, as a building material

Andesite x 2 + cell -> silicon cell + basalt dust
Granite x 16 + Centrifuge -> Quartz (dust?) x 6 + Sodium + Calcium + Potassium (components off feldspar)
Manganese + dyed glass -> glass
Manganese + iron ingot + steel ingot = steel ingot x 2
Olivine can be used in place of sand in a blast furnace to smelt items down
Phosphorous + ashes / dark ashes x 8 = gunpowder x 9

**Comment by modmuss50** [comment]
Im personally not bothed by unused items, they are useful for pack devs.
