### ISSUE TITLE
Overclockers not increasing by 75%

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2606]
![image](https://user-images.githubusercontent.com/7688001/141517315-7acce0a6-4893-4876-9359-ec7d9c1a38db.png)

I may be misinterpreting this tooltip.
IF I'm understanding it correctly, it will increase the energy used per tick from whatever hidden value by 75%

However it seems it increases the maximum energy a machine can hold, by 100%
Before
![image](https://user-images.githubusercontent.com/7688001/141517552-ed97348c-75b3-4123-a1b6-a70c20409018.png)
After
![image](https://user-images.githubusercontent.com/7688001/141517574-838b56f7-71a0-4955-9191-f16485f39dcb.png)

Is is faster, and does seem to consume more energy
Adding more again adds a further 100% (of base) max energy.
eg. Industrial Blast Furnace goes from 40k base to 120k with 2 overclockers.

If this is intended, please consider adding this to the tooltip of the Overclocker.

MC 1.17.1
TR 5.0.11-beta

**Comment by urmet** [comment]
overclocker scaling is overall strange. jump between 3 overclocks and 4 overclocks is huge and 4 overclocks make it actually cheaper to run.

I did some testing some days ago, smelting stacks of cobble in an electric furnace
```
0 - 10m40 - 32E/t - 6.4kE/item
1 - 8m03 - 64E/t - 9.6kE/item - 1.33x faster than no overclock
2 - 5m24 - 128E/t - 13kE/item - 1.5x faster than 1 overclock, 2x of no overclock speed
3 - 2m43 - 256E/t - 12.8kE/item - 2x faster than 2 overclocks, 4x of no overclock speed
4 - 9.9s - 512E/t - 1.6kE/item - 16x faster than 3 overclocks, 64x of no overclock speed
```

**Comment by Ayutac** [comment]
> overclocker scaling is overall strange. jump between 3 overclocks and 4 overclocks is huge and 4 overclocks make it actually cheaper to run.
> 
> I did some testing some days ago, smelting stacks of cobble in an electric furnace
> 
> ```
> 0 - 10m40 - 32E/t - 6.4kE/item
> 1 - 8m03 - 64E/t - 9.6kE/item - 1.33x faster than no overclock
> 2 - 5m24 - 128E/t - 13kE/item - 1.5x faster than 1 overclock, 2x of no overclock speed
> 3 - 2m43 - 256E/t - 12.8kE/item - 2x faster than 2 overclocks, 4x of no overclock speed
> 4 - 9.9s - 512E/t - 1.6kE/item - 16x faster than 3 overclocks, 64x of no overclock speed
> ```

It decreases the time needed to smelt. So the first overclocker reduces to 75%, i.e. it is 1/0.75=1.33 times faster than no overclocker. With two the time is reduced to 50%, i.e. double as fast as without. And since 25 are a third of 75, it is 1/(2/3)=1.5 times as fast as with only one overclocker. The third overclocker reduces the time to 25% and as we know, 1/0.25 = 4. The fourth overclocker attempts to reduce the speed to 0% but that is unhealthy for the engine, so effectively it reduces the smelting of one item to one redstone tick. You think it is 64x as fast as no overclocker, but that is wrong because your furnace is *too fast*. If you try again with eg the centrifuge, you will notice one item is still reduced to one redstone tick.


I haven't paid attention to the maximum stored energy value though.

**Comment by xanthian** [comment]
We discussed this the other day..

Tooltip is missing 2 bits of information that leads to misunderstanding of the energy increase.

Each OC also adds
100% Base Maximum Energy eg.(1k > 2k > 3k > 4k)
100% Current Energy Input Rate  eg.(16 > 32 > 64 > 128)

Maybe worth while adding this info when Shift key is held down? 

However what was also noticed was in the config file the spelling of Overclocker is incorrect

 "upgrades": {
    "overclcoker_speed": {
      "comment": "Overclocker behavior speed multipiler",
      "value": 0.25
    },
    
  I have tried amending this and adjusting the value to silly levels but neither the corrected spelling or incorrect spelling seems to alter anything in game.

**Comment by verlixis** [comment]
> > overclocker scaling is overall strange. jump between 3 overclocks and 4 overclocks is huge and 4 overclocks make it actually cheaper to run.
> > I did some testing some days ago, smelting stacks of cobble in an electric furnace
> > ```
> > 0 - 10m40 - 32E/t - 6.4kE/item
> > 1 - 8m03 - 64E/t - 9.6kE/item - 1.33x faster than no overclock
> > 2 - 5m24 - 128E/t - 13kE/item - 1.5x faster than 1 overclock, 2x of no overclock speed
> > 3 - 2m43 - 256E/t - 12.8kE/item - 2x faster than 2 overclocks, 4x of no overclock speed
> > 4 - 9.9s - 512E/t - 1.6kE/item - 16x faster than 3 overclocks, 64x of no overclock speed
> > ```
> 
> It decreases the time needed to smelt. So the first overclocker reduces to 75%, i.e. it is 1/0.75=1.33 times faster than no overclocker. With two the time is reduced to 50%, i.e. double as fast as without. And since 25 are a third of 75, it is 1/(2/3)=1.5 times as fast as with only one overclocker. The third overclocker reduces the time to 25% and as we know, 1/0.25 = 4. The fourth overclocker attempts to reduce the speed to 0% but that is unhealthy for the engine, so effectively it reduces the smelting of one item to one redstone tick. You think it is 64x as fast as no overclocker, but that is wrong because your furnace is _too fast_. If you try again with eg the centrifuge, you will notice one item is still reduced to one redstone tick.
> 
> I haven't paid attention to the maximum stored energy value though.

I have another suggestion. Instead of trying to make the smelting speed scale linearly (and a discreet jump on the 4th over clocker), why don't make it stack multiplicatively?
For example:
![image](https://user-images.githubusercontent.com/79554816/155824889-50def4cb-0ff1-4d84-8eb6-ad9f07916593.png)

EDIT: I would also like to point out that block of ores have a longer smelting time than regular items, even with 3 Overclockers installed. Flattening it into 1 redstone tick in the 4th OC is kind of unfair.

**Comment by Ayutac** [comment]
disagree. Most stuff gets reduced to 1 tick in tier one machines, but middle tear machines still eat a lot of time. debuffing the overclocker is out of the question as fair as I am concerned.

**Comment by verlixis** [comment]
> disagree. Most stuff gets reduced to 1 tick in tier one machines, but middle tear machines still eat a lot of time. debuffing the overclocker is out of the question as fair as I am concerned.

Not necessarily a "debuff", more like a "rescale" if the overclocker's time reduction is also changed.

**Comment by SimonFlapse** [comment]
I would say that the Overclocker upgrade is far too unbalanced. It is pretty much only effective if using 4 overclocks, and then it makes the machine very cheap to run.

I propose looking into:

* The overclocking speed multiplier should be reworked
* The power multiplier should be greatly increased to match the tooltip (1 % increase of speed costs 3 % increase of energy used)
* Overclocker upgrades should not also work as Transformer upgrades and Energy Storage upgrades

**Comment by Ayutac** [comment]
> very cheap to run

*laughs in blast furnace*

also not the speed is increased, the time is decreased. Timelord technology

**Comment by SimonFlapse** [comment]
> > very cheap to run
> 
> _laughs in blast furnace_
> 
> also not the speed is increased, the time is decreased. Timelord technology

Fundamentally something is wrong, either in the logic, or in the text 😃
