### ISSUE TITLE
TR added ores easily mined with enchanted diamond shovel

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2609]
Nothing special about the shovel.
![image](https://user-images.githubusercontent.com/7688001/141679367-73cbb70a-d0c4-4cb9-baf8-424c9f1f8475.png)

Not using any mods that modify damage of tools or how they break things.

Tags seem correct on the ores, but they do indeed break as if using a pickaxe
![image](https://user-images.githubusercontent.com/7688001/141679538-fb4b6204-7886-4a0f-b29b-5e521e183294.png)

Poor screen cap of 6 different TR ores.
[screen-capture.zip](https://github.com/TechReborn/TechReborn/files/7533643/screen-capture.zip)

Doesn't do it on any other mods ore or vanilla.

MC 1.17.1
TR 5.0.11-beta

**Comment by xanthian** [comment]
To expand on this, it is actually ANY tool.
Sword, Hoe, Axe or Shovel

That is >= Iron level

This also includes all the TR added variants Bronze, Ruby, Peridot, Sapphire

**Comment by Shockks** [comment]
can confirm this issue still exists, im in game breaking TR ores and getting the raw ore drop with an iron sword right now

**Comment by equal-l2** [comment]
Oddly, deepslate variants are not affected.

**Comment by josilo** [comment]
> Oddly, deepslate variants are not affected.

Deepslate variants are not affected because they are missing **_mineable/pickaxe_** tag, and Drill mines them at wrong speed (isSuitable() returns false if the tag is missing), after adding the tags (#2650) they are also affected by this bug but drill mines them at correct speed. I'm investigating what is causing this bug.

**Comment by xanthian** [comment]
> > Oddly, deepslate variants are not affected.
> 
> Deepslate variants are not affected because they are missing **_mineable/pickaxe_** tag, and Drill mines them at wrong speed (isSuitable() returns false if the tag is missing), after adding the tags (#2650) they are also affected by this bug but drill mines them at correct speed. I'm investigating what is causing this bug.

I cannot figure it out, its bugged me for weeks, then again, I don't understand java, but I've amended a few bits to no avail.
