### ISSUE TITLE
See through covered cables

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2611]
**Describe the bug**
Invisible cable block from certain angles

**Steps to Reproduce**
Look at insulated cable that has been covered with wooden plate from certain angles, usually when placed against another block above

**Screenshots**
![image](https://user-images.githubusercontent.com/7688001/142068478-135865f3-ef43-450b-b2f3-74a41c3d384a.png)
![image](https://user-images.githubusercontent.com/7688001/142068744-8eb39be9-173d-441c-b355-2c8d50aa5cf3.png)

**Environment (please complete the following information with the version):**
MC 1.17.1
TR 5.0.11-beta
Fabric Launcher 0.12.5
Java 17 (GraalVM)

**Mod list**
![image](https://user-images.githubusercontent.com/7688001/142068793-690b9a51-c409-411d-9bc1-94df19aec25d.png)

**Comment by drcrazy** [comment]
Can't reproduce in dev env. Might be mod compat issue related to CIT or lithium.

![image](https://user-images.githubusercontent.com/1382352/183847957-2ff742e6-ef3e-4053-8cab-1ef852d26c26.png)
