### ISSUE TITLE
Some Tooltips too large for GUI scale 3 & 4 (1.18 pre4)

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2617]
Example
![image](https://user-images.githubusercontent.com/7688001/143664297-f8d4a5bf-3487-4414-bc36-65599ac04607.png)

Screen Resolution 1920x1080

List of machines with issue at scale 3 (when holding shift)

Vacuum Freezer
Lightning Rod
Drain
Windmill
Industrial Chunkloader

List of machines with issue at scale 4

All above +
Extractor
Implosion Compressor
Industrial Electrolyzer
Industrial Grinder
Iron Alloy Furnace
Solid Canning Machine
Recycler
Gas Turbine
Plasma Generator
Semi-Fluid Generator
Generator
Player Detector
All Iridium Reinforced Tungsteel items

worth noting that in some cases depending on the toolbar or bag slot the item is placed, it may display most if not all, but this is not ideal.

**Comment by drcrazy** [comment]
Vanilla issue. There are a number of mods like https://www.curseforge.com/minecraft/mc-mods/tooltipfix to fix it.
