### ISSUE TITLE
Chrome should be renamed to chromium (the correct English word)

### ISSUE THREAD

**Issue by Technici4n** [TechReborn/TechReborn#2621]
We'll rename it in MI for 1.18.

**Comment by drcrazy** [comment]
What chrome items should be chromium? It looks like 'Chrome stairs' is fine, while 'Block of Chrome' probably should be 'Block of Chromium'.

**Comment by xanthian** [comment]
I think it would cause more issues renaming it now, maybe for next patch 1.19?

But..
Nugget, Ingot, Small Dust, Dust, Block are the obvious ones.
Chrome Plate makes sense to leave as is although 'Chromium Plating' is an uncommonly used name for it.

Chrome Plated block, stairs, slab and wall would initially make sense, but as they are made with Chromium, they are not Chromed  
So all items really 🤣

Chrome is actually the name of product created by plating a metal with Chromium.

A few addendums..

Chromite (raw form of Chromium) should really be added as an Ore, as its technically not a by-product of anything
Processing of Chromite would produce Chromium and Iron.
Why it is pink

**Comment by Ayutac** [comment]
Renaming would happen in the lang file, there would be no other issued I could foresee rn

**Comment by xanthian** [comment]
that would make sense lol
other points stand.

**Comment by xanthian** [comment]
draft PR in for this if its wanted.
#2780

**Comment by Ayutac** [comment]
Solved by #2795
