### ISSUE TITLE
Generators Feedback / Inconsistencies

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2622]
Tested all the Generators in 1.18 using superconductor cable output to a Matter Fabricator (2k input)
I found that some of the expected output rates do not match up, and the charge rates on some are well below par.

In addition it would be great to add charge rate to item descriptions.
Below I'll list my findings and annotate any that I believe are incorrect in regards to the description.

### Fluid Gens

**Generator**
Charge Rate 10 E/t 
Time taken to fully charge = 50 sec
Output Rate 32 E
Time taken to empty when not charging = 22 sec
Time taken to empty when charging = 15 sec
Ratio 16:5
_Basic Gen, seems reasonably balanced for early game, if not a little underwhelming_

**Diesel Generator**
Charge Rate 20 E/t 
Time taken to fully charge = 25 sec
Output Rate 32 E
Time taken to empty when not charging = 22 sec
Time taken to empty when charging = 41 sec
Ratio 8:5
_Progression from basic gen, however the fuels are far harder to come by than some of the higher tier gen_ 
Diesel production requires Oil, Oil is used in the SF Generator, which is higher tier
Producing Diesel is 20 E/t + 5 E/t from Oil production nearly renders this generator useless._

**Gas Turbine**
Charge Rate 16 E/t
Time Taken to fully charge = 52 minutes
Output Rate  128 E
Time taken to empty when not charging = 6min 30 sec
Time taken to empty when charging = 7min 26 sec
Ratio 8:1 
_The charge rate is far too low for this machine to be considered useful for anything other than backup
Given that it costs 10 E/t to generate Methane, this machine is only worth 6 E/t_

**Semi Fluid Generator**
Charge Rate 8 E/t
Time Taken to fully charge = 1 hour 44 minutes!!
Output Rate  128 E
Time taken to empty when not charging = 6min 30 sec
Time taken to empty when charging = 6 min 56 sec
Ratio 16:1 
_This machine is just plain awful, needs some tweaks to charge rate
Costs 5 E/t to generate Oil, this machine then only outputs 3 E/t_

**Thermal Generator**
Charge Rate 16 E/t
Time Taken to fully charge = 52 minutes!!
Output Rate  128 E
Time taken to empty when not charging = 6min 30 sec
Time taken to empty when charging = 7min 26 sec
Ratio 8:1 
_Identical to Gas Turbine, Lava is far easier to come by so I would expect this to be somewhat 'nerfed' in comparison, but as per previous 2, charge rate is just too low_

**Plasma Generator**
Charge Rate 400 E/t
Time Taken to fully charge = 17 hours 21 minutes!! _(this just seems insane)_
Output Rate  2000 E
Time taken to empty when not charging = 3 hours 28 mins
Time taken to empty when charging = 4 hours 20 mins 
Ratio 5:1 
_Probably the best of the lot, explained by the Extreme tier granted to it_

_Seem to be missing a bridge machine between Medium & Extreme tiers, maybe consider changing one of the existing machines or adding another to fill this gap
The generation rates on all machines are simply too low to compete with the passive gens below_

### Passive Gens

**Dragon Egg Siphon**
Output Rate  128 E 
Charge Rate 4 E/t
_Storage seems to be higher than 1k, more like 12.5k_
 _No interface, unable to see when full_
_As a early mid game passive generator it should be a little higher_

**Water Mill*
Output rate 32 E 
Charge Rate 0.1
_As above , 0.1 E/t seems very low, pretty much useless unless you have 100's_
_No interface, unable to see when full_

**Wind Mill**
Output Rate  128 E 
Charge Rate 2 E/t
 _No interface, unable to see when full_
_Storage seems to be higher than 10k, more like 15k_

**Basic Solar Panel**
Charge Rate 3 E

**Advanced Solar Panel**
Charge Rate 12 E

**Industrial Solar Panel**
Charge Rate 21 E

**Ultimate Solar Panel**
Charge Rate 48 E

**Quantum Solar Panel**
Charge Rate 512 E

_The charge rate of the Solar panels seems to ramp up/down during the day/night cycle only hitting peak generation at noon where it then immediately starts to fall, seems logical, but unsure if intended.
These are incredibly powerful and I would probably consider them a bit OP
Values listed on the wiki also do not match in game_

**Comment by xanthian** [comment]
Edit..

just noticed the extreme cost for the Dragon Egg Siphon.. I take back my comment about it being "early mid game"
😲

**Comment by BernardoGrigiastro** [comment]
DONT TOUCH "MY" SOLARS!!!! 😡 :rage4:  unless its to make it more powerful!

Agree on everything else

**Comment by Ayutac** [comment]
Ah yes, Lava gen cannot power a centrifuge live, big sadness

**Comment by xanthian** [comment]
I know this can be changed locally, but a lot of people don't know that and don't like to mess with the mod's intended balance.

So my suggestions (so far part 1/4)

**Generator.**
Leave it.

**Diesel Gen**
Centrifuge requires 5e/t to make Oil, Distillation Tower costs 20e/t to turn that to Diesel
This gen needs to be able to produce 25e/t to even power the 2 machines used to produce the fuel.
Given it only converts Diesel at the rate of 20e/t its net -5e/t so cant be used to power anything else.
Bump the generation rate to parity 1:1 and increase the stored power capacity

**Gas Turbine**
As it stands this is pretty useless.
Generation rate should be at least 32, if not 64, you can then restrict the output via lower tier cables.
It will use up fluid faster than a centrifuge (or 2 can actually generate it - unless you overclock them, at which point they run out of power anyway!!)

**Comment by drcrazy** [comment]
E\t is not so useful to calculate net gain from processing. Because it doesn't count E\Mb of fuel.

### Diesel Generator ###
Distillation tower will spent 8K Energy to produce 16 Diesel cells. This gives us 500E spent per cell.
Diesel generator will generate 128E per mB of diesel so one cell will give 128k energy. 
Net gain for Diesel is 127.5k energy per cell while Oil will give 16E\mB in semifluid generator with 16k energy per cell. 

Thus processing oil will give a huge boost in energy gain from a cell of a liquid.

### Gas turbine ###
Gas turbine will produce 45E\mB of Methan so one cell will give you 45k Energy per cell
Industrial Centrifuge will spend 25k on producing single Methan cell
Overall net gain is 20k Energy per cell

It looks like we can decrease time to make a methan cell, thus net gain for Gas turbine will be higher

**Comment by drcrazy** [comment]
E\t difference between generation and consumption should be balanced by energy storages. 1..n generators should supply power to energy storage and can do that in advance. Then some machine connected to energy storage output will use energy from it rather then from generator directly,
