### ISSUE TITLE
No icon on the Scrapbox REI tab

### ISSUE THREAD

**Issue by BernardoGrigiastro** [TechReborn/TechReborn#2625]
No icon on the Scrapbox REI tab

Fabric 1.18-rc4
TR 5.1.0 b2

same thing on earlier 1.18 versions of both ^^

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/144090456-226b53b2-6869-48fa-99c5-199bb1a52c32.png)

**Comment by xanthian** [comment]
I  see why. But think its beyond my capability to fix it (tried looking in the mod files & folders, but I'm guessing its declared in one of the class files somewhere.
![image](https://user-images.githubusercontent.com/7688001/144146951-d881ac45-c0ae-4c8b-a15e-11e2b5999113.png)
✔
![image](https://user-images.githubusercontent.com/7688001/144146971-29ec6d05-3b80-4348-8900-1c3f37560f15.png)
❌

**Comment by Ayutac** [comment]
... explain?
![excerpt](https://user-images.githubusercontent.com/7873396/144465823-2e2f2683-e741-4927-a6f1-42852ad721b9.png)
Why do you have these weird (old?) metal plate textures?

I'm using latest mod snapshot and already changed it a bit, but that doesn't explain the different textures.

Or did I already fix by accident? I doubt it,

**Comment by xanthian** [comment]
ha, they are MI textures :)
think you broke it completely now, there is no tab at all!
removed MI to check, see this image.
![image](https://user-images.githubusercontent.com/7688001/144467407-a822ddd3-7444-4476-8abb-4e875d913e79.png)

**Comment by Ayutac** [comment]
Ah, I was in construction of Scrap-inator, not use of Scrap. Symbol is displayed, problem does not occur on head of Github version I think.

![excerpt](https://user-images.githubusercontent.com/7873396/144472849-586dc122-4510-42bb-93cf-4d0591a5755f.png)

**Comment by drcrazy** [comment]
Can't reproduce in dev. 

![image](https://user-images.githubusercontent.com/1382352/146688313-8e6fdf3e-7f68-4bbe-946b-686ce53f0ad1.png)

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/146688820-3cf9c03d-d664-48af-81e1-81af41504f18.png)
Still occurring for me on a version i just build from 1.18 master. 
🤷‍♂️

**Comment by BernardoGrigiastro** [comment]
same here

![2021-12-19_20 50 24](https://user-images.githubusercontent.com/47037877/146688885-b6084eea-55f8-4ce1-9119-6f480bc6aeca.png)

**Comment by Wolfy8198** [comment]
I have this issue as well

**Comment by xanthian** [comment]
this is so strange.. must be some other mod interfering..
build latest in dev as of commit [347117b](https://github.com/TechReborn/TechReborn/commit/347117b95acfbd15b544475413440cf4fef4d98c) it works fine,
if i launch on beta5 release, its not fine 🤷‍♂️

**Comment by Ayutac** [comment]
Funnily enough, the error has maybe nothing to do with the scrapbox/scrap_box inaccurancy I think. I changed all occurances to scrap_box and the error persists. I think I mostly tracked it down though (just ignore wrong _ in the following, as I debugged in my corrected code):

In line 117 of TR's ReiPlugin the icon is registered via TRContent.SCRAP_BOX. This is done during MC Startup.

What interests us is the renderer field of REI's TabWidget class. One can check that by breaking at TabWidget#render(...), which is called continuously when a recipe is viewed via REI.

The renderer field is not set at construction, but lazily when needed. Two classes make use of TabWidget#setRenderer(...), the one that breaks when trying to render the scrap box in the tab is REI's CompositeDisplayViewingScreen#init(). There we call TR's AbstractMachineCategory#getIcon().

That method then uses the initially set-up, static iconMap field in TR's ReiPlugin and feeds the corresponding  entry to REI's EntryStacks.of(...).

And now I have the icon. **_Wait, what?_** Yeah, the tab icon is definitely here... Let's test in Run. No icon, aha. Let's test in debug again. No icon. Cool.

Have fun with this. I swear the icon was there once. Will commit my stuff as "fixes sometimes"

**Comment by Ayutac** [comment]
On the other hand, I am *convinced* this is happening either because Scrap Box is not a block or because SCRAP_BOX is only a static field in TRContent instead of an enum entry like all the machines, because these are the only differences to the other tabs. 100% convinced this would work if we used the Scrapinator instead of Scrap Box as icon.

**Comment by drcrazy** [comment]
Do you have MI alongside with TR?

**Comment by Ayutac** [comment]
No, my mods folder in run is empty
