### ISSUE TITLE
REI GUI Overlap

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2626]
![image](https://user-images.githubusercontent.com/7688001/144131172-d3479903-d03b-48a5-8d28-2e954f3d72e9.png)

MC 1.17.1
Fabric 0.12.5
TR 5.0.11 beta
REI 6.2.335

**Comment by Coyote21** [comment]
+1
I have the same issue. I'm guessing its not a common issue or I would have expected more ppl reporting it.
Happens with any machine that uses the Config Slot GUI, not just the Industrial Grinder.

My system details are:

MC 1.18.2
Fabric 0.14.6
TR  5.2.0 (Same result when using 5.2.0 beta)
REI 8.2.463

Log files avail if required..
Separate Client and Server Machines

Server Installed Mods
	- achievement_plates 1.6.1
	- additionaladditions 4.0.3
	- adorn 3.4.0+1.18.2
	- advdebug 2.3.0
	- ae2 11.0.0
	- animal_feeding_trough 1.0.3+1.18.2
	- appleskin 2.4.0+mc1.18.2
	- architectury 4.4.61
	- artifacts 7.0.3+fabric
	- attributefix 14.0.1
	- autopath 1.4.9
	- badpackets 0.1.2
	- balm-fabric 3.0.0+0
	- basicshields 1.3.1-1.18.2
	- bclib 1.4.4
	- beaconoverhaul 1.6.0+1.18.2
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.0
	- bettermineshafts 1.18.2-Fabric-2.1.1
	- bettersleeping 0.5.1+1.18
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- blockus 2.4.5+1.18.2
	- bookshelf 13.0.13
	- bowinfinityfix rv11
	- cardinal-components 4.1.4
	- carrier 1.10.0
	- chalk 2.0.1+1.18.2
	- charm 4.1.0
	- chime 1.2.1
	- chiselsandbits 1.2.87
	- clienttweaks 7.1.0
	- cloth-api 3.2.64
	- cloth-config 6.2.62
	- collective-fabric 4.26
	- columns 1.4.0
	- comforts 1.1.2-1.18.2
	- companion 2.0.1
	- completeconfig 1.4.1
	- connectiblechains 2.1.1+1.18.2
	- craftingtweaks 13.0.0
	- crawl 0.10.6
	- darkpaintings 10.0.1
	- dehydration 1.2.8
	- despawningeggshatch-fabric 2.3
	- disenchanter 0.1.6+1.18
	- dragonloot 1.0.10
	- easyelytratakeoff-fabric 2.2
	- elytratrinket 3.0.0-1.18.1
	- enchantinginfuser 3.2.0
	- endportalrecipe-fabric 2.6
	- expandedstorage 7.3.12
	- extraalchemy 1.8.1
	- extractpoison-fabric 1.6
	- fabric 0.53.4+1.18.2
	- fabricloader 0.14.6
	- fabricshieldlib 1.5.3-1.18
	- farmersdelight 1.18.2-0.2.1
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- fishofthieves 1.0.5
	- flytre_lib 1.8.0
	- forgeconfigapiport 3.2.0
	- furnacerecycle-fabric 1.2
	- grindstonesharpertools-fabric 1.6
	- harvest_scythes 2.5.0
	- hookshot 25.0
	- horseinfo 0.4.1-1.18
	- iceberg 1.0.38
	- inmis 2.5.3-1.18.2
	- inventorysorter 1.8.6-1.18
	- java 17
	- justmobheads-fabric 5.4
	- kiwi 6.0.2
	- kubejs 1802.5.3-build.444
	- leaves_us_in_peace 1.0.4
	- levelz 1.3.1
	- lifts 1.4.1-BETA+1.18
	- lithium 0.7.9
	- mcwdoors 1.0.6
	- mcwwindows 2.0.3
	- megane 7.5.1
	- mo_glass 1.6.1-MC1.18.2
	- mobscarecrow 1.2.2
	- monsters_in_the_closet 1.0.3+1.18
	- nameplate 1.0.2
	- nbtcrafting 2.1.3+mc1.18.2
	- nears 1.1.8
	- ninjaphenix_container_lib 1.3.0
	- notenoughcrashes 4.1.6+1.18.2
	- oreprospectingstick 1.0.8
	- oxidized 1.6.4
	- patchouli 1.18.2-66-FABRIC
	- pehkui 3.3.1+1.14.4-1.19
	- phosphor 0.8.1
	- pipe 1.6.3
	- polymorph 0.0.21-1.18.2
	- puzzleslib 3.3.1
	- qcommon-cfg-core 3.3.0 via hctm-base
	- qcommon-croco 2.1.1 via hctm-base
	- reach-entity-attributes 2.1.1 via beaconoverhaul
	- reborncore 5.2.0
	- repurposed_structures 4.1.6+1.18.2
	- rhino 1802.1.13-build.175
	- roughlyenoughitems 8.2.463
	- roughlyenoughresources 2.5.0
	- rpgdifficulty 1.0.11
	- rswires 4.13.0
	- scannable 1.7.7
	- serverpause 1.1.0
	- shulkerdropstwo-fabric 1.8
	- silencemobs-fabric 2.0
	- smootherbedrock 1.0.4
	- spiceoffabric 1.5.2+1.18.2
	- staticdata 1.1.2 via static-content
	- techreborn 5.2.0
	- toolstats 9.0.1
	- tooltiprareness 1.0.3
	- tr-patchouli 1.1
	- trashslot 11.0.2
	- trinketofundying 2.0.1-1.18
	- trinkets 3.3.0
	- twigs 1.1.3-patch1+1.18.2
	- waystones 10.0.0
	- whereisit 1.14.10
	- wolveswitharmor 1.7.1-1.18.2
	- wthit 4.10.1
	- xaerominimap 22.8.1
	- xaeroworldmap 1.22.0
	- xp_storage 1.4.3+1.18
	- xtraarrows 1.8.3
	- xp_storage_trinkets 0.1+1.18
	- yungsapi 1.18.2-Fabric-2.0.8

Client Installed Mods
	3dskinlayers-fabric-1.4.3-mc1.18.2.jar
	achievementplates-1.18.2-1.6.1.jar
	AdditionalAdditions-4.0.3.jar
	Adorn-3.4.0+1.18.2-fabric.jar
	advancementinfo-1.18.2-fabric0.47.10-1.3.1.jar
	AdvancementPlaques-1.18-fabric-1.4.4.jar
	advdebug-2.3.0.jar
	animal_feeding_trough-1.0.3+1.18.2.jar
	appleskin-fabric-mc1.18.2-2.4.0.jar
	appliedenergistics2-11.0.0.jar
	architectury-4.4.61.jar
	artifacts-7.0.3+fabric.jar
	AttributeFix-Fabric-1.18.2-14.0.1.jar
	autopath-mc1.18.2-1.4.9.jar
	badpackets-fabric-0.1.2.jar
	balm-fabric-3.0.0+0.jar
	BasicShields-1.3.1-1.18.2.jar
	bclib-1.4.4.jar
	BeaconOverhaul-1.6.0+1.18.2.jar
	better-end-1.1.0.jar
	BetterF3-1.2.5-Fabric-1.18.2.jar
	bettersleeping-0.5.1+1.18.jar
	BetterThirdPerson-Fabric-1.18.2-1.7.3.jar
	blockus-2.4.5+1.18.2.jar
	Bookshelf-Fabric-1.18.2-13.0.13.jar
	borderless-mining-1.1.2+1.18.2.jar
	BowInfinityFix-1.18.x-fabric-rv11.jar
	brb-1.18.2-fabric-1.5.6.jar
	breakprogress-1.0.1.jar
	can-i-mine-this-block-1.2.0.jar
	cardinal-components-api-4.1.4.jar
	carrier-1.10.0.jar
	chalk-2.0.1+1.18.2.jar
	charm-fabric-1.18-4.1.0.jar
	charmonium-fabric-1.18-4.0.0.jar
	chime-1.2.1.jar
	ChiselsBits-fabric-1.18.2-1.2.87.jar
	CITResewn-1.0.1+1.18.2.jar
	CleanView-1.18.2-v1-fabric.jar
	ClearDespawn-fabric-1.18.2-1.1.7.jar
	clienttweaks-fabric-1.18.1-7.1.0.jar
	cloth-api-3.2.64.jar
	cloth-config-6.2.62-fabric.jar
	collective-fabric-1.18.x-4.26.jar
	columns-1.4.0.jar
	comforts-fabric-1.1.2-1.18.2.jar
	Companion-1.18.2-fabric-2.0.1.jar
	completeconfig-lib-1.4.1.jar
	connectiblechains-2.1.1+1.18.2.jar
	continuity-1.1.0+1.18.2.jar
	craftingtweaks-fabric-1.18-13.0.0.jar
	crawl-0.10.6.jar
	DarkPaintings-Fabric-1.18.2-10.0.1.jar
	dehydration-1.2.8.jar
	despawningeggshatch-fabric_1.18.x-2.3.jar
	disenchanter-0.1.6+1.18.jar
	dragonloot-1.0.10.jar
	easyelytratakeoff-fabric_1.18.x-2.2.jar
	elytratrinket-fabric-3.0.0-1.18.1.jar
	EnchantingInfuser-v3.2.0-1.18.2-Fabric.jar
	enchantment-lore-1.2.6-1+MC1.18-1.18.2.jar
	EnchantmentDescriptions-Fabric-1.18.2-10.0.2.jar
	endportalrecipe-fabric_1.18.x-2.6.jar
	enhanced_attack_indicator-1.0.3+1.18.jar
	EquipmentCompare-1.18.2-fabric-1.2.12.jar
	expandedstorage-7.3.12+1.18.2.jar
	extraalchemy-fabric-1.18.2-1.8.1.jar
	extractpoison-fabric_1.18.x-1.6.jar
	fabric-api-0.53.4+1.18.2.jar
	fabric-language-kotlin-1.7.4+kotlin.1.6.21.jar
	FabricShieldLib-1.5.3-1.18.jar
	fallingleaves-1.11.1+1.18.2.jar
	farmers-delight-fabric-0.2.1.jar
	farsight.fabric-1.18-1.9.jar
	feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
	fish_of_thieves-mc1.18.2-v1.0.5-fabric.jar
	flytre_lib-1.18.2-1.8.0-fabric.jar
	ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar
	furnacerecycle-fabric_1.18.x-1.2.jar
	grindstonesharpertools-fabric_1.18.x-1.6.jar
	HealthOverlay-1.18.1-6.0.1.jar
	hookshot-r25.jar
	hotbarcycle-1.0.2.jar
	hwyla-addon-horseinfo-0.4.1-1.18.jar
	Iceberg-1.18.2-fabric-1.0.38.jar
	indium-1.0.3+mc1.18.2.jar
	inmis-2.5.3-1.18.2.jar
	InventoryHUD-fabric-[1.18]+-3.4.2.jar
	InventorySorter-1.8.6-1.18.jar
	iris-mc1.18.2-1.2.4-build.38.jar
	jumpoverfences-1.16-0.0.3.jar
	justenoughkeys-0.5.3-fabric.jar
	justmobheads-fabric_1.18.x-5.4.jar
	keymap-0.3.2-beta.4+1.18.1-fabric.jar
	Kiwi-1.18.2-fabric-6.0.2.jar
	kubejs-fabric-1802.5.3-build.444.jar
	levelz-1.3.1.jar
	lifts-1.4.1-BETA+1.18.jar
	light-overlay-6.0.5.jar
	lithium-fabric-mc1.18.2-0.7.9.jar
	mcw-doors-1.0.6fabric-mc1.18.2.jar
	mcw-windows-2.0.3bfabric-mc1.18.2.jar
	megane-7.5.1.jar
	mineralchance-fabric_1.18.x-1.6.jar
	Mo-Glass-1.6.1-MC1.18.2.jar
	mobscarecrow-1.2.2.jar
	modmenu-3.2.1.jar
	Multiplayer-Server-Pause-1.18-Fabric-1.1.0.jar
	nameplate-1.0.2.jar
	nbtcrafting-2.1.3+mc1.18.2.jar
	nears-fabric-1.18-1.1.8.jar
	ninjaphenix-container-library-1.3.0+1.18-fabric.jar
	notenoughanimations-fabric-1.6.0-mc1.18.2.jar
	oreProspectingStick-Fabric-1.18.1-1.0.8.jar
	oxidized-1.6.4.jar
	Patchouli-1.18.2-66-FABRIC.jar
	Pehkui-3.3.1+1.14.4-1.19.jar
	pipe-1.18.2-1.6.3-fabric.jar
	polymorph-fabric-0.0.21-1.18.2.jar
	PuzzlesLib-v3.3.1-1.18.2-Fabric.jar
	RebornCore-5.2.0.jar
	reeses_sodium_options-mc1.18.2-1.4.2.jar
	removeblockoutline-1.1.1-1.18.2.jar
	repurposed_structures_fabric-4.1.6+1.18.2.jar
	rer-2.5.0.jar
	rhino-fabric-1802.1.13-build.175.jar
	RingOfAttraction-Fabric-1.18.2-1.2.24.jar
	RoughlyEnoughItems-8.2.463.jar
	rpgdifficulty-1.0.11.jar
	rswires-4.13.0.jar
	scannable-1.18.2-fabric-1.7.7+67bcbed.jar
	shulkerdropstwo-fabric_1.18.x-1.8.jar
	silencemobs-fabric_1.18.x-2.0.jar
	smootherbedrock-1.0.4.jar
	sodium-extra-mc1.18.2-0.4.3.jar
	sodium-fabric-mc1.18.2-0.4.1+build.15.jar
	spiceoffabric-1.5.2+1.18.2.jar
	spyglass-improvements-1.2+mc1.18.2+fabric.jar
	TechReborn-5.2.0.jar
	ToolStats-Fabric-1.18.2-9.0.1.jar
	tooltipfix-1.0.4-1.18.jar
	tooltiprareness-1.0.3.jar
	torohealth-1.18-fabric-2.jar
	tr-patchouli-1.1.jar
	trashslot-fabric-1.18.1-11.0.2.jar
	trinketofundying-fabric-2.0.1-1.18.jar
	trinkets-3.3.0.jar
	twigs-fabric-1.1.3-patch1+1.18.2.jar
	waystones-fabric-1.18.2-10.0.0.jar
	whereisit-1.18.2-1.14.10.jar
	wolves-with-armor-1.7.1-1.18.2.jar
	wraith-harvestscythes-2.5.0.jar
	wthit-fabric-4.10.2.jar
	XaerosWorldMap_1.22.0_Fabric_1.18.2.jar
	Xaeros_Minimap_22.8.1_Fabric_1.18.2.jar
	xpstorage_trinkets-0.1+1.18.jar
	xp_storage-1.4.3+1.18.jar
	Xtra+Arrows+Fabric+MC1.18.2+v1.8.3.jar
	YungsApi-1.18.2-Fabric-2.0.8.jar
	YungsBetterDungeons-1.18.2-Fabric-2.1.0.jar
	YungsBetterMineshafts-1.18.2-Fabric-2.1.1.jar
	YungsBetterStrongholds-1.18.2-Fabric-2.1.1.jar
