### ISSUE TITLE
[1.18] Rubber Trees not spawning due to enableOreGeneration

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2629]
**Describe the bug**
Rubber Trees do not spawn when enableOreGeneration = false

**Steps to Reproduce**
enableOreGeneration = false even tho having enableRubberTreeGeneration = true.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric

**Comment by modmuss50** [comment]
Fixed: https://github.com/TechReborn/TechReborn/commit/d7cb40ccbd206680d312311cd253ab577a57b5a9
