### ISSUE TITLE
Missing texture with standard machine casing.

### ISSUE THREAD

**Issue by Deckee** [TechReborn/TechReborn#263]
Techreborn: 0.5.6.1004
reborncore:1.0.0.9
forge:10.13.4.1558
ic2/3:2.2.2.791
  #  Enable Connected textures
    B:"Enable Connected textures"=false
![2015-11-12_22 39 56](https://cloud.githubusercontent.com/assets/8199121/11138944/ac85ef34-898e-11e5-8830-dce26ac8b0ae.png)

**Comment by Deckee** [comment]
make that all casings.
![2015-11-12_22 44 29](https://cloud.githubusercontent.com/assets/8199121/11138960/00b52b42-898f-11e5-891b-d127707f0e8b.png)

**Comment by modmuss50** [comment]
Ah ok thanks, its an issue when connected textures are disabled, I though this might happen.
