### ISSUE TITLE
Dependency remap error

### ISSUE THREAD

**Issue by PavloosCzM** [TechReborn/TechReborn#2630]
**Describe the bug**
Error in remaping Tech Reborn gradle dependency

**Steps to Reproduce**
- Download fabric-example-mod-1.18
- Add TechReborn to dependencies in build.gradle

**Logs**
https://pastebin.com/qS1SwurA

**Comment by Technici4n** [comment]
Loom issue when upgrading, if you delete your `.gradle` folder in your project it should be OK.

**Comment by PavloosCzM** [comment]
I try it, but not working, This issue is also reproducable when you download fabric-example-mod-1.18 where is no deps and code like i said in "Steps to Reproduce".

**Comment by drcrazy** [comment]
What loom version do you use?

What mc, yarn and loader version do you use?

**Comment by PavloosCzM** [comment]
Everything default from https://github.com/FabricMC/fabric-example-mod
Only Added TechReborn Dependency


# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.18
	yarn_mappings=1.18+build.1
	loader_version=0.12.6

# Mod Properties
	mod_version = 1.0.0
	maven_group = com.example
	archives_base_name = fabric-example-mod

# Dependencies
	fabric_version=0.43.1+1.18

**Comment by modmuss50** [comment]
You shouldnt be using the :universal jar, (im not even sure why its called) thats thats the none remapped dev jar.

**Comment by PavloosCzM** [comment]
Thx, i set it manualy and it works.
