### ISSUE TITLE
Lamps have lost their textures

### ISSUE THREAD

**Issue by Atyneton** [TechReborn/TechReborn#2632]
Lamps both LED and Incandescent have lost their texture

I am on the modpack "All of Fabric" version 0.1.4, last night in pack version 0.1.2 the lamps did have a texture.

![image](https://user-images.githubusercontent.com/48011255/144967381-80775da2-171b-4c53-be18-50e05e60bdd8.png)

**Comment by xanthian** [comment]
my fault, missed a comma in the particle fix, just submitted a PR to resolve.

if you really want it resolved now, you could pull the files out and whack them in to a resource pack

![image](https://user-images.githubusercontent.com/7688001/145005598-ea001e20-d32b-4b8e-a6d5-3c9057499295.png)
![image](https://user-images.githubusercontent.com/7688001/145005567-669a5be5-382c-4a27-8b02-4a5d3c5b32a6.png)
add a comma , after the 1st line under "textures": {
