### ISSUE TITLE
[1.18] Smelting/Blasting recipes not working.

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2633]
**Describe the bug**
Smelting/Blasting recipes not working for atleast Refined Iron Ingot & Advanced Alloy. It probably goes for all the ingots but I didnt have the time to test without AOF5 unification stuff.

**Steps to Reproduce**
- Just look the recipes up I guess?

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric

**Comment by modmuss50** [comment]
Fixed.
