### ISSUE TITLE
Industrial machines impossible to obtain.

### ISSUE THREAD

**Issue by luisbrandao** [TechReborn/TechReborn#2635]
1.18...

I need nickel and aluminum to make a blast furnace... and a blast furnace to get nickel and aluminum.... dafuk?

**Comment by Ayutac** [comment]
Not a bug. Put Raw Iron/Copper/Gold into the Industrial ~~Grinder~~ to obtain Nickel Nuggets. EDIT: I meant Industrial Centrifuge

More in-game documentation coming soonish.

**Comment by xanthian** [comment]
Install REI/JEI to see where you get these from.
Can also get them from Raw Iron/Gold/Copper in an Industrial Centrifuge.

**Comment by equal-l2** [comment]
Industrial Grinder requires steels to craft, so Industrial Centrifuge is the only route to obtain nickel before steel age?

**Comment by luisbrandao** [comment]
I figure it out... there was a recipe hidden in JEI* i didnt see.
You can make industrial centrifuge without aluminum (When i opened the issue, i saw only the recipe with aluminum)
I can get niquel bits from iron raw iron.
