### ISSUE TITLE
[1.17.1] Chainsaws don't work well with pumpkin

### ISSUE THREAD

**Issue by equal-l2** [TechReborn/TechReborn#2637]
**Describe the bug**
Breaking a pumpkin takes the same time with bare hands when using chainsaws.
EDIT: as @xanthian says, it works fine on trees.

**Steps to Reproduce**
Break a pumpkin with chainsaws.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric
 - Tech Reborn: `TechReborn-5.0.11-beta.jar`

**Comment by xanthian** [comment]
can confirm.
chainsaw does work fine on trees though 👍
(And TR ores 🤦‍♂️)

**Comment by equal-l2** [comment]
> (And TR ores 🤦‍♂️)

According to the WTHIT, swords are the correct tools for them actually.
