### ISSUE TITLE
Crash when trying to view centrifuge of raw iron in rei

### ISSUE THREAD

**Issue by Polarite** [TechReborn/TechReborn#2639]
**Describe the bug**
When trying to view centrifuge of raw iron from rei, game crashes

**Steps to Reproduce**
- Open game and load in a world
- Try to view centifuge of iron to get nickel

**Screenshots**
I got crash logs... cant ss that

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric 0.12.8
**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://paste.ee/p/iNYWR
https://paste.ee/p/YH6OZ
**Additional context**
I play on a server if that matters

**Comment by Polarite** [comment]
update: it also crashes on single player

**Comment by xanthian** [comment]
Likely REI issue, cannot replicate on my game (different mod set)

MC 1.17.1
TR 5.0.11 beta
REI - 6.2.347
![image](https://user-images.githubusercontent.com/7688001/145277401-c81143c9-17f3-4471-bfc0-fdf23388d4d8.png)

**Comment by Polarite** [comment]
try going from nickel nugget craftings too, thats how mine got crashed

**Comment by modmuss50** [comment]
This crash log does point towards it being an REI issue, I would also it report it with them.

**Comment by Polarite** [comment]
well, they said they will look up tomorrow, just wanted to give a heads up here too in case that might be TR side issue

**Comment by Polarite** [comment]
but thanks, will close issue tomorrow if its rei side issue

**Comment by xanthian** [comment]
> try going from nickel nugget craftings too, thats how mine got crashed

nope, all good.

**Comment by drcrazy** [comment]
It's on REI side according to the log
