### ISSUE TITLE
[1.18] Refined Iron Smelting recipe non existant 

### ISSUE THREAD

**Issue by itsdinkd** [TechReborn/TechReborn#2641]
On Another Quality Modpack v1.1, Iron -> Refined iron smelting recipe is not showing up. only shows up for blast furnance
https://pastebin.com/bcv9p00n 

![image](https://user-images.githubusercontent.com/35115304/145347907-ea799893-7503-49e8-a0f1-8d3eb861cf45.png)

![image](https://user-images.githubusercontent.com/35115304/145347930-394e0ddc-6003-4381-9a02-2f0e5645000d.png)

**Comment by itsdinkd** [comment]
Looks like all furnace recipes are broken

**Comment by xanthian** [comment]
Afaik resolved with beta 4.

**Comment by Technici4n** [comment]
Should be fixed, yeah.
