### ISSUE TITLE
No correct texture of cell and bucket with fluids

### ISSUE THREAD

**Issue by Vooxsu** [TechReborn/TechReborn#2645]
**Describe the bug**
Hi,
I have been playing Tech Reborn mod for several months and I found a small issue.
When i play without Iris and Soudium mods a textures be ok.

Pleas do not tel me uninstal this mod to fix an issue because i want more fps

It happens in REI, Inventory, and Creative Inventory

**Steps to Reproduce**
- install tech reborn mod
- install Iris and soudium mods
- Run game
- look at the cells and buckets with fluids

**Screenshots**
This in witch Iris and soudium instald.
![image](https://user-images.githubusercontent.com/82597391/145717935-f66f6062-e45b-4ded-83e9-f7d670aae8ea.png)
And this hapend when i'm uninstall Iris and soudium:
![image](https://user-images.githubusercontent.com/82597391/145718081-b5667d64-549f-426d-a948-15e22ebd55e2.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 100% in 1.17.1 and 1.18 and 1.18.1
 - Mod Loader: its hapend on ony version of mod louder i usd

**Comment by modmuss50** [comment]
The issue is with sodium and/or iris as they do not impliment the Fabric Rendering API that we used to render the dyamic cells, there is nothing that can be done on our end to fix it.

Sorry about that.

**Comment by Vooxsu** [comment]
ok thanks for quick response

**Comment by xanthian** [comment]
Fairly sure installing Indium fixes this?

**Comment by Vooxsu** [comment]
Yes, it fixes this problem.
Iris' support gave me this link to Indium. After installing Indium cell and buckets with fluids textures work good.
but this is alpha version.
https://modrinth.com/mod/indium/versions
