### ISSUE TITLE
Recipes are still registered also when the Ore doesn't exist

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#265]
...Continuation of https://github.com/TechReborn/TechReborn/issues/241
See here:
![2015-11-12_15 19 03 2](https://cloud.githubusercontent.com/assets/8685029/11121226/dfa518a2-8954-11e5-8d94-dd761e435b66.png)
![2015-11-12_15 47 53 2](https://cloud.githubusercontent.com/assets/8685029/11121228/e0a6d8b2-8954-11e5-9e80-e20ccf68dec8.png)
![2015-11-12_15 47 58 2](https://cloud.githubusercontent.com/assets/8685029/11121229/e16490fa-8954-11e5-9ef4-8aefc249e886.png)
RebornCore-1.0.0.9-universal
TechReborn-0.5.6.1006-universal

**Comment by gigabit101** [comment]
It dosn't matter u cant get them without the ore

**Comment by Xen1290** [comment]
Yes I know, but modmuss said that he can remove that useless recipe in #241

**Comment by gigabit101** [comment]
That will mean checking the oreDict on load for each recipe b4 adding them slowing the load time of the game

**Comment by modmuss50** [comment]
We do, I made a system to cache the ores. It should be a simple fix if you want it fixed. I see no reason not to have them.

**Comment by Xen1290** [comment]
I thought the same thing modmuss50

**Comment by Xen1290** [comment]
I think that fix this is better than how is now.

**Comment by gigabit101** [comment]
fine just fix it

**Comment by modmuss50** [comment]
Theres not reason to not have the recipes, you wont be able to use them without the the input.

**Comment by gigabit101** [comment]
I agree
