### ISSUE TITLE
Blast Furnace: Armor smelting ignores item damage 

### ISSUE THREAD

**Issue by LauchInterceptor** [TechReborn/TechReborn#2652]
**Describe the bug**
When smelting a piece of iron or gold armor in the blast furnace using sand, the respective amounts to craft this armorpiece are returned exactly no matter how much damage the item has. This enables cheesing the armor durability and always recrafting it before it breaks

**Steps to Reproduce**
- Put a damaged piece of Armor into a Blast Furnace together with a block of sand
- Observe the amount of ingots

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - TechReborn: 5.1.0-beta.4
 - Mod Loader: fabric

**Comment by xanthian** [comment]
Agreed, should be nuggets not ingots, similar to furnace returns

**Comment by Ayutac** [comment]
Disagree.

1. Blast furnace needs additional component (sand) to smelt them, so it's not free.
2. An almost broken chestplate still gives you the same protection. It is not like there are chunks missing, it is more like instable and full of dents, but there is hardly material loss if you get the same amount of protection
3. If you really put off 4 almost broken armor pieces, smelt them one after another, recraft them and put them on again, you deserve 0 damage on them. The amount of work involved is tremendous.

Maybe the amount of ingots could be reduced by 1 or 2, but replacing it with nuggets is out of the question. We are using a top tier smelter here, not some barely functioning stone furnace.

**Comment by xanthian** [comment]
Ok, maybe nuggets is a little 'stingy' what about..

Either reducing the amount returned by 1/4
so 
8 > 6
7 > 5
5 > 4
4 > 3

OR

Increase the heat requirements so they are tiered more, currently its 1000 heat for Iron, Gold and Diamond.

Could make it 1000 iron, 1500 gold, 2000 diamond
That way you would need to invest a bit more in to getting your returns.

Other line of thought is to move Diamond to the grinder as it doesn't really make much sense to 'smelt' it.

**Comment by Ayutac** [comment]
This has been addressed by #2893
