### ISSUE TITLE
MFE: Stores way less energy than expected

### ISSUE THREAD

**Issue by LauchInterceptor** [TechReborn/TechReborn#2653]
**Describe the bug**
The Medium Tier Multi-Functional Energy Storage Unit (MFE) is made up of 4 energy crystals each storing 1M energy units but only stores 300k energy units.

**Steps to Reproduce**
- Craft an MFE
- Feel cheated

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - TechReborn: 5.1.0-beta.4
 - Mod Loader: fabric

**Comment by LauchInterceptor** [comment]
I propose 5M storage for the mfe and 100M for the mfsu.
Any thoughts, also should there be config for that?

**Comment by joziahg** [comment]
I think the crystals/batteries should just be nerfed, going from 100k EU storage with lithium batteries to 1m with the energy crystals is a huge jump

**Comment by drcrazy** [comment]
Closed by 8dbab8f62e931a1376717337b0bfab66144d3c99
