### ISSUE TITLE
Wrong Harvest Levels?

### ISSUE THREAD

**Issue by itsdinkd** [TechReborn/TechReborn#2656]
For some reason its displaying the wrong harvest level in WTHIT on TR ore. 

Latest Fabic Loader | Latest TR Prod Release | 1.18.1

![image](https://user-images.githubusercontent.com/35115304/146650655-781d31d6-e47c-44bc-818f-932d4c882b41.png)

![image](https://user-images.githubusercontent.com/35115304/146650658-b1722f4c-1116-4e2b-98e3-a65c025d5c89.png)

**Comment by josilo** [comment]
This is related to #2609, and fixed with this PR #2654

**Comment by drcrazy** [comment]
PR merged. Should be fixed in dev as for now. Please, reopen if it is not.
