### ISSUE TITLE
Crash with Stacker mod

### ISSUE THREAD

**Issue by dathide** [TechReborn/TechReborn#2657]
**Describe the bug**
When Tech Reborn and [Stacker](https://github.com/Andrew6rant/Stacker) are both installed, the client crashes upon stacking any amount of red cell batteries.

**Steps to Reproduce**
- Install Tech Reborn and [Stacker](https://github.com/Andrew6rant/Stacker)
- Have 2 red cell batteries in inventory
- Combine them into a stack

**Environment**
 - Minecraft 1.17.1
 - Fabric Loader 0.12.12
 - Fabric API 0.44.0+1.17
 - Tech Reborn 5.0.11-beta
 - Stacker 2.1.0

**Logs**
[Pastebin](https://pastebin.com/RtnRKuDV)

**Comment by Ayutac** [comment]
Sounds like a Stacker problem. Or is it normal that you can stack tools? Does the problem also appear with drills and the like?

**Comment by dathide** [comment]
It might be an issue with Stacker. It doesn't allow the stacking of tools, but some things like water buckets can be stacked. I also created an issue on Stacker's github because I don't know which mod is causing the crash. I'm using Stacker and TR in a large modpack (All of Fabric 4), and this is the only item that has ever caused a crash. I haven't tested drills.

**Comment by xanthian** [comment]
Id argue it is stacker, as it is stacking things that shouldn't be stacked.
batteries have nbt data to report the battery charge status, similar to that of tools which also cant be stacked.

**Comment by xanthian** [comment]
not a TR issue.
