### ISSUE TITLE
Internal tank desync issue

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#266]
See:
![2015-11-13_15 19 42](https://cloud.githubusercontent.com/assets/8685029/11148734/d5e64852-8a1e-11e5-8566-6092862b90be.png)
![2015-11-13_15 19 47](https://cloud.githubusercontent.com/assets/8685029/11148736/db8ff276-8a1e-11e5-88fa-7ba94a665d9b.png)
I need to close an reopen the gui to fix this.

**Comment by Xen1290** [comment]
Why?

**Comment by modmuss50** [comment]
Was it fixed? If not its a bug

**Comment by gigabit101** [comment]
I can't reproduce
