### ISSUE TITLE
Modern Industrialization Compatibility

### ISSUE THREAD

**Issue by Wolfy8198** [TechReborn/TechReborn#2675]
Could you add compatibility for the machines from Modern Industrialization? The current cells that hold the "liquids" from Modern Industrialization don't do anything, and I would like to be able to use them to fill the machines, instead of carrying a ton of fuel/water buckets, and to take the end result "liquids" out of the machines. And if possible, could you make the energy compatible as well, since right now you can power stuff from Tech Reborn with Modern Industrialization machines, but not the other way around?

**Comment by Ayutac** [comment]
However that doesn't solve the energy conversion issue

**Comment by Technici4n** [comment]
> And if possible, could you make the energy compatible as well, since right now you can power stuff from Tech Reborn with Modern Industrialization machines, but not the other way around?

This is intended.

**Comment by Ayutac** [comment]
> > And if possible, could you make the energy compatible as well, since right now you can power stuff from Tech Reborn with Modern Industrialization machines, but not the other way around?
> 
> This is intended.

Can you elaborate for future reference?

**Comment by Technici4n** [comment]
Modern Industrialization uses a different power system (EU) that is only compatible one-way with the other mods' (E) for balance reasons.

**Comment by Wolfy8198** [comment]
Can you use cells to put the liquids into/take them out of Modern Industrialization machines now?

**Comment by Ayutac** [comment]
I only changed the placing of liquids in the world

**Comment by Wolfy8198** [comment]
Alright-

**Comment by elro444** [comment]
I think that keeping the balance is important, but maybe add a late game option for "importing" power from other mods?
Maybe having an "HV energy acceptor"?
I feel that this obligation should stay when you pretty much finish everything and just want to automate things

**Comment by Technici4n** [comment]
Then you can automate MI's own power generation? :smile:

**Comment by elro444** [comment]
It's not something critical by any means, but when you get to the stage in the game that you have billions of RF (or any other energy units), having to setup a Diesel Generator feels kinda off..
Totally makes sense you would need to go through steam generation etc., to get that "energy acceptor", so that you can't really skip the mod progression and balance. But once you did, personally I don't see the point of enforcing that balance.
Would understand if the dev's vision of the mod is different, but I think it could be a nice addition to the mod (:

**Comment by Technici4n** [comment]
> when you get to the stage in the game that you have billions of RF

And I believe that stage is too easy to reach which is the whole reason why MI has its own power system.
This has nothing to do with TR though - MI does its own thing on the side. I will add the option for MI to accept EU but it will be a config option designed for pack devs - up to people to use it responsibly. 😄

**Comment by elro444** [comment]
I honestly feel a little stupid now, as I didn't even notice we are on TR's repo. Whoops!
This discussion no doubt belongs to MI's issues.

In any case, your suggestion sounds like a great option!

**Comment by massdivide** [comment]
@Technici4n  That would be amazing. SkyFabrication 3 has no such option to convert "E" power into EU and a config option or a block would be awesome 👍

**Comment by Technici4n** [comment]
@massdivide The option will only be available in 1.19 I think. (for SkyFabrication 4? 😄)

**Comment by samuelh2005** [comment]
> And I believe that stage is too easy to reach which is the whole reason why MI has its own power system. This has nothing to do with TR though - MI does its own thing on the side. I will add the option for MI to accept EU but it will be a config option designed for pack devs - up to people to use it responsibly. 😄

@Technici4n Do you know what version of MI/Tech Reborn this feature will be in? I tried to modify TechReborn's `Selected Energy system` (found in `/config/reborncore/misc.json` on the server) to EU, but TechReborn's tooltips still show 'E' and doesn't transfer to MI (which uses EU)

**Comment by massdivide** [comment]
> > And I believe that stage is too easy to reach which is the whole reason why MI has its own power system. This has nothing to do with TR though - MI does its own thing on the side. I will add the option for MI to accept EU but it will be a config option designed for pack devs - up to people to use it responsibly. 😄
> 
> @Technici4n Do you know what version of MI/Tech Reborn this feature will be in? I tried to modify TechReborn's `Selected Energy system` (found in `/config/reborncore/misc.json` on the server) to EU, but TechReborn's tooltips still show 'E' and doesn't transfer to MI (which uses EU)


UPC allows to convert the energy already. https://www.curseforge.com/minecraft/mc-mods/upc

**Comment by XxARQxX** [comment]
Mystical Agriculture Refabricated is not compatible with Modern Industrialization.. Is there a way to fix this??

**Comment by drcrazy** [comment]
It is better ask MI devs ;-)

**Comment by Neu18** [comment]
> I think that keeping the balance is important, but maybe add a late game option for "importing" power from other mods? Maybe having an "HV energy acceptor"? I feel that this obligation should stay when you pretty much finish everything and just want to automate things

Thankyou so much, you really saved this mod life for me.
