### ISSUE TITLE
Missing crafting recipes for blocks or raw metal

### ISSUE THREAD

**Issue by Adirelle** [TechReborn/TechReborn#2681]
**Describe the bug**
There are recipes to smelt blocks of raw metal (tin, lead, silver) but there are no recipes to craft such blocks.

**Steps to Reproduce**
 - Open REI and look for raw tin block,
 - There is no recipe to craft it.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Tech Reborn : 5.1-beta
 - Mod Loader: fabric

**Comment by xanthian** [comment]
confirmed, using beta4.

**Comment by Adirelle** [comment]
By the way, they are smelting recipes, but not blasting ones. Is it intended or not ? And should I open another issue about it ?

**Comment by xanthian** [comment]
> By the way, they are smelting recipes, but not blasting ones. Is it intended or not ? And should I open another issue about it ?

?

**Comment by Adirelle** [comment]
There is no recipe to smelt blocks of raw metals using the vanilla [blast furnace](https://minecraft.fandom.com/wiki/Blast_Furnace).

**Comment by xanthian** [comment]
Only Iridium and Tungsten, this is likely intentional as a gate mechanism, as to smelt these you need to upgrade the Ind Blast Furnace somewhat

**Comment by xanthian** [comment]
oh nm, I see what you mean. (ignore previous now deleted post)

The Raw Blocks that currently don't work, 
Tin, Lead and Silver can be smelted using a Furnace in to a Block of .. from the Raw Block of..
![image](https://user-images.githubusercontent.com/7688001/147364682-081720c2-cb09-4f82-96d7-248fce454b1f.png)
![image](https://user-images.githubusercontent.com/7688001/147364691-10545c1a-f2a5-43e6-aff6-a0bd2e911c73.png)
![image](https://user-images.githubusercontent.com/7688001/147364730-470f0b23-9535-4073-b320-6c64be7514ce.png)


Iridium and Tungsten don't have this so I guess it can be added.
As you quite rightly pointed out, none of them have vanilla blast furnace recipes though, will leave that decision to devs.
