### ISSUE TITLE
Broken crafting recipe for Generator

### ISSUE THREAD

**Issue by Wolfy8198** [TechReborn/TechReborn#2686]
**Describe the bug**
The recipe in the REI for the generator is broken, as it includes an "air" item

**Steps to Reproduce**
- Open REI
- Check recipe for Generator
- Obtain required items
- Hover your mouse over the "move items" button

**Screenshots**
![Screenshot 2021-12-24 213558](https://user-images.githubusercontent.com/64490202/147376265-63be73b2-e578-4954-9faa-869f09b4364c.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric

**Comment by xanthian** [comment]
This looks more like an rei bug to me
The recipe looks fine in the code
![IMG_20211225_083325](https://user-images.githubusercontent.com/7688001/147381011-702b3482-9d3d-4895-8f7d-f53c2b83f6aa.jpg)

**Comment by drcrazy** [comment]
Can't reproduce in dev env. 

![image](https://user-images.githubusercontent.com/1382352/147889199-1b9723b4-267f-4239-96c0-f248f02aaa17.png)


With REI 7.1.356
