### ISSUE TITLE
The autocrafter is reset on restart

### ISSUE THREAD

**Issue by Adirelle** [TechReborn/TechReborn#2688]
**Describe the bug**
The autocrafter content and all configuration is lost on restart (e.g. when launching a world on solo).

**Steps to Reproduce**
- Create a solo world.
- Build a setup with a working autocrafter recipe, for example building chests from planks, pulling the planks from a barrel and storing the chest in another one (see the screenshots), and lock it.
- Exit the world.
- Enter the world again.
- Check the autocrafter : the recipe, the content and all configuration is gone.

**Screenshots**
* The setup:
![2021-12-27_19 09 30](https://user-images.githubusercontent.com/24633/147497405-5e85736e-4270-40f7-aac1-2c5e762ae3f8.png)
![2021-12-27_19 09 28](https://user-images.githubusercontent.com/24633/147497402-3ac0ae22-bfdf-45cb-b6a3-4afe9dd2389d.png)
* After reentering the world:
![2021-12-27_19 09 58](https://user-images.githubusercontent.com/24633/147497413-6842ff0e-6d04-49e2-b5ea-f1d1f28c7d9f.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric
 - TechReborn: 5.1.0-beta.4
 - Other mods:  wthit, modmenu, megane, cloth-config.

**Comment by Ayutac** [comment]
looks like the NBT isn't written probably maybe. Last crafting recipe isn't saved

**Comment by xanthian** [comment]
tested on 2 new single player worlds.
1.17.1 & 1.18.1

Works fine on 1.17.1
Loses recipe and stored energy on 1.18.1
doesn't seem to impact other machines I've tested (not them all)

**Comment by Ioandar** [comment]
for me it also loses the import/export settings (1,18,1)
