### ISSUE TITLE
Grinder does not grind new ores

### ISSUE THREAD

**Issue by tgcgh** [TechReborn/TechReborn#2689]
**Describe the bug**
Grinder does not grind new ores like raw iron or raw gold, galena tho which does not have the new style of ore does get grinded.

**Steps to Reproduce**
-mine ore
-stick it in powered grinder

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric

**Comment by tgcgh** [comment]
doesn't crash or anything just does nothing

**Comment by xanthian** [comment]
which version of TR

**Comment by tgcgh** [comment]
5.1.0 beta 4

**Comment by tgcgh** [comment]
i run it with quite a few mods also hope it isn't something else I stuck in there, thanks for the fast response

**Comment by xanthian** [comment]
If you open Grinder with REI/JEI can you see the recipes?
![image](https://user-images.githubusercontent.com/7688001/147508145-a5ee3af9-cf3c-43b1-94dd-a16376babfc6.png)
Attached image showing REI and the 2 Ore's you mentioned.
If you can't see this I suspect its likely another mod messing with it.

**Comment by tgcgh** [comment]
I do see it just like you
![grinder](https://user-images.githubusercontent.com/86541194/147508375-6afb952f-56f8-48e4-8699-6277397b0877.png)
but there shouldn't be blocks on the left, there should be raw ores and on th right you should get dusts not raw ores I think.  Only galena or stuff mined with silk touch would drop the block versions of the ore.

**Comment by xanthian** [comment]
This is intended.
Ore doubling is from silk touch only.
There is no Iron, Copper or Gold dusts

**Comment by tgcgh** [comment]
oh ok thank you very much!

**Comment by RechargeableAA** [comment]
I realize this is 'intended', and requires fortune. I think this was poorly thought out. Why waste time with silk touch, and simply get fortune? is fortune > 2 machines + cables? Wouldn't the player feel more satisfied with their work (for crafting the machines) with one machine that doubles the raw ores into powders, adding one extra step to accomplish the goal of ore doubling? even if it say, gave 14 nuggets, (1.5 ingots) the machines would be worthwhile. My point is, why gate-keep behind a RARE enchantment, when a much more common VANILLA one makes the machines obsolete?

**Comment by tgcgh** [comment]
To be honest that's exactly what I did, got a fortune enchant on my pick and never used the grinder again except for recipes that use dusts.... It isn't even something I automate with ae2 since i practically don't use it...
