### ISSUE TITLE
[2.24.1.1017] player detector range not configurable

### ISSUE THREAD

**Issue by mamama1** [TechReborn/TechReborn#2690]
In FTB Ultimate Reloaded 1.9.1 (MC 1.12.2), the Player detector has no obvious way to set the desired detection range.
16 blocks is ridiculously high if you want just an automatic door.

**Comment by Ayutac** [comment]
Do you want a configurable range via config that is the same for all players or one that can be changed ingame?

**Comment by mamama1** [comment]
ingame would be great.

**Comment by drcrazy** [comment]
Implemented

![image](https://github.com/TechReborn/TechReborn/assets/1382352/1f410f6c-4b2c-4aee-a17b-cd8190bff3d2)

**Comment by mamama1** [comment]
nice, thank you!
