### ISSUE TITLE
problem with coolant cells recipes

### ISSUE THREAD

**Issue by tgcgh** [TechReborn/TechReborn#2691]
**Describe the bug**
Can't make any products that need fluids in the recipe, as an example, 60k coolant cell shows a bucket of helium as center item of the recipe, there's no way to make a bucket of helium. 

**Steps to Reproduce**
-click the 60k coolant cell in REI

**Screenshots**
![image](https://user-images.githubusercontent.com/86541194/147577486-efbbd051-c021-4367-b56a-538b2d470d56.png)

![image](https://user-images.githubusercontent.com/86541194/147577433-2cb3a40d-59bd-4b8e-b52c-943b563d05c1.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric
 - TR: 5.1.0 BETA 4

**Logs**
no crash log

**Additional context**
I tried using helium cells instead of helium buckets without success.

**Comment by xanthian** [comment]
I agree on this, its a fiddle.
However, to get a bucket of Helium, place a Helium cell in to a 1x1 hole and pick up the fluid with a bucket.
Or
Use the Helium Cell on a Tank and then place a bucket in the tank.

**Comment by tgcgh** [comment]
Thank you again, that totally works!  thank you for your fantastic support!  i'll close this!
