### ISSUE TITLE
Crash on World load (Energy)

### ISSUE THREAD

**Issue by thethrax** [TechReborn/TechReborn#2697]
**Describe the bug**
Server crashes on startup: World load (Energy). Suspected Mods: Energy (team_reborn_energy), Minecraft (minecraft), Fabric Transfer API (v1) (fabric-transfer-api-v1), Tech Reborn (techreborn), Reborn Core (reborncore)

**Steps to Reproduce**
- Start the server

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric
 - Modpack: Benchmark 2, version 0.4.8

**Logs**
https://pastebin.com/hLhiyuJD

**Additional context**
Broken region file: https://drive.google.com/file/d/1hbJNXr-PnGtUQfaxGrL5S-kuxyEIdUVn/view?usp=sharing
If I try to manually remove some of the powered devices via nbt explorer (eg. fluid replicator, matter fabricator, etc), the crash appears again but references a different ticking device hooked up to that power (lots of devices are in use)

An update: I removed all recyclers and a matter fabricator from that region, and the region works now... Hope that helps.

**Comment by drcrazy** [comment]
No support for 1.18. Please, reopen if it is still reproducible in 1.20
