### ISSUE TITLE
TechReborn ores not spawning in Terralith biomes

### ISSUE THREAD

**Issue by Alchemancer** [TechReborn/TechReborn#2701]
**Describe the bug**
Tech Reborn ores do not spawn in Terralith biomes

**Steps to Reproduce**
Install "Terralith" mod version with TechReborn
use spectator mode to observe ore spawn

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric 0.12.12

**Additional context**
According to Starmute (the author of Terralith) it is not an issue on their end and must be solved by mod authors by adding proper biome modifications.

**Comment by xanthian** [comment]
A fix is in the works, PR has been put in to another mod that has potential.

**Comment by xanthian** [comment]
New FAPI version fixes this :
![image](https://user-images.githubusercontent.com/7688001/151784851-5efc8455-665e-4e3e-a299-48b6fd16d192.png)
A new world with
FAPI 0.46.3
Terralith 2.0.12
TR beta 7
