### ISSUE TITLE
[Crash 1.18.1] Battery Client crash

### ISSUE THREAD

**Issue by itsdinkd** [TechReborn/TechReborn#2708]
Some odd crash is occuring due to client screen rendering and TR batteries, as reported here https://github.com/red2blue/AQM2/issues/23 -- Crash log for this; https://pastebin.com/XUB6kKp1 

Another player reported this, here is their crash log https://paste.corebot.dev/itimeyotip.php

**Comment by drcrazy** [comment]
Can't reproduce in dev env. Looks like it is fixed already by ShulkerBoxTooltip

![image](https://user-images.githubusercontent.com/1382352/173830723-3e2a05ae-cca9-4383-ae75-f7a52f203785.png)
