### ISSUE TITLE
(suggestion)power connecting to other mods

### ISSUE THREAD

**Issue by kajdaniec** [TechReborn/TechReborn#2715]
I'm playing with this mod and it would be very nice that cables would connect to other mods machine(Modern Industrialization mostly)

**Comment by xanthian** [comment]
thats for MI to accept them, not TR.

**Comment by kajdaniec** [comment]
Mi cables actually connect to tr ones but it's not working other way

**Comment by xanthian** [comment]
yes its an intentional limitation of MI not to accept power from other mods.
