### ISSUE TITLE
Items in storage units disappear

### ISSUE THREAD

**Issue by NemoJaaskelainen** [TechReborn/TechReborn#2717]
**Describe the bug**
If you put items in a storage unit with the fast method (hold an item and right-click the block), some of the items in the unit may disappear if you restart the world.

**Steps to Reproduce**
Here are steps that show some logic on how this works. It looks like this bug happens in both creative and survival modes, with any non-creative storage unit and with any item, this is just how I tested this.
- Go to a singleplayer world and use creative mode.
- Place down a crude storage unit.
- Give yourself 63 turtle eggs and put them into the empty storage unit with the fast method (right-click the unit with the items in your main hand).
- Give yourself 64 turtle eggs and put them into the storage unit with the fast method.
- Give yourself another 64 turtle eggs and put them into the storage unit with the fast method.
- Quit the world and play it again.
- The last 64 turtle eggs put into the unit have disappeared now. It seems that if the storage unit contains 64 or more turtle eggs and you fast-put more in there, the newly put eggs disappear after reloading the world. This works differently with items that don't stack to 64, but has the same logic behind it.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: fabric-loader-0.12.11-1.18
 - Mod: fabric-api-0.44.0+1.18
 - Mod: modmenu-3.0.1
 - Mod: TechReborn-5.1.0-beta.4

**Comment by xanthian** [comment]
Able to replicate.

**Comment by drcrazy** [comment]
Thank you for detailed steps to reproduce. That helped a lot!
