### ISSUE TITLE
RebornCore dependency not tagged with 1.18.1 on CurseForge

### ISSUE THREAD

**Issue by bessiq** [TechReborn/TechReborn#2727]
**Describe the bug**
RebornCore-5.1.0-beta.5 is not tagged on CurseForge for 1.18.1, which led TR to be a bit crash-y when I updated it and started the game. The CurseForge launcher didn't show that RebornCore needed to be updated, and when I checked manually it only listed beta4 (which is what I had installed). I went and found the new file on the CF website and it's working now, but just thought I'd let you know!

**Steps to Reproduce**
- Update TechReborn
- Start Minecraft
- Watch the crash log scream at me because my version of RebornCore was not having it apparently 😄

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric 0.12.12

**Logs**
Probably unnecessary but just in case: https://paste.ee/p/0ckw1

**Additional context**
Thanks for the silver armor!

**Comment by xanthian** [comment]
you shouldn't actually need it, its bundled with TR itself.
You probably had beta4 as a standalone for some reason?
(i did.. no idea why)

**Comment by modmuss50** [comment]
Fixed the build scripts, and manually fixed the existing version.
