### ISSUE TITLE
0.6.0.1015 Assembly Machine NEI integration doesn't work or is missing

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#273]
Even when adding MT recipes, looking up recipes in NEI doesn't work and there is no in gui recipe checker. (standalone)

**Comment by Carbon-Ghost** [comment]
Has been removed from normal mod, you can readd minetweaker recipes for it and other recipes, but it was mean't for modpack makers ;) Please close this.

**Comment by Xen1290** [comment]
https://github.com/TechReborn/TechReborn/issues/240

**Comment by modmuss50** [comment]
Nothing has been removed, I did recode it, it should have backwards compatability.

**Comment by modmuss50** [comment]
I will get a build with this on curse tonight.
