### ISSUE TITLE
Thermal Generator power production inconsistencies 

### ISSUE THREAD

**Issue by BLovegrove** [TechReborn/TechReborn#2742]
**Describe the bug**
Thermal Generator (Haven't tested others extensively) has some strange behavior. Seems to be outputting incorrect power.
Tried smelting titanium in a blast furnace. the internal power drained completely in a couple of seconds and although the thermal generator reports only draining 112 E/t (as does the furnace) the generator is completely drained and struggling to keep up.

The item desc says it only draws 128 E/t which is exactly what the thermal generator produces so there must be something going on in the background here. 

**Steps to Reproduce**
- Tank of lava feeding to thermal generator above.
- Thermal generator hooked up to blast furnace indirectly via copper cables.
- put something to smelt in the blast furnace.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric 
 - Mod version: 5.1.0 beta 4
 
**Logs**
[latest log](https://pastebin.com/Xh17S6jA)

**Comment by BLovegrove** [comment]
As an addendum - I've just noticed the normal coal generator (when hooked up to the same system as mentioned) says it can produce 32 E/t but the energy change value us -54 E/t and both generators remain completely drained while the furnace remains starved of energy and turning on for a pulse every other second or so

**Comment by xanthian** [comment]
It only creates 16 E/t from Lava, so when used alone to power a blast furnace it will drain very quickly around 7mins if it is still supplied with lava.

So 128 - 16 = 112 as you reported.
Generator info on wiki : [https://wiki.techreborn.ovh/doku.php?id=energy:generators](https://wiki.techreborn.ovh/doku.php?id=energy:generators)

Config exists in config\techreborn\generators.json where you can change the default values
![image](https://user-images.githubusercontent.com/7688001/149339742-5bff2cb8-ae0a-42a9-be94-5fbb54376031.png)


I made a long post on the Gen's as they arent great imo, and its far too easy to spam solar panels instead.
[https://github.com/TechReborn/TechReborn/issues/2622](https://github.com/TechReborn/TechReborn/issues/2622)

**Comment by BLovegrove** [comment]
Cannot believe I missed that.
Yeah that seems *really* low considering the lack of fluid pumps to automate the lava process (at least that I've found).

Thanks for the swift response and the config tips!

**Comment by xanthian** [comment]
Is this issue resolved?

**Comment by drcrazy** [comment]
Looks like yes )
