### ISSUE TITLE
TechReborn End Ores not Spawning in BetterEnd Mod Biomes

### ISSUE THREAD

**Issue by FirstMegaGame4** [TechReborn/TechReborn#2743]
The TechReborn End Ores are not Spawning in the BetterEnd Mod Biomes.

 - Minecraft: 1.18.1
 - Mod Loader: Fabric

I went to see the creator of the BetterEnd mod to find out why TechReborn's ores weren't showing up in his biomes, and it's because you didn't implement that. The creator of BetterEnd has shown how to get ores from other mods to appear in his End Biomes.
https://github.com/paulevsGitch/BetterEnd/issues/398#issuecomment-1012023175

Can you fix this please? It's really hard to find TechReborn ores with BetterEnd installed as BetterEnd biomes are almost everywhere in the end.

**Comment by xanthian** [comment]
known issue.
hoping the fix can be PR'd directly to fabric rather than relying on every mod to add.

**Comment by FirstMegaGame4** [comment]
The Fabric contributors know this issue ?

**Comment by xanthian** [comment]
I'd hope so, TR/Fabric API dev is one and the same :)

There is currently a PR up on Modern Industrialisation that aims to fix this.
[https://github.com/AztechMC/Modern-Industrialization/pull/223](https://github.com/AztechMC/Modern-Industrialization/pull/223 )

If it does not make it in to FAPI, its something that could be looked at here.

**Comment by xanthian** [comment]
duplicate of #2701

**Comment by xanthian** [comment]
New FAPI version fixes this :

![image](https://user-images.githubusercontent.com/7688001/151780494-ae07c221-d556-4723-8ab5-0d1d05f59b33.png)

A new world with
FAPI 0.46.3
Better End 1.0.1
TR beta 7

**Comment by FirstMegaGame4** [comment]
Ok thanks

**Comment by FirstMegaGame4** [comment]
Ok thanks
