### ISSUE TITLE
[BUG] Lapatron Crystal in Inmis Backpack causes CTD

### ISSUE THREAD

**Issue by itsdinkd** [TechReborn/TechReborn#2744]
Player of my modpack AQM2 reported this

**Describe the bug**
If placing a lapatron crystal in an inmis backpack, when you hover over the backpack in your inventory this will result in a crash. This appears to be due to Shulker Tooltips, as disabling this stops the issue happening.

**To Reproduce**

    Add Lapatron Crystal to backpack
    Hover cursor over backpack so that tooltip showing contents should appear
    Game crashes to desktop

**Expected behavior**
Tooltip showing contents should be shown.

**Screenshots**
n\a

**Crash log or latest.log.log**
[Crash report](https://pastebin.com/DUnyCX8F)

**Additional context**
[n\a](https://github.com/itsdinkd/AQM2/issues/48)

**Comment by xanthian** [comment]
duplicate of #2599

**Comment by itsdinkd** [comment]
apologies. just getting so many reports of this I forgot I already opened a issue.
