### ISSUE TITLE
Auto Crafting Table contents get deleted on restart

### ISSUE THREAD

**Issue by FelixLouis** [TechReborn/TechReborn#2745]
**Describe the bug**
All the data about the Auto Crafting Table block (including the input/output settings and the items stored in it) are reset each time the server restarts (or, in solo play, when you leave an restart the game).

**Steps to Reproduce**
 - Start a new game
 - Place an Auto Crafting Table
 - Place any item in it
 - Leave
 - Go back to the game: the item is gone.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric

**Additional context**
I am using the 5.1.0-beta.4 version but I haven't seen this bug fixed in beta.5

**Comment by xanthian** [comment]
its fixed in beta5

https://github.com/TechReborn/TechReborn/pull/2696
