### ISSUE TITLE
Machines don't use energy

### ISSUE THREAD

**Issue by BakermanLP** [TechReborn/TechReborn#275]
Hello,
when you filled up a machine with EU and put some work in the machine, the internal buffer doesn't go down / gets consumed. 

Tested versions:
- industrialcraft-2-2.2.790-experimental.jar  
- RebornCore-1.0.0.8-universal.jar  
- TechReborn-0.6.1.1021-universal.jar

Thanks for your mod.

Michael (aka BakermanLP)

**Comment by BakermanLP** [comment]
Sorry to say that, but https://github.com/TechReborn/TechReborn/commit/9283e46a1fdc2b313e1ef4168b148ce794fe1271 doesn't fix the problem. No Energy usage in single block and multiblock machines.

**Comment by modmuss50** [comment]
@BakermanLP opps, It should be fixed, now. I've noticed some of the recipes don't use a lot of power so it might take a while for you to see the power go down. But it has been fixed.

**Comment by BakermanLP** [comment]
Now it works as intended. Thanks a lot!
