### ISSUE TITLE
Autocrafting Table checks recipe reminders wrong

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2761]
AutoCraftingTableBlockEntity has this code in its `canMake` method

```java
		DefaultedList<ItemStack> remainingStacks = recipe.getRemainder(crafting);
		for (ItemStack stack : remainingStacks) {
			if (!stack.isEmpty() && !hasRoomForExtraItem(stack)) return false;
		}

		return true;
```

This is wrong, e.g imagine 15 empty buckets in the remainer and three milk buckets in the cake recipe. The method will not return `false`. Also doesn't work if there are two different remaining types, like a bucket and a glass bottle from a honey bottle for example. I think this never happens in vanilla recipes, but could easily in mod recipes.

**Comment by Ayutac** [comment]
I tried it with the cake recipe and the machine simply doesn't work when there are 15 empty buckets *and I don't get why*

**Comment by drcrazy** [comment]
Buckets stack max size is 16 ;)
