### ISSUE TITLE
Data generated with datagen not used in dev

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2763]
The data generated with datagen is not used in dev environment. This makes checking for correct behavior way more tedious.

**Comment by Ayutac** [comment]
I guess that is also the reason why https://github.com/Ayutac/TechReborn/tree/1.18-Ayutac-datagen didn't work. The generated tags are not added to TR in dev env and hence the static references to them in the JSON files cause errors. Hrmmm

**Comment by modmuss50** [comment]
Humm, odd ill take a look.

**Comment by Ayutac** [comment]
Fixed by 646132e9 (and following commits)
