### ISSUE TITLE
Tech reborn-modern industrialization iron/rails/minecart dupe

### ISSUE THREAD

**Issue by trlolo** [TechReborn/TechReborn#2767]
**Describe the bug**
tech reborn rail/minecart uncrafting recepe allow for iron dupe, When modern industrialization is instaled .

**Steps to Reproduce**
Useing recepe for rails from modern industrialization 16 rails can be made from 3 ingot,But uncrafting recepe for blast furnace use only 12 rails to produse 3 iron ingots, Useing recepe for minecart from modern industrialization minecart can be made from ~4 ingot,But
blast furnace uncrafting gives 5 ingots form minecart

**Screenshots**
recepes form modern industrialization
![2022-01-22_18 03 16](https://user-images.githubusercontent.com/43910955/150643931-652301b5-f1d5-4402-afdc-fa4f38400294.png)
![2022-01-22_18 03 07](https://user-images.githubusercontent.com/43910955/150643941-6e98bda7-a870-413d-ac4a-9f03fa5b25ed.png)
recepes from tech reborn
![2022-01-22_18 03 14](https://user-images.githubusercontent.com/43910955/150643963-ef738101-312a-4c95-871d-09a75df79f07.png)
![2022-01-22_18 03 09](https://user-images.githubusercontent.com/43910955/150643967-adb2d83e-2005-427f-9345-01e65a8105ca.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric
- Mod Pack: All of fabric 5 1.0.4
**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[latest.log](https://github.com/TechReborn/TechReborn/files/7918611/latest.log)

**Additional context**
Dupe can be fixed by redusing iron get form minecart oncrafting recepe and using more rails for rails oncrafting recepe .

**Comment by xanthian** [comment]
MI recipe for 16 Rails is 6 Steel Rods.
6 Steel Rods is made from 3 Steel Ingots.
4 Steel Ingots are made from 4 Iron Dust in the Cupronickel EBF (not early game for sure)
4 Iron Dust from 2 Raw Iron / 4 Iron Ingots


I'm missing something here? the effort for gain is so minimal at this stage of the game.

**Comment by Ayutac** [comment]
Iron Ingots are infinite with Iron Farms. Who puts that much effort in the uncrafting process might as well do an Iron Farm.

That said, I don't have any problem reducing the gain of rails to 2 Iron Ingot

**Comment by trlolo** [comment]
> 



> MI recipe for 16 Rails is 6 Steel Rods. 6 Steel Rods is made from 3 Steel Ingots. 4 Steel Ingots are made from 4 Iron Dust in the Cupronickel EBF (not early game for sure) 4 Iron Dust from 2 Raw Iron / 4 Iron Ingots
> 
> I'm missing something here? the effort for gain is so minimal at this stage of the game.

Alternative recepi exist that convert 7 iron ingots to 9 steel ingots at only steam blast furnace tier
![2022-01-23_01 28 58](https://user-images.githubusercontent.com/43910955/150657457-b1df1196-a1ec-4d99-b05e-12386ca25878.png)
![2022-01-23_01 28 53](https://user-images.githubusercontent.com/43910955/150657459-84b630f2-efff-4682-a7a8-8f79a576baea.png)
.

**Comment by Technici4n** [comment]
I would personally just delete the uncrafting recipe from TR entirely.

**Comment by drcrazy** [comment]
Mod compat should be balanced by pack authors.
