### ISSUE TITLE
Cannot connect to Beta.6 version server environment

### ISSUE THREAD

**Issue by aria1th** [TechReborn/TechReborn#2774]
**Describe the bug**
Beta 6 Client - Server mismatches

**Steps to Reproduce**

Construct fabric 1.18.1 server with beta.5 release and confirm its able to connect server with beta.5 client.
Construct fabric 1.18.1 server with beta.6 release and confirm its NOT able to connect server with beta.6 client.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric, fabric API 0.46.2

No logs remain : only disconnected 

Starting investigation with building commits by commits...

**Comment by Ayutac** [comment]
Issue is known and has been fixed in latest commit. Probably new beta out today or tomorrow.

**Comment by modmuss50** [comment]
Just releasing beta 7 now, should hopefully fix it. Please open a new issue if its not working quite right for you. 👍
