### ISSUE TITLE
Portable energy compatibility with trinkets

### ISSUE THREAD

**Issue by MiriamAlter** [TechReborn/TechReborn#2775]
Functionalities to add:
- Portable energy sources can be equipped in trinket slots
- Portable energy sources can charge items that are equipped in trinket slots

**Comment by Ayutac** [comment]
Is the support for Lapotronic Batpack given by that commit or do we need to reopen the ticket?

**Comment by SimonFlapse** [comment]
If it extends BatPackItem then it should be supported. I tested the two battery packs I found in REI and they both worked.
