### ISSUE TITLE
Glitch where the infusion table WAS, this was beta 5 version

### ISSUE THREAD

**Issue by entwinedent** [TechReborn/TechReborn#2779]
The game crashed whilst ticking block entity
Error: java.lang.ClassCastException: class net.jptrzy.infusion.table.blocks.InfusionTableEntity cannot be cast to class techreborn.blockentity.cable.CableBlockEntity (net.jptrzy.infusion.table.blocks.InfusionTableEntity and techreborn.blockentity.cable.CableBlockEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @35f26e72)
Exit Code: -1

**Comment by xanthian** [comment]
mc version?
tr version?

also looks like its net.jptrzy.infusion.table.blocks.InfusionTableEntity whatever this is.

**Comment by entwinedent** [comment]
I moved the infusion table to move one of the machines over to where the infusion table was then as soon as i placed a cable , it looks as if it tried to connect to it, MC version 1.18.1 fabric, tr version ?

**Comment by entwinedent** [comment]
java edition if thats what tr is

**Comment by entwinedent** [comment]
Don't know what caused it to glitch like that , but it looks like it fixed itself through a couple restarts.

**Comment by Ayutac** [comment]
> java edition if thats what tr is

You are submitting a bug for **T**ech**R**eborn. The version number of TechReborn is important.

Also please make sure a bug is reproducible before submitting it.

**Comment by drcrazy** [comment]
Looks like it was a ghost entity from InfusionTableEntity left. TR team not able to fix Infusion Table.
