### ISSUE TITLE
Errors in currently selected datapacks prevented the world from loading. - after updating

### ISSUE THREAD

**Issue by MrLatroX** [TechReborn/TechReborn#2782]
**Describe the bug**
Since the last update from RebornCore-5.1.0-beta.5.jar to RebornCore-5.1.0-beta.7.jar i can't join my world anymore.
Of course also TechReborn and Quarry Reborn.
If i go back to the old versions it works again.

**Steps to Reproduce**
1. Update the 3 Mods
2. Open Minecraft
3. Can't join the world

**Screenshots**
[https://picflick.de/images/2022/01/31/Screenshot-2022-01-31-193849dd0f699cde955486.png](url)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

[https://pastebin.com/tyf6j55B](url)

**Comment by arquxx** [comment]
its due to this mod - although its a bug in techreborn code -  https://www.curseforge.com/minecraft/mc-mods/ore-tree-reborn-fabric

**Comment by Technici4n** [comment]
The bug is that TR crashes when an item is missing instead of printing an error and silently ignoring the recipe. This is because MC only catches a few specific exceptions (IllegalArgumentException should do IIRC).

**Comment by MrLatroX** [comment]
> its due to this mod - although its a bug in techreborn code - https://www.curseforge.com/minecraft/mc-mods/ore-tree-reborn-fabric

You are right, without that mod i runs with the new versions.
But it would be great if it also works with that mod.
Who need to fix that?

**Comment by VulpesStella** [comment]
> > its due to this mod - although its a bug in techreborn code - https://www.curseforge.com/minecraft/mc-mods/ore-tree-reborn-fabric
> 
> You are right, without that mod i runs with the new versions. But it would be great if it also works with that mod. Who need to fix that?

Fixed by restoring recipes in Ore Tree, 0.2.4 for 1.18 released.
