### ISSUE TITLE
Raw variants take 10 seconds in vanilla blast furnace

### ISSUE THREAD

**Issue by ErrorSys** [TechReborn/TechReborn#2783]
I dont know if this is intended behavior, and if it is so, then this isn't an issue. but every recipe that uses raw variants of ores inside the vanilla blast furnace takes 10 seconds, while consuming twice the amount of fuel necessary. eg, coal smelts 4 items instead of 8. I should clarify that this only affects the mod variants and not the vanilla raw ores themselves. It also seems to override other mod recipes of the same ore and causes this issue with other mod variants, for example, raw tin from another mod takes 10 seconds as well. Removing tech reborn reverts to the other mods recipe which only takes 5 seconds.

**Comment by Ayutac** [comment]
probably stems from recent datagen

**Comment by ErrorSys** [comment]
I'm relatively new to making mods, but would this be the source of the issue?

/src/datagen/groovy/techreborn/datagen/recipes/smelting/SmeltingRecipesProvider.groovy
lines 73-74

```java
def offerBlasting(def input, ItemConvertible output, float experience = 0.5f, int cookingTime= 200) {
        offerCookingRecipe(input, output, experience, cookingTime, RecipeSerializer.BLASTING, "blasting/")
```

**Comment by Ayutac** [comment]
Oh, I wasn't aware that this error has persisted for a longer time! Well spotted!
