### ISSUE TITLE
Iridium-Reinforced Tungstensteel Block Blast Resistance

### ISSUE THREAD

**Issue by Dragonfly-Totem** [TechReborn/TechReborn#2786]
Fabric Loader 0.12.12-1.18.1
fabric-api-0.46.1+1.18
TechReborn-5.1.0-beta.8
RebornCore-5.1.0-beta.8

Wondering if the IRTB blocks have had their blast resistance dropped/altered.

Created a TNT block encased in a square of IRTB, and it shattered the IRTB back to floating entities.  Did a secondary test of it with vanilla Obsidian surrounding TNT block, and the Obsidian was untouched.

**Comment by ErrorSys** [comment]
Looks like all metal blocks have the same hardness and resistance, regardless of what it is actually composed of
