### ISSUE TITLE
Deepslate Ore Variants Breaking Speed

### ISSUE THREAD

**Issue by verlixis** [TechReborn/TechReborn#2788]
As of TechReborn-5.1.0-beta.8, deepslate ore variants of TechReborn have the regular breaking speed when mined instead of being slower as deepslate.

**Comment by Ayutac** [comment]
Easily fixable by checking for deepslate variant in TRContent.Ores constructor and make a case distinction just as with the sounds. I would do it, but I don't know the correct breaking values for deepslate.

**Comment by ErrorSys** [comment]
> Easily fixable by checking for deepslate variant in TRContent.Ores constructor and make a case distinction just as with the sounds. I would do it, but I don't know the correct breaking values for deepslate.

Problem is that the hardness currently is the same for both stone and deepslate variants. working on a PR right now to fix this though.

Edit: Just realized this is exactly what you just said lol.
