### ISSUE TITLE
Missing information and slots in AESU/LESU/IDSU

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#279]
Missing Charge and Discharge slots, and informations in the black screen.
See here, from GregTech2:
![2015-11-18_17 00 53](https://cloud.githubusercontent.com/assets/8685029/11247379/20dddc48-8e1c-11e5-9dad-d0202c03cf69.png)
![2015-11-18_17 01 11](https://cloud.githubusercontent.com/assets/8685029/11247380/20e08f56-8e1c-11e5-900d-023768be64eb.png)
![2015-11-18_17 26 48](https://cloud.githubusercontent.com/assets/8685029/11247381/20e4a4ce-8e1c-11e5-86b8-44cd5e3ba53c.png)

TechReborn-0.7.0.1036-universal
RebornCore-1.0.0.10

**Comment by modmuss50** [comment]
moving into todo
