### ISSUE TITLE
Do something about the website

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn#28]
[Sample issue comment]

**Comment by modmuss50** [comment]
When we are getting ready to make a website we can. It might be nice to make a blog post about what we have done so far.

**Comment by modmuss50** [comment]
Has anyone got any decent experience in web dev? Or are we going to use wordpress. I can make simple bootstrap sites and thats about it.

**Comment by gigabit101** [comment]
the website already uses wordpress

**Comment by joflashstudios** [comment]
I've done a lot of web dev. I can do something with it if/when needed.

**Comment by gigabit101** [comment]
I can give u access

**Comment by modmuss50** [comment]
if you enable registration we can make an account.

**Comment by joflashstudios** [comment]
techreborn.ninja should do a 301 redirect to techreborn.ninja/home, instead of returning a 403 error. I'm not sure if this is doable in Wordpress, since it is currently living under /home/. I think this is an apache configuration issue.

Alternatively, we could move wordpress to the root.

**Comment by joflashstudios** [comment]
Also, @modmuss50, @Tntrololol, @gigabit101, do we want to host a wiki / contribute to the FTB wiki regarding TechReborn? For instance, the LESU's behavior is (appropriately) significantly different from the GT 4 version, and we've made other minor and not-so-minor changes throughout.

**Comment by modmuss50** [comment]
We should host the wiki on the site

**Comment by joflashstudios** [comment]
@modmuss50, the Jenkins is down. Not sure if you're aware of that or not.

**Comment by modmuss50** [comment]
Thanks, I will have a look into it now,

**Comment by modmuss50** [comment]
Not a lot I can do about it, looks like OVH is having issues. https://twitter.com/OVH_Status/status/611166667025043456

**Comment by modmuss50** [comment]
Yep, ovh is having issues sorry.

**Comment by modmuss50** [comment]
@joflashstudios its up :) sorry about that
