### ISSUE TITLE
TR items aren't categorized properly in recipe book

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2808]
Like drill crafting recipe should be under tools together with pickaxe, all machines are redstone items etc.

This issue is mainly a reminder for myself, but if you, the reader, commit a PR to fix it, that would work as well :)

**Comment by drcrazy** [comment]
Recipe Book categorization done based on itemGroup which is a Tab in creative menu. This is why all TR items are in Misc category of the Recipe Book.
