### ISSUE TITLE
Power Issues

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#281]
If you fill the interenal storage with a batbox and a cable and then, remove the cable, you have infinite energy in the machines.This for all machines.
To reproduce, use this setup:
![2015-11-18_18 15 16](https://cloud.githubusercontent.com/assets/8685029/11248253/79ffe998-8e20-11e5-971e-2e377b55a63d.png)
![2015-11-18_18 15 20](https://cloud.githubusercontent.com/assets/8685029/11248254/7a0d9e1c-8e20-11e5-87e1-85852908d547.png)
![2015-11-18_18 15 27](https://cloud.githubusercontent.com/assets/8685029/11248255/7a14b51c-8e20-11e5-845e-52d1d1924787.png)
With this setup, remove the cable and you have done.

Also this this thing:
![2015-11-18_17 59 40](https://cloud.githubusercontent.com/assets/8685029/11247935/9c204b28-8e1e-11e5-917f-8a3d7b69d05c.png)
The thunder icon istantly fill(few EU are enough) and never decrease. This for all machines.

**Comment by modmuss50** [comment]
What version are you running?

**Comment by Xen1290** [comment]
TechReborn-0.7.0.1036-universal
RebornCore-1.0.0.10
