### ISSUE TITLE
Wrong Vacuum Freezer Name

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#282]
![2015-11-18_18 01 03](https://cloud.githubusercontent.com/assets/8685029/11248358/0a022222-8e21-11e5-81b9-64b61ff193c8.png)

**Comment by gigabit101** [comment]
GG @modmuss50

**Comment by modmuss50** [comment]
@gigabit101 I only had to copy and paste about 500 classes and hope I didnt miss anything.
