### ISSUE TITLE
Industrial Blast Furnace does not like being next to other multiblocks

### ISSUE THREAD

**Issue by ErrorSys** [TechReborn/TechReborn#2823]
MC 1.18.1
TR 5.1.0-beta.9

Industrial Blast furnace multiblock is considered invalid when other multiblock parts are directly connected to any side or part of an existing multiblock. This does seem to be an isolated case as the industrial grinder and implosion chamber do not have an issue with being next to each other.

![2022-02-19_19 56 58](https://user-images.githubusercontent.com/38744863/154826596-7a01b485-b798-4327-ad28-832d4af1120a.png)
![2022-02-19_19 57 17](https://user-images.githubusercontent.com/38744863/154826598-062e28d5-f9ed-4d54-80d3-5f9cfe4aaf68.png)

**Comment by Ayutac** [comment]
duplicate of #2458

**Comment by ErrorSys** [comment]
ah, my bad.
