### ISSUE TITLE
Comparator output from battery box not updating

### ISSUE THREAD

**Issue by johalun** [TechReborn/TechReborn#2825]
**Describe the bug**
When measuring the amount of charge in a battery box with a comparator the comparator output signal strength does not update. If you force a block update by placing a block next to the comparator it does update the signal strength. So far I've only seen this issue with battery boxes. Advanced solar panel seem to function as expected when used with a comparator.

**Steps to Reproduce**
- Place a battery box and a generator and let the generator charge the battery box.
- Place a comparator so that measures the charge of the battery box and place a redstone dust line from the comparator output side.
- Verify that the signal strength the comparator outputs does not change as the charge of the battery box increases.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/hqKC0VyY

**Additional context**
Stand alone server on amd64 Linux.
Client on M1 MacBook with arm64 native binaries.

**Comment by drcrazy** [comment]
Can't reproduce anymore. 

![image](https://github.com/TechReborn/TechReborn/assets/1382352/b7d627a6-0cba-4a66-b231-d29ab1a43f48)
