### ISSUE TITLE
Rock Cutter drops without applying Silk Touch.

### ISSUE THREAD

**Issue by Zarepheth** [TechReborn/TechReborn#2826]
**Describe the bug**
When using the "Rock Cutter", I expect broken ores to drop the ore block. Instead I get the ore item.

**Steps to Reproduce**
1. After crafting and charging the Rock Cutter, find an ore block in the world, for instance Coal, Nether Quartz, etc...
2. Use the Rock Cutter to break the block.
3. Expect the block of ore, but get Coal or Quartz instead of Coal Ore or Quartz Ore.

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric 0.13.2
 - Modpack: Benchmark II 0.6.12
 - Tech Reborn: 5.1.0-beta.5 and .beta.9
   - Note: I've disabled a couple mods from the pack and added a few of QOL mods of my own choice.

**Logs**
Attached the latest log file, but I didn't see anything relevant in it.
[latest.log](https://github.com/TechReborn/TechReborn/files/8137866/latest.log)

**Additional context**
I am guessing that there is a mod conflict, but the modpack is so large, I haven't a clue where to start looking.

**Comment by ErrorSys** [comment]
Definitely a mod conflict. Might have something to do with another mod modifying the way silk touch works, but I wouldn't be too sure.

**Comment by drcrazy** [comment]
Can't reproduce.  Both stone and coal ore dropped proper items.

![image](https://user-images.githubusercontent.com/1382352/180325528-07e981a3-70c9-4d3e-8d52-1823ae62446e.png)
