### ISSUE TITLE
Question about Fusion Reactor

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#283]
The Fusion Reactor is intended in this way? It's very different from GregTech 2.
Different GUI, different multiblock ...etc?

**Comment by gigabit101** [comment]
Nope this is the same as what was in Gtech 2.78c what is the version we are remaking

**Comment by Xen1290** [comment]
Oh,sorry. the only version of GregTech 2 that I have is from FTB Ultimate, and the only foundable in GregTech tread, and let me know if I miss something: 
Alloy Smelter was added in 2.80f
Digital Chest was added in 2.79d
(http://ftb.gamepedia.com/GregTech_2/Changelog)
So these machines will be removed?
Sorry but I can't understand why some machines are added, other not, and others that have never existed in TechReborn.
I asked this to try to make better bug reports, but I haven't any idea of Fusion Reactor worked in 2.79 for example.
@Gigabit101 @modmuss50

**Comment by gigabit101** [comment]
There are a few things in TechReborn just for map makers like the Assembly machine.
As for the digital chest yes that will be removed.
And the Alloy Smelter will be off by default but will still be there for mapmakers.
I think @parcel31u is using it in his pack??

**Comment by parcel31u** [comment]
Yes I am.

**Comment by gigabit101** [comment]
well there u go it will be staying in the mod just with no recipe by default

**Comment by Xen1290** [comment]
@gigabit101 Oh well, thanks for the informations. So maybe move these machines to addons instead of remove? So someone can merge the gap between 2.78c and 2.90h.

**Comment by justjanne** [comment]
Is there a plan to support the functionality from 2.90h, or are there already addons doing so, etc?

Because I’d especially love to see the Fusion Reactor from 2.90h.

**Comment by Skillotic0703** [comment]
As 1.12 will certainly be a plateau version, there will be new features in the future but not now and that'll be  for 1.12. There is a possibility that someday the big fusion reactor comes but it's an important feature so if it comes it would be in several months.

**Comment by modmuss50** [comment]
I would love to see it, but I have more important things to work on (like fixing bugs) it would take me a good 1 or 2 weeks to make it. In the future its a possibility.

Im always open to PR's though. (I think someone started it a while back but didn't get to far)
