### ISSUE TITLE
[1.18.1] Crashes on launch due to missing ICrafterSoundHanlder class

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2835]
**Steps to Reproduce**
- Launch game
- Crash

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric

**Logs**
https://www.toptal.com/developers/hastebin/lasuyohowo.yaml

**Comment by xanthian** [comment]
Interestingly, you have Reborn Core 5.1.0, but Tech Reborn 5.1.0.beta.9
Try updating TR to 5.1.0 and if you have Reborn Core as a separate mod, remove it.
