### ISSUE TITLE
Crude Storage Unit Recipe 

### ISSUE THREAD

**Issue by xanthian** [TechReborn/TechReborn#2838]
https://github.com/TechReborn/TechReborn/blob/1.18/src/main/resources/data/techreborn/recipes/crafting_table/unit/storage/crude_storage_unit.json
![image](https://user-images.githubusercontent.com/7688001/156164744-4625a5a3-7570-47b4-9417-82f7a6d5e27c.png)

Why are we using a mods tag when there are c: tags for barrels and wooden_barrels
c:wooden_barrels seems a better option as this will include betterx and blockus barrels (as well as my own) :D

**Comment by Ayutac** [comment]
Why: because there was an additional recipe for crude storage unit with these barrels, andi just generalized that into one recipe. Step by step

**Comment by xanthian** [comment]
because it still only uses c:blockus_barrels.. makes no sense to rely on another mods tag that may or may not be installed by the user.
adding the c: tags which are widely used makes more sense.
