### ISSUE TITLE
TechReborn RecipeType's are not registered to Registry.RECIPE_TYPE

### ISSUE THREAD

**Issue by jaredlll08** [TechReborn/TechReborn#2842]
**Describe the bug**
When you register your recipe types, you only register it as a RecipeSerializer, not as a RecipeType.
https://github.com/TechReborn/TechReborn/blob/1.18/RebornCore/src/main/java/reborncore/common/crafting/RecipeManager.java#L53

This is an issue since some mods (like CraftTweaker) use the RecipeType registry to see what types are available to work with.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric

**Comment by Tenchu98** [comment]
This has been an issue for me in making my modpack as I can neither remove nor add recipes to the machines in the mod through crafttweaker.

**Comment by modmuss50** [comment]
Ok great, was a easy fix once I knew about it 👍 I will try and get a new build out soon, need to do a bit more testing first as there are some quite large changes that will go out alongside this.

**Comment by Tenchu98** [comment]
ok thank you for the speedy fix
