### ISSUE TITLE
Superconductor cables not transmitting power (bug or feature request?)

### ISSUE THREAD

**Issue by mnsnownutt** [TechReborn/TechReborn#2848]
1.18.1 (please see the linked pastebin for all relevant mod info from forced crash report)

Superconductor cables are not transmitting power, or not the amount expected.  I have them attached to a fusion reactor.  

It had around 550M in it when I started crafting, none of that stored power went into the ASU (or, it did at a rate of 64E/T).  The ASU was at ~927M to start (I had adjusted that in the config to 1G for the ASU).  

After 15 recipes had gone through, I took the attached screenshots.  Each recipe produces about 150M, so including the original stored power, there should be over 2.6G worth of power.  EDIT- not sure if you can tell, but I have 3 cables total from the controller to the ASU.  All of the power either went into the cables or was voided, not sure.  I put deuterium and tritium in chests to feed into the reactor. 

I attached a forced crash report that contains all of the relevant mod info.

If this is not a bug, then a feature request, because this makes the superconductor cables not cables, but something else.  Maybe call them capacitors or something else, but they should transfer power at the rate stated.  I know there is a buffer, but all that should mean is that they will continue accepting power even when they are not transmitting power, until their buffer fills, not that they will not transmit over 2.6G worth of power, until some unknown condition unlocks it.

Currently, the only way I can charge the ASU is to break it with a wrench, put it on top of the fusion control computer until it is charged, then break it and move it.

EDIT - after crafting roughly 32 recipes, power started transmitting, or over 5G of power.  However, the other issue I am now having is that, even with 2 superconductor upgrades, the ASU is only accepting power at a rate of around 65K and according to the Wiki, that should be 139K, so it backs up the fusion computer which is generating at around 93K without being able to fully charge the ASU.

https://pastebin.com/jvS6RVR8
![2022-03-06_11 41 29](https://user-images.githubusercontent.com/31514693/156944492-796487e1-2821-4b03-8fd1-a6932704bb48.png)
![2022-03-06_11 43 45](https://user-images.githubusercontent.com/31514693/156944493-f0b97da1-2424-4ff4-bc19-372aca810ecc.png)

**Comment by mnsnownutt** [comment]
I am going to add a separate reply, due to this may be an unrelated issue, not sure.  I decided to make another superconductor upgrade for the ASU.  As soon as I put it in the ASU, it began charging and fully charged in a matter of seconds.  This was without anything running in the fusion computer, so I assume it was taking energy from the superconductor cables' buffers. 

However, this only occurs with 3 superconductor upgrades.  As soon as I remove the 3rd one, the ASU starts discharging at varying rates, anywhere from -100 to -1,000, as my base is being powered through it.  Put the 3rd upgrade in and the ASU immediately starts charging up again.

EDIT-added screenshots

![2022-03-08_05 40 18](https://user-images.githubusercontent.com/31514693/157231727-a0d8fc57-5dc0-4c59-87f4-69e61b1c6c4c.png)
![2022-03-08_05 40 25](https://user-images.githubusercontent.com/31514693/157231728-68ff0c2b-302b-4322-b8be-c6939442dd15.png)
s

**Comment by Ayutac** [comment]
Concerning your first issue, how many cables are there between your power source and your power acceptor?

**Comment by mnsnownutt** [comment]
3 cables

**Comment by drcrazy** [comment]
Can't reproduce on TR 5.3.3

![image](https://user-images.githubusercontent.com/1382352/183221297-36836852-6859-4449-b359-96c40041a4ef.png)
