### ISSUE TITLE
Iron Furnace smelts raw ore blocks too fast

### ISSUE THREAD

**Issue by dwentz89** [TechReborn/TechReborn#2850]
**Describe the bug**
With default settings, the Iron Furnace smelts raw ore blocks in 8 seconds, but it should take 60 seconds.

**Steps to Reproduce**
1. Place an Iron Furnace.
2. Put a Block of Raw Iron in its top slot, and an Oak Slab in its bottom slot.
3. Observe that the single slab is more than enough to smelt the entire block.

**Environment (please complete the following information with the version):**
 - Minecraft 1.18.1
 - Fabric Loader 0.13.3
 - Tech Reborn 5.1.0

**Additional context**
I think the issue is in AbstractIronMachineBlockEntity on line 58, where it uses a hardcoded 200 instead of checking the recipe time.

**Comment by Ayutac** [comment]
`// default value for vanilla smelting recipes is 200`

Yeah, definitely our fault ^^°
