### ISSUE TITLE
(Basic) Jackhammer breaks gravel slower than hand

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2865]
MC 1.18.2
TR 5.2.0-beta.2

Other mods are present, but I doubt they are responsible for this

**Comment by drcrazy** [comment]
Intended behaviour. Jackhammer should chew stone-based blocks, like stone, diorite, etc.

**Comment by Ayutac** [comment]
@drcrazy all vanilla tools never break any block slower than being broken by hand. Are you sure using the jackhammer being slower than the hand instead of being equally as fast is intended and not by accident?
