### ISSUE TITLE
Combining energy items can be used to exceed max capacity

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2873]
for example take a full basic jackhammer and a full lithium battery, craft them into advanced jackhammer, that has now 110k/100k storage (when config wasn't changed.

EDIT: Traced the bug.
The adding happens here:
<https://github.com/TechReborn/TechReborn/blob/1.18/src/main/java/techreborn/utils/PoweredCraftingHandler.java>

**Comment by Technici4n** [comment]
This should actually be checked on the TR side, not on the energy side.

**Comment by Ayutac** [comment]
Should be taken care of with 5.4.0. Didn't i close this bug already?
