### ISSUE TITLE
Missing toasts

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2883]
I might have missed a few toasts, see 

6db3df3037e7ce596ce58ef8f7a3ac6b117b7bbb
2278b76d8d3c3b455c522b56622d416dad294e67
9ae1f53c7dcea91cbc48d232d765e8a21ac794e7

This likely happened because I did this parallel to the big datagen stuff, so my recipes before datagen-6 probably all miss toasts, except if they were added via datagen itself.

**Comment by Ayutac** [comment]
Note that I refactored the vanilla ones into datagen in #2885 , so e.g. toast for wither roses is not needed

**Comment by modmuss50** [comment]
Im not too worried about these, ideally all the recipes should be moved to datagen.
