### ISSUE TITLE
centrifuge doesnt read NBT tags (TechReborn-1.12.2-2.27.3.1084-universal.jar)

### ISSUE THREAD

**Issue by Garb-in-PacK** [TechReborn/TechReborn#2884]
centrifuge (and probably all machines that use cells in recipes) doesnt read NBT tags (that cells use to describe what liquid cell contains)

- First Step: craft 16 empty cells
- Second Step: put empty cells into centrifuge. if you put 1 cell then centrifuge return calcium dust and cell (recipe of cell with calcium), if you put 16 empty cells you get tin, electrum, copper and wolfram dust (recipe of 16 cells with lava)

 - Minecraft: 12.2
 - Mod Loader: forge 14.23.5.2860

**Comment by Ayutac** [comment]
Cannot reproduce in MC 1.18.2. Older versions of TR are not supported.

**Comment by Garb-in-PacK** [comment]
> Cannot reproduce in MC 1.18.2. Older versions of TR are not supported.

12.2 is still very popular. i feel sad hear that you dont want help 12.2 players with this problem

**Comment by modmuss50** [comment]
I understand that 1.12.2 and other versions are still popular, sadly it takes a lot of work to maintian TR for one version of Minecraft let alone many. I would love to maintain all versions to the same standard we aim for with the 1.18.2 version, but its just not possible.

Sorry.

**Comment by Garb-in-PacK** [comment]
> I understand that 1.12.2 and other versions are still popular, sadly it takes a lot of work to maintian TR for one version of Minecraft let alone many. I would love to maintain all versions to the same standard we aim for with the 1.18.2 version, but its just not possible.
> 
> Sorry.

I just want you to fix this problem. no update needed. just a small fix. give this problem a very low priority, but do not leave it in this state

**Comment by modmuss50** [comment]
I wont be fixing it, I work on TR in me free time and do what I find fun, fixing a bug in a codebase that I havent touched for a long time isnt fun for me.

The 1.12 code can be found here: https://github.com/TechReborn/TechReborn/tree/1.12 if you or someone else wishes to fix the issue.

I expect it will take some work to even get the code building again.
