### ISSUE TITLE
Storage unit can cause lag with player heads unfortunately

### ISSUE THREAD

**Issue by aria1th** [TechReborn/TechReborn#2888]
**Describe the bug**
Scrap box has player head recipe, which can result player head output.
But its NBT is with signature, and it can be different over time. 

**Steps to Reproduce**
1. produce player heads with scrap box
2. try to input 2 same player's head but with different signatures.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric

**Logs**
[Pastebin the log [e.g. `logs/latest.log`] and link it below:](https://spark.lucko.me/jSh625kNPk)

**Additional context**
its pain.

**Comment by Ayutac** [comment]
Can you generally put stuff with different nbt into storage unit?

**Comment by aria1th** [comment]
No, you can put it manually but auto input / transfer does not allow it. Same item with different NBT causes lag, due to its NBT comparison, and player head item is unique since it has different nbt .... and even changes when its dropped.
