### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Xen1290** [TechReborn/TechReborn#289]
@gigabit101 @modmuss50 I put here some questions, because I can't find any other place to ask.

- In README, I read that you have the permission to use Greg's textures, so why only a few are used? Textures are messed up, some guis are 512x,some are 256x, some have still the G of GregTech and others have useless slots, etc.. So maybe switch to almost only use greg textures?(Faithful or classic with some adaptations)
- Some machines will be removed (Ex. Digital Chest), maybe move that machines to TechRebornAddons? So maybe if someone want machines any new things from other gregtech(Ex. New Fusion Reactor, New Complex Recipes..), Addons is the right place, right?
If I have other questions, I'll update that issue.

**Comment by modmuss50** [comment]
I think we should use Greg's textures but without the G.

**Comment by Xen1290** [comment]
I think so

**Comment by gigabit101** [comment]
I agree maybe we should replace the "G" with a "T" why we are at it

**Comment by Carbon-Ghost** [comment]
Can you please make a list of all machines please ? I have all 16x16 textures, I just need the list of which one you need + I also have GUIs

**Comment by modmuss50** [comment]
I am thinking of rewriting all GUIs in code. I'm not sure if I will do though.

**Comment by Xen1290** [comment]
For me, the important thing is to match the GUI with classic gregtech style without the G, but with a T, like gigabit suggested.

**Comment by Carbon-Ghost** [comment]
Listen, I can do all of this + Replacing G by T But I just need a list ^-^ ( and a bit of time ).

**Comment by modmuss50** [comment]
I am recoding all of the guis, they will be a lot easier to maintain, and get the style correct/perfect.

**Comment by Carbon-Ghost** [comment]
All 16x16 I guess ^-^ Also can someone list me all GTR machines for me to do textures pls :P 

Gonna use classical ones, I have no time to do exp ones + Imo GTR should support IC2 classic in priority as a GT 4 revival for exp already exist, GT5u ( have all old stuff + new ones + new stuff based on old ones as a continuation and to blend in )

Gonna maybe do exp one if I have time ^^

**Comment by gigabit101** [comment]
Well the mod can be loaded by itself its stand alone

**Comment by Carbon-Ghost** [comment]
Yup but is still wip when standalone :/

**Comment by modmuss50** [comment]
Its only missing recipes. If someone makes a PR with recipes it will be done.

**Comment by Carbon-Ghost** [comment]
I can make a MT script but don't have time atm and have a massive headache, anyway for now I am out..

**Comment by modmuss50** [comment]
an MT isn't very useful, I guess I could port it thought...

**Comment by Xen1290** [comment]
Oh, I think not only GUI, but also blocks and items textures need to match original GregTech style.

**Comment by joflashstudios** [comment]
@Xen1290 this was something I noticed a while back - namely that all the machine textures are missing the border they had in GT.

**Comment by joflashstudios** [comment]
@Carbon-Ghost Are you saying GT5u is a GT4 revival? That's not correct. It's a continuation of GT5, which is drastically different from GT4.

**Comment by Carbon-Ghost** [comment]
It's not a perfect revival of GT4, but rather a continuation of GT4 / how GT5 was supposed to be as a lot of mechanics and stuff from GT4 was re-implemented.
