### ISSUE TITLE
QUESTION: Does the Industrial Chunk Loader require player to be on the server?

### ISSUE THREAD

**Issue by carTloyal123** [TechReborn/TechReborn#2899]
Simple question, does the chunk loader only work when the player is on the server, or will it continue to work when the player is offline? I looked through the block entity and did not notice any obvious check for this condition, so I assume that it works all the time. Would appreciate any input!

**Comment by Ayutac** [comment]
Theoretically it should work always, but our ChunkLoader is finnicky. Does this happen on a pure TR server or do you have other mods installed?

**Comment by carTloyal123** [comment]
I am running a Valhelsia Enhanced Vanilla server so a good few other mods are present. It looks like it will load some blocks all the time regardless of if the player is logged in or not while other things only stay loaded while the player is on. Example, a quarry plus quarry will continue to run while a copper pan from oxidized will not.

**Comment by Ayutac** [comment]
That is good to know. Valhesia is known to be troublesome for the chunk loader, but we don't know why yet. I'll close this issue and refer to #2914 for updates on this matter.
