### ISSUE TITLE
Buildcraft 7 incompatibility 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#29]
Currently crashes on startup with Buildcraft 7.0.6
Launches fine with Buildcraft 6 latest.

http://pastebin.com/tkMnQdxV

Possibly changes to the API in BC7, breaking this class as best I can tell.
https://github.com/TechReborn/TechReborn/blob/1f9600b33c2736a53b69f788f63ed999f743c70b/src/main/java/techreborn/compat/recipes/RecipesBuildcraft.java

**Comment by joflashstudios** [comment]
This is due to TechReborn changing the recipe for the quarry, and the fact that BC 7 moved the quarry from the factory module to the builders module. Shouldn't be too bad to fix.

**Comment by modmuss50** [comment]
When I tried to update it I could not find bc 7 on the forge maven

**Comment by modmuss50** [comment]
Fixed with https://github.com/TechReborn/TechReborn/commit/2ef2ff997f585e8634c96393def0071437dc4efa

**Comment by modmuss50** [comment]
If needed we can make it work with both versions?

**Comment by modmuss50** [comment]
Readded bc  6 support https://github.com/TechReborn/TechReborn/commit/b56487b680000a646fdd4667d08249d28d6534a0
