### ISSUE TITLE
Crash with GregTech 5.09.10 and TechReborn 0.5.6.1005+: Ambiguous Recipe

### ISSUE THREAD

**Issue by walkerjonny** [TechReborn/TechReborn#290]
Hi,

it seems that you have now an issue with GT5u.
There is an ambiguous recipe exception when updating from TechReborn 0.5.6.963 to newer builds while GregTech 5u 5.09.10 is already present.
http://pastebin.com/jBtNRyTt
Is there really no way for you to catch those Ambiguous Recipe Exceptions?

**Comment by modmuss50** [comment]
I can add a check for Greg tech and then not add that recipe

**Comment by joflashstudios** [comment]
@walkerjonny you're running GT5u alongside a GT2 clone? I'm honestly curious - why?

**Comment by modmuss50** [comment]
I did say that we weren't supporting it, but I dont see that it would be a problem if I was to fix it.

**Comment by modmuss50** [comment]
The recipe that is crashing it is just a basic macerator one:

https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/compat/recipes/RecipesIC2.java#L1221

**Comment by walkerjonny** [comment]
Oh, I didn't know that you do not support GT5u alongside with TechReborn. 
I have just recogniced that you aimed to make TechReborn compatible to as many mods as possible
I like to do both development stages to compare them and to have just fun with it.
By the way: Why macerating 10 Redstone Dust out of a Block of Redstone that was made out of 9 Redstone Dust usually? This is very unusual at all and it can be misused to produce infinite Redstone Dust (well, not very effective but still possible)...
The same applies to Lapis, too. And there it could become quite effective, too. 
Staying with the standard interchange of 1 Block -> 9 Dust and vice versa would make much more sense. 
If you want to force the users to use the Compressor and the Macerator then just disable the default recipes for Block of Redstone/Lapis.

**Comment by modmuss50** [comment]
Thanks for spotting that, I will fix the recipe to only give you 9, and I will not add that recipe when GT is installed.

**Comment by walkerjonny** [comment]
Well, as long as you do not change the output amount to something else than the usual amount the recipes should not become ambiguous even when you add them.
