### ISSUE TITLE
Can't see wiki

### ISSUE THREAD

**Issue by imcasper** [TechReborn/TechReborn#2901]
Wiki page:

 **Access was denied Error code 1020

You do not have access to wiki.techreborn.ovh.

The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.**

**Comment by MrMasrozYTLIVE** [comment]
If you from Russia - Mod Owner blocked access from Russia :( 
P.S. Checked by myself by enabling VPN
