### ISSUE TITLE
Auto crafting table no longer works with unstackable items

### ISSUE THREAD

**Issue by rafter613** [TechReborn/TechReborn#2903]
If you lock the recipe for the autocrafter, it won't use the last item, thus preserving the recipe. But this means unstackable items like water buckets, knives, or Croptopia food tools, can't be used in recipes. I've tried putting extra items in adjacent chests, or trying to pipe extra items in, but the recipe just won't proceed.
 
![2022-04-12_09 40 22](https://user-images.githubusercontent.com/90335682/162975566-cee40abb-e8db-409f-8fd8-06cb164ece41.png)

**Comment by Technici4n** [comment]
That is a known limitation, and unfortunately I don't think that there is a good fix.

**Comment by Ayutac** [comment]
for recipes with up to 3 ingredients + 1 unstackable this is still doable via configurations and not locking the recipe
up to 4 + 1 if you manually remove the results (a stack of them, not the single unstackable remainder)
up to 5 + 1 if you don't give energy, but that is probably a bad call
