### ISSUE TITLE
Fluid tank crash.

### ISSUE THREAD

**Issue by eszdman** [TechReborn/TechReborn#2906]
**Describe the bug**
When I tried to fill fluid tank using create mechanism's I got this crash log.

**Steps to Reproduce**
- Create lava pump using create and connect it directly to fluid tank.
- Wait until it filled.

**Screenshots**
![2022-04-16_15 39 49](https://user-images.githubusercontent.com/45270494/163675839-b07413dd-b782-4e33-bc4f-b87d3467df4a.png)

**Environment (please complete the following information with the version):**
 - Minecraft 1.18.2, create, tech reborn
 - Fabric mod loader

**Logs**
[crash-2022-04-16_15.52.12-server.txt](https://github.com/TechReborn/TechReborn/files/8499946/crash-2022-04-16_15.52.12-server.txt)
[latest.log](https://github.com/TechReborn/TechReborn/files/8499948/latest.log)

Pastebin the log [e.g. `logs/latest.log`] and link it below:
[crash-2022-04-16_15.52.12-server.txt](https://github.com/TechReborn/TechReborn/files/8499946/crash-2022-04-16_15.52.12-server.txt)
Latest log link: https://pastebin.com/zMGjpWAq

**Additional context**
I suggest it just overflowing.

**Comment by aria1th** [comment]
test with create's most recent version, mostly its create's code fault. It does not check condition with <= 0 and uses == 0 and commits transaction.

**Comment by eszdman** [comment]
I tested again, it's pump direction bug, also got a negative amount bug, probably I should open issue on create too
[crash-2022-04-16_17.04.32-server.txt](https://github.com/TechReborn/TechReborn/files/8500054/crash-2022-04-16_17.04.32-server.txt)
