### ISSUE TITLE
Chunk loaders don't seem to work on LAN worlds?

### ISSUE THREAD

**Issue by HacoKavanah** [TechReborn/TechReborn#2908]
Can I do something to fix this?

**Comment by Ayutac** [comment]
Can you ascertain they always work in SinglePlayer without LAN?

**Comment by HacoKavanah** [comment]
Doesn't seem to work in singleplayer either. You happen to know if some specific mod disables / prevents chunkloaders?

**Comment by Ayutac** [comment]
You didn't test in TR only? Usually you provide a list with other mods then in your initial post.

Chunkloader has been wacky for a while know andi would like to fix it. But i need some people trying it since my hardware is too bad atm

**Comment by HacoKavanah** [comment]
Yeah sorry, I'm usually very busy. Here is the list of mods. I can test tech reborn by itself shortly.

        - additionalentityattributes 1.0.0+1.18.2 via apoli
	- advanced_reborn 1.0.5
	- advanced_runtime_resource_pack 0.5.7
	- advdebug 2.3.0
	- adventurez 1.4.10
	- ae2 11.0.0-alpha.3
	- ae2wtlib 11.0.0-alpha.2
	- agape_space 0.5.7
	- alloy_forgery 2.0.13+1.18
	- apoli 2.3.3 via origins
	- appleskin 2.4.0+mc1.18.2
	- architectury 4.2.50
	- archon 0.2.3
	- attributefix 14.0.1
	- autoconfig1u 3.4.0
	- awesomedungeon 2.0.8
	- awesomedungeonend 1.0.1
	- awesomedungeonnether 1.0.1
	- awesomedungeonocean 2.0.6
	- betteranimalsplus 1.18.2-11.0.5
	- betterf3 1.2.4
	- betterfpsdist 1.18-1.7
	- bewitchment 1.18-17
	- biomemakeover 1.18.2-1.4.17
	- blue_endless_jankson 1.2.1 via jankson
	- bookshelf 13.0.12
	- bosses_of_mass_destruction 1.3.6-1.18.2
	- botania 1.18.2-431-FABRIC
	- byg 1.4-RC-9
	- caffeineconfig 1.1.0 via sodium-extra
	- calio 1.5.1 via apoli
	- cardinal-components 4.1.4
	- cardinal-components-base 4.1.4 via archon
	- cardinal-components-block 4.1.4 via cardinal-components
	- cardinal-components-chunk 4.1.4 via cardinal-components
	- cardinal-components-entity 4.1.4 via archon
	- cardinal-components-item 4.1.4 via cardinal-components
	- cardinal-components-level 4.1.4 via cardinal-components
	- cardinal-components-scoreboard 4.1.4 via cardinal-components
	- cardinal-components-world 4.1.4 via cardinal-components
	- charm 4.0.0
	- clickadv 2.5
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- cloth-config-lite 2.0.6 via omega-config-gui
	- cloth-utils-v1 2.0.54 via computercraft
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_flowpowered_flow-math 1.0.3 via dimdoors
	- com_github_dimensionaldevelopment_poly2tri_java 0.1.1 via dimdoors
	- com_github_llamalad7_mixinextras 0.0.8 via debugify
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- comforts 1.1.2-1.18.2
	- completeconfig 1.4.0
	- computercraft 1.100.5
	- coxinhautilities 1.1.1+1.18.2
	- crowdin-translate 1.4+1.18.2 via the_aether
	- curse_maven_wthit-3707010 440979 via dimdoors
	- customportalapi 0.0.1-beta50-1.18 via the_aether
	- dark-enchanting 0.7.0+1.18.2
	- dark-loading-screen 1.6.11
	- darkutils 10.0.4
	- debugify 1.8.1
	- dimdoors 4.0.4
	- dml-refabricated 1.18.2
	- dml-refabricated-base 1.18.2 via dml-refabricated
	- dml-refabricated-events 1.18.2 via dml-refabricated
	- dml-refabricated-modular-armor 1.18.2 via dml-refabricated
	- dml-refabricated-rei 1.18.2 via dml-refabricated
	- dmlsimulacrum 0.5.3-beta
	- dynview 1.18.2-2.1
	- earthbounds 1.1.0a
	- earthtojavamobs 1.8.0+1.18.2
	- ecologics 1.5.2
	- eer 1.0.2+1.18
	- eldritch_mobs 1.11.0
	- enchant_giver 1.1.0 via mcdw
	- entityculling 1.5.1
	- essential-container 1.0.0
	- essential-loader 1.0.0 via essential-container
	- extraorigins 1.18-10
	- fabric 0.51.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.0+bd8a4a1860 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.3+kotlin.1.6.20
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via betterf3
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.13.3
	- fabricshieldlib 1.5.3-1.18
	- farsight 1.18-1.8
	- ferritecore 4.2.0
	- fiber 0.23.0-2 via botania
	- forgottengraves 1.18.2-2.5.1
	- friendsandfoes 1.3.4
	- gearreborn 1.18.2-0.1.11
	- geckolib3 3.0.38
	- graveyard 1.7
	- gud_recipe_confidence 1.0.2 via the_aether
	- hwg 1.1.5
	- immersive_weathering 2.4.0
	- impersonate 2.4.1 via bewitchment
	- incubus_core 1.6.6+1.18.2 via the_aether
	- indium 1.0.2+mc1.18.2
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kanos_config 0.2.0+1.14.4-1.19 via pehkui
	- keymap 0.3.2-beta.4+1.18.1-fabric
	- kibe 1.9.7-BETA+1.18
	- krypton 0.1.9
	- ktdatataglib 1.6.5+1.18.2 via dml-refabricated
	- lazydfu 0.1.2
	- libblockattributes 0.10.2 via pipeplus
	- libblockattributes_core 0.10.2 via libblockattributes
	- libblockattributes_fluids 0.10.2 via libblockattributes
	- libblockattributes_items 0.10.2 via libblockattributes
	- libgui 5.3.2+1.18.2 via dark-enchanting
	- libmultipart 0.7.3 via pipeplus
	- libnetworkstack 0.6.0 via pipeplus
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.3
	- limitedchunks 1.18.2-2.4
	- lithium 0.7.9
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- magna 1.7.0-1.18-pre1 via modern_industrialization
	- matrix 1.0.0 via dimdoors
	- mca 7.2.1+1.18.2
	- mcda 2.0.5
	- mcdar 1.4.5
	- mcdw 4.2.5
	- medievalorigins 1.18.x-4.0.2
	- medievalweapons 1.1.9
	- memorysettings 1.18.2-2.1
	- minecraft 1.18.2
	- mm 2.3 via fabricshieldlib
	- moborigins 1.8.1
	- modern_industrialization 1.1.0-alpha.01
	- modmenu 3.1.1
	- modsettings 1.1.0+1.18.1
	- moretags 3.0.3 via the_aether
	- mostructures 1.4.1+1.18.2
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- mythicmetals 0.13.1
	- mythicmounts 1.18.2-6.0
	- naturescompass 1.18.2-2.0.3-fabric
	- notenoughcrashes 4.1.6+1.18.2
	- observable 2.2.3
	- omega-config 1.2.3-1.18.1 via archon
	- omega-config-gui 1.2.3-1.18.1 via dark-enchanting
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_jgrapht_jgrapht-core 1.1.0 via dimdoors
	- org_joml_joml 1.10.2 via sodium
	- origins 1.4.1
	- origins-classes 1.3.0
	- owo 0.6.0+1.18
	- patchouli 1.18.2-67-FABRIC
	- pehkui 3.2.2+1.14.4-1.19
	- pigpen 8.0.1
	- pipeplus 1.18.2-0.4.0
	- playerabilitylib 1.5.0 via bewitchment
	- polymorph 0.0.20-1.18.2
	- pugh_tools 1.2.5 via treeaxe
	- reach-entity-attributes 2.1.1 via bewitchment
	- reborncore 5.2.0-beta.2
	- reeses-sodium-options 1.4.2
	- rightclickharvest 1.5.1
	- roughlyenoughitems 8.1.449
	- runelic 11.0.1
	- satin 1.7.2 via the_aether
	- serverpause 1.0.0
	- simple_pipes 0.7.2 via simple_pipes_dep_container
	- simple_pipes_dep_container 0.7.2
	- simplevoidworld 4.0.0
	- skinlayers 1.4.3-mc1.18.2
	- smoothboot 1.18.2-1.7.0
	- smoothchunk 1.18.2-1.7
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.3
	- starlight 1.0.2+fabric.89b8d9f
	- step-height-entity-attribute 1.0.0 via bewitchment
	- subterrestrial 1.0.2
	- team_reborn_energy 2.2.0 via coxinhautilities
	- techreborn 5.2.0-beta.2
	- terrablender 1.1.0.99
	- terraform-wood-api-v1 3.0.0 via bewitchment
	- the_aether 1.6.8+1.18.2
	- things 0.2.16+1.18
	- timeoutout 1.0.0+1.18
	- toofast 0.0.2.3
	- treeaxe 1.1.40
	- trinkets 3.3.0
	- vmp 0.2.0+beta.3.17
	- voidz 1.0.6
	- waystones 2.5.0
	- wthit 4.8.1
	- xaerominimap 22.5.0
	- xaeroworldmap 1.20.6

**Comment by HacoKavanah** [comment]
I also just noticed that the chunk loader provided by "Kibe Utilities" doesnt work either, so I'd say this is mostly a compatibility issue.

**Comment by Ayutac** [comment]
We are all busy u_u

Kibe works on kotlin, so i couldn't have copied much from there. But good to know it doesn't work to. Immersive portals seems to have their chunk loading in order though...

**Comment by aria1th** [comment]
too many mods to check, but pure tech reborn works... it does not load entity(living), it only loads as 'redstone-loaded', so block or tile entities are loaded.

**Comment by HacoKavanah** [comment]
Yeah, not trying to undermine your busyness :3 

I am now going through the mods by a small snippet at a time. The fact that the chunk loader doesn't load living entities is also good to know.

**Comment by Ayutac** [comment]
> too many mods to check, but pure tech reborn works... it does not load entity(living), it only loads as 'redstone-loaded', so block or tile entities are loaded.

does pure TR chunkloader work when you are in LAN?

**Comment by aria1th** [comment]
as long as I check with Carpet script, seems its loaded

**Comment by HacoKavanah** [comment]
Update: The issues I was having were caused by someaddon's mods. Limited Chunkloading was a gamechanger for our LAN world, but it also seemed to add a little snippet of code that would also override any chunk loaders after 10min had passed. Dynamic View meanwhile improved TPS a lot but also contributed in smoothly unloading chunks, which also would override chunk loaders. Thankfully, changing some settings in the configs of both mods allowed me to get my chunk loaders up and running! Thank you guys for being so open to help and thank you for the "chunk loader doesn't work on living entities" thing cause that while also helping this case also changed our mobfarm building plans for the better before it was too late! ;3

I have a smaller issue/compatibility problem I'll be posting right after this. :P
