### ISSUE TITLE
[1.17.1] Recycler processes blacklisted items

### ISSUE THREAD

**Issue by MSandro** [TechReborn/TechReborn#2909]
**Describe the bug**
I have added an item to the recycler blacklist in the machines.json but I am still able to pipe blacklisted items in the machine. I mean this would be okay if the machine wouldn'd process the item, but it do.

**Steps to Reproduce**
- Scrap is blacklisted by default, so just pipe scrap into the recycler
- the recycler will start to process the scrap

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: FABRIC

**Comment by Ayutac** [comment]
Can confirm for 5.2.0-beta.3

**Comment by MSandro** [comment]
any news here? It would be nice if it could be fixes (FOR MC 1.17.1 TOO, PLEASE)

**Comment by Ayutac** [comment]
Backport almost certainly won't happen.

I didn't have time to work on this, and neither did the other devs as far as I'm aware

**Comment by drcrazy** [comment]
It is not possible to insert blacklisted items via UI, only via automation.
Blacklist will work if you check 'Filter input' checkbox on slot config. 

Checked on 1.19.
