### ISSUE TITLE
1.8.8 Update blog thing

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#291]
https://modmuss50.me/shots/2015-11-23_20-39-52.png

Nothing works, no textures for anythig.

**Comment by Xen1290** [comment]
Without Ic2 or thermal expansion, everything is useless, no e-net, no cross-mod compatibility, etc... I think you should wait until 1.9, because for example cofh will never update to 1.8. 1.9 is the selected modded version as far as I know.

**Comment by modmuss50** [comment]
We have a built in E-Net, we are supporting the 1.8 port of RF. ATM 1.8.8 is just a bit of fun. I still aim on getting a stable 1.7.10 build at somepoint

**Comment by Xen1290** [comment]
ah, now I understand

**Comment by modmuss50** [comment]
Blocks without jsons: https://modmuss50.me/shots/2015-11-24_21-14-27.png
Items without json: https://modmuss50.me/shots/2015-11-24_21-34-27.png

**Comment by modmuss50** [comment]
https://modmuss50.me/shots/2015-11-25_21-03-06.png

**Comment by modmuss50** [comment]
Builds are now on jenkins:
http://modmuss50.me:8080/job/RebornCore-1.8.8/
and
http://modmuss50.me:8080/job/TechReborn-1.8.8/

Its not that far off from a public beta, just need to register all of the textures.

**Comment by modmuss50** [comment]
Things should be getting stable now. Testing would be appreciated.
