### ISSUE TITLE
[Compatibility Issue] Solid Canning Machine Being Picky About Tin!

### ISSUE THREAD

**Issue by HacoKavanah** [TechReborn/TechReborn#2910]
Unlike other machines in Tech Reborn, Solid Canning Machine only accepts tin from tech reborn. Modern industrialization tin, for example, is a no go. Which is weird since other machines and recipes do accept this! If this quality of life change could be made, I'd appreciate it!

Minecraft 1.18.2 - Fabric - TechReborn-5.2.0-beta.2.jar

**Comment by Ayutac** [comment]
No problem
