### ISSUE TITLE
Fluid Replicator producing when multiblock empty

### ISSUE THREAD

**Issue by justastranger** [TechReborn/TechReborn#2913]
**Describe the bug**
When the multiblock ring contains no fluid, the fluid replicator will still produce water and hydrogen when given uu matter. Giving 1 uu matter produces water while giving 2 or more produces hydrogen.

**Steps to Reproduce**
 - Place fluid replicator with the multiblock and power
 - Leave the ring empty
 - Add uu matter to the input slot

**Environment:**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric
 - Tech Reborn: 5.1.0

**Comment by Ayutac** [comment]
Can confirm for 5.2.0-beta.3, just that I get lava instead of water
