### ISSUE TITLE
Chunk loader doesn't work on some modpacks

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2914]
While our chunk loader does appear to work on stand-alone (cf. #2908), it does not so on some modpacks apparently, e.g. ValhelsiaEnchancedVanilla 1.1.2 (cf. https://discord.com/channels/159382191292416000/368133674626973696/967046327387168778)

This issue is to collect such appearances and eventually hunt this bug down...

**Comment by Ayutac** [comment]
Chunkloader works on [Ayutac's Best Friends](https://www.curseforge.com/minecraft/modpacks/ayutacs-modpack), so besides some QoL mods we can probably cross out Croptopia

**Comment by Arzumify** [comment]
New appearance of broken chunkloaders on the vinegar mod pack. More specifically they seem to wipe create tanks and make create machines go much slower than if a player is there.

https://github.com/xenanthropy/vinegar-modpack

**Comment by modmuss50** [comment]
Closing this as there is no recent reports of this. Please open an new issue if this is still the case in 1.21
