### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#292]
We would like to change the license of TechReborn to the MIT license. But first I need the permission of all of the people who have contributed.

@Amamiya-Nagisa 

Please reply to this issue saying that you are happy for us to change the license of your code.

**Comment by gigabit101** [comment]
I agree to the change

**Comment by Mattabase** [comment]
I agree to the change

**Comment by Tntrololol** [comment]
I agree to the change

**Comment by primetoxinz** [comment]
I agree to the change

**Comment by UniversalLP** [comment]
I agree to the change

**Comment by joflashstudios** [comment]
Sounds good.

**Comment by MrBretze** [comment]
I agree to the change

**Comment by TehporP** [comment]
go ahead     do whatever you want :)

**Comment by TheQuantumGeneral** [comment]
Fine by me, go ahead.

**Comment by Mj11jM** [comment]
go ahead

**Comment by Mazdallier** [comment]
It doesn't change anything for the translation work so go ahead !

**Comment by modmuss50** [comment]
@Amamiya-Nagisa are you around?

**Comment by TehporP** [comment]
@modmuss50
He agree    he dont know how to use github

**Comment by modmuss50** [comment]
ok thanks for that :)

**Comment by Carbon-Ghost** [comment]
I also agree, but seems like I was forgotten xD Oh well not really important as I don't understand licenses and haven't done much anyways xD

**Comment by liach** [comment]
@Carbon-Ghost You was not in [this list](https://github.com/TechReborn/TechReborn/graphs/contributors)

**Comment by Carbon-Ghost** [comment]
I used to though :C ( and I did some textures and was the official IC2 classic bug finder ) :C

**Comment by modmuss50** [comment]
You didn't commit, so it would have been classed as the other persons work

**Comment by Carbon-Ghost** [comment]
oh kk ^-^

Derp :P
