### ISSUE TITLE
[Compatibility Glitch] Infinite Leaves with Chest Cavity mod

### ISSUE THREAD

**Issue by HacoKavanah** [TechReborn/TechReborn#2923]
Shifting leaves, an item from the Chest Cavity mod, can be used to craft leaves. However, the auto crafting table doesn't ever consume these shifting leaves and just keeps making more leaves. Why is this happening?
![image](https://user-images.githubusercontent.com/87395651/165160708-c2fa54af-59a7-42f1-97dd-483c196c79dd.png)

 - Minecraft: [1.18.2]
 - Mod Loader: [Fabric]

**Comment by Ayutac** [comment]
tbf infinite leaves is a thing in vanilla minecraft. But I'll look into it :)

**Comment by Ayutac** [comment]
can confirm bug on TR 5.2.0-beta.3

**Comment by Ayutac** [comment]
Not a TR bug, see [#chestcavi](https://github.com/Tigereye504/chestcavity/issues/64)

**Comment by Tigereye504** [comment]
This has been fixed in CC version 2.16.2
