### ISSUE TITLE
EnergyPack item can cause lag (0.6mspt per player)

### ISSUE THREAD

**Issue by aria1th** [TechReborn/TechReborn#2924]
**Describe the bug**
Battery / energy pack items can cause lag, especially energy pack lag can't be prevented since it does not have toggle.

**Steps to Reproduce**
- put energy pack / battery item in inventory, wear quantum armors to check mspt

**Screenshots**

![2022-04-26_13 29 07](https://user-images.githubusercontent.com/35677394/165221436-cab2c7ae-97bc-4246-9dbe-db21c82b7220.png)
(https://spark.lucko.me/4zJ0nhHj1u)

**Environment (please complete the following information with the version):**
 - Minecraft:  1.18.1+
 - Mod Loader: fabric

**Logs**
[Pastebin the log [e.g. `logs/latest.log`] and link it below:](https://spark.lucko.me/4zJ0nhHj1u)

**Additional context**
It generates 0.6mspt per player with quantum armor set + laportonic energy pack (i7-7900 server), which means 10 player can generate 6 mspt... linearly.

**Comment by modmuss50** [comment]
Profiler link is dead and 1.18.1 is no longer supported.
