### ISSUE TITLE
Game crashes when you attach Wireless Energy Heater to TechReborn's Generators

### ISSUE THREAD

**Issue by QuantumEPR** [TechReborn/TechReborn#2927]
**Describe the bug**
For any TechReborn Generator, if one side has the Wireless Energy Heater Block from IronFurnaces attached directly and that side has ~~auto-output~~ auto-input on, the game crashes.

**Steps to Reproduce**
1. Place any TechReborn Generator down.
2. Place the Wireless Energy Heater Block on any of the generator's sides.
3. Toggle on ~~auto-output~~ auto-input of that attached side.
4. Client/Game Server Crashes.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric 0.13.3
 - Fabric API: 0.46.6+1.18
 - IronFurnaces 1.18-3.0.0 Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
- [Crash Report](https://gist.github.com/QuantumEPR/5d937265a99aa30bc9977e54c7b8e16b)
- [Log](https://gist.github.com/QuantumEPR/a75ddb966c737bdc810d7e46213938b9)

**Additional context**
I have also submitted a crash report to IronFurnaces' repo.

**Comment by Ayutac** [comment]
> Minecraft: 1.18.1

I'm afraid we wouldn't backport a solution anyway. But I will see if it holds in current mods.

**Comment by Ayutac** [comment]
an obvious workaround is to place a hopper between the machine and the furnace.

**Comment by aria1th** [comment]
Iron furnaces has weird slot behavior, not only wireless heater will be the problem. It actually only outputs into vanilla storage (chests, barrels) but none of modded inventories, so I suggest opening issue there.... I can't even find its updated source code unfortunately.

It will void items when iron furnaces try to output items into 'sidedInventory' :W

**Comment by Ayutac** [comment]
Cannot reproduce in 1.18.2. For example, works with solar generators. Also, generators usually have no auto-output except fluids. Tried with a grinder and auto output, but everything worked fine as well. Can you give your exact set-up and configuration?

**Comment by QuantumEPR** [comment]
My mistake. I wanted to say it's caused by auto-input. I am unsure if auto-output has the same problem. 

I just attempted with Thermal and Diesel Generator in 1.18.2. The game consistently crashes. It seems to be the same problem reading from the crash report/log. 

```
Caused by: java.lang.NullPointerException: Cannot read the array length because "availableSlots" is null
```

#### Exact Steps with Image
Here we have all five "generators." (Solar does not have an item output UI and does not have Generator in its name)
![2022-04-27_13 24 11](https://user-images.githubusercontent.com/32603388/165624829-fa7ffcca-33b7-4af4-83ff-3f62733fe856.png)

Now, for example, we choose diesel.
![2022-04-27_13 24 14](https://user-images.githubusercontent.com/32603388/165624867-0cd41a99-3dc3-431b-a7ca-5f87364df881.png)

We select the tab to configure slots.
![2022-04-27_13 24 18](https://user-images.githubusercontent.com/32603388/165624885-7c2c7a8e-542d-49f1-b110-70d800428ac0.png)

We also choose the Up direction as an example. Enable input on the Upside, and enable **auto-input**.
![2022-04-27_13 24 24](https://user-images.githubusercontent.com/32603388/165624892-a7ac8988-30ff-48de-86cb-7b934b6a1009.png)

Get a wireless heat transmitter .
![2022-04-27_13 24 45](https://user-images.githubusercontent.com/32603388/165624907-9d61e95f-c0fd-490f-8502-bb30564308f6.png)

Place it on the upside -> Game Crashes. (No Image for this since the game exits into the launcher's crash log page. Here I used MultiMC.)

#### The Idea
- The problem naturally occurs when you have used your generator with an auto-input setup for fuel intake and decide to repurpose that side with a wireless heat transmitter without changing the side settings. 
- Now, suppose other faces are occupied by machines (many people would attach machines/chests to generators when they don't want to make cables). 
- You decide to remove the top chest that was supposed to be fuel intake (where auto-input is enabled) and put your wireless energy heater there since you need energy now to smelt something.
- The game crashes and cannot be logged into without removing the block by either disabling one of the mods and logging into the game, so one of the blocks is removed or using Minecraft world editors like [Amulet](https://www.amuletmc.com/) to edit the ticking block away manually.


#### Logs
[New Crash Report](https://gist.github.com/QuantumEPR/4bd408279012c58aa3ddf66ff21b1a38)
[New Log](https://gist.github.com/QuantumEPR/a15d9eb46a81caed112b5765e6652996)

**Comment by QuantumEPR** [comment]
> Cannot reproduce in 1.18.2. For example, works with solar generators. Also, generators usually have no auto-output except fluids. Tried with a grinder and auto output, but everything worked fine as well. Can you give your exact set-up and configuration?

Yes, the exact set-up is posted above.

**Comment by Ayutac** [comment]
I noticed, but didn't have time to check again atm, sorry.

**Comment by Ayutac** [comment]
can confirm now

**Comment by drcrazy** [comment]
Please, report this issue to Wireless Heat Emitters.

TR uses Fabric API to get items from adjacent inventory and have no ability to stop crash in FAPI if that adjacent inventory doesn't play nicely.
