### ISSUE TITLE
Industrial grinder multiblock checking bug

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#293]
I put it like this 
![image](https://cloud.githubusercontent.com/assets/2989009/11607149/43e9dd74-9b44-11e5-980d-3cce9cbee043.png)
And it works
![image](https://cloud.githubusercontent.com/assets/2989009/11607150/4c8f11d8-9b44-11e5-91db-fc8e3904bb48.png)

Edit:same for implosion compressor, but it seems that the blast furnance and vacuum freezer has no problem

**Comment by modmuss50** [comment]
1.7.10 or 1.8.8?

**Comment by wormzjl** [comment]
1.7.10 for sure

**Comment by modmuss50** [comment]
Ok thanks, wasn't sure if it was something that I broke during porting.

**Comment by gigabit101** [comment]
GG @modmuss50
