### ISSUE TITLE
JSON bug

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2934]
on current 1.18 branch
![excerpt](https://user-images.githubusercontent.com/7873396/165946814-dd53edfd-818d-43f5-8f38-dc3321eac646.png)
I cannot discern where this error comes from.

**Comment by ghost** [comment]
#2919 "tag": "c:enderpearl_dusts" **->** c:ender_pearl_dusts

**Comment by Ayutac** [comment]
Sadly that is not the cause, but another bug. Fixed that one though, thanks

**Comment by drcrazy** [comment]
Can't reproduce in dev env.
