### ISSUE TITLE
FluidUtils.getFluidName null point

### ISSUE THREAD

**Issue by ToutatisGc** [TechReborn/TechReborn#2937]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because the return value of "net.minecraft.class_3610.method_15759()" is null
	at reborncore.common.fluid.FluidUtils.getFluidName(FluidUtils.java:187)
	at techreborn.items.DynamicCellItem.method_7864(DynamicCellItem.java:170)
	at net.minecraft.class_1799.method_7964(class_1799.java:622)
	at net.minecraft.class_1799.method_7950(class_1799.java:659)
	at net.minecraft.class_310.method_1485(class_310.java:770)
	at net.minecraft.class_1126.method_4795(class_1126.java:36)
	at net.minecraft.class_1121.method_4798(class_1121.java:48)
	at net.minecraft.class_310.method_1535(class_310.java:783)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_310.method_1546(class_310.java:782)
	at net.minecraft.class_310.<init>(class_310.java:576)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at reborncore.common.fluid.FluidUtils.getFluidName(FluidUtils.java:187)
	at techreborn.items.DynamicCellItem.method_7864(DynamicCellItem.java:170)
	at net.minecraft.class_1799.method_7964(class_1799.java:622)
	at net.minecraft.class_1799.method_7950(class_1799.java:659)
	at net.minecraft.class_310.method_1485(class_310.java:770)
	at net.minecraft.class_1126.method_4795(class_1126.java:36)
	at net.minecraft.class_1121.method_4798(class_1121.java:48)
	at net.minecraft.class_310.method_1535(class_310.java:783)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_310.method_1546(class_310.java:782)
	at net.minecraft.class_310.<init>(class_310.java:576)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6020019720 bytes (5741 MiB) / 8162115584 bytes (7784 MiB) up to 8162115584 bytes (7784 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 56251.00
	Virtual memory used (MB): 34497.93
	Swap memory total (MB): 23552.00
	Swap memory used (MB): 1648.79
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx7782m
	Fabric Mods: 
		ae2: Applied Energistics 2 10.1.0-beta.3
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.8.51
		bclib: BCLib 1.3.5
		betterf3: BetterF3 1.2.2
		betternether: Better Nether 6.0.11
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fallingtree: FallingTree 3.2.1
		ic2: Industrial Craft 2 2.9.70+ex118
		identity: Identity 1.16.0-1.18.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap-api-fabric: JourneyMap API 1.18.1-1.8-fabric-SNAPSHOT
		journeymap-fabric: Journeymap 5.8.1
		mcwdoors: Macaw's Doors 1.0.6
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.22
		nullscape: Nullscape for Fabric 1.1
		omega-config: OmegaConfig 1.0.4
		optifabric: OptiFabric 1.13.0
		playerabilitylib: Pal 1.5.0
		reborncore: Reborn Core 5.1.0
		seamless_loading_screen: Seamless Loading Screen: Refabricated 2.0+1.18.1
		seedfix: Seed Fix 1.0.0
		skinlayers: 3d Skin Layers 1.4.3-mc1.18.2
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		yuushya: Yuushya Beta-0.10.2
	Launched Version: 1.18.1-VOID-GC
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.18.1_HD_U_H6
	OptiFine Build: 20220324-210209
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS PTGI HRR Test 2.1.zip
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.1
	OptiFine jar version: OptiFine_1.18.1_HD_U_H6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: E:/MC/VOIDClient/.minecraft/versions/1.18.1-VOID-GC/.optifine/OptiFine_1.18.1_HD_U_H6/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by Ayutac** [comment]
In which context did this error occur? Does it also happen in TechReborn only? Note that 1.18.1 isn't supported, a fix is most likely only happening in 1.18.2

**Comment by aria1th** [comment]
Can you tell us what was you doing at that time? I suspect this is problem with some mod defining Non-placeable fluid, and returning defaultState or Block as null instead of Blocks.AIR.

**Comment by ToutatisGc** [comment]
> In which context did this error occur? Does it also happen in TechReborn only? Note that 1.18.1 isn't supported, a fix is most likely only happening in 1.18.2

I found a problem with the industrailcraft mod. For some unknown reason this mod didn't work and didn't report errors, so I accidentally ignored it.
