### ISSUE TITLE
REI stops Solar Panel configuration from working

### ISSUE THREAD

**Issue by MadProbe** [TechReborn/TechReborn#2942]
**Describe the bug**
Basic day / night rate of solar panels and solar panel capacity multiplier are not applied when ancommodating values have been modified in generators.json config while other generators' generation rates have been applied.

**Steps to Reproduce**
- Delete all mods with their respective configs and Install Tech Reborn with all necessary dependencies.
- Launch Minecraft to generate the default Tech Reborn configs.
- Change solarPanelBasic.basicDayRate.value to 6, solarPanelBasic.basicNightRate.value to 1 and solarPanelGeneral.internalCapacity.value to 250 (for example)
- Launch Minecraft and assert the fact that day & night generation rate / capacity of any solar panel were not changed.

**Screenshots**
> none

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: Fabric
 - TechReborn version: 5.2.0-beta.3

**Logs**
I don't know if you will find there anything useful because no errors were logged.
https://pastebin.com/d4kqDNmC

**Additional context**
I want to adjust generation rate of solar panels to make them more viable for their cost.
I have tried to convert the solar panel's config keys from camel case to snake case but these configurations have been erased and not applied.
I have PermanentLightGenerator addon installed and I don't know if it somehow matters and creates problems and if it is, please close the issue immediatly; but please not reject the issue just for the fact of presence of this modification in my mod list.

**Comment by Ayutac** [comment]
Tried with basic solar panel in clean 5.2.0-beta.3 TR set-up. Changing the config worked as intended, Cannot confirm bug. 

Try out if the error persists in a TR-only environment and if so, tell exactly what solar panel you tried with what values.

**Comment by MadProbe** [comment]
Additional Information:
- generators.json: https://pastebin.com/A2hpAU8r (Some non-solar-panel values are not final and high enough to easily notice the fact that they are applied)
- Somehow addiction of Roughly Enough Items 8.1.457 breaks the configuration and modified values are not applied to only solar panels and I can confirm that modified panel rate values worked for me without Roughly Enough Items installed.
- Logs: https://pastebin.com/wTc3xbdD

**Comment by Ayutac** [comment]
can confirm, REI causes the issue. WTF???

**Comment by drcrazy** [comment]
Can't reproduce anymore in 1.19.

**Comment by MadProbe** [comment]
> Can't reproduce anymore in 1.19.

Does this mean that 1.18.2 version is not supported?
If it's still supported I suggest to check if it still reproducable and reopen the issue as this issue would still persist!

**Comment by Ayutac** [comment]
It's not a breaking bug in 1.18.2. Also we have no idea what caused it there.

**Comment by TheStaticVoid** [comment]
I know this is an old issue, however I'm running into the exact issue on 1.19.2 as described above. The inclusion of REI in my modlist causes the settings in generators.json to be ignored and revert to their default values. I wasn't sure if it would be best to make a new issue or continue off this one.

**Mod Versions:**
- Architectury 6.5.82
- Cloth Config API 8.2.88
- Fabric API 0.76.0
- Fabric Language Kotlin 1.8.21
- Roughly Enough Items 9.1.595
- TechReborn 5.4.0

Fabric version: 0.14.19

Basic generator settings: 
![image](https://github.com/TechReborn/TechReborn/assets/6089108/29ff5065-6745-4f69-bcc4-aa47651d1cc3)
Actual values in game:
![image](https://github.com/TechReborn/TechReborn/assets/6089108/96f5b84d-b03c-4d4e-ad5e-cc989ccd4ba5)
Without REI:
![image](https://github.com/TechReborn/TechReborn/assets/6089108/ece21be6-a4cb-4dd3-8b4d-e70c85fa8a41)


It is not a visual thing with the tooltip, it effects the generation rate when the panel is placed in world as well.

Additionally, I've changed the values for the Dragon Egg Siphon and it actually generates at the rates I specify, but the tooltip with REI still shows the old rate.
