### ISSUE TITLE
Iron alloy furnace derp

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#295]
Edit: Seems that this bug only happens with the iron alloy furnace, the electric one works well

Feed with 1 gold and 1 silver ingot -> you get 2 electrum ingots, which is normal
Feed with 1 stack of gold and silver. it becomes...
![image](https://cloud.githubusercontent.com/assets/2989009/11670250/7bffd1a6-9e09-11e5-9116-1af34688fd3c.png)
Where item in the first slot is consumed by 4, and the second slot consumed by 3???

And this happens when I tries to make some red alloy ingots
![image](https://cloud.githubusercontent.com/assets/2989009/11670317/d2d1a20c-9e09-11e5-8082-772d8a84133f.png)

Also by NEI copper + zinc should give brass but I got bronze instead... etc
Seems that the recipes are totally messed up, Any idea about the cause?

**Comment by wormzjl** [comment]
Also, when broken by a pickaxe this thing drops a machine block, but it does not require a machine block when crafting

**Comment by modmuss50** [comment]
Are the ones in NEI showing up correctly? If so its an issue with the logic.

**Comment by wormzjl** [comment]
Yeah nei was fine
