### ISSUE TITLE
Raw Iron, gold, copper in grinder

### ISSUE THREAD

**Issue by RechargeableAA** [TechReborn/TechReborn#2958]
The Grinder doesn't recognize raw ores.
I've seen in the source code that raw ores are registered,  but the latest version of the mod (posted 2 days ago) doesn't use this feature.
I've seen other issues posted of the same problem, but all seem to have been blown off, or ignored. 

**Steps to Reproduce**
put raw ore in, get nothing out.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/36073006/169716180-5742b9d3-1ab3-4084-929f-d01cbe21d153.png)

**Environment**
 - Minecraft: [1.18.2]
 - Mod Loader: [Fabric 0.14.6]
 - TechReborn v5.2.0
 - RebornCore v5.2.0

**Comment by drcrazy** [comment]
Intended behaviour. Can you, please, link here these other issues, so they will also get a proper response?
