### ISSUE TITLE
Insulated cables not transmit power to non-insulated cables

### ISSUE THREAD

**Issue by 1a2s3d4f1** [TechReborn/TechReborn#2965]
**Describe the bug**
Insulated cables can not transmit power to non-insulated cables.

**Steps to Reproduce**
- First Step
Put a Insulated cable(such as copper cable) to link a Creative Solar Array.
- Second Step
- Put non-insulated copper cable to link machine or light.

**Screenshots**
![2022-05-26_14 04 15](https://user-images.githubusercontent.com/40121560/170427460-09194ae4-266a-4564-b070-9b08582f70cb.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: fabric

**Comment by Ayutac** [comment]
is this a problem though?
