### ISSUE TITLE
Crash trying to connect bluepower tubes to machine

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#297]
http://pastebin.com/XxT7SAmK

**Comment by modmuss50** [comment]
Do you happen to have a multi part cable next to a BC tube? It could also be an issue with uncomplication as you also have that installed.

**Comment by wormzjl** [comment]
No I only have the industrial grinder+bp tube

**Comment by modmuss50** [comment]
Thats strange as that crash is coming from a multi part ic2 cable.

**Comment by wormzjl** [comment]
From my memories ic2 cables shouldn't be multipart?

**Comment by modmuss50** [comment]
We add support for them, and this error is being called from one. Can you still load the world?

**Comment by wormzjl** [comment]
No it keeps crashing :p

**Comment by modmuss50** [comment]
Gah, sorry.

**Comment by wormzjl** [comment]
Since you have mentioned adding fmp support for ic2 wires, did you replace the original one or just added some asm?

**Comment by modmuss50** [comment]
They get converted when you try to place a cover on them, there is no asm or replacement

**Comment by wormzjl** [comment]
Hmm I haven't placed any covers, perhaps you can add a config for that to prevent such problems?

**Comment by modmuss50** [comment]
I get a different crash. But I can confirm.

**Comment by modmuss50** [comment]
https://gist.github.com/modmuss50/3573e3c2ad8631b50bc9 That's what I get

**Comment by modmuss50** [comment]
From IRC:
21:25 <@amadornes> yeah, that's already been reported
21:25 <@amadornes> but I can't do much to fix it right now since I'm working on the "rewrite"

**Comment by modmuss50** [comment]
Its a BluePower bug, sorry

**Comment by wormzjl** [comment]
Derp :p
