### ISSUE TITLE
TR Villagers have missing texture on zombie varients.

### ISSUE THREAD

**Issue by Gilberry** [TechReborn/TechReborn#2974]
**Describe the bug**
Villagers of the two tech reborn professions display the purple + black missing texture when converted to a zombie.

**Steps to Reproduce**
1. Place an unemployed villager next to either an alloy iron furnace or a generator.
2. When it has acquired a profession, let it be killed by a zombie (hard for 100% chance of conversion).
3. Look at the villager with the missing texture.

**Screenshots**
![2022-06-08_14 49 24](https://user-images.githubusercontent.com/105311418/172620634-caf3a81d-fe55-466f-a382-e193215b9170.png)

**Environment:**
 - Minecraft: 1.19
 - Mod Loader: fabric 0.14.6

**Comment by EthanRStokes** [comment]
I have this issue, but for me it sometimes also results in a crash. I am running a modpack I'm creating, and it throws a FileNotFoundException because it can't load techreborn:textures/entity/zombie_villager/profession/metallurgist.png

**Comment by Tomatobird8** [comment]
Simple fix.
https://github.com/TechReborn/TechReborn/pull/3020

In the meanwhile you can also make a datapack and copy tech reborn villager textures to assets/techreborn/textures/entity/zombie_villager/profession/

**Comment by drcrazy** [comment]
Fixed by https://github.com/TechReborn/TechReborn/pull/3020
