### ISSUE TITLE
1.19 Fabric BYG integration crash

### ISSUE THREAD

**Issue by aAndrew3030** [TechReborn/TechReborn#2976]
Crash on 1.19 fabric with Biomes You'll Go. From what I can tell, it is due to integration for lignite ore that was removed from BYG
[latest.log](https://github.com/TechReborn/TechReborn/files/8873349/latest.log)

**Comment by Ayutac** [comment]
lol why did they do that?

**Comment by Ayutac** [comment]
should be fixed by #2977
