### ISSUE TITLE
Rubber trees don't get affected by biome colour

### ISSUE THREAD

**Issue by StockiesLad** [TechReborn/TechReborn#2979]
**Describe the bug**
Rubber trees don't get affected by biome colour

**Steps to Reproduce**
Self-Explanatory

**Screenshots**

**Environment (please complete the following information with the version):**
1.18.2
0.14.6

**Comment by drcrazy** [comment]
Rubber tree follows logic similar to spruce tree. And spruce tree doesn't change foliage colours in different biomes.
