### ISSUE TITLE
1.8.8 version Material loss

### ISSUE THREAD

**Issue by gxy17886** [TechReborn/TechReborn#298]
I download the mod 1.8.8 version and play a time .but I look all block are black and pink .I hope author can fix the Material loss. forhe version 11.15.0.1624.thanks

**Comment by gxy17886** [comment]
forge version 11.15.0.1624

**Comment by modmuss50** [comment]
Did it happen when you updated forge, because that version of forge fixed an issue with that. See: https://github.com/MinecraftForge/MinecraftForge/commit/0632f2aadf50a39b3300a6999ec0085ffc6b3a8f

**Comment by gxy17886** [comment]
you means the problem of forge ?but I update the forge right now ,this problem still exist.forge version 11.15.0.1625

**Comment by modmuss50** [comment]
Did this happen after you updated forge? Or did it just randomly happen?

**Comment by gxy17886** [comment]
eww...today I fine the TechReborn 1.8.8 version in the curse and download it. It is the first time play this MOD in the 1.8.8 version . All the block and items are material loss . the first 1.88 forge version is 1624.and then update 1625.please look at the picture .(http://i4.tietuku.com/507c8ab722be1fc2.png).Hope you can look at.:-D.If not can you tell me picture bed you can see. thanks

**Comment by gxy17886** [comment]
sorry, web: http://i4.tietuku.com/507c8ab722be1fc2.png

**Comment by modmuss50** [comment]
Ah!, ok I get what you mean.

**Comment by modmuss50** [comment]
As soon as it gets verified by curse you will need to download the latest version of Reborn core

**Comment by gxy17886** [comment]
OK.I will update the reborn core .thanks again.And finally 1.8.8 version can play technology type MOD。:-D
