### ISSUE TITLE
[1.18.2] Fluid tank causes game crash

### ISSUE THREAD

**Issue by CvRain** [TechReborn/TechReborn#2981]
**bug info**
Using any tank to cooperate with the liquid tank of the “create” mod causes a crash

**This should be because there is a problem with the linkage of the module. Maybe it is not a bug?**
**But the world exploded**

**Bug recurrence method**
- palce either tank on the ground
- Click to enter the configuration page
- Click to enter "configure slot"
- Tick any square face
- Tick "Auto input"
-  Finally place one Create:Fluid tank on the ground

You can access the more detailed operation process through this link
https://www.bilibili.com/video/bv1LU4y1R7nu

**Comment by Technici4n** [comment]
Create bug, please report it to them.
