### ISSUE TITLE
Modded pickaxe

### ISSUE THREAD

**Issue by 42schlegel** [TechReborn/TechReborn#2983]
**Describe the bug**
Tech Reborn ores don't drop when a modded pickaxe is used.

**Steps to Reproduce**
- Download and install a mod that has pickaxes (The mods I used was Condensed Netherite (a new mod on curseforge) and a mod that added copper tools with iron tier mining)
- Try to mine any Tech Reborn ore

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric

**Comment by drcrazy** [comment]
1.18 will get only critical fixes. TR ores has necessary tags, both "mineable\pickaxe" and "need_<mininglevel>_pickaxe". PLease, ask Condensed Netherite author to double check on this.
