### ISSUE TITLE
Any ore thats drops itself can be duped with a fortune pickaxe

### ISSUE THREAD

**Issue by rChaoz** [TechReborn/TechReborn#2984]
I think the title says it all. Any ore that drops itself when mined, e.g. galena ore, bauxite ore will drop 2-3 of itself when mined with a Fortune III pickaxe (I only tested this with deepslate galena and deepslate bauxite, so I'm not 100% sure it's all of them). So you can just place it and mine it again to dupe it. I have not tested this on the 1.19 version, released 2 days ago, but I haven't found any issues related to this.

For more information, I'm playing Valhelsia: Enhanced Vanilla (running 1.18.2) and I discovered this after making a vanilla Fortune III Netherite pickaxe and realising Galena ore sometimes drops 2 of itself when mined. By placing and breaking it repeatedly, I managed to get a full stack from just 10 initial ore blocks in around a minute.

**Comment by drcrazy** [comment]
Can't reproduce in 1.19
