### ISSUE TITLE
Unable to change GUI name for Dark GUI Resource Pack

### ISSUE THREAD

**Issue by Afrocntrik** [TechReborn/TechReborn#2989]
I'm currently working on an extension for CyanideX's [Unity Dark Edition](https://www.curseforge.com/minecraft/texture-packs/unity-dark-edition), but I hit a snag. I am unable to find the namespace ID for the machine blocks as it's hard to see with the dark gui theme. 
![2022-06-19_18 28 03](https://user-images.githubusercontent.com/11052983/174502651-920160bf-5ae5-4ea8-ab84-71ee26839461.png)
The example below is showing me changing the color format as it was provided in the en_us.lang file for both Reborn Core and TR.
![2022-06-19_18 30 32](https://user-images.githubusercontent.com/11052983/174502699-9c0a97b8-4b9d-4ff2-9186-1e6c179e1b4b.png)
At this point I'm wondering if this is even possible with how the mod generates block GUI names.

**Comment by drcrazy** [comment]
Block Breaker name is here: https://github.com/TechReborn/TechReborn/blob/63eaf354d9d9548c623492c59aa51a61a3a4fa0b/src/main/resources/assets/techreborn/lang/en_us.json#L95

**Comment by modmuss50** [comment]
> Block Breaker name is here:
> 
> https://github.com/TechReborn/TechReborn/blob/63eaf354d9d9548c623492c59aa51a61a3a4fa0b/src/main/resources/assets/techreborn/lang/en_us.json#L95

I dont think this will help, as its going to change the block name everwhere.

A possibly solution would be to have a json file that can be overriden by reosurce packs including the gui colors.

**Comment by Ayutac** [comment]
We *could* put the colors into a config, no?

**Comment by modmuss50** [comment]
I quite like the idea of adding an official dark mode option 🤔 Shouldnt be a vast amount of work.

**Comment by modmuss50** [comment]
I have added a theming system that allows resource packs to alter the text color. Its highly likely some pieces of text arent using the new `theme.json`. I have also added a built in darkmode resource pack, that a user can opt-in to use.
