### ISSUE TITLE
Some 1.8.8 version BUG

### ISSUE THREAD

**Issue by gxy17886** [TechReborn/TechReborn#299]
hey,I came again.today I update the reborn core version .AND play  for a while.Find some problem.Let me tell you.
1.All texture material  of machine are lose. But all the items can see the texture.(only 3 items can't see). web: http://i4.tietuku.com/118105717903c212.png  and http://i4.tietuku.com/2ce7868951d5a6b2.png.
2.when I test the MOD .I take the block .and see a shadow of a bow.and dialog prompts opengl error .please look at picture.BTY,I don't throw a bow:-D, web: http://i4.tietuku.com/11be5e31c006d91e.png.
3.some block(I don't know what kind of going to happen ) After the block is destroyed, it will form an air wall.I've found an example.that is Galena Ore .
4.some block like the Galena Ore.they are able to display  texture in the creative tab .BUT put them down ,they lose  texture.web: http://i4.tietuku.com/b399c9346cb08db2.png.
forge version  1628

**Comment by modmuss50** [comment]
I can confirm this, it works fine in dev, but does not work in a obofed env.
