### ISSUE TITLE
REI covers input/output side config interface

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2998]
**Describe the bug**
Roughly Enough Items' interface covers up Tech Reborn machines' input/output side config windows, making them hard to see and use without clicking on items in the REI interface.

**Steps to Reproduce**
- Start game with TR, REI and their dependencies, and create a world in Creative mode.
- Place any TR machine with configurable input/output sides.
- Go to the input/output side config tab and click on one of the slots. To see the issue at its worst, choose a slot to the right.
- Observe the interface being obstructed and difficult to use.

**Screenshots**
![2022-06-30_15 57 23](https://user-images.githubusercontent.com/69029346/176792281-a3adcb61-38fd-40f9-8303-a4893fd22921.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: Fabric

**Logs**
N/A

**Comment by drcrazy** [comment]
Duplicate for #2626
