### ISSUE TITLE
Ic2 Classic support

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#30]
When are we gonna have a release ? Because I want to test compatibility with IC2 classic ;)

BTW: Check it out : https://github.com/TinyModularThings/IC2Classic/releases

Also, I can provide you with GregTech textures, as Greg gave me permission for that ;)

**Comment by modmuss50** [comment]
Release comes when we think it is ready.

Im not sure what ic2 classic is, Is it an addon for ic2? or an older version of it?

As for the textures, you would have to ask @gigabit101 or @Tntrololol if we need them

**Comment by gigabit101** [comment]
Ic2 classic is a fork of the old still Ic2

**Comment by modmuss50** [comment]
It should be an easy fix, IC2 classic does not have the gui fluid rendering hooks we are using. If needed we can support it. Do you think that we should?

**Comment by Carbon-Ghost** [comment]
At least, if you have me as a texturer, even if theoretically you won't need me ( if that is the case ), having me will give you an approved by Greg texture use ;) ( but I can still help you ). 

Still, may you send me a testing version of it to try if it supports IC2 classic ;)

**Comment by gigabit101** [comment]
It will be a bit of work as this was when Ic2 used refined iron instead of
any type of metal plates

**Comment by Carbon-Ghost** [comment]
And if I understood everything correctly, the mod doesn't require IC2 and is standalone but can use EU, and I just want to try the IC2 classic E-net with your mod, as normally, IC2 classic works with almost all IC2 addons ;) and other mods.

**Comment by modmuss50** [comment]
As a for textures that would be great :+1:

**Comment by Carbon-Ghost** [comment]
I can create a temporary Minetweaker script for that, so you get covered ;)

BTW: I am one of the 3 official testers of IC2 classic ( without counting the author ).

**Comment by modmuss50** [comment]
It would be easier to change the recipes if it was using ic2 classic. Are you on IRC? #TechReborn on esper? (its a nicer place to talk)

**Comment by Carbon-Ghost** [comment]
Nope, can you send me the link please ;) ?

**Comment by modmuss50** [comment]
http://webchat.esper.net/?nick=&channels=TechReborn Just give your self a username

**Comment by modmuss50** [comment]
https://github.com/TechReborn/TechReborn/commit/fb414d07576cafcf4cbff34f53072e13e57e788f (its in a diffrent branch) This got me to the world. Had to remove recipes and the fluid gui rendering. We can fix if needed but it will be a separate version of the mod if we do decide to continue with this.

**Comment by gigabit101** [comment]
So After the mod is finished we will release Techreborn and Techreborn
Classic sound good?

**Comment by Carbon-Ghost** [comment]
Yup ;)

**Comment by gigabit101** [comment]
As for textures submit some as we do not have permission to rent use Gregs
textures even though they are slightly edited. If we like you'res we will
use them instead

**Comment by modmuss50** [comment]
Ok, We can then just merge the master into the classic branch before release. Becuase the changes will be small it should only take a few mins.
