### ISSUE TITLE
crash with powah by connecting idsu to a powah cable

### ISSUE THREAD

**Issue by unix-supremacist** [TechReborn/TechReborn#3002]
**Describe the bug**
crash with powah

**Steps to Reproduce**
connect a powah cable to an idsu

**Environment**
 - Minecraft: [1.18.2]
 - Mod Loader: [fabric]

**Logs**
https://bin.snopyta.org/?dd9de065046bada5#DehnKTu3fLpSP9EpMc3sR3usFaDZ5vGjXmZTXU4CjnHz

@Technici4n

**Comment by modmuss50** [comment]
This is a powah issue. Should be a none issue in 1.19.2

**Comment by modmuss50** [comment]
See: https://github.com/TechReborn/Energy/issues/23

**Comment by Linguardium** [comment]
Can we have this reopened as it is still an issue in 1.18.2 and is still affecting AOF5?

**Comment by Ayutac** [comment]
It's still a powah issue. Nothing we can do on TR side. Also we don't support older versions.

**Comment by Linguardium** [comment]
nothing you can do turned into a TR energy api change that resolved the underlying issue...there is absolutely something that can be done, though i do agree that improper use of the 1.18.2 version of the api is what is causing it

I understand not supporting older versions

**Comment by Technici4n** [comment]
Fixed for 1.18.2 in TR 5.2.1 (now building).
