### ISSUE TITLE
Crashing on 1.18.1 

### ISSUE THREAD

**Issue by R3tr0PAG** [TechReborn/TechReborn#3003]
**Describe the bug**
Whenever i try to load my server backup, or just the world in singleplayer it crashesh.

**Steps to Reproduce**
- Download my world backup (1.18.1)
- run it on either a server or singleplayer

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric

**Logs**
https://pastebin.com/2X7CrLem

**Additional context**
It has worked just fine.
I did update my server to 1.18.2 but we made a new world and updated all mods seperatly, i also made a whole server backup.
i just need the world to open without it crashing because of techreborn, so i can get all my harddrives from AE2 and transfer them to the new world.

[latest.log](https://github.com/TechReborn/TechReborn/files/9039307/latest.log)

**Comment by dayzed95** [comment]
I am also having a extremely similar problem. 

[crash-2022-07-05_18.43.34-server.txt](https://github.com/TechReborn/TechReborn/files/9056459/crash-2022-07-05_18.43.34-server.txt)

**Comment by drcrazy** [comment]
Duplicate for #2697
