### ISSUE TITLE
Crashing on 1.18.1 due to Solar Panel

### ISSUE THREAD

**Issue by dayzed95** [TechReborn/TechReborn#3004]
I'm posting my crash log.

I simply did a restart on schedule, and it appears that a solar panel in my house is preventing the server from even starting now.
[crash-2022-07-05_18.43.34-server.txt](https://github.com/TechReborn/TechReborn/files/9056475/crash-2022-07-05_18.43.34-server.txt)

Something another about it being a negative value?

**Comment by drcrazy** [comment]
Duplicate for #2697
