### ISSUE TITLE
Matter fabricator Missing GUI

### ISSUE THREAD

**Issue by ibaraki-douji** [TechReborn/TechReborn#3005]
**Describe the bug**
So i was using the matter fabricator and when i try to open the "Configure slot" GUI (showed here #1699) i don't have the gui open but only the power bar and the blue arrow who disappear

**Steps to Reproduce**
If it works for you idk :
- Download v2.24.1.1017 (mc 1.12.2)
- place a matter fabricator
- open it
- click on the `Configure slots` button

**Screenshots**
Before i clicked
![image](https://user-images.githubusercontent.com/72337875/177822696-84a90d4a-3636-4dc9-82f8-5a4a13c6db3e.png)

After i clicked
![image](https://user-images.githubusercontent.com/72337875/177822730-a5e0741e-1a49-4a49-887d-b84f10348816.png)

**Environment :**
 - Minecraft: 1.12.2
 - Mod Loader: Forge (FTB Ultimate Reloaded)

**Comment by drcrazy** [comment]
Click on red slots to configure i\o options
