### ISSUE TITLE
[1.19 FABRIC] [ALL BUGS] [ALL FEATURES REQUEST] Read Me

### ISSUE THREAD

**Issue by MrJorman** [TechReborn/TechReborn#3006]
**Hi buddy, your mod is gorgeous and very cool, but I found a lot of flaws and now I'll tell you about them.**

**1.** It is necessary to make a balance in energy when I set generators in the **generators.json** values of energy generation **0.1** or **0.01** or **0.001** - then they do not work and are not displayed on the mechanism. And no working custom energy symbol "E" in misc.json. i changed from EU and no changes in game.

 ``` "solarPanelBasic": {
    "basicNightRate": {
      "comment": "Generation rate during night for Basic Solar Panel (Energy per tick)",
      "value": 0
    },
    "basicDayRate": {
      "comment": "Generation rate during day for Basic Solar Panel (Energy per tick)",
      "value": 0.05 or 0.01 or 0.001 (no working)
    }
  },
  ```
  **2.** Bug with improvements for mechanisms - _when the ore processing process is already taking place in some mechanism, then if I throw overclocker_upgrade at this moment, then they do not speed up the process of an existing item, it is necessary that I put it back or start the stage from the beginning._  `It needs to be done, if the ore is already being melted or processed in the mechanism, then when I put the improvement it will immediately speed up the process.`
  
  **3.** The wind generator needs to check the blocks for operation and animation. _I can put a million blocks dense even on earth and it will still give me energy, it shouldn't work like that. It is necessary that he was in the air and had enough space and that nothing interfered with him nearby to work._ `During a thunderstorm, it should produce more energy, and on a sunny day, less.`
![image](https://user-images.githubusercontent.com/55187962/178527117-e1074911-15cb-4084-a148-1331fabd4872.png)
![image](https://user-images.githubusercontent.com/55187962/178527404-2a2e7b9c-c0e6-4809-9cc0-9dece97cc61c.png)

**4.** The bronze wrench has no durability. _When I break the mechanism with any tool other than a wrench, it should not fall out, the body of the mechanism should fall out (as done in IC2). Since a wrench is considered an unnecessary item._ **Be sure to fix it!**

**5.** Intermediate armor between netherite armor and quantum amor is very much needed - this is **Nano armor!** Nano armor will be slightly worse than quantum armor, but it will be better than netherite armor. This armor is really needed! To reach the quantum, people will not be so interesting and for a long time, with nano armor it will be easier and already more interesting. Textures you can take from Reborn Advanced: https://www.curseforge.com/minecraft/mc-mods/advancedreborn (**the addon is very bad and crooked, so take the textures safely**)

**6.** To change the activation of the nano saber, to turn it on, you just need to right-click without a clamped shift. It is very necessary, otherwise the PVP players only squat. It can also be done if the nano saber is turned on, it consumes some of the energy, output it to the configuration.

**7.** Add a jetpack - this is a very useful item for builders. A really useful item.

**8.** Take away the quantum chestplate - flight and endless jump. A quantum bib helps to put you out if you are burning, as well as quantum boots give you an increased jump with CTRL pressed.

**9.** In order for the quantum chestplate to have a flight, you can improve it to GravitySuite, an example of the IC2 addon.

**10.** Remove the item Masking device, the most useless item. It doesn't make any sense.

**11.** Resin appears too often on a tree with rubber, reduce the chance of respawning it

**12.** To reduce the chance of the appearance of sapphires, rubies and other stones, they are too frequent.

**13.** **Add quantum plates and iridium, as in IC2, To make a quantum through a matter generator, this gives a lot of time to craft quantum armor.**

**Comment by Ayutac** [comment]
Dumping everything into one bug report is suboptimal.

1) No. This would require major changes in the energy API, or changes to every single generator. If you want to balance basic solar panels better, just make them harder to craft.
2) valid bug report, can confirm, might be worth investigating.
3) valid bug report, might be resolvable with Multiblocks requiring air.
4) optional durability for wrench is valid feature request, disassembling machines is not as far as I'm concerned. 
5) another armor is a valid feature request, but you can't just offer textures that are not your own. That's not how Copyright works
6) changing the activation configuration is possible, but if done this should be done via hotkeys and i don't know if the main devs like hot keys
7) valid request but huge implementation effort if done right
8) No.
9) No thanks.
10) the most useless item is the poisonous potato and that is by design. TR items will get uses eventually.
11) configuration of resin random tick rate is valid feature request
12) Nah, they are alright.
13) What?

**Comment by MrJorman** [comment]
5. Add any texture, even an empty one, let the players set themselves the textures they need, any nano armor is needed.Take the nano armor texture from IC2 and apply smoothness

**Comment by Ayutac** [comment]
We don't do missing textures, it's part of the quality of this mod

**Comment by MrJorman** [comment]
Nano armor has been requested for 2 years, it seems to me it was possible to draw it for a long time.

**Comment by MrJorman** [comment]
> 

Ahahaha) you answered me to all my suggestions - no, so my answer to you then keep: I will not use your garbage mod until you implement it all.
