### ISSUE TITLE
diesel generator crash

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#301]
http://pastebin.com/6xYKz3Wi

**Comment by modmuss50** [comment]
How do I reproduce this? Its it in 1.7?

**Comment by wormzjl** [comment]
yeah 1.7
I've just found this in the log, no idea how it happened since I got remove errored TEs on

**Comment by liach** [comment]
https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/tiles/TileDieselGenerator.java#L149
