### ISSUE TITLE
[fabric-server][crash][1.19] Cannot open Power/Input/Output config panels 

### ISSUE THREAD

**Issue by VaelophisNyx** [TechReborn/TechReborn#3011]
filling this out in-place of someone else

**Describe the bug**
Attempting to open the power, input, or output panels on a machine causes the client to crash to desktop.

**Steps to Reproduce**
- install mod on a server
- Place a machine
- Attempt to open one of the mentioned panels
- crash

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19
 - Mod Loader: Fabric
 - TechReborn 5.3.3

**Logs**
[latest (2).log](https://github.com/TechReborn/TechReborn/files/9217812/latest.2.log)

**Comment by modmuss50** [comment]
Your using the 1.19.1 version of TR on 1.19(.0)
