### ISSUE TITLE
Items deleted when using MI item pipes into machines with stack size over 64

### ISSUE THREAD

**Issue by dathide** [TechReborn/TechReborn#3012]
With Stacker, Modern Industrialization, and Tech Reborn installed, inserting a stack of more than 64 items into a machine sometimes deletes all the items except 64. Oddly enough, this only happens around half the time. Sometimes, the same, unmoved machine is able to have a stack of 256 inside of it until the next time I boot the game when it only gets up to 64 and starts deleting items. This probably isn't relevant, but this also happens with Kibe's Entangled Chests.

- Install Stacker, Modern Industrialization, and Tech Reborn.
- Change Stacker's config so that the max stack is 256 (can be done through Mod Menu without a restart)
- Place down a chest and a Scrapbox-Inator connected by an MI item pipe that is extracting from the chest into the Scrapbox-Inator, with an empty blacklist on both sides of the item pipe.
- Configure the Scrapbox-Inator so the side connected to the item pipe is accepting input.
- Place a stack of 256 Scrapboxes into the chest.
- After the full stack has transferred, there's around a 50% change only 64 Scrapboxes will remain in the Scrapbox-Inator.
- If the full stack of 256 is in the Scrapbox-Inator, take them out and try again after rebooting the game.

 - Minecraft: 1.18.2
 - Mod Loader: Fabric
 - Tech Reborn 5.2.0
 - Modern Industrialization 1.2.2
 - Stacker 3.0.1

latest.log: https://pastebin.com/ppfiZuqX

**Comment by Technici4n** [comment]
Stacker issue: mods that try to change the max stack size cause all sorts of problems, so it's on them to fix it.

**Comment by dathide** [comment]
Sorry, I should have added more details. Tech Reborn machines work fine with higher stack sizes when hoppers are used. Also, these issues don't occur with the machines from other mods like Modern Industrialization and Industrial Revolution. So I think that limits down the possible causes to the mods for the items pipes or Tech Reborn.

**Comment by dathide** [comment]
@Technici4n Sorry, I should have added more details. Tech Reborn machines work fine with stacks of 256 when hoppers are used. Also, these issues don't occur with the machines from other mods like Modern Industrialization and Industrial Revolution. So I think that limits down the possible causes to: the item pipe mods or Tech Reborn. Also, items pipes transfer stacks of 256 into hoppers just fine and other mod machines just fine, with the minor exception of Kibe. So I think there's a strong possibility Tech Reborn is the culprit. I could be wrong though, I'm not a modder.

**Comment by dathide** [comment]
Also, thanks for your work on Modern Industrialization, Modern Dynamics, and Applied Energistics 2! MI and AE2 are some of my favorite mods and have given me dozens of hours of more interesting gameplay.
