### ISSUE TITLE
Nano Saber always does 5 damage

### ISSUE THREAD

**Issue by lukaguyman** [TechReborn/TechReborn#3014]
the nano saber always does only 5 attack damage even if its fully charged and activated but in rei it says it should be doing 21

1. make nano saber
2. check stats
3. check stats for nano saber but in rei

fabric 0.14.8 for 1.19

**Comment by Ayutac** [comment]
Cannot reproduce in TR 5.3.3. Did you try with TR standalone or in a modpack?

**Comment by lukaguyman** [comment]
I did it in a modpack with about 73 other mods, none that should change the damage of anything or change how energy works
I am using version 5.3.2 is that the problem?
Inside curseforge it will not let me update to 5.3.3 and considers 5.3.2 the latest version.

**Comment by Ayutac** [comment]
Should is a powerful word here. Have you tried out if the problem persists when you only play TR 5.3.2? Because if not, the problem is with the modpack and we can hardly help you there

**Comment by drcrazy** [comment]
Can't reproduce with TR 5.3.3

![image](https://user-images.githubusercontent.com/1382352/183220138-70c6a9b1-d0b4-4d63-a0ae-80bce43555dd.png)
