### ISSUE TITLE
[Bug] Iridiyum Achievment granted on obtaining raw iridium 1.18.2

### ISSUE THREAD

**Issue by Merith-TK** [TechReborn/TechReborn#3017]
**Describe the bug**
When mining iridium ore, it drops raw iridium, picking up raw iridium, grants the "Iridiyum" achievement for grinding the ore into dust

**Steps to Reproduce**
Mine iridium ore with an diamond pickaxe in survival

**Screenshots**
![image](https://user-images.githubusercontent.com/10422110/182529033-ecf4dac0-fd6f-41fc-a216-f68a09f83b17.png)
![image](https://user-images.githubusercontent.com/10422110/182529477-e77973d3-d7b6-43a6-a6f6-c254534e5237.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: Fabric

**Logs**
https://mclo.gs/eaBVLn3

**Modpack**
https://git.merith.xyz/modpacks/ultron

**Comment by drakosoldier298** [comment]
He means grinding the ore block into raw iridium

**Comment by Ayutac** [comment]
Tooltip/Advancement Description is wrong, behaviour is correct :)
