### ISSUE TITLE
Game Instant Crash

### ISSUE THREAD

**Issue by ForeignXioes** [TechReborn/TechReborn#3018]
Game Crashes When Trying To Open Settings in Blocks
I also have 188 Mods In The Server, if needed I can send a list of said mods.

**Steps to Reproduce**
- First Step: Open Any TechReborn block that has options (Generator, Solar Panel, etc.) Configure Slots and/or Configure Redstone
- Second Step: Click on either tab.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19
 - Mod Loader: Fabric Server 1.19

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/3/22, 9:23 PM
Description: Rendering screen

java.lang.NoSuchMethodError: 'void net.minecraft.class_350.method_25311(net.minecraft.class_4587, int, int, float)'
	at reborncore.client.gui.guibuilder.GuiBuilder$TipsListWidget.method_25394(GuiBuilder.java:447)
	at reborncore.client.gui.guibuilder.GuiBuilder.drawSlotConfigTips(GuiBuilder.java:410)
	at reborncore.client.gui.builder.GuiBase.lambda$drawBackground$10(GuiBase.java:226)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at reborncore.client.gui.builder.GuiBase.method_2389(GuiBase.java:226)
	at techreborn.client.gui.GuiGenerator.method_2389(GuiGenerator.java:44)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:258)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at reborncore.client.gui.guibuilder.GuiBuilder$TipsListWidget.method_25394(GuiBuilder.java:447)
	at reborncore.client.gui.guibuilder.GuiBuilder.drawSlotConfigTips(GuiBuilder.java:410)
	at reborncore.client.gui.builder.GuiBase.lambda$drawBackground$10(GuiBase.java:226)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at reborncore.client.gui.builder.GuiBase.method_2389(GuiBase.java:226)
	at techreborn.client.gui.GuiGenerator.method_2389(GuiGenerator.java:44)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:258)

-- Screen render details --
Details:
	Screen name: techreborn.client.gui.GuiGenerator
	Mouse location: Scaled: (473, 176). Absolute: (1420.000000, 529.000000)
	Screen size: Scaled: (1147, 473). Absolute: (3440, 1417). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['SuicidalRuby'/559, l='ClientLevel', x=25.55, y=64.00, z=5.75]]
	Chunk stats: 16384, 1260
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,68,16), Section: (at 0,4,0 in 1,4,1; chunk contains blocks 16,-64,16 to 31,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 833 game time, 833 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Vybb Pack, Hardcore Hearts

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3003549064 bytes (2864 MiB) / 5536481280 bytes (5280 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 42987.63
	Virtual memory used (MB): 23114.49
	Swap memory total (MB): 10293.41
	Swap memory used (MB): 197.55
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.6.1+1.19
		advancementplaques: Advancement Plaques 1.4.5
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.14
		alloy_forgery: Alloy Forgery 2.0.15+1.19
		alloygery: Alloygery 2.1+1.19
		another_furniture: Another Furniture 2.0.1-1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 5.10.33
		armorchroma: Armor Chroma 1.2.2
		attributefix: AttributeFix 15.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		automated_crafting: Automated Crafting 1.4.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		auudio: Auudio 1.0.3
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 4.3.0+0
		bcc: BetterCompatibilityChecker fabric-2.0.1-build.15
		bclib: BCLib 2.0.16
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterend: Better End 2.0.9
		betterf3: BetterF3 1.3.1
		betternether: Better Nether 7.0.6
		betterthirdperson: Better Third Person 1.8.1
		bhmenu: BHMenu-Fabric 1.19-1.3
		biomemakeover: Biome Makeover 1.19-1.5.9
		blockus: Blockus 2.5.1+1.19
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		bookshelf: Bookshelf 14.1.7
		borderlessmining: Borderless Mining 1.1.4+1.19
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.0.7
		capybara: Capybara 1.0.5
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0-beta.2+1.19
		chesttracker: Chest Tracker 1.1.17
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.73
		clumps: Clumps 9.0.0+6
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.0-beta.4+1.19
			spectrelib: SpectreLib 0.8.1+1.19
		craftingtweaks: Crafting Tweaks 15.0.1
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		dark-loading-screen: Dark Loading Screen 1.6.12
		darkpaintings: DarkPaintings 11.0.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.3.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.11
		deepslatecutting: Deepslate Cutting 1.4.0
		dragonloot: DragonLoot 1.1.1
		duckling: Duckling 2.0.3
		dungeons_arise: When Dungeons Arise 2.1.51
		dustrial_decor: Dustrial Decor 0.5
		earthtojavamobs: Earth2Java 1.9.2
		easymagic: Easy Magic 4.0.0
		ecologics: Ecologics 2.1.4
		edenring: EdenRing 0.6.3
		effective: Effective 1.2.2
		enchdesc: EnchantmentDescriptions 11.0.4
		enhancedcelestials: Enhanced Celestials 2.1.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		expandeddelight: Expanded Delight 0.2.1
		expert_armor: Expert_Armor 2.0
		expert_weapons: Expert Weapons and Tools 2.5
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fallingtree: FallingTree 3.7.4
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmersknives: Farmer's Knives 2.0
		farsight: Farsight Mod 1.19-2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.24.0+1.19
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendsandfoes: Friends&Foes 1.5.5
		ftbchunks: FTB Chunks 1900.3.8-build.157
		ftblibrary: FTB Library 1900.3.8-build.135
		ftbteams: FTB Teams 1900.2.8-build.59
		galosphere: Galosphere 1.19-1.1.0-fabric
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.4
		gobber2: Gobber2 2.6.26
			pugh_lib: Pugh Lib 1.4.11
			pugh_tools: Pugh Tools 1.3.15
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 1.10
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		harvest_scythes: Harvest Scythes 2.5.3
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.8
		impaled: Impaled 1.1.4
		imst: Immersive structures 2.0.2
		incantationem: Incantationem 1.1.4+1.19
		infusion_table: Infusion Table 1.1.0
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventoryprofilesnext: Inventory Profiles Next 1.6.1
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemborders: Item Borders 1.1.6
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jamlib: JamLib 0.3.2
		java: OpenJDK 64-Bit Server VM 17
		just_end_anchor: Just An End Anchor 1.0.2
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lightoverlay: Light Overlay 7.0.0
		logical_zoom: Logical Zoom 0.0.15
		magnumtorch: Magnum Torch 4.0.1
		mantori: Aphid Additions 1.1.1-1.19
		mavm: More Axolotl Variants Mod 1.1.0
		medievalweapons: Medieval Weapons 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		memoryleakfix: memory Leak Fix 1.19-0.5.4
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.0
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 0.5.3
		moretotems: More Totems 2.11.0
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		naturalist: Naturalist 2.0.1
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		nbtcrafting: NBT Crafting 2.1.4+mc1.19
		nears: Nears 1.2.2
		nmuk: No More Useless Keys 1.0.1+mc1.19
		nochatreports: No Chat Reports 1.19-v1.2.3
		onsoulfire: On Soul Fire 1.19-2
		openloader: OpenLoader 13.0.1
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.1
		paintings: Paintings++ 10.0.0.0
		patchouli: Patchouli 1.19-74-FABRIC
		plushies: Plushie Mod 1.2
		presencefootsteps: Presence Footsteps 1.6.0
			kirin: Kirin UI 1.11.0
		puzzleslib: Puzzles Lib 4.0.17
		quarrymod: Industrial Quarry Mod 1.0.2
		quartzelv: Quartz Elevator 2.1.3+1.19
		reborncore: Reborn Core 5.3.3
			team_reborn_energy: Energy 2.2.0
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.19-build.47
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rightclickharvest: Right Click Harvest 2.2.1
		rocks: This Rocks! 1.6.1
		roughlyenoughitems: Roughly Enough Items 9.1.517
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		seasons: Fabric Seasons 1.4-BETA+1.19
		shulker-dupe: Shulker Dupe 1.0.0
		simplechunkloader: Simple Chunkloader 1.0.3
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.26
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spirit: Spirit 2.1.2
		splatus_ultris: Ultris: Boss Expansion 5.6.4
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.3
		steves_vanilla: Steves Vanilla 1.0.0+1.19
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.8
		techreborn: Tech Reborn 5.3.3
		terrablender: TerraBlender 2.0.0.120
		the_bumblezone: The Bumblezone - Fabric 6.1.1+1.19
			fake-player-api: Fake Player API 0.3.0
		thonkutil: ThonkUtil 2.15.3+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.1+7ce8ef6257
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toolstats: ToolStats 10.0.1
		tradingpost: Trading Post 4.0.0
		transparent: Transparent 5.1.0
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.8+1.19
		universal_ores: Universal Ores 1.4.1
		villagernames: Villager Names 4.0.5
		visualworkbench: Visual Workbench 4.0.0
		voidtotem: Void Totem 2.0.0
		voidz: VoidZ 1.0.8
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		wardentools: Warden Tools 1.0
		waystones: Waystones 11.0.1
		whereisit: Where Is It 1.14.11
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wthit: wthit 5.7.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		xp_storage: XP Storage 1.4.3+1.19
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.19
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 3440x1417
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Vybb Pack, file/Hardcore Hearts
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SuicidalRuby'/559, l='ServerLevel[New World]', x=25.55, y=64.00, z=5.75]]
	Data Packs: vanilla, Fabric Mods, minecraft/ewmodcompat, minecraft/eamodcompat
	World Generation: Stable

**Comment by Ayutac** [comment]
You are trying to run TechReborn for 1.19.1 on Minecraft 1.19
