### ISSUE TITLE
Server crash due to TechReborn failling to generate ore

### ISSUE THREAD

**Issue by Xstoudi** [TechReborn/TechReborn#3021]
**Describe the bug**
The server crash.

**Steps to Reproduce**
- On Another Quality Modpack 2
- Go in the Pure Mining Dimension
- Load a bunch of chunks

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric
 - Modpack : Another Quality Modpack 2 

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/VRPBttTJ

**Additional context**
It's seems that TechReborn fail to generate ore in the Pure Mining Dimension https://www.curseforge.com/minecraft/mc-mods/pure-mining-dimension.

The Pure Mining Dimension's developer said that I probably should report it to you.
![image](https://user-images.githubusercontent.com/2575182/185194811-e3a081d5-99b4-439c-8bbf-d8522610f579.png)

**Comment by drcrazy** [comment]
Unfortunately PMD doesn't provide sources. Thus it is impossible to check how it change vanilla world gen so TR oregen is compatible with vanilla but not compatible with PMD
