### ISSUE TITLE
Unable to Turn off Creative Flight

### ISSUE THREAD

**Issue by Dragonfly-Totem** [TechReborn/TechReborn#3023]
Unable to turn off Creative Flight for Quantum Chestplate on server.

In the "items.json" file located within .\minecraft\config\techreborn, there is the following entry:

    "quantumSuitEnableFlight": {
      "comment": "Enable Flight for Quantum Chest",
      "value": true

Changing the value to **false** does not seem to disable the Creative Flight option.

Minecraft 1.19
Fabric 0.14.8
Fabric API 0.57.0
Reborn Core 5.3.2
TechReborn 5.3.2

Haven't tested this in a more recent version, since I haven't updated my server to 1.19.2 just yet.  Still, wanted to report this.

**Comment by AmonRay** [comment]
same for quantumSuitEnableSprint param

also, it would be awesome if there was an ability to change the attack speed of nano sword

**Comment by AmonRay** [comment]
looks like config not working at all. Just tried to modify lapotronicOrbMaxCharge from 100000000 to 200000000 - no difference. Same for quantumSuitFlyingCost

**Comment by Ayutac** [comment]
try adjusting solar panel energy generation. that works, right?

**Comment by AmonRay** [comment]
just tried

nanoSaberDamage - works
quantumNightRate/quantumDayRate - nope

**Comment by xanthian** [comment]
Are you doing this server or client side

**Comment by AmonRay** [comment]
hosting server via client

**Comment by xanthian** [comment]
Interestingly, I tested the creative flight setting, turning it off on server did not stop it, but turning it off on client did 🤷🏻‍♂️

**Comment by AmonRay** [comment]
thats very strange, cos some random params works like quantumSuitCapacity, nanoSaberDamage while others do not...

**Comment by Ayutac** [comment]
I think this is simply because some things, like movement, happen on client

**Comment by CreativeTechGuy** [comment]
Seems to still be happening on 1.20.1 #3146

**Comment by modmuss50** [comment]
This was fixed.
