### ISSUE TITLE
Tech Reborn players joining get disconnected due to large string size.

### ISSUE THREAD

**Issue by Vixeliz** [TechReborn/TechReborn#3024]
**Describe the bug**
Hello, I have been playing some modded fabric on 1.19.2 lately and recently when updating mods I noticed that when players join the server that I host they will get kicked by a socket reset. going into the log it looks like this stems from the reborncore api for recipes. I think this is an incompatibility between reborncore and some other mod I have installed but not sure what since the only thing I can deduce is from reborncores api call. I will attach my log

**Steps to Reproduce**
- Install Mods
- Launch Singleplayer world and open to lan with port set(I have also tested on dedicated server)
- Profit?

**Screenshots**
Not too applicable in this case

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/6d0mSUJU
[latest.log](https://github.com/TechReborn/TechReborn/files/9390431/latest.log)

**Additional context**
I think that is the main context

**Comment by Vixeliz** [comment]
I've narrowed this down to be a conflict between this and one of three mods (Supplementaries, Every compat, or moonlight lib) Im not sure which yet but wanted to update that this still may or may not be at the fault of RebornCore im not sure yet

**Comment by Vixeliz** [comment]
It ended up being every compat. I'm going to open an issue there as well as Im still not sure whos side it is on. However I am leaning more towards every compat due to the complexity of how that mod works and that it adds so many items

**Comment by drcrazy** [comment]
Can't reproduce it with TR + Everycompat + MoonlightLib + REI(with deps).

Are you sure you do not have other mods enabled?

**Comment by drcrazy** [comment]
@Vixeliz Can you try with this build, please? https://github.com/TechReborn/TechReborn/suites/7938627936/artifacts/338692996
It has some extended logging for this particular issue.

**Comment by Vixeliz** [comment]
> Can't reproduce it with TR + Everycompat + MoonlightLib + REI(with deps).
> 
> Are you sure you do not have other mods enabled?

Yes I do I thought I mentioned that however I specified I thought it was every compat due to it going away from removing it. As for testing yes I can in a little bit

**Comment by dfontana92** [comment]
Appears to be caused by the Grinder recipe overflowing once you add a few mods linked in with EveryCompat (namely the Macaw's Doors mod).

Here's a sample string from my log on 5.3.4

--EDIT--
See attached text file. Cleaned it up a bit with some RegEx so it's easier to see the other mods contributing to the issue (MCWDoors + BYG  + EveryCompat).

I strongly suspect the issue also exists for MCWWindows and any other mods that add multiple variations of specific tags (doors, windows, etc), but the client disconnects after the first String overflow it encounters.

[TechReborn-EveryCompat-Overflow.txt](https://github.com/TechReborn/TechReborn/files/9553052/TechReborn-EveryCompat-Overflow.txt)

**Comment by Ayutac** [comment]
This is a serious problem. Why would the tag stuff be explicitly send??

**Comment by modmuss50** [comment]
This happens because we have to sync the tags to the client, I will look into improving this.

**Comment by modmuss50** [comment]
Should be a lot better now. Sorry about this 👍
