### ISSUE TITLE
[1.18.2] can not join, string too big

### ISSUE THREAD

**Issue by MSandro** [TechReborn/TechReborn#3026]
**Describe the bug**
With a large number of Mods I can not join my server anymore.

**Steps to Reproduce**
* installing my current Dev-Build Modpack Version. [SF3-0.4.1-dev2.zip](https://github.com/someaddons/connectivity/files/9314199/SF3-0.4.1-dev2.zip)
* create a server by copying the files to a Fabric Server Instance
* remove some client Mods (Sodium, Indium, ...)
* start the server
* join
* fail

**Screenshots**
![image](https://user-images.githubusercontent.com/10937159/184297661-ee4b0c66-5def-410e-b936-7f310c1db6ba.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: Fabric

**Logs**
https://gist.github.com/MSandro/d82b258379abed78a8bcc0b4fa83aad8

**Additional context**
I am struggling with this issue since 3 weeks, Everyone says, RebornCore is causing this issue.
I didn't want to believe that, but since I don't know what to do next, I'm going to create an issue here as well.
https://github.com/someaddons/connectivity/issues/37#issuecomment-1219365557

**Comment by MSandro** [comment]
similar error described on discord from someon:
![image](https://user-images.githubusercontent.com/10937159/186844744-0053e25a-e114-4472-bda7-63debe6d1cae.png)

**Comment by drcrazy** [comment]
Some other mods are messed up with TR recipe and made an output of the recipe too long.
Duplicate for #3024

**Comment by MSandro** [comment]
thx
any way to find out which recipe is the source of the problem?

**Comment by drcrazy** [comment]
There is a dev build for 1.19 with extended logging. It is mentioned in original issue. You can help with triage if you fine to update your pack to 1.19.

**Comment by MSandro** [comment]
okay thank you.
but I don't plan to update my Modpack Sky Fabrication 3 to 1.19 in the near future. Some mods like Create which is a big part in the progress line of the pack, or others like Botania, are still not available for 1.19. So its not possible to update yet.
