### ISSUE TITLE
Recycler Issues

### ISSUE THREAD

**Issue by 57331Fury** [TechReborn/TechReborn#3027]
**Describe the bug**
I'm having a couple of issues with the recycler. When I first place and connect the recyclers, they run very quickly, probably getting through roughly 10-20 items per second, but after a save and reload, the Recyclers slow down, so they are now only processing 1 item about once every 5 seconds. This is a huge difference in running speed (Approximately running 50-100 times slower after a reload). The problem can be resolved by wrentching the recyclers up, replacing them, and setting the side confirguration again, but this take time and effort that shouldn`t have to be done.
I have also noticed that the Recyclers are using up zero power, so once they are working, you can disconnect the power cable, and they will continue to run at 100% power

**Steps to Reproduce**
- Place/connect Recyclers and watch process speed.
- Save and reload, and now Recycler will be running much much slower.

**Screenshots**
Not really applicable

**Environment (please complete the following information with the version):**
 - Minecraft: 1.12.2
 - Mod Loader: Forge
 - Tech Reborn version: 2.27.3.1084-universal

**Logs**
https://pastebin.com/52MFqWiJ

**Comment by drcrazy** [comment]
Sorry, no support for 1.12 from TR team. It is too old.
