### ISSUE TITLE
Cells without liquid textures

### ISSUE THREAD

**Issue by Rislir** [TechReborn/TechReborn#3029]
Hi!
I noticed that the cells have become without liquid textures and do not differ from each other. In older versions, they were colored, as far as I remember.
Is this a bug?
Minecraft 1.19.2
8/30/2022 TechReborn
![Скриншот 31-08-2022 204152](https://user-images.githubusercontent.com/112578183/187746685-ff2b7702-86ab-4d29-91fe-4b7e8cc4b624.png)

**Comment by xanthian** [comment]
If you are using Sodium / Iris you will need to install Indium.

**Comment by Ayutac** [comment]
Duplicate of #2589
