### ISSUE TITLE
Enhancement: Implement Modtweaker support to the Rolling Machine

### ISSUE THREAD

**Issue by BakermanLP** [TechReborn/TechReborn#303]
Hello,
it would be nice, to add some recipes to the rolling machine via Mine- / ModTweaker.

Thanks!

Michael (aka BakermanLP)

**Comment by BakermanLP** [comment]
I am sorry to ask that ... could you please backport this to the 1.7.10er Version? PLEASE :)

**Comment by modmuss50** [comment]
I will if we end up doing another 1.7 version

**Comment by BakermanLP** [comment]
Thanks a lot!
