### ISSUE TITLE
According to logs, Modded Server REI failed to synchronize recipe data because of tech reborn

### ISSUE THREAD

**Issue by HelpIsNice** [TechReborn/TechReborn#3030]
**Describe the bug**
Playing on a modded 1.19 fabric server, hosted by Shockbyte. We are having issue where it show up in chat upon login that "REI: Server failed to synchronize recipe data with the client. Please check the console logs for errors. This breaks REI and vanilla crafting books." From what i can made from the log, it's caused by tech reborn

**Environment
 - Minecraft 1.19
 - Mod Loader: Fabric
 - Server Host: Shockbyte

**Logs**
https://pastebin.com/XgRRfiRE

**Comment by drcrazy** [comment]
Duplicate for #3024
