### ISSUE TITLE
rendering entity in world, mod compatibility ?

### ISSUE THREAD

**Issue by Voloww** [TechReborn/TechReborn#3031]
**Describe the bug**
The game crash client side when i open inventory, the last thing i do is to put golden jetpack in lazuli flux container and crash
after few try i see i can open my inventory without crashing trough another way, trough chest or any other inventory container, but when i'm pressing "e" it's the end ^^

I juste searching a way to unequip my jetpack (i think it's on me) without accessing my inventory

**Steps to Reproduce**
-Put golden jetpack in lazuli flux container and crash
(mods: Iron Jetpacks and Industrial Révolution)

**Screenshots**
//

**Environment (please complete the following information with the version):**
 - Minecraft: TNP Refabricated 1.18.2 modpack
 - Mod Loader: [fabric]

**Logs**
Pastebin link it below: https://pastebin.com/dkiXygq8

**Additional context**
Just Searching a way to charge the jetpack ^^

**Comment by Ayutac** [comment]
not part of TR, submit bug report to Iron Jetpacks
