### ISSUE TITLE
Fluid Replicator error: Something went wrong when retrieving data for this block

### ISSUE THREAD

**Issue by mdedmon** [TechReborn/TechReborn#3034]
**Describe the bug**
Running TR ver 5.2.0 in All Of Fabric mod pack. The fluid replicator is generating an error message when placing the block and on server restart. 

**Steps to Reproduce**
Fluid Replicator is placed the floor (even before the multiblock is built).
Tried breaking and replacing the block before and after the multiblock is built.
Multiblock holo works and the interface works as expected.
But, when placing the uu matter in the machine, nothing happens.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: fabric
 - (All of Fabric 5) 

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[https://pastebin.com/4VqayHPt](https://pastebin.com/4VqayHPt)

**Additional context**

**Comment by drcrazy** [comment]
Can't reproduce in dev env with TR only. Stacktrace points to megane
