### ISSUE TITLE
Use DFS instead of BFS for gathering cables

### ISSUE THREAD

**Issue by RolandPetrean** [TechReborn/TechReborn#3035]
I've noticed that CableTickManager performs a Breadth-First Search instead of a Depth-First Search to find all connected cables, for no apparent reason. Using a stack instead of a queue is faster and more memory efficient in this case.

**Comment by Technici4n** [comment]
How is it faster and more memory efficient? BFS is easier to implement than DFS without recursion, so unless we have someone profiling data showing that the BFS is a bottleneck I would keep the easier and existing option.

**Comment by Ayutac** [comment]
Relevant: https://www.geeksforgeeks.org/difference-between-bfs-and-dfs/
