### ISSUE TITLE
Villager information missing from wiki

### ISSUE THREAD

**Issue by johalun** [TechReborn/TechReborn#3038]
**Describe the bug**
There's no information (afaict) about tech reborn villagers except the source code and some reddit thread. Everyone I mention this to are surprised to hear that there even exists tech reborn villagers. A lot of people are missing out one this great feature I think. Please consider add this to the wiki. (yes, missing docs is a bug IMHO)

Thank you!

**Comment by xanthian** [comment]
Started work on this : 
_(might not be what Ayutac had in mind but better than nothing)_
https://wiki.techreborn.ovh/doku.php?id=villagers

what else needs adding?

**Comment by xanthian** [comment]
finished now :)

**Comment by johalun** [comment]
Awesome! Thank you so much. I didn't realize they had been added so recently.
