### ISSUE TITLE
Recipes not working

### ISSUE THREAD

**Issue by kazexdyt** [TechReborn/TechReborn#3040]
The lithium battery is not able to be crafted and the quantum armor and energy crystal, please fix this I love this mod.

**Comment by xanthian** [comment]
version?
modpack?

elaborate please :)
Help us to help you!

**Comment by kazexdyt** [comment]
It is a custom fabric modpack on 1.19, I fixed the quantum armor but the energy crystal and lithium battery are not showing how they are made Im using REI. And the version of tech reborn is 5.3.2

**Comment by xanthian** [comment]
this wont get fixed if you dont elaborate on your issue.
what other mods are you using? 
have you messed with recipes?
show screenshots.. cmon

**Comment by Ayutac** [comment]
If this bug still appears on 5.3.4 or newer, feel free to open up a new bug, that time with more information as Xanthian described.
