### ISSUE TITLE
Crash while crafting Forge Hammer

### ISSUE THREAD

**Issue by HolaAdios99** [TechReborn/TechReborn#3043]
**Describe the bug**
Every time I tried to craft a Forge Hammer the MC will force quit to desktop

**Steps to Reproduce**
Craft Forge Hammer

**Environment (please complete the following information with the version):**
 - Minecraft:  1.1.9
 - Mod Loader: Fabric
 - Dream Craft mod suite

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**
[crash-2022-10-10_18.29.52-client.txt](https://github.com/TechReborn/TechReborn/files/9748468/crash-2022-10-10_18.29.52-client.txt)

**Comment by modmuss50** [comment]
This seems to be caused by the TR addon: https://github.com/PTOM76/AdvancedReborn
