### ISSUE TITLE
Server was crashing due to ticking entity.

### ISSUE THREAD

**Issue by Ejz9** [TechReborn/TechReborn#3044]
**Describe the bug**
Currently: **[Server thread/ERROR]: Failed to initialize generator! This is a bug.**
This stemmed from re-uploading my server and a ticking entity issue for one of the water_mill blocks. I removed it, and the issue stopped, so I readded the mod and let it create a new config file. Without the mod though this issue is still there. It spams the console with the message in bold.

**Steps to Reproduce**
- Use my world region file with my mods folder
- I don't know why any of this happened to begin with.

**Screenshots**
![image](https://user-images.githubusercontent.com/114949726/195256523-57344464-c9da-4985-86e9-656e3c514d64.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: fabric

**Logs**
[latest.log](https://pastebin.com/6qNMpneA)

**Additional context**
I have removed TEN seconds of the log basically as it was 20kb short of 1Mb. It spams the console. Although I was able to join the server and do stuff.

**Comment by Ayutac** [comment]
Does this still persist in 1.19.2? 
I couldn't find this error message in the 1.19.2 TR repo.

**Comment by modmuss50** [comment]
I dont see such a log output in the code. I dont think this is us.
