### ISSUE TITLE
Tech Reborn for 1.17+ still shows Reborn Core as a required dependency

### ISSUE THREAD

**Issue by Mr1cecream** [TechReborn/TechReborn#3045]
**Describe the bug**
Tech Reborn for 1.17+ still shows Reborn Core as a required dependency rather than an embedded library on CurseForge.

**Steps to Reproduce**
- Go on Tech Reborn's CurseForge page
- Click on any file for Minecraft 1.17 or over
- Reborn Core is a required dependency
This also affects the CurseForge API (the `relationType` of Reborn Core is `3` which is the one for required dependencies).

**Screenshots**
See bottom of screenshot
![image](https://user-images.githubusercontent.com/88837169/195873416-47024d3b-d5f6-41cf-a070-51da6c6c22cb.png)

**Environment (please complete the following information with the version):**
- CurseForge Web
- CurseForge App
- CurseForge API

**Logs**
Irrelevant

**Additional context**
Third-party mod managers which use the CurseForge API to determine dependencies will see Reborn Core as a required dependency.

**Comment by modmuss50** [comment]
I dont think this causes a major issue.
