### ISSUE TITLE
Rubber trees spawn in way too many modded biomes

### ISSUE THREAD

**Issue by StockiesLad** [TechReborn/TechReborn#3046]
**Describe the bug**
Rubber trees spawn everywhere, in so many biome mods where it clearly doesn't belong. It ruins some biomes like the Autumnal woods from traverse.

**Steps to Reproduce**
Install any biome mod and see the billions of rubber trees

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: fabric 0.14.9

**Logs**
Not Needed

**Solution**
Two solutions here. Either make rubber trees change with biome colour, or restrict their spawning to only vanilla biomes.

**Comment by xanthian** [comment]
Firstly, 1.18.2 is no longer supported for features.

Secondly, restricting the spawn to only vanilla biomes could have an opposite effect if a large number of custom biomes are added, in that they become too rare.

**Comment by StockiesLad** [comment]
Well if a large number of custom biomes are added, precisely how is that techreborn's fault? I have pretty much all of the biome mods, and I'd like it to be in vanilla forests for 2 reasons:
- You should actually need to explore, thus improving that domain.
- Rubber trees do more harm then good by spawning in modded biomes.

It should at least be a config to restrict spawning to vanilla biomes.

**Comment by xanthian** [comment]
Feel free to put a PR in :)

```				
.add(ModificationPhase.ADDITIONS, BiomeSelectors.tag(BiomeTags.IS_FOREST)
.or(BiomeSelectors.tag(BiomeTags.IS_TAIGA))
.or(BiomeSelectors.includeByKey(BiomeKeys.SWAMP)), rubberTreeModifier())`

**Comment by StockiesLad** [comment]
alright!

**Comment by modmuss50** [comment]
Closing as this is an old issue, please create a new issue if this is still an issue. Thanks 👍
