### ISSUE TITLE
Can't create Titanium Dust from UU-Matter

### ISSUE THREAD

**Issue by slashfast** [TechReborn/TechReborn#3047]
**Describe the bug**
The Scute is crafted, not the Titanium Dust

**Steps to Reproduce**
- Place the UU-Matter as specified in the recipe for Titanium Dust

**Screenshots**
<br>
<p align="center">
<img src="https://user-images.githubusercontent.com/48316573/196993724-dbe8a605-c890-4c14-b0d9-61a9be93500f.png" width="500">
</p>

<details>
<summary>Recipe of the Scute in \data\techreborn\recipes\crafting_table\uu_matter\calcium\scute.json</summary>
<pre><code>
{
  "type": "reborncore:padded",
  "pattern": [
    "UUU",
    "UCU",
    "   "
  ],
  "key": {
    "C": {
      "tag": "c:calcium_dusts"
    },
    "U": {
      "item": "techreborn:uu_matter"
    }
  },
  "result": {
    "item": "minecraft:scute"
  }
}
</code>
</details>

<details>
<summary>Recipe of the Titanium Dust in \data\techreborn\recipes\crafting_table\uu_matter\dust\titanium_dust.json</summary>
<pre><code>
{
  "type": "reborncore:padded",
  "pattern": [
    "UUU",
    "U U",
    "   "
  ],
  "key": {
    "U": {
      "item": "techreborn:uu_matter"
    }
  },
  "result": {
    "item": "techreborn:titanium_dust"
  }
}
</code>
</details>

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric 0.14.9
 - Tech Reborn 5.3.4

**Logs**
https://pastebin.com/vzhwiAGj

**Additional context**
I've tested this without any mods, expect for Tech Reborn, tested with [the latest Tech Reborn build from GitHub Actions](https://github.com/TechReborn/TechReborn/actions/runs/3130932249), but only one result

Another strange thing is the prescriptions with saplings:
<details>
<summary>Correct (A Spruce Sapling)</summary>
<br>
<p align="center">
<img src="https://user-images.githubusercontent.com/48316573/196998458-39b895ef-5961-43f3-a804-c407f0095e5d.png" width="500">
</p>
</details>
<details>
<summary>Incorrect (The Spruce Sapling instead of an Acacia Sapling)</summary>
<br>
<p align="center">
<img src="https://user-images.githubusercontent.com/48316573/196998897-8cec85e4-a91a-4dec-9781-370c5976a41e.png" width="500">
</p>
</details>

**Temporary Solution**
<details>
<summary>Change the recipe of Scute to another</summary>
<pre><code class="language-json">
{
  "type": "reborncore:padded",
  "pattern": [
    "   ",
    "UUU",
    "U U"
  ],
  "key": {
    "U": {
      "item": "techreborn:uu_matter"
    }
  },
  "result": {
    "item": "minecraft:scute"
  }
}
</code>
</pre>
<br>
<p align="center">
<img src="https://user-images.githubusercontent.com/48316573/197009955-2984e0bf-3a09-4b6b-b850-b17e1b085009.png" width="500">
</p>

OR

Change the recipe of Scute to another
<pre><code class="language-json">
{
  "type": "reborncore:padded",
  "pattern": [
    "UUU",
    "UCU",
    "   "
  ],
  "key": {
    "C": {
      "item": "techreborn:calcite_dust"
    },
    "U": {
      "item": "techreborn:uu_matter"
    }
  },
  "result": {
    "item": "minecraft:scute"
  }
}
</code>
</pre>
<br>
<p align="center">
<img src="https://user-images.githubusercontent.com/48316573/197013882-22f13d8a-b4b2-49fb-8ed5-f1d1ae469c4b.png" width="500">
</p>

</details>

**Summary**
I'm afraid to jump to conclusions, but all recipes that use tags instead of an item in the "key" object don't work correctly

**Comment by OberstK** [comment]
Can confirm this issue on 1.19 with TechReborn 5.3.2 as well (Fabric 0.14.9)

**Comment by Ayutac** [comment]
the issue with the calcite recipes is because I wrote calcium_dusts instead of calcite_dusts. That is easy to fix and I have a PR ready. The other issue is the symmetric crafting, which even holds for regular uu matter.

**Comment by Ayutac** [comment]
Wow, symmetric crafting is intended for shaped recipes. I didn't know that! But this makes it very fixable
