### ISSUE TITLE
[1.16.5 FABRIC] Chunk loader is broken

### ISSUE THREAD

**Issue by quentin452** [TechReborn/TechReborn#3048]
**tech reborn**

**Describe the bug**

The chunk loader use alot of tps

TechReborn-1.16-3.8.4+build.236

**Screenshots**

with chunk loader

![Capture d’écran_2022-10-22_13-56-18](https://user-images.githubusercontent.com/42176772/197337660-ed1d5796-fc23-49f8-b2b1-731546fde983.png)

without chunk loader

![Capture d’écran_2022-10-22_13-56-04](https://user-images.githubusercontent.com/42176772/197337656-e4cc54ba-9f56-4e74-80c9-ee037fe5e7c5.png)

**Comment by Ayutac** [comment]
What do you propose should be changed?

Also I wouldn't call it broken.

And 1.16.5 is not supported anymore. Does this still persist on 1.19.2?

**Comment by modmuss50** [comment]
1.16.5 is not supported, I belive this issue has been fixed in newer versions. Sorry about that.
