### ISSUE TITLE
REI "Rendering entry" crash

### ISSUE THREAD

**Issue by Anzarot121** [TechReborn/TechReborn#3050]
**Describe the bug**
REI reports "Rendering entry" when I try to view Tech Reborn item recipes

**Steps to Reproduce**
- Install Sky FABRICation 3,
-  favorite many items from TR in REI
- Catch the log from REI

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
latest.log
https://privatebin.net/?e420d0d1ae8b3a9e#9DoiYJk2m3ZN9Pob42V2eDo26RMYDjN5Dnaa8SRx2MW
REI crash log
https://privatebin.net/?3e99d9421a2be00d#6R8QwSMwcVsUVzm6e4Du7qN7ZHEJscTwtsvkbh6v36sQ
**Additional context**

**Comment by modmuss50** [comment]
Paste has expired, please open an new issue if this still happens
