### ISSUE TITLE
Autocrafter can dupe remainers

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#3066]
**Describe the bug**
Recipes can have multiple reminders I suppose, for example in Croptopia. Don't know in vanilla. Autocrafter has only 1 place for reminders. if there are different reminders from a crafting recipe, they get converted to the first one.

**Steps to Reproduce**
- new world with TR and Croptopia
- place down creative solar panel and autocrafter next to it
- use the shapeless recipe for tortillas in the autocrafter (croptopia flour + croptopia frying pan + bucket of water)
- results in 2 tortillas (thats planned) and 2 frying pans in the remainder slot

**Screenshots**
normal crafting
![2022-11-19_17 18 05](https://user-images.githubusercontent.com/7873396/202861319-e22beef4-fe1b-4b50-98c2-5d243d821747.png)
![2022-11-19_17 18 08](https://user-images.githubusercontent.com/7873396/202861322-922514f4-ef94-4865-8b68-69b8a0b7ac33.png)
autocrafting
![2022-11-19_17 12 18](https://user-images.githubusercontent.com/7873396/202861337-e51fc83b-69a0-408a-9e1a-e2e12fdaf988.png)
![2022-11-19_17 12 21](https://user-images.githubusercontent.com/7873396/202861363-9641c8c0-60de-4b1b-bb7b-6f0c919558ec.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: 0.14.10
 - Fabric API: 0.63.0
 - TR: 5.3.4
 - Croptopia: 2.1.0

**Comment by Technici4n** [comment]
An easy solution here is to add an internal "remainder queue".
