### ISSUE TITLE
[1.8.8] update to latest JEI api

### ISSUE THREAD

**Issue by BBoldt** [TechReborn/TechReborn#307]
https://paste.ee/p/MU85C

```
<mezz> it's using an old JEI api
<mezz> which is a real crash
<mezz> JEI's api should be more stable from here on, there isn't a lot to add or change
<mezz> but he added support very early
<BBoldt> I'll include what you just said in the bug report
<mezz> ok, bug report should just be "update to latest JEI api"
<mezz> he'll know what to do
<mezz> I think he was waiting  for fluid support, which I just added yesterday and will be releasing soon
```

* TechReborn-1.8.8-0.7.2.40-universal
* jei_1.8.8-2.8.3.39
* Forge 11.15.0.1635

**Comment by BBoldt** [comment]
Didn't notice I wasn't on the latest tech reborn version, but I don't know if it is fixed in that either. Feel free to yell at me if it is. :P

**Comment by modmuss50** [comment]
It's not the first time the API had broken, I will update it when I get the chance.

**Comment by modmuss50** [comment]
Its working fine for me on:
JEI: 2.9.0.42
Techreborn on 1.8.8 branch
