### ISSUE TITLE
Server crash - TR Cables connected to Powah! cables

### ISSUE THREAD

**Issue by dandin87** [TechReborn/TechReborn#3075]
**Describe the bug**
Server crash when TR Cables connected to Powah! cables - Amount may not be negative, but it is: -4

**Environment (please complete the following information with the version):**
 - Minecraft: [1.18.2, 1.19.2]
 - Mod Loader: [Fabric]
 - Modpack: All of Fabric 5 and 6

**Logs**
https://aofpaste.com/hiveribaza.yaml

**Additional context**

**Comment by Ayutac** [comment]
This shouldn't happen anymore with the newest version of TR I think. What TR version is this on?

**Comment by ImAK9** [comment]
> This shouldn't happen anymore with the newest version of TR I think. What TR version is this on?

5.4.0 for AOF6

**Comment by Technici4n** [comment]
This is a different crash - happens when TR cables are being inserted into while they're pushing energy, most likely.

**Comment by Avakining** [comment]
Is there any way to fix a world this has happened to?

**Comment by Technici4n** [comment]
Edit chunk NBT to make the energy amounts positive again.

**Comment by Frontrider** [comment]
> Edit chunk NBT to make the energy amounts positive again.

How do I do that?

**Comment by fsedarkalex** [comment]
I think #3085 and #3127 are related

**Comment by Ayutac** [comment]
This should be fixed with newest version of Powah, see #3127

**Comment by Frontrider** [comment]
It is in fact fixed with that.
