### ISSUE TITLE
1.19.3 Rubber saplings dont grow

### ISSUE THREAD

**Issue by BernardoGrigiastro** [TechReborn/TechReborn#3078]
Planted saplings dont grow, if bone meal is used it advances to stage 1 but no further than that

TR 1.19.3 latest modmuss artifact
Fapi 0.67.3+1.19.3

**Comment by Ayutac** [comment]
they have place to grow?

**Comment by BernardoGrigiastro** [comment]
Place?

**Comment by Ayutac** [comment]
place above them, as trees need it

**Comment by modmuss50** [comment]
I wonder why? :D 

https://github.com/TechReborn/TechReborn/blob/1.19.3-port/src/main/java/techreborn/world/RubberSaplingGenerator.java#L41-L45

I commented out the code and never put it back lol

**Comment by BernardoGrigiastro** [comment]
:D

**Comment by modmuss50** [comment]
Fixed, thanks for testing 👍
