### ISSUE TITLE
Greenhouse controller being powered causes issues with block updates.

### ISSUE THREAD

**Issue by Asylum-Media** [TechReborn/TechReborn#3079]
**Describe the bug**
Something in TR power delivery to the greenhouse controller is causing insane block lag issues (afaik this is what it is)

**Steps to Reproduce**
- First Step
connect up the system using gold cable. I used thermal gennies with a lava farm, supplemented in the daytime with solar, powering a fully lighted 4-high rack. 
- Second Step
experience blocklag

**Screenshots**
I did one better than screenies and made a short example clip
https://youtu.be/gyXf4EJljN8

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric
 - Mod Version 5.4.0 with latest Reborn Core
 - Served on separate LAN machine, 9600K, 16Gb DDR4, basically dedicated to local MC

**Logs**
https://pastebin.com/xEWBXWbt

**Additional context**
There are no other power delivery or tech mods in my pack.
We had no issues with doors or block lag up until I placed a greenhouse controller.
We _THOUGHT_ that the issue may be Prefab (I've had a couple issues in the past and presumed, so that's why you're seeing removal evidence in the log) as the Phasic doors block stopped working properly around the same time that this started. As a precaution I removed it, but the problem still remains, leaning toward it being a Tech Reborn issue.
As you can see in the YT video, it's all blocks being affected, only being corrected by a right click.
As soon as the power is disconnected all is fine.
I'm also seeing lag with rubber trees and anything made of rubber wood.
Buttons will not update their status without a right click, for example; a rubber button for a powered rail, right clicking the rail returns the button to it's inactive position.
Growth of the trees shows only the bottom log, all other blocks appear only after a server relog.
The damndest thing is there is little to no MSPT increase while this is occurring, or when connecting the power.

**Comment by Asylum-Media** [comment]
I went and grabbed my grinder, to test if is the power provision or cabling causing the issue, but it is currently grinding bone at its normal rate, causing no issues as it does. Thus, I'm presuming it's a Greenhouse Controller issue.

**Comment by drcrazy** [comment]
Can you try with TR only?

**Comment by drcrazy** [comment]
No response from reporter.
