### ISSUE TITLE
Villagers need fixing in the lang file

### ISSUE THREAD

**Issue by BernardoGrigiastro** [TechReborn/TechReborn#3083]
Villagers have this in the lang file:

  "entity.minecraft.villager.metallurgist": "Metallurgist",
  "entity.minecraft.villager.electrician": "Electrician"

but jade shows this instead:

entity.minecraft.villager.techreborn.metallurgist
entity.minecraft.villager.techreborn.electrician

TR 1.19.3-port

**Comment by Ayutac** [comment]
more villagers has the same pattern as well, that is:
entity.minecraft.villager.modid.villagername

Will fix the lang file real quick
