### ISSUE TITLE
Villagers shows internal name on trade screen

### ISSUE THREAD

**Issue by BernardoGrigiastro** [TechReborn/TechReborn#3087]
Screenshot says it all..

TR 5.5.0
Fapi 0.68.1+1.19.3

![SS2](https://user-images.githubusercontent.com/47037877/206446089-38da0fe0-d3af-4efd-97c0-4d283440a8be.png)

...
Jade is working fine

![SS1](https://user-images.githubusercontent.com/47037877/206446192-d145e017-08af-42a6-b22e-3ba3dc5d073f.png)

**Comment by Ayutac** [comment]
https://github.com/TechReborn/TechReborn/issues/3083 D:

**Comment by Ayutac** [comment]
I think this is a bug in jade actually...
Thanks for testing btw

**Comment by BernardoGrigiastro** [comment]
I tested without jade and it does the same

**Comment by Ayutac** [comment]
No, I mean, that jade uses entity.villager.modid.jobname instead of entity.villager.jobname is a bug.

**Comment by BernardoGrigiastro** [comment]
Oh i see what you mean, the previous issue is on jade side... and both are fixed with that commit :D
