### ISSUE TITLE
Generic bucket model not working properly with resource pack

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#3090]
**Describe the bug**
My resource pack replaces the textures for your universal bucket model (for liquids from your mod), but it does not work correctly in the game.

**Steps to Reproduce**
- Install Tech Reborn
- Apply my resource pack

**Screenshots**
![](https://imageup.ru/img190/4106940/2022-12-11_225416.png "Demonstration")

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.3
 - Mod Loader: fabric
 - Fabric Loader: 0.14.11
 - Fabric API: 0.69.0
 - Mod Menu: 5.0.2
 - Reborn Core: 5.5.0
 - Tech Reborn: 5.5.0

**Logs**
[latest.log](https://gist.github.com/WantaSanchez/2e6474cf841f0a47fd4e87dc15b9bbe2)

**Additional context**
[Link to my resource pack](https://www.curseforge.com/minecraft/texture-packs/faithful-ultimate/files/4166484 "Faithful Ultimate")

**Comment by xanthian** [comment]
Whats wrong with it? (apart from being 32x) 👎🏼

**Comment by ghost** [comment]
> Whats wrong with it? (apart from being 32x) 👎🏼

The bucket part works fine, but the part of the texture that is automatically colored depending on the content (from the modification) does not change to the texture from my resource pack. At the same time, the names of the files, their paths and transparency parameters are normal.

**Comment by Ayutac** [comment]
Why would it change though?

**Comment by ghost** [comment]
> Why would it change though?

So that the mod normally uses resource packs? I do not understand your question.

**Comment by xanthian** [comment]
I'm massively confused here.
Which bit isn't changing?

**Comment by ghost** [comment]
> I'm massively confused here. Which bit isn't changing?

Look, instead of a couple dozen textures for each bucket of liquid (for example, sodium), the mod uses a universal bucket model. It consists of two textures, it is `backet_background.png` and `bucket_base.png`. Here they are in the mod's file structure:
![](https://imageup.ru/img285/4110382/screenshot_1.png)

In my resource pack, I make both of these textures at 32x, but only `backet_background.png` from resourcepack is used in the game.

**Comment by xanthian** [comment]
So the fluid texture. Why not just say that.
Not sure how this is a TR issue??

________________________________

**Comment by ghost** [comment]
> So the fluid texture. Why not just say that. Not sure how this is a TR issue?? Get Outlook for Android<https://aka.ms/AAb9ysg>

I'm not sure if the universal bucket model is RebornCore, but the textures I changed belong to TechReborn.

**Comment by drcrazy** [comment]
Can you try with minecraft buckets?

I think we don't actually use TR bucket textures.
https://github.com/TechReborn/TechReborn/blob/48f312d848ad2c71a01e4cfdb293ba525103ad2b/src/client/java/techreborn/TechRebornClient.java#L121

**Comment by drcrazy** [comment]
Is it still reproducible in 1.20?

**Comment by modmuss50** [comment]
Closing as no response.
