### ISSUE TITLE
Pull lava from cauldron via cell makes water withdraw sound.

### ISSUE THREAD

**Issue by WaffleDevsAlt** [TechReborn/TechReborn#3095]
**Describe the bug**

**Steps to Reproduce**
- Right click lava filled cauldron with empty cell

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.3
 - Tech Reborn: 5.5.0
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by drcrazy** [comment]
Fixed in 1.20
