### ISSUE TITLE
Mod incompatibility with Stacker resulting in item loss

### ISSUE THREAD

**Issue by Cirnobyl09** [TechReborn/TechReborn#3096]
Using certain machines such as the Iron Furnace and Iron Alloy Smelter will clamp stacks to 64 even if you have mods like Stacker installed. Stacker changes how stacks work to allow stack sizes much greater than 64.

While having the Stacker mod installed, have a stack of 65 or more items and place it into the Iron Furnace or Alloy Smelter. It will be clamped to 64, causing item loss.

Using Fabric with Minecraft 1.19.2. Stacker mod 3.0.2 and TechReborn 5.4.0.

**Comment by Technici4n** [comment]
Don't expect mods to support stack sizes above 64. Stacker doing is very hacky stuff to get around a lot the limit... This generally breaks with mods. Don't use Stacker in serious playthroughs.
