### ISSUE TITLE
Experience collection upgrade

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#3097]
It would probably be nice to be able to gain experience in smelting in electric furnaces and possibly other mechanisms. I think such an improvement can be made at several levels with a different limit on the accumulated experience. To collect experience from the storage, you can either click on the storage indicator or use a separate button.

**Comment by xanthian** [comment]
This has been asked numerous times.
No was the answer then.

**Comment by Ayutac** [comment]
the reason for no was that there would be no limit. A limit is suggested here, hence slightly different

**Comment by xanthian** [comment]
> the reason for no was that there would be no limit. A limit is suggested here, hence slightly different

The point is that granting xp with 4x overclockers is just too op.

There isn't really a reasonable limit you could apply unless you provide 1000x less xp per.. At that point it won't be worth the effort coding or using it.

**Comment by Ayutac** [comment]
I can see providing 1 XP for 64 items

**Comment by drcrazy** [comment]
It's not about grant rate or XP storage. There are two edge cases for electric furnace:
1) The very first machine and XP is important at that time. Thus request sounds reasonable.
2) You have dozens of electric furnaces which are processing hundreds of ores from your quarry. Player will not pop-in into processing room every other minute to gather that experience.

Requested feature will be a waste of dev time for second case. Moreover, for early game we have an iron furnace, which is faster than vanilla furnace and provide experience.  

Thus we have first case partially covered by lower tier machine. And there is no need for this feature at all in the second case.

Feel free to re-open if there is a good and well-known way to automate XP collection from dozens of electric furnaces constantly smelting tons of metals.

**Comment by ghost** [comment]
Hmm, could implement the Thermal Foundation's "fluid experience" and the ability to pump it into a reservoir (if Tech Reborn ever gets its own pipes). Or you can look at experience crystals like in Create. When the counter accumulates conditionally each X of experience, put a crystal in a separate slot and reset the counter? Thus, you can not only collect experience, but also automate its unloading into containers, and if necessary, the crystal can be broken to get experience points.

**Comment by Ayutac** [comment]
> if necessary, the crystal can be broken to get experience points.

i.e. sculk

**Comment by ghost** [comment]
> > if necessary, the crystal can be broken to get experience points.
> 
> i.e. sculk

Or experience bottle :D

**Comment by ghost** [comment]
However, it is possible to make crystals with a specified amount of experience when using them.
