### ISSUE TITLE
LESU controller doesn't scale/reset as intended.

### ISSUE THREAD

**Issue by WaffleDevsAlt** [TechReborn/TechReborn#3100]
Note: This is based off of information coming from the [LESU Controller wiki page](https://wiki.techreborn.ovh/doku.php?id=energy:batteries:lesu) and the [LESU Storage wiki page](https://wiki.techreborn.ovh/doku.php?id=energy:batteries:lesu_storage).

**Steps to Reproduce**
- Add/remove LESU Storage Blocks to the LESU Controller
- Observe

Video:
https://youtu.be/JuEll4rtTP4 : Shows both bugs at the same time. Individual bug showcases below.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.3 with TechReborn-5.5.0.jar
 - Mod Loader: Fabric

# **Scale Bug:**

Explanation:
On the wiki, it says 
![image](https://user-images.githubusercontent.com/81845843/210107705-07c3364e-4970-4f82-9842-1e2e0c472ef6.png)

Which should mean that for every storage block;
The max energy gets 1mE added with base of 1mE,
The max input gets 1E/t added with base of 32E,
The max output gets 1E/t added with base of 5E.

Ex: A controller with 7 storage blocks would have, 8m max energy storage, 12E/t output and 39E/t input.
However, [observed ingame](https://youtu.be/zLd56BEwjKA), it would actually be 8m max energy storage. 12E/t output and 32E/t input.

# **Reset Bug:**

Explanation:
When removing LESU Storage Blocks from the LESU Controller, it doesn't reset the Input E/t value.

[Observe](https://youtu.be/PVMxa8mI_Aw). Controller with 0 added blocks and having input of 128E/t.

**Comment by drcrazy** [comment]
Wiki also updated to describe proper stepped Input rate behaviour.
