### ISSUE TITLE
please Help The mod is what Makes SecurityCraft Work So can you please Fix it

### ISSUE THREAD

**Issue by xXshadowWolf** [TechReborn/TechReborn#3101]
**Describe the bug**

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [ 1.12.2 Modpack]
 - forge Mod Loader ]

**Logs**
[Vanilla 1.12.2 Crash Report [#S4GKl3E] - mclo.gs.pdf](https://github.com/TechReborn/TechReborn/files/10339963/Vanilla.1.12.2.Crash.Report.S4GKl3E.-.mclo.gs.pdf)

Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by xXshadowWolf** [comment]
https://mclo.gs/S4GKl3E

**Comment by Ayutac** [comment]
If it works, why did it?
Jokes aside, 1.12 and forge are not supported anymore
