### ISSUE TITLE
Ore Slabs and Ore Stairs don't have a way to pickup.

### ISSUE THREAD

**Issue by WaffleDevsAlt** [TechReborn/TechReborn#3104]
**Describe the bug**
When destroying any of the x_storage_block_stair's or x_storage_block_slab's with a gold pickaxe or better, they don't drop anything.

**Steps to Reproduce**
- Place any tech reborn storage block stair or slab
- Mine it
- Observe

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric

**Comment by Ayutac** [comment]
Can confirm for dev

**Comment by Ayutac** [comment]
I understand why it doesn't work for slabs and stairs. What I don't get is why it works for walls??
