### ISSUE TITLE
Industrial grinder multiblock issues

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#311]
First, placing water in the center of the multiblock does not work, it needs to be air 
Secondly, it does not detect multiblock structure properly after server reboot. I have to replace the central block with something else and break it to make it work.

**Comment by yuyuyzl** [comment]
well it is proved that the Arcane lamp in thaumcraft put a invisible light source in the center of the grinder and your machine won't accept it as air. so plz use isAir() method or just replace it with water source, thanks for your help.

**Comment by modmuss50** [comment]
Thats a new one! I will get that fixed
