### ISSUE TITLE
JEI integration bug

### ISSUE THREAD

**Issue by Igor4er** [TechReborn/TechReborn#3112]
**Describe the bug**
JEI integration doesn't work as it should. Some machines have a button for JEI integration (for example, the compressor in the screenshot). This button does not work.

**Steps to Reproduce:**
- Install Tech reborn
- Install JEI

**Screenshots:**
![Знімок екрана з 2023-02-13 11-07-43](https://user-images.githubusercontent.com/34284347/218416332-3fad19d5-6be3-48d9-910e-1f8f215c78ec.png)

**Environment:**
 - Minecraft: 1.19.2
 - Tech reborn: 5.3.4
 - Reborn core: 5.3.4
 - Mod Loader: fabric

**Comment by modmuss50** [comment]
This is a relic from when TR was on forge. I think for now the best thing is to remove this button, and then maybe replae it with something that works for both JEI and REI.

**Comment by Igor4er** [comment]
So should i close this and create feature request?

**Comment by modmuss50** [comment]
No, this bug report is great 👍 I was just commenting on how I think we should go about resolving it.

**Comment by modmuss50** [comment]
I removed this button
