### ISSUE TITLE
Game crashes when adjusting launch pad power

### ISSUE THREAD

**Issue by Kamikamiku** [TechReborn/TechReborn#3113]
**Describe the bug**
Game crashes when adjusting launchpad power

**Steps to Reproduce**
- First Step
Give yourself a launchpad and place it down.
- Second Step
Right click it to open the GUI and adjust the power whatever you want.

**Screenshots**
None

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.3
 - Mod Loader: Fabric 0.14.14

**Logs*
[latest.log](https://github.com/TechReborn/TechReborn/files/10722328/latest.log)
*

**Comment by maxvar** [comment]
related to https://github.com/TechReborn/TechReborn/issues/3091 ?

**Comment by drcrazy** [comment]
Closed by https://github.com/TechReborn/TechReborn/commit/9faa0089390f1a27a923c8944bde64a92dcc4966
