### ISSUE TITLE
used nvg crashed game cant get back on

### ISSUE THREAD

**Issue by spider123s** [TechReborn/TechReborn#3114]
i made the night vision goggles and put them on and it froze and crashed and now i cant get back on

**Comment by loleq2105** [comment]
The goggles come from my mod, Gear Reborn, which is precisely for 1.19 only. It's my fault I have improperly tagged it to be otherwise. The latest version doesn't work properly in 1.19.1+.  Just remove Gear Reborn for now. I'll put out a working version soon.

**Comment by drcrazy** [comment]
Not related to TR
