### ISSUE TITLE
reborncore render command produces upside down result with RC 5.5.0

### ISSUE THREAD

**Issue by maxvar** [TechReborn/TechReborn#3115]
**Describe the bug**
Command `/reborncore render hand` (or `item …`) produces image of the block upside down.

**Steps to Reproduce**
run command `reborncore render item techreborn:drain`
check the produced image

**Screenshots**
Drain:
![drain](https://user-images.githubusercontent.com/5999536/219488496-edefebf5-f054-4bdd-a0cf-d1e19b02bf75.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.3
 - Mod Loader: fabric
 - RC+TR 5.5.0

**Additional context**
A previous version working fine (in my MultiMC set of instances) is RebornCore-5.1.0-beta.5.jar for 1.18.1
![drain](https://user-images.githubusercontent.com/5999536/219488898-7edbc58c-21b5-4405-8d08-cc7cc83f58b7.png)

**Comment by modmuss50** [comment]
I fixed this in the 1.20 port.
