### ISSUE TITLE
Storage Buffer causes item loss when items are inserted while locked and no items in the OUT slot

### ISSUE THREAD

**Issue by trunksbomb** [TechReborn/TechReborn#3119]
_See edit history for original reported issue._

The issue is: A locked Storage Buffer with nothing in the OUT slot will consume everything from the IN slot except for the last item in the IN slot.

**Steps to reproduce:**

1. Place a Storage Buffer
2. Open the Storage Buffer
3. Insert at least one item and lock the Buffer
4. Remove all items from the OUT slot of the Buffer
5. Insert 2 or more of the same item in the IN slot
6. Observe the IN slot quickly drain to empty while putting nothing in the OUT slot, except for the last item in the stack from the IN slot.

**Expected Behavior:**
Don't eat my items 😢 

**Additional info:**
This behavior doesn't appear to be present for other storage units

**Version Info:**
Minecraft 1.21
TR 5.11.4
Fabric Loader 0.15.11
Fabric API 0.100.3+1.21

**Log:**
https://mclo.gs/Ji4VMf5

Item loss with manual insertion:
https://github.com/TechReborn/TechReborn/assets/1904331/6a7942ee-9206-43a9-9755-adefa0c7f6a2

Item loss with automation via "auto input" on the Buffer:
https://github.com/TechReborn/TechReborn/assets/1904331/821eb022-05d6-417d-bf82-febef59abaf5

Item loss with automation via "auto output" on an adjacent Storage Unit:
https://github.com/TechReborn/TechReborn/assets/1904331/d34dc196-7293-4f7a-9f55-c8def0369ab9

**Comment by trunksbomb** [comment]
Oh, interesting. it doesn't have anything to do with Create specifically, that's just how I discovered it.

After writing the bug report, I wondered if any other mod could cause this.

I have confirmed that using the Cardboard Box from Coxinha Utilities also causes the same bug.   
- Shift Right Click the Cardboard Box onto the Storage Buffer after setting it up (locking, empty) according to steps above
- The Cardboard Box will replace the Storage Buffer
- It is not necessary to pick up the Cardboard Box (by breaking it) and placing it down somewhere else, but you can if you want to
- (Place the Cardboard Box down if you picked it up then) Shift Right Click the cardboard box to remove it from the Storage Buffer
- Same bug happens

It appears to be a problem with saving and reloading the Storage Buffer, since I believe that's how both Create and Coxinha handle moving Tile Entities.

**Comment by trunksbomb** [comment]
Yea, confirmed that just saving and reloading the game with an empty, locked Storage Buffer causes the issue.

**Comment by modmuss50** [comment]
We dont support moving block entities with none tech reborn methods. Sorry.

**Comment by trunksbomb** [comment]
I saw this in my notifications and was confused because I didn't remember making any issues here lately, but this is from over a year ago lol.

Last year I also confirmed that it has nothing to do with moving the block with Create, but that it was a save/reload issue (which *can be but isn't strictly caused by* moving the block). 

I would hope that this isn't relevant anymore because it's been fixed elsewhere, but the reason for closing ("moving block entities with none tech reborn methods") isn't even relevant to this issue anymore 🙃

**Comment by trunksbomb** [comment]
https://github.com/TechReborn/TechReborn/assets/1904331/6a7942ee-9206-43a9-9755-adefa0c7f6a2

Here's the bug in the latest version of TR for 1.21. TR (5.11.4) + Fabric API are the only two mods installed.

**Comment by trunksbomb** [comment]
I updated the main description to reflect the nature of this bug more accurately, and included a few videos demonstrating it.
