### ISSUE TITLE
Rubber Trees break block above when growing

### ISSUE THREAD

**Issue by MorganeLeCaignec** [TechReborn/TechReborn#3131]
**Describe the bug**
When a Rubber Tree sapling is grown, the top leaf block seems to ignore the presence of a roof by 1 block. Regularly, a grown rubber tree will replace a block in the roof above it with a leaf block.
I've tried with cobble, stone, iron blocks and obsidian. This seems to be a bug regarding the detected height of the tree or maybe the height that the sapling requires to grow, since the rubber trees have a distinctive "spike" or leaves on top, this spike may be 1 block too high in how it detects a roof.

**Steps to Reproduce**
- Plant a rubber tree sapling, with 8 blocks of air (as an example, 9 or 10 height works too) above the sapling and a roof.
- Wait for the tree to grow or use bonemeal
- Regularly, a grown tree will have replaced the roof block above with a leaf block, destroying it completely.

**Screenshots**
![image](https://user-images.githubusercontent.com/12102823/234270229-137b5e7c-7745-43aa-85cb-8b6911d010cd.png)

![image](https://user-images.githubusercontent.com/12102823/234270463-93ad4d02-9bf5-496e-b0c6-0c4f4b268b31.png)

![image](https://user-images.githubusercontent.com/12102823/234270539-3a350fd0-b765-4fc4-a949-c5c841270258.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
part 1 : https://pastebin.com/SD4xJqVV
part 2 : https://pastebin.com/dRsFDk9S

**Additional context**
Playing on the Create Astral modpack, with create mod, but this behavior appears with normal dirt, normal sapling and bonemeal applied to it.

**Comment by Ayutac** [comment]
Confirmed for 1.19.4. I have a rough idea why, I will have a look.

PS: thanks for the excellent bug report :)
