### ISSUE TITLE
Tech Reborn crash with Advanced Reborn in 1.20

### ISSUE THREAD

**Issue by realBritakee** [TechReborn/TechReborn#3144]
**Describe the bug**
When only using Tech Reborn and Advanced Reborn the game crashed with reason "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'advanced_reborn'!"

**Steps to Reproduce**
- Make a new 1.20 Fabric 0.14.21 modpack in Curse Forge Launcher
- Add Tech Reborn, Advanced Reborn and Reborn Core
- Start and see

**Screenshots**

**Environment:**
 - Minecraft: 1.20
 - Mod Loader: Fabric 0.14.21

**Logs**
https://pastebin.com/bhuuavsi | Latest Log
https://pastebin.com/yzsgpUJx | Crash Report

**Additional context**

**Comment by modmuss50** [comment]
Hi, thank for opening an issue. This appears to be a bug with Adanced Reborn and not Tech Reborn. I reccomend opening an issue on their repo.
