### ISSUE TITLE
Rubber trees dont regenerate sap.

### ISSUE THREAD

**Issue by chainsawpenguin** [TechReborn/TechReborn#3147]
**Describe the bug**
after the first time rubber trees spawn sap, that same tree will never produce sap again. Basins make no difference.

**Steps to Reproduce**
Sap is collected from tree, and tree never produces sap again. tree must be cut down and replaced by a new sapling in order to get more sap

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft 1.20.0
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**
I've never found anything useful in the log but here it is. also, this is on a server, with the techreborn mod running on server and client side. we are not using te reborn core.
[latest.log](https://github.com/TechReborn/TechReborn/files/11784118/latest.log)

**Comment by chucklet** [comment]
Having the same issue on 1.20.1
