### ISSUE TITLE
Some translations are not included

### ISSUE THREAD

**Issue by squid233** [TechReborn/TechReborn#3148]
**Describe the bug**
Some translations are not included. For example, "tier" should be "能量等级"
![oncrowdin](https://github.com/TechReborn/TechReborn/assets/60126026/56f230b7-d43c-4ec1-8945-b989eaa19b5f)
![ingame](https://github.com/TechReborn/TechReborn/assets/60126026/48e6c0b2-99ad-4d2f-98b6-9ac4ea4242c8)

**Steps to Reproduce**
- Download from CurseForge and add TechReborn

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: fabric
 - Tech Reborn: v5.8.1

**Comment by modmuss50** [comment]
RebornCore (A sub project of TR) has its own set of translations that are not on crowdin: https://github.com/TechReborn/TechReborn/blob/1.20/RebornCore/src/main/resources/assets/reborncore/lang/zh_cn.json#L8

I think the solution is to move all of the translations to TechReborn (and thus crowdin), and remove any duplicate ones such as this.

**Comment by modmuss50** [comment]
I have completely changed the way that translations are handled, strings from reborn core can now be translated.
