### ISSUE TITLE
Can still fly after taking off quantum armor

### ISSUE THREAD

**Issue by Pib-k** [TechReborn/TechReborn#3150]
**Describe the bug**
Can still fly after taking off quantum armor

**Steps to Reproduce**
- Put on armor, fly
- Remove armor
- try to fly again and u can do it

**Screenshots**
![image](https://github.com/TechReborn/TechReborn/assets/116900254/5d280332-8e09-46f7-a628-ceb692c75ec3)

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.20.1]
 - Mod Loader: [Fabric]
 - Latest tech reborn version

**Comment by Technici4n** [comment]
Does this happen with only Tech Reborn and Fabric API? (no other mods)

**Comment by Pib-k** [comment]
Yes it happens while only having Fabric API and Tech Reborn installed
