### ISSUE TITLE
Player is pushed down when taken damage during quantum flight

### ISSUE THREAD

**Issue by chocobolt** [TechReborn/TechReborn#3151]
**Describe the bug**
When I get damage while flying and wearing quantum armor I will get pushing down. ( like skeleton shoot me I will keep getting down ! )

**Steps to Reproduce**
- Get damage to skeleton
- Keep getting pushing down

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric

**Comment by drcrazy** [comment]
Can't reproduce on TR 5.9.0 and MC 1.20.2

![image](https://github.com/TechReborn/TechReborn/assets/1382352/7003b2db-9ebc-43f8-9582-61fe6abd0e58)
