### ISSUE TITLE
Console Spam on Server

### ISSUE THREAD

**Issue by cheicen** [TechReborn/TechReborn#3152]
**Describe the bug**

Console is being spammed when the mod is being used alongside Origins. 

**Screenshots**
![image](https://github.com/TechReborn/TechReborn/assets/38669917/f3dda406-7f8b-45c0-96c3-07b012bfa789)

**Environment (please complete the following information with the version):**
 - Minecraft:  1.20.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

https://pastebin.com/HyRyGghR

**Additional context**

player is using quantum armor

**Comment by cheicen** [comment]
https://github.com/Ladysnake/PlayerAbilityLib

seems to be conflicting with this lib that is apart of both Origins and Amethyst Imbuement

**Comment by drcrazy** [comment]
Looks like issue is not under our control.
