### ISSUE TITLE
[1.16-3.8.4+build.236] A bug with solar panels

### ISSUE THREAD

**Issue by HIHAZET** [TechReborn/TechReborn#3153]
When interacting with solar panels, it writes that the panel is closed from the sky

Tested on different maps

Version Minecraft 1.16.5

Mod version 1.16-3.8.4+build.236
Minecraft Version  1.16.5

**Comment by Ayutac** [comment]
do you have screenshots where you placed the panels?

**Comment by HIHAZET** [comment]
Yes, of course
![2023-07-06_15 26 56](https://github.com/TechReborn/TechReborn/assets/132204059/8044e950-62ce-485a-a2f1-015b0cf26388)
![2023-07-06_15 27 00](https://github.com/TechReborn/TechReborn/assets/132204059/a8971b5a-a307-4962-89f9-e0cc45ec26be)
![2023-07-06_15 29 21](https://github.com/TechReborn/TechReborn/assets/132204059/063c61f8-5c4b-4d0c-8aab-b6708af30d18)

**Comment by Ayutac** [comment]
I dont think these generate at night, but I wouldn't know why they don't generate during day time...

Sadly, older Versions of TR are not supported anymore.
