### ISSUE TITLE
bug can't grind iron ingot to iron dust

### ISSUE THREAD

**Issue by akailham** [TechReborn/TechReborn#3158]
**Describe the bug**
bug can't grind iron ingot to iron dust, i also tried grind iron block but it become iron raw, it's different from the one on the wiki which is supposed to be iron dust, now i stuck i need iron dust to get another material

**Steps to Reproduce**
- make iron ingot
- put it to grinder 

**Screenshots**
![image](https://github.com/TechReborn/TechReborn/assets/67347182/c4da08a6-782e-4c75-8231-1b62cdeed839)

**Environment (please complete the following information with the version):**
 - Minecraft: [1.20.1]
 - Mod Loader: [fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: sorry i don't know how to

**Additional context**

**Comment by Ayutac** [comment]
wiki is not up to date in this regard. raw iron is the new iron dust and you cant get it from ingots
