### ISSUE TITLE
Quantum Suit does not give creative flight

### ISSUE THREAD

**Issue by UnRealDinnerbone** [TechReborn/TechReborn#3159]
**Describe the bug**
Quantum Suit does not give creative flight

**Steps to Reproduce**
- Wear Quantum Suit and be unable to toggle flight

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: fabric
 - Mod Version: 5.8.3

**Additional context**
quantumSuitEnableFlight is set to true

**Comment by drcrazy** [comment]
Can't reproduce. Could it be a mod conflict?

![image](https://github.com/TechReborn/TechReborn/assets/1382352/ad6d3de2-ece6-466f-ac2e-5705f1494fda)

**Comment by Neubulae** [comment]
PlayerAbilityLib complains about flight ability being tampered, I wonder that's a problem?
