### ISSUE TITLE
unable to craft stuff

### ISSUE THREAD

**Issue by gadgetshark** [TechReborn/TechReborn#3163]
**Describe the bug**
unable to craft stuff/crafting recipes missing
**Steps to Reproduce**
- First Step
fabric
- Second Step
tech reborn
**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 1.20.1
 - Mod Loader: [e.g. forge, fabric]
fabric
**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**
have been unable to craft stuff in the most recent beta for 1.20.1

**Comment by Thepigcat76** [comment]
That is a very bad description. What are you unable to craft? In which machine... Please give us more context so we can identify the problem better

**Comment by gadgetshark** [comment]
any plates. most dust into anything. most advanced machinery doesnt work. i have tried uninstalling and reinstalling to no avail

**Comment by gadgetshark** [comment]
or could be a jei incompat or smth.

**Comment by gadgetshark** [comment]
just tested. it could definitley be a jei issue now. wasnt working earlier but now i can craft stuff but jei still doesnt show recipes

**Comment by gadgetshark** [comment]
sorry if this report wasnt needed. but i think its some sort of issue with jei not showing recipes now. earlier wasnt crafting stuff. but now it is. sorry for the issue

**Comment by Thepigcat76** [comment]
Yea jei is not supported at the moment. But when opening an issue try to be as specific as possible. Don't say you can't craft anything but rather say that jei doesn't display any recipes. That would have made it easier for us to answer your question ;-)

**Comment by drcrazy** [comment]
JEI is not supported ATM
