### ISSUE TITLE
industrial grinder multiblock not completing

### ISSUE THREAD

**Issue by BloxMaster3** [TechReborn/TechReborn#3165]
**Describe the bug**
I've built it normally with 8 advanced machine casings surrounding a water block with 18 blocks of standard machine casing as the top and bottom caps creating a 3x3x3 multiblock but it won't complete. I've seen the other issues describing this but they didn't have water in the middle while I do and it still shows incomplete.

**Steps to Reproduce**
I think this is mod dependent so check the latest log but just build the industrial grinder as normal with my mods also I'm using BSL Shaders with Optifine if that helps
**Screenshots**
![2023-07-15_17 36 48](https://github.com/TechReborn/TechReborn/assets/136217084/da203baa-da59-4364-8be5-1e5db1556084)
![2023-07-15_17 37 15](https://github.com/TechReborn/TechReborn/assets/136217084/a158e373-4a4c-4fb4-a2ae-23d2148151c4)
![2023-07-15_17 37 28](https://github.com/TechReborn/TechReborn/assets/136217084/b14b9eb1-6752-462b-bae1-62756173392d)
**Environment (please complete the following information with the version):**
 - Minecraft: 1.12.2
 - Mod Loader: Forge

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[latest.log](https://github.com/TechReborn/TechReborn/files/12062847/latest.log)

**Additional context**
I'm trying to make yellow garnet for a tinker's weapon and you need the industrial grinder to do that but the multiblock won't complete

**Comment by drcrazy** [comment]
Wrong casings in the middle ring. It should be tier2 casings, not a tier 3.

**Comment by BloxMaster3** [comment]
what are the tier 2 casings called

**Comment by drcrazy** [comment]
I can't remember well how it was called in 1.12

But you can check their look on wiki: https://wiki.techreborn.ovh/doku.php?id=blocks:industrial_grinder

**Comment by BloxMaster3** [comment]
it says advanced machine casing which is what I have

**Comment by drcrazy** [comment]
Casings were renamed in 1.13. Better check look and, maybe, craft

**Comment by BloxMaster3** [comment]
ok thank you
