### ISSUE TITLE
Some zombie villagers were mistakenly rendered.

### ISSUE THREAD

**Issue by HuanGeiWoLiuGeBi** [TechReborn/TechReborn#3170]
**Describe the bug**
Some zombie villagers were mistakenly rendered.

**Steps to Reproduce**
Use Zombie Villagers Spawn Egg and you will see something filled with black and purple :(

**Screenshots**
![image](https://github.com/TechReborn/TechReborn/assets/113269187/c8d5de89-859b-44ee-ae07-a6cedd766e0e)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: fabirc

**Logs**
I don't think this need any log.

**Additional context**
Nope.

**Comment by xanthian** [comment]
This was fixed with 1.19 release
you could take the 2 files from there and datapack it as I highly doubt this will be fixed as its 1.18.

**Comment by drcrazy** [comment]
Already fixed in 1.19
