### ISSUE TITLE
[bug] [1.20.1] Inventory GUI Mod Incompat

### ISSUE THREAD

**Issue by noawx** [TechReborn/TechReborn#3172]
**Describe the bug**
When using mods like EMI or Stylish Effects, the GUI in blocks like the auto-blocker, overlaps with EMI and Stylish Effects.

**Steps to Reproduce**
1, Use a mod like EMI
2. Open Auto-Crafter etc.
3. Error occurs

**Screenshots**
![image](https://github.com/TechReborn/TechReborn/assets/76262280/79895ae8-20d0-49f0-bde3-2057c57d66df)
![image](https://github.com/TechReborn/TechReborn/assets/76262280/3d970355-fd82-4865-a0a7-ed857ca21a16)

**Environment (please complete the following information with the version):**
Minecraft Version: 1.20.1
Fabric Loader: 0.14.21
Mod Version: 5.8.5

**Comment by drcrazy** [comment]
I'm sorry but this will require a dedicate compatibility module for EMI and Stylish Effects. We already have one for REI. 

Having a lot of compatibility modules was a huge nightmare back in 1.12.
