### ISSUE TITLE
`StorageUnitBaseBlockEntity`'s `ItemStorage` lookup does not accept a null `Direction`

### ISSUE THREAD

**Issue by SquidDev** [TechReborn/TechReborn#3175]
**Describe the bug**
As of 1.19.4 (fabricMC/fabric#2909), the direction paramter to `ItemStorage.SIDED` is nullable. However, [`StorageUnitBaseBlockEntity`'s lookup function](https://github.com/TechReborn/TechReborn/blob/0b4b28dd62e423d37503ce8c79563f8fb4c3c7d6/src/main/java/techreborn/blockentity/storage/item/StorageUnitBaseBlockEntity.java#L583) does not accept a nullable side, causing crashes.

**Steps to Reproduce**
One way to reproduce this crash is with ComputerCraft, which uses the null side to get a view of the whole inventory (see cc-tweaked/CC-Tweaked#1563).

Steps to reproduce the behaviour:
- Set up a Minecraft instance with TechReborn and [CC: Tweaked](https://github.com/cc-tweaked/CC-Tweaked).
- Place down a computer.
- Place down a storage block next to the computer.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: Fabric

**Logs**
https://github.com/cc-tweaked/cc-restitched/files/12364905/crash-2023-08-17_03.37.25-server.txt

**Comment by modmuss50** [comment]
Added a quick and dirty fix, it will now default to accessing the bottom side, much better than crashing. 👍

**Comment by SquidDev** [comment]
Thanks!
