### ISSUE TITLE
Quantum armor console spam

### ISSUE THREAD

**Issue by TheNanuak** [TechReborn/TechReborn#3176]
**Describe the bug**
when a player on my server uses quantum armor the console is spammed with errors

**Steps to Reproduce**
- player joins and puts on quantum armor
- check console

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: Fabric
 - 
**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/mbSt4wWj
**Additional context**

**Comment by Technici4n** [comment]
PlayerAbilityLib is being too aggressive here with its checks...

**Comment by TheNanuak** [comment]
Is it origins, playerabilitylib or tech reborn that needs to fix this?

**Comment by Technici4n** [comment]
Debatable... I'd open a discussion on the PAL repo because they should know the problem better.

**Comment by drcrazy** [comment]
It's a PAL spamming.
