### ISSUE TITLE
 you cant make zinc with out a machine that needs zinc to make it 1.20.1

### ISSUE THREAD

**Issue by mailrevers** [TechReborn/TechReborn#3182]
**Describe the bug**

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 - Mod Loader: [e.g. forge, fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by mailrevers** [comment]
you cant make zinc with out a machine that needs zinc to make it

**Comment by xanthian** [comment]
wrong.
Raw Tin > Zinc Nuggets
![image](https://github.com/TechReborn/TechReborn/assets/7688001/db15f2e4-f51c-42b9-b663-d49d29256c12)

**Comment by mailrevers** [comment]
> wrong. Raw Tin > Zinc Nuggets ![image](https://user-images.githubusercontent.com/7688001/267466070-db15f2e4-f51c-42b9-b663-d49d29256c12.png)

that needs zink

**Comment by xanthian** [comment]
no it doesnt.
you should really use REI

you can make the mixed metal ingots using Tin, (but you get less return)

**Comment by mailrevers** [comment]
oh
