### ISSUE TITLE
[5.4.0] Fusion rector crafting not really using redstone input

### ISSUE THREAD

**Issue by Aphyxia** [TechReborn/TechReborn#3183]
**Describe the bug**
Fusion control computer ignores redstone signal for crafting.

**Steps to Reproduce**
Set crafting redstone to on, insert recipe, still crafts.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: fabric

**Additional context**
Supposedly this was fixed in a previous version as per this: https://github.com/TechReborn/TechReborn/pull/2987
but seems that it's not fixed in 5.4.0

**Comment by drcrazy** [comment]
sorry, no luv 4 old versions.
