### ISSUE TITLE
Storage Unit won't auto-input more than 64 of an item.

### ISSUE THREAD

**Issue by mcummings611** [TechReborn/TechReborn#3184]
**Describe the bug**
I have a basic storage unit set up and once it reaches 64 of whatever item is in it, it won't auto-input anymore and I can only enter stuff in manually.

**Steps to Reproduce**
Have a crude storage unit set up to automatically input items and put 64 in.

**Screenshots**
![2023-09-16_16 49 50](https://github.com/TechReborn/TechReborn/assets/61382509/f25267c8-b7b1-4287-a825-8ad81e233e05)

**Environment (please complete the following information with the version):**
 - Create Astral v2.0.5 | Minecraft 1.18.2

**Comment by drcrazy** [comment]
Can't reproduce on TR 5.9.0, MC 1.20.2

All 256 blocks were imported successfully from adjacent chest.
![image](https://github.com/TechReborn/TechReborn/assets/1382352/aca2c2e2-217d-45d8-907e-a2f1e21c208e)
