### ISSUE TITLE
A bug when attempting to connect client to LAN server.

### ISSUE THREAD

**Issue by Nelfian188** [TechReborn/TechReborn#3188]
**Describe the bug**
A bug when attempting to connect client to LAN server.

Exception: io.netty.handler.codec.EncoderException: org.apache.commons.lang3.NotImplementedException: Serializing ShapedRecipe is not implemented yet.

We worked our mod list down until we had only Fabric API, Reborn Core, and Tech Reborn. so that being the case it does not appear to be related to any other mod.

**Steps to Reproduce**
fresh install of tech reborn fabric. start LAN server. try to connect via Client on LAN network.

**Screenshots**
Not Applicable

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.2
 - Mod Loader: Fabric 0.14.22

**Logs**
https://pastebin.com/76AYyF19

**Additional context**
The log did not show the full error until after removing every other mod.

**Comment by Berytak** [comment]
I can confirm this, I also get the same error
