### ISSUE TITLE
Create crashing using REI 1.20.1 

### ISSUE THREAD

**Issue by carritguy** [TechReborn/TechReborn#3190]
my create isnt working and crashes when i click on anything in rei aswell as any create mod button? i dont know much about code and just want to play, this is the crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-10-06 18:58:44
Description: Rendering screen

java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.NonTerrainBlockRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.simibubi.create.content.kinetics.simpleRelays.BracketedKineticBlockModel.emitBlockQuads(BracketedKineticBlockModel.java:50)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.jozufozu.flywheel.fabric.model.DefaultLayerFilteringBakedModel.emitBlockQuads(DefaultLayerFilteringBakedModel.java:34)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.virtual.FixedColorTintingBakedModel.emitBlockQuads(FixedColorTintingBakedModel.java:43)
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:60)
	at net.minecraft.class_778.handler$cjo000$indium$hookRender(class_778.java:1053)
	at net.minecraft.class_778.method_3374(class_778.java)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.renderModel(GuiGameElement.java:210)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.renderModel(GuiGameElement.java:236)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.render(GuiGameElement.java:187)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.render(GuiGameElement.java:216)
	at com.simibubi.create.infrastructure.gui.CreateMainMenuScreen.renderWindow(CreateMainMenuScreen.java:115)
	at com.simibubi.create.foundation.gui.AbstractSimiScreen.method_25394(AbstractSimiScreen.java:119)
	at com.simibubi.create.infrastructure.gui.CreateMainMenuScreen.method_25394(CreateMainMenuScreen.java:82)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.simibubi.create.content.kinetics.simpleRelays.BracketedKineticBlockModel.emitBlockQuads(BracketedKineticBlockModel.java:50)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.jozufozu.flywheel.fabric.model.DefaultLayerFilteringBakedModel.emitBlockQuads(DefaultLayerFilteringBakedModel.java:34)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.virtual.FixedColorTintingBakedModel.emitBlockQuads(FixedColorTintingBakedModel.java:43)
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:60)
	at net.minecraft.class_778.handler$cjo000$indium$hookRender(class_778.java:1053)
	at net.minecraft.class_778.method_3374(class_778.java)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.renderModel(GuiGameElement.java:210)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.renderModel(GuiGameElement.java:236)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.render(GuiGameElement.java:187)
	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.render(GuiGameElement.java:216)
	at com.simibubi.create.infrastructure.gui.CreateMainMenuScreen.renderWindow(CreateMainMenuScreen.java:115)
	at com.simibubi.create.foundation.gui.AbstractSimiScreen.method_25394(AbstractSimiScreen.java:119)
	at com.simibubi.create.infrastructure.gui.CreateMainMenuScreen.method_25394(CreateMainMenuScreen.java:82)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: com.simibubi.create.infrastructure.gui.CreateMainMenuScreen
	Mouse location: Scaled: (145, 134). Absolute: (727.000000, 673.000000)
	Screen size: Scaled: (512, 274). Absolute: (2560, 1369). Scale factor of 5.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, essential
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 713062464 bytes (680 MiB) / 1845493760 bytes (1760 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1692
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31015.30
	Virtual memory used (MB): 24799.73
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amethystequipment: Amethyst Equipment 1.0.10
		animated_guns: Simple Animated Guns 1.3
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.1.12
		azurelib: AzureLib 1.0.31
		azurelibarmor: AzureLib Armor 1.0.3
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		betterend: Better End 4.0.10
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		bountiful: Bountiful 6.0.3+1.20.1
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.5
		chimes: Chimes 2.0.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 6.66
		comforts: Comforts 6.3.3+1.20.1
			spectrelib: SpectreLib 0.13.12+1.20.1
		connectedglass: Connected Glass 1.1.8
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		cosmetic-armor: Cosmetic Armor 1.6.0
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
				mm: Manningham Mills 2.3
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		creeperoverhaul: Creeper Overhaul 3.0.1
			resourcefullib: Resourceful Lib 2.0.6
				com_teamresourceful_yabn: yabn 1.0.3
		crockpot: Crock Pot 1.13.3+1.20.1
		croptopia: Croptopia 2.3.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		culturaldelights: Cultural Delights Fabric 0.14.11+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		cupboard: cupboard 1.20.1-2.0
		dawn: Dawn API 5.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
		display_case: Display Case Mod 1.0.7
		do_a_barrel_roll: Do a Barrel Roll 3.3.4+1.20
			cicada: CICADA 0.4.4
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.1
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.4
		eatinganimationid: Eating Animation 1.9.4+1.20
		edibles: Edibles 4.1
		elementa: Elementa 604
		emeraldequipment: Emerald Equipment 1.1.0
		essential: Essential 14099+deploy-staging+g4e34fe63b
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		exlinecopperequipment: Copper Equipment 2.1.6
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		extendedgears: Extended Cogwheels 2.1.0-1.20.1-0.5.1.c-fabric
		fabric-api: Fabric API 0.89.3+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+0737cd8077
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.1+0889cb7877
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fallingleaves: Falling Leaves 1.15.3
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		farmersrespite: Farmer's Respite 2.3.4
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
		fwaystones: Fabric Waystones 3.1.3+mc1.20
		geckolib: Geckolib 4.2.3
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic v2.0.0-mc1.20u1.20.1
		goblintraders: Goblin Traders 1.9.2
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		indium: Indium 1.0.21+mc1.20.1
		inventoryhud: Inventory HUD + 3.4.18
		ironchest: Iron Chests 2.0.0
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		itemfilters: Item Filters 2001.1.0-build.55
		jade: Jade 11.6.1
		jadeaddons: Jade Addons 5.2.1
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 6.1.1+1.20.1
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		litematica: Litematica 0.15.3
		lithium: Lithium 0.11.2
		malilib: MaLiLib 0.16.3
		mca: Minecraft Comes Alive 7.5.8+1.20.1
		mcpitanlibarch: MCPitanLib 1.7.8-1.20.1-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 7.1.0
		moonlight: Moonlight 1.20-2.8.42
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.3
		moremobvariants: More Mob Variants 1.2.2
		mousetweaks: Mouse Tweaks 2.25
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		notenoughanimations: NotEnoughAnimations 1.6.4
		org_jetbrains_annotations: annotations 13.0
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		promenade: Promenade 4.1.0
			biolith: Biolith 1.0.0-alpha.7
				terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.0-beta.1
		reborncore: Reborn Core 5.8.7
			team_reborn_energy: Energy 3.0.0
		resourcefulconfig: Resourcefulconfig 2.1.0
		roughlyenoughitems: Roughly Enough Items 12.0.665
			error_notifier: Error Notifier 1.0.9
		runes: Runes 0.9.10+1.20.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		smallships: Small Ships 2.0.0-a2.3.3
		sodium: Sodium 0.4.10+build.27
		spell_engine: Spell Engine 0.10.0+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.9.17+1.20.1
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.14
		terralith: Terralith 2.4.7
		toofast: TooFast 1.2.0
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.5
		trinkets: Trinkets 3.7.1
		universal_ores: Universal Ores 1.5.2
		universalcraft: UniversalCraft 312
		vigilance: Vigilance 286
		voidtotem: Void Totem 3.0.1
		wi_zoom: WI Zoom 1.5-MC1.20.1
		wizards: Wizards 1.0.1+1.20.1
		wooledboots: Wooled Boots 1.7
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 23.8.2
		xaeroworldmap: Xaero's World Map 1.34.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 30.0.101.1692, Intel
	Window size: 2560x1369
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

**Comment by drcrazy** [comment]
It is not related to TR. Please, submit this issue to Create bug tracker.
