### ISSUE TITLE
Tech Reborn Overclocker Upgrade tooltips don't reflect reality

### ISSUE THREAD

**Issue by KonSola5** [TechReborn/TechReborn#3196]
(This is Tech Reborn 5.8.7 on Minecraft 1.20.1)

## Current state
![oc](https://github.com/TechReborn/TechReborn/assets/125081901/3b42b43f-8444-4fdd-8c95-b14bcf1dd7a3)
16 upgrades with Shift:
![oc_shift](https://github.com/TechReborn/TechReborn/assets/125081901/c83e58b2-b839-4e8a-9acb-f8701a90860e)

The issues with this:
- You can't install more than 4 overclockers in a machine at once, so stats for more than 4 overclockers are completely out-of-place,
- The overclock speed is capped at 97.5% speed increase, regardless of configs,
- The power increase is **multiplicative**, not **additive**.

## The real stats after testing machines with different amounts of overclockers:
![obraz](https://github.com/TechReborn/TechReborn/assets/125081901/0b69c8a0-de21-4ab8-8132-ed41f89d0411)

**I made a suggestion in Discussions related to this issue - more on that [here](https://github.com/TechReborn/TechReborn/discussions/3195).**.

**Comment by xanthian** [comment]
https://github.com/TechReborn/TechReborn/issues/2606

**Comment by KonSola5** [comment]
... the aforementioned issue was closed, but no fix related to incorrect overclocker tooltip info has been made, the referred commit only changed some translations.

**Comment by Ayutac** [comment]
More than 4 upgrades are not antipicitated, so why would the tooltip reflect unexpected behaviour?
