### ISSUE TITLE
Changing the Energy System does not change the in-game unit at all

### ISSUE THREAD

**Issue by KonSola5** [TechReborn/TechReborn#3200]
**Describe the bug**
When you change the energy unit from E to something else, the mod's tooltips still say "E".
This may be due to hardcoding "E" in various places throughout the mod.

**Steps to Reproduce**
- Open `/minecraft/config/reborn_core/misc.json`.
- Change the "Selected Energy System" to "EU".
- Start up the game.
- Notice that all tooltips still say "E" instead of "EU".

**Screenshots**
![config](https://github.com/TechReborn/TechReborn/assets/125081901/26be3aa0-5c1d-48b3-9c23-3cdb0f9e1cd8)
![game](https://github.com/TechReborn/TechReborn/assets/125081901/233d08f4-9909-4dae-8a1c-1106c7e669b1)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Tech Reborn: 5.8.7

**Logs**
None.

**Additional context**
This change would be beneficial if someone would decide to change the mod's default "E" as the displayed unit to "EU" or ":zap:" for consistency with Modern Industrialization/Ad Astra.

**Comment by Thepigcat76** [comment]
It even says possible values E. You cannot switch between energy systems anymore that way a 1.12 and prior feature

**Comment by KonSola5** [comment]
The two changes possible:
Either:
- remove the config altogether,
- or un-hardcode the "E" string and instead pull the string from the translation/aforementioned config.

(The unit would be still functionally the same TR Energy)

**Comment by modmuss50** [comment]
TR only supports one energy system atm, this config value is a left over from when it used to support others such as EU.
