### ISSUE TITLE
Server Disconnect when Adjusting Machine Configurations

### ISSUE THREAD

**Issue by SwiftyWheels** [TechReborn/TechReborn#3201]
**Describe the bug**

When more than one player is connected to a fabric server, attempting to adjust any machine configurations through the "Configure Slots" GUI button will kick yourself or others from the server.

##### Mods Loaded
- fabric-api-0.91.1+1.20.2.jar
- RebornCore-5.9.1.jar
- TechReborn-5.9.1
- InGameAccountSwitcher-Fabric-1.20.2-8.0.2.jar (This was to test this bug offline on a LAN server.)

**Steps to Reproduce**
1. Launch Minecraft
2. Join a single-player world
3. Open to LAN
4. Have another client join LAN world
5. On first client, open any Tech Reborn block item GUI by right clicking block
6. Press Configure Slots button on top-left-hand side of machine GUI
7. Press any red slot in machine GUI to open configuration GUI
8. Press any option in configuration GUI (e.g., "Auto Input", "Adjust Block Face Input/Output")
9. Second client will disconnect with Internal Exception

**Screenshots**

![image](https://github.com/TechReborn/TechReborn/assets/75949606/661c469a-6dab-4b77-b625-8566c83f92e6)
![image](https://github.com/TechReborn/TechReborn/assets/75949606/a9e2e78f-8fde-41fd-97e3-54ee3c90da86)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.2
 - Mod Loader: Fabric 0.15.0

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/3UT4kGhg

**Additional context**
I have run into this issue originally on a Docker hosted fabric server which is running on Ubuntu. I have tested this issue on Windows 10 as well in a LAN server.

**Comment by modmuss50** [comment]
This was fixed in Fabric API 0.91.2.
