### ISSUE TITLE
fabric 1.20.1 no item recepies in jei

### ISSUE THREAD

**Issue by hallool** [TechReborn/TechReborn#3202]
**Describe the bug**
no item recepies in jei like smelting cobble stone or modded items

**Steps to Reproduce**
- First Step search a item u want to craft/smelt/bla bla in jei
- Second Step dont find it

**Screenshots**

![grafik](https://github.com/TechReborn/TechReborn/assets/48066058/a10e8a33-7e16-43a1-9979-f1b2355e24eb)

it should show smthn like this

![grafik](https://github.com/TechReborn/TechReborn/assets/48066058/2dd2ae38-e02b-40b2-a0e8-794db57f11a5)

it is the same with every tech reborn machine

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: fabric

**Logs**
dont know if it even gets log:ed

**Additional context**

**Comment by Thepigcat76** [comment]
we do not support jei use rei instead

**Comment by Syddd04** [comment]
general rule of thumb for most mods:

Fabric - REI
Forge - JEI

**Comment by drcrazy** [comment]
JEI compat is out of scope as for now. Please, use REI.
