### ISSUE TITLE
Raw Iron and Copper cannot be ground in the grinder.

### ISSUE THREAD

**Issue by zpalmer618** [TechReborn/TechReborn#3203]
It would make sense, now that iron ore is deprecated and has hence been renamed "raw iron," that the mod should be updateed in this way to accept raw iron and raw copper in the grinder.

 - Minecraft 1.20.2 [All the Fabric 5]
 - Mod Loader: [ATLauncher]

**Comment by xanthian** [comment]
https://github.com/TechReborn/TechReborn/issues/3158

**Comment by drcrazy** [comment]
Works as intended. Please, see mentioned issue.
