### ISSUE TITLE
rubber sappling won't grow in 1.20.4

### ISSUE THREAD

**Issue by RicardoRDSF** [TechReborn/TechReborn#3204]
Rubber tree seedlings simply don't work, I just saw a comment about it on discord so I just came to report that it happened to me too

 - Minecraft: [1.20.4]
 - Mod Loader: [fabric]

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/TechReborn/commit/4ee488d08c084abb4454c4fa553e5ada765e032f

Thanks.
