### ISSUE TITLE
Autocrafter causes server crash in Modern Skyblock 3

### ISSUE THREAD

**Issue by torbeneims** [TechReborn/TechReborn#3205]
**Describe the bug**
We are playing Modern Skyblock 3. I am trying to automate Quantum Solar Panels using Autocrafters, Electric Furnace, Grinder and Compressor from TechReborn in combination with Vanilla Hoppers.

**Steps to Reproduce**
I have not figured out the exact reason, but here is what I think could trigger the bug.
- Build a system that crafts an Advanced Machine Frame from ingot-ingredients
- Configure Tech Reborn Machines to input/ouput

**Screenshots**
![2023-12-17_02 03 49](https://github.com/TechReborn/TechReborn/assets/63680413/cbe2054b-a539-4838-abe2-2ad7bd94dbed)
(I replaced an autocrafter with the crafting table. This seems to have fixed crashing)

**Environment (please complete the following information with the version):**
 - Minecraft: TechReborn-1.12.2-2.20.12.937-universal.jar
 - Mod Loader: Forge

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[crash.log](https://mclo.gs/mc0z5Gk)

**Additional context**
The bug is not reproducible on first attempt but it happens often. Breaking crafters or hoppers around them seems to fix the bug. The server only crashes a while after joining.

[This repository](https://gitlab.com/torbeneims-minecraft/tt-island/-/commit/ef19abdbab23d9135250ddfdffa05213d79b790e) includes the latest world and all files to start the server using docker-compose.

**Comment by xanthian** [comment]
1.12 is long dead. no longer supported.
dont expect an update

**Comment by drcrazy** [comment]
It is something in Draconic Evolution that breaks autocrafting table.
