### ISSUE TITLE
About player detector

### ISSUE THREAD

**Issue by Rcc-xyz** [TechReborn/TechReborn#3206]
It should be like a redstone block, rather than strong charging in all directions.
This can make many situations difficult to handle

 Minecraft: 1.20.1
 Mod Loader: fabric
![7J726NNB%@ZRA6S KS8}{KS_tmb](https://github.com/TechReborn/TechReborn/assets/76724065/be8d1a6a-a028-498e-bebc-cdfe909b21b8)

**Comment by drcrazy** [comment]
Should behave similar to daylight detector now.

![image](https://github.com/TechReborn/TechReborn/assets/1382352/2fb35c01-0e04-45a7-a229-0752eb90d9e5)
