### ISSUE TITLE
Quantum chestplate flight abillity remains on player even after unequipped

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [TechReborn/TechReborn#3208]
**Describe the bug**
After unequipped quantum chestplate, player still possesses creative flight ability.

**Steps to Reproduce**
- First Step: equip quantum chestplate in survival mode.
- Second Step: unequip it, then double tap spacebar to fly.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric
 - TechReborn: 5.4.0
 - RebornCore: 5.4.0
 - Using Modpack: StaTech Industry 1.1.11

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
Nothing unusual in logs.

**Additional context**
The flight ability is removed after switching gamemode to creative then to survival.

**Comment by drcrazy** [comment]
Can't reproduce in dev env with TR only.
