### ISSUE TITLE
ruby helmet crashes game

### ISSUE THREAD

**Issue by Deloptin** [TechReborn/TechReborn#3213]
Equipping the ruby helmet and viewing it in any way (F5, Inventory, etc.) crashes my game. It could happen with other armour pieces, but I haven't tested it due to needing to restart my game each time

Equip ruby helmet
Open inventory

1.19.2 Quilt Loader

[crash log.txt](https://github.com/TechReborn/TechReborn/files/14094453/crash-2024-01-30_07.36.51-client.txt)

It's on a multiplayer server if that matters

**Comment by Deloptin** [comment]
ok i did some digging and it's with all TR armour, and it's an incompatibility with requiem
works fine when requiem is disabled

**Comment by modmuss50** [comment]
We only support fabric
