### ISSUE TITLE
Copying machine config does not work

### ISSUE THREAD

**Issue by Pib-k** [TechReborn/TechReborn#3220]
When opening a storage unit, a basic storage unit for example, u have the options to configure slots. At the bottom it says u can use ctrl + v to copy the slot config. However I don't think it actually copies it.

When I press ctrl + v in the same 'enviroment' it says: "Clipboard contents isn't a valid slot configuration"

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: fabric
 - TR: 5.8.7

**Comment by modmuss50** [comment]
This appears to be working as expect in 1.21.
