### ISSUE TITLE
What's the intended overclocker limit? (Speed increase limit is defined twice with different values)

### ISSUE THREAD

**Issue by KonSola5** [TechReborn/TechReborn#3223]
**Describe the bug**
On default configs:
Each Overclocker reduces the ticks needed (a.k.a. the "speed multiplier") by 0.25.
So according to this code in `MachineBaseBlockEntity`:
https://github.com/TechReborn/TechReborn/blob/6622285fe978c7a73e2d01e7c3977d266b202596/RebornCore/src/main/java/reborncore/common/blockentity/MachineBaseBlockEntity.java#L354-L361
the speed cap gets clamped to 0.99 with 4 overclockers.

However, when it comes to calculating the final amount of ticks needed for recipe, the value gets clamped AGAIN by the `getSpeedMultiplier` in `RecipeCrafter`:
https://github.com/TechReborn/TechReborn/blob/6622285fe978c7a73e2d01e7c3977d266b202596/RebornCore/src/main/java/reborncore/common/recipes/RecipeCrafter.java#L397-L400
to 0.975.

What's the intended speed cap then? 99% or 97.5%?

**Steps to Reproduce**
1. Open Minecraft in debug mode
2. Place a machine and insert 4 Overclocker Upgrades into it
3. Observe that the needed ticks for a recipe that takes 5000 ticks is 125 ticks.
4. Use a breakpoint on the `getSpeedMultiplier` in `RecipeCrafter` - that's a point between two clamps.

**Environment (please complete the following information with the version):**
 - Minecraft: Any (present on 1.20.4)
 - Mod Loader: Fabric

**Logs**
No logs, since it's an issue with the coding.

**Additional context**
I was trying to find out, why the top machine speed is 97.5% instead of 99%.
After some debugging, finally found out that the value is clamped twice.

**Comment by KonSola5** [comment]
Guess it's 99% then.

Please also reflect this in the overclocker tooltip helper.

**Comment by drcrazy** [comment]
Yepp, 99%
