### ISSUE TITLE
Jackhammer skipped blocks are hardcoded for some blocks

### ISSUE THREAD

**Issue by KonSola5** [TechReborn/TechReborn#3226]
**Describe the bug**
Blocks skipped by Jackhammer are:
- Air,
- Liquids,
- `c:ores`,
- **Obsidian and Crying Obsidian**
- **Ancient Debris**
- **Redstone Ore**

https://github.com/TechReborn/TechReborn/blob/6622285fe978c7a73e2d01e7c3977d266b202596/src/main/java/techreborn/utils/ToolsUtil.java#L174-L191
That means that if someone would like additional "hard" blocks to be skipped, one would need to add their block to `c:ores`, which is quite unintuitive.

Can be fixed by creating a tag that contains all the blocks that Jackhammer skips, and checking whether the block is tagged as such.

**Steps to Reproduce**
Coding issue.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: Any (though 1.19.3 brought an improvement replacing the `instanceof` check for `OreBlock`s with a `c:ores` tag check)
 - Mod Loader: Fabric

**Logs**
None

**Additional context**

**Comment by KonSola5** [comment]
Cool, although here's a thing:
Sands and Sandstones should totally have `c` or `minecraft` tags.
(To make it compatible out-of-the-box with other mods that add Sands/Sandstones, such as Ad Astra).
https://github.com/TechReborn/TechReborn/blob/d1f7f2a69553fe9fce640ebea827814a80fd75c0/src/datagen/groovy/techreborn/datagen/tags/TRBlockTagProvider.groovy#L61-L64

**Comment by drcrazy** [comment]
#minecraft:sand contains suspicious sand also. Which shouldn't be broken by Jackhammer, IMHO.

![image](https://github.com/TechReborn/TechReborn/assets/1382352/c912f88a-2ccc-4d77-8df4-65af0dbf7d57)

**Comment by KonSola5** [comment]
Though breaking of Suspicious Sand with the Jackhammer can be fine (it's a block which you need to be careful to not destroy it by accident)

And Jackhammer skipping it kinda kills the "carefulness" part.

TR is not usually played alone, together with vanilla Minecraft only, it's usually played in big packs.

**Comment by KonSola5** [comment]
Sand tags:
![sand](https://github.com/TechReborn/TechReborn/assets/125081901/b957eb1e-2ae8-4d85-be56-6d78d8147385)
Suspicious Sand Tags:
![sus_sand](https://github.com/TechReborn/TechReborn/assets/125081901/d151458e-014c-4d92-ad1f-94bf9d49fd3a)

Aka `c:sand` can be used there.

**Comment by drcrazy** [comment]
This will perfectly work until somebody will decide to add #minecraft:sand to #c:sand.  
Modpack author can add some modded sand to #techreborn:jackhammer_mineable

**Comment by KonSola5** [comment]
The tag is there for a reason - adding `#minecraft:sand` to `#c:sand` when there are two separate tags would be pointless, with `#c:sand` not including Suspicious Sand on purpose.

EDIT: After glancing onto the Fabric repository, `c:sand` is not a default convention tag.

Alternative idea: A "negative" tag, containing blocks **skipped** by Jackhammer, evaluated before the mineable tag.
