### ISSUE TITLE
Fuels accepted in various fluid fuel powered generators are hardcoded

### ISSUE THREAD

**Issue by KonSola5** [TechReborn/TechReborn#3227]
**Describe the bug**
Fuels accepted in various fluid fuel powered generators are **hardcoded**.

That means that a pack would have to either make a custom mod with an `@Inject` (for adding) or `@Overwrite` (for removing recipes) mixin into the class registering the fluid generator recipes, or the pack would have to perform weird fluid conversion recipes.

https://github.com/TechReborn/TechReborn/blob/d1f7f2a69553fe9fce640ebea827814a80fd75c0/src/main/java/techreborn/init/FluidGeneratorRecipes.java#L35-L58

**Steps to Reproduce**
Coding issue.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: Any (present on 1.20.4)
 - Mod Loader: Fabric

**Logs**
None, since it's a coding issue.

**Additional context**
Fusion Reactor recipes are already compatible with datapacks, and that's the only generator in the whole mod which inputs can be configured with a datapack.

**Comment by modmuss50** [comment]
Done, fluids are now data driven recipes, with the following format:

```json
{
  "type": "techreborn:diesel_generator",
  "fluid": "techreborn:nitrofuel",
  "power": 24
}
```

`type` can be one of:
- `techreborn:thermal_generator`
- `techreborn:gas_generator`
- `techreborn:diesel_generator`
- `techreborn:semi_fluid_generator`
- `techreborn:plasma_generator`
