### ISSUE TITLE
No recipe for Netherite Nugget -> Netherite Ingot

### ISSUE THREAD

**Issue by AlisonHuang777** [TechReborn/TechReborn#3228]
**Describe the bug**
Described in title.

**Steps to Reproduce**
N/A

**Screenshots**
N/A

**Environment:**
 - Minecraft: 1.20.1
 - Mod Loader: Forge, using Connector
 - Playing Prominence II Classic Modpack v2.5.5, with modifications

**Logs**
N/A

**Additional context**
Also there is an item called "Template Template" in the game, and it seems that it does not have any usage, neither can I found it on the official wiki.

**Comment by KonSola5** [comment]
Does the modlist contain REI?
Tech Reborn annoyingly supports **only** REI.

Netherite Nugget -> Ingot recipe is made in the Implosion Compressor.
Template Template is also made in a TR machine.

Official wiki is outdated, and stopped being updated post 1.17, it seems like.

**Comment by AlisonHuang777** [comment]
>Does the modlist contain REI?

No, the modpack I'm playing does not have REI, it uses EMI instead.

>Netherite Nugget -> Ingot recipe is made in the Implosion Compressor.

I'll be appreciated if you can send a screenshot of the recipe viewed with REI, as you mentioned.

>Template Template is also made in a TR machine.

I'm not asking for the recipe of that, I'm asking what is it used for.

**Comment by KonSola5** [comment]
https://modrinth.com/mod/extra-mod-integrations

This mod adds TR integration with EMI. Hopefully it works with Connector.
