### ISSUE TITLE
Fusion Reactor not transfering energy

### ISSUE THREAD

**Issue by Pib-k** [TechReborn/TechReborn#3229]
**Describe the bug** (I dont know if this is a bug)
Fusion Reactor generates energy when 'crafting'. During this time you can transfer energy to batteries or other machines. Once the crafting is finished, you can no longer pull energy out of the Fusion Reactor even if there is energy stored in the Fusion reactor.

**Steps to Reproduce**
- First Step: Build Fusion Reactor
- Second Step: put a batterybox or something similar on top
- Third Step: Add power to Fusion reactor
- Fourth Step: 'Craft'
- Fifth Step: See the batterybox and fusion reactor (partially) fill up with energy
- Sixth Step: When is finished, remove batterybox and place a new one
- Seventh Step: see that the batterybox is not filling up even though there is energy in the fusion reactor

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.4
 - Mod Loader: fabric

**Possible Solution**
Code sides of fusion reactor for putting energy into the fusion reactor and top and bottom for pulling energy out of reactor

**Comment by drcrazy** [comment]
Works as intended
https://wiki.techreborn.ovh/doku.php?id=energy:generators:fusion_control_computer
