### ISSUE TITLE
Cannot access inventory of any TR machines with any item/fluid transportation device from any mod, except for vanilla ones

### ISSUE THREAD

**Issue by AlisonHuang777** [TechReborn/TechReborn#3230]
**Describe the bug**
E.g., Create's Funnel cannot insert of extract items from TR machines. Neither does AE2's any device.

**Steps to Reproduce**
Take AE2 as an example:
1. Attach a Storage Bus to any TR machine.
2. The Bus does not detect any inventory, and says "not attached" in its GUI.

**Screenshots**
None.

**Environment:**
 - Minecraft 1.20.1
 - Mod Loader: Forge, using Connector
 - Playing Prominence II Classic modpack, with modifications

**Logs**
N/A

**Additional context**
Is this a Tech Reborn issue, or a general problem for any Fabric mod using Connector to run on Forge?

**Comment by Technici4n** [comment]
> Forge, using Connector

Connector is not supported for exactly these reasons.
