### ISSUE TITLE
1.12.2 port of TecnReborn has unsmeltable ores and wood

### ISSUE THREAD

**Issue by PiotrBarcz** [TechReborn/TechReborn#3232]
**Describe the bug**
Galena ore, Bauxite ore, Iridium Ore as well as Rubber Wood will NOT smelt in ANY furnace _including TechReborn furnaces_. I've ground the ores to dust and tried to smelt them that way but that doesn't work either. Rubber wood also has no way to be smelted into charcoal through any other furnace or method (including the charcoal pile which straight up doesn't work from Forestry)

**Steps to Reproduce**
Take Galena Ore, Bauxite Ore, Iridium Ore etc. and put it in a furnace, it won't smelt. Put it in a crusher from any other mod or TechReborn and make the ore into dust, it still won't smelt.

**Environment:**
 - Minecraft: 1.12.2 in the Tekkit Classic modpack which also includes Actually Additions, BuildCraft and other mods but none of which affect the ores and how they smelt.
 - Mod Loader: Forge

It seems I'm not the only one who's had this issue, I saw a reddit post also saying that Galena Ore in particular is impossible to smelt into anything.

**Comment by drcrazy** [comment]
It's is not intended to smelt it. Galena will produce both Silver and Lead. Thus it is not clear what should be a smeltable product in this case.
