### ISSUE TITLE
Fluid Tank

### ISSUE THREAD

**Issue by monochromem1nd** [TechReborn/TechReborn#3233]
I'm not sure it needed to be here but:
When creating an addon for TR, it was discovered that only one fluid tank is supported in a mechanism. It would be nice to have some inventory for fluid tanks to have 1+ in one mechanism at a time.

**Environment:**
- Minecraft: 1.20.1
- Mod Loader: fabric
- TR ver: 5.8.7

**Comment by modmuss50** [comment]
This is unlikely something I am going to do, I would be happy to accept a PR to make this possible though.
