### ISSUE TITLE
Хлорит

### ISSUE THREAD

**Issue by Apple025** [TechReborn/TechReborn#3242]
Нет применения к предмету
Для капсулы с хлоритом нету никаких крафтов и она нигде не используется
Версия 1.20.1 последняя

**Comment by Ayutac** [comment]
Google Translate: No application to item
There are no crafts for the chlorite capsule and it is not used anywhere
Version 1.20.1 latest

**Comment by modmuss50** [comment]
Items such as this can be used by pack devs to add their own recipes. Not a bug.
