### ISSUE TITLE
[1.20.1] Keybinds not present at all

### ISSUE THREAD

**Issue by krzysztofKKW** [TechReborn/TechReborn#3248]
As far as I understand the code, there should be a keybind to toggle the night vision on power armor in "Tech Reborn" category in the keybinds menu. The category doesn't exist, and the default binds don't work, not allowing me to turn off the night vision of the nano helmet, nor turn it on on the quantum one.

My game version:
 - Minecraft: 1.20.1
 - Mod Loader: Fabric 0.15.7

There are no errors or warnings reported in the minecraft log from this mod.

**Comment by modmuss50** [comment]
1.20.1 is no longer supported, sorry.
