### ISSUE TITLE
Crash on 1.8.9 with Biomes O' Plenty

### ISSUE THREAD

**Issue by DoughnutDev** [TechReborn/TechReborn#325]
Crash Report: http://pastebin.com/82Ku3HS2

**Comment by gigabit101** [comment]
http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/1.8.9-3.0.0.1623/BiomesOPlenty-1.8.9-3.0.0.1623-changelog.txt
