### ISSUE TITLE
Bronze tools (+more mybe?) recipe is broken, requiring only 2 sticks to make all tools

### ISSUE THREAD

**Issue by Atomiiku** [TechReborn/TechReborn#3252]
**Describe the bug**
 all the tools' ingots arent in the recipes and i get an axe (or the other tools with polymorph) with 2 sticks in the crafting table

**Steps to Reproduce**
- First Step: crafting table
- Second Step: 2sticks middle down

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: fabric 15.11

**Additional context**
https://paste.ee/p/pEGs3
Log from Multi MC to show what mods i have in my instance

**Comment by modmuss50** [comment]
1.19.2 is no longer supported. Sorry
