### ISSUE TITLE
Crash Upon using the Industrial Electrolyzer

### ISSUE THREAD

**Issue by AndreCelso** [TechReborn/TechReborn#3257]
**The Game Crashes upon using the Industrial Electrolyzer**
As soon as you put for example clay dust and the empty cells on the Industrial Electrolyzer the game crashes

**Steps to Reproduce**
- First Step: Place the Industrial Electrolyzer in the World, and power it
- Second Step: Insert the ingredients

**Environment**
 - Minecraft: [1.21] (Both Server and Client)
 - Mod Loader: [Fabric]

**Logs**
https://mclo.gs/CNVrbiC

**Comment by Tursiops-G** [comment]
Same here.  Electrolyzer Ticking Block Entity crash, resulting in a Bricked World.

https://mclo.gs/m7gy9rv

**Comment by modmuss50** [comment]
Fixed: https://github.com/TechReborn/TechReborn/commit/ab8474cdaf35857add876d8185d3441cf3c6dd30
