### ISSUE TITLE
Silicon plate crafting recipe and documentation missing

### ISSUE THREAD

**Issue by Cragsand** [TechReborn/TechReborn#3258]
**Describe the bug**
There is no recipe or indication on how to craft "Silicon Plate"

**Steps to Reproduce**
- Lookup silicon plate in REI
- Be confused

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: Fabric / Forge with Synytra connector

**Logs**
No log.

**Additional context**
The wiki also lacks information https://wiki.techreborn.ovh/doku.php?id=items:plate:silicon_plate

**Comment by modmuss50** [comment]
The wiki contains the recipe, 2x silicon fluid cells in a blast furnace.
