### ISSUE TITLE
Crash on 1.8.9 Server

### ISSUE THREAD

**Issue by kwpugh** [TechReborn/TechReborn#326]
See pastern crash report:

http://pastebin.com/raw/f7g6fwWm

**Comment by modmuss50** [comment]
Have you got reborn core installed?

**Comment by kwpugh** [comment]
Yes.   As shown in my crash report:

reborncore{1.3.0.6} [RebornCore] (RebornCore-1.8.9-1.3.0.6-universal.jar) 

Is this the correct version of the RebornCore?

**Comment by modmuss50** [comment]
I cannot seam to find out what is wrong with this one, very strange. It also happens in dev

**Comment by cauliflower69** [comment]
We had the same crash on addition of your mod

**Comment by covers1624** [comment]
Does reborn core still use the cofh stripper?

**Comment by modmuss50** [comment]
I don't think so, but that would explain it. I will have a look later.

**Comment by covers1624** [comment]
the reason i say this is that sometimes the default classwriter has issues with super classes ans will sometimes break in such a way that a class will become a super class for itself, if this is the case i have a class writer that fixes it.

**Comment by modmuss50** [comment]
That might be useful, but it still happens in dev. It's strange how it just broke.

**Comment by covers1624** [comment]
i had a similar issue and chicken bones pointed out that it was the class writer, ill take a look for you when i get home

**Comment by modmuss50** [comment]
ok thanks

**Comment by modmuss50** [comment]
After a lot of debuging I found the issue, https://github.com/TechReborn/RebornCore/commit/d20885e142c7319c94ffea0acb5bfbe41f65d587

https://i.imgur.com/xL9ntmN.png Why the fuck does MC do this??
