### ISSUE TITLE
Nano package causing collapse

### ISSUE THREAD

**Issue by tianyeorg** [TechReborn/TechReborn#3260]
Wearing any nano equipment other than a nano helmet during survival can cause the world to save and crash, and crash logs suggest that the required source code may be missing

**Comment by modmuss50** [comment]
Hi, sorry about that. Please can you provide the crash logs?

**Comment by tianyeorg** [comment]
[minecraft-exported-crash-info-2024-06-24T16-48-45.zip](https://github.com/user-attachments/files/15952337/minecraft-exported-crash-info-2024-06-24T16-48-45.zip)
Of course, this is the log file I exported, and there are no warning words in the game log. The hmcl.log indicates, "Your game may be missing a certain mod, or some mod files may be incomplete, or the mod may not match the game version. You may need to reinstall the game and mod, or request help from others." It also mentions two mods, "Dynamic FPS" and "Sodium  Extra" (sodium-extra). "After I deleted these two mods, the problem of wearing armor in survival mode causing crashes still remains unresolved.".

**Comment by tianyeorg** [comment]
After my testing, it conflicts with the ArmorChroma mod, but for some reason, other armor in the mod will not cause crashes, except for the nano armor that will crash

**Comment by tianyeorg** [comment]
Even many armor and armorchroma are linkage, for example, the armor bars of quantum armor will change color, but nano armor cannot:（

**Comment by modmuss50** [comment]
The crash is from armorchroma, and maybe related to https://github.com/TechReborn/TechReborn/issues/3186
