### ISSUE TITLE
Капсулы не отображают своё содержимое

### ISSUE THREAD

**Issue by unidok** [TechReborn/TechReborn#3266]
**Describe the bug**
Капсулы должны отображать то, что в них налито (как в industrial craft 2)

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 - Mod Loader: [e.g. forge, fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by modmuss50** [comment]
This is likely caused by you using a mod such as Sodium or Optifine that disables the renderer API.
