### ISSUE TITLE
Don't give the ores after mining

### ISSUE THREAD

**Issue by Coreglitchboy** [TechReborn/TechReborn#3267]
This happened while I was playing in a mod pack called Fabric Tricky Trials that has the version 5.11.0 of tech reborn. I mined any ore with an iron pickaxe or lower and they didn't give me anything but experience. So, I don't know if is a problem of the mod or of the mod pack,  that is why I'm complaining here, because I don't know and I saw that you published new version, so maybe in that version there is an error that makes that happen.

**Comment by modmuss50** [comment]
Update techreborn, this was fixed ages ago.
