### ISSUE TITLE
Server Crash - TechReborn-1.8.9-0.7.8.35

### ISSUE THREAD

**Issue by cauliflower69** [TechReborn/TechReborn#327]
http://pastebin.com/51j3tsLT

**Comment by modmuss50** [comment]
Fix is coming very soon

**Comment by cauliflower69** [comment]
Thanks

**Comment by modmuss50** [comment]
This will be on curse in about 10 mins - Sorry

**Comment by cauliflower69** [comment]
No need to apologies, thanks for a quick fix

**Comment by modmuss50** [comment]
I should of tested it, I fixed one crash.

**Comment by modmuss50** [comment]
And its up on curse, Ive taken the last build down.

**Comment by cauliflower69** [comment]
Thanks I'll test it now

**Comment by modmuss50** [comment]
wait, it got rejected by curse

**Comment by modmuss50** [comment]
ok, its live, not sure why they rejected it the first time.

**Comment by cauliflower69** [comment]
It booted!

**Comment by modmuss50** [comment]
have fun :+1:
