### ISSUE TITLE
Cell/Liquids will not render

### ISSUE THREAD

**Issue by spartan0430** [TechReborn/TechReborn#3271]
Empty cells, or any cells with a tech reborn liquid do not render at all leaving a clear space in its place.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.21 fabric w sodium/indium/iris

**Comment by monochromem1nd** [comment]
Modmuss answer in a similar issue:
> This is likely caused by you using a mod such as Sodium or Optifine that disables the renderer API.

**Comment by spartan0430** [comment]
Is there a fix for this or no?

**Comment by modmuss50** [comment]
Try using: https://www.curseforge.com/minecraft/mc-mods/indium

**Comment by spartan0430** [comment]
Indium does not rectify the issue while using sodium. Any other recommendations would be great if any. On Jul 13, 2024, at 04:39, modmuss ***@***.***> wrote:﻿
Try using: https://www.curseforge.com/minecraft/mc-mods/indium
