### ISSUE TITLE
Keybind `P` breaks with specific mods present.

### ISSUE THREAD

**Issue by Ampflower** [TechReborn/TechReborn#3278]
## Describe the bug
The keybind, `P` no longer functions when Tech Reborn is accompanied by other mods.

It is noted that on the last retry on combination C, I have managed to get it to act as if `P` was permanently held down by holding `P` whilst entering the world. Same applies to A.

A common with combinations B & C seems to largely be with Jade and Nostalgic Tweaks, however not universally as A does not contain either.

## Steps to Reproduce
- Add one of the mod combinations noted below.
- Set a keybind (`forward` is opted for here) to `P`.
  - Why `P`, I do not know.
- Note that the bound action does nothing when in world.
- Hold `P` while joining a world
- Note that the action it's bound to acts as if it was permanently held down after, even if you let go.
  - Seems to only apply to movement keys. The inventory key still no-ops.

## Screenshots
N/A, you can't exactly screenshot pressing a key and nothing happening.

## Environment (please complete the following information with the version):
 - Minecraft: 1.21
 - Mod Loader: Fabric 0.15.11
 - Fabric API: 0.100.7+1.21
 - Reborn Core 5.11.9
 - Tech Reborn 5.11.9
 
### One of:
 - A: Xaero's Minimap 24.2.1.
   - Note: Xaero's World Map does not cause the bug.
 - B: This mod combination of (yes, all 4 are required):
   - Architectury API 13.0.4
   - Jade 15.1.3+fabric OR 15.1.4+fabric
   - MidnightControls 1.9.7+1.21
   - Nostalgic Tweaks 2.0.0-beta.900
 - C: This mod combination of (yes, all 5 are required):
   - Architectury API 13.0.4
   - Iris 1.7.3+mc1.21
   - Jade 15.1.4+fabric
   - Nostalgic Tweaks 2.0.0-beta.900
   - Sodium 0.5.11+mc1.21

## Logs
(nothing really seemingly of interest in here but done for the sake of completeness)
- Mod combination A: https://mclo.gs/oTYNVYt
- Mod combination B: https://mclo.gs/3gEqPdi
- Mod combination C: https://mclo.gs/zUkYx4p

**Comment by Ampflower** [comment]
It is notable that CompactStorage ends up breaking in a similar manner, this time with right+shift and different incompatible mods.
Possible bug in Fabric API or a bad stray mixin in the mix?

**Comment by drcrazy** [comment]
Looks like a common issue with conflicting keybinds. Please, unbind other keybindings.

**Comment by Ampflower** [comment]
I have, is the thing.
