### ISSUE TITLE
Is there a way of loading lava into the industrial grinder?

### ISSUE THREAD

**Issue by bentterp** [TechReborn/TechReborn#3279]
https://github.com/TechReborn/TechReborn/blob/77250663539e3938145256c0b40db470121a6159/src/datagen/groovy/techreborn/datagen/recipes/machine/industrial_grinder/IndustrialGrinderRecipesProvider.groovy#L902C4-L902C38

Neither lava buckets nor lava cells want to empty themselves into the fluid reservoir like water or mercury.

**Comment by drcrazy** [comment]
Lava cells and tank units works fine with Industrial Grinder

![image](https://github.com/user-attachments/assets/8a95b5c2-0466-4d55-9ad5-588d50feeb05)
