### ISSUE TITLE
[1.20.1] Quantum Helmet doesn't provide night vision

### ISSUE THREAD

**Issue by iiPythonx** [TechReborn/TechReborn#3280]
**Describe the bug**
Compared to the Nano Helmet (which DOES provide Night Vision), the quantum helmet doesn't provide Night Vision at all on my 1.20.1 fabric server, although the issue also happens in singleplayer.

**Steps to Reproduce**
- Equip a charged quantum helmet, observe that you don't get night vision
- Switch to a a charged nano helmet, observe that you get night vision correctly

**Screenshots**

https://github.com/user-attachments/assets/dc3965ac-3361-4cb6-bba0-02782ff7028b

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: fabric

**Logs**
https://paste.ee/p/85gq5

**Additional context**
If 1.20.1 isn't supported anymore, could somebody at least point me in the right direction for fixing the issue and rebuilding TR? I can't find any differences between the nano helmet and the quantum helmet in terms of adding the status effect.

**Comment by drcrazy** [comment]
Works fine in 1.21. 

This is how it is done: https://github.com/TechReborn/TechReborn/blob/1f5cba1c4a5bd6a006f5e5903084a2c0506050ef/src/main/java/techreborn/items/armor/QuantumSuitItem.java#L88
