### ISSUE TITLE
[1.20.1] QUANTUN/NANO ARMOR DONT GET REROLL IN TIERED

### ISSUE THREAD

**Issue by Luucyd** [TechReborn/TechReborn#3281]
**[1.20.1] QUANTUN/NANO ARMOR DONT GET REROLL IN TIEREDZ**
the quantun and the nano armor dont reroll in the anvil to get another rarity to the armor, but the drill and other tools can change the rarity in the anvil 

**Steps to Reproduce**
- First Step create the nano/quantun amor
- Second Step put the armor in the anvil to change the rarity with TieredZ mod and cant change

**Screenshots**
![Screenshot_1](https://github.com/user-attachments/assets/1a115990-2f74-4cca-9b93-02bdf2097b62)
![Screenshot_2](https://github.com/user-attachments/assets/db229b6d-5052-4b2d-ad5d-a381a814e173)

**Environment (please complete the following information with the version):**
 - Minecraft: [1.20.1]
 - Mod Loader: [fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by drcrazy** [comment]
Looks like TieredZ  should handle these cases
