### ISSUE TITLE
Grinder not grinding raw variants of resources?  (1.21)

### ISSUE THREAD

**Issue by pourgb** [TechReborn/TechReborn#3282]
I have just started playing Tech Reborn, just got my first pair of machines, the generator and the grinder, and weirdly my grinder won't grind any raw ores variants at all, resources like bauxite that drops ore is still grinded normally but any resource that drop "raw" pieces wont grind(lead, silver, iron, ...). I have tested in creative that the grinder still grinds iron ore, lead ore, ... but wont grind raw iron, raw lead, ...
Im currently playing on Fabric 1.21, mod version 5.11.9 (latest at the time of posting)
This has make the grinder kinda useless in survival early on, Is this some bug with the latest release only?

**Comment by pourgb** [comment]
Wait, my bad for not checking more clearly, but it seems that it grinds ore into raw ore, but isn't the grinder for early game, isn't it a bit unfair to make ore doubling available for players with access to silk touch?

**Comment by igamer609** [comment]
just get _silk touch_ (find a village 😎 its intended behaviour btw)

**Comment by maciejstepie** [comment]
> Make a grinder 
> Dig a hole 
> Find 3 diamonds 
> Diamonds in grinder to dust 
> Make a rockcutter 
> Profit

**Comment by igamer609** [comment]
> > Make a grinder
> > Dig a hole
> > Find 3 diamonds
> > Diamonds in grinder to dust
> > Make a rockcutter
> > Profit

fr

**Comment by maciejstepie** [comment]
> > > Make a grinder
> > > Dig a hole
> > > Find 3 diamonds
> > > Diamonds in grinder to dust
> > > Make a rockcutter
> > > Profit
> 
> fr

https://wiki.techreborn.ovh/doku.php?id=items:rock_cutter

**Comment by pourgb** [comment]
God dang
