### ISSUE TITLE
Auto-crafting with Infusion Crystal crashes server

### ISSUE THREAD

**Issue by matthewvines1** [TechReborn/TechReborn#3283]
**Describe the bug**
Using an autocrafter with an infusion crystal from mystical agriculture crashes the server.

**Steps to Reproduce**
- Make sure the crafter has power
- Put an infusion crystal in the middle of the crafter
- Put inferium essence above, below, left, and right of the crafter
- Make sure lock icon at the top right is unlocked
- Wait for the progress arrow to complete

**Screenshots**
![image](https://github.com/user-attachments/assets/623c57c4-355d-4351-8dc4-ca562aacc659)
In this screenshot, the lock icon is set to locked to prevent it from crashing. To make it crash, set it to unlocked.r

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: Fabric 0.15.11
 - Tech Reborn 5.8.7
 - Mystical Agriculture: Refabricated 1.20.1-3.0.2 

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: 
[latest.log](https://github.com/user-attachments/files/16404885/latest.log)
[crash-2024-07-28_13.29.33-server.txt](https://github.com/user-attachments/files/16404886/crash-2024-07-28_13.29.33-server.txt)

**Additional context**

**Comment by drcrazy** [comment]
Recipe reminder works fine with vanilla recipes. Please, re-open if issue will persist on 1.21.

![image](https://github.com/user-attachments/assets/111942e6-5aba-4f46-8e4e-30bf5753aba9)
