### ISSUE TITLE
Chemical reactor recipe variant for shroomlight takes 0.2s instead of 20s to complete

### ISSUE THREAD

**Issue by krumble1** [TechReborn/TechReborn#3284]
**Describe the bug**
The chemical reactor recipe for a shroomlight that uses 4x glowstone dust and 1x brown mushroom block takes 0.2 seconds to complete, while all other recipes for a shroomlight, including the one using a red mushroom block, take 20 seconds to complete.

**Steps to Reproduce**
View crafting recipe in your favorite "item information" mod, or place the above ingredients in a powered chemical reactor.

**Screenshots**
![0.2s with brown mushroom block](https://github.com/user-attachments/assets/c95bf185-29a2-4540-a4df-db8aee481bcb)
![20s with anything else](https://github.com/user-attachments/assets/62996a05-c2f3-4905-8021-289ba75ba247)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.21
 - Mod Loader: fabric

**Comment by Ayutac** [comment]
Good catch, must have been a typo of mine.
