### ISSUE TITLE
[Bug] 纳米剑在激活后伤害仍是 5 点/The nanosword still deals 5 damage when activated

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [TechReborn/TechReborn#3288]
**Describe the bug**

纳米剑在激活后伤害仍是 5 点/The nanosword still deals 5 damage when activated

**Steps to Reproduce**

1.Activate the Nano Sword

**Environment (please complete the following information with the version):**
 - Minecraft: 1.21
 - Mod Loader: Fabric Loader 0.15.11

**Logs**
haven't logs

**Comment by drcrazy** [comment]
Can't reproduce. 

![image](https://github.com/user-attachments/assets/7c3dc896-1992-4fbe-8a69-e2c06834e397)
