### ISSUE TITLE
Iron Furnace experience texture is missing in 5.11.0 and above

### ISSUE THREAD

**Issue by GuyFromTheInternet** [TechReborn/TechReborn#3289]
**Describe the bug**
The texture for the iron furnace experience is missing

**Steps to Reproduce**
Have tech reborn installed

**Screenshots**
![missing](https://github.com/user-attachments/assets/dd07921c-f589-4158-b22b-99d88be38a13)

**Environment**
 - Minecraft: [e.g. 1.21]
 - Mod Loader: [fabric]

**Comment by igamer609** [comment]
it also happens for me on 1.20.4, idk why, doesn't really affect gameplay but its a bit annoying
