### ISSUE TITLE
"FluidRenderHandlerRegistry.INSTANCE.get is explicitly @Nullable but TechReborn is not checking for null"

### ISSUE THREAD

**Issue by SubordinalBlue** [TechReborn/TechReborn#3290]
Title comes from Balm dev, in response to issue first filed there: https://github.com/TwelveIterationMods/Balm/issues/94

**Describe the bug**
In AoF7, render crash upon REI listing TR cell containing `balm-fabric:milk`.

**Steps to Reproduce**
- Run latest AoF7 (2.5.0)
- Open REI to, or search for, TR cells—specifically the one containing `balm-fabric:milk`.

**Environment (please complete the following information with the version):**
- MC 1.20.1
- Fabric 0.16

**Logs**
Log is included in issue on Balm linked at top of this report.

**Comment by Linguardium** [comment]
issue seen on 1.20.1 with Balm and Cooking For Blockheads (CfB enables milk fluid which does not have a Fluid Render Handler registered with FAPI).
Likely still an issue in 1.21 as it throws a NPE via Objects.requireNonNull on a `@Nullable` method return https://github.com/TechReborn/TechReborn/blob/d28bc8922dc79797b6288ead60a48d10d1847cd3/src/client/java/techreborn/client/render/BaseDynamicFluidBakedModel.java#L80

Instead, it might be worth it to use FluidVariantRenderHandler.getColor and getSprites

**Comment by NattoRiisa** [comment]
(little note here since this was last week)
Balm fixes their end by registering a render handler, though this seems to still crash
