### ISSUE TITLE
Solar panels not working above Nether ceiling

### ISSUE THREAD

**Issue by AshdoII** [TechReborn/TechReborn#3291]
**Describe the bug**
Solar panels not working above Nether ceiling

**Steps to Reproduce**
- get to the top of the bedrock layer of Nether 
- Place a  quuantom solar panel, open gui, show 'panel obstructed from sky'.

**Screenshots**
![2024-08-21 164929](https://github.com/user-attachments/assets/3cfa45e4-fc8b-4e0a-b68b-064c68255ebe)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: fabric 0.15.11
 - Mod Version 5.8.7
 - 
**Logs**
[latest.log](https://github.com/user-attachments/files/16689200/latest.log)

**Additional context**
Don't know it's a bug or it's intended to be so.

**Comment by AshdoII** [comment]
having the same issue in the end dimention

**Comment by drcrazy** [comment]
Minecraft thinks that sky is not visible in these cases.

**Comment by AshdoII** [comment]
> Minecraft thinks that sky is not visible in these cases.

So its considered a feature not a bug and won't be fixed?

**Comment by drcrazy** [comment]
It's neither feature nor bug. It's how Minecraft works. Solar panel calls minecraft function to check if sky is visible.
