### ISSUE TITLE
In fabric server, quantum leggings give 0.15 speed but slow than single server

### ISSUE THREAD

**Issue by thebestduhan** [TechReborn/TechReborn#3292]
**Describe the bug**
In fabric server and single server, quantum leggings give same 0.15 speed. but fabric server leggings are slow than single server leggings

**Steps to Reproduce**
- Connect to Fabric server
- Wear Activated Quantum leggins

**Screenshots**

https://github.com/user-attachments/assets/65383b5e-0602-43fd-91b1-73117645c6b9

**Environment (please complete the following information with the version):**
 - Minecraft: 1.21
 - Fabric loader 0.16.0

**Logs**

**Additional context**
plus, in fabric server, cannot working shift-right click to "set to active"

**Comment by drcrazy** [comment]
Can't reproduce in dev env. Maybe some other mods or server settings are preventing this.
