### ISSUE TITLE
Missing xp texture in Iron Furnace

### ISSUE THREAD

**Issue by jshipley** [TechReborn/TechReborn#3296]
**Describe the bug**
The menu screen for the Iron Furnace is showing a missing texture in the XP slot.

**Steps to Reproduce**
- Right click on an Iron Furnace, see the missing texture

**Screenshots**
![image](https://github.com/user-attachments/assets/d29e3fb1-52d4-43e3-a416-0b045333515e)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.21.1
 - Mod Loader: Fabric Loader v0.16.5
 - Mods installed: Fabric API v0.104.0+1.21.1, Reborn Core 5.11.10, Tech Reborn 5.11.0

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/LBUYbfaY

**Additional context**
N/A

**Comment by drcrazy** [comment]
Please, update to TR >= 5.11.11
