### ISSUE TITLE
Fishing station I/O

### ISSUE THREAD

**Issue by programaus** [TechReborn/TechReborn#3297]
Fishing station's NBT data is not considering any item input/output
(despite being "added" https://discord.com/channels/159382191292416000/368133674626973696/1270664099562520626 https://discord.com/channels/159382191292416000/368133674626973696/1270666226670108724 )
how it currently looks (horrifying):
![image](https://github.com/user-attachments/assets/f6cc4140-d095-4423-9be0-81a91a206102)
how it should look:
![image](https://github.com/user-attachments/assets/353cb41e-d903-4172-a228-458635423b9b)

**Comment by Thepigcat76** [comment]
maybe it was not added on your version, but only the latest

**Comment by programaus** [comment]
mb yeah ive forgot to close this after reading that they gave up on 1.20.1 updates (despite it being a really good version??)
