### ISSUE TITLE
Industrial Grinder isn't accepting other fluids

### ISSUE THREAD

**Issue by wHazem** [TechReborn/TechReborn#3306]
**Industrial Grinder Bug**
The Industrial Grinder is not accepting other fluids like Mercury or Sodium Persulfate; only water can be filled. I tried using a mercury bucket and an external tank, but it doesn't work.

**Screenshots**
![image](https://github.com/user-attachments/assets/c0bd2c57-e2e1-44cf-afd0-6975f10c38cb)

**Environment:**
 - Minecraft: 1.21.1
 - Mod Loader: fabric 0.105.0

**Comment by KillReallll** [comment]
I can't add water to the Industrial Grinder. Minecraft 1.21.1. TR 5.11.11. Fabric-API-0.106.0. Compressed air can be added if it is important. I haven't tried other liquids.
![Снимок экрана 2024-10-22 185933](https://github.com/user-attachments/assets/9d1b2f05-d9b0-4649-999b-5bf07b71b98a)
![Снимок экрана 2024-10-22 185942](https://github.com/user-attachments/assets/00524f5e-0651-4e1b-8396-694c75b53cb9)
