### ISSUE TITLE
[Feature Suggestion] Neoforge Support.

### ISSUE THREAD

**Issue by v3xed-v0id** [TechReborn/TechReborn#3307]
Hello everyone! i really like this mod, so i have to ask, is a neoforge version being planned? and if not, could one be planned?

I know that a forge version is not being planned (understandably so), but neoforge is different from forge, so i think it is a worthwhile question to ask and suggestion to make.

Thanks very much for reading, have a great rest of your day/night/whatever it is there, i hope this gets seen.

**Comment by modmuss50** [comment]
No, its not planned.
