### ISSUE TITLE
Should we stop supporting running without ic2?

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#332]
This is a question. The issue is that a lot of the missing recipe issues that are open are for when we are running without ic2. I though It might be a good idea to ignore them and close them. The mod would still run without ic2 just without recipes. If a pack maker wants to add them its up to them. 

Doing this would close:
#330
#316 
#315 
#182
#157 

I am thinking of going on a massive bug fixing spree before I run out of time in the next month or so.
Please leave your feedback.

CC: @BBoldt @gigabit101 @Mattabase

**Comment by wormzjl** [comment]
IMO, GT is only good as an addon for ic2
That's why I don't like gt5, it has gone too far :P

**Comment by modmuss50** [comment]
Exactally, I get loads of questions about why there is no reipces and its becuase its an ic2 addon. The reason I allowed it to load without ic2 was becuase pack makers like the machines to create custom recipes.

**Comment by gigabit101** [comment]
@themattabase is currently making a pack without ice me and him are going
to be making recipes in the pack what I will then put in techreborn

**Comment by modmuss50** [comment]
Ok, that sorts the issue then.

**Comment by BBoldt** [comment]
I think Tech Reborn has a lot of potential as a standalone mod, especially in 1.8.9.

Just add some warnings that there will be missing recipes without IC2.
