### ISSUE TITLE
Can't fill different fluids/gases on machines 

### ISSUE THREAD

**Issue by CorreaJose13** [TechReborn/TechReborn#3323]
If you use for example methane cell first in a gas turbine and then you wanna fill it with hydrogen it won't work. The same happens with semifluid generator and industrial grinder but i saw that apparently the last mentioned was fixed few days ago, anyway i can't test this until a release is made i guess.

 - Minecraft: 1.21.1
 - Mod Loader: Fabric
 - Tech Reborn: 5.11.11

**Comment by ZurrTum** [comment]
It has been fixed, you can download and test it in advance via actions
https://github.com/TechReborn/TechReborn/actions/runs/11676377182?pr=3315

**Comment by CorreaJose13** [comment]
According to ZurrTum it has been fixed in https://github.com/TechReborn/TechReborn/actions/runs/11676377182?pr=3315
