### ISSUE TITLE
LESU controller storage state bug

### ISSUE THREAD

**Issue by CorreaJose13** [TechReborn/TechReborn#3325]
Everytime i re-enter my world the LESU controller storage state changes, for example, if my setup has 200M E if i leave my world and enter again it changes to 96 M E.

 - Minecraft: 1.21.1
 - Mod Loader: Fabric

**Comment by ZurrTum** [comment]
@CorreaJose13 Hey, sorry it took a week to fix this bug.
Are you interested in testing it out in advance?
https://github.com/TechReborn/TechReborn/actions/runs/11916094993
