### ISSUE TITLE
Crash when accessing block inventorys

### ISSUE THREAD

**Issue by spotandjake** [TechReborn/TechReborn#3332]
**Describe the bug**
When I access any gui such as the iron furnace or generator the game crashes after a second or two.

**Steps to Reproduce**
Steps to reproduce the behaviour:
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
   - Minecraft 1.21.1 (I was also seeing this on 1.21)
 - Mod Loader: [e.g. forge, fabric]
   - Fabric + Lunar Client

**Logs**
https://pastebin.com/ukW1w009

**Additional context**
In the error log's I am not seeing any conflicts registered and the error itself seems to be coming from Tech Reborn

**Comment by ZurrTum** [comment]
Applying the #3333 patch can open normally
![game](https://github.com/user-attachments/assets/435899b6-cd78-4442-8bdb-039a79ed9858)

> TR has been incompatible with development workspaces using alternate runtime mappings

Lunar Client is not supported, **it can run on Fabric.**
More see #3333

**Comment by spotandjake** [comment]
Thanks for the reply, if you do not mind me asking to apply the patch to my local version I would imagine I would need to build that branch from source. Is there any documentation on that?

I assume / if I understood that pr correctly this issue would be coming from a non standard distribution of fabric being included with lunar client, causing the name mappings to not match. (I was assuming when lunar said it used fabric it meant the standard but I guess this assumption was wrong on my part).

**Comment by modmuss50** [comment]
This is not a TR issue, I dont know what they are doing to cause this. Please use the official fabric installer on one of the supported launchers.

**Comment by sylv256** [comment]
The problem is the code. Whenever `field_29183` gets mapped in Yarn, TR will break. If you used a less brittle solution, there wouldn't be any weird breakages. Offending code is here:
https://github.com/TechReborn/TechReborn/blob/a337be94d9d296f94600aad6671756f78db2d1f2/RebornCore/src/main/java/reborncore/common/screen/ServerPlayerEntityScreenHandlerHelper.java#L37

**Comment by modmuss50** [comment]
`field_29183` is a syntentic field in an anonymous class, it will NEVER have a name other than `field_29183`. Mappings should never change this, if they do they are broken.

**Comment by sylv256** [comment]
Regardless, this is an odd choice.

**Comment by modmuss50** [comment]
Im not going to argue this anymore, fabric guarantees that this is always named `field_29183. Why should I go out of my way to fix another mod loaders problem? If you use a loader that cannot make this guarentee then its not compatible with Fabric mods.
