### ISSUE TITLE
Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [TechReborn/TechReborn#3365]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Tech Reborn mod was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks. It would be nice if such a cool mod could be downloaded from the second most popular Minecraft modding site.

**Comment by Ayutac** [comment]
Sorry pal, https://github.com/TechReborn/TechReborn/issues/2679
