### ISSUE TITLE
Many ores don't render correctly in the inventory anymore

### ISSUE THREAD

**Issue by The-Fireplace** [TechReborn/TechReborn#337]
Many ores and some other blocks from this mod no longer render correctly in the inventory with the latest version of the mod.

**Comment by MrBretze** [comment]
@modmuss50 What do you not use the vanilla model render ?

**Comment by modmuss50** [comment]
Because why not? No Jsons, more bugs.

**Comment by MrBretze** [comment]
I do not bug for my mod
