### ISSUE TITLE
Final 1.7 requests?

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#338]
Commits to merge:

- https://github.com/TechReborn/TechReborn/commit/b3bec47b11e7b4d80e356e84cb7fce7b7d1f6a1f

- https://github.com/TechReborn/TechReborn/commit/0d35ecb70fddb8d43f4524e8ec0946fe807485ce

Things to fix:

- #329

Comment on this to get the last things you need then 1.7 will be done with.

**Comment by gigabit101** [comment]
Its mostly recipe stuff just add recipes for anything that is uncraftable with ic2 installed and the close 1.7.10 unless a game breaking bug appears

**Comment by wormzjl** [comment]
This
https://github.com/TechReborn/TechReborn/issues/236

**Comment by modmuss50** [comment]
All of the above requests are done.

**Comment by wormzjl** [comment]
And I forgot this one since it's not opened by myself 
https://github.com/TechReborn/TechReborn/issues/217

**Comment by modmuss50** [comment]
and that's done

**Comment by wormzjl** [comment]
awsome

**Comment by 12cool725** [comment]
Is there a way to prevent changing recipes from IC2 or other mods?

**Comment by modmuss50** [comment]
Yes, it should all be in the config

**Comment by 12cool725** [comment]
Where exactly? I can't, for example, find the IC2 recipe for Iridium Reinforced Plate. Also my config looks like this:

[TechReborn.zip](https://github.com/TechReborn/TechReborn/files/143355/TechReborn.zip)

**Comment by modmuss50** [comment]
ok, I will take a look at this. You might be right.

**Comment by 12cool725** [comment]
There are other bugs/minor enhancements that might need fixing/application. E.g. 
![2016-02-25_10 30 55](https://cloud.githubusercontent.com/assets/7034311/13324180/8ef77f50-dbaa-11e5-98e5-26201c4f25eb.png)
I can't look up Assembly Machine recipes.
(Will edit this post w/further findings)

**Comment by gigabit101** [comment]
Um the last 1.7 build is already out

**Comment by modmuss50** [comment]
If its a major bug it can be fixed. But small things wont be. Feel free to report them to be fixed in 1.8
