### ISSUE TITLE
Rubber trees sometimes spawn inside other trees

### ISSUE THREAD

**Issue by ProfessorProspector** [TechReborn/TechReborn#343]
![2016-02-20_20 07 56](https://cloud.githubusercontent.com/assets/6166773/13200831/0ba20048-d80e-11e5-8c75-7914775089d9.png)
![2016-02-20_20 07 52](https://cloud.githubusercontent.com/assets/6166773/13200832/0ba593b6-d80e-11e5-83d9-2892cf0eede2.png)

**Comment by modmuss50** [comment]
Im going to close this as its the same issue as the other two rubber tree issues
