### ISSUE TITLE
Black hud...

### ISSUE THREAD

**Issue by Pilad** [TechReborn/TechReborn#347]
Any hud is black....
http://pixs.ru/showimage/2016022117_5063928_20778439.png

**Comment by Pilad** [comment]
Please add support modtweaker.

**Comment by modmuss50** [comment]
There is full minetweaker support. See here: http://blamejared.com/modtweaker/ Thanks for reporting that issue. It wont get fixed in 1.7, but It will get fixed for when you update to 1.8

**Comment by Pilad** [comment]
Hmm... Version minecraft 1.7.10 and last build TechReborn-1.7.10-0.7.12.1089-universal, and hud is black (((

**Comment by modmuss50** [comment]
Yes, I will fix that, but we are no longer working on the 1.7 version

**Comment by Pilad** [comment]
I am waiting for fix )))
