### ISSUE TITLE
the jenkins broke

### ISSUE THREAD

**Issue by ProfessorProspector** [TechReborn/TechReborn#357]
;(

its been trying to build for hours

**Comment by ProfessorProspector** [comment]
I think it has something  to do with the CraftTweaker api or something not being downloaded properly. Gradle keeps crashing when I try to setup a workspace, and it is mentioning CraftTweaker.

**Comment by modmuss50** [comment]
The website that gradle uses to download crafttweaker is down. Not a lot I can do about it. Ive tweeted him about it.

**Comment by ProfessorProspector** [comment]
Yeah I assumed as much. Hopefully it'll be up soon. Broke my workspace and havery no way of getting another right now.

**Comment by modmuss50** [comment]
It should be fixed, I am also working on improving the jenkins to be quicker and more stable. Maven uploads are currently broken, but should be fixed soon. But you can setup your workspace

**Comment by ProfessorProspector** [comment]
Gonna go ahead and close this. All appears to be well now?

**Comment by modmuss50** [comment]
Yes, im having some issues with my website that im trying to fix. The jenkins and gradle is uneffected. But I am restarting nginx a lot atm.

**Comment by modmuss50** [comment]
Ive tracked down the issue, so it should be stable agian now. And jenkins builds are 2x faster

**Comment by ProfessorProspector** [comment]
Yaaaay
