### ISSUE TITLE
JEI Alloy Smelter is not showing stack amount required 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#359]
Eg this recipe requires 3 copper and 1 tin 
http://puu.sh/nkUaT/b383d2695b.jpg

**Comment by gigabit101** [comment]
@mezz can you take a look at this ?

**Comment by mezz** [comment]
![2016-02-27_00 49 10](https://cloud.githubusercontent.com/assets/916092/13372069/56dba4a0-dcec-11e5-8a30-1ce8243dafde.png)

Fixed in the latest version

**Comment by modmuss50** [comment]
Thanks mezz :+1:

**Comment by gigabit101** [comment]
Thanks mezz :+1:

**Comment by ProfessorProspector** [comment]
Thanks mezz :+1:
