### ISSUE TITLE
Missing GUI texture Standalone 1.7.10 0.7.12.1089

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#362]
Missing Gui textures for diseal generator and semifluid generator

**Comment by ProfessorProspector** [comment]
Would a resource pack temporarily suffice, or is there actually no texture path registered?

**Comment by parcel31u** [comment]
http://i.imgur.com/FTHG2Yc.png

**Comment by ProfessorProspector** [comment]
Well I fixed the texture issue but it appears the texture called
semifluid_generator.png is not actually the correct one for the semifluid
generator...so I'm not actually sure what it's supposed to look like.

**Comment by modmuss50** [comment]
I can fix this, but we did release the last 1.7 version. I guess it wont harm to have another one,

**Comment by ProfessorProspector** [comment]
Maybe see if there are any other quick bugs worth fixing if your doing
another release

**Comment by modmuss50** [comment]
@gigabit101 are we going to fix this?

**Comment by gigabit101** [comment]
Umm if you won't to I don't have a 1.7.10 environment set up atm

**Comment by modmuss50** [comment]
I can fix it, I've got one on my other PC. I don't see why not
