### ISSUE TITLE
Would you like me to make a cable model?

### ISSUE THREAD

**Issue by ProfessorProspector** [TechReborn/TechReborn#363]
It would be a json model.

**Comment by modmuss50** [comment]
If its just a basic cable model no, if its something more advanced I will see if I can do it in code.

**Comment by gigabit101** [comment]
@ProfessorProspector can you message us in the #TechReborn irc channel on esper and not open issues ?

**Comment by ProfessorProspector** [comment]
Yeah, I will from bow on. Main problem is that we can almost never be on at the same time, our timezones must be way off.

**Comment by MrBretze** [comment]
UK VS California yes, it's not the same time zones ><

**Comment by modmuss50** [comment]
I've got a bouncer, so I will eventually get the messages.
