### ISSUE TITLE
Alright, so I am very confused. Which gregtech version is this recreating?

### ISSUE THREAD

**Issue by ProfessorProspector** [TechReborn/TechReborn#365]
The github readme says 2.78, the curse page says GT4.

Which is it? And does anyone have a download of the gregtech version that is being recreated?

**Comment by Xen1290** [comment]
Everyone is confused about this. See the closed issues

**Comment by gigabit101** [comment]
![ss 2016-02-28 at 09 34 57](https://cloud.githubusercontent.com/assets/5615438/13378435/920f1058-ddfe-11e5-8809-5fbb028c3198.png)

**Comment by gigabit101** [comment]
there are a few differences to be compatible with IC2 experimental and now standalone

**Comment by gigabit101** [comment]
as for the curse page I did not write it so....

**Comment by modmuss50** [comment]
I will change it

**Comment by gigabit101** [comment]
o0 hey @modmuss50
