### ISSUE TITLE
Alloy Furnace Crash

### ISSUE THREAD

**Issue by QuantumCoretex** [TechReborn/TechReborn#366]
[2016-02-28-3.log.gz](https://github.com/TechReborn/TechReborn/files/150049/2016-02-28-3.log.gz)
I noticed a crash every time I tried to play an alloy furnace (The version was 1090)
sorry btw it was caused when placing an alloy furnace next to a industrial craft 2 iron furnace.
[crash-2016-02-28_09.55.24-server.txt](https://github.com/TechReborn/TechReborn/files/150044/crash-2016-02-28_09.55.24-server.txt)

**Comment by ProfessorProspector** [comment]
Crash report and logs please

**Comment by modmuss50** [comment]
You didnt happen to place it next to a door?

**Comment by modmuss50** [comment]
worldObj.notifyBlockChange(xCoord, yCoord, zCoord, blockType); is causing it to crash. I will take a look. That is very odd. I don't think I need that line so it should be an easy fix

**Comment by QuantumCoretex** [comment]
sorry if this bug was already solved

**Comment by ProfessorProspector** [comment]
No, it wasn't. Thanks for the report, we got it fixed now ;)

**Comment by modmuss50** [comment]
A new build is on curse that fixes it
