### ISSUE TITLE
Tinker's support

### ISSUE THREAD

**Issue by ProfessorProspector** [TechReborn/TechReborn#368]
Add molten metals and tinker smelting/alloy support

**Comment by gigabit101** [comment]
wrong issue number derp...

**Comment by JCMais** [comment]
Was this implemented or closed by mistake? Because currently (latest techreborn version, minecraft 1.9) I cannot smelt techreborn ores in Tinkers smeltery

**Comment by modmuss50** [comment]
This has neaver been a thing, I will look into it

**Comment by gigabit101** [comment]
It should work with copper/tin/lead but as for the rest of are ores I don't see a point?

**Comment by Prospector** [comment]
Alloys?

**Comment by JCMais** [comment]
Thank you!
