### ISSUE TITLE
Recipes to process / use chrome are all missing / wrong

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn#37]
e.g., no IBF recipe for chrome, and advanced machine casings use aluminum instead of chrome.

**Comment by joflashstudios** [comment]
Also, I can craft an electrum block into 9 chrome ingots? Lolwut?

**Comment by Carbon-Ghost** [comment]
Mod still in alpha, may be a LOT of bugs.. ^.^''

**Comment by Carbon-Ghost** [comment]
so we need to squash them, so then we are beta, and then kill the rest of em for stable release, so basically, let's first start with recipes indeed, also OD is sometimes messed up...

**Comment by Carbon-Ghost** [comment]
Also a lot of machines still unimplemented and IC2 classic support still needs to be developped... This is actually alpha pre release then xD

But yeah you are right....

**Comment by joflashstudios** [comment]
@Carbon-Ghost, yeah Carbon, I know all this - I'm one of the project devs. I'm just making issues so I have a record of the problem.

**Comment by gigabit101** [comment]
this is because the meta changed when moving things around @Tntrololol will fix

**Comment by joflashstudios** [comment]
This has been fixed in a number of different commits.
