### ISSUE TITLE
In World Rendering Crash(1.8.9)

### ISSUE THREAD

**Issue by Armagedon13** [TechReborn/TechReborn#371]
http://imgur.com/AVNWkac
Crash Report:
http://pastebin.com/ECHJGEez

**Comment by modmuss50** [comment]
I think we might have to just remove it 1.8

**Comment by gigabit101** [comment]
Yeah I have some Ideas for a replacement but will have to me after we get the rest done

**Comment by gigabit101** [comment]
ps leave the code in reborncore atm
