### ISSUE TITLE
Add Recycler 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#372]

**Comment by Prospector** [comment]
I'll pop this in here because it's sorta related to scrap boxes, but at some point we should add MineTweaker (or Crafttweaker, whatever it's called nowadays) support for the scrapbox loot.

**Comment by Prospector** [comment]
also we really need a weight system for scrapboxes. Good stuff pops up wayyyy to much, and in the old days most of it was scrap, grass, gravel, and wooden tools.
