### ISSUE TITLE
Generator still burns when it's at it's maximum energy storage capacity

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#376]

**Comment by modmuss50** [comment]
I think this is fine, it would be up to the player to prevent fuel waste

**Comment by Prospector** [comment]
Alright. Though that is different from how the old IC2 did it. Speaking of, we need a page in the manual that says the differences between old IC2/GT and TechReborn, for the older players who remember the old mod.

**Comment by modmuss50** [comment]
I can add it
