### ISSUE TITLE
Retrogen

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#380]
For ores and rubber trees. Would be good to get this in before the big release.

**Comment by modmuss50** [comment]
The way I have done it will "break" all current worlds, there will just be twice as much ore.

**Comment by modmuss50** [comment]
Ive done what I can do, in my mind its not worth it.

**Comment by modmuss50** [comment]
If someone wants to fix what I have in on another branch

**Comment by modmuss50** [comment]
Can also go in todo

**Comment by Prospector** [comment]
Hmm is there any other way we could implement a machine or something to get ores for people in existing worlds? Could be defaulted to off.

**Comment by covers1624** [comment]
I have an idea or 2 for fixing retro gen, ill let you know on ts later. It's too complicated to explain here.

**Comment by modmuss50** [comment]
Adding a command to do it would be easier, less laggy, and you could say what would regen. And it would not break existing worlds

**Comment by Prospector** [comment]
Hmm good point. Yes this is a good idea.

**Comment by modmuss50** [comment]
The command will take a radius (in chunks) then you can define what ores/world features are regened, I may rewrite the ore gen to allow more config controls over it.

**Comment by Prospector** [comment]
Hmm perhaps we should move the ore configs to a separate file then. They already take up like half the document.

**Comment by modmuss50** [comment]
Its been added, enable in ore.json, disable once you have loaded the chunks you wanted to be generated
