### ISSUE TITLE
More 1.8 Things 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#383]
- [x] Bat box
- [x] MFE
- [x] MFSU
- [ ] Induction furnace
- [x] Turn transformers back into blocks

**Comment by modmuss50** [comment]
Most of them are easy to do, could almost do the energy storgeblocks and the transformers in one block

**Comment by Prospector** [comment]
Well you could do all 6 in one block. We could make upgrades to change
which tier they are?

**Comment by modmuss50** [comment]
Im doing them in the same block, just with different block sates, no point wasting 6 block ids
