### ISSUE TITLE
Survival Playtesting Issues

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#385]
Since we're nearing a release, I decided to give a survival playtest a try. Here's a few of the issues I've noticed from my play so far. I'll edit this as I find more issues:
- [x] Copper and tin ores don't have smelting recipes
- [ ] No compressor recipe
- [ ] Electric furnace doesn't work when cables are attached to it. (Actually a lot of machines don't)
- [ ] Extractor has no progress bar
- [ ] Recycler JEI handler shows the scrapbox recipes for some reason

**Comment by modmuss50** [comment]
I started putting a pack together to play, i will get a server up within the next week or so

**Comment by gigabit101** [comment]
@modmuss50 you can host it on the dedi if you wont

**Comment by gigabit101** [comment]
sorry im not working on TR at while my internet is like this I cant really commit to the repo

**Comment by modmuss50** [comment]
Yeah no worries, I've got 3 weeks off after this week, so i will have some time.

**Comment by gigabit101** [comment]
Well my new cable should be here Thursday

**Comment by modmuss50** [comment]
Ah good :+1:
