### ISSUE TITLE
MineTweaker Rolling Machine support

### ISSUE THREAD

**Issue by FilipK-CZ** [TechReborn/TechReborn#393]
Can you add Rolling Machine support for MineTweaker?

**Comment by modmuss50** [comment]
its in

**Comment by FilipK-CZ** [comment]
Ou. How can I use it?

**Comment by modmuss50** [comment]
http://blamejared.com/new/modtweaker/1.8.9/Techreborn%20MTRollingMachine.html

**Comment by FilipK-CZ** [comment]
And 1.7.10?

**Comment by modmuss50** [comment]
no, not happening. update

**Comment by modmuss50** [comment]
actually, its the same.

**Comment by FilipK-CZ** [comment]
Thx :)
