### ISSUE TITLE
Bunch of things I found when messing around.

### ISSUE THREAD

**Issue by AKTheKnight** [TechReborn/TechReborn#399]
Any issues/bugs/weird stuff I found while checking out the jenkins release:
RebornCore-1.9-2.0.3.39-universal
TechReborn-1.9-1.0.0.74-universal

Textures:
    Advanced Circuit Board
    Diamond Saw Blade
    Superconductor
    Pump
    Teleporter
    Diamond Jackhammer
    All the sources

Recipes:
    Teleporter
    Advanced drill
    Chainsaw
    Processor circuit board
    Advanced circuit board
    Charge bench
    Omni tool
    Jackhammer
    Iridium reinforced stuff
    Iron fence
    Nuke
    A lot of the plates
    All the nuggets
    Ingots:
        Antimoney
        Red alloy
        Blue alloy
        Cadmium
        Indium
        Lodestone
        Nickel
        Platinum
        Tellurium
        Zinc

```
Block of Ruby and Saphire have two recipes (same)

A lot of the cells

60K NaK coolant cell: recipe placeholder (flint in centrifuge)

Chemical reactor recipesr
```

Drills don't seem to lose power

Advanced drill no faster than diamond drill?

Manual:
    Double images
    Writing going off screen
    Black selection box not covering writing

Rock cutter not silk touching

Some kind of sound when igniting nuke

Solar panels not turning off when moved

Solar panels being powered with a solar panel above them?

Mass fab not producing anything?

Vacuum freezer gui

SPELLING:
    Cables: Should be "Entities" NOT "Entity's"

**Comment by Prospector** [comment]
Split into multiple issues
