### ISSUE TITLE
Texture Issues

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#400]
Pump
Teleporter

**Comment by gigabit101** [comment]
sources dont have Icons anymore look for water source these need to be hidden from JEI

**Comment by mystise** [comment]
Other items:
Superconductor
Diamond saw blade
Diamond Jackhammer
Advanced Circuit Board

**Comment by modmuss50** [comment]
yeah, they have been fixed in git.

**Comment by dries007** [comment]
Totally referenced the wrong issue number, sorry.
