### ISSUE TITLE
Recipe Issues

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#401]
Teleporter [ Removed ]
Advanced drill [ Fixed ]
Advanced chainsaw [ Fixed ]
basic circuit board  [ Removed ]
Processor circuit board  [ Removed ]
Advanced circuit board  [ Removed ]
Charge bench [ Fixed ]
Omni tool [ Going to rework ]
All Jackhammers [ Fixed ]
Nuke [ Really overpowered--keeping it without recipe ]
A lot of the plates [ None of them are needed yet ]
All the nuggets [ this will be tedious ]

**Ingots:**
Platinum [ Fixed ]
Zinc [ Fixed ]

Block of Ruby and Saphire have two recipes (same) [ One is ore dict, one is not. ]

A lot of the cells [ Cells were redone ]

60K NaK coolant cell: recipe placeholder (flint in centrifuge) [ Not an issue]

Chemical reactor recipesr [ Separate issue]

**Comment by gigabit101** [comment]
if someone wonts to take care of these you can get them here http://ftbwiki.org/GregTech

**Comment by Prospector** [comment]
I'm not sure what the circuit boards are for. They're not even in gregtech. Not sure where they came from.

**Comment by gigabit101** [comment]
there was a mix up not long after project started where things from other versions where added just remove anything that is not needed

**Comment by Prospector** [comment]
Gonna do a bit of "housekeeping" when I get home and get rid of these unnecessary things.

**Comment by modmuss50** [comment]
Bumping this for someone else to look at

**Comment by Prospector** [comment]
Heh, now I remember. I was solving this issue, bit I needed to make a teleporter first :P

I'll solve it today

**Comment by Prospector** [comment]
Oh also still need to solve the nickel issue
