### ISSUE TITLE
LESU Suggestion

### ISSUE THREAD

**Issue by Mattabase** [TechReborn/TechReborn#41]
http://i.imgur.com/E5iKAzb.png

Hover tooltip showing standard notation of all scientific notation GUI displays

**Comment by joflashstudios** [comment]
That's just a drawstring call on a integer, so I'm not even sure that the scientific notation is by design. Personally, I think that if possible, we should avoid displaying EU in scientific notation altogether.

**Comment by gigabit101** [comment]
thats a double just needs to be displayed as a int easy fix

**Comment by Mattabase** [comment]
I agree josh, I just assumed it was intended.

**Comment by modmuss50** [comment]
Its just me being lazy, but yes its a very easy fix
