### ISSUE TITLE
Solar panels being powered with a solar panel above them?

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#410]

**Comment by gigabit101** [comment]
This did not happen in my last test

**Comment by modmuss50** [comment]
Can someone confirm?

**Comment by gigabit101** [comment]
im not on comp stuck on laptop while babysitting

**Comment by Prospector** [comment]
not sure if true or not just copied all this stuff from @AKTheKnight's list

**Comment by Rushmead** [comment]
http://uploads.rushmead.xyz/uploader/share/rushmead/2016-03-27_17-47-14.png
