### ISSUE TITLE
Picks take no durability loss when breaking IC2-like energy storage devices

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#417]

**Comment by gigabit101** [comment]
um not are issue

**Comment by mystise** [comment]
BaseTileBlock lacks a hardness setting in the constructor. This is what causes the lack of durability loss, as the blocks break as fast as a torch. Breaking a torch, or any other instantly breakable block, with a tool in survival causes no durability loss.

**Comment by gigabit101** [comment]
RebornCore issue
