### ISSUE TITLE
Generators drop double their internal item storage when broken

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#418]

**Comment by Rushmead** [comment]
Could you please show me this happening and what version are you running?

**Comment by mystise** [comment]
Hm. That's odd, I was able to replicate it every time a few minutes ago, I'll attempt to replicate and if I can I'll post again.

I'm on version 1.0.1.75

**Comment by mystise** [comment]
It's when broken with a wrench.

![2016-03-27_11 45 45](https://cloud.githubusercontent.com/assets/246232/14066810/84d979a4-f411-11e5-85e9-093c12d549ff.png)
![2016-03-27_11 45 49](https://cloud.githubusercontent.com/assets/246232/14066812/84f98898-f411-11e5-8562-ddd796f069d8.png)
![2016-03-27_11 45 54](https://cloud.githubusercontent.com/assets/246232/14066813/84ff6e7a-f411-11e5-9b10-e1e1b6a063cb.png)
![2016-03-27_11 45 58](https://cloud.githubusercontent.com/assets/246232/14066811/84f6f448-f411-11e5-87b9-62338ddbf0ee.png)

**Comment by Prospector** [comment]
Interesting.
