### ISSUE TITLE
Crash Report on Newest Version.

### ISSUE THREAD

**Issue by skullzbeast** [TechReborn/TechReborn#42]
http://pastebin.com/YgDU0tCu 
I put TechReborn 0.1.572, IC2 2.2.736, code chicken core 1.0.4.29, and NEI 1.0.3.74 on forge 10.13.3.1370. I then ran it and got this crash. I was not sure where to put this, and I have never seen that error, so I put this here.

**Comment by modmuss50** [comment]
Update forge, we use a ore dic hook that was added in a recent version of it

**Comment by modmuss50** [comment]
10.13.3.1374 or higer will work, I will add a nice message insted of crashing.
