### ISSUE TITLE
Lava buckets give 2000mb in thermal generator

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#420]

**Comment by modmuss50** [comment]
working fine for me, can someone else test?

**Comment by Prospector** [comment]
Confirming issue. Putting lava bucket in gives 2000 mb rather than 1000

**Comment by Prospector** [comment]
Actually no. It's just clientside. I relogged and it properly went back down.

**Comment by modmuss50** [comment]
ah ok, I can fix this
