### ISSUE TITLE
Diesel Generator and Semifluid Generator Missing Gui Texture

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#421]

**Comment by gigabit101** [comment]
image ?

**Comment by mystise** [comment]
![2016-03-27_11 39 28](https://cloud.githubusercontent.com/assets/246232/14066782/9a867c58-f410-11e5-90d8-504ef92692ca.png)
![2016-03-27_11 39 30](https://cloud.githubusercontent.com/assets/246232/14066783/9a872752-f410-11e5-8dfa-a99a4df24ca8.png)

**Comment by gigabit101** [comment]
....
