### ISSUE TITLE
Energy transfer doesn't work without cables, so without MCMP energy can't be used

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#424]

**Comment by Prospector** [comment]
Well I mean the solution is to install mcmp.

**Comment by gigabit101** [comment]
This will not be a issue when MCMP gets merged into forge

**Comment by mystise** [comment]
But energy transfer should be working using just output to input. Putting a generator next to an energy storage device fills the generators internal storage and never puts it in the energy storage device.

**Comment by gigabit101** [comment]
That is not a thing the internal power net will do

**Comment by Prospector** [comment]
This works properly if you're using the RF config, not sure why this doesn't work with EU.

**Comment by modmuss50** [comment]
If you do not have MCMP, enable RF. I thought we would have MCMP in forge by now, so yeah.
