### ISSUE TITLE
MFE and MFSU drop themselves when broken with a pick rather than a machine block

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#428]

**Comment by gigabit101** [comment]
Lv Transformer and Batbox drop themselfs
MV Transformer and MFE drop machine block
HV Transformer and MFSU drop advanced machine blocks

**Comment by mystise** [comment]
The issue is shown below: (For reference)

![2016-03-27_12 38 30](https://cloud.githubusercontent.com/assets/246232/14067071/0ab19d8e-f419-11e5-8d73-1e8cdc7f7e14.png)
![2016-03-27_12 38 34](https://cloud.githubusercontent.com/assets/246232/14067073/0ad7da9e-f419-11e5-83b0-b2a580978d8a.png)
![2016-03-27_12 38 38](https://cloud.githubusercontent.com/assets/246232/14067072/0ad2c41e-f419-11e5-9fa1-372e350d4410.png)
