### ISSUE TITLE
Multipart cables crash on the server

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#43]
http://pastebin.com/Gwun0YHa

**Comment by modmuss50** [comment]
did https://github.com/TechReborn/TechReborn/commit/54845b8777e9f4237c50a50fc9026e62cac473c7 fit it?

**Comment by gigabit101** [comment]
No

**Comment by modmuss50** [comment]
When does it happen?

**Comment by gigabit101** [comment]
on server start
