### ISSUE TITLE
Higher tier machine casings drop standard machine casings when broken with a pick

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#431]
Standard machine casings aren't a crafting component in any of the higher tiers

![2016-03-27_13 03 11](https://cloud.githubusercontent.com/assets/246232/14067196/4e7e77f0-f41c-11e5-9475-5478a6a34cbc.png)
![2016-03-27_13 03 16](https://cloud.githubusercontent.com/assets/246232/14067197/4ea73aa0-f41c-11e5-9d3e-29468061814d.png)
![2016-03-27_13 03 18](https://cloud.githubusercontent.com/assets/246232/14067198/4ea74c34-f41c-11e5-9cc3-0554b7e96b2c.png)

**Comment by Prospector** [comment]
I have 117 unread emails from github. What did you guys do lol

**Comment by gigabit101** [comment]
we released a version on curse

**Comment by mystise** [comment]
I was excited for TechReborn's 1.0 release and did a bunch of creative testing :P

**Comment by modmuss50** [comment]
There will be a new version going up soon, with some of the fixes we have done recently.
