### ISSUE TITLE
Centrifuging all wood types returns advanced circuit parts and saplings

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#434]
The GT3 recipe only accepted rubber wood, took 16 instead of 15 logs, outputted plant balls rather than saplings, and outputted sticky resin rather than advanced circuit parts:

![screen shot 2016-03-27 at 13 00 30](https://cloud.githubusercontent.com/assets/246232/14067218/dca00c1a-f41c-11e5-894d-8e6de3c3dcb2.png)
![screen shot 2016-03-27 at 13 02 42](https://cloud.githubusercontent.com/assets/246232/14067219/dca0f72e-f41c-11e5-8e91-bead656d009a.png)

**Comment by gigabit101** [comment]
ore dict issue I Think

**Comment by Rushmead** [comment]
i've fixed some of this but we dont have any Plant balls, so i'll leave it to @gigabit101

**Comment by modmuss50** [comment]
I can fix the rest of this
