### ISSUE TITLE
Energy storage blocks do not output energy

### ISSUE THREAD

**Issue by lanAnderson** [TechReborn/TechReborn#435]
I am not able to get energy to output from any of the energy storage block, and they seem to accept energy from all sides including the output. 

(The MFE also doesn't have a GUI)

Using:
Forge 12.16.0.1811
TechReborn-1.9-1.0.2.92
RebornCore-1.9-2.0.3.41
MCMultiPart-1.1.0_55-universal

**Comment by Rushmead** [comment]
Hi, yeah they are currently being worked on and should be fixed tomorow. Apologies

**Comment by Rushmead** [comment]
@modmuss50 this relates to the powernet(Which seems to be broken), assigning you!

**Comment by modmuss50** [comment]
It's it all broken? Or does it break randomly?

**Comment by Rushmead** [comment]
http://uploads.rushmead.xyz/uploader/share/rushmead/2016-03-28_10-40-51.mp4
