### ISSUE TITLE
almost no textures at all

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#439]
was this already in a issue or is this new?

http://abload.de/img/2016-03-28_22.28.07qku8c.png

**Comment by modmuss50** [comment]
What os and graphics card are you on?

**Comment by Sailren** [comment]
windows 7 and igp in amd 5800k apu, i used a faithful pack at the same time, but it also happens without, lemme test build 126 from jenkins

**Comment by modmuss50** [comment]
try without the texture pack?

**Comment by Sailren** [comment]
well, now it seems to be fixed, the icons are back even with texture pack on, but your redpower 2 armor are missing textures

btw, the transformers have all batbox in their tooltip not sure if this is intended

**Comment by modmuss50** [comment]
@Rushmead can you look at the last comment? and yes. there are not textures yet for the armor.

**Comment by Prospector** [comment]
The armour textures are there unless I forgot to push them?

**Comment by Prospector** [comment]
They're for sure there. Refresh your resources folder.

**Comment by Rushmead** [comment]
@modmuss50 yeah its known, have you got guis for the transformers @ProfessorProspector?

**Comment by modmuss50** [comment]
Transformers dont have guis...

**Comment by Rushmead** [comment]
Cool, ill do the transformers in the morning.

**Comment by Prospector** [comment]
Transformers aren't supposed to have guis
