### ISSUE TITLE
Machines don't display the correct texture when running.

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#44]

**Comment by gigabit101** [comment]
they seem to work somtimes but not sure why

**Comment by gigabit101** [comment]
@modmuss50 if a recipe requires a stack size of more than 1 the texture dosnt change eg Bronze in the alloy smelter fails but electrum works

**Comment by gigabit101** [comment]
nope now it seems the tile.crafter,isactive is always returning false

**Comment by modmuss50** [comment]
http://modmuss50.me/shots/Minecraft_1.7.10_2015-07-26_15-22-13.png

Working fine with when powered by eu, but not working on RF machines

**Comment by modmuss50** [comment]
Hopefully this is fixed, if not I will cry
