### ISSUE TITLE
there also seems to be something wrong with the boxes

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#441]
not sure how to describe this and sorry if i post very often, but im very interested in this mod cuz it combines two famous mods in one sweet jar

http://abload.de/img/2016-03-28_23.00.177psnf.png

http://abload.de/img/2016-03-28_23.00.201wsfu.png

the second isn't supposed to be a battery box, i assume it should be a transformer best with internal redstone control

**Comment by Sailren** [comment]
~~isssue with idsu: http://abload.de/img/2016-03-28_23.11.14ahkit.png~~

~~going to sleep now m8, i will check here again tomorrow, in theory i could help with finding issues, sounds funn~~

**Fixed**

**Comment by Prospector** [comment]
We should also add an EV Transformer http://wiki.industrial-craft.net/index.php?title=EV_Transformer

**Comment by modmuss50** [comment]
@Sailren finding issues, is very helpful. We cannot fix things if we dont know about them

**Comment by Sailren** [comment]
i have a lot more strange stuff with machines, but maybe something like advanced machines like rotary macerators, induction furnaces, nuclear jetpacks, stuff perhaps from ic2 classic, your choice what u want to get inside, and the ev transformer, maybe u could add that to supercondensator transform anythig above ev down to 2048 if this makes sense

**Comment by gigabit101** [comment]
We have a api so add-ons are always possible and would be nice to see

**Comment by Sailren** [comment]
if this gets stable and people wake up there could show up some addons, ic2 included gt w/o gregs nerfs, seems to be a good choice, and u would be the first before cofh rofl :D

**Comment by gigabit101** [comment]
you should look at the config file more to come ;)

**Comment by Sailren** [comment]
those rf guys seem to be very far away from 1.9, there isnt even any public alpha yet :D

**Comment by gigabit101** [comment]
TechReborn has a config to allow are machine to be powered with RF fyi

**Comment by Prospector** [comment]
TechReborn supports RF, there's a config to use it.

**Comment by Sailren** [comment]
yeah, i meant stuff like thermal expansion and Immersive Engineering

@ProfessorProspector from your icon i imagine u will add overclockers

**Comment by gigabit101** [comment]
IE is already on 1.8 just not public

**Comment by gigabit101** [comment]
Ender IO is 1.8 aswell

**Comment by Sailren** [comment]
1.9, if this is going well u would be atleast a well known mod for 1.9, and one of the first proper ones, we will see what time brings, maybe one modder or team shows up anytime soon with a blockbuster mod, yeah yeah

**Comment by Sailren** [comment]
time is running short, need to count uu in dreams, gonna check in tomorrow and help with finding issues if i find some

(gibts hier auch deutsche?)

**Comment by gigabit101** [comment]
get build off jenkins if you wont to find new bugs

**Comment by modmuss50** [comment]
Thanks for that

**Comment by Sailren** [comment]
i will m8, i live on a bleeding edge, i'm kind of a nerd, always wants to have the newst stuff xD

**Comment by Speiger** [comment]
@gigabit101 am i seeing wrong? You copied the Battery Box? Really? You are kidding me right?

**Comment by Prospector** [comment]
What do you mean? We needed to use lots of IC2's features so we could run standalone.

**Comment by Speiger** [comment]
@ProfessorProspector there is a difference to implement features to Stand alone and simply copy features... Because EnergyStorage is only a Buffer thing and not really needed...
They should at least ask before they copied this "idea" it is still under IC2 License/My license

**Comment by Prospector** [comment]
Ideas aren't copyrighted. Every single thing in TechReborn is built from the ground up, nothing is stolen or taken from IC2 or Gregtech, except the ideas (and a few textures, but I'm slowly replacing them). We're trying to recreate the experience of playing the old GT 2.78, and to do so there are many things from IC2 we needed to reimplement.

That's like saying Thermal Expansion shouldn't be allowed to make a Pulverizer because the idea was stolen from Industrial Craft.

**Comment by Speiger** [comment]
I know its stated for TinyModularThings and as long i did not tell something differend then these rules count for almost every project i am providing:
https://github.com/TinyModularThings/TinyModularThings/blob/master/Permissions.txt

**Comment by Speiger** [comment]
@ProfessorProspector Idea of a Macerator and Pulverizer are differend. They technically do the same job but still Thermal Expansion did use a differend name... The TechReborn Team used the name from the Original mods and same numbers and almost same system... Only guis are little differend but have still key components... So i count that more stealing then naming something differend, giving it a new layout and also a differend recipeList... So yeah...

**Comment by Rushmead** [comment]
its very simple, dont like the mod? Dont use it.

**Comment by Prospector** [comment]
We have every right to use an idea from IC2 as long as it's not using any of the same code or assets of it. And we are not.

**Comment by Speiger** [comment]
Yeah but you are refering to the IC2 licence but this thing is a Classic thing and there you did not think that my license is also applying to it..

**Comment by Prospector** [comment]
No, nothing's been copied from IC2 classic. We have instances of 1.4.7 minecraft with IC2 and GT2.78 and everything we use is copied directly from there. Though everything in IC2Classic is was also in IC2, so are you claiming you own everything from the old IC2?

**Comment by Prospector** [comment]
Here's my 1.4 instance folder: http://i.imgur.com/AZdJ0bd.png

Everything we copy is from the IC2 version in that folder, or the GT version in that folder. Nothing from IC2 classic.

**Comment by Speiger** [comment]
@ProfessorProspector no i am not claming everything from IC2 Classic. I am claiming only the thing i did add to it... BatteryBox is a thing from classic so?
Edit: talked to modmuss50... Everything fine.

**Comment by modmuss50** [comment]
the bat box has been in ic for ages, way before ic2 classic was a thing. I remember using it in 1.2

**Comment by Rushmead** [comment]
http://wiki.industrial-craft.net/index.php?title=BatBox Sorry we added 4 letters onto an existing machine from Ic2

**Comment by modmuss50** [comment]
If you think we copied code, the mod is open source. Feel free to point out what we copied and I will recode it.
