### ISSUE TITLE
Spessartine dust electrolyzer recipe uses beryllium cells rather than empty cells

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#457]
![2016-03-28_20 22 09](https://cloud.githubusercontent.com/assets/246232/14096076/27e7864c-f523-11e5-8b1f-a313a2092da5.png)

**Comment by Prospector** [comment]
Thanks for all the reports! Your work is very much appreciated!

**Comment by mystise** [comment]
Happy to help :) Sorry if the report spam is a bit much, but last time I listed multiple things per issue the first thing on the list being fixed got the whole issue marked as being fixed :P Whoops.

**Comment by Prospector** [comment]
It's fine, though some of the issues could be put together like all of the ones not using empty cells could go together, etc

**Comment by mystise** [comment]
In the future I will do just that, thanks for you and the team's work on this mod :)
