### ISSUE TITLE
TechReborn items rendered in hand like 1.8 style blocked sword

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#462]
Cell:
![2016-03-28_20 04 44](https://cloud.githubusercontent.com/assets/246232/14096137/975f3042-f523-11e5-8a51-377e0ab9e8ec.png)

Vanilla bone:
![2016-03-28_20 04 59](https://cloud.githubusercontent.com/assets/246232/14096138/976e21a6-f523-11e5-8cc8-b2f8f6bfc0be.png)

This is especially funny with the wrench and pickaxes:
![2016-03-28_20 28 38](https://cloud.githubusercontent.com/assets/246232/14096150/ade080f0-f523-11e5-9e09-1d8a39776c7b.png)
![2016-03-28_20 28 40](https://cloud.githubusercontent.com/assets/246232/14096151/adeef8b0-f523-11e5-9eb6-7892c4e5430a.png)

**Comment by Prospector** [comment]
Yeah, this is a JSON-destroyer issue. It'll get fixed eventually.
