### ISSUE TITLE
Input slots in machines don't have filters

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#463]
For example, the alloy furnace is happy to accept coal in a metal slot and electrum in the fuel slot, and a generator accepts gold as a fuel (but doesn't do anything with it)

![2016-03-28_20 32 38](https://cloud.githubusercontent.com/assets/246232/14096252/612b250c-f524-11e5-819e-056493118738.png)
![2016-03-28_20 32 39](https://cloud.githubusercontent.com/assets/246232/14096253/61402344-f524-11e5-8945-cf9e55e686c6.png)

**Comment by modmuss50** [comment]
This should be possible
