### ISSUE TITLE
Rotating Battery Box with wrench rotates to opposite face clicked

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#467]

**Comment by modmuss50** [comment]
Thats how we decided for it to work, it makes it easy to point it down or up

**Comment by mystise** [comment]
So I suppose there won't be the fancy wrench usage of GT5 and above? (This is personally my favorite method of wrench usage)

http://ftb.gamepedia.com/Wrench_(GregTech_5)#Rotating_the_output_side
