### ISSUE TITLE
Missing Recipe Placeholder allows you to turn flint and other materials into diamonds and coolant cells

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#469]
I'm sure this is going away but I thought I'd make an issue to track it.

![2016-03-28_20 40 40](https://cloud.githubusercontent.com/assets/246232/14096371/70504cd2-f525-11e5-8679-7f65e1798213.png)
![2016-03-28_20 40 43](https://cloud.githubusercontent.com/assets/246232/14096376/7062aa62-f525-11e5-9433-db44604647b0.png)
![2016-03-28_20 40 44](https://cloud.githubusercontent.com/assets/246232/14096373/70620d50-f525-11e5-8239-b8ecd23bf228.png)
![2016-03-28_20 40 51](https://cloud.githubusercontent.com/assets/246232/14096372/7061c5fc-f525-11e5-81be-a4f52a82cfc5.png)
![2016-03-28_20 40 54](https://cloud.githubusercontent.com/assets/246232/14096375/70626674-f525-11e5-87b9-d7876c782f7f.png)
![2016-03-28_20 40 57](https://cloud.githubusercontent.com/assets/246232/14096374/706252d8-f525-11e5-8d11-7640e2f9eea4.png)

**Comment by modmuss50** [comment]
We need to add the missing items

**Comment by Prospector** [comment]
Also need to replace teleporter and pump with blocks

**Comment by modmuss50** [comment]
Yeah, I can do that. I might just put WIP on them for now
