### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#470]
http://pastebin.com/Y3kaD72f

**Comment by Prospector** [comment]
Looks like a HoloInventory issue? 
![image](https://cloud.githubusercontent.com/assets/6166773/14096424/9e65d086-f51d-11e5-9453-1c18a4d2221e.png)

**Comment by modmuss50** [comment]
Yeah, looks like a holoInventory issue, report it to them, it might have something to do with us though. @dries007 any ideas?

**Comment by Prospector** [comment]
Isn't holoinventory a clientside mod?

**Comment by dries007** [comment]
No @ProfessorProspector its not. My first guess its because this mod (or some other mod in the pack) is using null for something it should be using null for. I'll look into it.

**Comment by dries007** [comment]
@parcel31u Do you happen to know what Item causes this?

The contents of the inventory your looking at gets turned into NBT, send to the client and decoded, just like for example chests, but I don't handle null itemstacks on the client side, since they are filtered out on the server side, before sending to the client.

The error occurs because `ItemStack.loadItemStackFromNBT(tag);` is returning null, which should only be possible if `Item.getItemById(tag.getShort("id"))` returns null, which suggests a discrepancy in the id<>item map, which should be impossible...

**Comment by parcel31u** [comment]
@dries007 Specifically looking at the diesel generator from techreborn.

**Comment by dries007** [comment]
@parcel31u how do you have set them up? Its been forever since I played with IC², so I don't know how it all works anymore :p

**Comment by Sailren** [comment]
diesel generator is like combustion egine from buildcraft or biogas engine from forestry just for eu and maybe rf

**Comment by dries007** [comment]
but if I put one down, no IC² cables connect to it, and if I put in fuel it does nothing at all?

**Comment by Sailren** [comment]
the cable stuff belongs to mc multipart, but he is waiting for forge if they revert their event stuff or not

**Comment by gigabit101** [comment]
You need MC multipart for the cables to work there is a tooltip on cables saying this

**Comment by gigabit101** [comment]
as soon as it is merged into forge this will not be a issue

**Comment by Sailren** [comment]
he should give them his code so its faster for us available

**Comment by gigabit101** [comment]
will.make no diff forge has work to be done on it still and forge will be updating to 1.9.1 soon

**Comment by Sailren** [comment]
leaks?

**Comment by gigabit101** [comment]
no it has already been said after the re factor they wanted to move to 1.9.1

**Comment by gigabit101** [comment]
also basic logic applies here as well

**Comment by dries007** [comment]
@gigabit101 I disagree
https://dries007.net/screenshots/2016-03-29_18-55-06.png

Also, we are talking about 1.7.10 here, since Holoinventory is 1.7.10 only

**Comment by gigabit101** [comment]
you are using 1.7 why did you not say that

**Comment by gigabit101** [comment]
well the mod was not finished back then so try using the cables from TR as the RF config might be on

**Comment by dries007** [comment]
Because I did not make this issue.
Shouldn't it fill up its internal buffer regardless of if I put on cables or not?
https://dries007.net/screenshots/2016-03-29_19-00-35.png

**Comment by Sailren** [comment]
true

**Comment by modmuss50** [comment]
it should do yes

**Comment by gigabit101** [comment]
... It might have just not been finished at that point

**Comment by dries007** [comment]
But how is this person crashing then?
@parcel31u do you know what items where in the slots of the generator?

**Comment by gigabit101** [comment]
I don't remember what was broken in that version

**Comment by Sailren** [comment]
doesn't seem to be much since bakermanlp uses techreborn in his project RET series and this is 1.7.10

**Comment by gigabit101** [comment]
well good 2 know

**Comment by gigabit101** [comment]
wrong button lol

**Comment by dries007** [comment]
omg the email spamm

**Comment by modmuss50** [comment]
I didnt even click the button

**Comment by gigabit101** [comment]
lol

**Comment by modmuss50** [comment]
Is there something to fix, or shall I close it?

**Comment by gigabit101** [comment]
Its 1.7 and I don't think its ares

**Comment by Sailren** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0

rofl

**Comment by dries007** [comment]
I guess I need more information, but it seems to mee like a bug in your code (or a strange interaction). I can see if I can build in some protection in HoloInventory.

ps: Just a friendly note: Treating the github issue tracker like an IRC channel with quick, gibberish, incomprehensible comments and memes is not going to make others eager to help or respond.

**Comment by Sailren** [comment]
it wasnt supposed to be offensive, it just fit into modmuss "shall i close it" sentence

**Comment by dries007** [comment]
I know, its not offensive, but it's not very professional. Its also a bunch of email spam again :email:
