### ISSUE TITLE
Highly advanced machine block drops regular machine block when broken with a pick

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#472]
Other machine blocks are unaffected. On a side note, none of them are wrenchable.

![2016-03-28_20 46 51](https://cloud.githubusercontent.com/assets/246232/14096512/9c785c90-f526-11e5-97f6-b69e85c76206.png)
![2016-03-28_20 46 54](https://cloud.githubusercontent.com/assets/246232/14096513/9c786488-f526-11e5-82c0-f7e343ad6282.png)

**Comment by Prospector** [comment]
They're not supposed to be wrenchable, they're crafting ingredients. Will be fixed in next push.
