### ISSUE TITLE
Quantum tank has missing top texture in third person

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#473]
First person and item in inventory are fine, item in inventory's third person view and actual third person view are not.

![2016-03-28_21 11 51](https://cloud.githubusercontent.com/assets/246232/14096946/bff95112-f529-11e5-8a40-afdbf6383583.png)

**Comment by modmuss50** [comment]
This is a json destroyer issue.

**Comment by AKTheKnight** [comment]
#BlameJsonDestroyer

**Comment by modmuss50** [comment]
I've rewritten part of json destroyer to fix all the issues.

**Comment by Prospector** [comment]
Wait like ALL the issues?

**Comment by modmuss50** [comment]
yes, items all fixed, tools all fixed, blocks all fixed

**Comment by Prospector** [comment]
Wow good job, didn't take you long either at all.

**Comment by covers1624** [comment]
RIP #BlameJsonDestroyer 2016-2016

**Comment by gigabit101** [comment]
I can hold a sword woop woop 
![ss 2016-03-29 at 12 02 22](https://cloud.githubusercontent.com/assets/5615438/14105884/31e80ac6-f5a6-11e5-820d-5ad72f847c46.jpg)
