### ISSUE TITLE
Using beryllium cells rather than empty cells

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#474]
Centrifuge:
- Rubber Wood
- Endstone Dust

Electrolyzer:
- Emerald Dust
- ?
- Lapis (? Bug report said dye)
- Peridot Dust
- Pyrope Dust
- Sand
- Almandine Dust
- Spessartine Dust
- Andradite Dust
- Grossular Dust
- Uvarovite
- Dark Ashes

**Comment by modmuss50** [comment]
Is this an issue with the recipe, or an issue with getting the empty cell?

**Comment by Prospector** [comment]
Not sure. I'm not even sure where these recipes are registered. They weren't in the ModRecipes file I don't think.

**Comment by Rushmead** [comment]
Its an issue with getting the empty cell i think

**Comment by Prospector** [comment]
Maybe we should separate the different machine recipes into different classes. It's super hard (impossible) to navigate it without CTRL+F and even then it's hard to find what I'm looking for
