### ISSUE TITLE
Can't rotate or wrench IDSU, AESU, or LESU

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#476]
Right click does nothing except on top face, which opens the GUI. Shift-right click does nothing even when clicking on the top face.

**Comment by Rushmead** [comment]
Please update to the latest version.

**Comment by mystise** [comment]
I am on the latest jenkins version. TechReborn: 1.0.3.139 RebornCore:2.0.4.44

**Comment by mystise** [comment]
On the latest version (TechReborn 1.0.3.140 RebornCore: 2.0.4.44) the AESU and IDSU can be rotated by the wrench, the LESU cannot. The AESU, IDSU, and LESU cannot be broken with the wrench either.

**Comment by mystise** [comment]
Rotating is also client side only, so rotating then entering and exiting the GUI causes them to revert back to their original state.

**Comment by modmuss50** [comment]
The wrench needs a recode, it does not use the api correctally

**Comment by Dragon2488** [comment]
They need full rewrite.
