### ISSUE TITLE
MFSU drops advanced machine block when broken with a pick

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#477]
It should drop a regular machine block, as it's crafted from an MFE which uses a regular machine block.

![2016-03-29_11 29 20](https://cloud.githubusercontent.com/assets/246232/14117350/852794b8-f5a1-11e5-8e1f-2a1b5a1e101c.png)
![2016-03-29_11 29 24](https://cloud.githubusercontent.com/assets/246232/14117351/85379520-f5a1-11e5-95cd-d0ec03a51909.png)

**Comment by gigabit101** [comment]
Its crafted with both or at least should be

**Comment by mystise** [comment]
Huh. The current recipe uses 2 advanced circuits instead.

![2016-03-29_11 49 55](https://cloud.githubusercontent.com/assets/246232/14117956/6d884d40-f5a4-11e5-9bfa-2aa75cb4fe2b.png)
![2016-03-29_11 49 53](https://cloud.githubusercontent.com/assets/246232/14117955/6c2b7792-f5a4-11e5-8370-e2706a88942f.png)

**Comment by gigabit101** [comment]
yeah I will fix that
