### ISSUE TITLE
Electrolyzer recipes

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#484]
Running TechReborn: 1.0.3.140 RebornCore: 2.0.4.44

1. Pyrite returns only 1 sulfur

![2016-03-29_15 42 51](https://cloud.githubusercontent.com/assets/246232/14124856/22e34148-f5c5-11e5-9beb-c680da93598f.png)

GT2: 
![2016-03-29_15 42 53](https://cloud.githubusercontent.com/assets/246232/14124860/26208c1c-f5c5-11e5-988c-eb246b2fcee3.png)

2. Sulfuric acid processing returns sulfur dust rather than sulfur cell (Not that bad since sulfuric acid is uncraftable (because the canning machine doesn't exist, so sulfur cells are uncraftable) and doesn't have any other uses)

![2016-03-29_15 45 47](https://cloud.githubusercontent.com/assets/246232/14124908/7e197dc0-f5c5-11e5-97aa-dfb48b2bfbdf.png)

GT2:
![2016-03-29_15 47 22](https://cloud.githubusercontent.com/assets/246232/14124920/8a578b54-f5c5-11e5-865f-3755c8c5b33e.png)

3. (Sapphire/peridot/pyrope dust)/sand return more empty cells than they consume

![2016-03-29_15 49 55](https://cloud.githubusercontent.com/assets/246232/14125016/27e77848-f5c6-11e5-9c49-0aac6612bb19.png)
![2016-03-29_15 53 29](https://cloud.githubusercontent.com/assets/246232/14125059/6c57438c-f5c6-11e5-95f5-d1a5049e0164.png)
![2016-03-29_15 56 12](https://cloud.githubusercontent.com/assets/246232/14125164/e52694fc-f5c6-11e5-8a69-804884bd3db2.png)
![2016-03-29_15 56 14](https://cloud.githubusercontent.com/assets/246232/14125165/e533d702-f5c6-11e5-912c-81a6af4371fd.png)

4. Recipes that return compressed air in GT2 should probably not take or return empty cells, as compressed air doesn't exist
- Ruby dust
- Sapphire dust
- Peridot dust
- Emerald dust
- Missing recipe placeholder (Flint dust?)
- Olivine (Currently Peridot, see 5) dust
- Pyrope dust
- Sand
- Almandine dust
- Spessartine dust
- Andradite dust
- Grossular dust
- Uvarovite dust
- Nitrogen Dioxide

5. Peridot dust has a duplicate recipe that's supposed to be Olivine dust

![2016-03-29_15 55 00](https://cloud.githubusercontent.com/assets/246232/14125131/b6d026d6-f5c6-11e5-9f61-2cdcc3f4ad99.png)

GT2:
![2016-03-29_15 55 02](https://cloud.githubusercontent.com/assets/246232/14125135/bbfc4d1a-f5c6-11e5-8b56-05204f45e4e9.png)

6. Ruby dust takes only 6 instead of 9

![2016-03-29_15 59 46](https://cloud.githubusercontent.com/assets/246232/14125229/4aafa35e-f5c7-11e5-8208-e268a3fa2e20.png)

GT2:
![2016-03-29_15 59 49](https://cloud.githubusercontent.com/assets/246232/14125233/4e23e824-f5c7-11e5-9104-52f87c85b409.png)

7. Sapphire dust takes only 5 instead of 8

![2016-03-29_16 00 21](https://cloud.githubusercontent.com/assets/246232/14125252/64fb4b6e-f5c7-11e5-855d-b603dde5aaf0.png)

GT2:
![2016-03-29_16 00 18](https://cloud.githubusercontent.com/assets/246232/14125254/68b05736-f5c7-11e5-9a6b-45b8116793d6.png)

8. Nitrogen dioxide duplicates cells

![2016-03-29_16 01 31](https://cloud.githubusercontent.com/assets/246232/14125295/ac96c0f2-f5c7-11e5-93ec-78bd087454b7.png)

9. Calcium recipe should only take bonemeal, not all dyes

![2016-03-29_16 03 38](https://cloud.githubusercontent.com/assets/246232/14125315/d896a8d4-f5c7-11e5-9a36-e1c42b9f73ee.png)

GT2:
![2016-03-29_16 03 50](https://cloud.githubusercontent.com/assets/246232/14125319/da6c1626-f5c7-11e5-9b19-d89507666d8b.png)

10. Calcium carbonate recipe should take 2 cells in and provide 1 calcium and 1 carbon based on recipe

![2016-03-29_16 05 16](https://cloud.githubusercontent.com/assets/246232/14125371/1dce5ab4-f5c8-11e5-82c7-f62f7f40b769.png)
![2016-03-29_16 05 38](https://cloud.githubusercontent.com/assets/246232/14125372/207c7f98-f5c8-11e5-8f2c-71d915ae36dc.png)

11. Sodium Persulfate should take in 4 cells and output 1 sulfur cell, 1 sodium cell, and 2 empty cells based on the recipe. (This suffers from the same problem that sulfuric acid does, because the canning machine doesn't exist it can't actually be crafted)

12. Ashes to carbon cells should be a 2->1 electrolyzer recipe but is currently a 1->1 centrifuge recipe

![2016-03-29_16 11 52](https://cloud.githubusercontent.com/assets/246232/14125538/f68008a8-f5c8-11e5-9023-47e09971aa8f.png)

GT2:
![2016-03-29_16 11 49](https://cloud.githubusercontent.com/assets/246232/14125541/fa227a86-f5c8-11e5-8b4b-eb8526980227.png)

**Comment by Zygimantass** [comment]
If you guys need help, I probably could fix this

**Comment by gigabit101** [comment]
PRs are always welcome

**Comment by modmuss50** [comment]
Close this as its been 10 months and a lot of recipes have changed. Feel free to open or let me know if there are still issues.
