### ISSUE TITLE
Centrifuge Recipes

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#486]
- Blaze powder currently centrifuges to sulfur and dark ashes at a 1->1+1 rate, when it should be an electrolyzer recipe at a 4->1+1 rate.

![2016-03-29_16 24 37](https://cloud.githubusercontent.com/assets/246232/14125901/decae078-f5ca-11e5-8fd5-29c29fc472a0.png)

GT2:
![2016-03-29_16 24 36](https://cloud.githubusercontent.com/assets/246232/14125904/e2abff7e-f5ca-11e5-8681-6f60283ea599.png)
- Basalt dust produces Peridot dust and Magnesium dust rather than Olivine dust and Flint dust

![2016-03-29_16 27 00](https://cloud.githubusercontent.com/assets/246232/14125949/2721b9be-f5cb-11e5-8192-61f5a588c3cf.png)

GT2:
![2016-03-29_16 27 05](https://cloud.githubusercontent.com/assets/246232/14125951/2a1179c0-f5cb-11e5-9abf-9684a8eb5e39.png)
- Netherrack dust produces basalt dust rather than coal dust

![2016-03-29_16 30 17](https://cloud.githubusercontent.com/assets/246232/14126005/91a697a0-f5cb-11e5-8150-cc13369c7687.png)

GT2:
![2016-03-29_16 30 19](https://cloud.githubusercontent.com/assets/246232/14126007/9481ea92-f5cb-11e5-82fc-e75e42ee567e.png)
- Lapis dust produces 7 pyrite dust when it should produce 1

![2016-03-29_16 31 57](https://cloud.githubusercontent.com/assets/246232/14126049/d53edd24-f5cb-11e5-96c9-e52eebfc44ee.png)

GT2:
![2016-03-29_16 31 55](https://cloud.githubusercontent.com/assets/246232/14126051/d9697de6-f5cb-11e5-8e54-e9b7cbff755b.png)
- Glowstone produces 1 redstone dust instead of 8 and there is a duplicate recipe that produces 8

![2016-03-29_16 32 59](https://cloud.githubusercontent.com/assets/246232/14126073/f14b38fa-f5cb-11e5-9282-5256530d6059.png)

![2016-03-29_16 38 06](https://cloud.githubusercontent.com/assets/246232/14126216/ad012a82-f5cc-11e5-9486-3776a966ae84.png)

GT2:
![2016-03-29_16 33 01](https://cloud.githubusercontent.com/assets/246232/14126075/f2a50c62-f5cb-11e5-988f-67405579cb56.png)
- Glistering melons should take 8 instead of 1

![2016-03-29_16 34 26](https://cloud.githubusercontent.com/assets/246232/14126118/20a2a250-f5cc-11e5-9372-c4b25bfb89c5.png)

GT2:
![2016-03-29_16 34 25](https://cloud.githubusercontent.com/assets/246232/14126121/22c6fb30-f5cc-11e5-8bd2-2eb8be3a2201.png)
- Nether wart should take 32 instead of 1

![2016-03-29_16 36 10](https://cloud.githubusercontent.com/assets/246232/14126156/5f13aed0-f5cc-11e5-8cbc-f29a80ca7275.png)

GT2:
![2016-03-29_16 36 11](https://cloud.githubusercontent.com/assets/246232/14126159/62e1bf98-f5cc-11e5-9da3-0ffcf185674f.png)
- Red and brown mushrooms should take 32 instead of 1

![2016-03-29_16 37 11](https://cloud.githubusercontent.com/assets/246232/14126166/80e82a68-f5cc-11e5-9c92-e90b861b7204.png)
![2016-03-29_16 37 12](https://cloud.githubusercontent.com/assets/246232/14126167/80fc450c-f5cc-11e5-8ab9-a9ffca82a605.png)

GT2:
![2016-03-29_16 37 03](https://cloud.githubusercontent.com/assets/246232/14126175/840c3f36-f5cc-11e5-9cfb-a446ff402345.png)
![2016-03-29_16 37 04](https://cloud.githubusercontent.com/assets/246232/14126174/84090adc-f5cc-11e5-9c25-00a809e88d32.png)
- Redstone should produce 5 pyrite instead of 3

![2016-03-29_16 39 37](https://cloud.githubusercontent.com/assets/246232/14126255/ddbd23e2-f5cc-11e5-89a6-2586d48ac048.png)

GT2:
![2016-03-29_16 39 35](https://cloud.githubusercontent.com/assets/246232/14126256/dfa130a4-f5cc-11e5-9c07-aeb961de5176.png)
- Cinnabar dust should be an electrolyzer recipe

![2016-03-29_16 40 41](https://cloud.githubusercontent.com/assets/246232/14126278/03ecd74c-f5cd-11e5-933b-03e156990311.png)

GT2:
![2016-03-29_16 40 40](https://cloud.githubusercontent.com/assets/246232/14126279/06014248-f5cd-11e5-98d2-7935baeb334b.png)
- Flint dust should be an electrolyzer recipe, should take 8, and should produce a single silicon cell

![2016-03-29_16 41 23](https://cloud.githubusercontent.com/assets/246232/14126293/239c7dcc-f5cd-11e5-9be4-9390e1deb5a4.png)

GT2:
![2016-03-29_16 41 24](https://cloud.githubusercontent.com/assets/246232/14126295/26598a8c-f5cd-11e5-9bc8-151437e3a685.png)
- Lava cells should take 16, produce 1 electrum ingot, 18 tin ingots, 4 copper ingots, and 1 small pile of tungsten dust (For some reason in GT2 the small pile of tungsten dust is called a tiny pile, but still takes 4 to craft one dust)

![2016-03-29_16 43 11](https://cloud.githubusercontent.com/assets/246232/14126340/7ab8b918-f5cd-11e5-9af6-f1e98807065f.png)

GT2:
![2016-03-29_16 43 10](https://cloud.githubusercontent.com/assets/246232/14126345/7ce467e6-f5cd-11e5-9b9f-caa0e71d1e96.png)

**Comment by Zygimantass** [comment]
Assign me to this if you can

**Comment by modmuss50** [comment]
Doesn't look like I can, and im replying to your reddit message now

**Comment by modmuss50** [comment]
Same with this one: Close this as its been 10 months and a lot of recipes have changed. Feel free to open or let me know if there are still issues.
