### ISSUE TITLE
Crash when loading with IC2 classic

### ISSUE THREAD

**Issue by BBoldt** [TechReborn/TechReborn#49]
* [IC2.Classic.Version.1.0.9.10](https://github.com/TinyModularThings/IC2Classic/releases/tag/1.0.9.10)
* TechReborn-Classic-universal-0.1.7-universal
* Forge 1472

https://gist.github.com/BBoldt/c88951a0275aea526345

**Comment by TheQuantumGeneral** [comment]
I also crash with IC2 Classic, this crash doesn't occur when using the latest IC2 Experimental

Does appear to be a separate crash to BBoldt's

http://pastebin.com/vDk854L5

**Comment by modmuss50** [comment]
Thats @TheQuantumGeneral It is indeed a separate bug, I will make a new issue for i. But before I do it doesn't look like your using the Classic version of TechReborn?

**Comment by TheQuantumGeneral** [comment]
Yep, i'm an idiot, launched with wrong .jar

Identical crash to the OP - http://pastebin.com/5S1hx5pC

**Comment by modmuss50** [comment]
Ok thanks :), sadly we are working to getting the normal version stable then we will turn out attention to Classic

**Comment by Carbon-Ghost** [comment]
No problem, the priority is stability ;)

We also are trying to make IC2 classic even more stable and atm we are more successful than exp, lol, so no need to rush, we have time ;)

**Comment by gigabit101** [comment]
Moved to https://github.com/TechReborn/TechReborn-Classic-/issues/1
