### ISSUE TITLE
Industrial grinder mess up everything

### ISSUE THREAD

**Issue by oldjunyi** [TechReborn/TechReborn#491]
Setup:
3x3 standard machine casings
3x3 hollow reinforced machine casings with air in the middle
3x3 standard machine casings
An industrial grinder attached to center of a face
Then I right clicked the industrial grinder:
![2016-03-31_13 01 07](https://cloud.githubusercontent.com/assets/641817/14165896/b6b9465c-f740-11e5-9436-09763fa2a56e.png)

There are only broken textures, messed inventory and the "MISSING MULTIBLOCK" hint.
Test environment: Forge 1816, RebornCore 46, TechReborn 142, together with JEI and other functional mods.

**Comment by modmuss50** [comment]
@mezz any ideas?

**Comment by Sailren** [comment]
the missing multiblock could be water inside as in gt <5 or full casings, try to place 1 reinforced inside to replace air

**Comment by Sailren** [comment]
i have a similar bug like this, but it's not JEI, its the block itself, as u can see in this pic is jei not installed

http://abload.de/img/2016-03-31_17.22.39zdspr.png

http://abload.de/img/2016-03-31_17.22.37m1s9j.png

http://abload.de/img/2016-03-31_17.22.34y5spy.png

http://abload.de/img/2016-03-31_17.22.31wxsl2.png

http://abload.de/img/2016-03-31_17.22.28jssrd.png

**Comment by modmuss50** [comment]
ok, thanks for that. It must be an issue with the gui

**Comment by Sailren** [comment]
no problem, i like to help :)

**Comment by mezz** [comment]
My best guess is that the gui's guiLeft is set to 0, and the texture is being offset to put it in the right place.
