### ISSUE TITLE
no processing

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#492]
i placed some silver ore from TeREBo into the macerator and hooked up three gens to it via glas fiber, i took the ore out of the macerator and placed it inside again to test if it would explode, nada, it just not processing, three gens should be sucifient to power it, even 1 should be

http://abload.de/img/2016-03-31_17.04.27z8y14.png

the gens are all active

http://abload.de/img/2016-03-31_17.04.13k7uvn.png

oh btw, neotechs ores dont work in the macerator

**Comment by AKTheKnight** [comment]
This is an issue with the grinder not getting power. If you try with copper insulated cables it might work

**Comment by Sailren** [comment]
not getting power with 3 generators and almost lossless cable?

since which ic2 is the macerator a power sink block? the matter fabricator surely, but not a tier 1 processor

**Comment by Sailren** [comment]
oh btw, are u guys implementing advanced machines for those "i have no time, i want fast copper" people? 

this:

http://ftbwiki.org/Induction_Furnace

http://ftbwiki.org/Centrifuge_Extractor

http://ftbwiki.org/Singularity_Compressor

http://ftbwiki.org/Rotary_Macerator

**Comment by gigabit101** [comment]
That seems to be a power issue fyi might be a power net bug
as for advanced machines Add-on mod might be the best way for that

**Comment by Sailren** [comment]
if we get some

**Comment by gigabit101** [comment]
There is already one being made and I may end up making it myself

**Comment by Sailren** [comment]
do u have a link for the WIP mod?

**Comment by gigabit101** [comment]
nope

**Comment by Sailren** [comment]
how do u know that there is 1 made

**Comment by gigabit101** [comment]
But I will do advanced machines myself https://github.com/gigabit101/AdvancedMachinesReborn might start it tonight

**Comment by gigabit101** [comment]
and I said being made... @Rushmead is making one

**Comment by Sailren** [comment]
cool stuff, btw i like your mods, some of them are very good

**Comment by gigabit101** [comment]
Ty

**Comment by Prospector** [comment]
Hey @Gigabit101 want some textures for the advanced machines?

**Comment by gigabit101** [comment]
I sure do
