### ISSUE TITLE
Rubber leaves are non-transparent on Fancy mode

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#494]
![image](https://cloud.githubusercontent.com/assets/6166773/14223921/3a0a745a-f83f-11e5-90ee-d87eeca00856.png)

**Comment by covers1624** [comment]
I have the same issue with jarrm, the only way to fix it that I have found is to asm a hook in, otherwise you could create a client tick handler and cache if fancy is enabled and then set the leaves to fancy the way vanilla does if the fancy cache has changed.

**Comment by modmuss50** [comment]
No, is an issue with json destroyer in 1.9

**Comment by covers1624** [comment]
Ahh, I see.

**Comment by modmuss50** [comment]
Fixed in: https://github.com/TechReborn/TechReborn/commit/e7f9c679dfc0f717d03c0a44596507405a28208b
