### ISSUE TITLE
To Remove

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#495]
These can be removed, but I'm not sure how I can remove them without screwing up all of the ids.
- Advanced circuit parts
- basic circuit board
- advanced circuit board
- rock cutter blade
- teleporter
- pump
- mass hole device
- crushed ores

And these need to be re-added as blocks:
- pump
- teleporter

**Comment by modmuss50** [comment]
Is this the full list? now that we are working towards 1.1 we can remove things.

**Comment by Yulife** [comment]
- Plates
- Doge Coin
- Tellerium
- Antimony
- Forge Hammer
- Laser Focus
- Chunkloader 
- Heat Generator
- Battery Alloy
- Red Alloy
- Blue Alloy 
- Cadmium 
- Cupronickel (as in the ingots, etc, not the heating coil!)
- Kanthal(as in the ingots, etc, not the heating coil!)
- Nichrome(as in the ingots, etc, not the heating coil!)
- Magnalium
- Osmium
- Gem Armour
- Lodestone 
- Indium

**Comment by Prospector** [comment]
Gonna keep plates in, we plan on using them for an addon.

**Comment by Prospector** [comment]
I've got a lot of stuff half removed in my env so nobody touch that stuff or there's gonna be all kinds of merge conflicts

**Comment by ghost** [comment]
plates, are amazing , also what was the mass hole device ?

**Comment by Yulife** [comment]
- Circuit Parts 
- Machine Hulls
- Gem Tools

**Comment by Prospector** [comment]
Why not keep gem stuff? IMO it's part of the experience because anyone running GT had red power which had gem tools and armour. I think about TR as recreating the experience, rather than just GT

**Comment by ghost** [comment]
Why remove the gem tools ?

**Comment by Yulife** [comment]
I guess. I just thought that you wanted to recreate IC2 and GT and not mods like Redpower :)

**Comment by modmuss50** [comment]
I dont think we should remove everying to be on par with that exact version. Just remove the usless stuff

**Comment by BBoldt** [comment]
KEEP THE DOGE COIN HOW DARE YOU

**Comment by Prospector** [comment]
rip dogecoin

**Comment by modmuss50** [comment]
Dogecoin has to go, its using a massive texture and is stupid. The other stuff im not convinced with

**Comment by BBoldt** [comment]
D:

Think of the memes!

**Comment by Yulife** [comment]
No memes allowed
