### ISSUE TITLE
After relaunching my game, player detector blocks lost their textures

### ISSUE THREAD

**Issue by HarrisFauntleroy** [TechReborn/TechReborn#496]
If I placed new ones they would work fine

http://imgur.com/9xgYjoS

TechReborn-1.9-1.0.4.143-universal
RebornCore-1.9-2.0.4.46-universal

**Comment by Prospector** [comment]
Yep, they're a work in progress

**Comment by HarrisFauntleroy** [comment]
I assume everything is WIP, just these are behaving differently in regards to texture loading to all the other machines. Bug reports yo.

**Comment by modmuss50** [comment]
yeah, they were crashing on placement, this was the quick fix. I will get them working soon

**Comment by gigabit101** [comment]
closing this as block use jsons now

**Comment by modmuss50** [comment]
not all blocks use jsons, this is still an issue
