### ISSUE TITLE
Industrial grinder GUI not culling JEI... or something

### ISSUE THREAD

**Issue by HarrisFauntleroy** [TechReborn/TechReborn#498]
Every other machines GUI has JEI off to the side as normal, the industrial grinder seems to get messed up.

Picture shows Industrial grinder working wrong and blast furnace working correctly

http://imgur.com/a/8ITtp

TechReborn-1.9-1.0.4.143-universal
RebornCore-1.9-2.0.4.46-universal

**Comment by Prospector** [comment]
Dupe, and I believe this is already fixed? Don't think it's in a curse build yet though #491
