### ISSUE TITLE
TechReborn 1.8.9 bugs

### ISSUE THREAD

**Issue by Armagedon13** [TechReborn/TechReborn#499]
-Texture Incomplete:
Quantum Tank
Chermical Reactor
Plasma generator
Fusion Reactor
Lighting Rod
- Texture Lost
  Advanced Circuit Boards
  Diamond Saw Blades
  Super Conductor
  Pump
  Teleporter
  Water Mill
  Wind Mill
  Energy Cristal
  Lapotron Cristal
  Diamond JackHammer(0 EU and 100 EU)
  Refined Iron Ingot
  Super Conductor
- Recipe lost
  1 item lost "Missing Recipe Place Holder"
  Assembling Machine
  Data orb
  Platinum plate
  Titanium Plate
  Chrome Plate
  Advanced Alloy
  Teleporter
  Charge Bench
  All Player Detector
  All Machine Hull
  Basic Circuit Board
  Advanced Circuit Board
  Processor Circuit Board
  Data Control
  Laser Focus
  Aerospace Advanced....
  Lazurite Chunk
  Aluminium Plate 
  Lithium Cell
  Lapotron Pack
  Omni Tool
  Compressor
  Carbon Plate
  Water Mill
  Wind Mill
  Battery Box
  MFE
  MFSU
  And Wrong Name And Recipe for "LVt" "MVt" "HVt"
  Scrapbox-Inator
  Advanced Drill
  Iron Chainsaw and Diamod Chainsaw and Advanced Chainsaw
  All Jack Hammer
  NanoSaber
- Wrong Gui
  Quantum Chest
  Digital Chest
  Industrial Blast Furnace i can't use Upgrade Slot
  Implosion Compressor i can't use Upgrade Slot
  Magic Energy Converter
  Diesel Generator
  Semifluid Generator
  Gas Turbine
  IDSU AESU And LESU
  Destilation Tower
  Electric Autocrafiting Table
  Vacuum Freezer wrong "A" "B" button
  Plasma Generator
  Description of the Book and the techcomputer
  Water Mill
  Wind Mill
  Battery Box
  MFE
  MFSU
  All energy Voltage Changer
- Some images:http://imgur.com/a/0NOjl

And now nothing, just congratulate you for the excellent work and new textures that are beautiful

**Comment by Prospector** [comment]
Would you mind checking which of these bugs exist in 1.9? We're not working on the 1.8 version anymore, but we do plan on porting the changes in 1.9 to our 1.8 branch soon. Most of these have probably been fixed in 1.9

**Comment by Armagedon13** [comment]
Of course, thanks for answering

**Comment by modmuss50** [comment]
Most of this wont get fixed in 1.8, use 1.9 or 1.8 with ic2

**Comment by modmuss50** [comment]
1.8 is dead
