### ISSUE TITLE
transformers doesnt work at all

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#503]
first picture: http://abload.de/img/2016-04-04_16.05.33tez30.png

http://abload.de/img/2016-04-04_16.07.21blszz.png

http://abload.de/img/2016-04-04_16.05.22n2sf5.png

http://abload.de/img/2016-04-04_16.04.487ws9i.png

http://abload.de/img/2016-04-04_16.04.306msoz.png

**Comment by cookta2012** [comment]
What version of Minecraft, what other mods, and version of forge, and what version of Tech Reborn

**Comment by Sailren** [comment]
1.9
mcmp, quark by vazkii
1836
1.0.4.162

the first mfsu behind the coal generator doesn't get power if i dont connect it with a cable

that was weird, after client reload u have to disconnect cable from mfsu and replace again so it charges again, same happens to 2nd mfsu, u have to replace the hv cable so it recognizes the inventory for pwoer storage

those heat gens in lava refuse to generate power in mfsu even when connected via glass fiber

http://abload.de/img/2016-04-04_16.32.19kps5z.png

http://abload.de/img/2016-04-04_16.32.49zis17.png

http://abload.de/img/2016-04-04_16.32.50dbsdi.png

http://abload.de/img/2016-04-04_16.32.53s5swi.png
