### ISSUE TITLE
Latest release build for 1.9 crashes on Init

### ISSUE THREAD

**Issue by Mach12** [TechReborn/TechReborn#504]
The title is pretty self-explanatory, I'll just drop the crash log and leave the rest to you.
[Crash report](https://github.com/TechReborn/TechReborn/files/204195/crash-2016-04-05_11.18.43-client.txt)

**Comment by modmuss50** [comment]
Update reborn core

**Comment by Mach12** [comment]
Then you need to provide a minimal required version of reborncore in your mod.

This kind of issue is normally resolved by telling Forge (through mcmod.info I think) that you require version X of mod Y or higher, in which case it will be prompted explicitly to the user and not through a crash.
