### ISSUE TITLE
Message to install MCMP even though MCMP is not compatible with current TR version.

### ISSUE THREAD

**Issue by VanDerGroot** [TechReborn/TechReborn#506]
When selecting cables it says that MCMP should be installed for them to be placeable. The current version of MCMP only supports 1.7.10.

**Comment by covers1624** [comment]
You need mc multipart not forge multipart.

**Comment by VanDerGroot** [comment]
Oh, I see. This should be made obvious, and linked to, from somewhere.

**Comment by covers1624** [comment]
This one over here http://minecraft.curseforge.com/projects/mcmultipart?gameCategorySlug=mc-mods&projectID=239431

**Comment by modmuss50** [comment]
It is hopefully going to get merged into forge at somepoint
