### ISSUE TITLE
Make MCMP a dep

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#507]

**Comment by Prospector** [comment]
Is it listed as a dep?

**Comment by modmuss50** [comment]
No

**Comment by covers1624** [comment]
I'm going to do some reworking to CB's DepDownloader for JARRM to provide popups to the client to confirm if they want to download the mod automatically or from a link. Does that seem like an option for TR ?

**Comment by modmuss50** [comment]
Well we cannot download someone else's mod. We just need to link to it

**Comment by covers1624** [comment]
Probably best to have it as a required dependency then.

**Comment by Prospector** [comment]
Yeah, most people will have MCMP anyway, why not just require it?

**Comment by gigabit101** [comment]
Lets just make it a dep until its merged

**Comment by modmuss50** [comment]
This is not happening, its supposed to be in a few weeks
