### ISSUE TITLE
Black hud...

### ISSUE THREAD

**Issue by Pilad** [TechReborn/TechReborn#510]
I test last TechReborn-1.7.10-0.7.15.1096-universal
Black hud in all machines.
Fix please.

**Comment by modmuss50** [comment]
Update to 1.9

**Comment by Pilad** [comment]
Need version for 1.7.10. 
1.9 no thanks ((

**Comment by modmuss50** [comment]
We stopped working on 1.7 a long time ago. Sorry :(
