### ISSUE TITLE
Different cable texture north south, from east west texture. (1.9)

### ISSUE THREAD

**Issue by MechWarrior99** [TechReborn/TechReborn#512]
I don't think I need to explain anything else. But if I do let me know :)
![2016-04-07_20 57 59](https://cloud.githubusercontent.com/assets/8076495/14385886/6a4246bc-fd57-11e5-84d3-e0a9b332be83.png)

**Comment by Prospector** [comment]
Yeah, think that's modmuss' job :P

**Comment by Prospector** [comment]
Hmm, I haven't tested this, but are the up and down sides fine?

**Comment by modmuss50** [comment]
yes they are

**Comment by modmuss50** [comment]
@Rushmead broke it, but Im going to fix it

**Comment by Prospector** [comment]
Wanna come on the BGC discord channel for a sec modmuss?
