### ISSUE TITLE
Machines update there textures slowly (1.9)

### ISSUE THREAD

**Issue by MechWarrior99** [TechReborn/TechReborn#513]
If you have more than one item in a machine to be processed, when it is done processing one item the texture changes to the off texture then back to the on texture instead of it just staying on the on texture.

**Comment by modmuss50** [comment]
Yeah, I can have a look into this issue

**Comment by Prospector** [comment]
And you guys said this wasn't a real issue :P

**Comment by modmuss50** [comment]
its not, its a minor thing

**Comment by Prospector** [comment]
#378 was closed real quick :P

**Comment by MechWarrior99** [comment]
This bugs me vary much. :P
