### ISSUE TITLE
Releasing my textures as completely open?

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#515]
So I've been thinking, and I want to release all of my textures as open for anyone to use for any mod or anything, but I wanted to ask if you guys would be okay with me also releasing the TechReborn textures that I've done as public too? The reason I ask is if you'd think it would be weird if anyone used some of the textures that are in TechReborn for their own mod?

**Comment by modmuss50** [comment]
dont make an issue for this ask in irc

**Comment by Prospector** [comment]
Wanted to make sure it didn't get buried

**Comment by modmuss50** [comment]
Yeah I see what you mean, like I said on IRC they are your textures so it doesn't bother me. Might want to check with @gigabit101 first.

**Comment by Prospector** [comment]
Actually, I'm gonna go ahead and decide against it especially because I didn't make the base metallic backing for the machine texture, that was from the old IC2.
