### ISSUE TITLE
Wrenching Electric Furnace yields Electric Alloy Furnace

### ISSUE THREAD

**Issue by jesmores** [TechReborn/TechReborn#519]
#### Versions
- Minecraft 1.9
- Forge 12.16.0.1859
- TechReborn-1.9-1.0.4.143
- RebornCore-1.9-2.0.4.46
#### Repro
1. Place an Electric Furnace
2. Using the bronze wrench, try to wrench the Electric Furnace
#### Expected

Get Electric Furnace back
#### Actual

Got Electric _Alloy_ Furnace

**Comment by modmuss50** [comment]
Ive fixed this
