### ISSUE TITLE
Wrenching Batbox gives two Batboxes

### ISSUE THREAD

**Issue by jesmores** [TechReborn/TechReborn#520]
#### Versions
- Minecraft 1.9
- Forge 12.16.0.1859
- TechReborn-1.9-1.0.4.143
- RebornCore-1.9-2.0.4.46
#### Repro
1. Place Batbox
2. Wrench Batbox
#### Expected

Get Batbox
#### Actual

Get 2 Batboxen

**Comment by modmuss50** [comment]
Working as inteneded
