### ISSUE TITLE
1.9 Crash Forge 1863

### ISSUE THREAD

**Issue by TrikSteve** [TechReborn/TechReborn#521]
Pastebin Below
http://pastebin.com/raw/Jn9h319j

**Comment by modmuss50** [comment]
Try removing inventory tweaks?

**Comment by liach** [comment]
@TrikSteve InvTweaks did not update to latest forge which fry added encapsulation for all events. That's why `IllegalAccessError` happened.

**Comment by TrikSteve** [comment]
Gotcha. Looks like that cleared it up.  Didn't have any other mods error about inventory tweaks, but will wait till update.  Trying to build a pack.  Thanks
