### ISSUE TITLE
Startup Crash in any combination

### ISSUE THREAD

**Issue by Zkaface** [TechReborn/TechReborn#524]
Can not start the client (but server is running) with TechReborn and RebornCore.

This Error occurs:

Caught exception from techreborn
java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree

Doesn't matter, which version I use (I tried the last two versions of TechReborn and RebornCore ->1.9). Some problems, working together with other mods?

**Comment by modmuss50** [comment]
Remove inventory tweaks is an issue with them not updating to newer versions of forge
