### ISSUE TITLE
startup crash regarding org/hjson/JsonValue

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#525]
used version is .179 from jenkins

http://paste.ubuntu.com/15866071/

> Caused by: java.lang.NoClassDefFoundError: org/hjson/JsonValue
>     at techreborn.world.TechRebornWorldGen.load(TechRebornWorldGen.java:84)
>     at techreborn.Core.init(Core.java:130)

well, deleting config doesn't help, the ores.json screws up though

for some reasons cxlibrary is involved in a null pointer exception

> at cubex2.cxlibrary.CoreModTransformer.transform(CoreModTransformer.java:26)

@CubeX2

**Comment by modmuss50** [comment]
Update reborn core
