### ISSUE TITLE
Properly implement Magic Energy Absorber

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#526]
are you going to make the magic energy absorber like greg did in 2.78 so it can tap into ender crystals? if yes, maybe u should consider to make it harder to craft since u can do this in 1.9

http://abload.de/img/2016-04-16_12.00.38kru73.png

http://abload.de/img/2016-04-16_12.01.02jiu6j.png

make a blast proof containment for crystals and voila free power, seems a bit overpowered to me

overpowered because ender crystals can be placed on obsidian and not only bedrock

**Comment by modmuss50** [comment]
Does the magical energy absorber even work in TechReborn. I dont think it does.

**Comment by gigabit101** [comment]
It dose nothing not a issue also It will have recipes depending on the magic mod eg: Thaumcraft recipe/ Botania recipe and so on

**Comment by modmuss50** [comment]
Moved to: http://forum.techreborn.ovh/showthread.php?tid=8
