### ISSUE TITLE
[Feature Request] Any possibility of adding fluid pipes?

### ISSUE THREAD

**Issue by JCMais** [TechReborn/TechReborn#527]
Sorry if here is only for issues, I saw that you guys use YouTrack for features, but I didn't saw a link to it.

I'm asking for those blocks because right now it's getting complicated to get a mod with them working in Minecraft 1.9.

Pressure pipes works, but they don't have normal pipes. NeoTech is supposed to have them, but they are not working afaik, and having two tech mods is not what I would like to do.

**Comment by modmuss50** [comment]
1st thing, you track is broken, I need to remove that.

We will have to see @gigabit101 and anyone else what are you opinions?

**Comment by modmuss50** [comment]
if we do decide to add them, they will be MCMP only, and nothing too complicated.

**Comment by JCMais** [comment]
Thanks for the quick reply, anything working would be great. I will keep watching.

**Comment by gigabit101** [comment]
Again this is not a part of GTech this might be better suited in a add-on / another mod

**Comment by modmuss50** [comment]
If I get time I will do it. Time is rare at the moment.

**Comment by gigabit101** [comment]
yeah I have the same problem

**Comment by modmuss50** [comment]
Ive got 1st of 19 exams in 2 weeks. So it might happen after them.

**Comment by Prospector** [comment]
Well, I've never done anything like this but I mean I could see how the cables are done and maybe attempt something

**Comment by JCMais** [comment]
Was just taking a look at the commit story, and saw some work done on pipes, were they implemented?

**Comment by Prospector** [comment]
They kinda work, but they don't have an item model and their texture's pretty messed up

**Comment by modmuss50** [comment]
When I have more time I will polish them off
