### ISSUE TITLE
Problem using gradlew build

### ISSUE THREAD

**Issue by Ionaru** [TechReborn/TechReborn#528]
Hello guys,

I wanted to set up the workspace for the 1.7.10 branch of this mod but when I use the command 'gradlew build', this pops up:

:compileJava
FAILURE: Build failed with an exception.
What went wrong:
Could not resolve all dependencies for configuration ':compile'.
Unexpected state Evicted for parent node for dependency from mcp.mobius.waila:Waila:1.5.10_1.7.10(default) to codechicken:CodeChickenCore:1.7.10-1.0.7.47(default).
BUILD FAILED

What am I doing wrong?

**Comment by modmuss50** [comment]
Are you trying to build the mod or include it? If so link you build.gralde. And run with --stracktrace and give me the full ouput?

**Comment by Ionaru** [comment]
I'm trying to build it (I'd like to fix a few things in the 1.7.10 version)

http://pastebin.com/6UmJ5Asu

**Comment by gigabit101** [comment]
PR's are always welcome we will release new builds if people PR fix's in we just are not working on it are self

**Comment by modmuss50** [comment]
@Ionaru try running `gradlew setupDecompWorkspace build` also have you got it running in dev?

**Comment by modmuss50** [comment]
ok, I think its to do with chicken bones removing his maven. I will work on a fix. Just need to find the files

**Comment by Ionaru** [comment]
`gradlew setupDecompWorkspace build` didn't work either, same error.

**Comment by modmuss50** [comment]
Fixed in last 1.7 commit

**Comment by Ionaru** [comment]
Thank you guys so much!
