### ISSUE TITLE
runClient results in NoSuchMethodError: mantle...

### ISSUE THREAD

**Issue by Ionaru** [TechReborn/TechReborn#529]
Another problem (sorry...)
When executing runClient, the client will start and then crash with the following report:
http://pastebin.com/cN8mzY2Y
(The same with runServer)

In the full log, there's this line
`Skipping event FMLPreInitializationEvent and marking errored mod Natura since required dependency Mantle has errored`
But Mantle seems to be loaded

The dev environment is otherwise working and I'm able to build the mod and use the build in a seperate Minecraft instance.

**Comment by modmuss50** [comment]
This is an issue with mantle crashing. I dont think we need it so I will remove it.
