### ISSUE TITLE
Industrial Grinder multiblock issues

### ISSUE THREAD

**Issue by sironin** [TechReborn/TechReborn#530]
In the latest release 1.9 version the industrial grinder never detects its multiblock.

**Comment by vegeta897** [comment]
Industrial Grinder still not detecting multiblock in 1.0.6.197 for me.

**Comment by modmuss50** [comment]
Mind posting a screen shot of it?

**Comment by vegeta897** [comment]
Sorry for the delayed response.
- 3x3 Standard Machine Casings on top and bottom layers
- 3x3 Reinforced Machine Casings in the middle layer
- Water in the center block (second screenshot has 2 blocks removed to show this)
- Industrial Grinder attached to the side

![image](https://cloud.githubusercontent.com/assets/1789096/14839419/bc610172-0bf8-11e6-8426-7f2126c556a9.png)
![image](https://cloud.githubusercontent.com/assets/1789096/14839422/c247344e-0bf8-11e6-84dd-7c29b67a13d5.png)
![image](https://cloud.githubusercontent.com/assets/1789096/14839496/36358d88-0bf9-11e6-8eb0-44897a25b45b.png)

**Comment by modmuss50** [comment]
Ok thanks for that, I will take a look

**Comment by ghost** [comment]
Same thing happening in 0.7.18.111 for 1.7.10.
