### ISSUE TITLE
Transformer Duplication

### ISSUE THREAD

**Issue by ssblur** [TechReborn/TechReborn#532]
Upon breaking an LV transformer with a pickaxe, 2 LV Transformers are dropped.
Only other mod is Silent's Gems.

**Comment by modmuss50** [comment]
What version are you using?

**Comment by ssblur** [comment]
1.0.5.173 for Minecraft 1.9. Sorry about the lack of info, wrote it in a hurry.

**Comment by modmuss50** [comment]
ok thanks, I thought this was fixed. But it isnt.

**Comment by ssblur** [comment]
Thank you for your time!

**Comment by modmuss50** [comment]
Was this with a wrench or pick? I cannot seem to repoduce it in dev.

**Comment by ssblur** [comment]
This was with a pick axe from Silent's Gems.

**Comment by modmuss50** [comment]
Ok thanks, I will need to look into this more then

**Comment by Prospector** [comment]
I cannot reproduce either. Must be a silent's gems problem then.

**Comment by ssblur** [comment]
Bug is not replicable in the newest version for myself either, so apparently you fixed it. Thank you!

**Comment by Prospector** [comment]
Ah, awesome ;)
