### ISSUE TITLE
Allow charging of RF tools with EU in the chargebench (even when the mod's in EU mode)

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#533]
Had this idea when talking with a developer of a mod that adds RF-powered tools. It doesn't make sense to be able to charge EU items with RF, but if you could charge your RF tools in our chargebench I feel like it would be fine.

**Comment by modmuss50** [comment]
Moved to: http://forum.techreborn.ovh/showthread.php?tid=9
