### ISSUE TITLE
[1.9] Rubber logs do not rotate

### ISSUE THREAD

**Issue by Yulife** [TechReborn/TechReborn#536]
Would be fixable with JSONs I think (take a look at oak log jsons)

**Comment by modmuss50** [comment]
I think I can fix this without moving to json files, but it might move to json files for this anyway

**Comment by modmuss50** [comment]
Im not going to fix this becuase it would mess with the way the sap block states work. It might be fixed at somepoint but not soon

**Comment by Prospector** [comment]
This can be solved by having the rubber logs drop "decorative" rubber logs.

**Comment by Yulife** [comment]
Well just handle it in code and render it via JSON.

**Comment by Prospector** [comment]
Actually, this isn't terribly needed.

**Comment by ghost** [comment]
;-;
