### ISSUE TITLE
Move to JSON files

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#538]
This needs to be done at some point. Even if json destroyer exports them. At the moment RP devs cannot customise the blocks to their full ability.

Im not sure what the best practices on json files are. If people could post examples / ideas in the comments. This most likely wont happen until I have finished my exams, unless someone else wants to undertake the conversion.

**Comment by Yulife** [comment]
I think you have multiple machine side textures in your assets, for example Gregtech's and Tier 1's, those could use the same png in the model. I could post a json as an example soon.

**Comment by modmuss50** [comment]
Yeah, exmaples would be great as I have no idea how this works.

**Comment by Prospector** [comment]
I know a bit about this. Also that is intentional, so that resource pack authors could make different tier machines look different.

**Comment by Prospector** [comment]
Also does this mean json destroyer is gonna be discontinued or something

**Comment by modmuss50** [comment]
We will have to see.

**Comment by Yulife** [comment]
@ProfessorProspector ah right, that's kind of sensible. But with jsons we can define any texture on any side on any model anyway :)

**Comment by modmuss50** [comment]
Machines are done in the world, inventory blocks needs fixing. Then the rest of the blocks need moving over.

**Comment by Prospector** [comment]
Manual or generated? I can fix them if manual

**Comment by covers1624** [comment]
@modmuss50 when you register inventory variants it needs to be in preinit or they will not bake.

**Comment by modmuss50** [comment]
All machines are done. I will move the other blocks later
