### ISSUE TITLE
Industrial grinder can not store water

### ISSUE THREAD

**Issue by oldjunyi** [TechReborn/TechReborn#539]
Put a water bucket in it or right click with a water bucket will returns an empty bucket, but it still holds no water.
By the way, the empty cell can not pickup water. Is it a bug? (I am not familiar with GregTech)

**Comment by modmuss50** [comment]
Closing: could you reopen it here: http://forum.techreborn.ovh/forumdisplay.php?fid=6

**Comment by Dragon2488** [comment]
Fixed.
