### ISSUE TITLE
1.8.9 backport?

### ISSUE THREAD

**Issue by LuxusDarkangel** [TechReborn/TechReborn#541]
1.8.9 is still an active version and not everybody is porting to 1.9 yet. I heard those two versions aren't very different code wise, will it be possible to backport newer versions, at least for some months? (until there's a stable version)

**Comment by modmuss50** [comment]
No, not worth the effort. I did plan on it but I haven't got the time

**Comment by LuxusDarkangel** [comment]
Then it's not better to continue developing for 1.8.9 which is the "active" modded version instead of 1.9?

**Comment by Prospector** [comment]
1.9 is the latest version, and if someone doesn't want to update, that's their problem, not ours. They can use outdated and unsupported software, but we won't.

**Comment by gigabit101** [comment]
1.8.9 is not the "active" version anyway's where is forge...

**Comment by LuxusDarkangel** [comment]
Yeah, forge 1.8 has more than a year and it's starting to get mods now, so i don't think so...
Anyway, it's just a suggestion, good luck with the project.

**Comment by Prospector** [comment]
1.9 has been out for a month or two, and has 150 mods. 1.8 has been out for a year and a half, and there is 300 mods. 1.8 is dead. move on.

**Comment by modmuss50** [comment]
No, 1.9 is we're we are at.
