### ISSUE TITLE
Jenkin down?

### ISSUE THREAD

**Issue by xiaoschannel** [TechReborn/TechReborn#542]
I was looking for the update log, and got the below when accessing http://modmuss50.me:8080/job/TechReborn-1.9/

```
HTTP ERROR 404

Problem accessing /job/TechReborn-1.9/. Reason:

    Not Found
Powered by Jetty://
```

**Comment by modmuss50** [comment]
Find the builds here: modmuss50.me:8080 the urls changed when I updated to Jenkins 2

**Comment by modmuss50** [comment]
http://modmuss50.me:8080/job/TechReborn/job/TechReborn-1.9/
