### ISSUE TITLE
[ADDITION?] Fission reactor

### ISSUE THREAD

**Issue by w00tc0d3** [TechReborn/TechReborn#543]
Hello,

As IC2 hasn't been released for 1.9 yet, we are missing out on the standard reactor. Taking the extra isotopes TechReborn adds into account, it might be wise to add this functionality to TechReborn?

Please let me know what you think about it, I could try to implement/program it.

Thanks,
w00tc0d3

**Comment by Prospector** [comment]
If you would be willing to give it a go yourself, feel free to submit a PR. I'd say the more features that fit in-line with the mod's goal are awesome ;)

**Comment by w00tc0d3** [comment]
@ProfessorProspector Does it have to simulate IC2's reactor mechanics? Or is another approach preferred?

**Comment by modmuss50** [comment]
It can be based of the ic2 machanics. It doesnt need to be exact. Some level of thining about the logic would be nice.

**Comment by w00tc0d3** [comment]
@modmuss50 I was tinkering with the idea of designing a different system. Something along the lines of cooling reactor components with fluids which get converted to hot fluids with a certain ratio, and degrading fuel rods (which means that less heat will be radiated, and therefore, electric energy output will be reduced).

The hot fluids could power a turbine, which outputs shaft power. Which we could make compatible with RotaryCraft's shaft power.

**Comment by modmuss50** [comment]
Something diffrent might be a cool idea.

**Comment by w00tc0d3** [comment]
Well, after spending two hours on Wikipedia I have a few ideas which I'll work out in the coming days. The concepts (only a few easy components) are easy to grasp but the number of different configurations is immense.

What about the shaft power idea? I thought it might be a rather interesting idea, and it provides yet more different possible configurations.

**Comment by Prospector** [comment]
I like it. FYI we have an irc channel, #TechReborn on espernet

**Comment by w00tc0d3** [comment]
Just to let you know this is still a thing -- I spent some hours designing an API the other day. It might take a while to finish it, especially since I leave this weekend for approx. a week on school excursion.

**Comment by modmuss50** [comment]
Yeah, if your up for it great. If you need some help we can create a new branch for it and I can help you.

**Comment by modmuss50** [comment]
If you have irc we are on esper.net at #TechReborn or I can talk on discord: https://discord.gg/0tCDWb77cvetwm0e (IRC is the main place)

**Comment by modmuss50** [comment]
Moved to: http://forum.techreborn.ovh/showthread.php?tid=6
