### ISSUE TITLE
[1.9] NPE when generating a new world

### ISSUE THREAD

**Issue by w00tc0d3** [TechReborn/TechReborn#550]
Hello,

TechReborn crashes my world with a NPE when trying to generate the world. The problem is in this for-loop: https://github.com/TechReborn/TechReborn/blob/1.9/src/main/java/techreborn/world/TechRebornWorldGen.java#L222 . I'll try to debug it.

**Comment by modmuss50** [comment]
Mind posting the log?

**Comment by modmuss50** [comment]
Also mind posting ores.hjson from the config?

**Comment by modmuss50** [comment]
@ProfessorProspector removed some ores, and might not have removed them from the world gen

**Comment by w00tc0d3** [comment]
@modmuss50 Deleting the config folder worked. I recommend auto-regenerating the json files after the latest update. :)

**Comment by modmuss50** [comment]
I can add some checks to make sure the ores are valid, if not remove them. So I will leave this open

**Comment by Prospector** [comment]
Oh yeah, this is my bad. Removing ores is fun :P

**Comment by Prospector** [comment]
Hey @modmuss50, would it be possible to allow any block to be generated with the config?
