### ISSUE TITLE
[1.7.10] Iridium ore not spawing

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#551]
There is no irdium ore on the FTB one test server

**Comment by modmuss50** [comment]
Not going to fix, find it in chests or spawn it your self

**Comment by Prospector** [comment]
Does it spawn in 1.9?

**Comment by modmuss50** [comment]
I rewrote the ore spawning system so I asume it does. Might we worth checking

**Comment by Prospector** [comment]
Speaking of ore gen, did you see the curse comment regarding too frequent
ore gen?

**Comment by modmuss50** [comment]
No, I might change the defulat values
