### ISSUE TITLE
The rubber trees aren't recognized by Better Foliage

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#554]
I finded a very strange bug with TechReborn. The rubber tree isn't recognized by the mod Better Foliage. It has for result that the dense foliage and falling leaves effects don't applicate them to the tree.

**Comment by First-Follow** [comment]
You have to configure Better Foliage to recognize blocks added by mods. Its built in config contains blocks from several popular mods (like BoP), but not all of them.
