### ISSUE TITLE
[1.9]Iron Furnaces Don't Work As Expected

### ISSUE THREAD

**Issue by First-Follow** [TechReborn/TechReborn#556]
Iron furnaces are neither faster nor more efficient than normal ones. By putting a full stack of smelt-able material and 8 coal into both an iron furnace and a normal one then allowing them to finish one can see that both use up all of their fuel and finish simultaneously. On top of that, the iron furnace will also occasionally only smelt 63 of the 64 items put in.

**Comment by modmuss50** [comment]
@gigabit101 whats the intended behaviour?

**Comment by gigabit101** [comment]
It should be more efficient by half and slightly faster just forgot to add
that after getting it working

**Comment by Prospector** [comment]
It's funny, because I was always told it was more efficient and faster, but I tested it myself on 1.4.7 and it was identical to the normal furnace.

**Comment by mystise** [comment]
If I'm remembering correctly, it should smelt 10 items per coal. So it's not much more efficient, just slightly.
