### ISSUE TITLE
[Query] Invar recipes not Oredict

### ISSUE THREAD

**Issue by b0bst3r** [TechReborn/TechReborn#558]
Take the Thermal Generator for instance, question is, is this intended so you have to make the TechReborn alloy furnace or not?

It's going to be a pain in the ass with large mod packs to have this, can I suggest if it is intended that you make a different alloy which isn't common to other mods?

If it's not intentional then fair enougn :)

**Comment by Prospector** [comment]
I'm pretty sure a lot of recipes aren't ore dict properly, like circuits should also be ore dict (pretty much everything could be ore dict if we wanted to). Anytime I see one I try to fix it real quick.

**Comment by modmuss50** [comment]
Quick question what minecraft version?

**Comment by b0bst3r** [comment]
1.9

**Comment by Prospector** [comment]
Oops I fixed this last night
