### ISSUE TITLE
[1.9] Missing textures / item name changes when updating to latest versions

### ISSUE THREAD

**Issue by dirtyfargo** [TechReborn/TechReborn#559]
Version: 1.9-1.0.6.225
RebornCore: 1.9-2.1.0.64
Forge: 12.16.1.1892

Description: When I update past 1.9-1.0.6.208 on the jenkins builds:
- All of the tiny dusts have missing textures.
- Many of my dusts have been changed to a different type of dust, mostly Almandine.
- A few ores are gone, but I am told this is intended.

Examples:
Before updating:
![2016-05-08_08 44 12](https://cloud.githubusercontent.com/assets/10457528/15098807/96cde6e0-14fa-11e6-86b6-c3ee38fc753d.png)
After:
![2016-05-08_08 52 19](https://cloud.githubusercontent.com/assets/10457528/15098804/8686d9e0-14fa-11e6-84bf-949f7fd1184a.png)

Before:
![2016-05-08_08 44 04](https://cloud.githubusercontent.com/assets/10457528/15098813/c719db10-14fa-11e6-91e9-499eb454336a.png)
After:
![2016-05-08_08 52 16](https://cloud.githubusercontent.com/assets/10457528/15098817/d0d084ec-14fa-11e6-821b-85a7e31c7ce2.png)

**Comment by Prospector** [comment]
Yeah, I removed a lot of stuff and moved stuff around. I would recommend not updating. The next release (1.1) will likely break worlds.

Also, may I ask what enchantments are on that drill? I'm not sure if I added this or not, but unbreaking should lower energy usage.

**Comment by dirtyfargo** [comment]
Ah alright, I'll count on starting a new world at that point then, thanks for the heads up =)
And it's got Efficiency V Fortune III, I didn't know that about Unbreaking so I will have to add it to the drill thx for the tip :)

**Comment by Prospector** [comment]
Ah, that's a nice drill ;)

**Comment by dirtyfargo** [comment]
hehe it sure is!
