### ISSUE TITLE
Bauxite ore not ore dict with IE

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#562]
Thanks for reporting an issue! However, before you report an issue, please read the following:
- We will not backport to an old version of minecraft. Do not suggest this
- Make sure you're using the latest version of TechReborn, RebornCore, and Forge before reporting a bug!
- Don't argue with any TechReborn developers. What they say goes. Feel free to suggest a way to implement something, but if they say no, don't push it.
  
  Make sure to delete all this text before you report your issue.

**Comment by Prospector** [comment]
Nice issue template lol

**Comment by modmuss50** [comment]
Was this from ftb one?

**Comment by gigabit101** [comment]
yea

**Comment by modmuss50** [comment]
I think they are doing something funny with the bauxite, I will check this

**Comment by modmuss50** [comment]
im 90% sure its not supposed to be, in FTB Inventions ie bauxtie has been renamed.
