### ISSUE TITLE
Power charge issues in SMP

### ISSUE THREAD

**Issue by BakermanLP** [TechReborn/TechReborn#565]
Hello,

Used versions:
- forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
- industrialcraft-2-2.2.821-experimental.jar
- RebornCore-1.1.0.15-universal.jar
- TechReborn-1.7.10-0.7.16.1106-universal.jar

Yesterday we wanted to show some cool features of TechReborn. We tried to build up the fusion reactor  with the above versions. To charge the fusion reactor we build a AESU. First we tried to charge the AESU, which was attached to a glass cable (IC2). The gui showed first a little charge, then discharge, then charge, then discharge (+xxx EU, -xxx EU). The cable was connected to a input side, the side with the dots was empty.

The same happened later with the fusion reactor. We also tried a LESU with the same result.

This setup works in single player, but on server play there is the above error.

Configs on client and server are identically.

If added some gui screenshots and a test build, that doesn't work

Can you help us?

Modpack informations are here: https://github.com/BakermanLP/ProjectRETv8

Thanks

Michael (aka BakermanLP)

Screenshots:
Testbuild:
![build_small](https://cloud.githubusercontent.com/assets/3873443/15171511/6afef30e-174f-11e6-977b-fbb72453db36.png)

Gui screenshots:
![2016-05-11_07 49 58_small](https://cloud.githubusercontent.com/assets/3873443/15171522/79138c3e-174f-11e6-82f4-9404820ae463.png)
![2016-05-11_07 49 59_small](https://cloud.githubusercontent.com/assets/3873443/15171526/7d282dfc-174f-11e6-8a0b-acc0f056f18b.png)

**Comment by modmuss50** [comment]
I will take a look at this, this is stange

**Comment by BakermanLP** [comment]
Oh yeah, that wasn't only strange for me ... that was life on twitch :)

**Comment by BakermanLP** [comment]
OK, if you want to see the problem in "moving pictures" then you can look at this (it is in german, but I think that doesn't matter):
https://www.twitch.tv/bakerman_lp/v/65673977
Timecodes:
1:40:00 - 1:42:00 build of the fusion reactor
1:43:45 - 1:47:15 aesu charging problems
2:22:00 - 2:23:00 fusion reactor charging problem

**Comment by modmuss50** [comment]
Ok thanks for that. I will take a look.

**Comment by praetoras** [comment]
I can confirm this behavior still exists on server.

MC: 1.9.4
TechReborn: 1.3.2.120
RebornCore: 2.5.4.47
Forge: 12.17.0.1965

I was attempting to build a fusion reactor, and when trying to use the IDSU discovered I couldn't make it charge. When attempting to use other ESUs I found the problem where the ESUs would go into negative values (along with the Fusion Reactor) and would not charge properly. I can also confirm the AESU issue, as I noticed the same thing in attempting to use the AESU.

**Comment by Dragon2488** [comment]
Possibly fixed by #683

**Comment by modmuss50** [comment]
I doubt it as it is a syncing issue.

**Comment by Dragon2488** [comment]
Last RebornCore pull request also fixes energy syncing :)
