### ISSUE TITLE
1.7.10 LESU Charging issue!

### ISSUE THREAD

**Issue by BarbusCraft** [TechReborn/TechReborn#566]
How do I charge stuff in the LESU? Can't seem to charge it, And GUI texture is broken. It shows the armor slots but armor wont appear there, and there is no spot to put your items in, I SHIFT click the item and it gets put on the GUI but wont charge.... (1.7.10-0.7.16.1106-universal)

https://cloud.githubusercontent.com/assets/19311243/15189743/afc943a6-17ac-11e6-8b45-d2ddc5857d1c.png

**Comment by modmuss50** [comment]
1.7.10 is done now, sorry it did not get fixed
