### ISSUE TITLE
[1.9] Energy Transfer

### ISSUE THREAD

**Issue by DarkIceXD** [TechReborn/TechReborn#567]
Hello,
while playing around with the latest TechReborn i noticed that when i place a MFSU, MFE or Batbox directly next to a Maschine e.g. Grinder no Energy Transfer occurs (the output is on the right side) placing an cable in between solves it. The next Problem i ran into was Nickel cant be found or crafted except Scrapbox.
Hope ypu can help me.
Greetings

**Comment by modmuss50** [comment]
Make a new issue for the crafting recipe, this is how its supposed to work
