### ISSUE TITLE
Nickel is impossible to obtain

### ISSUE THREAD

**Issue by DarkIceXD** [TechReborn/TechReborn#568]
Hello,
lastly i ran into a problem i cant craft the Thermal Generator because there is no way to obtain nickel (except for scrap boxes).
**forge-1.9-12.16.1.1901
RebornCore-1.9-2.1.0.53-universal
TechReborn-1.9-1.0.6.197-universal**
Greetings

**Comment by modmuss50** [comment]
Do you have ic2?

**Comment by modmuss50** [comment]
oh wait 1.9

**Comment by modmuss50** [comment]
@gigabit101 should it be a ore?

**Comment by Prospector** [comment]
I think it should be IMO

**Comment by ghost** [comment]
An ore would make it extremely simlple, but at the same time grinding iron in a pulveriser or macerator was really satisfying. Could the macerator drop Iron dust and nickel dust ?

**Comment by Prospector** [comment]
A second output for the grinder would be interesting

**Comment by ghost** [comment]
it could open up to a double reward for a lot of other ores

**Comment by SophiaAska** [comment]
I was able to obtain one "Small pile of Nickle Dust" with the Industrial Centrifuge when inputting Copper Dust.

So you need 4 Copper Dust for 1 Nickle Dust.
