### ISSUE TITLE
Cloak Device Model?

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#569]
I remember playing with the cloaking device back in the old GT , would it be possible when you are not invisible that it displays somekind of cloak :P That would make it even cooler to wear XD.

**Comment by modmuss50** [comment]
We could add a hot key to disable it and show a cloak. BTW all features are now handled on our wiki: http://forum.techreborn.ovh/forumdisplay.php?fid=6 so could you please recreate it there.
