### ISSUE TITLE
Fix the recipes button 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#57]
Should we keep the recipes button or move to using the progress bar like other mods ??

**Comment by joflashstudios** [comment]
If we do, it needs work. For instance, even if it's displaying it doesn't fit on the electrolyzer UI. Perhaps it shouldn't be a traditional button, but some other label that says Recipes.

If we don't want to put in the work to re-envision it, we should just use the progress bar. It's standard and widely accepted.

**Comment by gigabit101** [comment]
yeah I think moving it to the progress bar will be the best way

**Comment by TheQuantumGeneral** [comment]
Progress bar is most intuitive since most all mods use it, if not have you considered just off the edge of the GUI like Forestry and Thermal Expansions info tabs?

**Comment by joflashstudios** [comment]
@TheQuantumGeneral this is the current system: http://imgur.com/4IWylqU

**Comment by TheQuantumGeneral** [comment]
Yeah, when I first tried Tech Reborn I still clicked on the bar before I tried clicking the button, its just grown to be such a standardized thing. 

There is also the book mark style buttons used in a few other mods, in the case that you wanted to display additional information it could extend to that as well

eg.

http://i.imgur.com/qPsKXjK.png

http://vignette1.wikia.nocookie.net/technicpack/images/c/cc/TE_GUI_1.png/revision/latest?cb=20120829180149

**Comment by joflashstudios** [comment]
In any case, it should be one or the other. Currently I can't lookup all the electrolyzer recipes, which makes adding and verifying recipes a pain, especially since I can't lookup universal fluid cell recipes because NEI thinks they're all the same. Have I mentioned I really don't like universal fluid cells?

**Comment by joflashstudios** [comment]
Currently I can't lookup all the electrolyzer recipes, which makes adding and verifying recipes a pain. A lot of the other recipe buttons are in the wrong place. (not over the arrow)

**Comment by gigabit101** [comment]
this is my derp I will fix later
