### ISSUE TITLE
[1.9] Crash when loading new chunks

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#571]
this crash happened when generating new chunks

used version is TRb_253 from jenkins and RbC_63 also from jenkins

http://paste.ubuntu.com/16398302/

**Comment by modmuss50** [comment]
Delete ores.json

**Comment by Prospector** [comment]
We should leave sone useful info in the log on these crashes

**Comment by modmuss50** [comment]
No we need to fix it

**Comment by Prospector** [comment]
Well that too :P

**Comment by modmuss50** [comment]
Was this with any other mods?

**Comment by modmuss50** [comment]
Cannot reporduce

**Comment by Sailren** [comment]
for now its working good, we will see
