### ISSUE TITLE
Matter Fabricator not working

### ISSUE THREAD

**Issue by Jackol0** [TechReborn/TechReborn#572]
The Matter Fabricator doesn't work, I fed it some scraps and it just ate it without doing anything.

I'm on the latest version of TechReborn on 1.7.10 and latest forge, etc.

**Comment by modmuss50** [comment]
is it using power, it should use a lot of it

**Comment by Jackol0** [comment]
Well I do have around 4096 eu/t feeding into the machine, and it still seems to do nothing.

**Comment by modmuss50** [comment]
ok I will look into it, thanks for the report

**Comment by modmuss50** [comment]
its better now
