### ISSUE TITLE
Thin cables look odd when facing north/south

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#573]
![2016-05-14_22 44 33](https://cloud.githubusercontent.com/assets/6166773/15272254/8841832c-1a25-11e6-8dee-3029135fe24e.png)

**Comment by covers1624** [comment]
Texture needs to be rotated.

**Comment by modmuss50** [comment]
I did fix this :/

**Comment by Prospector** [comment]
That was another issue, this one just needs to be rotated I think. It's not noticeable on the thick cables, but on glass fibre it's noticable

**Comment by modmuss50** [comment]
![kkw7oa6](https://cloud.githubusercontent.com/assets/4324090/15291850/f575c5a4-1b77-11e6-8181-347b2672b86a.png)

I have almost got it working

**Comment by modmuss50** [comment]
Its just a bit off on the north and south sides, not sure why though.
