### ISSUE TITLE
[1.9] Client crash at startup

### ISSUE THREAD

**Issue by kwpugh** [TechReborn/TechReborn#575]
Forge: 1906
Mods: RebornCore-1.9-2.2.0.77-universal.jar
TechReborn-1.9-1.0.6.197-universal.jar

Crash report: http://pastebin.com/raw/ZBThkx4P

**Comment by modmuss50** [comment]
Update TechReborn to the beta version

**Comment by modmuss50** [comment]
I have removed the beta tag from the version on curse to prevent this for some people
