### ISSUE TITLE
Can someone explain the fluid component of electrolyzer recipes?

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn#58]
Gregtech Industrial Electrolyzers didn't use fluids at all.

**Comment by gigabit101** [comment]
I just went by the gui that tnt gave us

**Comment by joflashstudios** [comment]
I mean, fundamentally Electrolization happens in solutions, not to just dusts. So it might make sense that the recipes that don't include a fluid solvent require water be added. http://encyclopedia2.thefreedictionary.com/Electrolyzation

**Comment by joflashstudios** [comment]
@Tntrololol, what were your plans for this?

**Comment by gigabit101** [comment]
I will remove the fluid tank later but will need a new gui
