### ISSUE TITLE
[Major Issue, possible performance fix?] Ores aren't solid like vanilla ores (1.9)

### ISSUE THREAD

**Issue by jawsawn** [TechReborn/TechReborn#580]
So I flew around with the spectator mode using latest tech reborn 1.1.0 258 and latest core When I noticed that ores are totally visible with it. Normally vanilla ores or any other blocks doesn't act like that! They voxel with the world itself. But those act more like redstone or glowstone blocks. I have no idea if this would cause chunk issues or cause lag (not having that much). But just wanted to put it right there.

Pictures of it with night vision https://gyazo.com/bfe3ab7a850163477d9f59cd138a8564

**Comment by modmuss50** [comment]
1.9?

**Comment by jawsawn** [comment]
Oh derp, forgot to tell that. Yep its 1.9

**Comment by modmuss50** [comment]
This is json destroyer, this will be fixed at some point. its not a major issue
