### ISSUE TITLE
IC2 in 1.9 Questions

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#581]
When ic2 comes out for 1.9(Very soon) how are we going to handle it. Are we going to disable our blocks and use the ic2 ones instead? It is going to have full support im just not sure how we want to handle it?

EDIT:

Our cables will use the ic2 power net, and work like they did in 1.7

**Comment by Prospector** [comment]
Honestly, I think standalone should be our main focus, and ic2 support is less important. Most people will probably use it standalone anyway. I think what we should do is have an "ItemBank" where depending on which mods are installed, it will prioritize using those equivalent items from those mods over the TR ones. I believe something like this is already implemented but I have no idea how it works exactly.
