### ISSUE TITLE
Reborn Core Crash

### ISSUE THREAD

**Issue by Armagedon13** [TechReborn/TechReborn#584]
here the paste bin: http://pastebin.com/mJdbfLmR

Reborn core version: 1.9-2.3.2.84-universal
TechReborn version: 1.9-1.1.1.267-universal

**Comment by Prospector** [comment]
1. RebornCore crashes go on the RebornCore repo, not the TR repo
2. Second of all, this looks like a conflict between InventoryTweaks and Steam Advantage, this has nothing to do with us at all.

**Comment by modmuss50** [comment]
Remove inventory tweaks, its not updated
