### ISSUE TITLE
(thaumcraft compatibility) cinnabar burnt into quicksilver

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#586]
I just make a little suggestion to give the possibility to burn the techreborn cinnabar into quicksilver like the thaumcraft cinnabar when thaumcraft is installed.

**Comment by Prospector** [comment]
Any idea if Thaumcraft cinnabar uses ore dict, or if the recipe uses ore dict?

**Comment by 0Navis0** [comment]
The thaumcraft cinnabar uses the ore dict, not sure for the recipe.

**Comment by modmuss50** [comment]
Will wait for 1.9.4 thaumcraft
