### ISSUE TITLE
InvTweaks Compatability Issue

### ISSUE THREAD

**Issue by MazeusXenon** [TechReborn/TechReborn#588]
When using the latest versions of TechReborn (1.1.1.267) and Reborn Core(2.3.2.84), and also including the latest release of InvTweaks (1.61-dev-49), I am getting a [client crash](http://pastebin.com/h2rcxVLM). 

According to the folks at InvTweaks, it's because there is a "broken" recipe in TechReborn (not 100% sure what they mean by that). I was able to use an older version of TechReborn (1.0.6.197) and Reborn Core (2.1.0.53) and a "dev" version linked out and it works from their [CurseForge](http://minecraft.curseforge.com/projects/inventory-tweaks) page.

If you know of this issue then I apologize for the duplicate but I do love this mod already and live by InvTweaks and would like to the two to live happily together. And of course, as their mod is techincially only Alpha for now, I am sure this is more on them than you, but if there is anything on your end that can be fixed, I'd certainly appreciate it!

**Comment by modmuss50** [comment]
OK I will leave this open as it is the 100x time this has been opened and I will track down the issue

**Comment by modmuss50** [comment]
I think my old mod will aid me in tracking down the broken recipe if there is one

**Comment by modmuss50** [comment]
@MazeusXenon could you try using this version of TechReborn? http://modmuss50.me:8080/job/TechReborn/job/TechReborn-1.9/277/

**Comment by MazeusXenon** [comment]
Well... it seems to work but now it is blowing up on Reborn Core (2.3.2.84) ... and of course, I can't actually test TechReborn without the core... right?

**Comment by modmuss50** [comment]
you will need this as well: http://modmuss50.me:8080/job/RebornCore/job/RebornCore-1.9/

**Comment by MazeusXenon** [comment]
Yay! it worked! Well, it did when I only loaded InvTweaks, RebornCore, and TechReborn.... and I didn't create a world, but the client loaded, so that is so much farther than I ever got before.

Now, if I can just track down all the other mods that InvTweaks is having issues with, I'll be all set.

Thanks!

**Comment by modmuss50** [comment]
Thanks for helping me fix this issue, In the end it was a number of different issues that needed fixing on both sides. 

New curse version incoming.

**Comment by MazeusXenon** [comment]
Glad to help! Now to go pester the InvTweak folks... :)
