### ISSUE TITLE
Crash when loading BlockPlayerDetector

### ISSUE THREAD

**Issue by BeyJohn** [TechReborn/TechReborn#589]
My game crashes on load and looking at the crash log
[crash.txt](https://github.com/TechReborn/TechReborn/files/271579/crash.txt)
it seems that the Player Detector is what is crashing.
EDIT - I forgot to mention I am using the latest version in Minecraft 1.9.0 as of now.

I looked through your code to find the problem and noticed this
[https://github.com/TechReborn/TechReborn/blob/1.9/src/main/java/techreborn/blocks/BlockPlayerDetector.java](url)
        public BlockPlayerDetector()
    {
        **super(true);**
        setUnlocalizedName("techreborn.playerDetector");
        setCreativeTab(TechRebornCreativeTab.instance);
        setHardness(2f);
        this.setDefaultState(this.getDefaultState().withProperty(METADATA, 0));
    }
I don't think the bolded text was intentional and I would like to see this issue resolved as quickly and efficiently as it can be. I hope I was helpful. Thank you for taking your time to read this.

**Comment by modmuss50** [comment]
I forgot to push the latest version of RebornCore to curse, that has now been submitted.
