### ISSUE TITLE
Emc Values

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#59]
Rubber 32
Steel 256 + coal
Coal dust 32
Carbon Plate 256
Diamond Dust 8192
Energium Dust makes 9 so 32896 / 9
Energy Crystal 32896 
Surfer 32
Lead dust 256

**Comment by Carbon-Ghost** [comment]
Well here is my opinion : 

Steel : Should be 256 + coal EMC value or, better, if mekanism installed, the value of 10 units of carbon in a metallugic infuser ( 1 / 10 of a charcoal if I am correct so Charcoal EMC/10 ) + EMC of iron
It's important to be precise to avoid loop, but the better would be to NOT add an EMC value to this one, as value will strongly varie from one mod to another, so loop will exist. 

Energium dust ? You mean IC2 one right ? Well, if you add a ruby recipe for this one, then or we should use the lowest emc value to avoid positive emc loop,  or we also should avoid EMC for this one. 

Also, if you add EMC, please make it for both EE3 and Project E :)

**Comment by modmuss50** [comment]
ee3's dynemc stops loops, so it wont matter. Also im not familiar with what project e is.

Im not sure what the steel value should be

**Comment by Carbon-Ghost** [comment]
Again, better to NOT have an EMC value for steel for another reason other than loops ( which CAN happen in both EE3 and Project E even though they have an anti loop system, both of them, which is basically a rewrite of EE2 with some new stuff :D ) as it will break a bit TechReborn tiers and gameplay ;)
I have nothing against non processed materials having EMC ( like chrome, tungsten... etc.. except iridium ) but processed materials shouldn't have an emc value for the sake of gameplay so people use machines ( ours or others ) to make steel ;)

**Comment by gigabit101** [comment]
@Carbon-Ghost that is the users choice and for the use who dosnt wont it http://puu.sh/iEDqz/603515b3e3.png Bottom line

**Comment by Carbon-Ghost** [comment]
Then disable steel by default ? 512 is way to high, even in techReborn, as it's only 1 iron + 1 coal in BF.

**Comment by joflashstudios** [comment]
Frankly @Carbon-Ghost, I would be hesitant to even give things like chrome and tungsten EMC values. There is no chrome ore, it can only be obtained through advanced industrial processing of other ores and resources. And tungsten, at least in ingot form, requires highly advanced machinery to smelt. Adding EMCs for either of those allows people to skip massive amounts of TechReborn gameplay.

**Comment by gigabit101** [comment]
All the emc values we set will be in the config to disable its not something Im worried about

**Comment by Carbon-Ghost** [comment]
Yeah you're right, but I was giving exemples, then it's the same case scenerario with steel :c

**Comment by gigabit101** [comment]
aluminum 256
electrum gold + 2052
bronze 160
lapis dust  864
re-battery, broken becuase of two types, need to work out the emc for one 608
silver dust 1024
tin dust 256

**Comment by Carbon-Ghost** [comment]
Well, bronze is subject to change, as copper might be 256, so it might be 256.
