### ISSUE TITLE
Crash with TechRebornV 1.9 - 1.1.2.278

### ISSUE THREAD

**Issue by RebeccaRedstone** [TechReborn/TechReborn#590]
Not sure what is going on or if it's Tinker's Construct? Here is the crash report. 

[crash-2016-05-19_17.37.58-client.txt](https://github.com/TechReborn/TechReborn/files/273523/crash-2016-05-19_17.37.58-client.txt)

**Comment by RebeccaRedstone** [comment]
I just updated TConstruct and Mantle - as I was one version behind - and I have a new, but pretty much the same, crash report. :)

[crash-2016-05-19_18.01.35-client.txt](https://github.com/TechReborn/TechReborn/files/273554/crash-2016-05-19_18.01.35-client.txt)

**Comment by gigabit101** [comment]
@ProfessorProspector

**Comment by modmuss50** [comment]
No I'm not sure it is him
