### ISSUE TITLE
1.8.9 IC2 Support is broken

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#591]
And I've been told the quarry recipe change config doesn't work

**Comment by modmuss50** [comment]
I hope the 1.9 version will be out soon and then I will do proper support. The reason the 1.8 version is so broken is we moved on from 1.8 and it would be hard to back port the fixes we did.

**Comment by Prospector** [comment]
Indeed

**Comment by modmuss50** [comment]
This has been fixed in the latest version, I am going to be porting the 1.9 branch back to 1.8
