### ISSUE TITLE
1.7.10: Electric Crafting Table broken

### ISSUE THREAD

**Issue by AKTheKnight** [TechReborn/TechReborn#592]
No gui and doesn't connect to power
# BlameRush

**Comment by Rushmead** [comment]
I blame Modmuss personally as he was the last person to commit to it. https://github.com/TechReborn/TechReborn/blob/1.7.10/src/main/java/techreborn/blocks/BlockElectricCraftingTable.java NO TE AT ALL. There. Fix it.

**Comment by modmuss50** [comment]
If you want this open in the forum
