### ISSUE TITLE
MultipartCable bug 1.9

### ISSUE THREAD

**Issue by xannor** [TechReborn/TechReborn#596]
While investigating issue #564 I think I found a related bug:

Shouldnt this line:
https://github.com/TechReborn/TechReborn/blob/1.9/src/main/java/techreborn/parts/powerCables/CableMultipart.java#L269

either pass mergeWith into the merge function of the network, or call merge on mergeWith passing in the getNetwork() result.

I noticed this because I am having an issue in 1.9 where my Extracter stopped pulling power on a cable change.

**Comment by modmuss50** [comment]
Thanks for spotting that :)
