### ISSUE TITLE
Player detectors use a ridiculous amount of power

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#597]
You need 5 generators running at once to make it work properly https://gfycat.com/HonoredNippyBlackcrappie

**Comment by modmuss50** [comment]
Generators are going to get a buff, and they use 50eu/t atm

**Comment by Prospector** [comment]
Actually, the generators generate fine, but they only store 100 EU...

**Comment by modmuss50** [comment]
When I buff then they will store 10k and linking to #564 the generators will make 20eu. I may make the player detectors use 20

**Comment by Prospector** [comment]
Do the player detectors constantly drain or only when there is a player in range? I feel like they should only drain if active, and a single generator should easily be able to power a few detectors IMO

**Comment by modmuss50** [comment]
they constantly drain, and I think they should use a good amount of power

**Comment by Prospector** [comment]
I mean honestly a player detector is just a slightly better pressure plate, which just costs 2 planks and no power :P

**Comment by modmuss50** [comment]
but this one, searches a radius of 16 blocks for a player, not just on top of it

**Comment by modmuss50** [comment]
They now use 5 times less
