### ISSUE TITLE
[1.7.10] IC2 fluid/solid canning machine drains beryllium

### ISSUE THREAD

**Issue by Xireka** [TechReborn/TechReborn#598]
I was trying to make Overclockers for IC2 needing 10k coolant cells.

Sadly whatever I try draining from a cell/bucket/unicell into the machines tanks by using it's "drain from cell" function results in BERYLLIUM.

No idea how water or distilled water turns to beryllium so quickly, but Techreborn has beryllium so I'm mentioning this here.

Pretty much something is broken breaking an entire recipe chain.

**Comment by modmuss50** [comment]
This is not going to be fixed due to 1.7 being old. Sorry
