### ISSUE TITLE
1.9.4-1.2.1.51 putting itself in the config files

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/TechReborn#599]
So, was trying to get a pack approved on Curse modpacks and they kept rejecting it it because all of sudden your mod is placing copies of itself in the config directory.

http://i.imgur.com/tjTBuiF.png

**Comment by modmuss50** [comment]
that is the manual that is downloaded, I will change the behaviour of this to fix this issue.

**Comment by modmuss50** [comment]
Please delete that file and folder in the config, I have talked to curse about this so they know that it is normal on the older versions of the mod.
