### ISSUE TITLE
Machine Recipes Need Work

### ISSUE THREAD

**Issue by Tntrololol** [TechReborn/TechReborn#6]
Custom machine recipes still need work. They currently do not show their input ItemStack stack size in NEI and dual inputs are not reversible for machines that allow it. Also, as demonstrated by the alloy smelter, not all recipes work properly. Some only smelt with certain items registered with a particular ore dictionary entry and others just don't process at all no matter what ore dictionary varient you use.

*Currently there are alloy smelter recipes in place for cross mod integration. They are currently set to register only when and if their output is registered with the ore dictionary.

**Comment by modmuss50** [comment]
We have a repo just for suggestions: https://github.com/TechReborn/TechReborn_TODO/issues

It does not matter this time, just for the next ones.

**Comment by Tntrololol** [comment]
I don't think this belongs in the "suggestion" repo seeing as how it involves a significant issue and all aforementioned features are already planned.

**Comment by modmuss50** [comment]
Fixed, input stack size
Fixed dual inputs are not reversible.

What mods do i need to test the alloy smelter recipes? and an example recipe would be useful
