### ISSUE TITLE
Opening Idsu gui kicks clients from server

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#60]

**Comment by modmuss50** [comment]
It would be easier to fix if I didn't have the channels, and just make one channel for each player? (Like in GT)

**Comment by TheQuantumGeneral** [comment]
Gregtech way makes the most sense unless there is a way to lock frequencies so people can't steal your power.

**Comment by modmuss50** [comment]
Ok, if I use the greg tech way its going to be easy to fix. We can add back the channels at a later date.
