### ISSUE TITLE
TechReborn Computer Cube GUI Bug 

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#600]
The TechReborn Computer Cube has two GUI bugs: firstly, if you click the config button and return to the original screen, the background disappears. Secondly, some text has a nasty habit of running off-screen. That is all, thanks for the great mod! Also, I'd be willing to sit down and write the text for it if you would like.

**Comment by modmuss50** [comment]
What version of minecraft are you using?

**Comment by modmuss50** [comment]
We will get a proper wiki soon, so this wont be an issue
