### ISSUE TITLE
(suggestion) rubber slabs, stairs, fences and fence gates

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#602]
Everything is in the title. ;)

**Comment by modmuss50** [comment]
I dont see why not, what about togglable pressure plates? Step on it it turn on, get off it says on until you get back on it.

**Comment by 0Navis0** [comment]
Hm why not, maybe a rubber door and trapdoor too ;)

**Comment by Prospector** [comment]
Maybe not trapdoor--to keep it consistant? None of the vanilla woods have trapdoors. Or we could add trapdoors for the vanilla woods.

**Comment by 0Navis0** [comment]
Quark already adds trapdoors for each wood. ;)

**Comment by ghost** [comment]
shouldn't this be transfered to the forum ?

**Comment by modmuss50** [comment]
Yeah, but I need to fix that

**Comment by modmuss50** [comment]
not needed, its just more bloat. May be added in another mod. I can add support if there is another mod that adds fences and things for all woods.

**Comment by 0Navis0** [comment]
Like building bricks

**Comment by Prospector** [comment]
Vanilla adds fences for all woods

**Comment by modmuss50** [comment]
Someone else can add it then

**Comment by GirafiStudios** [comment]
Rubber is not a normal wood kind though. Wouldn't make sense to me to add fences etc. for that.

**Comment by Prospector** [comment]
With the new textures, the planks look awesome. Would kinda be a shame to not really use them for decorative purposes. I'll add them, I added the iron fences anyway

**Comment by GirafiStudios** [comment]
_sigh_ Okay then!

**Comment by Prospector** [comment]
Only one problem, slabs are fucking hard to make. I still don't understand how to do it. I can do all the rest easy though.

**Comment by 0Navis0** [comment]
I think you must use the metada, each one for each position.

**Comment by modmuss50** [comment]
Too much bloat

**Comment by 0Navis0** [comment]
What do you mean ?

**Comment by modmuss50** [comment]
Not needed, if you want it, make a mod that adds it for every wood type.

**Comment by 0Navis0** [comment]
It's such a shame you don't include it, it would have been awesome if had did it.
