### ISSUE TITLE
1.9.4 Cells don't work!

### ISSUE THREAD

**Issue by Drew1749** [TechReborn/TechReborn#603]
I was fiddling with the 1.9.4 version of the mod and due to no pipe mods being available yet I decided to use lava cells in order to fill the thermal generator. To my disappointment the lava cells don't work. I can't right click the generator with them and I can't place them inside the GUI. (I mean I can place them, they just don't do anything.)

I believe this is an error. Hopefully the developers can resolve this issue.

Additional note about cells, the coolant cells do not have a texture (some of them at least. Worth looking into.)

**Comment by modmuss50** [comment]
Thanks for that, I will take a look soon

**Comment by modmuss50** [comment]
I have just fixed that :)
