### ISSUE TITLE
[1.9.4 TechReborn-1.2.2.52] Missing Itemtextures!

### ISSUE THREAD

**Issue by RakDuhl** [TechReborn/TechReborn#605]
- Diamond Saw Blad
- 180k & 360K Helium Coolant Cell
- Superconductor
- 10k, 20k, 60k Coolant Cell
- Steel Drill
- Steel Chainsaw
- Diamond Jackhammer
- Advanced Jackhammer
- Andesite, Diorite, Granite Dust
- Small Pile of Andesite, Diorite, Granite Dust
- Refined Iron Plate
- Advanced Alloy
- Hot Tungstensteel, Tungstensteel, Refined Iron, Advanced Alloy, Mixed Metal Nugget, Iridium Alloy, Diamond Nugget
- **Empty Cell + Name**

**Comment by Yulife** [comment]
but we did those textures

**Comment by RakDuhl** [comment]
hmm wierd... then i don't know whats wrong with my Minecraft.
I show you quickly.
![2016-05-28_14 16 46](https://cloud.githubusercontent.com/assets/18248606/15627268/df489a3e-24de-11e6-8136-f23817c5e5ae.png)

but it looks like, that few textures suddendly appeared, maybe because i use a resourcepack right now, i don't know

**Comment by modmuss50** [comment]
I think @Yulife has done them on the unity textures. They will come soon once they are ready.

**Comment by RakDuhl** [comment]
ah ok thanks!

**Comment by modmuss50** [comment]
Using the unity textures it looks like this, 
![2016-05-28_13 30 48](https://cloud.githubusercontent.com/assets/4324090/15627324/7135b726-24d8-11e6-9f6a-d4c2e9ee7234.png)
