### ISSUE TITLE
[1.9.4 TechReborn-1.2.2.52]  Electrolyzer Bugs

### ISSUE THREAD

**Issue by RakDuhl** [TechReborn/TechReborn#606]
When you Place empty cells and for example Ruby Dust into the Electrolyzer, it doesnt give out the acctual results when you have a stack of both items in there... it doesnt even consume any Ruby dust, only the Cells (which doesnt have a proper name, neither a Texture)
![2016-05-28_12 52 23](https://cloud.githubusercontent.com/assets/18248606/15626931/74a89d2e-24d3-11e6-9264-9327c5049b00.png)

The acctual result only happens when you have have less than 6 cells in there, otherwise it gives out this result.
with and Over 6 Cells this happens...
![2016-05-28_12 54 06](https://cloud.githubusercontent.com/assets/18248606/15626933/8a5252a0-24d3-11e6-8453-0f353f00fa66.png)

Less than 6 Cells (1-5 Cells)
![2016-05-28_12 54 56](https://cloud.githubusercontent.com/assets/18248606/15626935/adb41e04-24d3-11e6-98b1-8dab28217a72.png)

As well, there are like multiple Cell _"types"_, like you craft some with tin and these are the normal variants, but when you do a recipe in the electrolyzer, there come more cells out and they wont stack.

**Comment by ghost** [comment]
Could this recipe simply be removed? It seems like a rather strange recipe. 6 Empty cells turn into 4 hydrogen cells and 6 empty cells.
