### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by GazbonicAcid** [TechReborn/TechReborn#607]
The mod is missing some textures.
[Console Log showing missing texture error message](http://pastebin.com/jyRDJK6r)
[Proof of missing textures](http://imgur.com/a/bH4Sl)
I'm also wanting to wait until the missing textures are fixed before releasing my pack.

**Comment by modmuss50** [comment]
We have getting all of the textures redone, soon.

**Comment by Yulife** [comment]
Well the retexture could still use some time, maybe this should be fixed until then :D

**Comment by Dragon2488** [comment]
Textures of industrial electrolyzer (sides), lightning rod (top), energy crystal and lapotron crystal should be fixed in #687

**Comment by Dragon2488** [comment]
Most of textures fixed.
