### ISSUE TITLE
Crash when placing certain blocks by clicking on other blocks

### ISSUE THREAD

**Issue by supercrasher** [TechReborn/TechReborn#608]
I've seen this happen with botania too.Whenever you put a solar panel or extractor or generator(might be more blocks haven't tested them out), by right clicking on the side of another tile entity the world crashes and becomes corrupted until you delete the thing from techreborn with mcedit.
Crash report if it helps:
http://pastebin.com/1ftEvNVe

**Comment by modmuss50** [comment]
Ok, I know whats wrong. I will push a fix soon

**Comment by supercrasher** [comment]
Thanks for the extremely fast answer.

**Comment by modmuss50** [comment]
No worries :)
