### ISSUE TITLE
Make tooltips use lang file

### ISSUE THREAD

**Issue by 4rz0** [TechReborn/TechReborn#610]
There are several instances where tooltip text is hardcoded.
I suggest making it use the lang file.

Example: 
https://github.com/TechReborn/TechReborn/blob/7d95dea7834ee1cb8f606bd27c244dbcbaca2af6/src/main/java/techreborn/items/ItemUpgrades.java#L95
https://github.com/TechReborn/TechReborn/blob/7d95dea7834ee1cb8f606bd27c244dbcbaca2af6/src/main/java/techreborn/items/tools/ItemTechManual.java#L52
https://github.com/TechReborn/TechReborn/blob/7d95dea7834ee1cb8f606bd27c244dbcbaca2af6/src/main/java/techreborn/parts/powerCables/ItemStandaloneCables.java#L100

**Comment by Prospector** [comment]
I could've sworn I went around and localised all these...

**Comment by 4rz0** [comment]
More eyes see more ;D
