### ISSUE TITLE
[Crash]: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Lanse505** [TechReborn/TechReborn#611]
@modmuss50
Thinking this is either: Techborn, RebornCore or Fluxed Redstone since it references;
at me.modmuss50.fr.client.PipeModel.func_188616_a(PipeModel.kt:40)

Using:
Forge 12.17.0.1937
Techreborn 1.9.4-1.3.0.81
RebornCore 1.9.4-2.5.0.34
Fluxed Redstone 2.2.0.43

Crashlog:
https://gist.github.com/Lanse505/1b04d68477e36c7ec5fd791da376fe9e

**Comment by Lanse505** [comment]
As of the post being made forge 1937 is the newest forge also;
http://i.imgur.com/ELjtzxF.png

**Comment by modmuss50** [comment]
It is FluxedRedstone I can fix this

**Comment by modmuss50** [comment]
Ive fixed it, new build of fluxed redstone will be up soon
