### ISSUE TITLE
(feature suggestion) ores doors and trapdoors

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#612]
I find the idea interesting to have doors and trapdoors for each TechRebon metals, maybe with different behaviours.

**Comment by Yulife** [comment]
Oh god

**Comment by modmuss50** [comment]
Im not sure about it, I dont see a need for doors. Nothing wrong with the wood and iron ones

**Comment by ghost** [comment]
heh that made me think of a key-lockable door XD

**Comment by jriwanek** [comment]
Got doors/trapdoors for various metals in basemetals for those interested.
