### ISSUE TITLE
[Bug?]: HJson-File format?

### ISSUE THREAD

**Issue by Lanse505** [TechReborn/TechReborn#613]
Hey!

Not sure if this is a small derp or intentional or what but the "ores.hjson" file, is the file format .hjson supposte to be like that or was there a mistype in the format?.

Picture:
http://i.imgur.com/9qc50JL.png

**Comment by modmuss50** [comment]
no it is hjson https://hjson.org/

**Comment by Lanse505** [comment]
Good to know
