### ISSUE TITLE
(suggestion) ores generation for Zinc, Nickel, Platinium, Aluminium, Chrome and Titanium

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#615]
I just don't understand why these ores doesn't generate them. It would be nice if they generated them and just only got them by crushing or melting some other ores. It would be awesome if the Mythril and Mercure were included in the mod too.

**Comment by modmuss50** [comment]
I will look into this later, I think most of them can be obtained in other ways

**Comment by 0Navis0** [comment]
Yes I know they can be obtained in other ways, but I don't understand why they don't generate them and the other TechReborn ores do.

**Comment by modmuss50** [comment]
Because they can be obtained in other ways.

**Comment by Yulife** [comment]
^ they are supposed to be rare

**Comment by 0Navis0** [comment]
The Iridium is rare too but still generating, so why not these ones. But anyway modmuss decided that it's no, so I can't do anything against it. ^^'

**Comment by Yulife** [comment]
Well, a lot of variants cause bloat too. Gathering different ores through ores with different methods is nicer.
