### ISSUE TITLE
(suggestion) Mercure and Mythril

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#616]
I move this suggestion here for the adding of these two ores. What do you think about it ?

**Comment by modmuss50** [comment]
I dont see a need to add two ores just for the point of adding them.

**Comment by 0Navis0** [comment]
Of course, I don't say to add them only for adding them, maybe they could have many uses. I don't really know wich ones. ^^'

**Comment by modmuss50** [comment]
Give me a point to add them and I might think about it more. Atm no.

**Comment by 0Navis0** [comment]
Hm ok. For the time I haven't any particular ideas for them, but maybe I could get interesting ideas for them.
