### ISSUE TITLE
Add Config to disable Gem's

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#617]

**Comment by Prospector** [comment]
Do we need this? Doesn't the ore config file do this?

**Comment by GirafiStudios** [comment]
It was my suggestion, that Modmuss opened a issue for. It's meant to be for the gem armor/tools

**Comment by Prospector** [comment]
Hey modmuss, we would just want the recipe disabled and it hidden from JEI, right? What we should have is a json file where you could simply "disable" certain items, and it would hide it from JEI, remove from worldgen, and disable recipes for it.

**Comment by modmuss50** [comment]
This config is disabling the armor and tools. It does not register the items or the recipes. It keeps item id's down. If people want to hide stuff from JEI it has that built into it.
