### ISSUE TITLE
1.9.4-1.3.0.81 crashes dedicated forge server 1.9 build 1940 while player is exploring

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/TechReborn#619]
Issue: 1.9.4-1.3.0.81 crashes dedicated forge server 1.9 build 1940 while player is exploring

crash report:
Error: No such file or directory - /home/unoniner/uno-niner-four-mega-pack/mods/crash-2016-06-03_17.23.21-server.txt

fml server latest:
https://gist.github.com/f431bc4c32bd618effc2e54abf09cb24

**Comment by modmuss50** [comment]
I dont see a stack trace so im not sure what is happening.

**Comment by kreezxil** [comment]
sorry about that, here it is the crash report stack trace: http://gist.github.com/ee534a5b08fff5574c4a78eaeca5bbcd
