### ISSUE TITLE
[Strange Crash]:java.lang.Error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Lanse505** [TechReborn/TechReborn#620]
Using:
Forge-12.17.0.1950

TechReborns Side:
RebornCore-1.9.4-2.5.1.36
TechReborn-1.9.4-1.3.1.100

TConstructs Side:
Mantle-1.9.4-0.10.1
Tinker's Construct-1.9.4-2.3.1

---

Crashlog:
http://pastebin.com/hqatNnrw

Explaination:
Okey so the reason i'm pretty sure this is caused by TechReborn is cause it only happens if i have
TechReborn-1.9.4-1.3.1.100 enabled it crashes with this crash, but if i disable TechReborn it works just fine. Loads up no issues.

Sorry for the Derp Btw :S

**Comment by Lanse505** [comment]
Okey god dammit.... I'm gonna update this accidental enter press

**Comment by modmuss50** [comment]
ok, no worries :)

**Comment by Lanse505** [comment]
From Modmuss Stream:

"Okey so i've got a answer; 
Turning: 
B:"Compat:CompatModuleTinkers"=true 
To 
B:"Compat:CompatModuleTinkers"=false 

Fixes that Crash
