### ISSUE TITLE
IC2 1.9.4 Support

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#625]
IndustrialCraft just updated it today, and when I install both TechReborn and IndustrialCraft, I noticed that a lot of blocks are duplicated between the two mods. It would be nice to remove all the duplications when the both mods are present because it uses id for nothing and creates incoherence.

**Comment by modmuss50** [comment]
A lot of work is planned to make the work great together again. This is going to be a thing

**Comment by 0Navis0** [comment]
Thanks for the answer, I'm impatient to see it. ;)

**Comment by 0Navis0** [comment]
Do you still plan to remove the blocks and items duplication between IC2 and TechReborn ?

**Comment by modmuss50** [comment]
It should still work fine with ic2 atm, but I do plan on doing it. It will take a lot of effort to do so though. And sorry for being slow about it.

**Comment by 0Navis0** [comment]
It's fine don't worry, we have all our life and problems. ;)

**Comment by modmuss50** [comment]
When it does happen, I will most likely just hide the blocks in JEI and the creative tab, I will also need to find a way to remove the unneeded recipes.

**Comment by 0Navis0** [comment]
It would be nice to remove the blocks and items because it uses ids for nothing, it can be very annoying when you have bid modpack because of the id limit.

**Comment by modmuss50** [comment]
I might add a config to remove them all together then, as that would break worlds if you installed ic2 in pre existing worlds.

**Comment by 0Navis0** [comment]
Yeah it's surely the best to do. ;)

**Comment by modmuss50** [comment]
Seems to be working ok in 1.10.2

**Comment by 0Navis0** [comment]
Oh you finally implemented it ?

**Comment by modmuss50** [comment]
yeah, should be working good now.

**Comment by 0Navis0** [comment]
So I can disable the blocks and items duplication ?
