### ISSUE TITLE
[Crash]: java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Lanse505** [TechReborn/TechReborn#630]
---

Using;
Forge: 12.17.0.1954
Mantle: 1.9.4-0.10.1
TConstruct: 1.9.4-2.3.1
RebornCore: 1.9.4-2.5.1.36
TechReborn: 1.9.4-1.3.1.100

---

Crashlog:
http://paste.ee/p/Azwzq

---

Got this reported to me by one of our testers today.
Apparently the Lazurite Plate counts as a valid "modifier" type for Lapis (Luck) in the Tinker's Construct Book, which once hovering over the Lazurite Plate causes this Crash. 

Not sure if it's a TC/Mantle side only issue but reporting it here so both sides know.

**Comment by modmuss50** [comment]
Im not sure, mind linking the other issue?

**Comment by Lanse505** [comment]
This one?
https://github.com/SlimeKnights/Mantle/issues/65

or this one?
https://github.com/TechReborn/TechReborn/issues/620

**Comment by modmuss50** [comment]
The tinkers one, thanks :)

**Comment by Lanse505** [comment]
No problems ^^
I'll keep the crash reports coming ;)
