### ISSUE TITLE
Cannot automatically remove products of Compressor

### ISSUE THREAD

**Issue by varukasalt** [TechReborn/TechReborn#631]
1.9.4 
TechReborn-1.9.4-1.3.1.100-universal

RebornCore-1.9.4-2.5.1.35-universal

forge-1.9.4-12.17.0.1951

I have used EnderIO Item conduits, Refined Storage importers and even vanilla hoppers. Nothing will remove the processed products of the Compressor. Grinder by comparison works as expected.

**Comment by Prospector** [comment]
I believe the compressor needs to be moved to our new tile system.

**Comment by varukasalt** [comment]
Working after latest release.
