### ISSUE TITLE
Industrial Blast Furnace Recipe Issue

### ISSUE THREAD

**Issue by astocky** [TechReborn/TechReborn#633]
Using RebornCore-1.9.4-2.5.1.35-universal, TechReborn-1.9.4-1.3.1.100-universal and forge-1.9.4-12.17.0.1937.

It is not currently possible to make the industrial blast furnace. Making the furnace requires superconductors which require tungsten, but tungsten needs the industrial blast furnace and so it is not possible. Hopefully it should be a simple fix of adding an alternate method for making super conductors.

**Comment by modmuss50** [comment]
Ok thanks for spotting that

**Comment by Dragon2488** [comment]
Already fixed.
