### ISSUE TITLE
Hitting TechReborn Copper Cables with Tinker's Tools Crashes Game

### ISSUE THREAD

**Issue by Spireshield** [TechReborn/TechReborn#635]
Hello!
We've recently installed the latest version of RebornCore and TechReborn on our 1.9.4 Server, and after messing around, accidentally hit my Copper Cables with my Tinker's Iron Pickaxe. My game then crashed. I tried the same, same thing happened. I used my Iron Axe, crashed again. I didn't see this issue posted anywhere else, and figured it would be helpful to report it.

Thank You!

**Comment by modmuss50** [comment]
I fixed this, I will push an update out tomorrow.

**Comment by Spireshield** [comment]
Okay, cool. Thanks! I actually (like 5 seconds ago) accidentally placed a Copper Cable in another Copper Cable Block (not hitting the cable). Same issue?

**Comment by modmuss50** [comment]
I will check that out as well, also you should be able to break them with your hands if needed

**Comment by Spireshield** [comment]
Yes, hands work. Too scared to try with any other things.

**Comment by modmuss50** [comment]
Its now on curse
