### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by varukasalt** [TechReborn/TechReborn#636]
After upgrading both TechReborn and RebornCore, existing world crashed on opening. Reverting to older versions fixes. 

http://pastebin.com/Dt41uEzB

**Comment by modmuss50** [comment]
Ok I will take a look

**Comment by modmuss50** [comment]
That should fix it, you have a importer from refinedstorage importing from a TechReborn block. Ive added a check, this may fix it.
