### ISSUE TITLE
Putting Vanilla Hopper under Grinder (Macerator) Crashes Map

### ISSUE THREAD

**Issue by Spireshield** [TechReborn/TechReborn#639]
Hello!
After experimenting on my Server a little bit, I decided to attempt to automate an Ore Processing Unit. I placed a Hopper Duct (now gone from the Server) onto my Electric Furnace, and no issue. I then place my hopper into the duct, and place the Grinder on the hopper. The Server instantly closed. I was able to replicate this in SP, and my game crashes every time I try to get back on. It can be EASILY fixed by going into MCEdit and removing the Hopper, as that's what I did for the Server Map.

I did test it WITHOUT Hopper Ducts, putting Hopper In and Hopper Out with Chests. The second I put a Grinder on the hopper, the game crashed and I can't log back into that world.

As I've said prior to this, I didn't see the error anywhere else, and figured to report it.

**Comment by modmuss50** [comment]
I need the crash

**Comment by Spireshield** [comment]
Can do.
[crash-2016-06-08_12.07.26-server.txt](https://github.com/TechReborn/TechReborn/files/305193/crash-2016-06-08_12.07.26-server.txt)

**Comment by modmuss50** [comment]
Update reborn core, it was fixed in the next version

**Comment by Spireshield** [comment]
RebornCore got a new update? I just checked this morning. Must've missed it.

**Comment by modmuss50** [comment]
http://minecraft.curseforge.com/projects/reborncore/files/2305887

**Comment by Spireshield** [comment]
Ah okay, missed it. Thank You!
