### ISSUE TITLE
diamond dust not in ore dictionary, ruby (gem) can't be macerated etc

### ISSUE THREAD

**Issue by Nexans20** [TechReborn/TechReborn#64]
diamond dust not in ore dictionary, ruby (gem) can't be macerated etc

**Comment by TheQuantumGeneral** [comment]
Diamond dust does appear to be Ore Dict, are you using the latest build?
![diamond](https://cloud.githubusercontent.com/assets/7843312/8404427/475beb5e-1e90-11e5-8a54-cde64af8791b.PNG)

As for the gem dusts, only ores have been added for Macerator recipes so far, so not a bug just not finished. Which can be seen here - https://github.com/TechReborn/TechReborn/blob/6353b9dc06793ae33d75f608a6a06bc6d85cfbd7/src/main/java/techreborn/compat/recipes/RecipesIC2.java

**Comment by Nexans20** [comment]
ok then the recipe for the diamond saw blade doesn't use the ore dictionary for diamond dust, and yes i am.

**Comment by TheQuantumGeneral** [comment]
What mods diamond dust are you attempting to use? Works fine for me with Buildcraft additions, IC2 and tech reborn dusts. Possibly you have a mod that isn't utilizing ore dict properly? 

![capture](https://cloud.githubusercontent.com/assets/7843312/8407146/240333ee-1ea7-11e5-94db-5819b2112208.PNG)

**Comment by gigabit101** [comment]
this is not are side
