### ISSUE TITLE
Road away from JSON Destroyer

### ISSUE THREAD

**Issue by Yulife** [TechReborn/TechReborn#641]
Variant JSONS:
1: One ore JSON
2: One metal block JSON
3: One gem block JSON

Other than that we need a unique JSON for all blocks... in the right path D: The correct paths are in the run directory.
Oh I also need a basic json template without the orientable stuff, e.g. for the generators

**Comment by Prospector** [comment]
Though we'll probably keep JSON-D for the items, right?

**Comment by gigabit101** [comment]
@ProfessorProspector its not that bad 
My items are done with this https://gist.github.com/gigabit101/fa81d1d7dd21539e43d10f2895ff6ad0
and registered here https://gist.github.com/gigabit101/84195019254fd511a32ac3c22f6b67eb

**Comment by modmuss50** [comment]
Atm its working, dont want to break more things, all new blocks/items should use JSON.
