### ISSUE TITLE
Few issues, no explosions, no power transfer. 

### ISSUE THREAD

**Issue by slidingmike** [TechReborn/TechReborn#642]
Unsure if this just me or not, but I've noticed a few issues. 

Transformers are not passing power. 
MFE can not be rotated. 
Missing textures. (I saw this is a work in progress) 
No explosions on inadequate cabling or too much power into machine? (didn't see a config option for this) 

1.9.4
Forge 1257
Reborn Core 2.5.3.44
Techreborn 1.3.2.120

**Comment by slidingmike** [comment]
MFE amount stored going negative. Stack of coal net me a loss when extractor was the only machine running.

Transformers unable to be rotated as well.

**Comment by modmuss50** [comment]
We have currently rewriting the power system and all of the tiles, this should be fixed soon. Sorry about the wait

**Comment by Dragon2488** [comment]
Transformers don't work for now, machines don't explode too. For now it works like RF, cables transfer only limited amount of power, machines receive limited amount too. I don't know about explosions, but i'll fix transformers soon.
