### ISSUE TITLE
[1.9.4-1.3.2.120]Game crashes when connecting hopper to extractor

### ISSUE THREAD

**Issue by Karra11** [TechReborn/TechReborn#643]
If the hopper is connected on the top to automatically input items nothing happens, but if connected from the bottom to automatically output items to a chest, the game crashes. The world cannot be opened after this.

**Comment by modmuss50** [comment]
Can i have the log? What versions of reborn core are you using?

**Comment by Karra11** [comment]
Sorry i didn´t put it before, I´m using the last updates of both mods. I send you in a minute the log.

**Comment by Karra11** [comment]
Here are the log and the crash file:
[crash-2016-06-12_12.34.55-server.txt](https://github.com/TechReborn/TechReborn/files/310728/crash-2016-06-12_12.34.55-server.txt)
log:
[fml-client-latest.txt](https://github.com/TechReborn/TechReborn/files/310730/fml-client-latest.txt)

**Comment by Oranjui** [comment]
This also occurs with Iron Furnaces, and while I haven't tested, presumably other machines too.

**Comment by Prospector** [comment]
Please don't just say "latest version"

The latest versions 16 hours ago are not the same latest versions now. Please give actual version numbers.

**Comment by modmuss50** [comment]
I can push a fix for this

**Comment by Karra11** [comment]
The bug is for the following versions:
-Tech Reborn: 1.9.4-1.3.2.120
-Reborn Core: 1.9.4-2.5.3.44
I haven't tested it for newest versions, so I don't know if the bug is already fixed, sorry for the bad call. I will change the name.

**Comment by dirtyfargo** [comment]
I am having a similar issue with all of the latest versions since  Tech Reborn-1.9.4-1.3.2.120 and RebornCore-1.9.4-2.5.1.41, although my hopper isn't on an extractor I don't think. [Crash Report](https://gist.github.com/dirtyfargo/fa0dd75bcfee6e4c374c5953f1c4c171)

**Comment by slidingmike** [comment]
Can confirm that this occurs on Iron Furnaces as well. 1.3.2.120 and 2.5.1.41 with forge 1257

**Comment by modmuss50** [comment]
Ok I will get an update out soon to fix this

**Comment by modmuss50** [comment]
I will upload a new build to curse in a few mins

**Comment by modmuss50** [comment]
http://minecraft.curseforge.com/projects/reborncore/files/2307265
