### ISSUE TITLE
[1.9.4]Netherrack dust recipes are missing

### ISSUE THREAD

**Issue by Karra11** [TechReborn/TechReborn#644]
As for 
-Tech Reborn: 1.9.4-1.3.2.120
-Reborn Core: 1.9.4-2.5.4.47
the recipes that use netherrack dust can't be done, because the only recipe for the netherrack dust is using its own tiny pile, which can only be crafted using the dust.
If there is a recipe for the (industrial)grinder/macerator as in versions before 1.9.4, it is missing in this one.

**Comment by modmuss50** [comment]
Ok thanks, When one of us has the chance im sure this can be added.

**Comment by Karra11** [comment]
Thank you a lot.
