### ISSUE TITLE
Empty batteries/crystals keep on charging energy storage

### ISSUE THREAD

**Issue by Cendrb** [TechReborn/TechReborn#645]
Empty batteries/crystals (doesn't matter if discharged or put in empty) charge energy storage block they are put in (MFSU/MFE/...)

Also the completely empty versions don't have any textures

forge 12.17.0.1963
TechReborn 1.3.2.120
RebornCore 2.5.4.47

**Comment by Dragon2488** [comment]
Duplicate.
