### ISSUE TITLE
Dev Heads causing lag

### ISSUE THREAD

**Issue by alexgeek** [TechReborn/TechReborn#648]
Hey I posted an [issue on the RebornCore repo](https://github.com/TechReborn/RebornCore/issues/28) about this as the code that gets the heads is in RebornCore. I've done a little digging and found the cause is adding the dev heads on on [line 135 here](https://github.com/TechReborn/TechReborn/blob/8d06a8bef3d99253272d61734ce93acea55fcd25/src/main/java/techreborn/init/ModRecipes.java).

Adding the heads in and not hiding them in JEI causes severe lag due to the number of textures it tries to retrieve at once. Further, they don't seem to be cached so the repeated requests cause an AuthenticationException as you can see in my log in the RebornCore issue. 

This causes severe lag any time I scroll past the heads or search for something that matches any of them. They can be manually hidden in JEI but I have found that they do not stay hidden on relogging.

**Comment by modmuss50** [comment]
I dont think we need this, this can just be removed

**Comment by Dragon2488** [comment]
Mojangs is to blame for not caching requests, i think they should fix it soon.

**Comment by modmuss50** [comment]
We can remove the dev heads untill they fix it.
