### ISSUE TITLE
Rubber Trees don't seem to generate with Quark's worldgen

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#655]
I flew around in a forest for a while and I couldn't find any at all. Having someone else confirm this would be great.

**Comment by primetoxinz** [comment]
they generate just fine with quark

**Comment by erindal** [comment]
Sorry, I should have been more specific. Quark has a realistic worldgen option.

**Comment by primetoxinz** [comment]
which uses the vanilla level modification

**Comment by erindal** [comment]
Okay made a new world and I just found some. They seem rarer than usual. Thanks for your help.
