### ISSUE TITLE
[1.10.2] Texture glitches

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#659]
I'm using the latest version of TechReborn, RebornCore and Forge.
Here's a list of items and blocks which have no texture : 
- Industrial Electrolyzer
- Diamond Saw Blade
- 180k Helium Coolant Cell
- 360k Helium Coolant Cell
- Superconductor
- 10k Coolant Cell
- 30k Coolant Cell
- 60k Coolant Cell
- Energy Crystal (discharged)
- Lapotron Crystal (discharged)
- Battery (discharged or not)
- Diamond Jackhammer (discharged or not)
- Small Pile of Andesite/Granite/Diorite Dust
- Refined Iron Plate
- Advanced Alloy
- Lazurite Plate
- Hot Tungstensteel Nugget
- Tungstensteel Nugget
- Refined Iron Nugget
- Diamond Nugget
- Frequency Transmitter

**Comment by Yulife** [comment]
So we doing item JSONs now?

**Comment by Prospector** [comment]
No

**Comment by Dragon2488** [comment]
Small piles, plates, and nuggets are generated automatically from ingots and gems, so some of them don't have textures.

**Comment by 0Navis0** [comment]
These textures are still broken today.

**Comment by modmuss50** [comment]
Yeah, We havent moved to the new ones yet

**Comment by 0Navis0** [comment]
Oh ok, can't wait to see it. ;)

**Comment by modmuss50** [comment]
All textures are fixed.
