### ISSUE TITLE
Crash with Tech reborn and JEI

### ISSUE THREAD

**Issue by Peach774** [TechReborn/TechReborn#660]
I was in creative mode but when I went to scroll through the JEI tab, a crash related to tech reborn shields appeared:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  ProgressionTransformer (Progression-1.9.4-0.6.5.jar)
  LoadingPlugin (NoNausea-MC1.9.4-1.0.jar)
  LoadingPlugin (Quark-beta-29.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 7/3/16 10:41 AM
Description: Rendering item

java.lang.NullPointerException: Rendering item
    at reborncore.shields.client.RebornItemStackRenderer.func_179022_a(RebornItemStackRenderer.java:47)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:146)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:309)
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:348)
    at mezz.jei.gui.ingredients.GuiItemStackFast.renderSlow(GuiItemStackFast.java:149)
    at mezz.jei.gui.ingredients.GuiItemStackFastList.render(GuiItemStackFastList.java:144)
    at code.elix_x.mods.fei.client.jeioverride.ItemListOverlayOverride.drawScreen(ItemListOverlayOverride.java:317)
    at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:87)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_533_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:582)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1095)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at reborncore.shields.client.RebornItemStackRenderer.func_179022_a(RebornItemStackRenderer.java:47)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:146)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:309)

-- Item being rendered --
Details:
    Item Type: net.minecraft.item.ItemShield@32da97fd
    Item Aux: 0
    Item NBT: {}
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:348)
    at mezz.jei.gui.ingredients.GuiItemStackFast.renderSlow(GuiItemStackFast.java:149)
    at mezz.jei.gui.ingredients.GuiItemStackFastList.render(GuiItemStackFastList.java:144)
    at code.elix_x.mods.fei.client.jeioverride.ItemListOverlayOverride.drawScreen(ItemListOverlayOverride.java:317)
    at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:87)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_533_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:582)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (578, 262). Absolute: (1156, 492)
    Screen size: Scaled: (960, 509). Absolute: (1920, 1018). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Peach774'/6821, l='MpServer', x=277.61, y=66.00, z=43.37]]
    Chunk stats: MultiplayerChunkCache: 398, 398
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (188,64,232), Chunk: (at 12,4,8 in 11,14; contains blocks 176,0,224 to 191,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 10206 game time, 10206 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 75 total; [EntityConcussionCreeper['Concussion Creeper'/10752, l='MpServer', x=283.43, y=35.00, z=50.22], EntitySpider['Spider'/11270, l='MpServer', x=204.50, y=24.00, z=38.50], EntityZombie['Zombie'/11284, l='MpServer', x=296.50, y=37.00, z=48.50], EntityItem['item.item.witheringDust'/9247, l='MpServer', x=302.69, y=13.00, z=38.78], EntityZombie['Zombie'/10798, l='MpServer', x=304.76, y=35.00, z=58.56], EntityZombie['Zombie'/6722, l='MpServer', x=262.47, y=55.00, z=56.75], EntityBat['Bat'/11342, l='MpServer', x=299.47, y=50.37, z=50.35], EntityCreeper['Creeper'/10337, l='MpServer', x=317.84, y=20.00, z=47.50], EntityFallingBlock['Falling Block'/9832, l='MpServer', x=307.50, y=19.78, z=-100.50], EntityZombie['Zombie'/10858, l='MpServer', x=220.50, y=15.00, z=10.50], EntityPig['Pig'/6765, l='MpServer', x=297.34, y=71.00, z=34.18], EntitySpider['Spider'/11374, l='MpServer', x=291.70, y=14.00, z=102.03], EntityBat['Bat'/10869, l='MpServer', x=300.40, y=18.10, z=18.04], EntitySkeleton['Skeleton'/9348, l='MpServer', x=262.53, y=54.00, z=58.73], EntityBat['Bat'/11402, l='MpServer', x=338.67, y=42.62, z=64.73], EntityBat['Bat'/11403, l='MpServer', x=313.25, y=27.05, z=5.62], EntityCreeper['Creeper'/11410, l='MpServer', x=308.50, y=34.00, z=65.50], EntitySkeleton['Skeleton'/11417, l='MpServer', x=278.30, y=29.00, z=50.50], EntitySquid['Squid'/10919, l='MpServer', x=216.65, y=55.51, z=80.46], EntitySkeleton['Skeleton'/11439, l='MpServer', x=237.50, y=42.00, z=-31.50], EntitySkeleton['Skeleton'/11440, l='MpServer', x=237.50, y=42.00, z=-31.50], EntitySkeleton['Skeleton'/11441, l='MpServer', x=237.50, y=42.00, z=-28.50], EntitySkeleton['Skeleton'/11442, l='MpServer', x=240.50, y=43.00, z=-24.79], EntityZombie['Zombie'/11443, l='MpServer', x=236.50, y=42.00, z=-29.93], EntityZombie['Zombie'/11444, l='MpServer', x=236.50, y=42.00, z=-29.30], EntityPig['Pig'/6837, l='MpServer', x=320.72, y=63.00, z=-6.50], EntityPig['Pig'/6838, l='MpServer', x=327.50, y=71.00, z=-6.50], EntityPig['Pig'/6839, l='MpServer', x=327.50, y=70.00, z=-7.50], EntityPig['Pig'/6840, l='MpServer', x=327.50, y=71.00, z=-5.50], EntityPig['Pig'/6843, l='MpServer', x=307.19, y=67.00, z=29.50], EntityPig['Pig'/6844, l='MpServer', x=299.19, y=67.00, z=32.45], EntityPig['Pig'/6845, l='MpServer', x=276.50, y=67.00, z=36.21], EntityPlayerSP['Peach774'/6821, l='MpServer', x=277.61, y=66.00, z=43.37], EntityCreeper['Creeper'/11471, l='MpServer', x=328.50, y=21.00, z=48.50], EntityEnderman['Enderman'/11477, l='MpServer', x=303.50, y=14.00, z=112.50], EntityGuardian['Guardian'/10972, l='MpServer', x=347.50, y=48.00, z=121.50], EntityBat['Bat'/11495, l='MpServer', x=301.42, y=50.86, z=48.16], EntityCreeper['Creeper'/10479, l='MpServer', x=296.50, y=18.00, z=53.50], EntityBat['Bat'/11504, l='MpServer', x=278.75, y=44.00, z=103.48], EntityWitch['Witch'/11522, l='MpServer', x=303.50, y=13.00, z=101.50], EntityZombie['Zombie'/11526, l='MpServer', x=333.50, y=33.00, z=61.50], EntityBat['Bat'/10008, l='MpServer', x=269.49, y=41.10, z=47.01], EntityCreeper['Creeper'/7961, l='MpServer', x=255.54, y=43.00, z=47.88], EntityItem['item.item.bone'/10527, l='MpServer', x=335.99, y=51.00, z=29.18], EntityWitherCat['Wither Cat'/8491, l='MpServer', x=294.45, y=54.00, z=59.17], EntityPig['Pig'/6956, l='MpServer', x=331.50, y=63.00, z=-20.50], EntityPig['Pig'/6957, l='MpServer', x=329.50, y=68.00, z=-21.50], EntityPig['Pig'/6958, l='MpServer', x=329.50, y=68.00, z=-22.50], EntityPig['Pig'/6961, l='MpServer', x=351.78, y=72.00, z=-22.48], EntityCreeper['Creeper'/8498, l='MpServer', x=279.85, y=48.00, z=44.39], EntityConcussionCreeper['Concussion Creeper'/11059, l='MpServer', x=293.50, y=21.00, z=47.50], EntityZombie['Zombie'/11063, l='MpServer', x=332.79, y=33.00, z=60.43], EntityZombie['Zombie'/11069, l='MpServer', x=296.50, y=50.00, z=-33.50], EntityBat['Bat'/11089, l='MpServer', x=345.78, y=48.10, z=50.02], EntityPig['Pig'/7000, l='MpServer', x=352.72, y=72.00, z=-29.83], EntityPig['Pig'/7001, l='MpServer', x=351.51, y=71.00, z=-36.49], EntityCreeper['Creeper'/11097, l='MpServer', x=256.50, y=27.00, z=121.50], EntitySkeleton['Skeleton'/11098, l='MpServer', x=356.50, y=16.00, z=58.50], EntityPig['Pig'/7003, l='MpServer', x=349.49, y=70.00, z=-36.51], EntityCow['Cow'/7005, l='MpServer', x=350.49, y=71.00, z=-28.09], EntityCow['Cow'/7006, l='MpServer', x=350.51, y=71.00, z=-30.11], EntityCow['Cow'/7007, l='MpServer', x=350.18, y=71.00, z=-29.08], EntitySkeleton['Skeleton'/11166, l='MpServer', x=280.50, y=18.00, z=108.50], EntityZombie['Zombie'/11173, l='MpServer', x=222.50, y=41.00, z=52.50], EntityCreeper['Creeper'/11174, l='MpServer', x=303.50, y=47.00, z=22.50], EntitySkeleton['Skeleton'/10697, l='MpServer', x=283.50, y=19.00, z=26.50], EntityBat['Bat'/11225, l='MpServer', x=325.66, y=60.07, z=6.40], EntityBat['Bat'/11227, l='MpServer', x=320.42, y=61.87, z=4.56], EntityZombie['Zombie'/10206, l='MpServer', x=283.49, y=54.00, z=8.80], EntityBat['Bat'/11234, l='MpServer', x=254.75, y=40.10, z=63.42], EntityBat['Bat'/11236, l='MpServer', x=301.18, y=16.43, z=18.02], EntityCreeper['Creeper'/11241, l='MpServer', x=223.50, y=35.00, z=34.50], EntityZombie['Zombie'/11244, l='MpServer', x=257.50, y=53.00, z=83.20], EntitySkeleton['Skeleton'/10733, l='MpServer', x=303.50, y=24.00, z=52.50], EntitySkeleton['Skeleton'/11260, l='MpServer', x=253.50, y=40.00, z=59.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:390)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 884571128 bytes (843 MB) / 3229089792 bytes (3079 MB) up to 3758096384 bytes (3584 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4031m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
    FML: MCP 9.28 Powered by Forge 12.17.0.1987 90 mods loaded, 90 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAA  FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1987.jar) 
    UCHIJAAAAAAAAA  Forge{12.17.0.1987} [Minecraft Forge](forge-1.9.4-12.17.0.1987.jar) 
    UCHIJAAAAAAAAA  additionalbanners{1.2.0.17} [Additional Banners](AdditionalBanners-1.9.4-1.2.0.18.jar) 
    UCHIJAAAAAAAAA  ARMourstands{1.9.4-0.0.3} [ARMourstands](ARMourstands-1.9.4-0.0.3.jar) 
    UCHIJAAAAAAAAA  autopackager{1.6.3} [AutoPackager](autopackager-1.6.3.jar) 
    UCHIJAAAAAAAAA  bagginses{2.4.2d} [Bagginses](Bagginses-1.9.4-2.5.0c.jar) 
    UCHIJAAAAAAAAA  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAAAAAAA  BaublesHud{3.0.0} [Baubles-Hud](BaublesHud-1.9.4-3.0.0.jar) 
    UCHIJAAAAAAAAA  BetterAchievements{0.3.0.26} [Better Achievements](BetterAchievements-1.9.4-0.3.0.26.jar) 
    UCHIJAAAAAAAAA  BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
    UCHIJAAAAAAAAA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UCHIJAAAAAAAAA  JEI{3.6.7.216} [Just Enough Items](jei_1.9.4-3.6.7.216.jar) 
    UCHIJAAAAAAAAA  blockdrops{1.0.4} [Block Drops](BlockDrops-1.9.4-1.0.4.jar) 
    UCHIJAAAAAAAAA  BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-48.jar) 
    UCHIJAAAAAAAAA  Botania{r1.8-312} [Botania](Botania-unofficial.r1.8-312.jar) 
    UCHIJAAAAAAAAA  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAAAAAAA  SonarCore{3.0.0} [SonarCore](SonarCore-1.9.4-3.0.0.jar) 
    UCHIJAAAAAAAAA  Calculator{3.0.0} [Calculator](Calculator-1.9.4-3.0.0.jar) 
    UCHIJAAAAAAAAA  capsule{1.9.4-1.1.7} [Capsule](Capsule-1.9.4-1.1.7.jar) 
    UCHIJAAAAAAAAA  Chameleon{1.9.4-2.1.5} [Chameleon](Chameleon-1.9.4-2.1.5.jar) 
    UCHIJAAAAAAAAA  ChestTransporter{2.4.0} [Chest Transporter](ChestTransporter-1.9.4-2.4.0.jar) 
    UCHIJAAAAAAAAA  chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.29.jar) 
    UCHIJAAAAAAAAA  chiselsandbits{10.12} [Chisels & Bits](chiselsandbits-10.12.jar) 
    UCHIJAAAAAAAAA  compasscoords{1.9.4-3.1.4} [Compass Co-ords](CompassCoords-1.9.4-3.1.4.jar) 
    UCHIJAAAAAAAAA  cookingforblockheads{3.1.26} [Cooking for Blockheads](CookingForBlockheads-mc1.9.4-3.1.26.jar) 
    UCHIJAAAAAAAAA  cosmeticarmorreworked{1.9.4-v2} [CosmeticArmorReworked](CosmeticArmorReworked-1.9.4-v2.jar) 
    UCHIJAAAAAAAAA  craftingtweaks{5.0.6} [Crafting Tweaks](craftingtweaks-mc1.9.4-5.0.6.jar) 
    UCHIJAAAAAAAAA  MineTweaker3{3.0.9} [MineTweaker 3](CraftTweaker-1.9-3.0.9.jar) 
    UCHIJAAAAAAAAA  cyclopscore{0.6.3} [Cyclops Core](CyclopsCore-1.9.4-0.6.3.jar) 
    UCHIJAAAAAAAAA  ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UCHIJAAAAAAAAA  deepresonance{1.2.0beta35} [DeepResonance](deepresonance-1.9.4-1.2.0beta35.jar) 
    UCHIJAAAAAAAAA  endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
    UCHIJAAAAAAAAA  EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.46_alpha.jar) 
    UCHIJAAAAAAAAA  shetiphiancore{3.2.6} [ShetiPhian-Core](shetiphiancore-1.9.4-3.2.6.jar) 
    UCHIJAAAAAAAAA  endertanks{1.3.6} [EnderTanks](endertanks-1.9.4-1.3.6.jar) 
    UCHIJAAAAAAAAA  EnderZoo{1.9.4-1.2.2.40} [Ender Zoo](EnderZoo-1.9.4-1.2.2.40.jar) 
    UCHIJAAAAAAAAA  ValkyrieLib{1.9.4-0.9.12} [Valkyrie Lib](valkyrielib-1.9.4-0.9.12.jar) 
    UCHIJAAAAAAAAA  EnvironmentalTech{1.9.4-0.9.4e} [Environmental Tech](environmentaltech-1.9.4-0.9.4e.jar) 
    UCHIJAAAAAAAAA  evilcraft{0.10.2} [EvilCraft](EvilCraft-1.9.4-0.10.2.jar) 
    UCHIJAAAAAAAAA  excore{1.5.3} [EXCore](Excore-1.5.3-1.9.4.jar) 
    UCHIJAAAAAAAAA  ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation](ExtraBitManipulation-1.9.4-2.1.0.jar) 
    UCHIJAAAAAAAAA  FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage](Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
    UCHIJAAAAAAAAA  fastleafdecay{v10} [Fast Leaf Decay](FastLeafDecay-v10.jar) 
    UCHIJAAAAAAAAA  flatcoloredblocks{mc1.9.4-v3.2} [Flat Colored Blocks](flatcoloredblocks-mc1.9.4-v3.2.jar) 
    UCHIJAAAAAAAAA  forestry{5.0.23.170} [Forestry](forestry_1.9.4-5.0.23.170.jar) 
    UCHIJAAAAAAAAA  moreoverlays{1.4} [MoreOverlays](moreoverlays-1.4-mc1.9.4.jar) 
    UCHIJAAAAAAAAA  FEI{1.0.13} [Forever Enough Items](ForeverEnoughItems-1.0.13-1.9.4.jar) 
    UCHIJAAAAAAAAA  graves{1.9.4-b17-universal} [Graves Mod](graves-1.9.4-b17-universal.jar) 
    UCHIJAAAAAAAAA  HelpFixer{1.3.14} [HelpFixer](HelpFixer-1.9.4-1.3.14.jar) 
    UCHIJAAAAAAAAA  immcraft{1.1.7} [Immersive Craft](immcraft-1.9.4-1.1.7.jar) 
    UCHIJAAAAAAAAA  integrateddynamics{0.3.10} [Integrated Dynamics](IntegratedDynamics-1.9.4-0.3.10.jar) 
    UCHIJAAAAAAAAA  inventorysorter{0.10.0+42} [Simple Inventory sorting](inventorysorter-1.10-0.10.0+42.jar) 
    UCHIJAAAAAAAAA  IronChest{6.0.146.788} [Iron Chest](ironchest-1.9.4-6.0.146.788.jar) 
    UCHIJAAAAAAAAA  journeymap{1.9.4-5.2.4} [JourneyMap](journeymap-1.9.4-5.2.4-unlimited.jar) 
    UCHIJAAAAAAAAA  jeresources{0.4.6.39} [Just Enough Resources](JustEnoughResources-1.9.4-0.4.6.39.jar) 
    UCHIJAAAAAAAAA  JET{2.1.32} [JustEnoughTooltips](JustEnoughTooltips-1.9.4-2.1.32.jar) 
    UCHIJAAAAAAAAA  mantle{1.9.4-0.10.3.jenkins211} [Mantle](Mantle-1.9.4-0.10.3.jar) 
    UCHIJAAAAAAAAA  moarsigns{3.1.0} [MoarSigns](MoarSigns-1.9.4-3.1.0.jar) 
    UCHIJAAAAAAAAA  Morpheus{1.9.4-3.1.5} [Morpheus](Morpheus-1.9.4-3.1.5.jar) 
    UCHIJAAAAAAAAA  multistorage{1.1.3} [Multi-Storage](multistorage-1.9.4-1.1.3.jar) 
    UCHIJAAAAAAAAA  NoNausea{1.0} [No Nausea](NoNausea-MC1.9.4-1.0.jar) 
    UCHIJAAAAAAAAA  notenoughwands{1.3.5} [Not Enough Wands](notenoughwands-1.9.4-1.3.5.jar) 
    UCHIJAAAAAAAAA  ObsidianPlates{1.1.1} [Obsidian Plates](ObsidianPlates-1.1.1_1.9.4.jar) 
    UCHIJAAAAAAAAA  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4c.jar) 
    UCHIJAAAAAAAAA  progression{0.6.5} [Progression](Progression-1.9.4-0.6.5.jar) 
    UCHIJAAAAAAAAA  Psi{r1.0-35} [Psi](Psi-r1.0-35.jar) 
    UCHIJAAAAAAAAA  Quark{beta-29} [Quark](Quark-beta-29.jar) 
    UCHIJAAAAAAAAA  reborncore{2.5.4.50} [RebornCore](RebornCore-1.9.4-2.5.4.50-universal.jar) 
    UCHIJAAAAAAAAA  reborncore-mcmultipart{2.5.4.50} [reborncore-MCMultiPart](RebornCore-1.9.4-2.5.4.50-universal.jar) 
    UCHIJAAAAAAAAA  recallstones{0.6.1} [Recall Stones](RecallStones-1.9.4-0.6.1.jar) 
    UCHIJAAAAAAAAA  redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJAAAAAAAAA  StorageDrawers{1.9.4-3.1.11} [Storage Drawers](StorageDrawers-1.9.4-3.1.11.jar) 
    UCHIJAAAAAAAAA  refinedstorage{0.7.19} [Refined Storage](refinedstorage-0.7.19.jar) 
    UCHIJAAAAAAAAA  xreliquary{1.9.4-1.3.2.404} [Reliquary](Reliquary-1.9.4-1.3.2.404.jar) 
    UCHIJAAAAAAAAA  rftools{4.67} [RFTools](rftools-1.9.4-4.67.jar) 
    UCHIJAAAAAAAAA  rftoolsdim{4.30beta44} [RFTools Dimensions](rftoolsdim-1.9.4-4.30beta44.jar) 
    UCHIJAAAAAAAAA  Roguelike{1.5.3} [Roguelike Dungeons](RoguelikeDungeons-1.9.4-1.5.3.jar) 
    UCHIJAAAAAAAAA  roots{0.007} [Roots](roots-0.007.jar) 
    UCHIJAAAAAAAAA  runesofwizardry{1.9.4-0.6.8} [Runes of Wizardry](Runes-of-Wizardry-1.9.4-0.6.8.jar) 
    UCHIJAAAAAAAAA  runesofwizardry_classics{1.9.4-0.3.5} [Runes of Wizardry - Classic Dusts Pack](RunesofWizardry-Classics-1.9.4-0.3.5.jar) 
    UCHIJAAAAAAAAA  ShieldHider{1.0.1} [Shield Hider](ShieldHider-1.0.1_1.9.4.jar) 
    UCHIJAAAAAAAAA  soulshardstow{1.9.4-2.4.5-33} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.5-33.jar) 
    UCHIJAAAAAAAAA  supercraftingframe{1.2.0.84} [Super Crafting Frame](supercraftingframe-1.9.4-1.2.0.84.jar) 
    UCHIJAAAAAAAAA  tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct](TConstruct-1.9.4-2.3.3.jar) 
    UCHIJAAAAAAAAA  techreborn{1.3.2.177} [TechReborn](TechReborn-1.9.4-1.3.2.177-universal.jar) 
    UCHIJAAAAAAAAA  terrainCrystals{1.0.8} [Terrain Crystals](Terrain Crystals - 1.9.4 - 1.0.8.jar) 
    UCHIJAAAAAAAAA  underphangables{1.0.2} [Underp Hangables](underphangables-1.10.0-1.0.2.jar) 
    UCHIJAAAAAAAAA  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UCHIJAAAAAAAAA  Zoology{1.0} [Zoology](zoology-1.9.4-alpha-1.1.0.jar) 
    Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
ProgressionTransformer (Progression-1.9.4-0.6.5.jar)
  joshie.progression.asm.ProgressionTransformer
LoadingPlugin (NoNausea-MC1.9.4-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
LoadingPlugin (Quark-beta-29.jar)
  vazkii.quark.base.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  shetiphian.core.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13440 Compatibility Profile Context 16.200.1025.0' Renderer: 'AMD Radeon R9 200 Series'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
EnderIO: No known problems detected.
Launched Version: forge-12.17.0.1987
LWJGL: 2.9.4
OpenGL: AMD Radeon R9 200 Series GL version 4.5.13440 Compatibility Profile Context 16.200.1025.0, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: net.minecraft.client.Minecraft$15@40996675
```

**Comment by Peach774** [comment]
This still occurs in 1.10

**Comment by modmuss50** [comment]
Can you try restart your game? it should work now I hope

**Comment by Peach774** [comment]
Fixed, thanks so much!
