### ISSUE TITLE
Bugs in 1.7.10 version.

### ISSUE THREAD

**Issue by Furious1964** [TechReborn/TechReborn#661]
I plat FTB Infinity Evolved and the pack is only 1.7.10. I've noticed that half of the machines either don't work or lack the necessary recipes in order to actually use it. The other half work and then glitch out for no apparent reason with no chance of getting them to start up again. For instance: not being able to wrench any machine and the IDSU suddenly stopping and receiving or transmitting any power. As for the distillation tower, it can be built but does nothing. Can't even access the GUI.

Using Forge 1.7.10-10.13.4.1614.

**Comment by modmuss50** [comment]
We only fix major issues in 1.7 now, have you got ic2 enabled?

**Comment by modmuss50** [comment]
I would recommend updating to 1.10.

**Comment by Furious1964** [comment]
Can't upgrade the pack to 1.10 as a lot of the mods used aren't updated. I'm using industrialcraft-2-2.2.822-experimental as per the pack. Can you please look into this as it's a great mod to have when GregTech is too cumbersome. I like the machine, but the ore generation and other stuff doesn't play well with some of the mods. Had it installed before and it crashed.
