### ISSUE TITLE
RubberWood meta values seem weird

### ISSUE THREAD

**Issue by HenryLoenwind** [TechReborn/TechReborn#662]
when looking at this https://github.com/TechReborn/TechReborn/blob/1.10/src/main/java/techreborn/blocks/BlockRubberLog.java#L62-L92 and adding it up I get:

```
0 SOUTH
1 WEST
2 NORTH
3 EAST
3 SOUTH with sap
4 WEST with sap
5 NORTH with sap
6 EAST with sap
```

which seems a bit weird as 2 states map to the same meta value. Is that intended or a typo?

**Comment by modmuss50** [comment]
that would be an issue, yeah
