### ISSUE TITLE
strange crash with Tinker's Addons

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#667]
I get this crash when I try to display the Tinker's Addons items in the Minecraft creative menu. http://pastebin.com/G7iYEQe1 
I had already reported this crash to the Tinker's Addons dev, but he told me that it was the TechReborn fault and then report it here.

**Comment by modmuss50** [comment]
I assume you didn't have the latest version?

**Comment by 0Navis0** [comment]
I don't know, I haven't more the bug now, so I suppose it is solved.
