### ISSUE TITLE
Diesel Generator eats lava cells 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#67]
I know a lot of these blocks are W.I.P but the Diesel Generator will currently accept and do nothing with all cells, with the exception of lava cells. It will consume 10 lava cells, regardless of mod fluid container, forestry cans, buckets, etc and won't accept any more until broken and replaced. 

Might be related to issue https://github.com/TechReborn/TechReborn/issues/66 ?

**Comment by modmuss50** [comment]
Should this run off the diesel cell? Or do we need to add a diesel liquid for this, im not sure how its supposed to work.

**Comment by TheQuantumGeneral** [comment]
It is intended to operate on these fuels for these values

Biofuel Cell               6,000 EU
Coalfuel Cell            16,000 EU
Biofuel                     32,000 EU
Bio Diesel Cell          32,000 EU
Nitro-Coalfuel Cell     48,000 EU
Fuel                         384,000 EU
Nitro-Diesel Cell        400,000 EU

However currently it only consumes Lava cells and gives no empty cells or power in return.

**Comment by modmuss50** [comment]
Is there a forge api for this, ore should I hard code the values?

**Comment by Carbon-Ghost** [comment]
This made me laugh, diesel gen eating lava xD

Also, IC2 fuel is underated, BUFF IT ! ( for classic )

**Comment by modmuss50** [comment]
Last issue to fix before the first beta? Have I missed anything?

**Comment by modmuss50** [comment]
Im still not sure on the correct way to fix this

**Comment by TheQuantumGeneral** [comment]
Hardcode it to only accept fluid:diesel or something?

**Comment by modmuss50** [comment]
That's what I was thinking

**Comment by modmuss50** [comment]
Looks like foresty has an api for it.

https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/fuels/GeneratorFuel.java

We can hook into that and make it run standalone

**Comment by modmuss50** [comment]
Ive recoded it, please report any incompatabilly
