### ISSUE TITLE
All sides of ores (and possibly other blocks) are always rendered

### ISSUE THREAD

**Issue by LatvianModder** [TechReborn/TechReborn#675]
This isn't game breaking bug, but it seem like all ores are non-opaque blocks, and all sides are always rendered. And since there is a ton of them in ground, that could reduce rendering performance by at leasy 0.001 FPS (wow!)

Screenshot: (taken with /gamemode 3)
![Img](http://i.imgur.com/3n7eoDy.png)

**Comment by Prospector** [comment]
I would assume all sides of any block using jsondestroyer is probably rendered.

**Comment by Dragon2488** [comment]
Well, JsonDestroyer will be destroyed someday

**Comment by modmuss50** [comment]
Fixed with: https://github.com/modmuss50/JSON-Destroyer/commit/b6ce407a1a11df99decf8c111bf037206fe009d7
