### ISSUE TITLE
[Regression] Crash on startup

### ISSUE THREAD

**Issue by C0rn3j** [TechReborn/TechReborn#676]
TechReborn-1.10.2-1.3.2.1-universal > TechReborn-1.10.2-1.3.3.10-universal.jar

New version crashes both on client(Forge 2011) and server (2010).

Crash log: http://pastebin.com/dVekDGkQ

Is it because the new version is using latest forge instead of recommended?

**Comment by C0rn3j** [comment]
Client crashes with forge 2014 too.

**Comment by modmuss50** [comment]
For now use the older version

**Comment by modmuss50** [comment]
I should be able to get a fix out soon
