### ISSUE TITLE
Weird Crash from voltage explosion involving Tough as Nails

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#678]
https://github.com/Glitchfiend/ToughAsNails/issues/76

Crash Report:
http://pastebin.com/U3VEVTYV

**Comment by modmuss50** [comment]
I think is our issue, but I will look into it. How would I reproduce it?

**Comment by erindal** [comment]
I cannot seem to reproduce it. I overloaded an assembly machine with an MFE and glass fibre cable. I picked up the machine block drop, but I can't seem to reproduce it.

**Comment by modmuss50** [comment]
Looking at the log it seems the item had a meta data value of 6 for some reason.

**Comment by modmuss50** [comment]
I will have a look to see if I can figure out why this happened.

**Comment by erindal** [comment]
Yeah I failed to noticed I got a machine block with a meta value of 6 in my inventory from the drop

**Comment by erindal** [comment]
![2016-07-17_21 18 48](https://cloud.githubusercontent.com/assets/12499779/16904430/12b27690-4c64-11e6-9c5b-82746d3111ce.png)

**Comment by vladfrangu** [comment]
This might be just an error when the explosion happens, if it uses special code for an explosion.. Can you place down that block? 

IT shouldn't have happened.. Try again and again.. I'll try with FTB Inventions. What blocks were used when it blew up?

**Comment by KingDGrizzle** [comment]
And this has nothing to do with Tough as Nails, so you can remove that

**Comment by vladfrangu** [comment]
I can't get the machines to overload. What steps do you use?

**Comment by vladfrangu** [comment]
And I can let you know one thing..

Minecraft, if showed a illegal metadata, it shouldn't crash, but when used, the block is placed as its default metadata, meaning any meta above the real one will be the first one, if that makes sense

**Comment by erindal** [comment]
@KingDGrizzle this is in 1.10.2, not 1.7.10

**Comment by Dragon2488** [comment]
I don't sure it's the issue if you can't reproduce it.
