### ISSUE TITLE
Items that hold energy seem to provide energy even when they are empty

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#680]
I have enabled Tesla only for this.
![2016-07-17_21 08 20](https://cloud.githubusercontent.com/assets/12499779/16904390/12282432-4c63-11e6-9a08-d43cd9f23993.png)

**Comment by modmuss50** [comment]
Oh huh, yeah thats an issue.

**Comment by erindal** [comment]
As a note, this only works in machines that charge items, like the batbox and mfe.

**Comment by Dragon2488** [comment]
Will fix in 2 hours.

**Comment by Dragon2488** [comment]
Fixed
