### ISSUE TITLE
various issues

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#685]
Before i start, i'm on the latest 1.10.2 build of forge, TR & RC(configs are set to RF usage for ease of testing). All of the listed below were occurring in 1.9.4 as well.

A lot of what i'm about to list is already covered in other already posted issues, but i'll still list them anyway.
1. industrial grinder isn't detecting the multiblock or accepting water
2. implosion compressor isn't detecting the multiblock
3. distillation tower has no gui so can't tell if it's not detecting the multiblock or accepting power & fluids
4. industrial sawmill isn't accepting water
5. other machines not accepting power;
- electric furnace
- recycler
- scrapbox-inator
- when i was doing a creative assisted survival play through i got a client crashing bug which wouldn't let you back in the world/server unless your inventory was edited to remove the culprit items. These items were specifically enderio dark steel armour with the lapatronic energy orb chestplate (the crash triggered when i put the helmet on after the boots & leggings were already on; i may still have the crash report).

So of the 7 multiblock machines only 2 work of which one of these relies upon another one to gets its items to do its process (industrial blast furnace needing the industrial grinder).

With all that said be it known or not; it would be great if this mod worked as it'll make our planned custom recipe pack more enjoyable, harder & lenghty in a general progression sense. We 

Thanks, The_Creamster.

**Comment by Dragon2488** [comment]
Power issues should be fixed in #687. I'll take look at multiblocks tomorrow. Always want to add play with them :)

**Comment by varukasalt** [comment]
I am having issues automating the grinder. It's supposed to accept water in the bottom slot and ore in the top, but no matter where I try to place things, they will go to either slot.

**Comment by Dragon2488** [comment]
Power issues fixed, sawmill too. Industrial Grinder and Implosion Compressor are in process.

**Comment by Dragon2488** [comment]
Fixed all multiblocks.
