### ISSUE TITLE
The chainsaw and diamond chainsaw recipes are broken

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#688]
The normal chainsaw recipe is for the diamond chainsaw, and the normal chainsaw has no recipe.

![2016-07-22_20 54 39](https://cloud.githubusercontent.com/assets/12499779/17074781/bccbf672-504e-11e6-8f43-4cd83b030f42.png)

**Comment by modmuss50** [comment]
Oh yeah, I will look into it once im back from my holiday.

**Comment by erindal** [comment]
I feel bad modmuss I'm giving you so much work to do when you get back :P

**Comment by modmuss50** [comment]
Meh its fine

**Comment by Zygimantass** [comment]
Fixed in the latest build.
