### ISSUE TITLE
Assembly machine Crafttweaker scripts don't accept ore dictionary as input

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#689]
MT.log error: http://pastebin.com/xmMirmkP
scripts.zs file: http://pastebin.com/v83Lbpqh

I have two assembly machine scripts. The first one (for glass panes) working perfectly fine. The second one throws an error. No idea why. Removing the working script doesn't fix the issue. It thinks something is a string (no idea why) as opposed to a valid itemstack.

I've been informed this is a TechReborn bug by the CraftTweaker dev.

**Comment by modmuss50** [comment]
Humm, I will take a look into it

**Comment by erindal** [comment]
Okay I changed the ore:redstone and ore:diamond to the minecraft: versions, and it worked

**Comment by erindal** [comment]
Why did this get closed? Did it get fixed?

**Comment by modmuss50** [comment]
Should be
