### ISSUE TITLE
Tesla/RF Rebalance?

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#690]
4 Tesla (And therefore RF) is equal to 1 EU right? 

So having a generator output 16T (All generators are like this) and only hold 25 doesn't really make sense. I'm not sure about RF, and I'm also not sure about machine power consumption.

The same goes for transformer buffer sizes.

**Comment by erindal** [comment]
https://github.com/Darkhax-Minecraft/Tesla#standards

**Comment by erindal** [comment]
Also its worth nothing the coal generator (For instance) outputs 64 EU/t normally

**Comment by Prospector** [comment]
The machines aren't supposed to hold much power, but yeah generators should hold more than normal machines.

**Comment by erindal** [comment]
Also I think the EU to RF/Tesla ratio is inverted. I have it set to the normal 4 but instead its 1/4

**Comment by Prospector** [comment]
hmm, probably is.

**Comment by erindal** [comment]
Also I changed the config to .25 and it reset itself to 4.

**Comment by Dragon2488** [comment]
No it isn't inverted. Conversion always was 4 RF per 1 EU and not inverted.

**Comment by Dragon2488** [comment]
Also generators and machines buffed in last commits.

Generators:
Coal / Semifluid / Solar Panel / etc = 8000EU/32000RF
Thermal = 16000EU/64000RF 
Diesel/Gas = 64000EU/256000RF
Dragon Egg = 256000EU/1024000RF
Fusion Reactor = 10000000EU/40000000RF

Machines:
Tier 1 (32EU/Low) = 16000EU/64000RF (Furnace, Grinder, Extractor, Compressor, etc)
Tier 2 (128EU/Medium) = 64000EU/128000RF (Most multiblocks, Industrial Machines, Rolling Machine, Recycler)
Tier 3 (512EU/High) = 256000EU/1024000RF (Blast furnace)
Tier 4(2048EU/Extreme) = 1024000EU/4096000RF (Lightning Rod, Matter Fabricator)
Tier 5(8192EU/Insane) = 10000000EU/40000000RF (Fusion Reactor, AESU, LESU, IDSU)

**Comment by Dragon2488** [comment]
Hmm, maybe conversion need rebalance for 1.10.2, RF isn't buffed now.

**Comment by Dragon2488** [comment]
Maybe it should be 2 RF to 1 EU, or 1.5 RF to 1 EU

**Comment by erindal** [comment]
> No it isn't inverted. Conversion always was 4 RF per 1 EU and not inverted.

But that's not what it is. The values were 64 EU/t and 16 T(or RF)/t when I checked.

**Comment by erindal** [comment]
Now that said, a device that stores 4000000 RF and 1000000 EU (MFE) is a huge difference. I'm not sure the 4 to 1 ratio is right, as you've said.

**Comment by modmuss50** [comment]
The config setting is an int

**Comment by modmuss50** [comment]
Fixed in RC PR
