### ISSUE TITLE
Industrial grinder and implosion compressor bug

### ISSUE THREAD

**Issue by ChrisMar00** [TechReborn/TechReborn#691]
When i create the multiblock structure for the industrial grinder and implosion compressor and power them,the energy icon doesn't charge up and the grinder doesn't work.This happens to the compressor too.I'm using the FTB Inventions pack with the latest version for the reborn core and the techreborn.
The version of forge is:10.13.4.1614.

**Comment by Dragon2488** [comment]
Duplicate. Already fixed.
