### ISSUE TITLE
Major Retrogen performance problem(1.10.2)

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#692]
I'm back again this time with one which renders any world unplayable!!!
http://www.minecraftforge.net/forum/index.php/topic,40830.0.html I originally posted it there but after some elimination testing it came down too if the retrogen option was on it would tps lag. As i mention in the Minecraft Forge post i can't give the full log unless it's compressed and sent via email directly or i put it up as a downloadable file.

Which option do you want?

Cheers, The_Creamster.

**Comment by modmuss50** [comment]
When i get home i can have a poke around at it and try and improve it

**Comment by modmuss50** [comment]
To prevent the lag for now disable it in the ores.hjson file.

**Comment by modmuss50** [comment]
Linked to: https://github.com/TechReborn/TechReborn/issues/699
