### ISSUE TITLE
I think its time to move on (TechReborn2) ?

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#695]
So the src for TechReborn has become a mess and I and over TechReborn devs have got sick of working on the mod.

I am considering restarting the mod as TechReborn 2 

Less block ID's
Remove RF/Tesla support as will make the code cleaner
Remove cables (If we go back to IC2 only these are not needed)
Use jsons no more JsonDrstroyer
Remove base IC2 blocks (IC2 addon only)

any more suggestions are welcome

Any of the current devs do not worry the mod will still be on the TechReborn github and anyone who wants to help can.

We need to stay more organised this time and try and not repeat code all over the place

**Comment by modmuss50** [comment]
We are working on techreborn 2

**Comment by Dragon2488** [comment]
No, it's stupid idea. 

First, I re-wrote tesla and RF support and reorganized code in RebornCore and it's clean now. 
Second, look at cables, they work perfect now and much smarter than IC2 cables.
Making IC2 addon makes TR depend on it. It's mean that TR will stay on old versions before ic2 updates.
Less block id is a bad practice. Look at GregTech and what it became with meta tile entities and meta ores.
Roading away from JsonDestroyer is required, but can be done without mod rewrite.
And the most important part, it will throw mod back in development very far away.
Totally, i DON'T LIKE this idea

**Comment by Dragon2488** [comment]
And i think rewrite wont make devs work on TR and only throw mod back.

**Comment by gigabit101** [comment]
Yes I can see the that and it looks good I closes the issue because modmuss showed me all the work you have been doing. I suggested this because I no the code is/was a mess and in my mind at least it would be faster to rewrite than clean but after all the work you have been doing this seems unfair.

I will be coming back and working on the mod again soon and wish to do a large clean/overhaul of the code Base I also wish to move so things over to capabilities as they will also allow for a much cleaner code Base

**Comment by Dragon2488** [comment]
Yes, moving to capabilities is very high priority. I wanted to make it myself, but there are too many uses of interfaces. Rewrite isnt difficult, but boring. Also, if there is issue about TR, what everybody think about vein ore generation and moving closer a bit to current GT? I am not talking about making TR realistic and difficult, i'm talking about more interesting and balanced crafting.

**Comment by gigabit101** [comment]
Moving to capabilities i can do easy I will just handle it all in Tilebase and update the Inventory class in RebornCore to use then and same for tank I have already done this in my new mod and it works well

**Comment by gigabit101** [comment]
And for what I want to do most move is move most things to TileBaseMachine to allow less copy paste same for guis and containers

**Comment by Dragon2488** [comment]
Yes, i did same in IEnergyTile and implemented methods in place. In this scenery in TilePoweredBase I nedded to implement only RF and Tesla plus setEnergy and getEnergy. I also think that we need to road away from JsonDestroyer ASAP.

**Comment by gigabit101** [comment]
Yes I agree I already have experience working with the json system so moving over will be boring but easy Ai may work on that today

**Comment by Dragon2488** [comment]
And if you want changes to guis, i have already fixed fluid drawing (Look at GuiIndustrialSawmill) and started gui widgets system (subpackage widget). It need basic widgets like fluid tank, progress bar, etc and client sync

**Comment by Dragon2488** [comment]
And there are new textures in run/resourcepacks/unity, they need move. Can you please do it in next commit?

**Comment by gigabit101** [comment]
Yeah will do that also the tank render is it animated as I already have code to grab the animated version if exist else grab still

**Comment by Dragon2488** [comment]
And also tank renderer shouldnt resize fluid texture. It should cut and duplicate it.

**Comment by Mathiey** [comment]
Its a good idea cause there is a lot of bug with ic2 item / TechRebon items and IC2 have already a lot of addons and a big community, so if techreborn is not compatible with ic2 a lot of people will not use it ...

Just an exemple : i put an ic2 machine on a techrebon cable and my game is crash and cant use it again without use and external editor ...

Be an ic2 exp addon like gregtech is the best way for all

**Comment by modmuss50** [comment]
Can I have the crash log, TR should be compatible with ic2

**Comment by modmuss50** [comment]
Complaining doesnt get things fixed

**Comment by Mathiey** [comment]
I just create a new world with a generator / cable from TR and the MFSU from IC2 :

http://pastebin.com/SPULhxzg

And now impossible to load again the map

**Comment by modmuss50** [comment]
Yeah thats a know bug, It will get fixed at somepoint. A work around is to install Tesla.

This can be found here: https://minecraft.curseforge.com/projects/tesla?gameCategorySlug=mc-mods&projectID=244651

**Comment by Mathiey** [comment]
Ok i'll try thanks

**Comment by Mathiey** [comment]
humm it dont crash anymore but i cant connect them together its normal ? 

So we need 2 EU ? EU for ic2 and EU for TR ?

**Comment by Zygimantass** [comment]
close ?

**Comment by Zygimantass** [comment]
offtopic: modmuss50, can you check your reddit messages?
