### ISSUE TITLE
Server Issue with Mekanism 

### ISSUE THREAD

**Issue by MainFreak** [TechReborn/TechReborn#696]
I am playing on a server with Mekanism and Tech Reborn. Since both mods run on RF I tried to charge a Diamond Drill in a Energy Cube (Mekanism) but as soon as I did so, the server crashed. It is still down and tries to start.
 Minecraft Version: 1.10.2
 Mod Version: Most recent at the time of this post
 Modpack: Material Energy^Ex

**Comment by modmuss50** [comment]
Could I have the log please?

**Comment by MainFreak** [comment]
I do not own the server, but I will try to get it.

**Comment by MainFreak** [comment]
Unfortunately the server owner deleted the crash log and when I tried to reconstruct it in a custom pack it didn't let me put the drill inside the cube.

**Comment by MainFreak** [comment]
I tried to get the Log. I was unable but after an Update I was unable to put the Drill in the Energy Cube anymore. I hope this issue is closed then?

**Comment by modmuss50** [comment]
No it still happens, I tested it

**Comment by Prospector** [comment]
ah okay

**Comment by ProsperCraft** [comment]
if you are still looking for crashlogs- here they are -

https://github.com/aidancbrady/Mekanism/issues/3825
