### ISSUE TITLE
1.10.2 Retrogen crash

### ISSUE THREAD

**Issue by Keridos** [TechReborn/TechReborn#699]
Got this crash on Forge 12.18.1.2011 with TechReborn 1.3.4.11 when retrogenning ore: https://gist.github.com/Keridos/bce1e4b06f843f54418da8464317bce3
And this happened, too: https://gist.github.com/Keridos/3c7569345abfba7ac84cefdc83f49b61

**Comment by PrincessOfEvil** [comment]
I'm not sure these mods are 1.10.2 compatible. CCC is said not to be, for example(although it never crashes on its own).

**Comment by Keridos** [comment]
Does CCC touch world generation?

**Comment by PrincessOfEvil** [comment]
No, it's just an example. But i don't see anything about TR in the log, just a massive BoP>vanilla>pam>vanilla>chisel>vanilla>BoP loop.

**Comment by Keridos** [comment]
Well, It easy to detect, disabling retrogen fixed this. Although I am now not sure if it really is TR, flat bedrock retrogen has similar issues (no regeneration and later it just flat out crashes the server).

**Comment by PrincessOfEvil** [comment]
Okay, looked at it in Eclipse, definitely someone hacking into generation. Try without BoP(in singleplayer).

**Comment by Keridos** [comment]
Removing BoP does not solve this issue, weird.

**Comment by modmuss50** [comment]
Whats the crash without BOP?

**Comment by Keridos** [comment]
https://gist.github.com/Keridos/2e5a9be21f17ee9608156612ca706b4b

**Comment by modmuss50** [comment]
java.lang.OutOfMemoryError: GC overhead limit exceeded

You either are not giving mc enough ram, or its having a mem leak.

**Comment by modmuss50** [comment]
Looks like it could be a mem leak, I will look into it

**Comment by modmuss50** [comment]
Humm, after playing around with the retro gen in my dev world I cannot get it to work, or crash, or lag.

**Comment by Keridos** [comment]
It seems to happen without chisel and with, and removing BoP doesnt fix it either, gave MC 4GB of ram, that should be plenty.

**Comment by covers1624** [comment]
Log on the latest please?

**Comment by Keridos** [comment]
That was a combination, I had the crash with (BoP, no chisel), (no BoP, but had chisel) and (chisel and BoP) These are at least I think so the three crashes I posted here. Being quite busy atm, so testing might take a bit longer. I am not sure what causes this crash, but I remember reading something about that in the forge patch notes, but it might be unrelated.

**Comment by covers1624** [comment]
Just a bit of advice, assuming crashes are the same is a really bad idea because 90% of the time they are not, not trying to be a dick just want to get to the bottom of this.

**Comment by Keridos** [comment]
That is why I mentioned I think so, it crashed a few times, mostly with different crash logs. The only things most of these had in common that they either had GC overflow or a very very very circular stacktrace or a stack length overflow (forgot how that is actually called). So it most likely is a bug that caused the same method to be called over and over during retrogen.

**Comment by covers1624** [comment]
Yes I know, but in order to debug it I need the latest log as your origional had method calls to bop and that has been removed since then.

**Comment by modmuss50** [comment]
No update on this, open a new issue if its still broken
