### ISSUE TITLE
Config for all recipes + New addition ( JSON file for adding recipes )

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn#70]
The old GT had a config with all of it's machine recipes in it iirc, would be nice if you include it ^.^ Would basically allow people to modify recipes if they need to for their modpack for x reasons. 

Optionnally, it would be nice to have our own JSON file with a basic syntax to add recipes :D ( it would save us time from having to do modtweaker compatibility ), here is an exemple of syntax : 

MachineName("x";"y optionnal"){("list of outputs seperated with ; like here") , ("list of additionnal bonus outputs seperated with ; like here")}
You can use UN or OD, in both cases, put your your names in <> and if you use OD, use it like this : 

<ore:exempleshapeExempleMaterial>

add * x for specifying the number of items used.

Exemple :
BlastFurnace(<ore:plateCarbon> * 32 ; <minecraft:iron> ) {(<ore:ingotDamascusSteel> ; <ore:dustAsh> * 8)}

**Comment by TheQuantumGeneral** [comment]
Any pack doing modifications is going to have Minetweaker/Modtweaker installed anyway because they work great, have a extremely easy to use scripting language, can be updated in real-time and support is pretty easy to implement with its API.

Greg probably only had it because it would have predated Modtweaker.

Even if you do this, strongly consider Minetweaker support additionally/instead.

**Comment by Carbon-Ghost** [comment]
I am not talking about crafting recipes but machines one, and modtweaker doesn't support us yet and to create support it might take time...

**Comment by TheQuantumGeneral** [comment]
Can either wait for Modtweaker support if someones in close contact with Jared or use the Minetweaker 3 API, detect it on launch and if its not there fall back to standard recipes.

Here's a mod that added Minetweaker support to Gregtech as an example - https://github.com/Dream-Master/Minetweaker-Gregtech-5-Addon

**Comment by Carbon-Ghost** [comment]
I know Deam-Master, but jared atm have exams and already need to update other mods that worked before like mekanism, that's why ..

**Comment by modmuss50** [comment]
I can make it work with MineTweaker? Shouldn't be too hard

**Comment by Carbon-Ghost** [comment]
You can try if you want ^^ , also sorry, I derped, should have put this issue in TODO Techreborn >.<°

**Comment by modmuss50** [comment]
Can someone help me make a script to test this, i've never used minetweaker before ;(

**Comment by TheQuantumGeneral** [comment]
import mods.techreborn.alloySmelter; //Don't know if the import was needed

//input1, input2, output1, tickTime, euPerTick
mods.techreborn.alloySmelter.addRecipe(<minecraft:gold_ingot>, <minecraft:iron_ingot>, <minecraft:diamond>, 20, 100);

Throwing error - No such member: techreborn

**Comment by modmuss50** [comment]
ok thanks for giving me something to test with :)

**Comment by modmuss50** [comment]
Do you know if that worked?

**Comment by TheQuantumGeneral** [comment]
Got further than it did before, not sure of the syntax of your Minetweaker support

I tried - mods.techreborn.alloySmelter.addRecipe(minecraft:gold_ingot, minecraft:iron_ingot, minecraft:diamond, 20, 100);

Before it was saying "No such member - techreborn"
Now its saying "expected -- )"

So I don't know the correct format for the script in this case.

**Comment by modmuss50** [comment]
We might need to think how we want to do this, becuase when I export the machine recipes to a json file its 12000 lines long.

https://gist.github.com/modmuss50/e0bb9990eff7f0cf008a

Im not sure of a better way of allowing recipes to be disabled.

That does not include vanilla crafting table recipes, forestry machines, Natura, and thumcraft recipes.

**Comment by modmuss50** [comment]
We could use that json format for adding recipes, but im not sure what we would use to disable them

**Comment by jaredlll08** [comment]
Pinging me is always good ;)

So how many machines are we talking about here?
Do I need to use reflection to add/remove recipes?
Just a heads up, it is usually <output>, <input>, <others>

**Comment by modmuss50** [comment]
Nope, I started on a minetweaker support but I don't know how to do it, I will send you the details on how the system works when I get to a computer. But all the recipes are handled in one array list.

**Comment by jaredlll08** [comment]
I hope you mean each machine has its own array...

**Comment by modmuss50** [comment]
Nope, one array. 

https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/api/recipe/RecipeHandler.java#L19

Thats an array of IBaseRecipeType, you can get the machine name from there. You can see the list of machines and their names here:

https://github.com/TechReborn/TechReborn/tree/master/src/main/java/techreborn/api/recipe/machines

I had a go at adding support here, https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/compat/minetweaker/MTAlloySmelter.java

but as @TheQuantumGeneral said it was not working.

I dont mind if you want to add the support into your mod. I hope that is all the info you need.

**Comment by modmuss50** [comment]
oh and you can get all the recipes for a certain machine here:
https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/api/recipe/RecipeHandler.java#L34

**Comment by Carbon-Ghost** [comment]
@jaredlll08 : Get some rest first, you are sick after all :c It's low priority ^^

**Comment by jaredlll08** [comment]
I feel bad though, since I had exams, then I went away for a week, now I am
sick, and until the 19th of August I have some tasks to do for school :/

**Comment by modmuss50** [comment]
There is no rush, dont worry about it

**Comment by Carbon-Ghost** [comment]
Like I said, get some rest, no need to rush, it's bad for your health :c

**Comment by modmuss50** [comment]
Ive fixed MT support, so use that

**Comment by TheQuantumGeneral** [comment]
Any documentation on the syntax?

**Comment by modmuss50** [comment]
mods.techreborn.alloySmelter.addRecipe(<minecraft:gold_ingot>, <minecraft:iron_ingot>, <minecraft:diamond>, 20, 100);

mods.techreborn.assemblingMachine.addRecipe(<minecraft:gold_ingot>, <minecraft:iron_ingot>, <minecraft:diamond>, 20, 100);

mods.techreborn.blastFurnace.addRecipe(<minecraft:gold_ingot>, <minecraft:gold_ingot>,<minecraft:iron_ingot>, <minecraft:diamond>, 20, 100, 1000);

mods.techreborn.centrifuge.addRecipe(<minecraft:gold_ingot>, <minecraft:iron_ingot>, <minecraft:gold_ingot>, <minecraft:iron_ingot>, <minecraft:diamond>, <minecraft:diamond>, 20, 100);

I will get proper ones done when I have the time, I will look into getting a wiki on the website or something. They all have remove recipe function as well.

**Comment by jaredlll08** [comment]
Should I add it to
Www.blamejared.com/modtweaker/

**Comment by modmuss50** [comment]
yes!, I will send you a list of all the machines when i've finished adding support for them

**Comment by Carbon-Ghost** [comment]
Nice :D Blame jared !

**Comment by jaredlll08** [comment]
Just link me to the classes, that site is automatic, judt needs .java files

**Comment by modmuss50** [comment]
Thats cool :)

https://github.com/TechReborn/TechReborn/tree/master/src/main/java/techreborn/compat/minetweaker

Ive not finished adding all of our machines, I would wait till I have finished.

**Comment by modmuss50** [comment]
They are all there now :)

**Comment by modmuss50** [comment]
@jaredlll08 did you ever get around to adding it?
