### ISSUE TITLE
Machines don't work when placed directly next to generator

### ISSUE THREAD

**Issue by Hobby-boy** [TechReborn/TechReborn#702]
I've noticed that if I place a machine, such an electric furnace, directly next to a generator without a cable, the generator doesn't power the furnace. It does work however if I have a cable inbetween. 

Using 1.3.4.11 for 1.10.2 with Forge 12.18.1.2011

**Comment by modmuss50** [comment]
![2016-08-01_10 18 38](https://cloud.githubusercontent.com/assets/4324090/17289369/57d542f2-57d1-11e6-9ca6-c12a5bd8e243.png)

Its been fixed in dev versions
