### ISSUE TITLE
Placing Fluid Generator

### ISSUE THREAD

**Issue by DoughnutDev** [TechReborn/TechReborn#704]
After placing the Fluid Generator in TechReborn version 1.10.2-1.4.0.35 it will cause a ton of FPS lag.

**Comment by modmuss50** [comment]
Do you mean the semifluid generator?

**Comment by modmuss50** [comment]
![2016-08-01_09 53 35](https://cloud.githubusercontent.com/assets/4324090/17288593/dd3ae662-57cd-11e6-95bd-418ea08eb28c.png)

Ok yeah, it does

**Comment by modmuss50** [comment]
I think this needs a bit of optimization: https://github.com/TechReborn/RebornCore/blob/1.9.4/src/main/java/reborncore/common/tile/TilePowerProducer.java#L41

**Comment by utoc** [comment]
EDIT: Removed, created new issue

**Comment by modmuss50** [comment]
Yes please, I will go through the issues after TMT

**Comment by modmuss50** [comment]
Working fine in newest build
