### ISSUE TITLE
Various bugs (I can fix some of them, too)

### ISSUE THREAD

**Issue by ThexXTURBOXx** [TechReborn/TechReborn#706]
Hello TechReborn-Dev-Team,

I have some obvious bugs (I will fix some of them myself and create a PR. If you don't want my help, then just close the PR):
- [ ] Much textures missing: http://imgur.com/kgZSNu2 (Fixing in progress)
- [x] Some names missing
- [x] JEI showing ambigious recipes for cells (if you look after the e.g. Wolframium Cell, then it shows the recipes for EVERY cell, same thing happens with all cells): http://imgur.com/Bby1T1v (Fixed in JEI 3.7.9)
- [ ] OreDictionary-Entries of the Cells let the Informationbox (if you hover over them) explode (See here: http://imgur.com/mVyF32s)
- [ ] In ores.hjson-configfile: Typo ==> Tungston Ore

Now in Detail:
Textures missing for those:

TODO (Please someone else make them):
- [ ] Fluid Sulfur
- [ ] Fluid Sodium Sulfide
- [ ] Fluid Nitro Diesel
- [ ] Fluid Nitro Carbon
- [ ] Fluid Carbon Fiber
- [ ] Fluid Sulfuric Acid
- [ ] Fluid Diesel
- [ ] Fluid Carbon
- [ ] Fluid Oil

Already pushed:
- [x] Diamond Jackhammer
- [x] Diamond Saw Blade
- [x] Superconductor
- [x] Frequency Transmitter
- [x] EV Transformer
- [x] Battery
- [x] Silicon Ingot
- [x] Small Pile of Andesite Dust
- [x] Small Pile of Diorite Dust
- [x] Small Pile of Granite Dust
- [x] Lazurite Plate
- [x] Ruby Plate
- [x] Sapphire Plate
- [x] Peridot Plate
- [x] Red Garnet Plate
- [x] Yellow Garnet Plate
- [x] Refined Iron Plate
- [x] Advanced Alloy (Plate version)
- [x] Hot Tungstensteel Nugget
- [x] Tungstensteel Nugget
- [x] Refined Iron Nugget
- [x] Diamond Nugget

Translation Missing:
- [x] fluid.fluidSulfur
- [x] fluid.fluidsodiumSulfide
- [x] fluid.fluidnitrodiesel
- [x] fluid.fluidnitrocarbon
- [x] fluid.fluidcarbonfiber
- [x] fluid.fluidsulfuricacid
- [x] fluid.fluiddiesel
- [x] fluid.fluidcarbon
- [x] fluid.fluidoil
- [x] tile.techreborn.evtransformer.name
- [x] item.techreborn.ingot.silicon.name
- [x] item.techreborn.dust.obsidian.name
- [x] item.techreborn.plate.Ruby.name
- [x] item.techreborn.plate.Sapphire.name
- [x] item.techreborn.plate.Peridot.name
- [x] item.techreborn.plate.RedGarnet.name
- [x] item.techreborn.plate.YellowGarnet.name

**Comment by ThexXTURBOXx** [comment]
May I go ahead and fix the lang-files and maybe some textures (if there are just some typos)? If you want, I could make some textures for some Items/Fluids.

**Comment by modmuss50** [comment]
Go for it, just open a PR. This was closed as it contained loads issues in one issue.

**Comment by ThexXTURBOXx** [comment]
Ok, fixed translations already... Going for the textures now. Thanks! :)

**Comment by ThexXTURBOXx** [comment]
_1 question: There is a ruby plate ingame, but in the ItemPlates-class is no ruby-plate in the types[]-array. How could this be? o_O
Same thing with Sapphire, Peridot, Red Garnet, Yellow Garnet and Refined Iron btw_

**Forget about it :) Didn't read the comments in the code :)**

**Comment by ThexXTURBOXx** [comment]
The issue with the information-box is there, because of any other mod. I think it is WAWLA, but I don't know... Anything is making it explode ;D

**Comment by modmuss50** [comment]
ores.hjson should be that as its using https://hjson.org/

**Comment by ThexXTURBOXx** [comment]
Ah ok, didn't know that format... Sorry

**Comment by ThexXTURBOXx** [comment]
@mezz Could you please take a look at the JEI-recipe-bug (The 4th checkbox)? I don't know how to fix it and I think, that it has high priority...

**Comment by Dragon2488** [comment]
JEI ignores stack tag while searching recipes

**Comment by mezz** [comment]
You need to register your item with the `ISubtypeRegistry` to tell JEI how to interpret its NBT.
However, this is such a common issue that I am probably going to use the fluid capabilities on items to differentiate them automatically, no need to make everyone implement the same thing on their fluid container items.

**Comment by mezz** [comment]
The JEI issue should be solved by this commit: https://github.com/mezz/JustEnoughItems/commit/983503201e1fa0e5c793f297aa4cb06b8e4897c1
It will automatically detect fluid in the items and differentiate them that way by default.
This is added in JEI 3.7.9

**Comment by ThexXTURBOXx** [comment]
Wow, thanks! This is really nice of you :)

**Comment by modmuss50** [comment]
Most of this seems fixed, so closing.
