### ISSUE TITLE
Multipart Cable Crash

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#708]
When i placed a glass-fibre cable it gave me a multipart crash(RF power disabled to test the RF-EU cable conversion method in latest update)
https://gist.github.com/the-creamster/4e223c140468e3b8c1fba2fe994140ba

**Comment by modmuss50** [comment]
It looks like the new cables crash if tesla isnt installed. So install tesla and it shouldnt crash. I will fix this soon.
