### ISSUE TITLE
More machine bugs

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#713]
I'm back again this time with more bugs to report;
1. The multiblock machines work apart from the industrial sawmill which isn't detecting it's multiblock(or i've built it wrong; built it according to the gregtech wiki) with the minor gui big of still displaying "incomplete multiblock" across all of them except the industrial blast furnace
- jei is showing no log recipes for the industrial sawmill and the machine gui has no 'show recipes' button
- The standalone machines are getting inconsistent power levels(have glass fibre cables connected to a creative capacitor bank, using 'the one probe')
- electric furnace 1/16k eu
- electric alloy furnace 1/8k eu
- industrial centrifuge 10/64k eu
- assembling machine 10/64k eu
- industrial electrolyzer 1/64k eu(advanced machine frame texture on sides, intentional?)
- grinder 8/1k eu
- scrapbox-inator 1k/16k eu
- chemical reactor 10k/8k eu
- rolling machine 100k/64k eu
- matter fabricator 100m/1m eu

I'm using forge build 2039 as another mod in the pack crashes with anything higher if on the latest version.

Cheers, The_Creamster.

**Comment by Dragon2488** [comment]
Because Industrial Sawmill hasn't got recipes at all. It only process wood.

**Comment by Dragon2488** [comment]
And what is "incosistent power levels"?

**Comment by the-creamster** [comment]
Firstly the industrial sawmill isn't even processing the stack of logs i put in it so it's not detecting the multiblock or i built the multiblock wrong(a ring of 8 standard around a single reinforced).

Secondly the inconsistent power levels are as i wrote; machines not getting enough power or too much. So the grinder is only receiving 8 eu instead of the 1k eu which is its internal buffer full.

As for the 'incomplete multiblock' message in the multiblock machine gui's a line of code somewhere may have been missed. Great job getting TR to the stage it is at presently :)

Cheers, The_Creamster.

Edit:
i can get a collection of pretty pic's for your reference?? if you'll need them.

**Comment by the-creamster** [comment]
![2016-08-03_12 03 57](https://cloud.githubusercontent.com/assets/2037833/17351680/14b52ccc-5974-11e6-81bf-1093ebb8fc8e.png)
![2016-08-03_12 26 07](https://cloud.githubusercontent.com/assets/2037833/17351900/ef0edd36-5975-11e6-9858-9c55058b3d1c.png)
![2016-08-03_12 25 52](https://cloud.githubusercontent.com/assets/2037833/17351906/f9d9d0ae-5975-11e6-8f67-6ec8ef196dda.png)
![2016-08-03_12 27 03](https://cloud.githubusercontent.com/assets/2037833/17351910/01a0180c-5976-11e6-95b2-c5cfe41fd855.png)
![2016-08-03_12 26 50](https://cloud.githubusercontent.com/assets/2037833/17351933/2e2ea686-5976-11e6-95f5-f15604ecee0c.png)

**Comment by the-creamster** [comment]
Update for the standalone machines:
- breaking & replacing the power connection at any point made no difference to the power contained within the machines
- breaking & replacing the machine is now resulting in the machines getting no power

**Comment by Dragon2488** [comment]
Firstly:
Sawmill multiblock is:
SSS 
SSS
SSS

AAA
A   A
AAA

SSS
SSS
SSS

Where:
A - advanced machine casings
S - standard machine casings

**Comment by Dragon2488** [comment]
Secondary, grinder perfectly receives like other LV machines 32 EU/t (or 128 RF/t)

**Comment by the-creamster** [comment]
As far as the industrial sawmill goes the multiblock format you gave me didn't work regardless of where i placed the machine or whether the multiblock had water inside of it;
![2016-08-03_16 45 35](https://cloud.githubusercontent.com/assets/2037833/17356342/3fc68156-599a-11e6-9fa8-a9028d838e2c.png)
I tried it with the reinforced casings as the middle ring to no avail.

When it comes to any machine with no power i've narrowed it down to the cables(any RC-MCMP cable) aren't pulling/accepting RF when directly connected to a RF generator/storage block with the rf config option enabled; but any machine gets power when connected to a RF generator/storage block or RF conduit/cable.

**Comment by Dragon2488** [comment]
Oh. Not **advanced**, but reinforced in the middle
Controller on top.

**Comment by Dragon2488** [comment]
Freezer need only one-layer reinforced base.

**Comment by the-creamster** [comment]
The vacuum freezer worked as you can see it in the above picture so i'll try the single layer variant(it works as a single layer of reinforced, thanks for that cheaper pointer).
![2016-08-03_18 27 02](https://cloud.githubusercontent.com/assets/2037833/17359018/281b5276-59a8-11e6-9c08-c5d2df377592.png)
![2016-08-03_18 27 10](https://cloud.githubusercontent.com/assets/2037833/17359033/2fd6255e-59a8-11e6-94b4-d2c2b866400e.png)

Edit:
the industrial sawmill needs a bucket of water in the centre of the multiblock to function properly.

**Comment by the-creamster** [comment]
Just got this crash when reforming the multiblocks(had fluid conduit in hand);
https://gist.github.com/the-creamster/f0e32e5b86c5b2045bea05ed964674d1

I will have to reconfirm all the multiblocks tomorrow as i found the 'multiblock.java' files and can read the formatting.

**Comment by Dragon2488** [comment]
It looks like EIO bug.

**Comment by the-creamster** [comment]
I can confirm that all the multiblocks work :) and the enderio bug i've pinpointed the crash occurring when you go to edit a connections configuration with a conduit in your hand if that connection is a TR machine(will test with other blocks/machines) before reporting on their github.

Thanks for all the help clearing up the multiblock ambiguities(now you just need to document it in the in-game WIP manual)

Edit:
the RC-MCMP cables not getting RF power from a generator/storage block is still outstanding though

**Comment by HenryLoenwind** [comment]
Here' the Ender IO code:

```
    public static int getSlot(ISidedInventory inv, int slot, EnumFacing side)
    {
        int[] slots = inv.getSlotsForFace(side);
        if (slot < slots.length)
            return slots[slot];
        return -1;
    }

    public ItemStack getStackInSlot(int slot)
    {
        int i = getSlot(inv, slot, side);
        return i == -1 ? null : inv.getStackInSlot(i);
    }
```

The crash is getStackInSlot(5). Any hints what should be wrong?

**Comment by covers1624** [comment]
Could getSlotsForFace be returning null at any point?

----- Original Message -----

**Comment by HenryLoenwind** [comment]
Then it would crash on our side. Hasn't happened to Ender IO yet.

**Comment by covers1624** [comment]
Hmm, true, ill look in to it a bit more when i get home if i remember
and if i have time, TMT is on at the moment so time for other things
is limited at the moment. 

----- Original Message -----

**Comment by the-creamster** [comment]
I've recently done some SP semi-survival testing and found that some machine buffers empty faster than they can be refilled with the RF power option enabled and using EnderIO's ender energy conduits(20,480 RF/t per connection) when the conduit line is connected to a multiblock capacitor bank with an input/output of 375kRF/t per multiblock capacitor bank face.

The particular machines are:
- industrial grinder
- industrial electrolyzer

It's occurring for recipes that have a 30-100 EU/t usage within 3-5 sec and for the above machines with 10k EU internal buffers. Should they be draining that fast??

**Comment by modmuss50** [comment]
this issue is impossible to keep track of, only one issue per post. thanks.
