### ISSUE TITLE
Crash with shift-click in Generator

### ISSUE THREAD

**Issue by MapperTV** [TechReborn/TechReborn#714]
Using the very last versions of TR and RC downloaded on Curse (the versions published 22 hours ago):

I tried to fill a generator with logs and my client crashed (server is fine).

Crash log: http://pastebin.com/AFz7avJ4

It only happens if I try to input more items than the fuel slot can handle. Like if there are 32 logs and I try to shift-click 33 logs, it will crash, but if all the logs can go in then it's fine.

I also noticed copper cables got removed when updating. Not a big deal, just to say.

Thanks for updating.

**Comment by Zygimantass** [comment]
Fixed in dev build
