### ISSUE TITLE
Lava dupe with techreborn installed

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#720]
Latest 1.7.10 version
When right clicking lava with an empty cell you get 8 lava cells
one lava cell = one bucket of lava

**Comment by modmuss50** [comment]
Humm yeah thats an issue, I may not fix this for 1.7 though

**Comment by wormzjl** [comment]
Could you tell me where is the issue so I can fix it myself

**Comment by modmuss50** [comment]
I cannot seem to find it having after having a quick look.

**Comment by wormzjl** [comment]
Seems that this is the cause of problem
https://github.com/TechReborn/TechReborn/blob/1.7.10/src/main/java/techreborn/compat/recipes/RecipesIC2.java#L463

**Comment by modmuss50** [comment]
oh yeah, good spot. Even a github web edit should fix it.

**Comment by modmuss50** [comment]
If you want to fix it, edit that and bump the version and I can push it
