### ISSUE TITLE
Free saltpeter for everyone!

### ISSUE THREAD

**Issue by utoc** [TechReborn/TechReborn#722]
Hey guys!

We ran into a cute issue this morning as can be seen here: http://i.imgur.com/ExNQbia.gifv

When there are no items in the input slot of the grinder, it idly makes saltpeter.  Two at a time, it makes two more when you remove whatever is in the output slot.  I have had two separate users report this.

I removed all craft/modtweaker scripts to confirm this was not a script gone awry.  This happens in SSP and SMP.

I'm running FML 2046, TechReborn 1.4.0.41 and RebornCore 2.6.2.15 on Minecraft 1.10.2

**Comment by modmuss50** [comment]
Huh, that is a strange one.

**Comment by utoc** [comment]
I did remove all mods except TechReborn and RebornCore and confirmed this behavior is still present.

**Comment by modmuss50** [comment]
Yeah that is very strange then.

**Comment by Zygimantass** [comment]
We'll have to remove the saltpeter recipe, because there's no saltpeter ore.
