### ISSUE TITLE
Lapatronic Energy Orb Chestplate Issues

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#724]
I was attempting to retest a bug i was getting with the 1.9.4 version where you would crash if you equipped enderio dark steel armour(i found it triggered on the helmet; equiping order
1. boots
2. leggings
3. helmet)
in conjunction with the Lapatronic Energy Orb Chestplate but now in 1.10.2 to see if it still occurred. The crash triggered when the helmet was equipped. https://gist.github.com/the-creamster/357351ff8093c30c3d98ee040f43ec6f
As you can see by the above crash i can't even equip the Lapatronic Energy Orb Chestplate(latest 1.10.2 build) without crashing(the game crashes but just freezes the game giving no indication of a crash).

Note:
I deleted my initial 1.9.4 test pack so i don't have the crash report sadly; but the crash report referenced enderio only from memory. Will link this to the enderio github as it's a cross-mod issue.

Edit:
I'll create a 1.9.4 pack just to retest this bug specifically to see if i can get an exact recreation of it.

**Comment by the-creamster** [comment]
"1.9.4 testpack"
I've made progress, but at the same time no progress as i have 3 separate crashes which haven't even allowed me to get close enough to re-testing the crash in mind;
1. Every mod curse latest except TR(tried all builds and it stopped at the latest build)
https://gist.github.com/the-creamster/0e8fc94d70abeaa5c9820091e811fa86
2. All curse latest builds, no IC2
https://gist.github.com/the-creamster/be351ad4234774790d39acb3b3ff287a
3. All curse latest builds, with IC2
https://gist.github.com/the-creamster/a284f1da5dc269b603477d340b6438cb

Crash number 2(number 3 most likely) is the same for 1.10.2 with all the latest curse builds & forge build 2042.

So at this point i can't re-test the enderio dark steel armour in conjunction with lapatronic energy orb chestplate crash until at least crash number 2/3 are fixed; and that's even if the crash in mind is still occurring.

Cheers, The_Creamster.

**Comment by modmuss50** [comment]
The new power net is fucked up, I may have to go back to the old one.

and the first issue you have is you have the wrong reborn core version

**Comment by the-creamster** [comment]
Very strange; the latest release build available on curse for the 1.9.4 pack is a 1.10.2 MC version for both TR & RC??
I'll try to recreate crash number 1 with the latest 1.9.4 curse version of TR & RC and repost my results.

Edit:
I retested it with the latest curse 1.9.4 build and i got a picture of happiness :)
![2016-08-09_20 05 48](https://cloud.githubusercontent.com/assets/2037833/17512788/ead69a5a-5e6c-11e6-9573-07198c84a52e.png)
Now to see if i can get the orb chestplate crash with the 1.10.2 pack.

Edit 2:
Without IC2 crash number 2 is still occurring.
With IC2 crash number 3 is still occurring.

**Comment by modmuss50** [comment]
the 1.10.2 version should work on 1.9.4, but I would not recommend it. There should be no reason not to be on 1.9 atm

**Comment by the-creamster** [comment]
In regards to the new power being 'broken' according to your words i have a few thoughts:
1. What parts of the new power net make it better, more efficient, more performance friendly(compard to the old one)etc... that would make it preferable over the old one given that the current bugs with it will get reported/fixed??
2. What can me/others do as a user do to help with the bug finding/reporting for the new power net if we can do anything at all

Cheers, Cream Bun.

Note:
I co-admin a small community and am currently co-developing/refining a modpack so i'm testing/refining the modpack to our desired result and reporting any bugs we find. So i'm more than welcome to properly test the new power net if at all possible.

**Comment by modmuss50** [comment]
We have gone back to the old power system, when I get some time I will be going through all the issues related to it and seeing if they have been fixed.

**Comment by the-creamster** [comment]
It's not crashing :)
![2016-09-17_13 53 21](https://cloud.githubusercontent.com/assets/2037833/18605747/2e5a7f32-7cde-11e6-835d-74bba6f939d8.png)
