### ISSUE TITLE
[1.10.2] Break any of machines (maybe) doesn't let them unload properly 

### ISSUE THREAD

**Issue by 3TUSK** [TechReborn/TechReborn#726]
Quite not sure whether it is reported or not, but here is a screenshot from my dev environment (TechReborn-1.10.2-1.4.0.41, IC2-ex110-2.6.37, MinecraftForge 12.18.1.2044):
![2016-08-10_01 20 37](https://cloud.githubusercontent.com/assets/9113033/17526483/ffba3224-5e99-11e6-9cec-6fe2ffa89834.png)
As the pic shown on right side, ic2 cables are still "connecting" to those machines even if those machines are no longer existed.

**Comment by modmuss50** [comment]
IC2 bug I think, repoen if still an issue.
