### ISSUE TITLE
Pages worth of NPEs in client console for TechReborn Tile Entities

### ISSUE THREAD

**Issue by utoc** [TechReborn/TechReborn#727]
FML 2046
TechReborn-1.10.2-1.4.0.41
RebornCore-1.10.2-2.6.2.15

I had a honey of a time tracking this down but was able to with a lot of help from @mezz as can be seen here: https://github.com/mezz/JustEnoughItems/issues/382

The issue happens when chunks with TechReborn machines are placed in the world and then are present in loaded chunks.  Exceptions being thrown and it usually crashes the console window within 5-15 seconds of connecting.  You can review the log here: http://bbqsauce.terron.com/npe/NPE.txt
Full flight recording here: http://bbqsauce.terron.com/npe/jfr-08Aug2016.jfr

mezz compiled a version of forge that gave the xyz of the TEs that were having issues and they turned out to be TechReborn machines.  The log then looked like this: http://bbqsauce.terron.com/npe/NPE2.txt

I went to 3 different coords and found that all the blocks being reported were TR machines.  Batbox, Compressor, etc.

We updated to Jenkins 46, no luck
We downgraded to Curseforge's 38, no luck.

To reproduce the issue:  Load a world, throw a few TR machines in seperate places about 1000 blocks apart. Load into the first area with machines and you'll get a NPE for each machine present.  Then, /tp yourself to the second location with TE machines.  You'll get pages and pages of NPEs at this point from the location you've left as it is still chunkloaded.

Our workaround:  We make sure everyone taskkills their console window before connecting to the server.

reborncore.cfg can be found here: http://bbqsauce.terron.com/npe/reborncore.cfg
techreborn's main.cfg can be found here: http://bbqsauce.terron.com/npe/techrebornmain.cfg

Also, this might interest you: http://i.imgur.com/fyusfJB.png but this may be a completely separate issue entirely.

If I missed anything, please let me know.

**Comment by modmuss50** [comment]
I think think this has something to do with the new power net that was added, I already plan to revert to the older version of it as its causing loads of issues

**Comment by utoc** [comment]
I noticed on my bandwidth graphs that my upload is being significantly increased by this depending on how many bases are loaded with TR machines.. Is there any temporary bandaid I could apply in a fork to suppress the erroneous packets in the meantime while you're making changes?

**Comment by modmuss50** [comment]
Can you try with the latest TR from the jenkins, it may have been fixed? Ask me if you need a link

**Comment by utoc** [comment]
Jenkins says the latest builds have failed

http://modmuss50.me:8080/job/TechReborn/job/TechReborn-1.10.2/44/console

**Comment by modmuss50** [comment]
huh ok, I will fix that

**Comment by modmuss50** [comment]
http://modmuss50.me:8080/job/TechReborn/job/TechReborn-1.10.2/45/ get latest RC as well

**Comment by utoc** [comment]
Tested and working perfectly in a test environment.  Thank you SO much!  It will be a couple days before I can deploy this but I will report back then if there are unseen issues.  One thing I noticed though is that TR cables won't connect to Mekanism power sources anymore.  Would you like a separate issue on that or is this working as intended? I can have my users use Mek cables in the meantime as a workaround.  Thanks again!

**Comment by modmuss50** [comment]
I reverted back the the old power net(this fixed the issues) that doesnt support this. I should be able to add back in the support for RF and Tesla to this powernet. I will close this issue, and if you open another issue about adding the support back in it will prevent me from forgetting about it.

**Comment by utoc** [comment]
One other question so I don't clutter up the new ticket:  I noticed that Mekanism supports IC2 EU but not yours. Is there a way to remedy that? I would rather TR use EU only since it's the native energynet.

**Comment by modmuss50** [comment]
humm, I will look at mekanism at some point
