### ISSUE TITLE
[1.10.2] Request for TechReborn to support Tesla power

### ISSUE THREAD

**Issue by utoc** [TechReborn/TechReborn#730]
Greetings,

Now that the powernet has been rolled back to a more stable platform, I would like to humbly request TR  cables be able to pass Tesla power from other mods cables and suppliers.  I've done some testing and it appears that other mods' can power TR machines using their own means (Mekanism Cube and Universal Cable, EnderIO capacitor and Conduits) but TechReborn's cables will only accept power from its own blocks (BatBox, Transformers).

Additionally, I would like to request support for other mods power storage items, IE, batteries and power cells so that TR blocks like the BatBox can charge them as well as use their stored energy.

I hope I have not asked too much!  Thank you for your fantastic mod.

**Comment by Dragon2488** [comment]
It's stupid revert. Instead of fixing bugs, we just "revert big commits to old broken system", which actually isnt work at all.

**Comment by Prospector** [comment]
Fix your own broken system then.

**Comment by Dragon2488** [comment]
Yes, it's buggy but works instead of current system.
