### ISSUE TITLE
Crash after editing configs (1.10.2)

### ISSUE THREAD

**Issue by lilmoefow** [TechReborn/TechReborn#732]
Changing some of your config options seems to cause a crash with Tinkers

I have set these to options to false

```
B:"Compat:StandalonePartCompact"=false
B:"Compat:TechRebornParts"=false
```

I did this because i am using IC2 and would prefer your mod to be used as an add on in the pack im working on rather than a complete standalone.  I dont need all the extra items and i am assuming those two options are intended to revert TechReborn to use all IC2's materials.  

I am using

Forge-12.18.1.2052
industrialcraft-2-2.6.37-ex110
RebornCore-1.10.2-2.6.2.27-universal
TechReborn-1.10.2-1.4.0.45-universal
Mantle-1.10.2-0.10.4
TConstruct-1.10.2-2.4.0

If i make any config changes to your mod i get this crash here
http://pastebin.com/CxpMz1tD

If i disable tinkers and mantle after making config changes i get no crash

and if i dont make any config changes i can load all the mods fine.

**Comment by modmuss50** [comment]
This seems to be a thinkers issue, please post if its still an issue with the latest version of everything.

**Comment by lilmoefow** [comment]
It is still an issue with the latest versions of everything. And I understand that the crash log references tinkers, but the crash occurs when editing the configs of this mod.  So you can see why I would think the the issue would be on your end. 

Forge 12.18.1.2095
Mantle-1.10.2-1.0.0.jar
TConstruct-1.10.2-2.5.3.jar
RebornCore-1.10.2-2.7.3.46-universal.jar
TechReborn-1.10.2-1.4.6.67-universal.jar

**Comment by modmuss50** [comment]
Ok thanks for checking I may need to take a deeper look.

**Comment by modmuss50** [comment]
I think I may have an idea of what it is, I will take a look when I get a chance.

**Comment by lilmoefow** [comment]
Alright thanks, I reported it to the tinkers dev as well just to cover all grounds.

**Comment by bonii-xx** [comment]
Considering it's happening in itemstack.toString.. looks like there is an item that's not registered in that Itemstack. Are you oredicting items that are disabled in your configs? ;P

**Comment by modmuss50** [comment]
That could be the case I will look into it

**Comment by lilmoefow** [comment]
I am disabling things in your "ores.hjson" file,  maily the rubber trees.  I want to use your ore gen as base, but not the Rubber trees.  I would prefer to go with IC2's if possible.

**Comment by modmuss50** [comment]
Ok, its a bug with out deps system, StandalonePartCompact should not be false, I will have to add a way to remove that from the config

**Comment by lilmoefow** [comment]
Just tested out the Dev build from your Jenkins that is supposed to fix this, and i am getting this crash

Crashlog:  https://gist.github.com/lilmoefow/bfa49bdd8e0c1345fa8c4bb81c5fb371

FML-client: https://gist.github.com/lilmoefow/238baa43b2f1032943a88afde478f32f

**Comment by modmuss50** [comment]
Oh huh, thats a weird on, I will look into that tomorrow

**Comment by modmuss50** [comment]
Your using the dev version of the mod use universal from the same page

**Comment by lilmoefow** [comment]
I don't know why I missed that.  Alright everything loads up fine now, but now I can not disabled all the extra components added by techreborn any more.  Those config options worked with out Tinkers loaded.  I know you guys want this to be a stand alone mod, but for people who still prefer to use it as an addition to IC2 this just leaves us with several duplicate items.  Is minetweaking things out going to be my only option now?

**Comment by modmuss50** [comment]
I will look into removing the items but stopping it from crashing was the major concern , it may take a bit of work, but it should be possible.

The cables are part of a larger issue that can be seen here: https://github.com/TechReborn/TechReborn/issues/766

**Comment by lilmoefow** [comment]
alright cool.  thanks for the quick responses.
