### ISSUE TITLE
Various missing/duplicate/unusual recipes

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#733]
I'll just list them as you know my main pack details/configurations already:
- bauxite dust unprocessable
- iridium ingot uncraftable
- sodalite dust unprocessable
- manganese dust unprocessable
- 2 output recipes for peridot dust
- magnesium dust unprocessable
- steel plate unobtainable
- electrum plate unobtainable

Also the only way to obtain the plates is by any random combination of IE Metal Press, TCon Smeltery Plate Cast, IE Hammer & TR Compressor(only 4 or so plates can be crafted this way); and it's across all of the plates.

**Comment by varukasalt** [comment]
Data Orb and Data Control Circuit recipes are also missing.

**Comment by the-creamster** [comment]
Here's some more:
- Digital & Quantum Chest(they need the data things)
- Charge Bench missing an "Energy Flow Circuit" in the bottom right of the crafting grid
- Assembling Machine uncraftable
- 10k Coolant Cell uncraftable
- Lithium Cell unobtainable
- Steel Drill uncraftable(shouldn't the Steel Drill be an upgrade step for the diamond drill as it has 2 recipes, 1 including itself)
- Nanosaber uncraftable
- Sodium Persulfate cell missing the second 'filled' cell
- Sulfur cell unobtainable (used in Sodium Sulfide,Sulfuric Acid cell)
- Potassium cell unobtainable
- Wolframium cell unobtainable
- Nitrogen Dioxide cell missing the second 'filled' cell
- Brass Dust/Ingot??
- Silicon Ingot??
- Deisel Cell unobtainable (and anything that uses it)

**Comment by modmuss50** [comment]
Most of them have either been fixed, have no use so need no recipe. So I think im going to close this. If there are still issues when things cannot be crafted feel free to open a new issue.
