### ISSUE TITLE
1.10.2 Energy net issues

### ISSUE THREAD

**Issue by K1ltu** [TechReborn/TechReborn#739]
Techreborn machines explode upon reviving their rated input or less from ic2 sources
I.E. a ic2 mfe feeding a TechReborn mfe causes the Tech reborn mfe to explode

it does not matter if its directly connected or via cables always results in the explosion also tested with compact solars and had the same results 

I also tried ic2 mv to tech reborn hv same results

MC ver 1.10.2
Forge 2053
Tech reborn 1.4.2.50 - latest ver on curse

**Comment by modmuss50** [comment]
it seems ok, please open a new issue if its still in 2.0
