### ISSUE TITLE
problem of compatibility between TechReborn and ImmersiveEngineering Bauxite

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#740]
I link this issue here too since it is relative to the TechReborn Bauxite. The Bauxite of TechReborn can't be melted into Aluminium like the ImmersiveEngineering Bauxite.
https://github.com/BluSunrize/ImmersiveEngineering/issues/1406

**Comment by modmuss50** [comment]
Not going to be fixed, see BluSunrize/ImmersiveEngineering#1406 for the reason.

**Comment by 0Navis0** [comment]
It's not possible to add the possibility to smelt TechReborn Bauxite into Aluminium when ImmersiveEngineering is present ?

**Comment by modmuss50** [comment]
It's two different ores, I am not going to fix it. Use mine tweaker if you must.

**Comment by 0Navis0** [comment]
Hm ok, thanks for your answer. :)
