### ISSUE TITLE
Reinforced Machine Casing is transparent in current release of TR

### ISSUE THREAD

**Issue by utoc** [TechReborn/TechReborn#741]
Seen here: http://i.imgur.com/SyEW0FO.png

The block has a texture as an item in your inventory but when placing it in the world, such as part of the Implosion Compressor Mutliblock, it doesn't render.

Running TechReborn 1.10.2-1.4.2.50 and RebornCore 1.10.2-2.7.0.34-universal with FML 2077

Need any other info?

**Comment by modmuss50** [comment]
I assume all other blocks are working?

**Comment by modmuss50** [comment]
Could you try with this version of reborn core as well? https://minecraft.curseforge.com/projects/reborncore/files/2323518

**Comment by utoc** [comment]
All the "casing" (basic, reinforced, advanced) blocks are invisible.
Machine blocks (compressor, quantum chest) render correctly.
Compressed versiond of items (titanium blocks etc) render correctly.

build 27 - renders
build 31 - renders
build 32 - renders
build 33 - invisible
build 34 - invisible

**Comment by modmuss50** [comment]
Ok, thanks

**Comment by modmuss50** [comment]
Was this with Optifine?

**Comment by utoc** [comment]
No Optifine but I do have BetterFPS.

EDIT: Tested without BetterFPS, issue persists.  Let me know if its cross-mod interaction, I'll track it down.

**Comment by modmuss50** [comment]
Ok, this may fix it: http://modmuss50.me:8080/job/RebornCore/job/RebornCore-1.10.2/

**Comment by utoc** [comment]
Still invisible.  Also, I checked the the log just in case I missed something, found nothing.

https://gist.github.com/utoc/97038b7ea76be75e5bebdccba95be9a6

**Comment by modmuss50** [comment]
Ok, try build 40: http://modmuss50.me:8080/job/RebornCore/job/RebornCore-1.10.2/

**Comment by utoc** [comment]
Success!  All casing blocks are visible.  Thank you very much modmuss :)

**Comment by modmuss50** [comment]
Thanks for your help, I will push this to curse then.
