### ISSUE TITLE
Missing circuitData for multiple recipes

### ISSUE THREAD

**Issue by thejims** [TechReborn/TechReborn#742]
The recipes for quantum chest requires data orbs which have no recipe due to a missing component circuitData .  There is a similar item, circuitStorage that has no other obvious uses.  Is it possible the recipes that require circuitData need to be updated to instead use circuitStorage or a recipe needs to be added for circuitData

**Comment by the-creamster** [comment]
This is already logged here;
https://github.com/TechReborn/TechReborn/issues/733

**Comment by modmuss50** [comment]
Fix in dev
