### ISSUE TITLE
[1.10.2] "Battery" item texture

### ISSUE THREAD

**Issue by xXJamieXx** [TechReborn/TechReborn#743]
In 1.10.2 (mod version 1.4.2.50), the "Battery" item does not have a texture. I haven't seen any other issue with this so I don't know if this is the same for anybody else?

Thanks for the help in advance!

**Comment by modmuss50** [comment]
I will take a look at some point.

**Comment by xXJamieXx** [comment]
Thanks for the very quick reply :)

No problem will be pleased to hear what you find whatever it is :)

**Comment by modmuss50** [comment]
Fixed
