### ISSUE TITLE
oregen json could use some sanity checking

### ISSUE THREAD

**Issue by Saereth** [TechReborn/TechReborn#745]
Latest version of TR and Forge 2088, the json config files for oregen dont seem to have any sanity checking currently,
https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/world/TechRebornWorldGen.java#L227

What this resulted in was an inverted max/min value causing the game/server to crash on load with an index out of bounds error. Obviously a config error on my part but a little foolproofing may be useful in the future.

**Comment by modmuss50** [comment]
Ah yeah, that should be easy to add.

**Comment by modmuss50** [comment]
Ive added a few checks, I could go on for ever adding them.
