### ISSUE TITLE
More machine bugs v2(continuation of original minus the fixed/irrelevant stuff {issue no.713})

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#748]
**Dated 18th August from older issue**
I've recently done some SP semi-survival testing and found that some machine buffers empty faster than they can be refilled with the RF power option enabled and using EnderIO's ender energy conduits(20,480 RF/t per connection) when the conduit line is connected to a multiblock capacitor bank with an input/output of 375kRF/t per multiblock capacitor bank face.

The particular machines are:

industrial grinder
industrial electrolyzer
It's occurring for recipes that have a 30-100 EU/t usage within 3-5 sec and for the above machines with 10k EU internal buffers. Should they be draining that fast??

**Now for the newest things**
Upon updating and launching the pack after a few weeks of not touching it; ive found an interesting one
![2016-09-15_20 56 26](https://cloud.githubusercontent.com/assets/2037833/18605798/bacdceb4-7cdf-11e6-8d21-951429ef99bc.png)
![2016-09-15_20 56 31](https://cloud.githubusercontent.com/assets/2037833/18605799/bf0288b2-7cdf-11e6-9fe7-1bb7e0867ab4.png)

Edit:
As per the 18th August comment its not occurring for those 2 machines but the Industrial Grinder Instead. 1 Bauxite ore drains it's internal buffer down to 4.6k EU/10k EU with the energy not being replineshed by the ender energy conduit connection

**Comment by the-creamster** [comment]
To clarify the invisible mulitblocks got 3 more pics;
![2016-09-17_14 13 58](https://cloud.githubusercontent.com/assets/2037833/18605823/2ada5bd6-7ce1-11e6-8d38-e9570857c515.png)
![2016-09-17_14 13 59](https://cloud.githubusercontent.com/assets/2037833/18605825/2d7721a8-7ce1-11e6-80ea-9b48e5249da1.png)
![2016-09-17_14 14 01](https://cloud.githubusercontent.com/assets/2037833/18605826/2f8901a0-7ce1-11e6-8529-1c2a237d299d.png)

There behaving like the "Unstable ingot block" from Extra Utilities 1(1.7.10) which was purposely designed for X-Ray function.

**Comment by modmuss50** [comment]
Closing this as it contains more than one issue. and I think most of them are fixed.
