### ISSUE TITLE
Can't Automate Empty Cells for Industrial Centrifuge (1.7.10)

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#750]
In the 1.7.10 build, attempting to feed Empty Cells through any side of an Industrial Centrifuge results in them being placed into the center slot (the one normally used for items to be processed) or the battery slot.

This makes it impossible to automate the Industrial Centrifuge, as you need Empty Cells for most of the processing.

**Comment by modmuss50** [comment]
Update to 1.10.2, sorry we dont support 1.7 anymore
