### ISSUE TITLE
Server Crash - Mek windmilll charging a chainsaw.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#754]
https://github.com/aidancbrady/Mekanism/issues/3825

Different api versions or something?

**Comment by modmuss50** [comment]
Fix for now is to disable forge and RF power in the reborn core config, log back in, remove items, and then enable it again.

and dupe of: https://github.com/TechReborn/TechReborn/issues/696

**Comment by ProsperCraft** [comment]
The reborn core config does not have the option to disable forge and RF power that I can find anywhere.
