### ISSUE TITLE
quantum chest does not show total items stored

### ISSUE THREAD

**Issue by LeChuckXIV** [TechReborn/TechReborn#760]
only shows one stack of items as total amount regardless of adding/removing items

also when broken with incorrect tool it destroys all items except 65 which pop out, when collected with wrench, 65 items pop out and it retains remainder inventory, also updates item amount when replaced but does not update afterwards

**Comment by modmuss50** [comment]
yeah, the tank and the chest need the updates from QS

**Comment by Prospector** [comment]
This is fixed in 1.11.2, hopefully we'll get a backport out soon!
