### ISSUE TITLE
ore generation in the end

### ISSUE THREAD

**Issue by LeChuckXIV** [TechReborn/TechReborn#765]
does not have end stone variants: http://prntscr.com/cn7xv3

also places nether variants: http://prntscr.com/cn7y29

edit: not sure if intentional as sodalite has end variant http://prntscr.com/cn7za9

**Comment by 0Navis0** [comment]
Normally if they are activated only Soladite, Sheldonite, Tungsten and Peridot are supposed to generate them in the End, the other ores shouldn't generate them in the End, so yeah it's an issue.

**Comment by modmuss50** [comment]
Fixed
