### ISSUE TITLE
IC2 and TechReborn blocks and items duplicated

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#766]
The IC2 and TechReborn blocks and items are still duplicated.

**Comment by modmuss50** [comment]
Is there an issue with this, as long as its not stopping you from playing with either mod its fine in my eyes.

**Comment by 0Navis0** [comment]
Of course it doesn't prevent to play, but it creates duplication and confusion, and it uses a lot of ids for nothing, and ids aren't unlimited. (that it's the modpack dev who speak :p)
Anyway it's not really a normal behaviour for a mod which is supposed to be an IC2 addon and GregTech resurrection.

**Comment by LeChuckXIV** [comment]
it's not really an addon though when it works completely fine without ic2 installed, it has it's own power system and set of machines, that being said there should be a config option to disable the "duplicate" blocks.

**Comment by 0Navis0** [comment]
It's what I had proposed in first time, an option for disbling the duplicated blocks when IC2 is present. ;)

**Comment by modmuss50** [comment]
Uhhh, this may get fixed at some point, but I think the best way to play is either with TR or with IC2, pick your favorite.
