### ISSUE TITLE
mechanical pipes from mekanism dont connect to thermal generator

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#767]

**Comment by Prospector** [comment]
gonna assume this is probably because we're not using the fluid capability?

**Comment by modmuss50** [comment]
Yeah, Im I think I will pull the changes that me and @gigabit101 have done to QS if he is ok with that.

**Comment by gigabit101** [comment]
go for it I did some more the other day Dsu now supports ItemCapability

**Comment by modmuss50** [comment]
Fixed in next reborn core version
