### ISSUE TITLE
Machines taking more energy than they should?

### ISSUE THREAD

**Issue by wagon153** [TechReborn/TechReborn#769]
Machines appear to be using as much energy as they can draw. A compressor for example drew 400k EU to compress 4 iron ingots. I've also confirmed this to be happening with the extractor as well. 

For reference, the setup is a Thermal Generator going into a LV Transformer, which then outputs to my machines. If there is any other info you would like me to provide, just tell me.

**Comment by cookta2012** [comment]
They are hungry for all the RF, not sure if it is because ic2 is present too.

**Comment by modmuss50** [comment]
This has been fixed in the tile rewrite, once some things have been fixed we should be able to release v2
