### ISSUE TITLE
CropPlugin API

### ISSUE THREAD

**Issue by Speiger** [TechReborn/TechReborn#77]
Crop plugin API is out.
If you want to support the Nei Plugin for IC2 Crops then just install the Helper Class that give DisplayItems (for better Identifying) or Info text for some things that would be maybe good to know^^
https://github.com/TinyModularThings/IC2-Nei-Plugin

**Comment by modmuss50** [comment]
We need to add the crops from the old GT before we can do this.

**Comment by modmuss50** [comment]
Im gonna close this until we add new crops. I have not forgotten.

**Comment by modmuss50** [comment]
@Speiger is there an easy way to see if ic2 classic is installed? I have a check for "IC2" just need an api for classic?

**Comment by Speiger** [comment]
look into my API class: IC2Classic. I have there a function which detect that.
There is also a custom modID inserted if you do just want to use that. Go ahead^^" But i do not know the id out of my head

**Comment by modmuss50** [comment]
Ok great, thanks
