### ISSUE TITLE
TechReborn Version 2

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#770]
This issue is going to be use to track the progress on TR2. TR2 **WILL** be fully compatible with old worlds. If you have any suggestions for changes please comment on this issue.

No more textures need to be done, however there are quite a few broken/missing models.
## Models that need fixing
- [ ] Solar Panel (Missing In-World)
- [ ] Water Mill (Missing In-World; Wrong In-Inventory)
- [ ] Standard Machine Casing
- [ ] Reinforced Machine Casing
- [ ] Advanced Machine Casing
- [ ] Sulfur Fluid
- [ ] Sodium Sulfide Fluid
- [ ] Nitrodiesel Fluid
- [ ] Nitrocarbon Fluid
- [ ] Carbon Fiber Fluid
- [ ] Sulfuric Acid Fluid
- [ ] Diesel Fluid
- [ ] Carbon Fluid
- [ ] Oil Fluid
- [ ] Iridium Reinforced Stone
- [ ] Reinforced Glass
## General Notes

Bugs need to be fixed, but that can be an on going process. I will assign the bugs to the 2.0 milestone.

I would like to get this done as quick as possible, im not going to a date on it though.
- [x] New Logo and curse page.

I have got someone to do a wiki, but they are waiting on this to start.

@gigabit101 if you have any ideas on other stuff that can be done for 2.0 please suggest.

Any help from anyone (even via PR) on fixing the missing textures will be of great help.

**Note** all development on version 2 is currently taking place on the `1.10.2-v2` branch

**Comment by modmuss50** [comment]
@ProfessorProspector and @Yulife I have gone though and found a list of the textures that I could not find, they may well be there under a different name.

**Comment by Yulife** [comment]
Yeah most of these are finished

**Comment by Yulife** [comment]
All textures done! We've got a new logo as well?

**Comment by modmuss50** [comment]
@ProfessorProspector has it, it will be applied in all the places once 2.0 is done. Good work and thank you both.

**Comment by Prospector** [comment]
https://cdn.discordapp.com/attachments/159382191292416000/232007418131906560/unknown.png

**Comment by Yulife** [comment]
## Models that need fixing
- [ ] Solar Panel (Missing In-World)

I can do that
- [ ] Water Mill (Missing In-World; Wrong In-Inventory)
I can do that

- [ ] Standard Machine Casing
- [ ] Reinforced Machine Casing
- [ ] Advanced Machine Casing

These three need CTMH on the SIDES and SCTM on top and bottom. Textures are done.

- [ ] Fusion Coil

This needs to be placeable like a log

- [ ] Iridium Reinforced Stone
- [ ] Iridium Reinforced Tungstensteel
- [ ] Reinforced Glass

These all need normal CTM

**Comment by Yulife** [comment]
## Models that need fixing
- [ ] Solar Panel (Missing In-World)

I can do that
- [ ] Water Mill (Missing In-World; Wrong In-Inventory)
  I can do that
- [ ] Standard Machine Casing
- [ ] Reinforced Machine Casing
- [ ] Advanced Machine Casing

These three need CTMH on the SIDES and SCTM on top and bottom. Textures are done.
- [ ] Fusion Coil

This needs to be placeable like a log
- [ ] Iridium Reinforced Stone
- [ ] Iridium Reinforced Tungstensteel
- [ ] Reinforced Glass

These all need normal CTM

**Comment by Yulife** [comment]
Small things:
- [ ] Fusion coil needs to be rotateable
- [ ] Enchantment sheen on rockcutter gone
- [ ] Durability bars on full and empty energy storing blocks (if too much then 2.1)
- [ ] Cells to material tab
