### ISSUE TITLE
Server Performance issues with Techreborn

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#771]
Warmroast profile--
https://gyazo.com/2353e9852176d2cde4168c964759370c

Server TPS tanked to 7 tps for a long period of time, removal of techreborn machines and cables tps jumped back to 20 tps with 12 players on.

TechReborn-1.10.2-1.4.6.67-universal

Modpack- allthemods 1.32

**Comment by ProsperCraft** [comment]
![2016-10-02_09 10 54](https://cloud.githubusercontent.com/assets/4427684/19021661/f5655380-8883-11e6-9143-19bf9a7bea2d.png)
![2016-10-02_09 09 03](https://cloud.githubusercontent.com/assets/4427684/19021666/fd57ab4c-8883-11e6-820b-96446d46ea1e.png)

**Comment by modmuss50** [comment]
Ok I will take a look, this is strange.

**Comment by ProsperCraft** [comment]
Now with them removed, we are having tps tanking to .2 and this message in console.

olis, prism, com.nguyenquyhy.spongediscord] at CLIENT
[09:17:46] [Netty Epoll Server IO #6/INFO] [journeymap]: CLIENT
[09:18:14] [HikariPool-2 housekeeper/WARN] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=52s276ms853µs719ns).

> [09:18:14] [HikariPool-1 housekeeper/WARN] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=52s276ms854µs949ns).
> forge tps
> 
> [09:18:14] [Netty Epoll Server IO #4/WARN] [io.netty.channel.DefaultChannelPipeline]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
> io.netty.handler.timeout.ReadTimeoutException
> forge tps
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.generator.TileGenerator@774f5cf8 at dim 0: -2121/60/-2813.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.generator.TileWaterMill@7076627c at dim 0: -2120/58/-2808.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.generator.TileWaterMill@4a015bf5 at dim 0: -2119/58/-2808.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.generator.TileWaterMill@35b9c4cf at dim 0: -2119/58/-2810.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.generator.TileWaterMill@7527ef7e at dim 0: -2121/58/-2808.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.teir1.TileElectricFurnace@30aa68e6 at dim 0: -2117/60/-2813.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.generator.TileWaterMill@5f6577af at dim 0: -2121/58/-2810.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.storage.TileBatBox@3f8b8547 at dim 0: -2120/60/-2812.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.teir1.TileExtractor@4ba74516 at dim 0: -2119/60/-2813.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.teir1.TileElectricFurnace@3e94149b at dim 0: -2118/60/-2813.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.teir1.TileCompressor@4f6a79aa at dim 0: -2117/61/-2813.
> [09:18:14] [Server thread/INFO] [IC2.EnergyNet]: No tile found for techreborn.tiles.teir1.TileGrinder@5c99256a at dim 0: -2118/61/-2813.
> [09:18:14] [Server thread/INFO]: Rbandboy lost connection: Disconnected
> [09:18:14] [Server thread/INFO] [com.nguyenquyhy.spongediscord]: Rbandboy has disconnected!
> [09:18:14] [Server thread/INFO]: Rbandboy left the game
> [09:18:14] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
> [09:18:14] [Server thread/INFO] [mcjty.lib.varia.Logging]: SMP: Sync dimensions to client
> [09:18:14] [Server thread/INFO]: joshmilke[/127.0.0.1:60194] logged in with entity id 133113 in world-allthemods(0) at (-1258.9833033695907, 65.0, -206.16745961524495)

**Comment by modmuss50** [comment]
Hum, looks like the ic2 enet is messing with ours in some way. I will see what I can do.

Thanks for reporting this.

**Comment by ProsperCraft** [comment]
its in some kind of loop 

http://pastebin.com/w8VBt4hV

**Comment by ProsperCraft** [comment]
http://pastebin.com/i8QpiXGu

**Comment by modmuss50** [comment]
Reboot the server after you have broken our blocks and it should return to normal, I will look into asap.

**Comment by modmuss50** [comment]
Ive made some improvements: https://modmuss50.me/shots/idea_2016-10-03_20-41-20.png You can see the time it took to tick the power net.

**Comment by modmuss50** [comment]
The ic2 issue is a separate one that I will also look into
