### ISSUE TITLE
Spam in the FML log about missing recipes and models

### ISSUE THREAD

**Issue by DatrixTHLK** [TechReborn/TechReborn#774]
All I'm going to say is that I keep getting FML Spam about missing textures and missing recipies from your mod. 

https://gist.github.com/DatrixTHLK/eaf375de01acdb2bf3b367aad9c3628e

1.10.2
Forge: 2095
Reborncore: 2.7.3.46
TechReborn: 1.4.6.67

**Comment by modmuss50** [comment]
This wont get down to 0, but it should be improved some in 2.0

**Comment by DatrixTHLK** [comment]
Thanks for the update and fix.
