### ISSUE TITLE
TR's MFE + MFSU eu storage values currently match IC2exp Values not original values

### ISSUE THREAD

**Issue by LuigiHutch** [TechReborn/TechReborn#777]
Forge 12.18.2.2098
RebornCore-1.10.2-2.7.3.46
TechReborn-1.10.2-1.4.7.70

Currently the MFE and MFSU EU storage values currently match IC2exp values (unlike the rest of the mod) of 4M EU and 40M EU respectively which means that their crafting recipies do not allign properly Eu storage wise

The values should be: MFE = 600,000EU and MFSU = 1,000,000EU 

Thanks,
- LuigiHutch

**Comment by modmuss50** [comment]
I will go though and check all machine power values after the tile rewrite has been merged.
