### ISSUE TITLE
Wrench and generator

### ISSUE THREAD

**Issue by Theedoctor10** [TechReborn/TechReborn#779]
The Tech Reborn generator can not be picked up with the wrench or electric wrench in the new Hermitpack mod pack.

**Comment by modmuss50** [comment]
Humm, ok I will take a look

**Comment by Prospector** [comment]
Is this with the IC2 wrenches?

**Comment by Theedoctor10** [comment]
I tried both the IC2 and Tech reborn wrench

**Comment by RheyvenFox** [comment]
When you attempt to use the wrench it just makes the wrench noise but nothing happens. This is the same with machines as well. Verified both IC2 and TR wrench on the machines and generators.

**Comment by DnTheMn** [comment]
can confirm this to be the case https://github.com/whatthedrunk/allthemods/issues/239

**Comment by DnTheMn** [comment]
ok so after further testing the techreborn wrench will work on ic2 machines but not techreborn it will make the sound but nothing else could it be that both wrenches have the same recipy and the ic2 one is overwriting it?

**Comment by kaosjr** [comment]
Can also confirm this is happening in version 1.4.6.67 while playing with both TechReborn and IC2Experimental.

**Comment by modmuss50** [comment]
Our wrench is working fine on our machines in my dev env: https://modmuss50.me/shots/2016-11-05_10-44-28.mp4

**Comment by modmuss50** [comment]
Works fine again for me.
