### ISSUE TITLE
Iron into Iridium plate recipe

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#78]
Not sure if this exists for debug purposes or something

![2015-07-11_03 51 38](https://cloud.githubusercontent.com/assets/7843312/8625155/3f754036-2780-11e5-95ed-bf1feba47b9b.png)
![2015-07-11_03 51 40](https://cloud.githubusercontent.com/assets/7843312/8625156/3fa0e2ae-2780-11e5-81bf-017a8909ba1b.png)

**Comment by Carbon-Ghost** [comment]
Unrelated but there is a lot of stuff that recipes is wrong, like the coolant cells, gonna open a new issue for that ..

**Comment by gigabit101** [comment]
this was just a test and the hammer is not craft able not a bug
