### ISSUE TITLE
Industrial Blast Furnace is not craftable

### ISSUE THREAD

**Issue by DreiPixel** [TechReborn/TechReborn#780]
the industrial Blast furnace is not craftable since it requires superconductors and those require tungsten that hast to be made with a indutrial blast furnace :V

we are using: 
MC 1.10.2 
Techreborn-1.10.2-1.4.7.70
RebornCore-1.10.2-2.7.3.46-universal.

**Comment by 3Pixel** [comment]
ok srsly? how did you guys missed this? its fixed in 1.9.4 branch but not on the 1.10.2 branch.

**Comment by DreiPixel** [comment]
https://github.com/TechReborn/TechReborn/pull/781 do that one.

**Comment by DreiPixel** [comment]
fixed with pull request.
https://github.com/TechReborn/TechReborn/pull/781
