### ISSUE TITLE
Unify ids

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#784]
Currently there's some that are `techreborn:techreborn.block` and some that are `techreborn:block`

Will be fixed in 1.11.

**Comment by modmuss50** [comment]
Might be fixed in 1.11 depending if people plan to update worlds

**Comment by gigabit101** [comment]
We could just use the remap event to fix this when ever

**Comment by Prospector** [comment]
We could, but we also want to fix a load of metadata things as well.

**Comment by Leftorius** [comment]
I would like to upgrade my world but hope v1 to v2 does that smoothly as well :D

**Comment by gigabit101** [comment]
Worst case scenario you may need to replace some of the machines and even
that seems a very unlikely

**Comment by Leftorius** [comment]
tried a jenkins build to test v2 a little but can't start it at the moment, I think I have to wait a little longer :) I build an Serverpack around TechReborn and other nice mods and yeah it's far from done (I use MT a lot for it :D) so I'm really excited to play more with it :D

**Comment by modmuss50** [comment]
v2 will NOT break worlds, I dont see a NEED for this change and it will only happen if 1.11 is enough to break other mods that worlds will not be updating anyway.

v2 is not ready yet, I cannot even place any of the blocks in dev without crashing, soon though.

**Comment by utoc** [comment]
I wanted to chime in with a handful of things we noticed when we tried to throw build 80 (2.0) into an existing world.  I realize this is still a work in progress and these things may already be known:

All plates from plate:11 or so increased by 1 to make room for a new plate
ingot:20 (used to be advanced alloy ingot) is now a placeholder.
TR machines don't seem to be RF capable anymore.

**Comment by modmuss50** [comment]
Yeah don't use 2.0 just yet
