### ISSUE TITLE
[Suggestion] Treetap should consider IC2 rubber spots valid

### ISSUE THREAD

**Issue by hron84** [TechReborn/TechReborn#786]
I thought rubber is rubber whatever we call it but it seems like not. I love your treetap texture (it's just more fancier than the really old and rusty IC2 one) and I really hoped I could use it on my IC2 rubber trees but it does not work. Could you please make it work against IC2 trees? I really don't care what it produces (either IC2 resin or TR counterpart), but please, please make it work on IC2 rubber spots. Because your treetap is just better.

Modpack: FTB Presents Hermitcraft 1.0.1
Mods: IC2 2.6.69-ext110 & TechReborn 1.10.2-1.4.6.67

**Comment by Prospector** [comment]
Yeah, we'll look into it. Thanks!

**Comment by modmuss50** [comment]
I need to figure out getting ic2 running in my dev env to test this.

**Comment by ChubbyTurtle101** [comment]
Also seems like you need an IC2 Extractor to extract IC2 Sticky Resin and you need a Techreborn Extractor for its version.  It would be nice to only use one extractor and not have to make two.

**Comment by marysaka** [comment]
@modmuss50 I recommend you to switch to the 129 build and don't use the 'dev' version

**Comment by modmuss50** [comment]
yeah, the dev version is on different mappings.

**Comment by hron84** [comment]
Thanks :-)
