### ISSUE TITLE
possible problem?

### ISSUE THREAD

**Issue by Alienfreak10** [TechReborn/TechReborn#788]
so im playing hermitcraft 1.10 mc
and my problem is to make the industrial blast furnace u need tungsten ingots which u get from smelting tungsten in a industrial blast furnace, and thats the only way JEI is telling me. Im ASSUMING im either blind or JEI is missing a recipe.
thanks in advance x.x
trying to play with this mod is a pain :P when u havent touched ic2 in forever + no guide out yet lol

**Comment by utoc** [comment]
What version are you running?  This was addressed in https://github.com/TechReborn/TechReborn/issues/780

**Comment by modmuss50** [comment]
I think I should push a 1.x build at some point with some small fixes, I may have not made it to curse.

**Comment by utoc** [comment]
@modmuss50 I would appreciate if you could submit a build with all the 1.0 changes as a final release while you're still working on 2.0

**Comment by modmuss50** [comment]
I plan to soon ish

**Comment by modmuss50** [comment]
Fix in a new version
