### ISSUE TITLE
Incorrect Blast furnace recipe / Galena cooking into Iron

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#79]
Galena ore making Iron in the blast furnace, instead of the correct silver/lead
Dust works fine, ore broken

![2015-07-11_15 45 57](https://cloud.githubusercontent.com/assets/7843312/8632574/97c842d8-27e4-11e5-9926-6f4d9d4105a8.png)

**Comment by modmuss50** [comment]
The code also look fine for this:

RecipeHandler.addRecipe(new BlastFurnaceRecipe(ItemDusts.getDustByName("galena", 2), null, ItemIngots.getIngotByName("silver"), ItemIngots.getIngotByName("lead"), 80, 120, 1500));

**Comment by TheQuantumGeneral** [comment]
This is the problem recipe I believe, only Iron and Pyrite ask for calcite to process, yet there is no in game blast furnace recipe for Pyrite. Somehow Pyrite and Galena are being mixed up. 

RecipeHandler.addRecipe(new BlastFurnaceRecipe(BlockOre.getOreByName("pyrite"), ItemDusts.getDustByName("calcite"), new ItemStack(Items.iron_ingot, 2), ItemDusts.getDustByName("darkAshes"), 140, 120, 15000));

**Comment by gigabit101** [comment]
this is a issue with https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/blocks/BlockOre.java#L42 we use itemBlocks for the ores so this wont work

**Comment by gigabit101** [comment]
@modmuss50 sorry but I dont have any free time atm so I cant work on this atm
