### ISSUE TITLE
Bug [1.10.2]: ores being added to ores.hjson

### ISSUE THREAD

**Issue by darklordwonton** [TechReborn/TechReborn#790]
Whenever the game loads techreborn adds all of its ores to the ores.hjson file (after a few loads it becomes incredibly large). Since it puts them at the end this also has the effect of making ores spawn in the end that shouldn't spawn there.

I am running RebornCore-1.10.2-2.7.3.46-universal and TechReborn-1.10.2-1.4.7.70-universal and have disabled every overworld ore using the ores.hjson file but no other ores.

**Comment by modmuss50** [comment]
I have fixed this in 2.0, but that is taking longer than I had hoped. So I think I'm gonna do one last 1.x update with a few fixes like this one in.
