### ISSUE TITLE
TechReborn 1.10.2 latest version (iridium and industrial blast furnace)

### ISSUE THREAD

**Issue by g3niusss** [TechReborn/TechReborn#792]
Iridium ore is unusable and iridium ingots are uncraftable
Industrial blast furnace require tungsten ingots to craft and its the only way to craft tungsten ingots
![2016-11-02_12 44 04](https://cloud.githubusercontent.com/assets/23213088/19927483/161a9c14-a0fa-11e6-8cd7-92498edbbbf2.png)
![2016-11-02_12 44 07](https://cloud.githubusercontent.com/assets/23213088/19927484/162059e2-a0fa-11e6-8ff3-380ce81f1b86.png)
![2016-11-02_12 44 15](https://cloud.githubusercontent.com/assets/23213088/19927485/16209d6c-a0fa-11e6-94e9-c152061a4d70.png)

**Comment by modmuss50** [comment]
Looks fine in dev, so I assume the next version will fix it:
https://modmuss50.me/shots/java_2016-11-04_20-16-39.png

**Comment by g3niusss** [comment]
iridium still has no recipe and iridium ore has no usage

**Comment by modmuss50** [comment]
Humm, I will reopen this and fix that.

**Comment by Hakameda** [comment]
Any luck on this ? Makes a ton of the mod unusable
