### ISSUE TITLE
liquid ruby, sapphire and peridot for Tinker's Construct

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#795]
Since liquid emeral exists, why not liquid ruby, sapphire and peridot. ;)

**Comment by Prospector** [comment]
What would the purpose be?

**Comment by 0Navis0** [comment]
Already for more compatibility between mods, and maybe a way to double the gems by smelting and casting it.

**Comment by Prospector** [comment]
I don't think this really makes sense. The only reason liquid emeralds exist is because of villagers.
