### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Y0ungSandwich** [TechReborn/TechReborn#797]
Pack crashes with this error using the latest release versions of all required mods:

http://pastebin.com/kVVUEyFG

**Comment by modmuss50** [comment]
Update reborn core

**Comment by Y0ungSandwich** [comment]
http://pastebin.com/reVHHVxU

Just another crash. Different, but another.

**Comment by modmuss50** [comment]
Update jei, if it still doesn't work then you have an issue

**Comment by Y0ungSandwich** [comment]
Updated to the latest version already. Guess Ill try over with JEI. Thanks.
