### ISSUE TITLE
Bauxite ore incompatible with other mods

### ISSUE THREAD

**Issue by GeorgeDeac** [TechReborn/TechReborn#798]
Bauxite ore from other mods can't be used in the industrial grinder and vice versa, bauxite from TechReborn isn't recognized by others. Maybe this is caused by different "Aluminium" spellings in the oredict?

**Comment by modmuss50** [comment]
yeah, that might be why

**Comment by GeorgeDeac** [comment]
I think the most common spelling is Aluminium, based on what i saw at other mods

**Comment by 0Navis0** [comment]
It's surely due to the fact that Bauxite is Aluminium for other mods while it's Titanium in TechReborn.

**Comment by ChubbyTurtle101** [comment]
Suggestion is to finish the recipe to either use the centrifuge or electrolyzer.  Aluminium (Al)[http://www.chemicalelements.com/elements/al.html] is not an easy thing to get and it should take several machines to get it.

**Comment by GeorgeDeac** [comment]
Yep, something like this: https://en.wikipedia.org/wiki/Bayer_process
At least the crystallization part.

**Comment by Staegrin** [comment]
Like venturaguy101 said there needs to be a use for bauxite dust. Especially because you can process the ore in machines from other mods but that leaves you with dust that has no use and no small piles of titanium.

**Comment by modmuss50** [comment]
im thinking something to create aluminum is going to be the best plan.

**Comment by Prospector** [comment]
Yeah I am slowly going through all the recipes to make sure they're all right. Going to be doing centrifuge/electrolyzer ones next which should fix this

**Comment by Prospector** [comment]
Bauxite dust will no longer be useless in the next release. not sure when that'll be though. I don't know about compat though.

**Comment by modmuss50** [comment]
Closing this as I dont feel like there is a solid solution to this. I have spoken to devs of other mods with Bauxite and we didnt come to a solution.
