### ISSUE TITLE
Nuclear reactor?

### ISSUE THREAD

**Issue by Ananka59** [TechReborn/TechReborn#800]
Hey!

Just a question, did you add nuclear reactor soon?
Coz i like nuclear power, but didnt find any mod who
generate energy with nuclear, just IC2 but i dont think that
install techreborn AND IC2 is really good...

Thanks !

**Comment by modmuss50** [comment]
We have been planning on adding one for ages.

**Comment by modmuss50** [comment]
Closing this as its an addition, it will happen when its done.
