### ISSUE TITLE
[1.10.2] Crash with Industrial Centrifuge

### ISSUE THREAD

**Issue by FnordMan** [TechReborn/TechReborn#801]
Was centrifuging some glowstone, got this when it completed. 

Complete setup was a vanilla hopper on top and an Ender IO item conduit on the side to extract stuff. 
It worked fine in the previous version, now it's utterly broken. 

Crash log: 
[crash-2016-11-13_11.45.35-server.txt](https://github.com/TechReborn/TechReborn/files/587932/crash-2016-11-13_11.45.35-server.txt)

**Comment by modmuss50** [comment]
This should have been fixed in yesterdays version, I will test now
