### ISSUE TITLE
Industrial Grinder doesnt need the standard and reinforced blocks anymore?

### ISSUE THREAD

**Issue by jadeonking** [TechReborn/TechReborn#802]
![?](http://i.imgur.com/EzjGJ5m.png) as you can see the industrial grinder for whatever reason still says missing multiblock but is still functional is this intentional?

**Comment by modmuss50** [comment]
No is not

**Comment by jadeonking** [comment]
weird I actually set the blocks up before i took the screenshot and was still getting the error then i placed water inside the machine and it just started working then i removed the multiblocks and it still functioned

**Comment by modmuss50** [comment]
Humm ok, that's weird

**Comment by jadeonking** [comment]
http://pastebin.com/x1S7ZVN8 just crashed when I right clicked the industrial grinder

**Comment by jadeonking** [comment]
not really related to the grinder but it appears the implosion compressor doesnt work either ![Implosion](http://i.imgur.com/2dmXk1g.png) Middle is hollow ![multiblocks](http://i.imgur.com/hocvZd8.png)
