### ISSUE TITLE
Generating Ores in other dimensions

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#803]
I couldn't find a config option to generate overworld ores in other dimensions. This is relevant for the Aroma Mining World (Dim 6) and the ExtraUtils2 Quantum Quarry which mines Dim -9999. Ores don't generate there. Please make it either the default generating ores in other overworld dimensions like other mods do it or add a config option for a dimension white list. I would appreciate it.

Minecraft 1.10.2, TechReborn 1.4.11.96

**Comment by modmuss50** [comment]
I should be able to fix this for any world that says it's the overworld, failing that I will add a config

**Comment by davqvist** [comment]
Awesome thanks.
