### ISSUE TITLE
bad registered ruby, sapphire and peridot block

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#805]
It's impossible to switch between BOP and TechReborn gem block for the recipes. It's not possible to switch between them in the ore dictionnary converter too. I suppose they are bad registered in ore dictionnary.

**Comment by modmuss50** [comment]
I dont think they are registering the blocks, we are doing it just fine:

https://modmuss50.me/shots/idea_2016-11-26_19-08-00.png
