### ISSUE TITLE
a few issues with 1.10 latest version techreborn you asked me to put up here

### ISSUE THREAD

**Issue by knubbis93** [TechReborn/TechReborn#806]
TechReborn-1.10.2-1.4.11.96-universal

Battery 10k is missing textures
bunch of random liquids cells missing textures?
also the ruby plates and others are missing texture
the upgrades such as overclockers and such is not functioning?
some machines like recycler has no progress bar?
the end is generating overworld ores for some reason?

would be really happy if you could fix whats fixable from these issues im liking your mod very much and im still in 1.10 but i understand if you dont want to fix the issues and go to 1.11 thank you in advance
best regards knubbis93

**Comment by modmuss50** [comment]
I think im going to keep doing 1.10 bug fixes along side 1.11, when I get a chance I will take a look at some of the issues.

**Comment by knubbis93** [comment]
thank you very much @modmuss50 great mod 👍

**Comment by modmuss50** [comment]
All but the missing textures are fixed, that issue can be tracked here; https://github.com/TechReborn/TechReborn/issues/817
