### ISSUE TITLE
Alot of recipes are broken 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#81]

**Comment by modmuss50** [comment]
I have plans...

**Comment by TheQuantumGeneral** [comment]
Sapphire to Chrome ![2015-07-22_19 31 27](https://cloud.githubusercontent.com/assets/7843312/8822371/5b91a986-30a8-11e5-96bc-56f0974cc32b.png)

**Comment by modmuss50** [comment]
What version are you using?

**Comment by TheQuantumGeneral** [comment]
TechReborn-universal-0.1.698-universal, downloaded it yesterday.

**Comment by modmuss50** [comment]
Ok thanks, looks like I didn't fix it.

**Comment by modmuss50** [comment]
Do we know of any missing/broken recipes?

**Comment by TheQuantumGeneral** [comment]
All of the coolant cells are using placeholder recipes

**Comment by TheQuantumGeneral** [comment]
Right issue?

**Comment by modmuss50** [comment]
Wrong issue closed by commit, opps

**Comment by bear989** [comment]
galena ore in blast furnace shows iron as output

**Comment by TheQuantumGeneral** [comment]
Was a known issue, closed for some reason - https://github.com/TechReborn/TechReborn/issues/79

**Comment by gigabit101** [comment]
yup it not a recipe issue its the nei handler

**Comment by modmuss50** [comment]
same issue as https://github.com/TechReborn/TechReborn/issues/83

**Comment by TheQuantumGeneral** [comment]
Not quite broken, but there are a lot of recipes that should be shapeless, but are shaped. For example Aluminium block to Aluminium Ingots is shaped, yet a lot of the other metal blocks are shapeless.

**Comment by modmuss50** [comment]
I cant find where that recipe is getting registered :(

**Comment by TheQuantumGeneral** [comment]
Sorry, was titanium not aluminium. 

Also some are getting double uncrafting recipes, for example silver can be both shapeless or shaped in uncrafting. 

Silver shaped and shapeless
![2015-08-06_00 23 01](https://cloud.githubusercontent.com/assets/7843312/9088052/77c44a12-3bd1-11e5-9b36-2420575948e3.png)
![2015-08-06_00 22 59](https://cloud.githubusercontent.com/assets/7843312/9088054/77c64ed4-3bd1-11e5-937c-7875de19fe08.png)

Titanium only shaped

![2015-08-06_00 23 09](https://cloud.githubusercontent.com/assets/7843312/9088053/77c54ea8-3bd1-11e5-9d68-de44fbf22a75.png)

**Comment by TheQuantumGeneral** [comment]
Here's a list, tested all the metal blocks. 

-Can be uncrafted shapeless
Sapphire
Ruby

-Can be uncrafted shaped
Zinc
Tungsten
Brass
Chrome
Titanium
Lodestone
Iridium
Telurium
Tungstensteel
Osmium

-Can be uncrafted both
Silver
Platinum
Electrum
Lead (has two shapeless uncrafting recipes registered)
Invar
Nickel

-Can't be uncrafted
Yellow garnet
Red garnet
peridot
Aluminum
Steel

**Comment by modmuss50** [comment]
This should help a bit, https://github.com/TechReborn/TechReborn/commit/56c747bb93fd8ff52f4873da66fa86c3bf802ba0

Tell me whats still broken

**Comment by TheQuantumGeneral** [comment]
Perfect, all the metal blocks work 100% 

Ruby, Sapphire, Peridot, Red and Yellow Garnet blocks can't be uncrafted at all, but that may be intentional?

**Comment by Carbon-Ghost** [comment]
It shouldn't, other mods adds recipes so why not us ?

**Comment by modmuss50** [comment]
ok I will find out why thats not working, it was not intended to be that way

**Comment by bear989** [comment]
cupronickel heating coil takes a 360k helium coolent cell and steel?
![2015-08-08_10 19 53](https://cloud.githubusercontent.com/assets/8433695/9150771/7ebe680a-3db8-11e5-8f94-a8ecf06ec9f6.png)

**Comment by TheQuantumGeneral** [comment]
Should be a rolling machine recipe with copper and nickel/ferrous ingots 
![capture](https://cloud.githubusercontent.com/assets/7843312/9150879/669c9a5c-3e31-11e5-9d4a-2af7206f99ee.PNG)

**Comment by TheQuantumGeneral** [comment]
I put 4 Nickel and 4 Copper in the Alloy furnace in build 755 and got 16 bronze with 4 nickel left over. NEI says bronze requires tin not nickel, I should have gotten Cupronickel.

**Comment by gigabit101** [comment]
Grr I should fix these at some point

**Comment by TheQuantumGeneral** [comment]
Still all related to NEI handlers being funky?

**Comment by gigabit101** [comment]
Partly also if u update to the latest u can look at the pda ingame wiki not
finished but looks cool

**Comment by TheQuantumGeneral** [comment]
Yeah I saw the commits and checked it out before, I like it a lot.

**Comment by gigabit101** [comment]
I cleaned it up abit last night but still more todo

**Comment by Carbon-Ghost** [comment]
use old textures ffs xD It looks better :P

**Comment by modmuss50** [comment]
Ive fixed the cupronickel heating coil

**Comment by bear989** [comment]
thanks for fixing the cupronickel heating coils, and I agree with the texture change. the old textures where better.

**Comment by TheQuantumGeneral** [comment]
Im posting any further problems as seperate issues now if you guys want to close this issue, 

ps i also agree on the old texture looking nicer.
