### ISSUE TITLE
OOR Exception on trying to open Recipes from a TechReborn Block

### ISSUE THREAD

**Issue by sayore** [TechReborn/TechReborn#810]
I'm trying to use a Block from TechReborn and wanted to fetch the Recipes(per the GUI in the Block) but i get an OOR Exception as soon as i try to open it in JEI.

Using Latest Releases for 1.10
http://pastebin.com/rQpnxbSP
Screenshot:
![screenshot_27](https://cloud.githubusercontent.com/assets/6115966/20644597/81bde504-b43a-11e6-85b7-c18fd39492b8.png)

I dont know on which side the error occurs so i posted it in both of the GitHubs
Crosslink: https://github.com/mezz/JustEnoughItems/issues/638

**Comment by modmuss50** [comment]
Its an issue With TechReborn, I will be able to fix it another day.

**Comment by Prospector** [comment]
~~I could try to do it, I plan on redoing all the GUIs anyway~~

EDIT: oh um.. I was gonna do that for 1.11, not 1.10. I'll let modmuss fix it for 1.10.

**Comment by modmuss50** [comment]
yeah, this is just a crash error
