### ISSUE TITLE
[1.10.2] Possible Incompatibility with Pipes (EnderIO/Mekanism)

### ISSUE THREAD

**Issue by sayore** [TechReborn/TechReborn#811]
It seems like EnderIO Pipes can occasionally cause an Thread unsafe action resulting in a freeze of the game after a while. (Ender IO Pipes in this setup: EnderIO Pipe piping into Furnaces with a Filter Module on the _back_ and out from the _top_ the items are mainly Dusts produced in SAW Machines from Ender IO)

Version: 1.10.2 newest Release of TechReborn
Screenshot: Not Available

Log:
http://pastebin.com/hN5rq1FK

**Comment by sayore** [comment]
I'm having the same exact error with Mekanism Item Pipes Latest Releases from both again.
At least this time i could see the error more directly happening.

I put a Pipe above an electric furnace, i changed one of the Pipes sides to NONE so it doesnt interact with a chest next to it and instead only sends item in the top of the furnace. After that => Game freezes

Logs:
http://pastebin.com/0v37jny8

Please fix this as a hot fix its really game breaking in my opinion.

**Comment by modmuss50** [comment]
It seems to be an issue with our multipart api, so you have any power cables from TechReborn or FluxedRedstone in you world? 

The log also mentions `CCExtendedBlockRendererDispatcher` so im also going to ping @covers1624 to check its not his core mod wizardry breaking this.

**Comment by covers1624** [comment]
Nope, if it only sniffs the model being rendered and then handles it internally, if it falls back to the Vanilla renderer in the stack then nothing of mine is executing.

**Comment by covers1624** [comment]
And, its not even done with a coremod, just a parent overriden BlockRenderDispatcher with reflection to replace the instance.

**Comment by modmuss50** [comment]
Ok, great, just wanted to check it wasnt you before I start poking around trying to fix this.

**Comment by sayore** [comment]
I sure do have power cables from TechReborn in my World but the error only happens if i try to use Item Pipes from other mods with TR Machines. The game is stable as long as i dont have these around TR Machines.

**Comment by modmuss50** [comment]
Do you have optifine?

**Comment by modmuss50** [comment]
Yeah, you do, remove that.

**Comment by sayore** [comment]
To test it out or is this a general incompatibility?
Cus i need ma optifine yo. [< not an attack just a joke yo]

Will test it even so.

**Comment by sayore** [comment]
seems like it works fine at the moment, i also saw that i used that i am using an outdated optifine version (1 behind which came out a week ago) i just don't know if it fixes this specific issue.

**Comment by modmuss50** [comment]
I think its been fixed in the master mcmp, I will need to update that and that should fix it.

**Comment by modmuss50** [comment]
Let me know if this is an issue without optifine and I will reopen it.
