### ISSUE TITLE
Rolling Machine not receiving power.

### ISSUE THREAD

**Issue by ousmeister** [TechReborn/TechReborn#814]
The rolling machine does not seem to receive power, while all other machines from the mod pack do. Playing Hermitcraft 1.4.0 on a multiplayer server, and cannot find anyone with a similar issue.
![2016-11-28_02 15 41](https://cloud.githubusercontent.com/assets/24219465/20659351/0e9880f2-b511-11e6-8562-9528d80bf946.png)
![2016-11-28_02 16 22](https://cloud.githubusercontent.com/assets/24219465/20659356/13647bea-b511-11e6-8bab-1752b7844a0e.png)

Also RFTools Network monitor claims it has power.
![2016-11-28_02 24 49](https://cloud.githubusercontent.com/assets/24219465/20659512/07299260-b512-11e6-8c81-5752fc8e337d.png)
![2016-11-28_02 24 57](https://cloud.githubusercontent.com/assets/24219465/20659515/0845f92c-b512-11e6-8927-865f86edca35.png)

And one final thing, on connection to a server, it briefly displays it has power accurately in the GUI, but does not start crafting.
![2016-11-28_02 25 51](https://cloud.githubusercontent.com/assets/24219465/20659535/20c96fb0-b512-11e6-996f-faef3b53830e.png)

**Comment by brad18** [comment]
Didn't I fix this in #787 ?

**Comment by modmuss50** [comment]
Humm, you may have done. What version are you using?

**Comment by brad18** [comment]
HermitPack 1.4.0 is using build 1.4.9.84 whereas the fix wasn't applied until build 1.4.9.94

**Comment by modmuss50** [comment]
this can be closed then.
