### ISSUE TITLE
[1.10.2] Missing textures

### ISSUE THREAD

**Issue by SimonMeskens** [TechReborn/TechReborn#817]
This happens when loading just TR + JEI, I assume this happens because they reference textures from other mods that I don't have. Broken textures:

* Battery

Fluids in Cells (Cell texture works fine, fluid inside renders broken):
* sulfuric acid
* sulfur
* sodium sulfide
* diesel, carbon, oil
* nitrodiesel
* nitrocarbon
* carbon fiber

**Comment by 0Navis0** [comment]
I update this issue for 2.0 version, there are still some broken textures. I don't know if it's the case for 1.11.2, I didn't try it, but it's for 1.10.2.
- heat generator
- yellow garnet block
- red garnet block
- refined iron block

**Comment by modmuss50** [comment]
Fixed in v2
