### ISSUE TITLE
[1.10.2] Missing recipes

### ISSUE THREAD

**Issue by SimonMeskens** [TechReborn/TechReborn#818]
This happens when loading just TR + JEI. 

Missing recipes:
* Nanosaber
* All fuel rods (Thorium and Plutonium)
* Diamond Grinding Head
* 10k Coolant Cell
* Electric Tree Tap
* Nuke

**Comment by SimonMeskens** [comment]
Added Nuke (not sure if this has a recipe yet)

**Comment by modmuss50** [comment]
I dont think im gonna add a recipe for the nuke, as I feel like it could be abused especially on servers.

**Comment by SimonMeskens** [comment]
That's fine, just wanted to report all items lacking recipes :)
