### ISSUE TITLE
weird crashes when placing or interacting with certain blocks

### ISSUE THREAD

**Issue by Sailren** [TechReborn/TechReborn#82]
well, fastcraft is installed

internal server crash: http://paste.ubuntu.com/11883415/

client crash: http://paste.ubuntu.com/11883419/

used version is TechReborn-0.2.693-univseral.jar from jenkins

ic2: industrialcraft-2-2.2.748-experimental.jar

this also happens with the industrial blast furni

**Comment by modmuss50** [comment]
It could be an issue with my custom build tool

**Comment by modmuss50** [comment]
It was, the newest build on the jenkins has fixed it.
