### ISSUE TITLE
[1.10.2] Cells are loaded for non-existant materials

### ISSUE THREAD

**Issue by SimonMeskens** [TechReborn/TechReborn#820]
Happens with just TR + JEI loaded. I don't quite know how to label this one or if it's a bug or intended.

Example case:

Sulfur Cell doesn't have a recipe
Sulfuric Acid Cell has a recipe relying on Sulfur

This makes JEI very confusing to use for cells. 

For example, clicking through all the recipes, I don't think there's a way to get Nitrogen Cells, but it's very confusing since all of the recipes that convert higher materials back into Nitrogen (like Nitrocarbon) are there.

This is less confusing for, say, a Diesel Cell, since I assume that just means I could make Diesel Cells if I had a mod that has Diesel, but I don't. No other recipes rely on Diesel or convert back into Diesel, so this is clearer.

I assume the best way to fix would be to only load cells relying on materials that are available through ore-dict (so I could add recipes to get these if I want: for example nitrogen from some other mod's fertilizer).

**Comment by modmuss50** [comment]
The cells are loaded for all fluids in the game, some fluids may not have a use.
