### ISSUE TITLE
Matter Fabricator non-functional

### ISSUE THREAD

**Issue by brad18** [TechReborn/TechReborn#822]
Using the latest TechReborn 1.10.2 v1 and RebornCore and the matter fab does not work properly. It has no insert/extract support (it's commented out) and I think the rate at which it consumes energy and uses scrap is incorrect. I'm not sure how accurate this page is (http://feed-the-beast.wikia.com/wiki/Matter_Fabricator) but it claims it takes 34 scrap and ~ 17 mil EU to make UU matter. In my testing, it took hundreds of scrap and only used about 2 million RF.

**Comment by Prospector** [comment]
Was this intentionally closed?

**Comment by brad18** [comment]
Yes, I closed it while I gathered some more information. I edited the original comment.

**Comment by Ommina** [comment]
I'm not sure if I'm adding anything useful, or just noise, but with 1.4.15.127 (1.10.2) I'm getting a UU for ~12,000 EU, far less than @brad18 measured, above.  Three pieces of coal in a generator was all it took.

Which seemed pretty generous indeed.

**Comment by modmuss50** [comment]
Humm, something is indeed wrong then.
