### ISSUE TITLE
[1.11] Crash on launch

### ISSUE THREAD

**Issue by vrork** [TechReborn/TechReborn#823]
Welp, i am crashing on lauching, here is the crash.
TechReborn - 1.11-2.0.0.29
RebornCore - 1.11-2.10.0.33

http://pastebin.com/VZE6et5R

**Comment by shuymn** [comment]
same issue occured.

crash report: http://pastebin.com/rzL6C8YF

Minecraft: 1.11
Forge: 2180(latest)
TechReborn: TechReborn-1.11-2.0.0.29-universal
RebornCore: RebornCore-1.11.2.10.0.33-universal

It's similer to #821 (closed issue)

**Comment by modmuss50** [comment]
Ah I know why, I will fix once I get back to my pc

**Comment by modmuss50** [comment]
Ok should be fixed now, please let me know if its not

**Comment by vrork** [comment]
Fixed!

**Comment by modmuss50** [comment]
Nice, thanks for reporting <3
