### ISSUE TITLE
Localisation issue with The One Probe (1.11 - v2.0.0.29)

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/TechReborn#824]
When using TR in 1.11 all blocks/ores are showing incorrectly in The One Probe.

https://gyazo.com/873ac68eb731746410a6fd5899606574

I believe this to be a localisation issue with TR.

**Comment by modmuss50** [comment]
Do they work fine when looked at in the inventory?

**Comment by modmuss50** [comment]
In dev they work fine: https://modmuss50.me/shots/ss08-25-20.png
so it may be an issue that only happens outside dev.

**Comment by Boomflex** [comment]
In the Inventory itself it does work yes, but in the world when placed, no.

Also, machines too.

https://gyazo.com/fb1e8de418abd5f6c276e383bed5966a

**Comment by modmuss50** [comment]
humm, ok. Thanks I think I have an idea on what it could be.

**Comment by Boomflex** [comment]
Latest update changed the error to this:

https://gyazo.com/c741de14de79bccfc2dc54161dd56c08

**Comment by Prospector** [comment]
This should be fixed in the latest version on curse when I did some changes. Please update.

**Comment by modmuss50** [comment]
Nothing else we can do if the new fixes dont sort it. Closing
