### ISSUE TITLE
GUI visual bug on BatBox (1.11 - v2.0.0.29)

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/TechReborn#827]
Do I now owe the BatBox energy?

https://gyazo.com/aa84f4af39013e3e0b1a7f863a6734df

When full and the chunk is unloaded, coming back to this.

Repeatable.

**Comment by modmuss50** [comment]
This bug has been around for ages, and its got something to do with syncing the power to the client. I will have to take a close look into this again.

Dupe of https://github.com/TechReborn/TechReborn/issues/703
