### ISSUE TITLE
Server Crash - net/minecraft/client/entity/EntityPlayerSP

### ISSUE THREAD

**Issue by whatthedrunk** [TechReborn/TechReborn#829]
Tried to update the mod earlier but got this on the server. Single player worked fine. 

http://pastebin.com/k0rNeyM3

**Comment by ProfessorProspector** [comment]
Ah, I see the problem. Try with this build of RebornCore https://jenkins.modmuss50.me/job/RebornCore/job/RebornCore-1.11/50/

**Comment by Prospector** [comment]
Can you try with this build and make sure it's fixed? https://jenkins.modmuss50.me/job/TechReborn/job/TechReborn-1.11/48/
