### ISSUE TITLE
Nei Handler does not show correct amount of forestry wood

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#83]
The Noteblock recipe for example, in the assembling machine it normally requires 8 planks and one redstone, though wood from Forestry, which is ore dict correctly, only requires 1, despite the fact that its still 4 planks from a log like any other wood.

First pic shows Extra Trees wood, it asks for 8, same for Vanilla wood
![2015-07-20_22 39 51](https://cloud.githubusercontent.com/assets/7843312/8775963/a7b3d6a0-2f30-11e5-8983-f2cbf9bd63cc.png)

Second shows Forestry wood., it only asks for 1
![2015-07-20_22 39 54](https://cloud.githubusercontent.com/assets/7843312/8775962/a7b29eb6-2f30-11e5-9dbe-ae7d797f0eac.png)

Lastly, this shows both wood types are ore dictionary correctly. 
![2015-07-20_22 41 14](https://cloud.githubusercontent.com/assets/7843312/8775964/a7b9d672-2f30-11e5-9a69-cc2b037f76e6.png)

**Comment by gigabit101** [comment]
hmm It it uses the ore dict so im not sure whats wrong

**Comment by modmuss50** [comment]
Are you saying it works fine with forestry but not extra trees?

**Comment by TheQuantumGeneral** [comment]
Wasn't sure at first, but its Forestry that is working incorrectly.

**Comment by modmuss50** [comment]
ok thanks

**Comment by modmuss50** [comment]
It should work fine, RecipeHandler.addRecipe(new AssemblingMachineRecipe(new ItemStack(Blocks.planks, 8), new ItemStack(Items.redstone, 1), new ItemStack(Blocks.noteblock), 120, 5));

**Comment by TheQuantumGeneral** [comment]
This is the problem recipe I believe, only Iron and Pyrite ask for calcite to process, yet there is no in game blast furnace recipe for Pyrite. Somehow Pyrite and Galena are being mixed up. 

RecipeHandler.addRecipe(new BlastFurnaceRecipe(BlockOre.getOreByName("pyrite"), ItemDusts.getDustByName("calcite"), new ItemStack(Items.iron_ingot, 2), ItemDusts.getDustByName("darkAshes"), 140, 120, 15000));

**Comment by modmuss50** [comment]
This appears to only be an issue with the nei handler

**Comment by Speiger** [comment]
I found this and this is bad:
https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/util/ItemUtils.java#L109

You override the oredictionary. Please copy the itemstack instead of changing the name of the orereference! This could be also your bug...

**Comment by modmuss50** [comment]
Oh, :) that looks like it! Let me test
