### ISSUE TITLE
Red Garnet not found? (v.1.11-2.0.4.50)

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/TechReborn#836]
It looks like when TNT went off it tries to drop Red Garnet but it can't be found or created?

http://pastebin.com/JW1MM9XD

Not entirely sure how to read Crash Logs but that is what I denote from it.

**Comment by modmuss50** [comment]
I know what's up, I think @ProfessorProspector renamed some things, I can fix it in a few hours if he doesn't. Just don't blow up Red Garents for now

**Comment by Prospector** [comment]
Oh yeah. I guess I missed that one. Just change it to red_garnet instead of redGarnet and it should be good

**Comment by Prospector** [comment]
I can fix it right now on githubs editor on mobile :P
