### ISSUE TITLE
HWYLA Energy Caps Receiving NPE

### ISSUE THREAD

**Issue by ChloeDawn** [TechReborn/TechReborn#839]
**Mod version:** [2.0.6.71](https://minecraft.curseforge.com/projects/techreborn/files/2356177)
**HWYLA version:** [1.8.5-B19](https://minecraft.curseforge.com/projects/hwyla/files/2355186)
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

**Stacktrace:**

```[Netty Server IO #1/WARN] [Waila]: mcp.mobius.waila.addons.capability.HUDHandlerEnergy.getNBTData:47```
```[Netty Server IO #1/WARN] [Waila]: Caught unhandled exception : [class techreborn.tiles.TileAlloySmelter] java.lang.NullPointerException```

This occurs in the console every time a Tech Reborn machine is placed in the world.

**Link to referenced line in the stacktrace:** [mcp.mobius.waila.addons.capability.HUDHandlerEnergy.getNBTData:47](https://github.com/TehNut/HWYLA/blob/1.11/src/main/java/mcp/mobius/waila/addons/capability/HUDHandlerEnergy.java#L47)

**TechReborn config, if relevant:** [main.cfg](http://hastebin.com/fozivaqolu.cfg)
**RebornCore config, if relevant:** [reborncore.cfg](http://hastebin.com/agasadojuf.cfg)

**Edit:** Updated title to just HWYLA, since WAILA itself doesn't have capabilities support..

**Comment by modmuss50** [comment]
Is this still an issue? It hasnt been brought to my attention for a while?

**Comment by modmuss50** [comment]
Uhh, not sure what we are doing wrong. I dont believe its our issue.
