### ISSUE TITLE
Config Missing Some Formatting

### ISSUE THREAD

**Issue by ChloeDawn** [TechReborn/TechReborn#840]
**Mod version:** [2.0.6.71](https://minecraft.curseforge.com/projects/techreborn/files/2356177)
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

There is an entry with missing localization in `main.cfg`.

![image](https://cloud.githubusercontent.com/assets/9869940/21204825/116ee22e-c251-11e6-8d2a-a5f4b03bc68d.png)

There is also an entry with inconsistent formatting:

![image](https://cloud.githubusercontent.com/assets/9869940/21204893/70c2c3a8-c251-11e6-8de8-1a05e3902175.png)

That's all there is to this issue, really.

**Comment by modmuss50** [comment]
Not even worth spending my time fixing tbh, and it works fine. Sorry.

**Comment by Prospector** [comment]
Fix it yourself! :P

**Comment by modmuss50** [comment]
I dont want to break the config as well, thats another reason.
