### ISSUE TITLE
Semifluid generator missing texture

### ISSUE THREAD

**Issue by Ourten** [TechReborn/TechReborn#842]
At the commit [c12d5aa](https://github.com/TechReborn/TechReborn/commit/c12d5aaf1e4de45cc4529ea90c6c1a202b1ab197) the **Semifluid Generator** in the ActivatedState doesn't have **any textures nor animation**.

**Comment by modmuss50** [comment]
The block state isnt being set to active when I put oil in it.

**Comment by drcrazy** [comment]
It looks like it is fixed now

![image](https://user-images.githubusercontent.com/1382352/29731258-6e7bbbfa-89ec-11e7-8447-6d5262b10cf9.png)
