### ISSUE TITLE
Fluids generators invalid fluid display

### ISSUE THREAD

**Issue by Ourten** [TechReborn/TechReborn#843]
The fluids generators don't display correctly the used fluid in their gui.

The SemiFluid, GasTurbine and DieselGenerator show a missing texture : 
 <img src="http://i.ferenyr.info/images/2016/12/10597a1.png" width="400">

The ThermalGenerator, this one is special and I don't know why, just show an air ItemStack : 
 <img src="http://i.ferenyr.info/images/2016/12/576f523.png" width="400">

**Comment by modmuss50** [comment]
I assume the generators have the same issues in 1.10? I doubt they broke this bad in the update.

**Comment by lynxx131** [comment]
Yes this issue appears to be present in 1.10.2 as well.

**Comment by modmuss50** [comment]
Ok, I think im going to redo all the generators in 1.10 then, and pull that over to 1.11
