### ISSUE TITLE
[1.10.2] Energy system explosions

### ISSUE THREAD

**Issue by lynxx131** [TechReborn/TechReborn#845]
Just a couple of problems I have seen with energy transfer. Please forgive me if these are already known issues or have been decided on already.

## Two TechReborn MFE's connected face to face as per the below screenshot will blow up the receiving MFE.

![mfe_direct_connect](https://cloud.githubusercontent.com/assets/12794418/21234255/e1deb068-c2e9-11e6-8ee2-ff59f996031e.png)

Weirdly this only occurs when the rear MFE already has stored energy if both MFEs are empty and directly connected as per the above screenshot and I then connect a generator of some kind to the rear MFE the front one doesn't blow up. On the flip side if the rear MFE is empty and I charge it with a battery then the front MFE will blow up so it seems to only happen when the MFE has a lot of stored energy to quickly discharge.

This does not occur if connected via TechReborn cables of any tier. This also does not happen with Battery Boxes it only occurs with MFE's and MFSU's from what I can see.

Connecting an MFE/MFSU directly to a standard coal generator that already has energy in its buffer will also cause the MFE to explode but if the generator has no energy its buffer and then I burn some coal the MFE charges happily. Again does not happen if I use a TechReborn cable of any tier to connect to the Generator.

Connecting TechReborn blocks together via IC2 cables produces all the same results above in the same scenarios. However connecting two TechReborn Battery boxes via IC2 cables works perfectly fine just like connecting two TechReborn Battery boxes face to face works fine.

Unfortunately although I am a developer I haven't had any experience with Forge or Minecraft modding and the underlying mechanics so wouldn't know where to even start.

**Comment by lynxx131** [comment]
The explosions only happen if the RebornCore option "Allow EU" is set to true. If the option is set to false then directly connecting two TechReborn MFE's face to face results in the second MFE getting no energy at all.

**Comment by modmuss50** [comment]
That would explain it, the explosions are coming form ic2's energy net. And ours doesn't work without cables atm. So it's two issues in one.

**Comment by Pwnacillin** [comment]
This seems to stem from Power Tier in IC2 vs. Power Tiers in TechReborn. I've tested with IC2 quantum gen and the eu/t doesn't seem to matter, but the power tier outputting does. 

You can set the generator to output 1000 eu/t at power tier 1, which I'm assuming is correlated to "Low" for Tech Reborn and the machines won't explode, but if you do 32 eu/t at power tier 2, then they blow up. 

Its very strange.

**Comment by modmuss50** [comment]
Should be fixed now.
