### ISSUE TITLE
[1.11] Exception ticking world

### ISSUE THREAD

**Issue by codenamedonut** [TechReborn/TechReborn#847]
NoSuchMethodError occurs when using your mod w/ forge 13.19.0.2172 and techreborn 2.0.6.71. 

http://pastebin.com/sNDZQNay

**Comment by Ourten** [comment]
This method was added to Forge in 2173, TechReborn is currently build with the 2180, you should update to the Forge RB, the 2189.

**Comment by codenamedonut** [comment]
i need to stay on 2172 as 2173+ breaks a bunch of mods. is there a version of techreborn that works with 2172?

**Comment by modmuss50** [comment]
No, sorry.

**Comment by codenamedonut** [comment]
alright. thanks. i guess i'll have to wait for half the mods to update to forge higher than 2173 and then add your mod to it!

**Comment by modmuss50** [comment]
Most mods should be on the recommended version of forge.
