### ISSUE TITLE
[1.11] 2.0.6.71 Wrong FE amounts displayed with large amounts of FE in BatBoxes

### ISSUE THREAD

**Issue by CorwinJV** [TechReborn/TechReborn#848]
![image](https://cloud.githubusercontent.com/assets/8602242/21282058/731cccc4-c3a6-11e6-9ee5-b8fdd3589fff.png)

Playing in ATM2

**Comment by modmuss50** [comment]
dupe of https://github.com/TechReborn/TechReborn/issues/703
