### ISSUE TITLE
[1.10.2] Hopper below Industrial Grinder crash

### ISSUE THREAD

**Issue by jacfalcon0** [TechReborn/TechReborn#849]
Downloaded the newest version of the AllTheMods pack, and it updated me from updated from

TechReborn-1.10.2-1.4.14.118-universal

to

TechReborn-1.10.2-1.4.15.127-universal

and I couldn't boot the game. After some searching, I removed a hopper that was pulling from below my Industrial Grinder to a furnace to it's side, and the game stopped crashing right before bringing me into the map. I replaced the hopper below it in-game and the game crashed again right there. Edited it back out and playing fine, but I wanna use the hopper again :(

Crash logs:
http://paste.ee/p/MuJQO

**Comment by modmuss50** [comment]
Have you got crash logs?

**Comment by modmuss50** [comment]
Working fine in 1.11, not A lot I can do without logs.

**Comment by jacfalcon0** [comment]
Sorry about that, there ya go!
http://paste.ee/p/MuJQO

**Comment by modmuss50** [comment]
Ah thanks

**Comment by modmuss50** [comment]
Closing this as it should be fixed in v2. Open another issue if not.
