### ISSUE TITLE
EU/RF ratio wrong?

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#85]
From the config file

    # How many eu are in each RF
    I:"Eu per RF"=4

Four EU per RF is back to front, the community standard is 4 RF per EU, because RF is easy as pie to generate.

Should be like this

    # The amount of RF that equal 1 EU. 4 by default, so 4RF == 1EU and .25EU == 1RF
    I:"EU Conversion"=4

**Comment by Carbon-Ghost** [comment]
It's indeed 4 RF to 1 EU, the standard was established by the first converter MJ EU mod, and since 1 MJ is 10 RF; the conversion was easy ^^

**Comment by modmuss50** [comment]
Thanks for that. I need to test this system soon, then when it's ready I will move all the machines to use both, by default it will not work with rf when ic2 is installed.

**Comment by TheQuantumGeneral** [comment]
Wasn't sure if this needed a new issue,
I set the config to make 1 EU = 8 RF but WAILA is still showing that 8 RF = 1 EU
![capture](https://cloud.githubusercontent.com/assets/7843312/8890493/25063a62-3346-11e5-9443-e8494ce82001.PNG)
![2015-07-26_03 24 09](https://cloud.githubusercontent.com/assets/7843312/8890492/2505460c-3346-11e5-936e-403e27f7ba8c.png)
![2015-07-26_03 24 14](https://cloud.githubusercontent.com/assets/7843312/8890494/250654a2-3346-11e5-8821-6717ee2b8b4a.png)

**Comment by Carbon-Ghost** [comment]
Did you guys checked my STORAGE UNITS VALUES reminder xD ? Unless WAILA is derping, almost all of them are false xD Also, GUI makes me want to cry, why don't you use the old GT AESU GUI ? I mean, we have full permission from Greg, and it looks better, + I can tweak it a bit for making it visually more appealing, not like this xD Also, why did you dissolved the team in Github ?

**Comment by modmuss50** [comment]
What do you mean about the storage units? The maximum amount of energy in the tile?

**Comment by Carbon-Ghost** [comment]
No, I mean the old values of the storage units EU Storage amount, https://github.com/TechReborn/TechReborn_TODO/issues/55
