### ISSUE TITLE
A lot of issues and questions

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#851]
Forge 12.18.2.2166
RebornCore 2.8.4.77
TechReborn 1.4.15.127

Hello, I'm working currently on a modpack that plans to use TechReborn as an endgame tech mod.
I don't know a lot about it, so I investigated block after block and had a lot of issues. (Sorry that all the issues are in one bug report, but I don't really feel like making >10 of them (also maybe some aren't even bugs and misunderstandings instead and some might be duplicate to open issues sorry)).

1.) Digital Chest / Quantum Chest: doesn't update numbers and you can't insert items through pipes/hoppers
2.) Sawmill: I was figuring out how it works, it seemed to need liquids, but as I inserted water with an EnderIO Fluid Tank the game crashed and even corrupted my world. I had to delete the block with MCEdit, so this is a major bug. http://pastebin.com/LvsPRqYD
3.) Industrial Grinder: The GUI doesn't update when fluids get added also the recipe in JEI doesn't show if the fluid is water or Mercury.
4.) Transformer: Do they work? I added a MV Transformer behind a MFE to transform down from 512 to 128, machines after it don't get power though (and The One Probe shows no power in the Transformer) and if I place it vice versa it blows up. Also I connected machines that say 128 EU/t max with a MFE with Copper Cables to them and nothing blew up. Is this supposed to happen? Has the MFE the wrong tooltip?
5.) Implosion Compressor / Vacuum Freezer: works but still says "Incomplete Multiblock" even though it is built correctly
6.) Lithium Cell: is there a way to get those? I found a wiki that says that you have to electrolyze Clay Dust to get them, but that doesn't seem to be implemented, just as no way to get Clay Dust
7.) Semifluid Generator / Diesel Generator / Gas Turbine: they don't work with cells, only with buckets but you can't turn cells into buckets as far as I can see. The Diesel Generator works only with Nitrofuel which doesn't seem obtainable, the Semifluid Generator I could only get to work with Biomass, with Creosote the game crashed. http://pastebin.com/j6ZmuGFx All in all those generators seem useless at the moment.
8.) Distillation Tower / Plasma Generator: has no GUI and doesn't connect to cables, so it seems unfinished. Will they be implemented?
9.) Fusion Reactor: JEI Recipes seem wrong for the outputs and isn't 4RF = 1EU? But I attached a full Vibrant Capacitor Bank (25M RF) to the Reactor and it had then 100M EU so it seems the conversion rate is here vice versa.
10.) I don't understand the Iridium plan. You can get Iridium Ore from UU-Matter but the only weird use seems to get infinite Platinum from the Grinder. Iridium Nuggets you get from Sheldonite, but there are no uses either. And then you can get Iridium Plates from 4 Iridium Ingots (which are unobtainable) in a Implosion Compressor, but you can get them from one Ingot in a normal Compressor (why would you use the first recipe?). There seem to be missing and not fitting recipes.
11.) Recycler: missing Progress Bar and I'm asking myself with the Overclockers not working how you would get Scrap in a reasonable speed
12.) I wanted also to add a recipe to the Grinder with Minetweaker. Looking into the github I could only find code for the Industrial Grinder which is fine, but it didn't do anything. 
Then I saw the commented line in its code, so it seems broken at the moment.

These are only the fix I found after a couple of hours testing. I really like to use this mod in my pack, but I can't really use it at this state. I would really appreciate it if you can look into these issues.

**Comment by rikislief** [comment]
the iridium is needed for the industrial blast furnace right? You can get iridium ingots through the arc furnace. To get there i had to build 7 multiblocks. I think a lot of your problems arent really problems but just not looking good enough.

**Comment by laserlemons** [comment]
I think a lot of these issues come from lack of documentation or JEI support for a lot of the machines. I have a really hard time progressing through this mod because the only way to figure it out is to look up old ftbwiki stuff for gregtech and industrialcraft and test out whether it's the same or not.

**Comment by davqvist** [comment]
@rikislief You know that the Arc Furnace is from Immersive Engineering right? And if I know it correctly its Arc Furnace just looks for any registered Ores, so not only isn't it the intended way it probably also breaks the normal progression. And be sure I looked enough, at least what JEI tells me, It might be that there are ways that JEI aren't telling me, but that's why I'm asking. And I don't think you need Iridium for the Blast Furnace, at least not for lower temperatures. You need it for Advanced Machine Casings.

@laserlemons That might be my problem. That's why I'm asking though specifically regarding Iridium, some other issues are though serious bugs that need to be fixed. I could easily add a recipe for Iridium Nuggets to Ingots, but before I do that I want to know for sure what the intended ways are.

**Comment by modmuss50** [comment]
Closing this, please open one issue per issue as this is impossible to keep track of. Sorry.

**Comment by davqvist** [comment]
I did just now, I hope it's better for you now.
