### ISSUE TITLE
[1.11] TechReborn Gems not oreDict for usage on Mystical Agriculture.

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/TechReborn#853]
I raised a query with the MystAgri devs in regards to the TechReborn gems (sapphire, ruby and peridot) not working with their mod.

See below correspondance:

https://gyazo.com/f78e6fe03a66ff7fecbc7db8281c59c5

Thanks,

Boom

**Comment by modmuss50** [comment]
Humm I'm sure we register them, if not I will check

**Comment by Prospector** [comment]
lol it's probably my renaming again. I think I've caused at least 10 github issues because of one stupid rename

**Comment by Prospector** [comment]
ah I see the problem. the gems are being added with double `gem` so ruby is `gemgemRuby`
