### ISSUE TITLE
[1.11] Crash on load (fluid chlorine not found)

### ISSUE THREAD

**Issue by StarrDraws** [TechReborn/TechReborn#854]
On load I get this crash on latest ver 2.0.7.77  http://pastebin.com/BgMPiRfY
TLDR: Caused by: java.lang.NullPointerException: The fluid chlorine could not be found

**Comment by modmuss50** [comment]
I think I fixed it, I will take another look

**Comment by StarrDraws** [comment]
Alright thanks.

**Comment by modmuss50** [comment]
Ah I think I fixed it in 1.10, just need to merge the changes to 1.11 :)
