### ISSUE TITLE
[1.11] TechReborn-1.11-2.0.7.77 redGarnet not found, still not fixed from last version

### ISSUE THREAD

**Issue by shortybsd** [TechReborn/TechReborn#855]
Forge version 2188
RebornCore-1.11-2.11.3.65-universal
TechReborn-1.11-2.0.7.77-universal

I saw a Red Garnet in the cave wall, I mined it only for it to not yield anything. Checked the server logs and this same error from last version still persists:
http://pastebin.com/SayMmzAD

**Comment by modmuss50** [comment]
@ProfessorProspector renamed a load of shit I think, I will go through and fix it

**Comment by shortybsd** [comment]
lol all good, that lower-case change driving you nuts? I can help you with a sh script or if you use windows a batch script to rename everything properly.

**Comment by modmuss50** [comment]
we should be good, tbh

**Comment by securitycopper** [comment]
Related to: https://github.com/TechReborn/TechReborn/issues/852
