### ISSUE TITLE
[1.11] Cannot mine Ruby Ore

### ISSUE THREAD

**Issue by MoonCutter2B** [TechReborn/TechReborn#856]
Not sure if this an old issue or not but when I try to mine a ruby ore using an iron pickaxe the block breaks but I get no ruby. (Maybee I need a diamond pickaxe but that is not what JEI say)
Latest version of everything.
All other tech reborn ores that I'v found so far is ok, only rubies is a problem for me so far.
According to the author of Silent Gems who alos have a ruby ore he has recreated the problem with only Tech Reborn (+ core thingy) installed

**Comment by codenamedonut** [comment]
this is happening with me also. can't mine it with diamond pickaxe either. also, if a creeper explodes breaking a ruby block, the server crashes. 
here's the crash report from that - http://pastebin.com/UgJ9VKRQ
