### ISSUE TITLE
[1.10.2] Iridium Ore Produces Iridium Ore in Industrial Grinder

### ISSUE THREAD

**Issue by revdave33** [TechReborn/TechReborn#857]
TechReborn v. 1.4.15.127

I successfully built the Industrial Grinder. In processing different Ores, I noticed that Iridium Ore produced Iridium Ore plus small pile of Platinum.

So, with one Iridium Ore you can produce infinite Platinum and nothing useful with Iridium itself.

This actually does match the recipe that is shown in the GUI.

**Comment by modmuss50** [comment]
I may have fixed this in 1.11, I will check

**Comment by Prospector** [comment]
This is fixed in 1.11.2.
