### ISSUE TITLE
[1.11] Electric Treetap does not accept power from Energizer

### ISSUE THREAD

**Issue by Boomflex** [TechReborn/TechReborn#858]
Hello guys,

It did work, now it doesn't?

https://gyazo.com/36cfda4cebac42a45585ed80a4e91671

I know Modmuss and Ellpeck (ActAdd Dev) spoke about it in chat on the ATM2 discord but I just wanted to document it here :)

Boom

**Comment by modmuss50** [comment]
I know whats up with this, I still need to rewrite the way I handle power in items. Soon(tm)

**Comment by modmuss50** [comment]
This is part of a wider issue that our powered items do not accept tesla or FE. This will be fixed in due course.
