### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by ChloeDawn** [TechReborn/TechReborn#859]
**Mod version:** [2.0.8.84](https://minecraft.curseforge.com/projects/techreborn/files/2358298)
**Forge version:** [1.11-13.19.1.2189](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2189/forge-1.11-13.19.1.2189-changelog.txt)

**No recipes exist for the following:**

- [ ] - All nuggets (Shapeless crafting from ingots).
- [ ] - Fluid Cells (No processing recipes.)
  - [ ] - Heliumplasma Cell
  - [ ] - Chlorite Cell
  - [ ] - Sulphur Cell
  - [ ] - Lava Cell
  - [ ] - Diesel Cell
  - [ ] - Potassium Cell
  - [ ] - Carbon Fiber Cell
  - [ ] - Nitrofuel Cell
- [ ] - Electronic Circuit
- [ ] - HV Cable
- [ ] - Wooden Plate
- [ ] - Obsidian Plate
- [ ] - Lazurite Plate
- [ ] - Iridium Alloy Ingot
- [ ] - Nuke
- [ ] - Scrapbox-inator
- [ ] - Player Detector
- [ ] - Assembling Machine
- [ ] - Block of Refined Iron
- [ ] - Refined Iron Ingot (crafting from block.)
- [ ] - Thorium/Plutonium Fuel Rods (Not sure if these are intended to have recipes or not.)
- [ ] - Dragon Egg Energy Syphon
- [ ] - Iridium Reinforced Stone
- [ ] - Iridium Reinforced Tungstensteel Block
- [ ] - Block of Yellow Garnet (Shaped crafting from gem.)
- [ ] - Yellow Garnet (Shapeless crafting from block.)
- [ ] - Yellow Garnet Plate
- [ ] - Block of Red Garnet (Shaped crafting from gem.)
- [ ] - Red Garnet (Shapeless crafting from block.)
- [ ] - Red Garnet Plate
- [ ] - WIP Machines (Added because other WIP machines *do* have recipes.)
  - [ ] - Industrial Chunkloader
  - [ ] - Magic Energy Converter
  - [ ] - Magic Energy Absorber

**Bugged recipes/information for the following:**

- [ ] - No ores display their world generation information via. Just Enough Resources.
- [ ] - Ruby, Sapphire, and Peridot Plate recipes have mixed inputs and outputs.

![recipe_bug_001](http://i.imgur.com/oCRCyP6.png)

- [ ] *Also the progress element is misaligned.* ;-;
- [ ] *Also also the energy cost for recipes is always in EU even though I have my config set to FE.*

**Comment by Prospector** [comment]
most of these are fixed because of the ore dictionary fixes. this is kinda multiple issues in one. Open new issues with any remaining issues
