### ISSUE TITLE
Sync issue and a query on the jackhammer

### ISSUE THREAD

**Issue by xenoflot** [TechReborn/TechReborn#864]
Hi,

I'm testing a new server pack at the moment so playing around in creative.

I tried out the Advanced Jackhammer and noticed that it's very fast on stone and variants, but no faster than hand-breaking on anything else (inc. cobble and ores (modded and vanilla)). Not sure if this is intentional. I'd expect not since I think it'd be a pretty big drawback to the tool.

The second thing I felt worth commenting on is the blitzing speed of the Advanced Jackhammer. It's so fast that my client desynchs from the server and at a guess about 50% of the blocks that my client says are gone, the server still thinks are present. Lots of head-bumping on invisible blocks ensues :)

I have a ~210ms ping to the US-based server. Generally speaking I have no troubles with latency, although when using a tconstuct hammer, it does occasionally mine only the centre block. I'm not sure if there's anything that can be done about that, but I thought it worth mentioning.

techreborn-1.10.2-1.4.15.127-universal
reborncore-1.10.2-2.8.4.77-universal
forge 2185

Cheers!

**Comment by Prospector** [comment]
Yeah this is intentional. It's function is to allow you to easily clear mass amounts of stone and not drop any of it, I believe. I'm not sure if it does that at the moment, but I will take a look.

**Comment by Prospector** [comment]
As for the sync issue, that even occurs with vanilla tools when you mine blocks instantly. I don't think we can do anything about that.

**Comment by modmuss50** [comment]
We can make it slower, if we cannot do that there isnt a lot we can do about that sorry.

**Comment by xenoflot** [comment]
@ProfessorProspector Ah ok. I didn't specifically notice if there were drops. I think that's fair though, blinding speed and no drops (or maybe a few pieces of gravel!)

Yeah, I think there's probably not much you can do about it, I just felt it was worth mentioning in case you had some performance improvements you'd been procrastinating over :-P

I wouldn't slow it down, modmuss. Keep it true to the vision. I think most server players accept that some stuff just doesn't work in SMP.

**Comment by Prospector** [comment]
Ooh I like that gravel idea!

**Comment by xenoflot** [comment]
I'm in a good mood! You like that idea? It's yours! Royalty free! Merry Christmas, Professor!
