### ISSUE TITLE
Scrapbox-inator Missing Recipe

### ISSUE THREAD

**Issue by ChloeDawn** [TechReborn/TechReborn#866]
**Mod version:** [2.0.8.91](https://minecraft.curseforge.com/projects/techreborn/files/2358919)
**Forge version:** [1.11-13.19.1.2189](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2189/forge-1.11-13.19.1.2189-changelog.txt)

**Scrapbox-inator has no crafting recipe.**

![2016-12-22_11 54 50](https://cloud.githubusercontent.com/assets/9869940/21424882/834f00d0-c83d-11e6-8f08-4cdbf4327344.png)

**Comment by Prospector** [comment]
The scrapboxinator doesn't even work at the moment. And to be honest, we might want to remove it entirely because a dispenser opens scrapboxes as well.

**Comment by robintrepte** [comment]
you could change it to a device that makes scrap boxes out of scrap
