### ISSUE TITLE
Fluid Cells Missing Processing Recipes

### ISSUE THREAD

**Issue by ChloeDawn** [TechReborn/TechReborn#867]
**Mod version:** [2.0.8.91](https://minecraft.curseforge.com/projects/techreborn/files/2358919)
**Forge version:** [1.11-13.19.1.2189](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2189/forge-1.11-13.19.1.2189-changelog.txt)

**The following fluid cells have no processing recipes:**

- [x] - Heliumplasma Cell
- [x] - Chlorite Cell
- [x] - Sulphur Cell
- [x] - Lava Cell
- [x] - Diesel Cell
- [x] - Potassium Cell
- [x] - Carbon Fiber Cell
- [x] - Nitrofuel Cell

**Comment by drcrazy** [comment]
Diesel, Carbon Fiber and Nitrofuel are still actual

**Comment by drcrazy** [comment]
Carbon fiber cell could be made in Industrial Electrolyzer from Ash
Nitrofuel cell could be made in Chemical reactor from oil and nitrogen
Diesel recipe added to Industrial Centrifuge as a temporary workaround until Distiallation tower will be implemented
