### ISSUE TITLE
Red Garnets behaving strangely

### ISSUE THREAD

**Issue by xenoflot** [TechReborn/TechReborn#871]
Hi guys,

I set up an RFTools builder as a clearing quarry. Shoved a Diamond "Iron Chest" on top and set it running. Everything's going well, then I notice the quarry has been spitting a few red garnets on the ground. Chest isn't full and indeed the Builder simply pauses when the output inventory is full. Let it run a bit longer and I hear the pop pop pop of items coming into my personal inventory and sure enough, I have a few more red garnets. No red garnets were placed in the chest by the builder, yet sapphires etc. were.

I set up a 2nd chest and used an xu2 transfer node to pipe them into the same diamond chest and that worked fine. /shrug

Further, I have an inventory toolip mod which shows me some info on mouse-over and what it reports from the garnets is different from your other gems. http://i.imgur.com/xeoLrPq.png

I'm reporting to you rather than McJty as the red garnets were the only items or blocks that didn't wind up in the output chest. 

Cheers!

techreborn-1.10.2-1.4.15.127-universal
reborncore-1.10.2-2.8.4.77-universal
rftools-1.1x-5.71
mcjtylib-1.1x-2.3.1
compatlayer-1.10-0.1.4
modnametooltip-1.10.2-1.6.0

**Comment by modmuss50** [comment]
I know what's up, I will take a look after Christmas.
