### ISSUE TITLE
There Is No Way To Produce Lazurite Plate and Some Other Plates.

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#872]
Using latest version of mod by now, and using forge 13.20.0.2201 (latest).
Using also JEI; i just tried to build a Solar Panel.
 I couldn't because there is no way to produce **Lazurite Plate**.
And i noticed that **wooden plate, obsidian plate, refined iron plate, red garnet plate, yellow garnet plate** are not craftable as Lazurite Plate. Is this problem about "coming soon" ? or is it a bug that we can not build a solar panel for get electricity -.-
thanks a lot...

**Comment by Prospector** [comment]
You say latest version, this is on 1.11.2?

**Comment by ghost** [comment]
yes it is

**Comment by ghost** [comment]
anyone help? =(

**Comment by Prospector** [comment]
Yeah we're aware of this. We'll try to fix it soon

**Comment by ghost** [comment]
thanks ^^ hope we will build a solar panel this night :D (on my time, after 9 hours)

**Comment by ghost** [comment]
you labelled 1.11.0 but it is on 1.11.2

**Comment by ghost** [comment]
when will the new release come...

**Comment by Prospector** [comment]
Give me a minute

**Comment by ghost** [comment]
and can you tell me what is the key for the run the engine of the lithium batpack? can i fly with it? i pressed jump but its not working. it is %100 charged.

**Comment by Prospector** [comment]
The Batpack charges items in your inventory. It's not a jetpack.
