### ISSUE TITLE
MaxStackSize of EmptyCells is 16 should be 64 or anything above 18

### ISSUE THREAD

**Issue by AxMedia** [TechReborn/TechReborn#873]
The Industrial Electrolyzer's recipe for making beryllium cells is broken as it needs 18 empty cells to run.
Obviously you can't put more than 16 in as that's the maximum stacksize.

Very easy fix in items/DynamicCell.java:
```
public DynamicCell()
{
    func_77637_a(TechRebornCreativeTab.instance);
    func_77655_b("techreborn.cell");
    setMaxStackSize(**64**);
}
```
Thanks very much!

**Comment by modmuss50** [comment]
I think the easy fix for this is to lower the required cell count.

**Comment by Prospector** [comment]
Semifixed in 1.11.2. Recipe still uses way too many, but cells stack to 64 now.

**Comment by Dorfinger** [comment]
So There's no fix for those playing with the lastest hermitpack using techreborn 1.10.2-1.4.17.141 ?

**Comment by Prospector** [comment]
They need to update, that version is very old.

**Comment by modmuss50** [comment]
I can ask them to update.

**Comment by Dorfinger** [comment]
That would be neat.

**Comment by modmuss50** [comment]
I will ask them when I get a chance.
