### ISSUE TITLE
[1.7.10] Problem with PDA and some recipes missing

### ISSUE THREAD

**Issue by chaos234** [TechReborn/TechReborn#874]
Hey together,

the PDA is missing many text pages (only langauages variables are shown).

This applies to the following pages:

Charge Bench, Chemical Reachtor, Industrial Chunkloader, TechReborn Computer Base Cube,
Digital Chest, Distillation Tower, Electric Autocrafting Table, Fusion Coil, Fusrion Reactor, Industrial
Grinder, Highly Advanced Machine Block, Implosion Compressor, Industrial Electrolyzer,
Aluminium Machin Hull (has also no crafting recipe), Matter Fabricator, Plasma Generator, 
Quantum Chest, Quantum Tank, Rolling Machine, Vacuum Freezer, UU-Matter (incl. missing crafting
recipe), Advanced Drill (incl. missing crafting recipe), Cloaking Device, Lapotonic Energy Orb, 
Laptron Pack (incl. missing crafting recipe), Lithium Batpack (incl. missing crafting recipe), Omni Tool (incl. missing crafting recipe), Rockcutter.

Upgrade Page is compleatly empty (UPGRADES_PAGE stands on it).
All Entries under Power Generation are missing there respective descriptions, Power Storage too.

The Page for the Multiblock(s) is currently also empty (MULTIBLOCK_PAGE and the language variable is still there as also the button to show a non placeable Multiblock but with no knowledge for what it is).

I hope that this will be fixed soon.

I am running latest FTB-Infinity (2.6) so IC2 is included in this pack as well, as well the correct (latest) TRCore is included.

Greeting
Chaos234

**Comment by modmuss50** [comment]
Thanks for putting effort into the report but we no longer support 1.7.10.

**Comment by chaos234** [comment]
This is rly bad since it is then rly, rly, rly bad written. But ok, then I must remove your mod sinc you don't want to fix this or either any bugs (which should normy for 1.7.10 done since many player using 1.7.10 currently because not all mods are ported yet).

Cheers

**Comment by modmuss50** [comment]
I wish we could support 5/6 versions of minecraft, but its not that easy. We havent been supporting TR in 1.7.10 for 6 months now. Sorry.

**Comment by chaos234** [comment]
Ok. I accept it. But can u answere me how this can happen? I mean the mod looks great but why is the ingame documentation such a mess up so that it's hard to use?

Pls don't understand it false, since normaly this should be checked in a single player test, shouldn't it?

**Comment by modmuss50** [comment]
The ingame documentation was never finished, and was added late. the best way to figure out how to use the mod is to look on old wiki's.

**Comment by chaos234** [comment]
So that is the point, I see. Then to bad that it wasn't finished with the 06/2016 release :( 

But thanks for the fast response.
