### ISSUE TITLE
[1.11.2] Localization Missing

### ISSUE THREAD

**Issue by sokratis12GR** [TechReborn/TechReborn#876]
Everything is missing their localization
![image](https://cloud.githubusercontent.com/assets/12274096/21619427/51ffa740-d1f8-11e6-87e9-59232e175a2e.png)

Reason: probably error in the localization files

**Comment by modmuss50** [comment]
We spoke on discord and its fixed in the beta version

**Comment by Prospector** [comment]
Don't think it is. That screenshot was on the beta

**Comment by sokratis12GR** [comment]
That screenshot wasn't on the beta All the Mods isn't using the beta version, they use latest stable

**Comment by sokratis12GR** [comment]
![image](https://sokratis12gr.com/uploads/e7A9P2jQ.png)
That is how it looks while running beta

**Comment by modmuss50** [comment]
yeah, @ProfessorProspector you fixed this.
