### ISSUE TITLE
Breaking MFE with pickaxe incorrectly returns Advanced Machine Block

### ISSUE THREAD

**Issue by xenoflot** [TechReborn/TechReborn#877]
Tested with an ActuallyAdditions drill and a TR diamond drill. 

I have lots of mods in a custom pack so if it doesn't do it for you, let me know and I'll try to narrow it down.

TR 1.10.2-1.4.16.133
Forge 2185

**Comment by modmuss50** [comment]
You need to use a wrench to break things like that.

**Comment by xenoflot** [comment]
That's true, but an item constructed with a regular machine block, shouldn't return an advanced machine block :)

**Comment by modmuss50** [comment]
Ah right
