### ISSUE TITLE
Digital Chest / Quantum Chest not working correctly

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#878]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

Digital Chest / Quantum Chest: doesn't update numbers and you can't insert items through pipes/hoppers

**Comment by Prospector** [comment]
Fixed in 1.11.2

**Comment by Prospector** [comment]
Actually just the numbers are fixed. automation is fucked on every machine, at least in 1.11.2

**Comment by davqvist** [comment]
Thanks for all the fixes, I appreciate it. But given that all the modpacks currently in development are 1.10.2 (including mine) and it is a bug not a feature request, is there a chance the bugs will get fixed for 1.10.2 as well?

**Comment by Prospector** [comment]
@modmuss50 said he plans on attempting to port the 1.11.2 version to 1.10.2, so at this point just hope he's able to do that.

**Comment by davqvist** [comment]
That would be perfect, thanks for your quick answer.
