### ISSUE TITLE
Sawmill corrupting world if you insert water

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#879]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

Sawmill: I was figuring out how it works, it seemed to need liquids, but as I inserted water with an EnderIO Fluid Tank the game crashed and even corrupted my world. I had to delete the block with MCEdit, so this is a major bug. http://pastebin.com/LvsPRqYD

**Comment by modmuss50** [comment]
Do you have an ender io machine next to it?

**Comment by davqvist** [comment]
No, only the Fluid Tank filled with water, pushing into the Sawmill.

**Comment by modmuss50** [comment]
Ah, fluid tank (from ender io I guess) that stack contains this: `crazypants.enderio.machine.AbstractMachineEntity.doUpdate`

**Comment by davqvist** [comment]
Yes EnderIO Fluid Tank as described in the original post.
