### ISSUE TITLE
Implosion Compressor Incomplete Multiblock

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#881]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

Implosion Compressor / Vacuum Freezer: works but still says "Incomplete Multiblock" even though it is built correctly

**Comment by Prospector** [comment]
Yeah, we need to get the holograms working on all multiblocks.

**Comment by xenoflot** [comment]
Possibly related so I'll log it here.

Blast furnace hologram is set 1 Y value too low, showing the machine casings as starting as 1 block below the blast furnace block. If the whole casing shebang is moved up such that it's sitting on the same level as the blast furnace block, everything works OK.

techreborn-1.10.2-2.1.2.160-universal

**Comment by drcrazy** [comment]
There is a wiki article on how to build multi-block for Implosion Compressor: https://wiki.techreborn.ovh/doku.php?id=blocks:implosion_compressor

Vacuum freezer works fine in 1.12.1 and it is not a multi-block

**Comment by drcrazy** [comment]
Fixed by @alexpic57 with #1269
