### ISSUE TITLE
Lithium Cells: How to obtain?

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#882]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

Lithium Cell: is there a way to get those? I found a wiki that says that you have to electrolyze Clay Dust to get them, but that doesn't seem to be implemented, just as no way to get Clay Dust

**Comment by Prospector** [comment]
Fixed in 1.11.2. Clay dust is electrolyzed into lithium, yes. 
![image](https://cloud.githubusercontent.com/assets/6166773/21659817/3c282562-d281-11e6-816a-f6f1e7092107.png)
