### ISSUE TITLE
Fluid Generators don't work with cells and buckets aren't obtainable

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#883]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

Semifluid Generator / Diesel Generator / Gas Turbine: they don't work with cells, only with buckets but you can't turn cells into buckets as far as I can see. The Diesel Generator works only with Nitrofuel which doesn't seem obtainable, the Semifluid Generator I could only get to work with Biomass, with Creosote the game crashed. http://pastebin.com/j6ZmuGFx All in all those generators seem useless at the moment.

**Comment by Prospector** [comment]
Fluid generators have been massively improved in 1.11.2. This may have been fixed

**Comment by Ourten** [comment]
Fluid Generators work properly with cells in 1.11.2.
Their logic has been remade, you now have JEI recipes integration for all of them.

Diesel Generator accept : Nitrofuel, Nitrocoal Fuel, Lithium, Nitro Diesel, Oil.
Semifluid Generator accept : Oil, Sodium, Lithium.
