### ISSUE TITLE
Adding Industrial Grinder Minetweaker Recipes not working

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#888]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

I wanted also to add a recipe to the Grinder with Minetweaker. Looking into the github I could only find code for the Industrial Grinder which is fine, but it didn't do anything.
Then I saw the commented line in its code, so it seems broken at the moment.

**Comment by modmuss50** [comment]
is it just not showing up in JEI but works in the machine?

**Comment by davqvist** [comment]
It is not working. Maybe I made an error in the script. I tried for example that:
`mods.techreborn.grinder.addRecipe(<techreborn:dust:32>, <techreborn:smallDust:32>, null, null, <chisel:marbleextra:7>, null, 100, 48);`

I think it's because of that commented line:
https://github.com/TechReborn/TechReborn/blob/1.10.2/src/main/java/techreborn/compat/minetweaker/MTIndustrialGrinder.java#L32

**Comment by modmuss50** [comment]
Yep it is that. Easy fix.
