### ISSUE TITLE
Not accepting EU or RF from Immersive Engineering Cables

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#89]
Machines won't accept power from this mods cables which provides both EU and RF.

An Assembling machine not accepting power (Tested to work with IC2 cables)
![doesntlikepowah 1](https://cloud.githubusercontent.com/assets/7843312/8890115/f17897f2-3337-11e5-9930-c5c8d283565c.png)
![doesntlikepowah 3](https://cloud.githubusercontent.com/assets/7843312/8890114/f1785454-3337-11e5-903b-69999b98f1b8.png)

Other mods accepting EU or RF respectively, including Open Computers, Galacticraft, Forestry, Railcraft, Binnies mods, IC2
![doesntlikepowah 2](https://cloud.githubusercontent.com/assets/7843312/8890113/f1782628-3337-11e5-88ed-6558ab26b565.png)

**Comment by modmuss50** [comment]
Can you try with https://github.com/TechReborn/TechReborn/commit/e8bbbcc7c3f9b99e4ec9f1aa40fc95bb9ee70857

it works fine in my dev env, http://modmuss50.me/shots/Minecraft_1.7.10_2015-07-25_17-54-11.png

**Comment by TheQuantumGeneral** [comment]
Works fine, had to wrench and re-place the machines else they went into negative numbers.

Also, everything I tested seems to work fine, but for some reason it takes me around 25-30 seconds to fill the Assembly Machine
