### ISSUE TITLE
If You Put A Cable Between Three Solar Panels World Will Be Corrupted / Some Dusts On Grinder..

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#891]
Is it normal? i put a copper cable between 3 solar panels  like this=> -_- and minecraft closed
using 1.11.2 and forge 1.11.2-13.20.0.2206 and techreborn 2.0.9.25. 
hey, why can't we get lazurite dust from a grinder? please fix it :( and the other dusts. please... because we can not build an industrial grinder........
ANOTHER BUG: can not see saw mill recipes. can not see what we can do with sawmill. probably we can not see any material recipe that produced with sawmill.
another bug: can not see UU-matter recipe.

**Comment by modmuss50** [comment]
Need the log

**Comment by ghost** [comment]
i don't know but i couldn't get the same crash again. i don't have my old log because i deleted minecraft and installed again to know if the problem is in my game... sry

**Comment by modmuss50** [comment]
Ok thanks, I'm going to close this then. Feel free to make a new one if you can get the log.
