### ISSUE TITLE
Fluxed Redstone Wires Won't Work

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#892]
i tried all of them (redstone fluxed, gold fluxed...) i connected them to a solar panel; they consumed all the energy but didn't delivered the energy to the connected machine. why is this? i just wanted to give energy to a centrifuge from a solar panel :( (centrifuge in forestry) because insulated copper cables or gold cables won't connect to centrifuge from Forestry mod. any solution or help? thanks

1.11.2 13.20.0.2206 latest techreborn

**Comment by modmuss50** [comment]
Should go on the Fluxed Redstone issue tracker.
