### ISSUE TITLE
No way to get steel, nickel , or titanium ores to make industrial machines.  for latest version of techreborn  1.11.2

### ISSUE THREAD

**Issue by rayronqween** [TechReborn/TechReborn#893]
Hello found some more late game issues with the mod in my mod pack . Currently, industrial machines are still not craftable let me explain.

So its starts with me starting to craft a rockcutter so here is where the issues start

I need to craft titanium ingot ( no way of getting titanium ore either)  

I need to craft industrial blast furnace 

I need to craft cupronickel heating coal 

I need nickel ingot

only way to get nickel is dust via the Industrial grinder via iron ore or sheldonite ore ( since there is no Nickel Ore) 

I need to craft Industrial grinder which I  need Diamond or tungsten grinding heads both  needing steel 

Only way to get steel with this mod is through the Industrial blast furnance via dust

No way to get steel dust; or the blast furnace due to the crafting loop of missing items....

hope this helps. 

 
 this is for 1.11.2 lastest version of techreborn

**Comment by rayronqween** [comment]
for latest 1.11.2 version of the mod

**Comment by Prospector** [comment]
Aha! Thanks for that. A lot of people have said this and your the first to fuly explain it.

**Comment by ChubbyTurtle101** [comment]
I think this was one of the reason why Greg added Nickel Ore to Extreme Hills Biome.  It took some work and it was not wide spread so it just helped to get the Blast Furnace.  It might just be easier to add Nickel Ore than to redesign the progression steps.  Immersive Engineering adds Nickel so it is available in mod packs that includes IE at least for 1.10.2..

**Comment by Prospector** [comment]
GregTech 2 didn't add nickel though, and TR is based off of GT2. I will try to find which recipe is incorrect, because I know it was possible to make a blast furnace in GT2

**Comment by Prospector** [comment]
Small nickel dust can be made from an industrial centrifuge, which does not require steel. I will look into adding alternative ways to get nickel maybe though
