### ISSUE TITLE
Crash if loaded after AbyssalCraft

### ISSUE THREAD

**Issue by zTorden** [TechReborn/TechReborn#894]
TechReborn crashes on load, if loaded after AbyssalCraft. If i rename AbyssalCraft jar to ZAbyssalCraft - the load order is reversed and it loads just fine

https://openeye.openmods.info/crashes/ba9acae87c46a9e04735675733cc79f4

**Comment by modmuss50** [comment]
Uhh they are doing something weird with the ore dict. I will take a look

**Comment by modmuss50** [comment]
Someone somewhere is being stupid, that should fix the crash.
