### ISSUE TITLE
Crash on server load {1.11.2-2.0.9.25}

### ISSUE THREAD

**Issue by Nykorin** [TechReborn/TechReborn#895]
Server crashed on load when trying to load TechReborn mod, server is on Minecraft version 1.11 running latest Forge version. 

Link to crash log on [Pastebin](http://pastebin.com/4WniqzyG)

**Comment by Prospector** [comment]
May be linked to #894. @modmuss50 has there been a new build put out since you closed that issue?

**Comment by Prospector** [comment]
(oops didn't mean to close)

**Comment by Nykorin** [comment]
I can check if what they did works, but other than that, I suppose it will still need to be fixed

EDIT: That is using the latest version with RebornCore-1.11.2-2.12.0.7-universal.jar\
EDIT2: Well, the solution does seem to work (from #894). A bit strange to be honest. Never thought Minecraft had a load order system.

**Comment by Nerokinkage** [comment]
Well, the solution does seem to work. A bit strange to be honest. Never thought Minecraft had a load order system.

**Comment by modmuss50** [comment]
Yeah, I haven't been able to test the new version, I haven't pushed it to curse yet. I think I will do that later today.

**Comment by modmuss50** [comment]
Somemod is fucking with the ore dict, I should try and reproduce it and figure out what.

**Comment by modmuss50** [comment]
Can you test with the newest version?

**Comment by modmuss50** [comment]
Fixed update.
