### ISSUE TITLE
MFSU Doesn't Store Energy From Solar Panels When Reload World

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#897]
i placed 3 solar panels and connected them with copper cable to mfsu, it is charging okay, but if i disconnect (in singleplayer) and open my world again, it will not store energy **till i break a cable** and connect it to the same place again.
using 1.11.2 forge 2214 and latest techreborn

**Comment by ghost** [comment]
anyone has seen this? it is important in fact, if you built a good connection system that cables doesn't shown...

**Comment by Cendrb** [comment]
I had the same issue too. Try deleting TechReborn and RebornCore configs. That worked for me.

**Comment by VanDerGroot** [comment]
Seems my MFE stops working after reload. Breaking it (with wrench) and replacing it seems to fix the problem.
