### ISSUE TITLE
When MFSU Got 132000 RF It Get Back To -132000 RF on Server

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#898]
playing on my server, joined with client and placed 3 solar panels and connected them to mfsu. when mfsu reach to 132000 RF, it is being -132000 RF and repeats forever 
**(-132000 -131000 ...-1000 0 1000 ...131000 132000 -132000 -131000)**
using 1.11.2 forge 2216
edit: and it is not possible to see the energy stored in any machine via TheOneProbe. but in client(single player) i can see the energy of machines for example solar panel. i look solar panel i see stored RF in it. but **in server, it says "Error: TechReborn".**

**Comment by Ourten** [comment]
Is it doing that when you don't have the gui opened?

**Comment by ghost** [comment]
what you mean i didn't understand

**Comment by Ourten** [comment]
Does it happen without looking at the energy with the gui?

**Comment by ghost** [comment]
yes it happens. i waited 5 mins without looking on it or opening mfsu. i just looked to air and wait 5 mins and return it back its on -5000 etc

**Comment by Ourten** [comment]
Which version of TechReborn are you using?

**Comment by ghost** [comment]
1.11.2-2.0.9.25

**Comment by ghost** [comment]
i uploaded the true numbers. sorry if that's problem for you. it is 131something. i wrote 132000 rolled numbers.

**Comment by ghost** [comment]
any help? what should i do? maybe in reborncore config file? can i fix it or i must wait the new update? or i should install minecraft-flux mod or fluxed redstone mod or both? please help :((

**Comment by modmuss50** [comment]
Just wait, we cannot fix things instantly.

**Comment by Ourten** [comment]
Could you check if this issue is still present in the latest release of TechReborn?

**Comment by ghost** [comment]
okay its fixed. BUT there are no upgrade module place in machines. i was using overclocker upgrade, it was working. but now there are no upgrade module place in machines to put upgrades...

**Comment by modmuss50** [comment]
Upgrades are not in, there is no way it was working.

**Comment by ghost** [comment]
oh no, there are overclocker upgrade, i was using it on grinder and extractor...

**Comment by modmuss50** [comment]
they dont do anything. Unless someone added it and I didnt see.

**Comment by ghost** [comment]
overclocker upgrade was doing. it was increasing the speed of the machine, i was loving it...

**Comment by modmuss50** [comment]
well then I dont know sorry.

**Comment by ghost** [comment]
can you please add the upgrade module place to the machine gui in the next release please....

**Comment by Prospector** [comment]
The upgrades have never worked. I just removed the slots until we get them working. There's literally no way they could've been working.
