### ISSUE TITLE
Rockcutter doesn't actually have Silk Touch

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#90]
Enchantment is on it, doesn't work 
build 0.1.718

![2015-07-27_00 55 24](https://cloud.githubusercontent.com/assets/7843312/8894452/49736136-33fa-11e5-8483-e39aabb0919e.png)
![2015-07-27_00 55 21](https://cloud.githubusercontent.com/assets/7843312/8894453/499e5fb2-33fa-11e5-90c1-0c726c70ccd8.png)

**Comment by modmuss50** [comment]
The issue is that it only gets silk touch when crafted
