### ISSUE TITLE
[1.11] TechReborn crashes server upon start

### ISSUE THREAD

**Issue by shortybsd** [TechReborn/TechReborn#900]
Mc 1.11
Forge 2199
TechReborn-1.11.2-2.0.9.25-universal
RebornCore-1.11.2-2.12.0.7-universal

Server crashes with the following error upon startup:
http://pastebin.com/PSYgqxqF

**Comment by modmuss50** [comment]
Can you try updating to the newest versions please?

**Comment by shortybsd** [comment]
modmuss50, I will do it when I get home from work. Around 5pm CST I will push an update and let you know then. Thank you sir

**Comment by shortybsd** [comment]
Works good server side, no errors. Updating client and will test.

**Comment by shortybsd** [comment]
Works great client side as well, you sir are awesome and I thank you!
