### ISSUE TITLE
Rubber Wood Planks And Industrial Centrifuge Doesn't Shown In Inventory

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#903]
pink and black...pink and black.....
using game 1.11.2 forge 2216 tech reborn 2.1.0.32

**Comment by modmuss50** [comment]
Is this when placed in the world, or when you can see them in the inventory.

**Comment by ghost** [comment]
inventory.

**Comment by ghost** [comment]
validation? did you released a new version? i am following only on curseforge.
![validation](https://cloud.githubusercontent.com/assets/24831406/22066508/e22e20fa-dd95-11e6-9186-b632c5e3c3de.PNG)
![validation2](https://cloud.githubusercontent.com/assets/24831406/22066510/e380a680-dd95-11e6-8af5-d10084a383c3.png)

**Comment by VanDerGroot** [comment]
![minecraft_tr_rubberwoodplanks](https://cloud.githubusercontent.com/assets/10174815/22174798/f732af5e-dfe6-11e6-8f27-a57cfc563e2e.png)

Missing here as well. There are quite a few objects with this problem, but it doesn't feel like a huge problem to me.

**Comment by ghost** [comment]
hey modmuss, i can help about pixel art if you want. for items or blocks.

**Comment by modmuss50** [comment]
This is not an issue, it works fine for me and others. It must have been fixed.

**Comment by ghost** [comment]
no i didn't mention this issue, i just asked in general.
