### ISSUE TITLE
Some Of The Machines' Names And RF Powers, Ores' Names Doesn't Shown on Look-at GUI

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#904]
https://s24.postimg.org/bucm2uwth/solarpanel.png
https://s24.postimg.org/kbc4ds1id/grinder.png
https://s24.postimg.org/fo62c0e5h/generator.png
https://s29.postimg.org/wud7fwtbb/extractor.png
as you see in the picture... i can add more for other machines if you want.
using game 1.11.2 forge 2216 techreborn 2.1.0.32 and playing on my forge **server**.
using the one probe
i think **all the ores in mod**. (tin ore, copper ore, lead, silver etc..)

**Comment by modmuss50** [comment]
Is this still an issue!?

**Comment by ghost** [comment]
yes it is...

**Comment by ghost** [comment]
added 3 more machines...

**Comment by modmuss50** [comment]
it works fine in the inv right. If it does im closing this.

**Comment by ghost** [comment]
yes it does

**Comment by modmuss50** [comment]
We have tried to fix this a few times, and it still doesnt work. I dont know what we are doing wrong.

**Comment by ghost** [comment]
please add upgrade module places to machine gui... and also the problem that "reloading world-cable connection system doens't work" still happening and i'm breaking my cables and placing them again to solve it. please fix this

**Comment by modmuss50** [comment]
its not as easy as just "adding upgrade slots"

**Comment by ghost** [comment]
okay i know that is hard but **there were** upgrade slots. they are deleted in the new version. thanks... and do not forget the cable connection issue please..

**Comment by modmuss50** [comment]
I will forget if its posted here. The upgrade slots didnt even work.
