### ISSUE TITLE
There Is No Iridium Ore Spawn!

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#905]
iridium ore spawn are not available i think. on world generation. i generated the world with techreborn mod. i couldn't find any iridium ore so far. its so sad..............
1.11.2, forge 2216, latest tech reborn

**Comment by ghost** [comment]
and this means i must create a new world when new version released :(((((((((((((

**Comment by Prospector** [comment]
Are you sure? It's supposed to be very rare, but it also might be a bug.

**Comment by ghost** [comment]
im sure i didn't see any iridium ore........ i searched for it too much

**Comment by 0Navis0** [comment]
I'm not sure about it, but it could be normal, Iridium by default generates one cluster of 1 ore by chunks between 60 and 0 layers, so really rare to find. You can try to change the default settings for generating it more and bigger clusters by chunks.

**Comment by modmuss50** [comment]
the code is the same as all the other ores, its very rare so if you want turn up the config and see if that helps. If it is too rare we might change the defaults.
