### ISSUE TITLE
Can't See Saw Mill Recipes(machine uses)

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#906]
saw mill use recipes won't work on jei. (right clicking)
game 1.11.2 forge 2222 techreborn 2.1.0.32
**and same bug on recycler, scrapbox-inator,**

**Comment by Prospector** [comment]
I don't think there are any, which is the real bug here I think. And the other 2 are pretty self explanatory. Recycler consumes all items and scrapboxintor opens scrapboxes

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/TechReborn/pull/1039
