### ISSUE TITLE
RecipeRemover crash on latest build?

### ISSUE THREAD

**Issue by TheQuantumGeneral** [TechReborn/TechReborn#91]
Getting some IC2 RecipeRemover crash on .727

http://pastebin.com/Aa3XtMZJ

**Comment by YuRaNnNzZZ** [comment]
Got same crash on same build.
http://pastebin.com/ZmnneWNp

**Comment by modmuss50** [comment]
ok thanks for confirming, I will have a look now

**Comment by modmuss50** [comment]
It looks like my refactor to the recipe remover broke something. Its been reverted and should work now.
