### ISSUE TITLE
[1.10.2] Clicking the energy bar UI crashes the game

### ISSUE THREAD

**Issue by SeriousCreeper** [TechReborn/TechReborn#910]
TechReborn version 2.1.1.156
RebornCore version 2.13.1.104
Forge 12.18.3.2215

When i open a machine that has an energy bar and click on it, the game crashes. 

Crash report: http://pastebin.com/RWv1GBu2

Let me know if i can prove any additional info! 

Thanks,
SC

**Comment by modmuss50** [comment]
Will be fixed in the next RC build.
