### ISSUE TITLE
No Way To Build Blast Furnace and Industrial Grinder

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#911]
Industrial grinder wants **steel ingot** to build(in grinding head) and to get steel ingot, you need blast furnace. Blast furnace wants **nickel ingot**(cupronickel heating coil) but if you want to get nickel ingot, you need to smelt nickel dust which can be obtained by industrial grinder.
using game 1.11.2 forge 2216 TR 2.1.0.32

**Comment by Prospector** [comment]
This is like the 10th time this has been reported. *You can make it!*

Small Nickel Dust is made in the industrial centrifuge which does not require steel.
