### ISSUE TITLE
(suggestion) rubber plank slab, stair, fence, fence gate

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#912]
I just come back with this suggestion because I think it's something which really miss to TechReborn. Maybe now you have update it to 2.0 version, and added all the content you wanted and updated all the textures, you could think to add this feature. ;)

**Comment by modmuss50** [comment]
Closing this for 3 reasons:

1. I dont see a need? Just added bloat.
2. I tried to do it and spent an hour trying to get a fence gate working, so I rage quit an deleted the fence. I hadn't even got to the slabs.
3. You opened the same issue 7 months ago and we spoke about it there: https://github.com/TechReborn/TechReborn/issues/602

**Comment by modmuss50** [comment]
If someone else doesnt get aggravated by jsons and wants to add them feel free.
