### ISSUE TITLE
TechReborn causes wrong amounts of redstone in JEI recipes

### ISSUE THREAD

**Issue by ShelLuser** [TechReborn/TechReborn#914]
First thanks for all the effort into making this wonderful plugin! I'll share my findings later in a more appropriate place but yah, had to be said ;)

Ever since I started my "Technical Minecraft" experience (I collected my own set of "tech mods", including yours) I started to notice the wrong amounts of redstone (dust) being displayed in recipes. Even official ones, like the on for the clock which you can see here:

![2017-01-18_14 33 09](https://cloud.githubusercontent.com/assets/25201078/22066399/2319f0de-dd8d-11e6-94e1-eff3ec6f19fd.png)

At first I suspected something wrong in JEI, but when I checked out their issue overview I noticed a closed issue dealing with the same thing where they pointed at a plugin going wrong. I removed all my "tech plugins" and for sure: everything was back to normal. So then I re-added plugins one by one until I came to yours.

I didn't go as far as to check the situation with only the RebornCore, but my assumption was that the library is pretty passive and therefore this test wouldn't do much.

Hope this helps and that you can fix this!

**Comment by modmuss50** [comment]
What versions of the mods are you using, is this in 1.10 or 1.11?

**Comment by ShelLuser** [comment]
Yikes, talk about fast! :)

You're right, my bad:

RebornCore-1.11.2-2.13.0.12-universal
TechReborn-1.11.2-2.1.0.32-universal

There you go!

**Comment by modmuss50** [comment]
Ok thanks, I will take a look at this when I get a chance.

**Comment by Prospector** [comment]
It's the grinder recipe. Disabling it fixes thi. Not sure why it only happens with redstone though.

**Comment by modmuss50** [comment]
Ok, thanks that gives me some clue of where its happening

**Comment by modmuss50** [comment]
Was what I though it would be when you first told me @ProfessorProspector

**Comment by ShelLuser** [comment]
Thanks for the quick fix, it's all back to normal now!
