### ISSUE TITLE
Upgrade Slots on Machines

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#915]
they were deleted in new version of techreborn. reason: they not work. really? let's see.
this is the techreborn version 1.11.2 - 2.0.9.25

![upgrade](https://cloud.githubusercontent.com/assets/24831406/22067200/e5794192-dd98-11e6-8b50-d7f5aa6b8187.gif)
they **work**. at least they were. please add that slots again...
now you believe me @modmuss50 ?

**Comment by modmuss50** [comment]
I wasnt aware that they worked, I said I didnt think they worked.

**Comment by modmuss50** [comment]
And I wasnt the one that removed them, also please stop with the augmentative tone. They will be added back at some point.
