### ISSUE TITLE
crash on new version

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#918]
I get this crash when Minecraft load with the last TechReborn version on 1.10.2. http://pastebin.com/jpTx7S55

**Comment by modmuss50** [comment]
Update TechReborn and RebornCore

**Comment by 0Navis0** [comment]
Oh yeah sorry, I thought I had did, but after having checked, it hadn't did. Curse launcher wanted to troll me. Sorry for the useless issue. >__<
