### ISSUE TITLE
Unable to recharge electric tools in MFE

### ISSUE THREAD

**Issue by VanDerGroot** [TechReborn/TechReborn#919]
Electric tools (Diamond drill and Steel chainsaw tested so far) can't be dropped in the recharging slot in an MFE. They also don't appear to use power anymore. The chainsaw still cuts trees quickly. The drill does not cut quickly.

The tools do not have a meter or value showing amount of power like they did before the current update (2017-01-18).

**Comment by modmuss50** [comment]
I feel like the mixin system isnt working. Mind sending your full logs to me. And giving some more info.

**Comment by VanDerGroot** [comment]
Which files do you need?

I've been trying to understand the code for the mod so I can help out but it's a lot to take in when you have no experience with modding at all. :P

**Comment by modmuss50** [comment]
Do the items that should hold power have a tool bar, and have a tool tip with some power info. Are you also running in a dev env becuase that might explain it.

**Comment by VanDerGroot** [comment]
![minecraft_tr_drill](https://cloud.githubusercontent.com/assets/10174815/22174027/0765e8ea-dfd4-11e6-956d-0fd00db6d7a0.png)

No, not a dev environment. Just the regular forge client.

All previously electric items lack the energy bar and energy info on tooltip.

**Comment by modmuss50** [comment]
Ok, that means the mixin isnt being applied, I assume  you have the newest RebornCore, make sure you are using either: RebornCore-1.11.2-2.13.1.25-universal.jar or RebornCore-1.10.2-2.13.2.114-universal.jar

**Comment by VanDerGroot** [comment]
I'm using RebornCore-1.11.2-2.13.1.25-universal.

Is it fml-client-latest.log you have use for?

I found these lines in the file: 
[12:06:40] [Client thread/DEBUG] [RebornCore/]: Mod RebornCore is missing a pack.mcmeta file, substituting a dummy one
[12:06:40] [Client thread/DEBUG] [reborncore-MCMultiPart/]: Mod reborncore-MCMultiPart is missing a pack.mcmeta file, substituting a dummy one

Are they of interest?

**Comment by VanDerGroot** [comment]
Also found this in latest.log:

FMLFileResourcePack:TechReborn
[12:06:40] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: TechRebornItems.xcf in C:\Users\jimgr\AppData\Roaming\.minecraft\mods\TechReborn-1.11.2-2.1.1.42-universal.jar
[12:06:40] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: TechReborn.xcf in C:\Users\jimgr\AppData\Roaming\.minecraft\mods\TechReborn-1.11.2-2.1.1.42-universal.jar
[12:06:40] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: Casings.xcf in C:\Users\jimgr\AppData\Roaming\.minecraft\mods\TechReborn-1.11.2-2.1.1.42-universal.jar

**Comment by modmuss50** [comment]
Humm, I will need to check this.

**Comment by VanDerGroot** [comment]
Tell me if you need me to test something.

**Comment by modmuss50** [comment]
Humm, i loaded up the latest TR and RC in 1.11.2 and it works fine:

![javaw_2017-01-22_14-24-41](https://cloud.githubusercontent.com/assets/4324090/22183128/959efd38-e0ae-11e6-807b-a40b3d9f8042.png)

**Comment by VanDerGroot** [comment]
Even a new install of minecraft and the mods produces the same negative result here.

Same thing on wife's computer btw.

**Comment by modmuss50** [comment]
any chance you could send me the entire log file?

**Comment by VanDerGroot** [comment]
Sure. Where do I send it?

**Comment by modmuss50** [comment]
Gist if it will fit, Dropbox, Email (modmuss50@gmail.com)? what ever.

**Comment by VanDerGroot** [comment]
The files are in the mail.

**Comment by VanDerGroot** [comment]
Is this line interesting: 
[19:58:21] [main/ERROR] [FML/]: The coremod reborncore.mixin.implementations.forge.MixinForgeLoadingCore is requesting minecraft version 1.11.2 and minecraft is 1.11. It will be ignored.

As far as I can tell, forge only exists for up to 1.11.

**Comment by modmuss50** [comment]
thats you issue, there is a 1.11.2 version: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.11.2.html I should be able to fix this as well. But update.

**Comment by VanDerGroot** [comment]
Ah! That wasn't obvious from the forge website. Beta version? Anyway, updating.

**Comment by modmuss50** [comment]
I can fix this, to also work on 1.11

**Comment by VanDerGroot** [comment]
It works.  =)
