### ISSUE TITLE
Machine Hulls missing recipes

### ISSUE THREAD

**Issue by Johnsonmc** [TechReborn/TechReborn#92]
The below blocks are missing their recipes:
Aluminum Machine Hull
Iron Machine Hull
Bronze Machine Hull (spelled Brone in game)
Brass Machine Hull
Steel Machine Hull
Titanium Machine Hull

Versions used:
TechReborn 0.3.0.729
IC2 Exp 2.2.759
CodeChickenCore 1.0.7.46
NEI 1.0.5.111

**Comment by modmuss50** [comment]
We haven't got machine parts item to craft the hulls. Should it be added?

**Comment by TheQuantumGeneral** [comment]
If you do add it, the recipe it uses, as follows:
![cadpture](https://cloud.githubusercontent.com/assets/7843312/9087949/ff3a477c-3bd0-11e5-9e19-47fb1e587a02.PNG)

Is currently being used as a placeholder recipe for 360K helium coolant cells. 
![capture](https://cloud.githubusercontent.com/assets/7843312/9087960/0e168f8a-3bd1-11e5-95d0-a9ba3333a58e.PNG)

Kill two birds with one stone? :)

**Comment by modmuss50** [comment]
I will add it, and change the helium cell recipe.
