### ISSUE TITLE
Unable to add water to secondary slot in Industrial grinder

### ISSUE THREAD

**Issue by VanDerGroot** [TechReborn/TechReborn#920]
Industrial Grinder only accepts water (cells and buckets) in the primary slot.

**Comment by Prospector** [comment]
this is the most useless bug report.

Please give minecraft version, tech reborn version, reborn core version, forge version, and provide a screenshot because I have no idea what you mean by "primary slot"

**Comment by VanDerGroot** [comment]
Apologies. Not used to submitting bug reports. Mistakenly assumed everyone would be using the latest version available.



I'm using:
TechReborn-1.11.2-2.1.1.42-universal
RebornCore-1.11.2-2.13.1.25-universal

and also have jei_1.11.2-4.2.3.222 installed.

Minecraft version 1.11-forge.1.11-13.19.1.2189 (I assume this is what you need?)

![minecraftbug](https://cloud.githubusercontent.com/assets/10174815/22168989/018a557c-df71-11e6-97af-847c8d28b395.png)

The water containers (cells and buckets) are not accepted in the marked box. They are accepted in the one above it.

I hope this helps.

**Comment by Prospector** [comment]
Sorry, didn't mean for mine to sound so rude, just we've been getting quite a lot of poor bug reports recently. Use the top slot. The bottom slot there is where the empty cells will go after you empty them into the tank from the top slot.

**Comment by Prospector** [comment]
I'll make this more clear in the GUI soon

**Comment by VanDerGroot** [comment]
Will there be some sort of standard for how this will work in different machines?

**Comment by Prospector** [comment]
What do you mean?

**Comment by VanDerGroot** [comment]
It seems different machines work in different ways now. The saw mill for instance, takes water from the second slot. It would be useful to not need to keep switching between your work (smelting ore) and filling with water. This is how it worked before last update, btw.

**Comment by VanDerGroot** [comment]
The industrial grinder also doesn't have any other use for that second box. All recipes for it uses only one item. Edit: Well ok, it does have a use now as the exit box, but it would be better if it was in the previous version where the second box was the input for water. That let me have a hopper filled with water cells constantly refill it when needed.
