### ISSUE TITLE
Game freezes when I click on Centrifuge recipes in JEI

### ISSUE THREAD

**Issue by MarikCZ** [TechReborn/TechReborn#921]
When I looking for recipes in Centrifuge in JEI, game freezes and few minutes later crashes without crash-report.

**Comment by modmuss50** [comment]
Can someone check this?

**Comment by VanDerGroot** [comment]
Works on my machine.

**Comment by MarikCZ** [comment]
Right now my game freezes again. But when I click on "All-Items" tab in creative inventory - So the problem is somewhere else.

**Comment by MarikCZ** [comment]
Maybe in my old and slow machine... :D
