### ISSUE TITLE
Max energy for IDSU is negative

### ISSUE THREAD

**Issue by VanDerGroot** [TechReborn/TechReborn#922]
![minecraft_tr_idsu](https://cloud.githubusercontent.com/assets/10174815/22174492/44d2769c-dfe0-11e6-9803-2facf645e0b7.png)

TechReborn-1.11.2-2.1.1.42-universal
RebornCore-1.11.2-2.13.1.25-universal
jei_1.11.2-4.2.3.222

Minecraft version 1.11-forge.1.11-13.19.1.2189

**Comment by modmuss50** [comment]
fixed
