### ISSUE TITLE
Steel creation error.

### ISSUE THREAD

**Issue by HenrikMP** [TechReborn/TechReborn#923]
Hi,

I am runnning the latest build of TechReborn and Core.

It is not possible to create steel, without a blast furnance. But the furnance requieres a multibloch structure, which in turn requires steel to create Advanced machine blocks.

Please create a way to create steel or blast furnance without requring steel.

Thsanks,
Henrik

**Comment by VanDerGroot** [comment]
The blast furnace does not require steel. Advanced machine blocks require 2 carbon plates and 2 advanced alloy plates. None of these require steel.

**Comment by HenrikMP** [comment]
Thank You

**Comment by VanDerGroot** [comment]
No problem. :)
