### ISSUE TITLE
java.util.ConcurrentModificationException(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [TechReborn/TechReborn#924]
i was exploring my world why the generator filled up again and then got this crash
[crash-2017-01-22_07.42.16-server.txt](https://github.com/TechReborn/TechReborn/files/721477/crash-2017-01-22_07.42.16-server.txt)

RebornCore-1.11.2-2.13.1.25
TechReborn-1.11.2-2.1.1.42
forge:1.11.2-2223

**Comment by modmuss50** [comment]
Huh, that again.

**Comment by VanDerGroot** [comment]
I've had this a few times as well.

**Comment by modmuss50** [comment]
If you have it please report it :)

**Comment by VanDerGroot** [comment]
Wasn't sure it had to do with TR. Also, there are too many things for me to report all of them. I want to have *some* time to play. :P
