### ISSUE TITLE
MT issue with the rolling machine

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#928]
mods.techreborn.rollingMachine.removeRecipe(<minecraft:detector_rail>);
mods.techreborn.rollingMachine.removeRecipe(<minecraft:rail>);
mods.techreborn.rollingMachine.removeRecipe(<minecraft:detector_rail>);
mods.techreborn.rollingMachine.removeRecipe(<minecraft:activator_rail>);
mods.techreborn.rollingMachine.removeRecipe(<minecraft:golden_rail>);

Doesnt work

+ railcraft support

**Comment by drcrazy** [comment]
Not reproducible
