### ISSUE TITLE
Energy is not consumed

### ISSUE THREAD

**Issue by XuPuPG** [TechReborn/TechReborn#93]
If submit mechanism at least 1 unit of energy it can perform prescription indefinitely.For example: take batbox with 1 unit of energy,connected to the stove.The stove will take 1 energy and will be able to fry bars indefinitely without wasting energy

**Comment by modmuss50** [comment]
Has this got anything to do with TechReborn, it sounds like an issue with mekanism? A screen shot to show your setup would be helpful.

**Comment by XuPuPG** [comment]
well,1 point I will make a video

**Comment by XuPuPG** [comment]
My mods folder http://dl2.joxi.net/drive/0008/3299/560355/150805/c7beaf63b7.png
Video https://www.youtube.com/watch?v=ETq-iU1gfiQ&feature=youtu.be
forge version 10.13.4.1490

**Comment by modmuss50** [comment]
Thanks for that video, I will have a look now

**Comment by XuPuPG** [comment]
How to fix it:
https://github.com/TechReborn/TechReborn/blob/master/src/main/java/techreborn/powerSystem/TilePowerAcceptor.java#L245
put "!"

**Comment by gigabit101** [comment]
Seems like the on textures are broke again aswell @modmuss50

**Comment by modmuss50** [comment]
They might have been fixed because of the power issues, I will check.

**Comment by modmuss50** [comment]
They are broken again :(
