### ISSUE TITLE
Server Crash- after removing a mod that the alloy furnace was processing.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#931]
https://gist.github.com/ProsperCraft/8692d92ab3693df7712cd4fc48005635

I had a mod called allomancy, and I had copper and zinc in the alloy furnace when the server went down for update, the updated pack removed allomancy and the server crashed whenever this base was loaded.

I re-enabled the mod in client and server and started it back up and removed the ingots, then restarted both without allomancy and the server is happy now.

**Comment by modmuss50** [comment]
Uhh, I guess that needs fixing.

**Comment by modmuss50** [comment]
If its still broke, enable the forge config to remove crashing tiles.
