### ISSUE TITLE
Server Crash when wrenching a techreborn machine attached to a fluxed redstone energy conduit

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#933]
https://gist.github.com/ProsperCraft/99c2d0443324d535c23fb825ae3e45c3

If you wrench the machine the server crashes, if you break the fluxed redtone conduit, then wrench the machine it does not crash.

Versions in the crashlog.

**Comment by ProsperCraft** [comment]
Apparently its breaking anything connected to them, I was breaking my refined storage controller.
https://gist.github.com/ProsperCraft/9c76b735d4199f4bec0dae50e1d1f904

**Comment by modmuss50** [comment]
This is a fluxed redstone issue: https://github.com/modmuss50/Fluxed-Redstone/issues
