### ISSUE TITLE
[1.10.2] Minetweaker recipes not showing up in JEI

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#935]
All these versions are most recent available on the curse launcher at the time of this posting
JEI-1.10.2-3.14.3.403
Techreborn-1.10.2-2.1.2.160
RebornCore-1.10.2-2.13.2.114
Crafttweaker -1.10.2-3.0.17
Forge 2221

I've only tried a few different ones, but it seems that any MT machine recipes that I add won't show up in JEI after refreshing, but will still function correctly. I haven't taken a peek at the relevant code yet, but I suspect it's related to crafttweaker API updates (see [here](https://github.com/jaredlll08/CraftTweaker/issues/136) and [here](https://github.com/SonarSonic/Calculator/issues/202) for what seems to be a similar case)

**Comment by modmuss50** [comment]
Yeah, I think it has something to do with that as well. Im 90% sure the changes got in, but might have been left out of 2.0
