### ISSUE TITLE
Item dupe using recyclers

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#939]
TechReborn-1.11.2-2.1.1.42-universal

When you put a stack of cobble in the input slot and it starts making scrap, remove the scrap, and place anything in the output slot, and it increments that item.

I am not a coder, but I am guessing the code reads something like this- place scrap in output slot, increment output slot by 1.  

But because the output slot is accessible and not protected you can add anything to be incremented into the output slot.

**Comment by Ourten** [comment]
Closed in [1b08456](https://github.com/TechReborn/TechReborn/commit/1b084569accdfcfefc5910782ac19ab098f5566f)
