### ISSUE TITLE
Possibly change the refined iron recipe?

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/TechReborn#946]
Installed varied commodities the other day and turns out they have a furnace recipe that overrides your furnace recipe. The recipe is for iron to next metal type. Their recipe turns it to steel, your recipe turns it to refined iron. I suggested to them that they create a blast furnace as the interim step to produce the steel.

I'm thinking that ideally since you aren't calling yours steel, and because attaching carbon to iron makes steel (see: http://www.keenovens.com/articles/steel-furnance.htm), that there probably should be a grinding and filtering step to produce a refined iron powder that is finally smelted to produce refined iron.

**Comment by modmuss50** [comment]
What mod is causing the issue? I recommend you use a minetweaker recipe to fix this.

**Comment by kreezxil** [comment]
Varied Commodities. The only thing for 1.11.2 that can modify recipes is the Backpacks! mod. However, I removed varied commodoties because they had another issue where their steel ingot was somehow oredicted to bronze.

I still think there should be an interim recipe or step to get refined iron.

Cheers, still love your mod.

**Comment by Prospector** [comment]
Refined iron is supposed to be simple to get.

**Comment by Prospector** [comment]
I don't think this is our issue
