### ISSUE TITLE
TechReborn ores not generating in the beneath dimension [1.11.2]

### ISSUE THREAD

**Issue by megaloloful** [TechReborn/TechReborn#947]
i guess the title already describes it pretty good. I don't know if this is a problem on your side or on the beneath's so sorry if I reported it to the wrong authors.

**Comment by modmuss50** [comment]
Have you got a link to that mod?

**Comment by megaloloful** [comment]
https://mods.curse.com/mc-mods/minecraft/254629-the-beneath

**Comment by modmuss50** [comment]
https://github.com/Shinoow/The-Beneath/blob/master/src/main/java/com/shinoow/beneath/common/world/WorldProviderDeepDank.java#L58

I have a feeling its their issue as they are returning false on `isSurfaceWorld`  Unless im missing a way to know if I should spawn ores (Feel free to correct me)
