### ISSUE TITLE
Still Couldn't Find Any Iridium Ore

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#950]
playing for 3 months, created 5 worlds and still couldn't find any iridium ore. it got annoying now..

**Comment by Ourten** [comment]
Duplicate of #949

**Comment by ghost** [comment]
not duplicate... i say no iridium ore, he say no small vein ore...

**Comment by modmuss50** [comment]
It is, we spent a lot of time yesterday figuring it out.
