### ISSUE TITLE
Missing Texture in JEI

### ISSUE THREAD

**Issue by SpeedSlider** [TechReborn/TechReborn#952]
The following textures is missing in JEI using ATM2 Version 0.41 which currently is using the latest version of your mod.
-Heat Generator
-Compressed Air Source
-Electrolyzed Water Source
![2017-02-01_12 51 08](https://cloud.githubusercontent.com/assets/25437944/22519101/209ac126-e87d-11e6-8557-e37a2e8c4a99.png)

**Comment by drcrazy** [comment]
Heat generator removed, cells are fine in 1.12.1
