### ISSUE TITLE
Cells can't be converted to liquids

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#954]
TechReborn 2.1.3.164
Minecraft 1.10.2
Forge 12.18.3.2221

Any filled cells can't be converted into their liquid form in any way. Water or Mercury Cells don't work in the Industrial Grinder, I can't right click liquids into the world or into a tank. Other blocks that turn fluid containers into liquids like the EnderIO Fluid Tank or the Forestry Bottler don't work either.

**Comment by modmuss50** [comment]
Ok, yeah. That needs fixing.

**Comment by davqvist** [comment]
Hi, I released my modpack 2 days ago. Sorry if I sound like a jerk, but this is one of the 3 bugs I encountered that really heavily affects gameplay. I still released the modpack in hopes that at the time users would reach end game and unlock TechReborn the issue would be fixed. I would really appreciate it if you could have a look at this issue. Thanks in advance.

**Comment by Sese-Schneider** [comment]
@modmuss50 Hi. I'm such an user who reached end game now, and this bug sucks.. I spend hours building a complicated machine to convert rotten flesh to methane and now what? nothing works. thank you...
