### ISSUE TITLE
Machines use more power than they accept (EU)

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#955]
TechReborn 2.1.3.164
Minecraft 1.10.2
Forge 12.18.3.2221

I've only tried the Industrial Electrolyzer and Industrial Grinder, but have looked at the max power inputs of other machines and guessing something similar. The machines use may more EU than their max input is. Unless I'm missing something obvious you can't run those machines at a decent speed (or even max speed) if you use EU power. For example the Industrial Electrolyzer has a max input of 128 EU/t but definitely uses more. I've never played the old Gregtech but I am confused how this is supposed to work. The obvious solution would be to use Transformer Upgrades, but they are not implemented yet. The other option would be just to raise the max input levels. Please let me know if I missing something.

**Comment by davqvist** [comment]
Quick update. I noticed that the Electrolyzer can keep up when processing Ruby Dust but not when processing Bauxite Dust. So it obviously depends on the recipe. So I looked here: https://github.com/TechReborn/TechReborn/blob/1.10.2-backport/src/main/java/techreborn/init/recipes/IndustrialElectrolyzerRecipes.java#L36

and Ruby Dust needs 50 EU/t while Bauxite needs 128 EU/t. It seems to me that the Electrolyzer doesn't accept 128 EU, but more than 50 EU/t.

**Comment by davqvist** [comment]
Hi, I released my modpack 2 days ago. Sorry if I sound like a jerk, but this is one of the 3 bugs I encountered that really heavily affects gameplay. I still released the modpack in hopes that at the time users would reach end game and unlock TechReborn the issue would be fixed. I would really appreciate it if you could have a look at this issue. Thanks in advance.

**Comment by davqvist** [comment]
@modmuss50 As you just told me that you try fix some issue for 1.10. Can you please backport this to 1.10?

**Comment by modmuss50** [comment]
I can have a go at trying to fix some of the issues.
