### ISSUE TITLE
Helium Coolant recipe error

### ISSUE THREAD

**Issue by VanDerGroot** [TechReborn/TechReborn#956]
The helium coolant recipe is supposed to be 4x tin and 1x helium cell (line 231 in https://github.com/TechReborn/TechReborn/blob/45600ded324d3e574bc9c4181e675488c8fe9be6/src/main/java/techreborn/init/ModRecipes.java) but it accepts an empty cell instead of helium cell.

**Comment by Blizzor** [comment]
I can Agree. 
Here is another picture of that problem (https://pudding.tk/lZ9qHk0b.png)

**Comment by drcrazy** [comment]
Duplicate for #1043
