### ISSUE TITLE
TheOneProbe - Information TechReborn not displayed in multiplayer - please read - on end is reaction of author TheOneProbe

### ISSUE THREAD

**Issue by Umiyaki** [TechReborn/TechReborn#959]
Minecraft 1.11.2
Forge 13.20.0.2226
theoneprobe-1.1x-1.4.1.jar (installed on the server and client)
TechReborn-1.11.2-2.1.3.54-universal.jar
RebornCore-1.11.2-2.13.3.34-universal.jar

compare pictures: (singl/multiplayer)
https://justpaste.it/1328k

McJty commented 5 minutes ago
Report to TechReborn please. That is their bug
@McJty
Owner
McJty commented 4 minutes ago
Hint to them: they are most likely using client side code in their top handler. TOP handler is server side

**Comment by modmuss50** [comment]
Fixed.
