### ISSUE TITLE
Crashes when viewing crafting recipe

### ISSUE THREAD

**Issue by SnipeHub** [TechReborn/TechReborn#960]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RebornCoreASM (RebornCore-1.11.2-2.13.3.34-universal.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 2/2/17 8:22 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1104)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['driftgoat'/7254, l='MpServer', x=120.99, y=74.00, z=360.22]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (68,64,256), Chunk: (at 4,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6112226 game time, 6164310 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 115 total; [EntityPlayerSP['driftgoat'/7254, l='MpServer', x=120.99, y=74.00, z=360.22], EntitySkeleton['Skeleton'/9737, l='MpServer', x=153.50, y=16.00, z=298.50], EntityPainting['Painting'/176, l='MpServer', x=97.00, y=81.00, z=380.97], EntityCreeper['Creeper'/9748, l='MpServer', x=139.50, y=89.00, z=428.50], EntityPainting['Painting'/282, l='MpServer', x=119.00, y=87.00, z=326.03], EntityPainting['Painting'/283, l='MpServer', x=121.97, y=87.00, z=329.00], EntityPainting['Painting'/284, l='MpServer', x=126.03, y=83.00, z=324.50], EntityPainting['Painting'/286, l='MpServer', x=127.50, y=83.00, z=343.97], EntitySkeleton['Skeleton'/9760, l='MpServer', x=173.50, y=78.00, z=390.50], EntityZombie['Zombie'/9763, l='MpServer', x=198.50, y=84.00, z=343.50], EntityZombie['Zombie'/9766, l='MpServer', x=82.81, y=31.00, z=322.50], EntityPainting['Painting'/306, l='MpServer', x=121.00, y=76.50, z=363.97], EntitySkeleton['Skeleton'/9274, l='MpServer', x=102.50, y=100.00, z=386.50], EntityPainting['Painting'/361, l='MpServer', x=134.50, y=83.50, z=335.97], EntityPainting['Painting'/362, l='MpServer', x=130.50, y=82.50, z=330.03], EntityPainting['Painting'/363, l='MpServer', x=134.97, y=83.00, z=324.50], EntityPainting['Painting'/365, l='MpServer', x=130.50, y=82.50, z=335.97], EntityPainting['Painting'/367, l='MpServer', x=131.97, y=83.00, z=341.00], EntityPainting['Painting'/368, l='MpServer', x=129.50, y=83.00, z=343.97], EntitySkeleton['Skeleton'/9292, l='MpServer', x=149.50, y=20.00, z=288.50], EntityBat['Bat'/9812, l='MpServer', x=100.45, y=13.57, z=319.28], EntitySpider['Spider'/9836, l='MpServer', x=171.55, y=87.00, z=373.75], EntityCreeper['Creeper'/9327, l='MpServer', x=138.50, y=90.00, z=412.50], EntityBat['Bat'/9847, l='MpServer', x=198.58, y=23.76, z=298.83], EntityChicken['Chicken'/139, l='MpServer', x=55.21, y=73.00, z=289.48], EntityPig['Pig'/141, l='MpServer', x=45.01, y=67.00, z=298.47], EntitySkeleton['Skeleton'/9874, l='MpServer', x=58.50, y=106.00, z=385.50], EntityPig['Pig'/7318, l='MpServer', x=72.77, y=101.00, z=416.51], EntityChicken['Chicken'/150, l='MpServer', x=66.57, y=75.00, z=287.13], EntityZombie['Zombie'/9884, l='MpServer', x=175.83, y=37.00, z=353.50], EntitySpider['Spider'/9897, l='MpServer', x=55.75, y=64.00, z=426.76], EntityPainting['Painting'/176, l='MpServer', x=97.00, y=81.00, z=380.97], EntitySkeleton['Skeleton'/9912, l='MpServer', x=129.50, y=14.00, z=373.50], EntitySkeleton['Skeleton'/9913, l='MpServer', x=118.50, y=14.00, z=376.50], EntitySkeleton['Skeleton'/9914, l='MpServer', x=119.50, y=14.00, z=377.50], EntitySkeleton['Skeleton'/9915, l='MpServer', x=129.50, y=14.00, z=374.50], EntitySkeleton['Skeleton'/9916, l='MpServer', x=194.50, y=63.00, z=284.50], EntityZombie['Zombie'/9917, l='MpServer', x=117.50, y=16.00, z=332.74], EntityCreeper['Creeper'/9918, l='MpServer', x=63.50, y=72.00, z=418.50], EntityPig['Pig'/7361, l='MpServer', x=183.48, y=62.31, z=426.45], EntitySkeleton['Skeleton'/9931, l='MpServer', x=96.50, y=16.00, z=315.50], EntityZombie['Zombie'/9421, l='MpServer', x=42.50, y=64.00, z=422.50], EntityEnderman['Enderman'/9423, l='MpServer', x=155.48, y=79.00, z=356.59], EntitySkeleton['Skeleton'/9939, l='MpServer', x=108.50, y=17.00, z=348.50], EntitySkeleton['Skeleton'/9940, l='MpServer', x=108.50, y=17.00, z=349.50], EntitySkeleton['Skeleton'/9948, l='MpServer', x=157.50, y=32.00, z=391.50], EntitySkeleton['Skeleton'/9949, l='MpServer', x=155.50, y=32.00, z=392.50], EntitySkeleton['Skeleton'/9950, l='MpServer', x=155.50, y=32.00, z=393.50], EntityZombie['Zombie'/9951, l='MpServer', x=158.50, y=32.00, z=390.50], EntitySkeleton['Skeleton'/9963, l='MpServer', x=135.50, y=15.00, z=383.50], EntityZombie['Zombie'/9463, l='MpServer', x=92.50, y=105.00, z=367.50], EntitySpider['Spider'/9468, l='MpServer', x=160.50, y=78.00, z=353.50], EntityCreeper['Creeper'/9980, l='MpServer', x=176.50, y=78.00, z=321.20], EntityCreeper['Creeper'/9981, l='MpServer', x=178.50, y=78.00, z=322.50], EntityItem['item.item.egg'/9470, l='MpServer', x=165.69, y=78.00, z=337.96], EntitySkeleton['Skeleton'/9982, l='MpServer', x=179.30, y=79.00, z=326.49], EntityBat['Bat'/9476, l='MpServer', x=135.68, y=14.08, z=332.13], EntityZombie['Zombie'/9989, l='MpServer', x=108.50, y=22.00, z=395.50], EntityBat['Bat'/10000, l='MpServer', x=199.66, y=46.00, z=369.25], EntityPainting['Painting'/282, l='MpServer', x=119.00, y=87.00, z=326.03], EntityBat['Bat'/10010, l='MpServer', x=177.53, y=37.65, z=357.12], EntityPainting['Painting'/283, l='MpServer', x=121.97, y=87.00, z=329.00], EntityPainting['Painting'/284, l='MpServer', x=126.03, y=83.00, z=324.50], EntityItemFrame['entity.ItemFrame.name'/285, l='MpServer', x=126.50, y=81.50, z=342.97], EntityPainting['Painting'/286, l='MpServer', x=127.50, y=83.00, z=343.97], EntityItemFrame['entity.ItemFrame.name'/287, l='MpServer', x=126.03, y=82.50, z=340.50], EntityItemFrame['entity.ItemFrame.name'/288, l='MpServer', x=126.03, y=81.50, z=340.50], EntityItemFrame['entity.ItemFrame.name'/289, l='MpServer', x=126.03, y=83.50, z=338.50], EntityItemFrame['entity.ItemFrame.name'/290, l='MpServer', x=126.03, y=82.50, z=338.50], EntityItemFrame['entity.ItemFrame.name'/291, l='MpServer', x=126.03, y=81.50, z=338.50], EntityItemFrame['entity.ItemFrame.name'/292, l='MpServer', x=126.03, y=82.50, z=337.50], EntitySquid['Squid'/9509, l='MpServer', x=132.54, y=61.92, z=316.17], EntityItemFrame['entity.ItemFrame.name'/294, l='MpServer', x=120.03, y=76.50, z=357.50], EntityItemFrame['entity.ItemFrame.name'/295, l='MpServer', x=120.03, y=75.50, z=357.50], EntityItemFrame['entity.ItemFrame.name'/296, l='MpServer', x=120.03, y=74.50, z=357.50], EntityItemFrame['entity.ItemFrame.name'/297, l='MpServer', x=120.03, y=76.50, z=359.50], EntityItemFrame['entity.ItemFrame.name'/298, l='MpServer', x=120.03, y=75.50, z=359.50], EntityItemFrame['entity.ItemFrame.name'/299, l='MpServer', x=120.03, y=74.50, z=359.50], EntityItemFrame['entity.ItemFrame.name'/300, l='MpServer', x=120.03, y=76.50, z=361.50], EntityItemFrame['entity.ItemFrame.name'/301, l='MpServer', x=120.03, y=75.50, z=361.50], EntityItemFrame['entity.ItemFrame.name'/302, l='MpServer', x=120.03, y=74.50, z=361.50], EntityItemFrame['entity.ItemFrame.name'/303, l='MpServer', x=120.03, y=76.50, z=363.50], EntityItemFrame['entity.ItemFrame.name'/304, l='MpServer', x=120.03, y=75.50, z=363.50], EntityItemFrame['entity.ItemFrame.name'/305, l='MpServer', x=120.03, y=74.50, z=363.50], EntityPainting['Painting'/306, l='MpServer', x=121.00, y=76.50, z=363.97], EntityBat['Bat'/10036, l='MpServer', x=118.64, y=16.59, z=299.60], EntityBat['Bat'/9527, l='MpServer', x=166.55, y=37.15, z=364.55], EntitySkeleton['Skeleton'/10040, l='MpServer', x=155.50, y=27.00, z=325.50], EntityCreeper['Creeper'/10042, l='MpServer', x=118.81, y=27.00, z=403.54], EntitySkeleton['Skeleton'/10045, l='MpServer', x=78.70, y=19.00, z=285.70], EntitySkeleton['Skeleton'/10049, l='MpServer', x=124.49, y=55.00, z=423.22], EntityZombie['Zombie'/10054, l='MpServer', x=182.50, y=72.00, z=293.50], EntityCreeper['Creeper'/9550, l='MpServer', x=147.46, y=88.00, z=417.31], EntityZombie['Zombie'/10069, l='MpServer', x=82.21, y=103.00, z=406.54], EntityZombie['Zombie'/9563, l='MpServer', x=145.50, y=85.00, z=383.50], EntityCreeper['Creeper'/7524, l='MpServer', x=113.84, y=98.00, z=335.60], EntityBat['Bat'/10088, l='MpServer', x=158.36, y=26.27, z=352.40], EntityPainting['Painting'/361, l='MpServer', x=134.50, y=83.50, z=335.97], EntityPainting['Painting'/362, l='MpServer', x=130.50, y=82.50, z=330.03], EntityPainting['Painting'/363, l='MpServer', x=134.97, y=83.00, z=324.50], EntityItemFrame['entity.ItemFrame.name'/364, l='MpServer', x=132.50, y=81.50, z=334.97], EntityPainting['Painting'/365, l='MpServer', x=130.50, y=82.50, z=335.97], EntityPainting['Painting'/367, l='MpServer', x=131.97, y=83.00, z=341.00], EntityPainting['Painting'/368, l='MpServer', x=129.50, y=83.00, z=343.97], EntityFallingBlock['Falling Block'/396, l='MpServer', x=149.50, y=18.50, z=285.50], EntityMinecartChest['Minecart with Chest'/397, l='MpServer', x=151.28, y=16.00, z=290.99], EntityChicken['Chicken'/422, l='MpServer', x=166.50, y=78.00, z=338.21], EntitySpider['Spider'/9140, l='MpServer', x=164.41, y=76.00, z=320.63], EntityZombie['Zombie'/9144, l='MpServer', x=150.50, y=12.00, z=308.50], EntityZombie['Zombie'/9659, l='MpServer', x=45.57, y=112.00, z=393.25], EntityPig['Pig'/447, l='MpServer', x=185.83, y=79.00, z=319.17], EntityBat['Bat'/9674, l='MpServer', x=162.75, y=25.10, z=319.21], EntityBat['Bat'/9704, l='MpServer', x=54.24, y=27.63, z=334.29], EntityBat['Bat'/9708, l='MpServer', x=169.76, y=13.24, z=441.55], EntityBat['Bat'/9714, l='MpServer', x=113.32, y=21.03, z=300.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 301036168 bytes (287 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2226 Optifine OptiFine_1.11.2_HD_U_B6 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJA	forge{13.20.0.2226} [Minecraft Forge] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJA	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCHIJA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJA	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCHIJA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJA	reborncore{2.13.3.34} [RebornCore] (RebornCore-1.11.2-2.13.3.34-universal.jar) 
	UCHIJA	reborncore-mcmultipart{2.13.3.34} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.3.34-universal.jar) 
	UCHIJA	techreborn{2.1.3.54} [TechReborn] (TechReborn-1.11.2-2.1.3.54-universal.jar) 
	UCHIJA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
RebornCoreASM (RebornCore-1.11.2-2.13.3.34-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.49' Renderer: 'GeForce GTX 670/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2226
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.49, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz

**Comment by modmuss50** [comment]
Remove optifine
