### ISSUE TITLE
Blast Furnace blows up at 128 EU/t

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#962]
TechReborn 2.1.4.172
Minecraft 1.10.2
Forge 12.18.3.2221

I connected an IC2 MV-Transformer and IC2 Copper Cables to a Blast Furnace and it blew up, tried with CESU instead of MV-Transformer and same result. LV-Transformer and Tin Cables worked. But of course this means the Blast Furnace is really slow because I calculated the recipes in JEI and it needs 120 EU/t. So I guess there is somewhere configured a wrong number that contradicts the tooltip.

**Comment by Pwnacillin** [comment]
TechReborn 2.1.10.207
Minecraft 1.10.2
Forge 12.18.3.2254
Pack: FTB Beyond 1.2

The above bug is present in Infinity beyond as well with the Industrial grinder - even a single Thermal Generator will cause it to explode. Tried a CESU connected directly and this also causes an explosion. Only work around seems to be stacking Batboxes with copper cable. Even a CESU with copper cable will cause an explosion.

**Comment by davqvist** [comment]
Hi, I released my modpack 2 days ago. Sorry if I sound like a jerk, but this is one of the 3 bugs I encountered that really heavily affects gameplay. I still released the modpack in hopes that at the time users would reach end game and unlock TechReborn the issue would be fixed. I would really appreciate it if you could have a look at this issue. Thanks in advance.

**Comment by davqvist** [comment]
@modmuss50 As you just told me that you try fix some issue for 1.10. Can you please backport this to 1.10?
