### ISSUE TITLE
Quantum Tank / Mekanism Brine error

### ISSUE THREAD

**Issue by Zuiq** [TechReborn/TechReborn#963]
Forge: 12.18.3.2202
Core:  2.8.2.69
Tech: 2.1.2.160

When i have brine in the tank and try to open the UI, i get the following error.

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(21446) + length(2) exceeds writerIndex(21446): UnpooledHeapByteBUf(ridx: 21446, widx: 21446, cap: 21446/21446)

https://puu.sh/tN433/30b2789173.png

**Comment by modmuss50** [comment]
Need the log please

**Comment by modmuss50** [comment]
Closing as no log provided + link is dead. Reopen if still an issue in 1.12.2
