### ISSUE TITLE
Has the quantum chest/tank been removed from the latest  versions?

### ISSUE THREAD

**Issue by Staegrin** [TechReborn/TechReborn#964]
Using TechReborn-1.10.2-2.1.4.172-universal

The quantum chest and tank do not show up in JEI. Nor is there a use for platinum which was needed for making the quantum tank if I remember correctly.

There is a digital chest but no uses for it in crafting.

I do have QuantumStorage-1.10.2-3.2.19 installed as well which also uses recborncore. Not sure if this is relevant.

**Comment by modmuss50** [comment]
It's hidden when QS is installed.

**Comment by Staegrin** [comment]
Thanks, I went through the mod page and the config for both techreborn and Quantumstorage and couldn't find a mention of this.

**Comment by modmuss50** [comment]
I should add a config
