### ISSUE TITLE
[1.11.2] Grinder will not accept input from the sides, or pull from the sides.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#967]
Grinder will not accept input from the sides, or pull from the sides.

TechReborn-1.11.2-2.1.3.54-universal

**Comment by drcrazy** [comment]
Duplicate for #1103

**Comment by ProsperCraft** [comment]
For the record I was the original not the duplicate :)

**Comment by drcrazy** [comment]
#1103 is more generic. I believe nobody will wait till users will report each and every machine )
