### ISSUE TITLE
Quantum / Digital chest crashes

### ISSUE THREAD

**Issue by HardwareAccelerated** [TechReborn/TechReborn#971]
In the latest version of tech reborn I ran into issues with the quantum chest. After I put a stack of something inside it says that the quantum chest is holding a stack. However when I try to put items in again my game crashes, also using refined storage I could not put anymore than a stack of one item into a quantum chest.  The game would also freeze whenever I tried to load the same world again. Here is a [crash log](http://pastebin.com/D3VeLPuZ) and a [short clip](https://www.dropbox.com/s/3pfiy5n3vvv880b/2017-02-08-0141-19.mp4?dl=0).

**Comment by drcrazy** [comment]
Not reproducible in 1.12
