### ISSUE TITLE
Crash when typing "ax" into search box 1.11.2 TR 2.1.3.54

### ISSUE THREAD

**Issue by jjjworley** [TechReborn/TechReborn#974]
After installing your mod, when I open my inventory and search for ax, the game crashes.

**Comment by modmuss50** [comment]
Need the crash log

**Comment by ghost** [comment]
you need to update optifine. to B7

**Comment by modmuss50** [comment]
Closing this as it sounds like you have optifine, provide a log and I might be able to help.
