### ISSUE TITLE
Wiki suggestion (getting started).

### ISSUE THREAD

**Issue by ShelLuser** [TechReborn/TechReborn#976]
First: I actually read ;)  I visited the forums but they're closed, I went over Muss' Curse profile and noticed several comments wrt comments ("_please open an issue_") as such...  yah :)  Sorry if this is out of place, I honestly don't know where to put this.

I'm commenting on this: https://wiki.techreborn.ovh/doku.php?id=getting_started

"The generator uses a solid fuel type to generate a small amount of power. You will need to get your self some cables to transfer the power between blocks."

May I suggest:

"Please note that if you're using generators from other mods then this can affect balance in gameplay. Some generators might use other energy types which may either be over or under powered.

The first machines you might want to look into building are the electronic furnace and the grinder. If you place these next to the generator you first build you won't even have to worry about power distribution because the generator automatically powers blocks which are directly next to it.

The electronic furnace will allow you to smelt much more items using the same resources. For example: 1 piece of coal will smelt 9 blocks in a regular furnace, 10 in an iron furnace and an easy whole stack (and more!) in an electric furnace powered by a generator.

The grinder allows you to grind ores into dust which you can then smelt back into ingots. One ore block gets you two dust, one one dust can be smelted back into an ingot. Effectively giving you a good way to double your mined ingots."

Just a suggestion of course, but I really think you should give the wiki some love too, never underestimate the importance of documentation to help players get started.

**Comment by drcrazy** [comment]
Done
