### ISSUE TITLE
[1.10.2] Some valid recipes are uncraftable?

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#977]
Tech Reborn-1.10.2-2.1.5.178
RebornCore-1.10.2-2.13.4.128
Forge 2221

I've been working on a new modpack that includes TechReborn and we've been encountering an issue lately where certain items are uncraftable even though they have recipes. When we put the ingredients in a vanilla crafting table it will show the output as expected, but once we try to grab it, it will dissapear out of our "hand" and back into the crafting table output slot, making it impossible to actually grab the input. At first I was only able to replicate this issue on our server, but someone just reported to me that this happened to them on single player as well. 

Now, I understand that most likely this has nothing to do with you guys, but I just figured i'd report it here because it has only happened with items from tech reborn and i'm not sure who else to ask about it.

**Comment by modmuss50** [comment]
Do you have any recipe changing mods? What recipes exactly? Whats your mod list? Is there anything to note in either the client or server logs?
