### ISSUE TITLE
No documentation for industrial sawmill

### ISSUE THREAD

**Issue by ManMan36** [TechReborn/TechReborn#979]
I have no idea how to use the industrial sawmill. No matter what multiblock I give it, it says that it is wrong. I have looked at Greg tech wikis and those don't work either. I am sorry if this isn't the right place for this question but I can't find any documentation on this machine.

**Comment by modmuss50** [comment]
Added the wiki label as thats where it should go.

**Comment by Prospector** [comment]
this is also a bug though, there's not even JEI recipes for it

**Comment by drcrazy** [comment]
It is there now.
https://wiki.techreborn.ovh/doku.php?id=blocks:saw_mill
