### ISSUE TITLE
Compressors do not progress on turning Carbon Mesh into Carbon Plate (progress bar stays at 0%)

### ISSUE THREAD

**Issue by epharian** [TechReborn/TechReborn#982]
Running version with file name: TechReborn-1.11.2-2.1.6.76-universal.jar.  Running forge 13.20.0.2226.

In both single player creative and survival multiplayer on a locally hosted server, Carbon Mesh will insert into the proper slot of a Compressor, but does not convert into Carbon Plate.  Machine is fully powered.  Cannot progress to higher-level machines without this.  

![2017-02-20_11 37 24](https://cloud.githubusercontent.com/assets/5552107/23134156/c553f26c-f761-11e6-9fdb-6561365df503.png)

List of mods installed:
Mystical Agriculture (by BlakeBr0)
Chance Cubes (by turkey2349)
Advanced Generators (by bdew)
Just Enough Items (JEI) (by mezz)
Ore Excavation (by Funwayguy)
BdLib (by bdew)
Logical Drops (by EM3R50N)
Clay Bucket (by abecderic)
Colossal Chests (by kroeser)
JourneyMap (by techbrew)
Cyclops Core (by kroeser)
Hwyla (by TehNut)
Minecraft-Flux (by SH3VEK)
EnderTanks (by ShetiPhian)
Inventory Tweaks (by Kobata)
Persistent Bits (by oitsjustjose)
UndergroundBiomesConstructs (by Zeno410)
Pipes (by CrafterKina)
Waila Harvestability (by squeek502)
ShetiPhianCore (by ShetiPhian)
Substratum (by EXTER7)
Advanced Shulkerboxes (by EuhDawson)
RebornCore (by modmuss50)
Refined Storage (by raoulvdberge)
TechReborn (by modmuss50)
Hopper Ducts (by FyberOptic)

**Comment by epharian** [comment]
Extractors are having a similar issue with rubber wood (logs), JEI reports they should pull out rubber.

**Comment by modmuss50** [comment]
https://modmuss50.me/shots/java_2017-02-23_13-13-00.png

**Comment by modmuss50** [comment]
Working fine for me, in dev.

**Comment by modmuss50** [comment]
The other mod fixed it
