### ISSUE TITLE
[1.10.2]/[1.11.2] Some kind of incompatibilities with Forge Energy System

### ISSUE THREAD

**Issue by ParaMotor** [TechReborn/TechReborn#984]
After Progressive Automation's last update ([1.10.2] supporting FE), I played around a bit with both Mods (TechReborn and Progressive Automation). I found out, that if the Generators are directly connected to the machines, they can transfer the power. Cables and Energy Storage Blocks wont transfer Power, cables don't connect to these machines. This seems to happen with all Mods using Forge Energy System. Using other power transfer options (like Fluxed Redstone), it works - they connect to the Energy Storage Blocks, Machines from TR, Machines from other mods (but they do some strange things with the power - I managed to drain 50 million FE out of an empty machine and put it into a MSFU, but this is another issue) and transfer the Power. (Tested with following Mods: 1.10.2 Progressive Automation/1.11.2 Actually Addition)

Using 1.10.2: forge 12.18.3.2234, 1.10.2-2.1.6.180, ProgressiveAutomation-1.10.2-1.7.0
          1.11.2: forge 13.20.0.2230, TechReborn 1.11.2-2.1.6.76, ActuallyAdditions-1.11.2-r102

**Comment by modmuss50** [comment]
Our cables dont work with other power systems atm

**Comment by Prospector** [comment]
Condensed into #1038
