### ISSUE TITLE
[1.10.2] Unable to locate/use the Pump

### ISSUE THREAD

**Issue by HybridAir** [TechReborn/TechReborn#986]
I have been looking for any mods in my personal modpack that include fluid pumping machines. When going through this repo, I found references to a Pump in the code. I asked Modmuss50 on the TeamReborn Discord server about it, and they said that pumps have been implemented. While I do not have much experience with Minecraft mod code in particular, I found that the pump block is not listed inside ModBlocks.java along with all the other machines. I think I have reasonable suspicion to think that this is why I am unable to find any reference to it in game. I am running TechReborn 1.10.2-2.1.6.186, RebornCore 1.10.2-2.13.4.128, and Forge 1.10.2-12.18.3.2185. I can provide any additional information as necessary.

**Comment by modmuss50** [comment]
Its not done, it will come back once its read.
