### ISSUE TITLE
GUIs are client-side

### ISSUE THREAD

**Issue by Eufranio** [TechReborn/TechReborn#988]
At the moment, the GUI of the TechReborn's machines are client side. That means that the GUIs don't wait for any server-side check to see if the client can really open the machine, it opens imediately. I would like to suggest that you delay a bit the opening of the GUIs, waiting for the server green signal to the client finally open the GUI, like other mods do.

**Comment by modmuss50** [comment]
I have known about this for a while, as it allows bypassing of mods that try to protect blocks.
