### ISSUE TITLE
About repost license

### ISSUE THREAD

**Issue by TehporP** [TechReborn/TechReborn#99]
Hey Modmuss50
As you can see the GT5 is too hard to play.It makes a lot of player feel bored.And GT6 is intertsting....but it is still not done yet! When I tell my friend about the TechReborn. They are really intertsted in it! But GFW block thier way to download! For those reason,I would request A license form you to REPOST this mod to the biggest minecraft forum in China(we called it MCBBS)

REPOST means:
1.Clarified origin author name which is YOU(I just a "reposter")
2.Clarified origin URL link could reach TechReborn official web/Curse Forge directly
3.Obey EULA with no conditions
4.Never re-compile/re-package/re-distribute this mod
5.A free/AD-free Chinese net-disk download link to boost download speed(No cent could be earn)

**Comment by modmuss50** [comment]
If this were to happen would the file be hosted by us or by this website?

**Comment by TehporP** [comment]
you mean the mod file?

**Comment by modmuss50** [comment]
If you were to repost this mod on this forum would the file still be downloaded from curse forge? Or would the file be re-uploaded to another website?

**Comment by TehporP** [comment]
curse forge  
but just in case I will re-uploaded the file for the player which have very poor download speed(Because of the fucking GFW :( )

**Comment by modmuss50** [comment]
I will talk to the other team members about this first, just to make sure.

**Comment by TehporP** [comment]
ok I‘ll wait

**Comment by modmuss50** [comment]
That should do, or if you want to add a list of all of us you can.

Tech Reborn team : Modmuss50, Gigabit101, Tntrololol, Joflashstudios, Mattabase, Johnodagiant, Mine_Sasha

**Comment by TehporP** [comment]
hummm I will do that   And If your teammate agree my request ,just tell me Thanks

**Comment by modmuss50** [comment]
Yes that should be fine. :)

**Comment by TehporP** [comment]
Thanks!
