### ISSUE TITLE
Missing textures in 1.10

### ISSUE THREAD

**Issue by DeadSix27** [TechReborn/TechReborn#994]
Version: `TechReborn-1.10.2-2.1.6.180-universal.jar`

![image](https://cloud.githubusercontent.com/assets/1492505/23584684/b7b819ec-0168-11e7-8961-6a75488b1e39.png)

![image](https://cloud.githubusercontent.com/assets/1492505/23584789/f115de56-016b-11e7-9e52-17f5c345fb29.png)

Diesel, Nitrodiesel and some other things have missing textures.

![image](https://cloud.githubusercontent.com/assets/1492505/23589766/cd535f3a-01d3-11e7-90e7-49ad8a48b9a1.png)

Saw this: https://github.com/TechReborn/TechReborn/issues/817
But that says its fixed in V2, which I am using.. or not? TechReborn-1.10.2-**_2.1.6_**.180-universal.jar.

**Comment by modmuss50** [comment]
Should be fixed in newer versions.
