### ISSUE TITLE
Issue with JEI and steel

### ISSUE THREAD

**Issue by Adissaric** [TechReborn/TechReborn#996]
I'm running with JEI and can't find anyway to make steel. According to JEI the only way to get steel ingots is in the blast furnace with steel dust. You can only get steel dust through either grinding a steel ingot or combining four small piles of steel dust. You can only get the small piles through steel dust. The issue here is that either there is a problem with how jei is finding recipes or there is no way to get steel. I'm assuming that it is the former and would appreciate the recipe for steel. 
Thanks,
Adissaric

**Comment by drcrazy** [comment]
Hi Adissaric, 

You can make steel in blast furnace using iron ingots and coal dust. Recipe is in JEI for both 1.11.2 and 1.10.2

WBR,
drcrazy

**Comment by modmuss50** [comment]
Update the mod.
