### ISSUE TITLE
[1.10.2] plutonium fuel rods not accepted in ic2 reactor

### ISSUE THREAD

**Issue by Alessandro404** [TechReborn/TechReborn#997]
as in the title, the rods in techreborns are not seen as valid items in ic2 reactors.
Using last version TechReborn-1.10.2-2.1.6.180-universal

**Comment by Alessandro404** [comment]
Adding something else: the three tiers of reflector, similarly, are not accepted.

**Comment by modmuss50** [comment]
I dont think im going to do this, as the logic behind it is quite complex, and I dont really understand how the new? ic2 reactor works. If someone else wants to add this please feel free.

We may add our own reactor in the future
