### ISSUE TITLE
[1.10.2] Several items and machines are not removed when playing with "Remove Duplicates when IC2 is installed"=true

### ISSUE THREAD

**Issue by Alessandro404** [TechReborn/TechReborn#998]
Here a list:
the TR rubber sapling is still  seen in JEI, when placed is a full pink block that grow into a TR rubber tree. It should be removed altogheter, i guess?

Some machines are still there:
the water mill, semifluid generator, wind mill, 
I guess machine blocks and casing area okay

Same with some items:
Enegy crystals, treetaps and electric treetap, chainsaws (maybe in this case is better to mantain them, since there are more tiers? Maybe removing the recipe for the original), same for the drills, nanosaber.

**Comment by Alessandro404** [comment]
adding something else. 
reflectors, in all three variants

**Comment by modmuss50** [comment]
Ok, our tree taps work on ic2 and are better (put into inv not spurting out) The reflectors need to be fixed though.
