### ISSUE TITLE
[1.10.2] LESU not outputting energy

### ISSUE THREAD

**Issue by Alessandro404** [TechReborn/TechReborn#999]
The LESU central block accept energy normally, but seems to be unable to output anything. Tried to place ic2 cables (not the TR cables, i have the option to remove overlapping items) on every side of the block, still nothing. 
Using a lever for redstone signal, still nothing.

**Comment by Leftorius** [comment]
same in 1.11.2 (TechReborn-1.11.2-2.1.6.76-universal)

**Comment by The-Admiral** [comment]
Also having this issue
